### ISSUE TITLE
Which open source licence?

### ISSUE THREAD

**Issue by c3iq** [OpenDevin/OpenDevin#10]
Which open source licence?

I don't have an opinion but feel the project should have a licence before people contribute.

**Comment by jjfantini** [comment]
That's what I was thinking. Then it keeps people from spinning off their own entities to use `OpenDevin` for profit.

💪🏼💪🏼

**Comment by djaym7** [comment]
Commercial may bring funding, real open source licenses are apache 2.0, MIT, etc

**Comment by asadm** [comment]
If we go with a non-commercial license:
- many will not contribute at all, since it's not open source in true sense
- commercial folks will just reimplement ideas here, LoC vs. impact is pretty low in genAI world, will take a weekend to replicate ideas
- this repo will be left behind.

**Comment by jjfantini** [comment]
those are good points, points for MIT, apache 2.0

**Comment by jjfantini** [comment]
or will OpenDevin replicate itself and then leave us behind 👀

**Comment by realsnick** [comment]
@devinhalladay i'm pretty sure GPL 3.0 allows commercial use... None of the "open source licenses" prohibit commercial use... Personally i'm against OSI and all of their "approved" licenses. 

I do believe that OpenDevin needs to be protected from corporates aka commercial use for obvious reasons...Just look at what happen with OpenAI and other non-profit open source projects ... I submitted a PR per @lauesa suggestion of Attribution-NonCommercial 4.0 International.

**Comment by neubig** [comment]
Personally, I agree with @asadm . I would prefer a real open-source license. MIT, BSD, Apache. Restrictions on use are against the spirit of the open-source movement.

**Comment by m-a-sch** [comment]
Not a lawyer here, but who would 1) grant the license and 2) pay the fees due to those who came up with the original ideas of "Devin"?

**Comment by hannibalhuang** [comment]
> Not a lawyer here, but who would 1) grant the license and 2) pay the fees due to those who came up with the original ideas of "Devin"?

nobody needs to grant the license, it is decided by the open source team. The "fees" depends upon what patent the original Devin has filed and what royalty of the guarantees.

That said I also agree that MIT or Apache 2.0 or BSD 3.0 are good choices, any of them would do. Apache 2.0 are more commercial friendly to some extent

**Comment by huybery** [comment]
Thanks for the discussion, more people think the MIT license is a better fit for OpenDevin, I'll merge the #8.
