### ISSUE TITLE
'action' key is not found in action={'thought':....

### ISSUE THREAD

**Issue by sercanerhan** [OpenDevin/OpenDevin#1000]
#### Describe the bug

While using with `ollama/llama2` and running the open devin with `make run`, after it receives my first prompt, it throws below error:
```bash
"'action' key is not found in action={'thought': <agent's prompt text>
```

#### Setup and configuration
**Current version**:

```bash
commit 9846e242994a9a88786f8bdba525e080d70ae072 (HEAD -> main, origin/main, origin/HEAD)
Author: Robert Brennan <accounts@rbren.io>
Date:   Wed Apr 10 14:48:40 2024 -0500

    Fix logger import (#985)
    
    * fix logger import
    * fix mypy version
    * make mypy happy (#994)
```

I'm running on `macos M1, conda virtual env with python 3.11`
**My config.toml and environment vars** :
```toml
LLM_MODEL="ollama/llama2"
LLM_API_KEY="ollama"
LLM_BASE_URL="http://localhost:11434"
LLM_EMBEDDING_MODEL="local"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model: llama2
* Agent: -

**Commands I ran to install and run OpenDevin**:
```
git pull 
conda create -n opendevin python=3.11
make build
make setup-config
make run
```

**Steps to Reproduce**:
1. Land on the open devin web client on localhost:3001
2. give your prompt (i.e. a simple web page that shows hello world text.)
3. Track the terminal and see  `Step 0...` has printed
4. *_bug appears_* receive the error message
 
**Logs, error messages, and screenshots**:
Error outout on the terminal is:

```log
STEP 0

PLAN:
simple web page that shows hello world text.

ERROR:
"'action' key is not found in action={'thought': 'How can I structure my code to make it easy to read and maintain?'}"
Traceback (most recent call last):
  File "<my_path>/OpenDevin/opendevin/controller/agent_controller.py", line 135, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<my_path>/OpenDevin/agenthub/monologue_agent/agent.py", line 217, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<my_path>OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 158, in parse_action_response
    return action_from_dict(action_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<my_path>OpenDevin/opendevin/action/__init__.py", line 33, in action_from_dict
    raise KeyError(f"'action' key is not found in {action=}")
KeyError: "'action' key is not found in action={'thought': 'How can I structure my code to make it easy to read and maintain?'}"
23:57:15 - opendevin:ERROR: agent_controller.py:113 - Error in loop
Traceback (most recent call last):
  File "<my_path>/OpenDevin/opendevin/controller/agent_controller.py", line 111, in start_loop
    finished = await self.step(i)
               ^^^^^^^^^^^^^^^^^^
  File "<my_path>/OpenDevin/opendevin/controller/agent_controller.py", line 135, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<my_path>/OpenDevin/agenthub/monologue_agent/agent.py", line 217, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<my_path>/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 158, in parse_action_response
    return action_from_dict(action_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<my_path>/OpenDevin/opendevin/action/__init__.py", line 33, in action_from_dict
    raise KeyError(f"'action' key is not found in {action=}")
KeyError: "'action' key is not found in action={'thought': 'How can I structure my code to make it easy to read and maintain?'}"

```

#### Additional Context

<img width="495" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/3420568/ec950ab8-b83b-4504-8597-1c552492c603">

**Comment by rbren** [comment]
This is very strange.

The error itself is expected--the LLM returned an invalid action. But it should have recovered.

We do `step()` in a `try` block [here](https://github.com/OpenDevin/OpenDevin/blob/cc584445c68dd158905793b1e97e1936710e59c9/opendevin/controller/agent_controller.py#L135)

We can see in the logs that we hit the `except` [here](https://github.com/OpenDevin/OpenDevin/blob/cc584445c68dd158905793b1e97e1936710e59c9/opendevin/controller/agent_controller.py#L141)

But it still gets `raised` [here](https://github.com/OpenDevin/OpenDevin/blob/cc584445c68dd158905793b1e97e1936710e59c9/opendevin/controller/agent_controller.py#L144)

And now I see the issue: the `or` for that raise is wrong! Fix incoming

**Comment by lowlyocean** [comment]
This printout looks similar to the one reported in https://github.com/OpenDevin/OpenDevin/issues/864 . Wonder if cause is related?

**Comment by roafhtun** [comment]
I am having the same problem, is there a fix yet ?

**Comment by enyst** [comment]
> I am having the same problem, is there a fix yet ?

Yes, it's fixed. Please update with ```git pull``` and run ```make build```. If you still experience problems, please open a new issue on that.
