### ISSUE TITLE
Task testing / Evaluation.

### ISSUE THREAD

**Issue by arthurwolf** [OpenDevin/OpenDevin#1006]
Follow up from issue #/993 

In that issue I gave some examples of tasks I'd like OpenDevin to be able to do, that were a bit too advanced for it (or more likely current LLM) 's abilities.

That got me to thinking how I could help with making sure somewhere in the project, those capabilities are remembered/targeted for, and from there I got to unit testing / evaluation sets.

What if, for each of the tasks I described (and many others), there was a test of "tests" that can be run, and that determine if OpenDevin is capable of doing those tasks or not. Something a bit like unit tests, or an evaluation harness (think «HumanEval» but for coding agents).

(Ignoring for now how difficult that is to implement), the way (I imagine) that'd work is: 

1. You think of a new thing you want OD to do.
2. You write a test for that thing, which consists of:

 * a. An input: prompt/instructions, «what to do», files for an existing project OD must modify, documentation gathered from links provided by the user, etc.
 * b. An output: a finished project that correctly follows the instructions requested, that can be "compared" to the output of OD during testing. A web page, a library file, etc.
 * c. A set of "acceptance criteria": A list of questions that must be answered in the positive when looking at the output of the test (some based on common sense, some based on previously observed errors in the output), like "does it return a string and not a number", "does it check for errors in the HTTP call", "does it have a timeout option in the config file".

4. With all that information in hand, you run the test.
5. If the test succeeds, great, you now know Devin is capable of doing these things.
6. If the test does not succeed, then you look at *how* it failed, and you have learned information about what must be improved, and maybe even how to improve it.

Does that sound like a good idea?

It's very much like the evaluation harnesses used to test/«rate» LLMs currently ( like SWE-bench), but more finely-grained, more in-tune with what users would actually want to do with OD ( SWE-bench is only "fix these random github issues", it's good as a metric, but not necessarily as a guide ) and with more options to actually work on solving specific issues.

I searched the OD code, issues and PR and couldn't find anything like that.

Now, it's not actually as straightforward as writing unit tests for a library. We're talking about tests for an agent/LLM. Things are "fuzzier" in a way, not as deterministic.

BUT there is a great tool to work around that: LLMs!

You can use LLMs at pretty much all the steps of writing the test:

1. For the input, you can imagine a task, then have a LLM actually write the request/prompt and the "started project" that the agent must modify. Or you do it by hand if it's small enough, or can't be done by a LLM.
2. For the output, you ask OD to do it, see how far it gets, and then what it can't do, you do yourself.
3. For the evaluation criteria, they can help with writing them too, as well as with "having ideas" of what to test for and how.

But that's not where LLMs are most important/helpful for this.

Where they are most helpful is in actually testing the evaluation criteria.

When running the test, for each evaluation criteria, you use a LLM to test it.

To run a test, you do this, in order:

1. Take the input (instructions, existing files), and feed it to OD.
2. Get the tested output (finished project) that OD produced for this input (this is different from the "static" output pre-defined in the test definition, that is the "ideal" output that is known to work well).
3. For each "evaluation criteria" in the set of criteria, you use a LLM to test it. For example, if the criteria is « does it read the facebook API key from the .env file », you give a LLM the tested output that OD generated for this input, and you ask that LLM « in the code I am providing you, does it read the facebook API key from the .env file ». And the LLM will tell you YES or NO (or maybe... LLMs are like that. but we can work with that...).
4. Optionally, we can even have an LLM (with a large context window) compare the "tested output" to the "static output", and ask that LLM if they are functionally identical/similar.

With all of this, we are able to actually test if OD is able to «do» a given project or not. 

Not just that, but we can test if it's able to do specific tasks inside that project or not.

So with enough of these, we can say "today's OD codebase is able to pass 334 out of 893 evaluation tasks".

That lets you check for regressions (OD getting worse because of some change you made).

But most importantly, it gives you clear ways to test if some solution you implemented actually fixes a problem / improves OD.

Does all this sound like a good idea?

Now I understand this is a lot of work. I'd be interested in doing *some*/most of this, but I'm not familiar with the project yet, so I would likely have a few questions along the way. I'd do most of what I can to figure it out myself. And I'd start with very simple tasks ( «write a library in python that adds two numbers» ). I'd follow any instructions about "how" to implement it, what format to store the test info in, how to execute it, how to call OD, etc.

Another important factor here I believe, is that this evaluation harness would be useful for projects that are not OD, but also for other projects like Devika etc. This means **potentially**, they (there are like a dozen at this point) could also participate in it, and help move the test harness along faster (if you guys are open to that sort of collaboration).

I'm hoping I'm not wasting anyone's time, sorry if I'm being too enthusiastic, maybe this is just something for the far future, or you consider it not useful.

I'll shut up now and see if anyone thinks something about it.

Cheers.

PS: I'd be extremely surprised if (closed)Devin, and other agent startups like them, **did not** do exactly this, internally...

**Comment by rbren** [comment]
I think this is related to https://github.com/OpenDevin/OpenDevin/issues/341

**Comment by arthurwolf** [comment]
> I think this is related to #341

I went over #341 , and I'm not sure it's related (at least not closely).

I'm talking about running tests that would require calling LLMs, like when running a LLM benchmark or test harness.

That ticket is more about "classical" regression testing where you like, make sure your server still answers on the right port, etc.

**Comment by rbren** [comment]
#341 is about testing LLM-generated code, which I think is what you're after here. E.g. we have a task like "write a bash script that prints hello to greet.sh", and then a `test.sh` that runs `./greet.sh | grep hello`, and we make sure it exits non-zero.

Is that kind of what you're looking for?
