### ISSUE TITLE
Make Run - Sqlite Incorrect Version

### ISSUE THREAD

**Issue by ArtisticMusician** [OpenDevin/OpenDevin#1011]
#### Setup and configuration
**Current version**:

```bash
```

**My config.toml and environment vars** (be sure to redact API keys):
LLM_MODEL="ollama:dolphincoder"
LLM_API_KEY=""
LLM_EMBEDDING_MODEL="llama2"
LLM_BASE_URL="http://localhost:3000/v1/"
WORKSPACE_DIR="./workspace"

Envirunment  Vars

DISPLAY=:0
SHLVL=1
NVM_CD_FLAGS=
XDG_RUNTIME_DIR=/run/user/1000/
WSLENV=
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/home/josh/.local/bin:/home/josh/.nvm/versions/node/v20.12.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/:/mnt/c/Program Files/CMake/bin:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/:/mnt/c/Program Files (x86)/Microsoft SQL Server/150/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/150/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/150/DTS/Binn/:/mnt/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit/:/mnt/c/Program Files/ACE Studio:/mnt/c/Users/josh/Anaconda3:/mnt/c/Users/josh/Anaconda3/Scripts:/mnt/c/Users/Josh/Documents/00-AIAIO/Fooocus/python_embeded/Scripts:/mnt/c/Program Files/wkhtmltopdf/bin:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Users/Josh/anaconda3:/mnt/c/Users/Josh/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Josh/App:/mnt/c/Users/Josh/AppData/Local/Programs/Ollama:/mnt/c/Users/Josh/.bun/bin:/mnt/c/Users/Josh/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
NVM_BIN=/home/josh/.nvm/versions/node/v20.12.1/bin
HOSTTYPE=x86_64
PULSE_SERVER=unix:/mnt/wslg/PulseServer
```toml
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
```

**Steps to Reproduce**:
1.Followed the instruction up to make run command. 
2.
3.

**Logs, error messages, and screenshots**:

**Comment by rbren** [comment]
@ArtisticMusician can you add some more info? What are the log messages you're seeing about sqlite?

**Comment by rbren** [comment]
Should be fixed with the new docker installation method!
