### ISSUE TITLE
cannot create user for docker?

### ISSUE THREAD

**Issue by fenixlam** [OpenDevin/OpenDevin#1014]
#### Describe the bug

Looks like the apps is trying to create user group for docker in ssh_box.py, 
so the system cannot create agent. But my docker work. 

#### Setup and configuration
**Current version**:
commit 51b3ae56c75d3f00bc717849e43a600e54b9683d (HEAD -> main, origin/main, origin/HEAD)
Author: PierrunoYT <95778421+PierrunoYT@users.noreply.github.com>
Date:   Thu Apr 11 04:59:46 2024 +0200

    Add German Translation (#851)
    
    * Update index.ts
    
    * Update translation.json
    
    * Update index.ts
    
    * Remove comment and ident JSON
    
    ---------
    
    Co-authored-by: Jim Su <jimsu@protonmail.com>

```bash
```

**My config.toml and environment vars** (be sure to redact API keys):
```
  GNU nano 6.2                                                       config.toml                                                                 
LLM_MODEL="experiment26"
LLM_API_KEY="no-key"
LLM_EMBEDDING_MODEL=""
LLM_BASE_URL="http://localhost:5001/v1/"
WORKSPACE_DIR="./workspace"

```

**My model and agent** (you can see these settings in the UI):
* Model: dolphin-2.8-experiment26-7b-Q8_0.gguf
* Agent: koboldcpp 1.62
* OS: ubuntu 22.04 LTS

**Commands I ran to install and run OpenDevin**:
```
make build
make run
```

**Steps to Reproduce**:
1. after make run, open localhost:3001
2. website show"
Error creating controller. Please check Docker is running using `docker ps`.
Initializing agent (may take up to 10 seconds)...
3.

**Logs, error messages, and screenshots**:
Running the app...
Starting backend server...
Waiting for the backend to start...
The currently activated Python version 3.10.9 is not supported by the project (^3.11).
Trying to find and use a compatible version. 
Using python3.11 (3.11.0)
/root/.cache/pypoetry/virtualenvs/opendevin-g9zpds2K-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/root/.cache/pypoetry/virtualenvs/opendevin-g9zpds2K-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/root/.cache/pypoetry/virtualenvs/opendevin-g9zpds2K-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_group_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/root/.cache/pypoetry/virtualenvs/opendevin-g9zpds2K-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/root/.cache/pypoetry/virtualenvs/opendevin-g9zpds2K-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
INFO:     Started server process [82377]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
Backend started successfully.
Starting frontend with npm...

> opendevin-frontend@0.1.0 start
> vite --port 3001

  VITE v5.2.8  ready in 697 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
INFO:     ('127.0.0.1', 48108) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIzN2E5YTI5MS1hZmQ5LTRlYzYtYTNmNi0wMjMyMmNhMjJiOGEifQ.sv6fRrl8J9Gj3gGDCRRgHh0hHoiXN3VP8HIgY0CpiEM" [accepted]
Starting loop_recv for sid: 37a9a291-afd9-4ec6-a3f6-02322ca22b8a, False
INFO:     connection open
INFO:     127.0.0.1:48124 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:48114 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     127.0.0.1:48118 - "GET /configurations HTTP/1.1" 200 OK
INFO:     127.0.0.1:48130 - "GET /refresh-files HTTP/1.1" 200 OK
15:20:15 - opendevin:INFO: ssh_box.py:65 - Using workspace directory: /home/jacky-sgi/program/OpenDevin/workspace
15:20:15 - opendevin:INFO: ssh_box.py:280 - Container stopped
15:20:17 - opendevin:INFO: ssh_box.py:315 - Container started
15:20:18 - opendevin:INFO: ssh_box.py:331 - waiting for container to start: 1, container status: running
15:20:19 - opendevin:ERROR: manager.py:133 - Error creating controller.
Traceback (most recent call last):
  File "/home/jacky-sgi/program/OpenDevin/opendevin/server/agent/manager.py", line 124, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/jacky-sgi/program/OpenDevin/opendevin/controller/agent_controller.py", line 86, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/jacky-sgi/program/OpenDevin/opendevin/controller/command_manager.py", line 22, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/home/jacky-sgi/program/OpenDevin/opendevin/sandbox/ssh_box.py", line 84, in __init__
    self.setup_user()
  File "/home/jacky-sgi/program/OpenDevin/opendevin/sandbox/ssh_box.py", line 123, in setup_user
    raise Exception(
Exception: Failed to create opendevin user in sandbox: b'useradd: UID 0 is not unique\n'

#### Additional Context
Looks like the apps is trying to create user group for docker in ssh_box.py, but my docker work.

> docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS         PORTS     NAMES
cd492ac95f4c   ghcr.io/opendevin/sandbox   "/usr/sbin/sshd -D -…"   8 minutes ago   Up 8 minutes             sandbox-37a9a291-afd9-4ec6-a3f6-02322ca22b8a

**Comment by SleepyHitman** [comment]
I had it too last night but I can't remember exactly how I got over it, it was right before I went to sleep and I was exhausted.
I wrote just to say that it happened to me too and if I remember anything I'll try to add it here.

**Comment by enyst** [comment]
Please add SANDBOX_TYPE="exec" in the config.toml. It should work with it. Maybe restart docker if needed.

If you still have problems, feel free to let us know in a new issue.

**Comment by fenixlam** [comment]
I remember I have added that SANDBOX_TYPE="exec" in the config.toml before, but it raises an error that line 6 is unexpected.

**Comment by PierrunoYT** [comment]
> "exec" with quotes, not without?

Yes with quotes like the other lines in the config.

**Comment by fenixlam** [comment]
Ok, I try SANDBOX_TYPE="exec" and make build again. This time it works (at least not saying cannot load docker). Unlucky litellm didn't support local server, even I add the LLM_BASE_URL="http://localhost:5001" or 5001/v1/
