### ISSUE TITLE
pexpect.pxssh.ExceptionPxssh: password refused

### ISSUE THREAD

**Issue by userandpass** [OpenDevin/OpenDevin#1018]
#### Describe the bug

self.ssh.login(hostname, username, self._ssh_password, port=2222)
raise ExceptionPxssh('password refused')
pexpect.pxssh.ExceptionPxssh: password refused

#### Setup and configuration
**Current version**:

```bash
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
```

**Steps to Reproduce**:
1.
2.
3.

**Logs, error messages, and screenshots**:

**Comment by rbren** [comment]
Try setting `SANDBOX_TYPE=exec` in your config.toml or environment. We're working on a longer-term fix

**Comment by rbren** [comment]
Going to close this as we have a lot of these, but feel free to ping this thread if that doesn't work
