### ISSUE TITLE
No JSON Found/ unexpected keyword argument

### ISSUE THREAD

**Issue by davidceka** [OpenDevin/OpenDevin#1026]
#### Describe the bug
Hi, installed the new version, all is well configured and starts with no errors. Problem is, whenever I try to run a task, it fails on a "no JSON Found" error (see image), or a " got an unexpected keyword argument '2'"

#### Setup and configuration
**Current version**:

```bash
```

**My config.toml and environment vars** (be sure to redact API keys):
LLM_MODEL="ollama/llama2"
LLM_API_KEY=""
LLM_EMBEDDING_MODEL="llama2"
LLM_BASE_URL="http://localhost:11434"
WORKSPACE_DIR="./workspace"
SANDBOX_TYPE="exec"

**My model and agent** (you can see these settings in the UI):
* Model: llama2
* Agent:

**Commands I ran to install and run OpenDevin**:
make build
make start-backend
make start-frontend

**Steps to Reproduce**:
1. "write a python script to sum up the first 10 numbers"
2. wait for it to give the error

**Logs, error messages, and screenshots**:
![image](https://github.com/OpenDevin/OpenDevin/assets/90139776/fbb99549-c6b5-4bdc-8571-20fef27c1fc2)
![image](https://github.com/OpenDevin/OpenDevin/assets/90139776/67aee2c9-570e-4f0f-ac24-d04e4a198918)
![image](https://github.com/OpenDevin/OpenDevin/assets/90139776/082a5b5f-8c8c-48b4-9a88-e5a5838abcf3)
![image](https://github.com/OpenDevin/OpenDevin/assets/90139776/093f7fa6-76d4-456b-b87a-a9b57be39f60)

**Comment by flavioTocca** [comment]
I have the same issue, I think it's due to insufficient hardware power, I have a 3060ti, but when the requests start the gpu goes to 100%, what do you have as a gpu? if you can try and confirm that the hypothesis is correct

**Comment by Syzygy2048** [comment]
I don't think it's performance issues.

If you query the ollama directly does it have similar issues?

I'm on an RTX 2080, trying with different LLM models, ollama/codellama and ollama/codegemma:instruct) and when query ollama directly it's fast and has no issues. Only in the OD interface does it mess up like that.

**Comment by davidceka** [comment]
> I don't think it's performance issues.
> 
> 
> 
> If you query the ollama directly does it have similar issues?
> 
> 
> 
> I'm on an RTX 2080, trying with different LLM models, ollama/codellama and ollama/codegemma:instruct) and when query ollama directly it's fast and has no issues. Only in the OD interface does it mess up like that.
> 
> 
> 
> 

Querying ollama the model answers with no problems, that's why I doubted the performance issue; but I may be wrong. Its not super fast answering but it does

**Comment by flavioTocca** [comment]
querying ollama individually obviously does not cause problems as it will respond when it is finished, whereas opendevin, having many more requests, continues but the response has not yet arrived as the load is too high, if you keep the ollama terminal open you will see the json not found error corresponds to ollama's calls that did not respond correctly (maybe I'm wrong), also because I see some strange things in ollma's logs like: " msg":" total time = 582.20 ms " this is only a small part of the requests made to ollama for 11 steps, but in any case it should be something solvable, let's hope they take it into consideration

![totalTimeMsg](https://github.com/OpenDevin/OpenDevin/assets/64084046/f0394274-3eab-4d85-a369-1c7db0747bd4)

![logOllama](https://github.com/OpenDevin/OpenDevin/assets/64084046/e87fe020-beb7-4142-b13d-bc4a6403e7cc)

**Comment by rbren** [comment]
This is a typical issue with underpowered models. GPT-4 and Claude work best.

The Agent will try to recover, and will send an error message back to the LLM so it can correct. But sometimes it doesn't

Not much we can do about this unfortunately--it's up to the underlying LLM. Going to close this one

**Comment by Syzygy2048** [comment]
What does underpowered model mean?

codegemma should be state of the art as far as open source/local models goes.

I’m generating 50 token/s which doesn’t seem much slower than ChatGPT 4.

If that is underpowered, we might as well remove ollama and local models from the feature list and readme.

**Comment by rbren** [comment]
I'm not particularly familiar with codegemma

I'm actually not sure that code-fine-tuned models are the best to work with here, because we're asking the LLM to do all sorts of things other than coding (e.g. planning, summarizing, etc)

They'll probably work better when we have a multi-agent setup
