### ISSUE TITLE
Integration of Azure OpenAI

### ISSUE THREAD

**Issue by JLJuradoDeloitte** [OpenDevin/OpenDevin#1027]
**What problem or use case are you trying to solve?**
I am developing an application that leverages the capabilities of OpenAI for AI-driven content generation and interaction. Currently, my application uses the simple OpenAI API, but I am looking to enhance its capabilities by integrating Azure OpenAI. This integration would allow my application to take advantage of Azure's advanced features, such as improved scalability, security, and compliance with specific regulatory requirements.

**Describe the UX of the solution you'd like**
The ideal solution would allow developers to easily switch between the simple OpenAI API and Azure OpenAI within the OpenDevin project. This could be achieved through a configuration setting or an environment variable that specifies the API endpoint to be used. The user experience should remain consistent, with minimal changes required in the application code to switch between the two APIs.

**Do you have thoughts on the technical implementation?**
Based on the examples provided in the Azure OpenAI documentation, integrating Azure OpenAI into the OpenDevin project would involve modifying the API client to support Azure's specific authentication and endpoint requirements. This could include adjusting the base URL to point to Azure's OpenAI service and ensuring that the API key and other necessary headers are correctly set for Azure's API.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by enyst** [comment]
Thanks for the request! I think this should work already. We use LiteLLM for support of Azure and many other providers.
https://docs.litellm.ai/docs/providers/azure

If you set the environment variables as documented above, does it work?

**Comment by VishalHaibatpure1** [comment]
@enyst Looks like few changes are required in OpenDevin to support Azure OpenAI. 
I was able to run OpenDevin with below changes+hacks 

1. While creating litellm instance, API_Version param is not passed. I had to add few lines in llm.py to support this (Ref screenshot-1 below)

2. It looks like OpenDevin expecting two models: Chat completion (gpt-35-turbo) and embedding (text-embedding-ada-002
). But config.toml allows only one deployment name. In Azure each model requires its own deployment (this does not apply in case of pure OpenAI as it only works based on Key and does not require deploymentname). If we just give "gpt-35-turbo" model and deployment name then it will start throwing "embedding operation does not work with specified model" and vise versa. 
For this I had to do below changes
- LLM_EMBEDDING_MODEL param is used to detect embedding strategy from different provider and it expects the value "azureopenai" in Azure case. Here I had to define new config "LLM_EMBEDDING_DEPLOYMENT_NAME" and update this value in config.toml with "text-embedding-ada-002" model deployment name. I had to update multiple files Config.py, memory.py and MakeFile to define and use this new config along with LLM_EMBEDDING_MODEL. 


Screenshot-1 (Changes to fix API_Version issue)

![image](https://github.com/OpenDevin/OpenDevin/assets/126610431/3b2729d7-e975-496b-b2e3-96856fba4541)

ScreenShot-2 (config.toml with new deployment param for Embedding model)
![image](https://github.com/OpenDevin/OpenDevin/assets/126610431/72ae543a-a5fc-4909-ad84-e3d278ce5ae1)

ScreenShot-3 (addition of Embedding deployment config in config.py  )
![image](https://github.com/OpenDevin/OpenDevin/assets/126610431/c8e8e090-035b-492f-ad3d-0d58519c8014)

![image](https://github.com/OpenDevin/OpenDevin/assets/126610431/deb50382-7889-4120-a3d8-f2ff2f5add59)

ScreenShot-4 (changes in MakeFile)
![image](https://github.com/OpenDevin/OpenDevin/assets/126610431/7a384426-62db-452a-b9d2-4cc83f041c66)

ScreenShot-5 (Referring Embedding deployment in memory.py)
![image](https://github.com/OpenDevin/OpenDevin/assets/126610431/eef8ec1e-3a5f-4e69-a918-fc950d17b971)

**Comment by LeoYoungChina** [comment]
what is wrong with my config.toml ? why running into the errors:
![1](https://github.com/OpenDevin/OpenDevin/assets/15046431/b3327619-46a8-4ac4-a807-cb573d1171c9)
![2](https://github.com/OpenDevin/OpenDevin/assets/15046431/deeac25d-f5cd-41d8-9adf-7b51fa4a4892)

**Comment by enyst** [comment]
@JLJuradoDeloitte @VishalHaibatpure1 Added documentation for Azure: https://github.com/OpenDevin/OpenDevin/pull/1035

Feel free to comment, correct or add to it!

**Comment by LeoYoungChina** [comment]
> **What problem or use case are you trying to solve?** I am developing an application that leverages the capabilities of OpenAI for AI-driven content generation and interaction. Currently, my application uses the simple OpenAI API, but I am looking to enhance its capabilities by integrating Azure OpenAI. This integration would allow my application to take advantage of Azure's advanced features, such as improved scalability, security, and compliance with specific regulatory requirements.
> 
> **Describe the UX of the solution you'd like** The ideal solution would allow developers to easily switch between the simple OpenAI API and Azure OpenAI within the OpenDevin project. This could be achieved through a configuration setting or an environment variable that specifies the API endpoint to be used. The user experience should remain consistent, with minimal changes required in the application code to switch between the two APIs.
> 
> **Do you have thoughts on the technical implementation?** Based on the examples provided in the Azure OpenAI documentation, integrating Azure OpenAI into the OpenDevin project would involve modifying the API client to support Azure's specific authentication and endpoint requirements. This could include adjusting the base URL to point to Azure's OpenAI service and ensuring that the API key and other necessary headers are correctly set for Azure's API.
> 
> ## **Describe alternatives you've considered**
> ## **Additional context**

hi i'm having the same issue with setting up Azure OpenAI API with OpenDevin ，let me know how u have it done , many thx !!!

**Comment by enyst** [comment]
I'll close this in favor of #1033 . Lets continue the discussion there. @JLJuradoDeloitte please try and let us know if it works!
