### ISSUE TITLE
Azure OpenAI config.toml keeps running into these errors~!!!

### ISSUE THREAD

**Issue by LeoYoungChina** [OpenDevin/OpenDevin#1033]
this is the content of my config.toml file：
![1](https://github.com/OpenDevin/OpenDevin/assets/15046431/3867aa7a-0080-4c2b-a1b6-45c2341f7c3d)

this is the errors keeps coming up:
![2](https://github.com/OpenDevin/OpenDevin/assets/15046431/440e3cd1-d35e-4fed-9196-59fd2b4136a0)

**Comment by enyst** [comment]
The error says to check docker ps. Write ```docker ps``` in console and see what it says. Does it give an error or what does it say?

**Comment by LeoYoungChina** [comment]
> The error says to check docker ps. Write `docker ps` in console and see what it says. Does it give an error or what does it say?

then i docker ps , it comes into 404 error, is there anything wrong with my Azure settings ? :

![image](https://github.com/OpenDevin/OpenDevin/assets/15046431/6f7fcd64-8b65-47ce-9040-8580277f3bf0)

**Comment by enyst** [comment]
It does look like something is wrong with model settings. I think "deployment name" is wrong, it should be the name of the embeddings deployment in Azure, not chat GPT deployment. Please try to find that, and change it.

**Comment by LeoYoungChina** [comment]
> It does look like something is wrong with model settings. I think "deployment name" is wrong, it should be the name of the embeddings deployment in Azure, not chat GPT deployment. Please try to find that, and change it.
is there any advices or full params example for azure open ai settings for us?
![image](https://github.com/OpenDevin/OpenDevin/assets/15046431/ea3051e5-608f-4b81-ad16-d1efcdd10016)

**Comment by LeoYoungChina** [comment]
> > It does look like something is wrong with model settings. I think "deployment name" is wrong, it should be the name of the embeddings deployment in Azure, not chat GPT deployment. Please try to find that, and change it.
> > is there any advices or full params example for azure open ai settings for us?
> > ![image](https://private-user-images.githubusercontent.com/15046431/321861685-ea3051e5-608f-4b81-ad16-d1efcdd10016.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4OTkxNDUsIm5iZiI6MTcxMjg5ODg0NSwicGF0aCI6Ii8xNTA0NjQzMS8zMjE4NjE2ODUtZWEzMDUxZTUtNjA4Zi00YjgxLWFkMTYtZDFlZmNkZDEwMDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA1MTQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZTQ0YmI2NzkyNzgzZTJjNzEzZDEwZTUyZTczYjc3NmIwMmYyYzM1MjFkM2ViOGZkMjhiMmNiZmMzNzliY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6JwswBA4CFvVD9_CBJkaY4XvCXhbfxbAclOREOTOiqo)

still getting 404 errors coming up all the time

**Comment by enyst** [comment]
I think it is again the wrong name: the model for embeddings is "text-embedding-ada-002". But the "deployment name" in Azure is a name of an Azure resource with this model that you have access to. It's a name probably similar with this, but not the same.
I'm confused too 😆 but really, look around at what they call deployment, related to embeddings.

**Comment by VishalHaibatpure1** [comment]
@LeoYoungChina  : Please below instruction with screenshot from AzureStudio helps you

![image](https://github.com/OpenDevin/OpenDevin/assets/126610431/dcd978dd-9a0b-431d-88a0-d9fdf6d567c9)

Please note: For LLM_EMBEDDING_DEPLOYMENT_NAME to work, you will have to do few changes mentioned here: https://github.com/OpenDevin/OpenDevin/issues/1027#issuecomment-2050443706 


@enyst : Mostly this confusion on the deployment name and API version is happening for everyone. May be some detailed/special instructions will be required as part of Azure config doc for OpenDevin.

**Comment by enyst** [comment]
> @enyst : Mostly this confusion on the deployment name and API version is happening for everyone. May be some detailed/special instructions will be required as part of Azure config doc for OpenDevin.

We have just added a guide here:
https://github.com/OpenDevin/OpenDevin/blob/main/docs/documentation/AZURE_LLM_GUIDE.md

Please take a look and let us know what you think. Is it missing something relevant? Maybe this screenshot? I think it could help! 😄

**Comment by Umpire2018** [comment]
@he-aook I believe above pic can solve your question.

@enyst Suggest to add the screenshot to avoid misunderstanding. And i think `DEPLOYMENT_NAME` is little bit confused, maybe rename it to `LLM_EMBEDDING_SERVICE_NAME` , and `LLM_EMBEDDING_MODEL` to `LLM_EMBEDDING_TYPE` ?

**Comment by rbren** [comment]
Deduping all the azure OpenAI issues into this: https://github.com/OpenDevin/OpenDevin/issues/1042
