### ISSUE TITLE
does someone have run successfuly by using Azure Open AI APIs?

### ISSUE THREAD

**Issue by LeoYoungChina** [OpenDevin/OpenDevin#1038]
i am setting up like this :
![image](https://github.com/OpenDevin/OpenDevin/assets/15046431/4e1ea51b-ea9d-41c6-a095-97adc345cce9)

but still get 404 errs like this:
![1](https://github.com/OpenDevin/OpenDevin/assets/15046431/7d2fa2b3-ce81-4991-a3a3-c74021e5b166)

could anyboy plz setting an example which really runs open devin up by Azure Open APIs ? love u guys ~

**Comment by enyst** [comment]
I'm closing this issue, since you already have https://github.com/OpenDevin/OpenDevin/issues/1033 on the same problem. If you want to start a discussion, not an issue, please use Discussions tab. Lets solve the issue in 1033.
