### ISSUE TITLE
make: *** [start-backend] Error 1 when use ollama 

### ISSUE THREAD

**Issue by zhipengzuo** [OpenDevin/OpenDevin#1041]
exec "make  start-backend" ,
![image](https://github.com/OpenDevin/OpenDevin/assets/54702578/7e84c07b-496f-475f-b258-ee276c32971b)

my config.toml 

LLM_MODEL="ollama/llama2:7b-chat-q4_K_M"
LLM_API_KEY="ollama"
LLM_BASE_URL="http://localhost:11434"
WORKSPACE_DIR="./workspace"
LLM_EMBEDDING_MODEL="local"

if change the LLM_EMBEDDING_MODEL="local" to LLM_EMBEDDING_MODEL="llama2" ,it will be ok to start  ,but can't found llama2:"Oops. Something went wrong: Ollama call failed with status code 404. Details: model 'llama2' not found, try pulling it first"

**Comment by rbren** [comment]
This is the huggingface.co issue, see here for workarounds: https://github.com/OpenDevin/OpenDevin/issues/939

**Comment by rbren** [comment]
This should be fixed now that we're running in docker!
