### ISSUE TITLE
Reviewing code changes using a linter.

### ISSUE THREAD

**Issue by JayQuimby** [OpenDevin/OpenDevin#1043]
**What problem or use case are you trying to solve?**
When models are writing code to modify files they often make spacing mistakes and other errors that can be easily detected using a linter.

**Describe the UX of the solution you'd like**
Performance enhancement for all agents!

**Do you have thoughts on the technical implementation?**
Use a docker image within the current environment that will be able to compile and test the code for any simple errors.

**Additional context**
This is in conjunction with the SWE-Agent implementation #846 

I have discussed this with @guneetsk99 and he is going to work on this.

**Comment by rbren** [comment]
Can we do this generically? How do you plan to detect the correct language, and choose the right linter?

**Comment by foragerr** [comment]
[stubs here](https://github.com/OpenDevin/OpenDevin/pull/846/files#diff-3aaad2119d555d0e6e5a198ee482add5b3e090688900b95d226d345931489280R36-R45) indicate linter selection is by file extension, and a desire to support 4 languages.
