### ISSUE TITLE
docker start pod faild

### ISSUE THREAD

**Issue by he-aook** [OpenDevin/OpenDevin#1047]
531988dfef7a   ghcr.io/opendevin/sandbox   "/usr/sbin/sshd -D -…"   13 seconds ago   Exited (255) 13 seconds ago             sandbox-083e5d99-17e5-4175-87b4-4faf771455ff
f3a1386b117b   ghcr.io/opendevin/sandbox   "/usr/sbin/sshd -D -…"   26 seconds ago   Exited (255) 25 seconds ago             sandbox-f0eda1d4-ea00-4568-998a-53f9b855eb11
d10d71a613ae   ghcr.io/opendevin/sandbox   "/usr/sbin/sshd -D -…"   5 minutes ago    Exited (255) 5 minutes ago              sandbox-d5f7773d-6d03-4df4-b032-263ae826c6fe
02cfc8f104d3   ghcr.io/opendevin/sandbox   "/usr/sbin/sshd -D -…"   36 minutes ago   Up 36 minutes                           sandbox-86d75264-f1bf-4177-8430-08cb77eb0f33
[root@iZrj9huih64xl89h2l5pcwZ frontend]#
<img width="955" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/48249754/e575f4a1-29ec-433a-9625-9eafaefaef85">

**Comment by he-aook** [comment]
Traceback (most recent call last):
  File "/opt/OpenDevin-main/opendevin/server/agent/manager.py", line 124, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/opt/OpenDevin-main/opendevin/controller/agent_controller.py", line 86, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/opt/OpenDevin-main/opendevin/controller/command_manager.py", line 22, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/opt/OpenDevin-main/opendevin/sandbox/ssh_box.py", line 81, in __init__
    self.restart_docker_container()
  File "/opt/OpenDevin-main/opendevin/sandbox/ssh_box.py", line 336, in restart_docker_container
    raise Exception('Failed to start container')
Exception: Failed to start container

**Comment by he-aook** [comment]
这项目写的, 启动起来太费劲了

**Comment by rbren** [comment]
Try setting `SANDBOX_TYPE=exec` in your config.toml or env. A better fix is on the way

**Comment by Jmzp** [comment]
That works but missing "" -> `SANDBOX_TYPE="exec"`

> Try setting `SANDBOX_TYPE=exec` in your config.toml or env. A better fix is on the way

**Comment by rbren** [comment]
Fixed!

**Comment by he-aook** [comment]
docker启动没问题了, 但是页面还是无法完成对话
<img width="2837" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/48249754/bfaeeed7-0723-495a-afe7-cefaf6fb01f3">

**Comment by rbren** [comment]
@he-aook please open a new issue with the template filled out

Closing this one since the workaround is working

**Comment by he-aook** [comment]
好的, 谢谢
















At 2024-04-15 16:06:54, "Robert Brennan" ***@***.***> wrote:

@he-aook please open a new issue with the template filled out

Closing this one since the workaround is working

**Comment by 1apolloe1** [comment]
Where do I find config.toml?
