### ISSUE TITLE
Add pause/resume functionality (and button)

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#1049]
**What problem or use case are you trying to solve?**
I want to be able to pause the agent so it stops its work, then resume when I'm ready

**Describe the UX of the solution you'd like**
On the backend, a websocket action for `pause`, and another for `resume`

On the frontend, a button that sends those requests, and reflects current state

**Do you have thoughts on the technical implementation?**
This will probably be a little difficult on the backend...there's weird concurrency stuff to consider.

**Comment by iFurySt** [comment]
I can take a look tomorrow
