### ISSUE TITLE
Document features for limiting LLM costs

### ISSUE THREAD

**Issue by wolfhoundjesse** [OpenDevin/OpenDevin#1061]
#### Describe the bug

Possibly not a problem, just a peculiarity. I put $10 into my OpenAI rate limit for GPT-4 today, and I've already hit the ceiling on tokens.

![image](https://github.com/OpenDevin/OpenDevin/assets/13468509/cd02a5fc-36ba-4fcb-9d70-54a6ea343403)

#### Setup and configuration
**Current version**:

```bash
commit e0c7492609bf8ebdbd7270c9e9261bf2944f3bc6 (HEAD -> main, origin/main, origin/HEAD)
Author: Boxuan Li <xxx@xxx.xxx>
Date:   Fri Apr 12 12:01:52 2024 -0700

    Traffic Control: Add new config MAX_CHARS (#1015)

    * Add new config MAX_CHARS

    * Fix mypy linting issues
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="gpt-4"
LLM_API_KEY="sworn_to_secrecy"
LLM_EMBEDDING_MODEL="openai"
WORKSPACE_DIR="./workspace"
SANDBOX_TYPE="exec"
SANDBOX_CONTAINER_IMAGE="node:21-bullseye"
```
WSL2 on Windows 10 Home
I'm using Pengwin from Whitewater Foundry

```bash
uname -r
5.15.146.1-microsoft-standard-WSL2
```

**My model and agent** (you can see these settings in the UI):
* Model: gpt-4
* Agent: MonologueAgent

**Commands I ran to install and run OpenDevin**:
```
git clone https://github.com/OpenDevin/OpenDevin
cd OpenDevin
make build
make setup-config
make run
```
Of course, I installed the required dependencies first

**Steps to Reproduce**:
1. Start an empty project using the monorepo tool Nx. The project will have two apps. The first is a NestJs app, and the second is a React app.

**Logs, error messages, and screenshots**:
```json
Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
```

#### Additional Context
I see gpt-4-turbo is an option, but I honestly didn't think I'd hit the limit so quickly. Happy to answer any questions!

**Comment by yufansong** [comment]
We introduce a feature #1015 to limit the LLM token. Not sure whether it is helpful.

**Comment by rbren** [comment]
@wolfhoundjesse thanks for letting us know! It does indeed use a lot of tokens.

I think `max_tokens` and `max_iterations` are probably the best way to solve this, but we should document them more extensively

**Comment by dagelf** [comment]
Many API endpoints provide feedback on how many tokens you have left eg `groq`:

https://console.groq.com/docs/rate-limits
```
Header	Value	Notes
retry-after	2	In seconds
x-ratelimit-limit-requests	14400	Always refers to Requests Per Day (RPD)
x-ratelimit-limit-tokens	18000	Always refers to Tokens Per Minute (TPM)
x-ratelimit-remaining-requests	14370	Always refers to Requests Per Day (RPD)
x-ratelimit-remaining-tokens	17997	Always refers to Tokens Per Minute (TPM)
x-ratelimit-reset-requests	2m59.56s	Always refers to Requests Per Day (RPD)
x-ratelimit-reset-tokens	7.66s	Always refers to Tokens Per Minute (TPM)
```

**Comment by yufansong** [comment]
Close it. Let track the progress here #1913
