### ISSUE TITLE
OpenDevin is NOT able to download datasets from Kaggle

### ISSUE THREAD

**Issue by sinpsarkar** [OpenDevin/OpenDevin#1062]
#### Describe the bug

I passed the following command in the Chat. I have installed Kaggle using apt. But OpenDevin throws the message : "kaggle : command not found"
#### Setup and configuration
**Current version**:

```bash
Response recognition for weak llms (https://github.com/OpenDevin/OpenDevin/pull/523)

Tweak for weak llms

Update to the latest commits

Update to the latest commits

Fix lint errors

Remove merge artifact
```

**My config.toml and environment vars** (be sure to redact API keys):
``` 
Environment: WSL2 in Windows 11

whereis kaggle  :   kaggle: /home/sinp/.local/bin/kaggle

Environment Vars:   -bash: echo/home/sinp/.local/bin:/home/sinp/.nvm/versions/node/v21.7.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program: No such file or directory



toml
LLM_MODEL="gemini/gemini-pro"
LLM_API_KEY="***************************************"
LLM_EMBEDDING_MODEL=""
WORKSPACE_DIR="./workspace"
SANDBOX_TYPE='exec'
```

**My model and agent** (you can see these settings in the UI):
* Model: gemini-pro
* Agent: MonologueAgent

**Commands I ran to install and run OpenDevin**:
```
git clone https://github.com/OpenDevin/OpenDevin.git
cd OpenDevin
make build
make setup-config
make run
```

**Steps to Reproduce**:
1. update the model and the api_key
2. make run
3. enter the command in the Chat in UI: download the kaggle data file using the API command "kaggle datasets download -d aspillai/netflix-stock-price-with-indicators"

**Logs, error messages, and screenshots**:
![issue3](https://github.com/OpenDevin/OpenDevin/assets/45538409/1b0e548e-8d9a-4692-a3ec-9dfab9364221)
![issue2](https://github.com/OpenDevin/OpenDevin/assets/45538409/5183ea5a-fe8f-4892-b8a0-316bc304f21e)
![issue1](https://github.com/OpenDevin/OpenDevin/assets/45538409/49e0ecca-942a-4656-a1ff-f9b426a038f4)

#### Additional Context

I am trying to test the capabilities of OpenDevin and how can it help in some simple to complex real-world problems.

**Comment by SmartManoj** [comment]
Is it stopped?

**Comment by sinpsarkar** [comment]
> Is it stopped?

No .. I do a docker ps and it shows me the container for OpenDevin running

**Comment by SmartManoj** [comment]
backend stopped?

**Comment by sinpsarkar** [comment]
> backend stopped?

No.. the terminal doesn't show any error saying backend is stopped

**Comment by SmartManoj** [comment]
Does it continue after step 4?

**Comment by sinpsarkar** [comment]
> Does it continue after step 4?

The same loop loop continues

**Comment by rbren** [comment]
Deduping this with https://github.com/OpenDevin/OpenDevin/issues/550

**Comment by sinpsarkar** [comment]
> Deduping this with #550

I have followed all the steps mentioned in #550 but the issue still persists. Not sure if I am speaking the correct thing, but it seems like kaggle API needs to be available in the docker image. and there should be a provision to push the kaggle.json. Please revert if you agree.

**Comment by rbren** [comment]
@sinpsarkar we don't want to build _too_ much into the sandbox image, or it will get bloated. But the LLM should be able to install these things.

Did you set `RUN_AS_DEVIN=false` in your config?

**Comment by sinpsarkar** [comment]
> @sinpsarkar we don't want to build _too_ much into the sandbox image, or it will get bloated. But the LLM should be able to install these things.
> 
> Did you set `RUN_AS_DEVIN=false` in your config?

I completely understand that the size of the sandbox is a  consideration. The LLM is also able to pip install kaggle. However, next when it runs kaggle command, it throws the error that "kaggle: command not found".
`RUN_AS_DEVIN=false`--- this is already in the sandbox.py.
Please advise.

**Comment by rbren** [comment]
🤔 if you're seeing `RUN_AS_DEVIN=false` in sandbox.py, you're on a pretty old version. Can you try updating?
