### ISSUE TITLE
What are we doing here?

### ISSUE THREAD

**Issue by katmai** [OpenDevin/OpenDevin#1066]
There's a chance i might be stupid and i'm just misunderstanding it, but i have to give this a go.

So it went this way:

i've been running a custom model, and i can ask/receive a decent answer in about 30 seconds.

Going through OpenDevin, each step takes about 5-10 minutes. i see the cpu spiking, so there's something going on, but no idea what, because it's surely not the answer, because it keeps going on about making plans and agendas and what not, so clearly there's some other wrappers there.

i see the Docker sandbox running a tail to keep it alive,  but otherwise it's empty. Devin's not doing anything there either. 

Then i went to the LLM parameters, and now i had to learn what all those mean, and i tuned the parameters to what i thought it makes sense in terms of precision and accuracy as per the documentation available:

```
PARAMETER temperature 0.8
PARAMETER num_ctx 16384
PARAMETER num_thread 12
PARAMETER seed 42
PARAMETER top_k 40
PARAMETER top_p 0.9
PARAMETER tfs_z 0.92
PARAMETER mirostat 2
PARAMETER mirostat_eta 0.05
PARAMETER mirostat_tau 3.0
PARAMETER repeat_penalty 0
PARAMETER repeat_last_n -1
```

Gave a nice system prompt, and off to the races we went. But all that comes out is nonsense.

So.

The only way to go back to getting any sort of "meaningful" output, i'd have to tweak the parameters to introduce more "diversity" and "probability" and "creativity", which if i'm interested in precision and accuracy, that's not what i need.

Again, there's the possibility of me being stupid at this point, but i do have to ask. What is this and what are we doing here? To me it looks like a way to introduce delays.

**Comment by katmai** [comment]
i have a few alternatives, options, ideas, theories, whatever you may wanna call it, and since you like probability so much, feel free to choose whatever suits you:

```
- i made a mistake in reading the docs, and i've selected some wrong parameters due to me not knowing this subject well enough.
- you're all on an inside joke but me. 
Because coders, are smart people right? they write code, they are good with numbers, algorithms, math, they are by all definitions knowledgeable. They work based on logic and precision and they work with computers which are - just that - precise. They are made of switches, upon which we have abstracted meaning, in the form of instruction sets (i'm not gonna call them programming languages, because we all know - or at least i thought everybody knew - that "language" is a term used when you communicate with someone. And with a computer, you don't communicate, you give it instructions on where to move bits of data. So why use the term "language" anyway, in an environment where it's all about precision?)
- you're all idiots. 
Because i can't understand how so many people which by all standards are smart, are going about and giving their effort to something that is not what it is.
- you've all been duped. Into going on an AI bandwagon, searching for something, all world's brightest minds, going on loops, and inaccurate data, and they themselves creating more inaccurate data in the process, muddying the waters in order to make them seem deep.
- ill intent. you all know what you're doing, but somehow you decided that it's fun and maybe that's the definition of chaos and you feel giddy about it. However, it's a mediocre implementation of chaos.
- you're all just playing along, fully aware of what you're doing, but going along to see where this leads, if anywhere, just to see what this is all about. No harm done, it's time spent by enthusiasts, doing something exciting and new.
However, here, we come back to the idea that programmers, are smart people, so it couldn't have taken anyone focused nearly anywhere as it took me to think about this. 
```

So, what are we doing? Because at this point i'd rather just compute primes than doing this. At least that's doing something.

**Comment by bnthn** [comment]
I just stumbled upon this repository, then saw this issue, and while I'm surely not knowledgeable enough to answer your questions i wanted to give my 2 cents anyway. I'm sure someone will come along and give a proper answer to your issue.

As for why we (or anyone) is doing this:
Innovation can be driven by a lot of things: curiosity, money, even national security or safety concerns. Things like Ollama and Opendevin seem like a try to stand up to a rising AI oligarchy, giving people back power over computing, which is a good thing to me. If it succeeds, good. If this and the current wave of AI hype is nothing but that, then we'll see what will stick around. At least some people have to have learned something along the way.

For Opendevin specifically: 
These kind of tools are in a very early stage, who knows what will come. If everything will go according to plan, this could be a great opportunity to teach about programming or let people quickly spin up prototypes. On the flip side, it could remove a big part of programming that i really liked. But no one can and should stop innovation.

Anyways, will try this thing out tomorrow. Maybe I'll even like it, maybe wait for another year or 10 until its ready for prime time. Maybe this will never happen and it's all just a fever dream coming to an end soon lol.

**Comment by katmai** [comment]
> I just stumbled upon this repository, then saw this issue, and while I'm surely not knowledgeable enough to answer your questions i wanted to give my 2 cents anyway. I'm sure someone will come along and give a proper answer to your issue.
> 
> As for why we (or anyone) is doing this: Innovation can be driven by a lot of things: curiosity, money, even national security or safety concerns. Things like Ollama and Opendevin seem like a try to stand up to a rising AI oligarchy, giving people back power over computing, which is a good thing to me. If it succeeds, good. If this and the current wave of AI hype is nothing but that, then we'll see what will stick around. At least some people have to have learned something along the way.
> 
> For Opendevin specifically: These kind of tools are in a very early stage, who knows what will come. If everything will go according to plan, this could be a great opportunity to teach about programming or let people quickly spin up prototypes. On the flip side, it could remove a big part of programming that i really liked. But no one can and should stop innovation.
> 
> Anyways, will try this thing out tomorrow. Maybe I'll even like it, maybe wait for another year or 10 until its ready for prime time. Maybe this will never happen and it's all just a fever dream coming to an end soon lol.

i mean none of that stand up to a rising AI oligarchy and giving people power over computing is true, so the idea of it being a good thing is sort of questionable.

However, they do lead to better understanding of what the current AI is about, and that is a good thing.

As far as trying things out goes, it comes with it's caveats and debbie downers due to lag, delays and response times not being on point. Waiting is often pointless when you know. It usually leads of frustration and going about learning other cool things like playing an instrument and what not, which is not necessarily a bad thing, but it's usually more fun if things are in motion. Then, we can play.

**Comment by rezzie-rich** [comment]
Bro, relax.

These guys are trying to replicate a $2 billion company without any paycheck, and it's only been around 2 months since the project started. 

It's only been a year since AI agent frameworks got introduced, so there's still a lot to be understood in order to get production level outputs.

I lost interest halfway through reading your post as you're clearly acting like a Karen. If u have any solution to offer, then please do so. Orelse, keep your childish tantrum out of the issues.

**Comment by rbren** [comment]
Appreciate the feedback y'all. It's definitely still early days, but we're close to having a SWE-Agent implementation, which will be a huge boost in quality. And I'd definitely recommend using it with SOTA LLMs, rather than a smaller local model (which often produces nonsense, as you point out). 

Let's move this discussion to Discord or Slack--we're trying to keep GitHub issues for bugs and features.
