### ISSUE TITLE
There is a similar project called Devika

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#108]
There is a similar project called Devika and I don't know if it make sense that people working on two similar projects.

**Comment by wrapss** [comment]
Devika is a really amateur project, no websooket, +10 requests to the api per second, the interface isn't really that of devin

**Comment by PierrunoYT** [comment]
How can I test OpenDevin to see how it looks like in compare of Devika?

**Comment by AbhisekOmkar** [comment]
We can close this Issue @huybery

**Comment by rbren** [comment]
@PierrunoYT we're closing in on a working prototype. Stay tuned!
