### ISSUE TITLE
BackgroundCommand/Process should be better documented

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#1083]
**What problem or use case are you trying to solve?**

The BackgroundCommand/Process class is not very well documented, despite the logic being somewhat complex. Docstrings should be added: https://github.com/OpenDevin/OpenDevin/blob/d27895d018098860e5c3d6613d0cf1b4a66a8478/opendevin/sandbox/sandbox.py#L15

**Comment by foragerr** [comment]
I'm not quite following why python's docker library wouldn't handle low level processing of output streams, and OpenDevin needs to handle it.
