### ISSUE TITLE
Give it a Chatdev like interface

### ISSUE THREAD

**Issue by GameMaster007** [OpenDevin/OpenDevin#11]

**Comment by mangalprada** [comment]
Can we connect sometime on gmeet to discuss the specifics?

**Comment by z-zeechung** [comment]
count me in as well, thanks

**Comment by poornima-alugubelly** [comment]
can I also work on this please?

**Comment by CL0R0X** [comment]
Can I also help this out

**Comment by VJlaxmi** [comment]
can I work on this too?

**Comment by rbren** [comment]
This is a great idea, but I don't see this issue getting closed anytime soon--it'd be a huge undertaking.

If someone wants to start building out a chatdev interface, feel free to open a PR, or start a discussion in Slack!
