### ISSUE TITLE
[Bug] Error creating controller. Please check Docker is running using `docker ps`. 

### ISSUE THREAD

**Issue by etunay-mufin** [OpenDevin/OpenDevin#1101]
#### Describe the bug

**I don't fully understand the issue, but I think Docker isn't working. I've struggled to get it to work properly in previous attempts as well. It seems like there might be a problem on my end or my development environment isn't progressing correctly**

#### Setup and configuration
**Current version**:

```bash

commit 033352e34093743aca5ff0647168940772957d69 (HEAD -> main, origin/main, origin/HEAD)
Author: மனோஜ்குமார் பழனிச்சாமி <smartmanoj42857@gmail.com>
Date:   Sun Apr 14 19:02:36 2024 +0530

added to sudo group (#1091)
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="gpt-3.5-turbo-1106"
LLM_API_KEY="sk-........."
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model: chat-gpt-3.5
* Agent: CodeAct

**Commands I ran to install and run OpenDevin**:
```
```

**Steps to Reproduce**:
1. make build
2. make setup
3. make run

**Logs, error messages, and screenshots**:

![image](https://github.com/OpenDevin/OpenDevin/assets/160699323/574d8caf-f8a7-495c-880e-605daef95de7)

#### Additional Context

Maybe my docker is not valid :(

**Comment by justynazander** [comment]
This is solved [here](https://github.com/OpenDevin/OpenDevin/issues/1047). Add a line `SANDBOX_TYPE="exec" ` in your config.toml.

**Comment by rbren** [comment]
Deduping this with all the similar issues. Should be permanently fixed once the DOOD PR is in

**Comment by etunay-mufin** [comment]
Thank you for response!
