### ISSUE TITLE
make: *** No rule to make target 'build'.  Stop.

### ISSUE THREAD

**Issue by xplorer990** [OpenDevin/OpenDevin#1106]
Windows 11 WSL2 Ununtu 22.04

This is a fresh install with finally everything in place. Yet I now get a completely different error

```
**enli@LY5:~/1/OpenDevin$ make build
make: *** No rule to make target 'build'.  Stop.**
enli@LY5:~/1/OpenDevin$ python3 --version
Python 3.11.9
enli@LY5:~/1/OpenDevin$ poetry --version
Poetry (version 1.8.2)
enli@LY5:~/1/OpenDevin$ node --version
v18.17.1
enli@LY5:~/1/OpenDevin$
```

**Comment by rbren** [comment]
@xplorer990 can you show which version you're on with `git log -n1`?

It's a weird error--there's definitely a `build` in the makefile...

**Comment by Umpire2018** [comment]
```bash
make build
Building project...
Checking dependencies...
Checking Python installation...
Python 3.11.2 is already installed.
Checking npm installation...
npm 10.2.4 is already installed.
Checking Docker installation...
Docker version 26.0.0, build 2ae903e is already installed.
Checking Poetry installation...
Poetry (version 1.8.2) is already installed.
Dependencies checked successfully.
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
```

@xplorer990 I am using ubuntu linux, for your reference. Maybe delete `OpenDevin` folder and retry?

**Comment by SmartManoj** [comment]
check the folder and run `ls`

**Comment by loopyd** [comment]
# Troubleshooting Options

For your issue.

## Run make with Debug on:

Additional output from make can help:

```sh
make SHELL='/bin/sh -x' build
```

Will display everything that make is trying to do.  This can help you resolve the issue yourself, or definitely share that with us.

## Verify non-cmake installation of make (GNU Autotools):

If you happen to run this command without an error about a missing VERBOSE flag.

```sh
make VERBOSE=1 build
```

You have the cmake version of make installed, or it is being referenced, which is not correct.

## Check environment in WSL container:

Consider what is on your environment variables, as that is imported from the Windows host when some ``%USERPROFILE%\.wslconfig`` or ``/etc/wsl.conf`` options are changed, such as ``host_inteop: true`` which can irregularly set PATH sometimes.

```
printenv
```

Advise check environment, ensure that host integration isn't pulling a windows installation of cmake from PATH before proceeding.

Your make version may also help us out:

```
make --version
```

Correct version of make is GNU auto tools make.  If you see mention of cmake here, ensure PATH isn't adding it from Windows.

## Other potential hiccups (Line Endings, MSYS2 and Git Bash interference)

Weird errors can also be related to doing a ``git clone`` from within Windows, and then trying to cd to a Windows git-cloned directory in WSL, where line endings are different.  Avoid using tools like git bash, MSYS2, etc. on Windows that can interfere incorrectly with WSL2, and use git from within your WSL container as an installed package.

**Comment by SmartManoj** [comment]
@loopyd, If it is an LLM response , mention it too.

**Comment by loopyd** [comment]
> @loopyd, If it is an LLM response, mention it too.

I hand type all of my responses. None of tbis is AI generated.

**Comment by xplorer990** [comment]
Cloning in new folder did the trick.
