### ISSUE TITLE
Please include the option to insert a custom model 

### ISSUE THREAD

**Issue by yf007** [OpenDevin/OpenDevin#111]
Like this

OPENAI_ENDPOINT=https://some-private.com/v1
OPENAI_API_KEY=****

Thanks

**Comment by rbren** [comment]
[This PR](https://github.com/OpenDevin/OpenDevin/pull/114) moves to LiteLLM, which I think should support this.

**Comment by rbren** [comment]
Confirmed: https://github.com/BerriAI/litellm/blob/05dfc9e6acee94af7216288cd3af25a446a39c14/docs/my-website/docs/providers/openai.md?plain=1#L53
