### ISSUE TITLE
Incorrect version for Azure OpenAI

### ISSUE THREAD

**Issue by he-aook** [OpenDevin/OpenDevin#1113]
<img width="2611" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/48249754/6af57f80-86bc-442c-be56-06b16d54dca3"<img width="1138" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/48249754/2fa671ef-e5ca-454e-9fd2-bd481e5e4dc6">

**Comment by he-aook** [comment]
![Uploading image.png…]()

**Comment by Umpire2018** [comment]
Model Dialogue Indicates Incorrect Version

> 请问您关于此问题的具体情况/软件版本是什么？能否附带相关详细说明帮助定位问题？

Could you please specify the exact circumstances and/or software version regarding this issue? Would it be possible to provide a detailed description to assist in troubleshooting the problem?

**Comment by he-aook** [comment]
Oops. Something went wrong: Error code: 400 - {'error': {'code': 'OperationNotSupported', 'message': 'The embeddings operation does not work with the specified model, gpt-35-turbo. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.'}}

**Comment by he-aook** [comment]
部署完成之后, 对话一直在不停的刷上面的一条错误日志,

**Comment by he-aook** [comment]
LLM_MODEL="GPT-3.5"
LLM_API_KEY="320f94XXXXXXXXX40cba81e"
LLM_EMBEDDING_MODEL="azureopenai"
LLM_BASE_URL="https://ai-test-dev.openai.azure.com/"
LLM_DEPLOYMENT_NAME="gpt35-1106-test"
LLM_API_VERSION="2024-02-15-preview"
WORKSPACE_DIR="./workspace"
SANDBOX_TYPE="exec"

**Comment by he-aook** [comment]
不知道我这块的配置对的没?

**Comment by he-aook** [comment]
<img width="857" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/48249754/a0f7a442-7442-4929-a330-8c0bee3c2ed0">

**Comment by Umpire2018** [comment]
## azure openai configs

The model used for Azure OpenAI embeddings is "text-embedding-ada-002". You need the correct deployment name for this model in your Azure account.

During installation of OpenDevin, you can set the following parameters used for embeddings, when prompted by the makefile:

```
LLM_EMBEDDING_MODEL="azureopenai"
DEPLOYMENT_NAME = "<your-embedding-deployment-name>"        # e.g. "TextEmbedding...<etc>"
LLM_API_VERSION = "<api-version>"         # e.g. "2024-02-15-preview"
```

You can re-run ```make setup-config``` anytime, or add or edit them manually in the file afterwards.

Reference [here](https://github.com/OpenDevin/OpenDevin/blob/main/docs/documentation/AZURE_LLM_GUIDE.md)
Try to replace `gpt35-1106-test` to `text-embedding-ada-002` in `config.toml`, and remember to hide sensitive info like `LLM_BASE_URL`.

But i think `DEPLOYMENT_NAME ` is little bit confused, maybe rename it to `LLM_EMBEDDING_SERVICE_NAME` , and `LLM_EMBEDDING_MODEL` to `LLM_EMBEDDING_TYPE` ?

**Comment by he-aook** [comment]
Oops. Something went wrong: Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}

**Comment by he-aook** [comment]
我刚替换之后, 还是不行,  ”Try to replace gpt35-1106-test to text-embedding-ada-002 in config.toml“
Oops. Something went wrong: Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}

**Comment by Umpire2018** [comment]
Sorry, I can only recommend you to find answers in microsoft's doc.

1. https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/working-with-models
2. https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#embeddings-models

![image](https://github.com/OpenDevin/OpenDevin/assets/138990495/039c3a05-d073-4c5a-a652-3e74d37521e4)

**Comment by he-aook** [comment]
好的, 感谢, 我试下

**Comment by rbren** [comment]
Deduping Azure OpenAI issues into this one: https://github.com/OpenDevin/OpenDevin/issues/1042

**Comment by he-aook** [comment]
https://github.com/OpenDevin/OpenDevin/issues/1113#issuecomment-2057095897

**Comment by he-aook** [comment]
https://github.com/OpenDevin/OpenDevin/issues/1113#issuecomment-2057095897
这个可能不对, 我在尝试用前面的问题解答来配置
