### ISSUE TITLE
Error creating controller. Please check Docker is running using `docker ps`.

### ISSUE THREAD

**Issue by xplorer990** [OpenDevin/OpenDevin#1119]
Windows 11 WSL2 Ubuntu 22.04, installation of opendevin went flawlessly (no errors encountered by me).

Opendevin loaded but with a warning.
`Error creating controller. Please check Docker is running using `docker ps`.`
Also `Initializing agent (may take up to 10 seconds)...` doesn't go away, it's stuck there...

`> docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS         PORTS     NAMES
f5a****ba4   ghcr.io/opendevin/sandbox   "/usr/sbin/sshd -D -…"   7 minutes ago   Up 7 minutes             opendevin-sandbox-3ad******-3**9-4**c-ad**-2*********a`

![image](https://github.com/OpenDevin/OpenDevin/assets/76548373/5861b529-93ac-4f65-b188-080aef57006c)
![image](https://github.com/OpenDevin/OpenDevin/assets/76548373/32bc5c05-8a19-46d2-a80a-0c2e45c446e3)

`$ make run
Running the app...
Starting backend server...
Waiting for the backend to start...
INFO:     Started server process [25633]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
Backend started successfully.
Starting frontend with npm...

> opendevin-frontend@0.1.0 start
> vite --port 3001

  VITE v5.2.8  ready in 450 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
INFO:     127.0.0.1:38340 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     127.0.0.1:38354 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:38348 - "GET /configurations HTTP/1.1" 200 OK
INFO:     127.0.0.1:38356 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 38364) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIzYWQ5NTc4ZC0zOGM5LTRhOWMtYWQzNS0yZWM4MjVlZGEzZGEifQ.np8CzUuT2VP24up-9NxLCZxDn-RFBWsJC2gMb9gXgmA" [accepted]
Starting loop_recv for sid: 3ad9578d-38c9-4a9c-ad35-2ec825eda3da
INFO:     connection open
INFO:     127.0.0.1:38382 - "GET /messages/total HTTP/1.1" 200 OK
15:00:08 - opendevin:INFO: ssh_box.py:81 - Using workspace directory: /home/enli/2/OpenDevin/workspace
15:00:09 - opendevin:INFO: ssh_box.py:280 - Container stopped
15:00:09 - opendevin:INFO: ssh_box.py:312 - Container started
15:00:10 - opendevin:INFO: ssh_box.py:329 - waiting for container to start: 1, container status: running
15:00:11 - opendevin:INFO: ssh_box.py:170 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 57251 opendevin@localhost` with the password '2d47aac2-cd33-4d03-9572-57c7dd704996' and report the issue on GitHub.
15:00:11 - opendevin:ERROR: agent.py:136 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/home/enli/2/OpenDevin/opendevin/server/agent/agent.py", line 126, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/enli/2/OpenDevin/opendevin/controller/agent_controller.py", line 95, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/enli/2/OpenDevin/opendevin/controller/command_manager.py", line 29, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/home/enli/2/OpenDevin/opendevin/sandbox/ssh_box.py", line 99, in __init__
    self.start_ssh_session()
  File "/home/enli/2/OpenDevin/opendevin/sandbox/ssh_box.py", line 173, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/home/enli/.cache/pypoetry/virtualenvs/opendevin-NMU0JHM5-py3.11/lib/python3.11/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
INFO:     127.0.0.1:38372 - "GET /configurations HTTP/1.1" 200 OK
15:00:11 - opendevin:INFO: ssh_box.py:81 - Using workspace directory: /home/enli/2/OpenDevin/workspace
15:00:12 - opendevin:INFO: ssh_box.py:280 - Container stopped
15:00:12 - opendevin:INFO: ssh_box.py:312 - Container started
15:00:13 - opendevin:INFO: ssh_box.py:329 - waiting for container to start: 1, container status: running
15:00:14 - opendevin:INFO: ssh_box.py:170 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 56547 opendevin@localhost` with the password '6d85de1c-d360-424b-8d4a-7c9504dc5ac0' and report the issue on GitHub.
15:00:14 - opendevin:ERROR: agent.py:136 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/home/enli/2/OpenDevin/opendevin/server/agent/agent.py", line 126, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/enli/2/OpenDevin/opendevin/controller/agent_controller.py", line 95, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/enli/2/OpenDevin/opendevin/controller/command_manager.py", line 29, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/home/enli/2/OpenDevin/opendevin/sandbox/ssh_box.py", line 99, in __init__
    self.start_ssh_session()
  File "/home/enli/2/OpenDevin/opendevin/sandbox/ssh_box.py", line 173, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/home/enli/.cache/pypoetry/virtualenvs/opendevin-NMU0JHM5-py3.11/lib/python3.11/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host`

**Comment by xplorer990** [comment]
> SANDBOX_TYPE="exec"

That seemed to have work. Thanks @SmartManoj

**Comment by SmartManoj** [comment]
> you can try `ssh -v -p 56547 opendevin@localhost` with the password '6d85de1c-d360-424b-8d4a-7c9504dc5ac0' and report the issue on GitHub.

Is it connecting?

**Comment by enyst** [comment]
I'll close this issue, but please do open a new issue if there are further problems. You may also want to note that we just changed the recommended setup, so when you update please check the readme and let us know of any issues!
