### ISSUE TITLE
Publish an official image into ghcr.io

### ISSUE THREAD

**Issue by foragerr** [OpenDevin/OpenDevin#1122]
**What problem or use case are you trying to solve?**
Publish an official image for OpenDevin into ghcr.io and eiliminate the `docker build` step from getting started instructions at https://github.com/OpenDevin/OpenDevin?tab=readme-ov-file#-get-started

**Comment by rbren** [comment]
Fixed in https://github.com/OpenDevin/OpenDevin/pull/1121

Dealing with a permission issue first

**Comment by foragerr** [comment]
Fixed indeed. Thanks @rbren 

OpenDevin image now available at https://github.com/OpenDevin/OpenDevin/pkgs/container/opendevin
See updated README instructions!
