### ISSUE TITLE
`docker build` error:  Internal Server Error for API route and version

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#1124]
#### Description of the errors
1. Error when creating the Docker image for OpenDevin
2. Error when installing the current project: opendevin (0.1.0)

#### Setup and Configuration
**Current version**:
```
commit 2491a3524e9b112ef9fe4d5059161ec3f85cbc69 (HEAD -> main, origin/main, origin/HEAD)
Author: Edwards.Arno <138990495+Umpire2018@users.noreply.github.com>
Date:   Mon Apr 15 22:14:37 2024 +0800

    feat: add `question.md` template for community Q&A (#1115)

    * feat: add `question.md` template for community Q&A  

    * Update .github/ISSUE_TEMPLATE/question.md

    Co-authored-by: Robert Brennan <accounts@rbren.io>
```

* Operating System: Windows 10, WSL2

**Logs, Error Messages and Screenshots**:
```
Installing the current project: opendevin (0.1.0)

Warning: The current project could not be installed: [Errno 2] No such file or directory: '/app/README.md'
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
In a future version of Poetry this warning will become an error!
^C
(base) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ docker build -t opendevin-app -f container/Dockerfile .
ERROR: request returned Internal Server Error for API route and version http://%2Fvar%2Frun%2Fdocker.sock/_ping, check if the server supports the requested API version
```

**My Configuration**:
No config.toml or environment variables set.

**Model and Agent**:
Not yet configured

**Installation Commands**:
```
git clone https://github.com/opendevin/opendevin.git
cd opendevin 
docker build -t opendevin-app -f container/Dockerfile .
```

**Steps to Reproduce**:
1. Clone the Git repository
2. Change to the directory
3. Create the Docker image with `docker build -t opendevin-app -f container/Dockerfile .`
4. Install the current project with `poetry install`

#### Additional Context
The first error occurs specifically when creating the Docker image for OpenDevin in the WSL2 environment on Windows 10. The second error occurs when trying to install the current project using Poetry.

The Docker error message suggests a problem with the Docker installation or configuration in the WSL2 environment. I have tried updating Docker, checking the configuration, restarting the Docker service, and verifying the API version, but the issue persists.

The Poetry error indicates that the README.md file is missing from the '/app' directory. This could be due to an issue with the project structure or the way the Docker image is being built.

**Comment by rbren** [comment]
It seems like maybe docker isn't running. @PierrunoYT are you able to run `docker run hello-world`?

**Comment by PierrunoYT** [comment]
> It seems like maybe docker isn't running. @PierrunoYT are you able to run `docker run hello-world`?

I installed if before I opeend Docker but then I thought I will run the command again and I got this issue.
I tried docker ps but 

(base) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ docker ps
request returned Internal Server Error for API route and version http://%2Fvar%2Frun%2Fdocker.sock/v1.45/containers/json, check if the server supports the requested API version
(base) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$

**Comment by rbren** [comment]
OK--the issue is with docker. You'll need to make sure `docker ps` is able to run before trying `docker build`
