### ISSUE TITLE
cannot import name 'spawn' from 'pexpect'

### ISSUE THREAD

**Issue by ashrafML** [OpenDevin/OpenDevin#1125]
**Summary**
Can't run OpenDevin from VS on widows  that rise error of
ERROR:root:<class 'ImportError'>: cannot import name 'spawn' from 'pexpect'
**Motivation**
I Pull Latest Docker image 
**Technical Design**

**Alternatives to Consider**

**Additional context**
I setup SANDBOX_TYPE="exec"

**Comment by rbren** [comment]
@ashrafML please open a new "bug" issue with the template filled out--we need to know what version you're running and what commands you ran to start the app
