### ISSUE TITLE
make build failed

### ISSUE THREAD

**Issue by he-aook** [OpenDevin/OpenDevin#1129]
#### Setup and configuration
**Current version**:

```
pwd " /opt/OpenDevin-main"
make build 
```

* Operating System:
  

**My config.toml and environment vars** (be sure to redact API keys):
```
LLM_MODEL="azure/gpt4-1109-XXXX"
LLM_API_KEY="320fXXXXXXXXXXXXXXXXa81e"
LLM_EMBEDDING_MODEL="azureopenai"
LLM_BASE_URL="https://ai-test-PPPP.openai.azure.com/"
LLM_DEPLOYMENT_NAME="gpt4-1106-LLLL"
LLM_API_VERSION="2024-02-15-VVVVV"
WORKSPACE_DIR="./workspace"
SANDBOX_TYPE="exec"
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
```

**Steps to Reproduce**:
1.
2.
6.

**Logs, error messages, and screenshots**:

**Comment by he-aook** [comment]
make build failed

**Comment by he-aook** [comment]
- Installing requests-oauthlib (2.0.0)
  - Installing rich (13.7.1)
  - Installing safetensors (0.4.2)
  - Installing scipy (1.13.0)
  - Installing shellingham (1.5.4)
  - Installing soupsieve (2.5)
  - Installing starlette (0.37.2)
  - Installing sympy (1.12)
  - Installing threadpoolctl (3.4.0)
  - Installing tokenizers (0.15.2)
  - Installing uvloop (0.19.0)
  - Installing watchfiles (0.21.0)
  - Installing websocket-client (1.7.0)
  - Installing websockets (12.0)
make[1]: *** [Makefile:84: install-python-dependencies] Killed
make: *** [Makefile:25: build] Error 2

**Comment by he-aook** [comment]
python 3.12.3

**Comment by he-aook** [comment]
我写了很多, 但是提交之后, 可能格式不对,我只能看到一部分的 ,提交

**Comment by yufansong** [comment]
You failed at `make install-python-dependencies `. Can you try this commands and show more error logs? Maybe you can try `poetry update` then do it again.

**Comment by rbren** [comment]
Given the new docker flow, I think we can close this one

**Comment by he-aook** [comment]
我试了很多次都不行,  这个先别关闭呀

**Comment by he-aook** [comment]
我最后发现是我的磁盘满了,

**Comment by seemyoung** [comment]
> 我最后发现我的磁盘已经装满了，

虚拟环境用python312， 安装poetry，node 20.11.0后make build没问题

**Comment by he-aook** [comment]
是, 我发现我磁盘报红, 然后增加硬盘之后,重新解压, 能正常构建启动了, 但是访问还有些问题, 正在调试
















在 2024-04-16 13:30:41，"cona" ***@***.***> 写道：

我最后发现我的磁盘已经装满了，

虚拟环境用python312， 安装poetry，node 20.11.0后make build没问题
