### ISSUE TITLE
App experiences performance Lag after startup

### ISSUE THREAD

**Issue by akhilvc10** [OpenDevin/OpenDevin#1130]
## Describe the bug
The app lags a lot after running, which the I believes is happening because the app is trying to load the entire app directory instead of just the workspace directory.

## Setup and configuration

**Current version**:
```Author: Edwards.Arno <138990495+Umpire2018@users.noreply.github.com>
Date:   Mon Apr 15 22:14:37 2024 +0800

    feat: add `question.md` template for community Q&A (#1115)
    
    * feat: add `question.md` template for community Q&A
    
    * Update .github/ISSUE_TEMPLATE/question.md
    
    ---------
    
    Co-authored-by: Robert Brennan <accounts@rbren.io>
```

**Operating System:**
- macOS Ventura 13.4

**My config.toml and environment vars** :
```toml
LLM_MODEL="gpt-4-0125-preview"
LLM_API_KEY="***"
LLM_EMBEDDING_MODEL="openai"
WORKSPACE_DIR="./workspace"
```

**My model and agent**:
* Model: gpt-4-turbo-2024-04-09
* Agent: MonologueAgent

**Commands I ran to install and run OpenDevin**:

Followed the instruction [here](https://github.com/OpenDevin/OpenDevin/blob/main/Development.md)

**Logs, error messages, and screenshots**:
No specific error messages

**Comment by yufansong** [comment]
> The app lags a lot after running

Could you please provide more detail? Lags after you run `make run` or other commands? Any logs?

**Comment by akhilvc10** [comment]
> > The app lags a lot after running
> 
> Could you please provide more detail? Lags after you run `make run` or other commands? Any logs?

Yes, I followed this [Development.md](https://github.com/OpenDevin/OpenDevin/blob/main/Development.md)

**Comment by foragerr** [comment]
Closing this in favor of https://github.com/OpenDevin/OpenDevin/issues/1136
