### ISSUE TITLE
LLM return non exist action in predefined list

### ISSUE THREAD

**Issue by yufansong** [OpenDevin/OpenDevin#1134]
**What problem or use case are you trying to solve?**
Maybe user proposed problem like 
```
'str' object has no attribute 'copy'
```
in #718, #1064, #1126. I should better figure out a way to improve it, or find a workaround to pass it.
Because it depends on the LLM response, I am still trying to find a way to reproduce it. Want to get the error LLM response to do futher investigation.

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**
1. Solution 1: From backend logic, can we add some retry logic if LLM return action not in predefine list?
2. Solution 2:When initialization the agent, can we add some prompts emphasize the action type? I have seen some case emphasize it in prompts can help. But currently we have no way to do experiments to evaluate it.
3. Solution 3: In solution 1, when we find error and retry, maybe we can add extra prompts to let LLM pay attention to providing a correct action in list.

**Describe alternatives you've considered**

**Additional context**

**Comment by yufansong** [comment]
I still cannot reproduce it locally. I have no chance to see the true response. Our code didn't log response, so no user can provide it. If some one can provide the true error `response` message, that will be very helpful.

**Comment by li-boxuan** [comment]
> When initialization the agent, can we add some prompts emphasize the action type?

I found https://www.youtube.com/watch?v=RJ6NN8Y-xok&ab_channel=OfirPress very worth watching. At 18:58, the author mentioned that they had to emphasize the current directory the agent is on, otherwise it would often mess up. This redundant piece of information seemingly helps the LLM strengthen its memory.

That being said, apparently powerful LLMs have no problem of remembering what actions are legal. Maybe you want to tune prompt only for "very weak" LLMs, but we don't have a framework to tune prompt per LLM (group) yet.

**Comment by yufansong** [comment]
> > When initialization the agent, can we add some prompts emphasize the action type?
> 
> I found https://www.youtube.com/watch?v=RJ6NN8Y-xok&ab_channel=OfirPress very worth watching. At 18:58, the author mentioned that they had to emphasize the current directory the agent is on, otherwise it would often mess up. This redundant piece of information seemingly helps the LLM strengthen its memory.
> 
> That being said, apparently powerful LLMs have no problem of remembering what actions are legal. Maybe you want to tune prompt only for "very weak" LLMs, but we don't have a framework to tune prompt per LLM (group) yet.

Yeah, I also see this case. This is what trigger me idea. I wonder whether add some redundant info in prompts can be helpful to solve it.
