### ISSUE TITLE
frontend setting modal options to customize monolouge agent character traits and summary verbosity

### ISSUE THREAD

**Issue by 808vita** [OpenDevin/OpenDevin#1135]
**What problem or use case are you trying to solve?**
Not able to set verbosity of summaries and other traits of the agent.

**Describe the UX of the solution you'd like**
ability to customize the monologue agent's traits and summary verbosity from the frontend.

**Do you have thoughts on the technical implementation?**
- dropdown / input / sliders on the frontend inside settings modal. 
- These can be passed along to the backend just like other selection settings ie. models , agent ,etc.
- on the backend those settings / custom prompt will be attached to the required prompts (action prompt , summary prompt)

**Additional context**
- introduces variations without breaking the agent.
- control the token usage to some extent
- can aid in: experimentations ,new agent building / discovery , prompt optimization , etc

**Comment by rbren** [comment]
I would suggest an architecture like this:
* Each agent provides a list of configurable parameters
* Each parameter needs a few fields:
  * `name`
  * `description`
  * `type` (number/string/text/enum)
  * `default`
* The UI ingests that list of parameters, and shows them in the settings modal when you select an agent
* Parameter settings are passed into the agent

This way it's very easy for agents to add new parameters, without also needing a UI change
