### ISSUE TITLE
Setting for workspace directory in the UI

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#1145]
**What problem or use case are you trying to solve?**
We removed the ability to choose your directory from the UI due to bugs

**Describe the UX of the solution you'd like**
In the settings modal, a dropdown of all directories inside the WORKSPACE_BASE folder.

**Do you have thoughts on the technical implementation?**
* A REST API that returns a list of all directories available in the WORKSPACE_BASE folder
  * probably shouldn't be recursive, or shouldn't recurse past anything that has a `.git` subdirectory, otherwise it will be too crowded
* We will need to pass up the directory through `initialize`, and plumb it into a few places:
  * the sandbox
  * the file operations in `./opendevin/actions/...`
  * probably somewhere else I'm forgetting

**Comment by iFurySt** [comment]
i think this and #1146  can be processed together. the setting modal deserves to be improved.

**Comment by enyst** [comment]
Github bot doesn't see a PR was added just 5 days ago. For the bot: there we go, this is a comment. 😅

**Comment by mamoodi** [comment]
If anyone happens to pick this up, the requirements are:
* The Settings page allows you to choose the workspace
* The folders being shown are the WORKSPACE_BASE set initially by the user and the folders available in the WORKSPACE_BASE folder. This list is static and does not change.
