### ISSUE TITLE
Add Openrouter API option

### ISSUE THREAD

**Issue by konradre** [OpenDevin/OpenDevin#115]
Openrouter hosts many of the latest models, both paid and open source, like Claude 3 Opus (unregulated beta). 

Moreover you can fund use of the paid ones in one place just by adding funds to Openrouter account.

**Comment by rbren** [comment]
Looks like LiteLLM supports OpenRouter: https://github.com/BerriAI/litellm

**Comment by rbren** [comment]
See here for how to select openrouter: https://github.com/OpenDevin/OpenDevin?tab=readme-ov-file#picking-a-model
