### ISSUE TITLE
Error when creating the Docker image for OpenDevin

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#1157]
#### Description of the Error
Error when creating the Docker image for OpenDevin

#### Setup and Configuration
**Current version**:
```
commit 516c9bf1e0ed6648fbf56b2c3384dd4526516f21 (HEAD -> main, origin/main, origin/HEAD)
Author: Robert Brennan <accounts@rbren.io>
Date:   Tue Apr 16 01:10:38 2024 +0200

    Revamp docker build process (#1121)

    * refactor docker building
    * change to buildx
    * disable branch filter
    * disable tags
    * matrix for building
    * fix branch filter
    * rename workflow
    * sanitize ref name
    * fix sanitization
    * fix source command
    * fix source command
    * add push arg
```

* Operating System: Windows 10, WSL2
* Docker Version: Docker Desktop for Windows, Version 4.18.0 (97476)

**Logs, Error Messages, and Screenshots**:
```
(base) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ export WORKSPACE_DIR=$(pwd)/workspace
(base) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ docker build -t opendevin-app -f container/Dockerfile .
[+] Building 0.0s (0/0)                                                                                  docker:default
ERROR: could not find container: stat container: no such file or directory
```

**My Configuration**:
No config.toml or environment variables set.

**Model and Agent**:
Not yet configured

**Installation Commands**:
```
git clone https://github.com/opendevin/opendevin.git
cd opendevin
export WORKSPACE_DIR=$(pwd)/workspace
docker build -t opendevin-app -f container/Dockerfile .
```

**Steps to Reproduce**:
1. Clone the Git repository
2. Change to the directory
3. Set the WORKSPACE_DIR environment variable
4. Create the Docker image with `docker build -t opendevin-app -f container/Dockerfile .`

#### Additional Context
The current version being used is the one with the commit 516c9bf1e0ed6648fbf56b2c3384dd4526516f21, which revamps the Docker build process.

I have already tried reinstalling Docker, using the latest version, restarting the Docker service, and adjusting the Docker daemon configuration, but the error "ERROR: could not find container: stat container: no such file or directory" persists.

The WSL2 integration is enabled in the Docker settings.

Please provide me with further instructions or suggestions on what I could try next to solve this problem. There might be changes in the new version that are causing this error.

**Comment by SmartManoj** [comment]
Reason for building the image instead of downloading it?

https://www.coreycleary.me/why-would-you-download-a-docker-image-vs-just-building-from-the-dockerfile-for-local-dev/

**Comment by foragerr** [comment]
The issue is exactly what it says. There is no directory called container anymore. It's now called containers, and the app dockerfile is in `containers/app`

I also agree with @SmartManoj , just pull the[ official image](https://github.com/OpenDevin/OpenDevin/pkgs/container/opendevin), you don't need to build it anymore (Hooray!)

Did we miss a README update?
