### ISSUE TITLE
Windows 10 WSL2 config 

### ISSUE THREAD

**Issue by thazalega** [OpenDevin/OpenDevin#1160]
## Describe your question

I'm not sure but looks like that on Windows 10 its not possible to set the right network settings?

## Additional context

In the docs under "Additional Notes for WSL2 Users:" 

![image](https://github.com/OpenDevin/OpenDevin/assets/108468282/fef0b301-c4f4-41c4-86d1-074f6d1e44f4)

i found the fix for my problem but it seems it is not 
possible for me because the Network settings requires Windows 11. If this is the case maybe it would be good 
to make a node that this is not possible.  

![image](https://github.com/OpenDevin/OpenDevin/assets/108468282/20bbfd38-7904-419f-8924-ed8f81238893)

**Comment by rahulvaddepalli2** [comment]
Enabling mirrored mode networking will 'mirror' the network interfaces that you have on Windows into Linux, looks like you just have to find an alternate means of doing so. You can opt for WSL instead of WSL2 since you're on Windows 10.

**Comment by thazalega** [comment]
> Enabling mirrored mode networking will 'mirror' the network interfaces that you have on Windows into Linux, looks like you just have to find an alternate means of doing so. You can opt for WSL instead of WSL2 since you're on Windows 10.

Thank you for the answer.
WSL never worked really on my system only WSL2.

**Comment by thazalega** [comment]
> Enabling mirrored mode networking will 'mirror' the network interfaces that you have on Windows into Linux, looks like you just have to find an alternate means of doing so. You can opt for WSL instead of WSL2 since you're on Windows 10.

Thank you for the answer.
WSL never worked really on my system only WSL2.
