### ISSUE TITLE
DogFood: Use OpenDevin to review PRs

### ISSUE THREAD

**Issue by li-boxuan** [OpenDevin/OpenDevin#1178]
**What problem or use case are you trying to solve?**

It would be nice if we could let OpenDevin review PRs in OpenDevin repo. Inspired by https://github.com/OpenDevin/OpenDevin/issues/1067.

**Describe the UX of the solution you'd like**

No UX is needed. We need a GitHub workflow file.

**Do you have thoughts on the technical implementation?**

Reviewing PRs sounds easy, but in some sense, it's harder than creating a PR. To review a PR, the agent essentially needs to:
1) Understand the patch
2) Fix/Modify the patch
3) Verify the patch works
4) Suggest the updated patch

Of course, at the moment, we can simply let the agent review the patch and post a single review comment. Eventually it shall be able to submit review at appropriate lines, and/or even `Add a suggestion` (one-liner code changes that can be directly applied on GitHub GUI) directly.

**Additional context**

I am working on this. Will come up with a preliminary version soon.

**Comment by PierrunoYT** [comment]
I think @rbren also opened something similar.
