### ISSUE TITLE
Error running in grok

### ISSUE THREAD

**Issue by pegostar** [OpenDevin/OpenDevin#1185]
Runnig OpenDevin with docker in windows, with this parameters:

docker run -e LLM_API_KEY="gsk_GD....rmoL" -e LLM_MODEL="groq/llama2-70b-4096" -e WORKSPACE_DIR="C:\Projects\IA\Workspace" -e WORKSPACE_MOUNT_PATH="C:\Projects\IA\Workspace" -v "C:\Projects\IA\Workspace":/opt/workspace_base -v /var/run/docker.sock:/var/run/docker.sock -p 3000:3000 ghcr.io/opendevin/opendevin:latest

Receive this error:
<img width="308" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/19372922/773ddd1e-89db-4c6b-bd66-5198abbba3b8">

**Comment by rbren** [comment]
@pegostar what happens if you run
```
docker run -e LLM_API_KEY="gsk_GD....rmoL" -e LLM_MODEL="groq/llama2-70b-4096" -e WORKSPACE_DIR="C:\Projects\IA\Workspace" -e WORKSPACE_MOUNT_PATH="C:\Projects\IA\Workspace" -v "C:\Projects\IA\Workspace":/opt/workspace_base -v /var/run/docker.sock:/var/run/docker.sock -p 3000:3000 ghcr.io/opendevin/opendevin:main python opendevin/main.py --task "write a bash script that prints hello"
```

**Comment by rbren** [comment]
Ahh--Grok is returning bad responses. This is an issue with the quality of Grok, so unfortunately there's not much we can do here.

Claude 3 and GPT-4 seem to work best for now. Hopefully Grok and others start to catch up on quality
