### ISSUE TITLE
Error in setting up the OpenDevin 

### ISSUE THREAD

**Issue by 20481A5450** [OpenDevin/OpenDevin#1186]
#### the bug
I was trying to run OpenDevin in my local system, where I encountered an error while configuring the front-end part. This was  regarding the build wheels of chromadb as the requirements.text file was missing from the project directory. I can't find it anywhere in the open project. So it made me to install the packages manually.

#### Setup and configuration
**Current version[python]**: 3.12.0
**My operating system**: Windwos OS

I was trying to run the code:
 ```bash
uvicorn opendevin.server.listen:app --port 3000
```

**Logs, error messages, and screenshots**:

![Screenshot 2024-04-17 211156](https://github.com/OpenDevin/OpenDevin/assets/99806742/411853fd-9412-4552-a501-bce1ee058151)

#### Additional Context
Any solutions to solve this error?

**Comment by rbren** [comment]
@20481A5450 we don't support windows without WSL.

Any reason you're trying to build the project rather than use the Docker image?

**Comment by 20481A5450** [comment]
Thanks @rbren  for your support
