### ISSUE TITLE
Docker build is flaky for the app container

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#1192]
#### Describe the bug

The gchr GitHub action often fails to build the frontend, due to npm connectivity errors.

See e.g. https://github.com/OpenDevin/OpenDevin/actions/runs/8726482243/job/23941851758

#### Setup and configuration
N/A

#### Additional Context
Seems like maybe we're not the only ones: https://github.com/actions/runner-images/issues/3737

**Comment by arjuuuuunnnnn** [comment]
It works for stable network connection
and also 
try `npm cache clean --force`

**Comment by rbren** [comment]
This seems to be solved with the npm update!
