### ISSUE TITLE
Custom dependencies in sandbox Docker image

### ISSUE THREAD

**Issue by Samuele458** [OpenDevin/OpenDevin#1196]
## Describe your question

I would like to understand what the standard procedure is for making the sandbox have custom dependencies.

In many cases where execution fails it is due to missing programs/dependencies within the `sandbox` image.

It would therefore be convenient to have the possibility to carry out an initial customization (in my case, it would be convenient to configure a node.js/nvm environment, the agent often fails when trying to install them).

Currently, what would be the most effective/consistent way to carry out this type of customization?

**Comment by foragerr** [comment]
While it's likely true that the [sandbox image](https://github.com/OpenDevin/OpenDevin/blob/main/containers/sandbox/Dockerfile) could have more things pre-installed, it is hard to come up with a "complete" setup that will cover everyone's need.

To meet your specific need though, you can make your own custom image, starting FROM the [sandbox image](https://github.com/OpenDevin/OpenDevin/pkgs/container/sandbox).

and then adding an env var or config file entry for [`SANDBOX_CONTAINER_IMAGE`](https://github.com/OpenDevin/OpenDevin/blob/main/opendevin/schema/config.py#L11)

**Comment by rbren** [comment]
☝️ foragerr nailed it. Setting `SANDBOX_CONTAINER_IMAGE` is the way to go. There are tons of pre-built images out there for the language/stack of your choice
