### ISSUE TITLE
ERROR:root:<class 'ImportError'>: cannot import name 'spawn' from 'pexpect' (C:\Users\muhammad_anas\.virtualenvs\OpenDevin-59qZ_dP-\Lib\site-packages\pexpect\__init__.py)

### ISSUE THREAD

**Issue by muhammad-anas087** [OpenDevin/OpenDevin#1205]
#### Describe the bug
 File "C:\Users\muhammad_anas\.virtualenvs\OpenDevin-59qZ_dP-\Lib\site-packages\pexpect\pxssh.py", line 23, in <module>
    from pexpect import ExceptionPexpect, TIMEOUT, EOF, spawn

ERROR:root:<class 'ImportError'>: cannot import name 'spawn' from 'pexpect' (C:\Users\muhammad_anas\.virtualenvs\OpenDevin-59qZ_dP-\Lib\site-packages\pexpect\__init__.py)

#### Setup and configuration
**Current version**:

```
commit 426f3871235ce7e98ef60c0122f5de91c4974547 (HEAD -> main, origin/main, origin/HEAD)
Author: sp.wack <83104063+amanape@users.noreply.github.com>
Date:   Wed Apr 17 20:55:17 2024 +0300

    setup env for controlled integration tests with redux (#1180)
```

**My operating system**: Windows 10

**My environment vars and other configuration** (be sure to redact API keys):
```bash
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
uvicorn opendevin.server.listen:app --port 3000
```

**Steps to Reproduce**:
1.
2.
3.

**Logs, error messages, and screenshots**:
![image](https://github.com/OpenDevin/OpenDevin/assets/167299158/4d07a404-b716-4598-8554-6161b54aaa82)

**Comment by rbren** [comment]
Deduping with https://github.com/OpenDevin/OpenDevin/issues/1156

**Comment by rbren** [comment]
Setting SANDBOX_TYPE=exec may fix this
