### ISSUE TITLE
Error when running the Docker container for OpenDevin - Agent controller fails to establish connection to host

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#1207]
Here's the updated bug report with the new commit information:

#### Description of the Bug
Error when running the Docker container for OpenDevin - Agent controller fails to establish connection to host

#### Setup and Configuration
**Current Version**:
```
commit 6b0408d47ca06153663424d3befb76f33cad0300 (HEAD -> main, origin/main, origin/HEAD)
Author: Robert Brennan <accounts@rbren.io>
Date:   Thu Apr 18 07:31:39 2024 -0400

    use threading to insert docs into the db (#1191)
```

* Operating System: Windows 10, WSL2
* Docker Version: Docker Desktop for Windows, Version 4.18.0 (97476)

**Logs, Error Messages, and Screenshots**:
```
(base) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ docker run \
    -e LLM_API_KEY \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR \
    -v $WORKSPACE_DIR:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    ghcr.io/opendevin/opendevin:latest
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     172.17.0.1:60412 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     172.17.0.1:60412 - "GET /index.html HTTP/1.1" 200 OK
INFO:     172.17.0.1:60412 - "GET /assets/index-DiDnKupX.js HTTP/1.1" 200 OK
INFO:     172.17.0.1:60422 - "GET /assets/index-CVqJeQJv.css HTTP/1.1" 200 OK
INFO:     ('172.17.0.1', 60436) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJiMWU1ZDM1My05MDM1LTRiYTEtOGEwMC04NGZmNDU0ZWMxYTEifQ.VHFX1AwnLJprhuTP_CHGpOpUBZNlruNT6Guzt1y2G9k" [accepted]
INFO:     connection open
Starting loop_recv for sid: b1e5d353-9035-4ba1-8a00-84ff454ec1a1
INFO:     172.17.0.1:60412 - "GET /locales/en/translation.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:60422 - "GET /locales/de/translation.json HTTP/1.1" 200 OK
INFO:     172.17.0.1:60444 - "GET /apple-touch-icon.png HTTP/1.1" 200 OK
INFO:     172.17.0.1:60422 - "GET /favicon-32x32.png HTTP/1.1" 200 OK
INFO:     172.17.0.1:60412 - "GET /api/refresh-files HTTP/1.1" 200 OK
INFO:     172.17.0.1:60422 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     172.17.0.1:60412 - "GET /api/configurations HTTP/1.1" 200 OK

12:22:06 - opendevin:INFO: ssh_box.py:271 - Container stopped
12:22:06 - opendevin:WARNING: ssh_box.py:283 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
12:22:06 - opendevin:INFO: ssh_box.py:309 - Container started
12:22:07 - opendevin:INFO: ssh_box.py:326 - waiting for container to start: 1, container status: running
12:22:07 - opendevin:INFO: ssh_box.py:161 - Connecting to root@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 50469 root@host.docker.internal` with the password '709f4a59-8669-4567-8fae-b45889dfa845' and report the issue on GitHub.
12:22:07 - opendevin:ERROR: agent.py:127 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 118, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 47, in __init__
    self.action_manager = ActionManager(self.id, container_image)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/action_manager.py", line 36, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/app/opendevin/sandbox/ssh_box.py", line 90, in __init__
    self.start_ssh_session()
  File "/app/opendevin/sandbox/ssh_box.py", line 164, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host

Mounting workspace directory:  /mnt/c/Users/pierr/OpenDevin/workspace
INFO:     172.17.0.1:60422 - "GET /workbox-c06b064f.js HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:60412 - "GET /sw.js HTTP/1.1" 404 Not Found
```

**My Configuration**:
No config.toml or environment variables set.

**Model and Agent**:
Not configured yet

**Installation Commands**:
```
git clone https://github.com/opendevin/opendevin.git
cd opendevin
export WORKSPACE_DIR=$(pwd)/workspace
docker run \
    -e LLM_API_KEY \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR \
    -v $WORKSPACE_DIR:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    ghcr.io/opendevin/opendevin:latest
```

**Steps to Reproduce**:
1. Clone the Git repository
2. Change into the directory
3. Set the WORKSPACE_DIR environment variable
4. Run the Docker container with the provided command

#### Additional Context
The current version being used is the one with the commit 6b0408d47ca06153663424d3befb76f33cad0300, which introduces the use of threading to insert documents into the database.

The Docker container for OpenDevin starts successfully, and the application is running on http://0.0.0.0:3000. However, the agent controller fails to establish a connection to the host, resulting in the error "Could not establish connection to host".

This issue seems to be related to a known problem with the `network_mode='host'` option not being supported on macOS, which is causing the agent controller to fail to establish a connection to the host. The logs mention: "Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information."

**Comment by grewhit25** [comment]
It seems the problem may be related to  ‘host.docker.internal’ and SSH_HOSTNAME not being set.
which, for me,  I have temporary worked around the connection issue by setting it to my Docker host IP like in this example:

 ```bash
 -e SSH_HOSTNAME=$(ip route get 8.8.8.8 | head -1 | awk '{print $7}') -e SSH_HOSTNAME=$(ip route get 8.8.8.8 | head -1 | awk '{print $7}')
 ```

You could try is it see if it helps.

**Comment by rbren** [comment]
Side note: newest recommendation is to run `ghcr.io/opendevin/opendevin:main` instead of `ghcr.io/opendevin/opendevin:latest`. The latter might contain unmerged changes.


adding `-e SANDBOX_TYPE=exec` might help

**Comment by rbren** [comment]
@PierrunoYT had you run inside of docker before on this machine? Nothing has changed recently here...

**Comment by rbren** [comment]
Deduping with https://github.com/OpenDevin/OpenDevin/issues/1156

**Comment by PierrunoYT** [comment]
> @PierrunoYT had you run inside of docker before on this machine? Nothing has changed recently here...

I worked a few days ago but I pulled everything today again and then this happens. I does not downloaded the Docker Image

**Comment by djaym7** [comment]
21:02:31 - opendevin:INFO: ssh_box.py:329 - waiting for container to start: 1, container status: running
21:02:31 - opendevin:INFO: ssh_box.py:163 - Connecting to root@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 47803 root@host.docker.internal` with the password '7935a9c0-1aa2-4d02-803a-e2cc1b12f036' and report the issue on GitHub.
21:02:31 - opendevin:ERROR: agent.py:157 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 148, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 54, in __init__
    self.action_manager = ActionManager(self.id, container_image)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/action_manager.py", line 36, in __init__
    self.sandbox = DockerSSHBox(
                   ^^^^^^^^^^^^^
  File "/app/opendevin/sandbox/docker/ssh_box.py", line 92, in __init__
    self.start_ssh_session()
  File "/app/opendevin/sandbox/docker/ssh_box.py", line 166, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
Mounting workspace directory:  /home/jdesa/Agent/OpenDevin/workspace
