### ISSUE TITLE
WORKSPACE_DIR is ignored / local storage overriding WORKSPACE_DIR

### ISSUE THREAD

**Issue by tpsjr7** [OpenDevin/OpenDevin#1237]
#### Describe the bug
in my config.toml I set WORKSPACE_DIR to anything, but it is always showing the entire tree of OpenDevin source code repo in the workspace window.

#### Setup and configuration
**Current version**:
```bash
0.3.1
```

**My operating system**:
WSL2

**My environment vars and other configuration** (be sure to redact API keys):
```bash
```

**My model and agent** (you can see these settings in the UI):
* Model: 
* Agent:

**Commands I ran to install and run OpenDevin**:
```
make start-frontend
make start-backend
```

**Steps to Reproduce**:
in my config.toml I set WORKSPACE_DIR to anything
Observe that it's not respected and  the entire tree of OpenDevin source code repo in the workspace window.

#### Additional Context
running locally, not with docker.

I think it is caused because the browswer local storage seems to be overrideing the config variables.
in the browser local storage I see ALL_SETTINGS as this:
```
{"LLM_BASE_URL":"http://0.0.0.0:5000/v1","WORKSPACE_BASE":"/home/user/code/OpenDevin","WORKSPACE_MOUNT_PATH":"null","WORKSPACE_MOUNT_REWRITE":"null","LLM_MODEL":"openai/alpindale_Mistral-7B-v0.2-hf","SANDBOX_CONTAINER_IMAGE":"ghcr.io/opendevin/sandbox","RUN_AS_DEVIN":"true","LLM_EMBEDDING_MODEL":"lokal","LLM_DEPLOYMENT_NAME":"null","LLM_API_VERSION":"null","LLM_NUM_RETRIES":"1","LLM_COOLDOWN_TIME":"1","MAX_ITERATIONS":"10000","MAX_CHARS":"5000000","AGENT":"MonologueAgent","SANDBOX_TYPE":"ssh","USE_HOST_NETWORK":"false","SSH_HOSTNAME":"localhost","DISABLE_COLOR":"false"}
```

**Comment by tpsjr7** [comment]
Never mind on this. I realize that it's supposed to use WORKSPACE_BASE not WORKSPACE_DIR as the variable to set. 

Also if you try to use an absolute path in WORKSPACE_BASE like "/tmp/workspace" it appears to make it a relative path instead like "./tmp/workspace"

**Comment by rbren** [comment]
@tpsjr7 sorry for the confusion--`WORKSPACE_DIR` is no longer supported (it was very buggy).

`WORKSPACE_BASE` is the new variable to set your directory. In the future, we'll allow setting subdirectories of that via the UI.

**Comment by rbren** [comment]
> Also if you try to use an absolute path in WORKSPACE_BASE like "/tmp/workspace" it appears to make it a relative path instead like "./tmp/workspace"

Where are you seeing this? It should always be absolute...

**Comment by tpsjr7** [comment]
> > Also if you try to use an absolute path in WORKSPACE_BASE like "/tmp/workspace" it appears to make it a relative path instead like "./tmp/workspace"
> 
> Where are you seeing this? It should always be absolute...

sorry, had a mixup, you responded before I was about to delete that comment. Thank you.
