### ISSUE TITLE
FileReadAction: 'AgentController' object has no attribute 'command_manager' 

### ISSUE THREAD

**Issue by tpsjr7** [OpenDevin/OpenDevin#1239]
#### Describe the bug
I have the model running, and it's doing mostly useful stuff, but it gets to a state where it reports and error 

Oops. Something went wrong: 'AgentController' object has no attribute 'command_manager'

Looks to be related to FileReadAction

#### Setup and configuration
**Current version**:
```bash
d61fdb8bba9ecc6fbe
```

**My operating system**:
WSL2

**My model and agent** (you can see these settings in the UI):
* Model: local
* Agent: monologue

**Commands I ran to install and run OpenDevin**:
```
make start-frontend
make start-backend
```

**Steps to Reproduce**:
Make it trigger a FileReadAction it appears

**Logs, error messages, and screenshots**:
14:33:08 - PLAN
in the workspace directory there is list.txt can you sort it and put it in a new file.
14:33:12 - ACTION
FileReadAction(path='list.txt', start=0, end=-1, thoughts='', action=<ActionType.READ: 'read'>)
14:33:12 - opendevin:ERROR: action_manager.py:52 - 'AgentController' object has no attribute 'command_manager'
14:33:12 - OBSERVATION
'AgentController' object has no attribute 'command_manager'

**Comment by rbren** [comment]
Whoops this is a merge issue. on it
