### ISSUE TITLE
OpenDevin address binding error.

### ISSUE THREAD

**Issue by mahiatlinux** [OpenDevin/OpenDevin#1244]
#### Describe the bug

When starting OpenDevin with `make run`, it starts wthen after a few seconds it gives this error:

![image](https://github.com/OpenDevin/OpenDevin/assets/110882203/63adf6bc-f317-43ee-b6a7-38974abfa0f2)

Even after killing all processes on `http://localhost:3001/` it is still showing that error.

#### Setup and configuration
**Current version**:
```bash
commit ca1d53c161583c51acffee5be8cfa58416ad79ab (HEAD -> main, origin/main, origin/HEAD)
Author: sp.wack <83104063+amanape@users.noreply.github.com>
Date:   Fri Apr 19 02:19:57 2024 +0300

    fix(frontend): improve the <Input /> component (#1195)
    
    * create a better chat input component
    
    * remove the useInputComposition hook

```

**My operating system**:

I am using Ubuntu 22.04.

**My environment vars and other configuration** (be sure to redact API keys):
```bash
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
Development.md
```

**Steps to Reproduce**:
1. Run make run
2. Get error within a few seconds.

**Comment by SmartManoj** [comment]
you need to kill 3000 (backend port) not 3001

**Comment by mahiatlinux** [comment]
Yep! Killing port 3000 works.
