### ISSUE TITLE
[Bug]: OpenDevin: "Error creating controller. Check if Docker is running using docker ps."

### ISSUE THREAD

**Issue by LeonidUIN** [OpenDevin/OpenDevin#1260]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/Troubleshooting.md
- [X] I have checked the existing issues.

### Describe the bug

Hello. I launch Docker and open OpenDevin at “[http://localhost:3000/index.html”](http://localhost:3000/index.html%E2%80%9D). The OpenDevin interface itself displays normally, but it says "Error creating controller. Check if Docker is running using docker ps.", "Agent is not running. Wait a second..." and "I did not recognize this action: terminal." I saw that people in the comments (https://github.com/OpenDevin/OpenDevin/issues/974) write that you can write the symbol "SANDBOX_TYPE=exec" in the file "config.toml" and expect that this should fix the problem, but I cannot find the file "config.toml" (the search function does not helps) to do this. Help me please. Tell me where this file is located. If anything, I have a Mac.

### Current Version

```bash
ghcr.io/opendevin/opendevin:0.3.1
```

### Installation and Configuration

```bash
any commands
```

**Comment by rbren** [comment]
@LeonidUIN this is literally the first issue in Troubleshooting.md 😅 please follow the instructions when filing new issues.

https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/Troubleshooting.md#unable-to-connect-to-docker

**Comment by gbenaa** [comment]
Hi, has this page moved? Link to the troubleshooting page seems broken.
https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/Troubleshooting.md#unable-to-connect-to-docker

Thanks

**Comment by rbren** [comment]
Whoops it's here now: https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
