### ISSUE TITLE
[Bug]: Model selection from settings is ignored (OpenAIException - Error code: 401)

### ISSUE THREAD

**Issue by dagelf** [OpenDevin/OpenDevin#1261]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/Troubleshooting.md
- [X] I have checked the existing issues.

### Describe the bug

When I set the correct key, and choose the correct model in settings, it still tries to use GPT4 with my key to another platform. 

### Current Version

```bash
ghcr.io/opendevin/opendevin:0.3.1
```

### Installation and Configuration

```bash
docker run     -e LLM_API_KEY     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR     -v $WORKSPACE_DIR:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     --add-host host.docker.internal=host-gateway     ghcr.io/opendevin/opendevin:0.3.1
```

### Reproduction Steps

1. set API key in env
2. docker run
3. Send first instruction

### Logs, Errors, Screenshots, and Additional Context

```
Error during task loop: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: gsk_vKbB********************************************PIaY. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
```

**Comment by dagelf** [comment]
Of course works if you run with:

```
docker run  -e OPENAI_API_BASE  -e LLM_MODEL  -e LLM_BASE_URL   -e LLM_API_KEY     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR     -v $WORKSPACE_DIR:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     --add-host host.docker.internal=host-gateway     ghcr.io/opendevin/opendevin:0.3.1
```

But it shouldn't expose settings that doesn't work!

**Comment by enyst** [comment]
Just to clarify, please: you say you chose model in settings, but in the reproduction steps it's only set key and run? The app has some fallback if you set nothing as model.

It should work with the UI choice if you made it. Was it a different run?

**Comment by rbren** [comment]
@dagelf we have an `LLM_MODEL` for running OpenDevin programatically (i.e. `python opendevin/main.py`), but we don't encourage setting that for running the full application.

Which model did you choose in the UI?

**Comment by zhonggegege** [comment]
I also have the same problem. Even if the server address of lm-studio is set in the environment variable, after starting the ui and selecting a model in the interface, it still prompts that the wrong openai key is used.

---------------------
git pull
export LLM_API_KEY="lm-studio"
export WORKSPACE_BASE=/home/agetn/OpenDevin/workspace
export LLM_BASE_URL="http://192.168.0.76:1234/v1"
docker run \
>     -e LLM_API_KEY \
>     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
>     -v $WORKSPACE_BASE:/opt/workspace_base \
>     -v /var/run/docker.sock:/var/run/docker.sock \
>     -p 3000:3000 \
>     --add-host host.docker.internal=host-gateway \
>     ghcr.io/opendevin/opendevin:0.3.1

litellm.exceptions.AuthenticationError: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: lm-studio. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

**Comment by dagelf** [comment]
Hi, same run, no matter what model I choose, it always falls back on the
same model, whether its given in the environment or not.

**Comment by dagelf** [comment]
Yes this looks related

**Comment by zhonggegege** [comment]
![image](https://github.com/OpenDevin/OpenDevin/assets/152971528/57ae8da3-6d3a-4269-baea-da0125714b7f)
Setting the environment variable "LLM_BASE_URL" solved the 401 problem by
"docker run\
     -e LLM_API_KEY \
     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
-e LLM_BASE_URL="http://192.168.0.76:1234" \
     -v /var/run/docker.sock:/var/run/docker.sock \
     -p 3000:3000 \
--add-host host.docker.internal=host-gateway \
     ghcr.io/opendevin/opendevin:0.3.1"
The test webui can be linked to the lm-studio server, but an error still occurs:
"TypeError: 'NoneType' object is not iterable"

These errors occur no matter how the model of the front-end UI is set, for example: "MaziyarPanahi/WizardLM-2-7B-GGUF/WizardLM-2-7B.Q6_K.gguf", "MaziyarPanahi/WizardLM-2-7B-GGUF"

**Comment by zhonggegege** [comment]
> 是的，这看起来相关

docker run \
    -e LLM_API_KEY \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
	-e LLM_BASE_URL="http://192.168.0.76:1234/v1" \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
	--add-host host.docker.internal=host-gateway \
    ghcr.io/opendevin/opendevin:0.3.1

**Comment by zhonggegege** [comment]
![image](https://github.com/OpenDevin/OpenDevin/assets/152971528/d61f8a54-f5fc-4c5d-b294-b37f705666a8)
The web UI selects a model, but still requests the wrong model when requesting the endpoint.

**Comment by enyst** [comment]
@zhonggegege are you running the latest version? Please use 0.4.0, the latest released version, or pull from git if that's how you're running.

It might also be useful to clear your local storage in the browser, if you choose from the UI and it doesn't seem to get applied, although it shouldn't be necessary...

**Comment by enyst** [comment]
@dagelf Can you please upgrade to 0.4.0? You were using 0.3.1 before. And if you're running with an UI (as you are), choose the model in the UI.

**Comment by zhonggegege** [comment]
> @dagelf Can you please upgrade to 0.4.0? You were using 0.3.1 before. And if you're running with an UI (as you are), choose the model in the UI.

thank you for your reply. Yes, I am using the latest 0.4.0 and pulling the latest repository code. I've described a complete error of multiple attempts here:[#1380](https://github.com/OpenDevin/OpenDevin/issues/1380)

**Comment by mamoodi** [comment]
Looks like this issue is resolved in the newer versions. Closing. Please reopen if you feel otherwise.
