### ISSUE TITLE
[Bug]: Minimum docker version should be documented

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#1275]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/Troubleshooting.md
- [X] I have checked the existing issues.

### Describe the bug

When I run with the docker command recommended in the README, I get the following error:

```bash
$ docker run -e LLM_API_KEY -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR -v $WORKSPACE_DIR:/opt/workspace_base -v /var/run/docker.sock:/var/run/docker.sock -p 3000:3000 --add-host host.docker.internal=host-gateway ghcr.io/opendevin/opendevin:0.3.1
invalid argument "host.docker.internal=host-gateway" for "--add-host" flag: bad format for add-host: "host.docker.internal=host-gateway"
```

### Current Version

* Docker: `Docker version 20.10.21, build baeda1f`
* Image: `ghcr.io/opendevin/opendevin:0.3.1`

### Installation and Configuration

```bash
export LLM_API_KEY="sk-..."
export WORKSPACE_DIR=$(pwd)/workspace
```

**Comment by neubig** [comment]
This was an issue of docker being too old, upgrading to the most recent version `25.0.3` fixed it. We should probably document a minimum docker version.

**Comment by Umpire2018** [comment]
If i found a issue which i can come up with a fix, i will open a pr. 

:)

**Comment by xuhe2** [comment]
my docker version is `20.10.24`, I use `--add-host host.docker.internal:host-gateway` arg, it works.
in old version, the syntax is different for this arg, the README.md can add a tip for this trouble

**Comment by rbren** [comment]
Hmm--we used to have this documented right in the readme. Must have gotten lost in the switch to the docs site
