### ISSUE TITLE
[Feature] "open pull request" capability

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#1281]
**What problem or use case are you trying to solve?**

We would like to solve github issues using OpenDevin: https://github.com/OpenDevin/OpenDevin/issues/1067

OpenDevin can get most of the way there, but when it tries to "git push" it will not work, because it does not have appropriate permissions to push to github and send a PR.

**Describe the UX of the solution you'd like**

To fix this, I think we should probably add an `OpenPullRequest` action to our agents.

1. In the case where the user has not configured github credentials, this will trigger a message to the user that in order for the agent to proceed, they should enter their github credentials or cancel.
2. In the case where the user has configured github credentials, this will send a PR to a branch, and open up the github PR page for the user to review the PR before they actually click the "submit pull request" button themselves.

**Describe alternatives you've considered**

Another althernative is to let OpenDevin actually do the PR itself, but this is too risky.

**Comment by temotskipa** [comment]
>but this is too risky

I mean, you could just not approve the PR if the generated code is somehow malicious. Which is extremely unlikely.

**Comment by neubig** [comment]
That's true, but OpenDevin could also accidentally push something directly to the main branch without sending a PR. I'd kinda like to avoid giving Devin credentials to do something on github directly and have access be somewhat more controlled.

**Comment by neubig** [comment]
This is fixed by documentation here: https://opendevin.github.io/OpenDevin/faq
