### ISSUE TITLE
Try to Local LLM by docker. but it does not work.

### ISSUE THREAD

**Issue by zhaoweihan2017** [OpenDevin/OpenDevin#1283]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/Troubleshooting.md
- [X] I have checked the existing issues.

### Describe the bug

i want to use local ollama model. when i install openDevin by docker and follow the guide here: https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/LocalLLMs.md ,but it does not work.

### Current Version

```bash
1、ghcr.io/opendevin/opendevin:main
2、docker: Docker version 25.0.3
3、ollama list
  gemma:latest          	a72c7f4d0a15	5.0 GB	2 weeks ago	
  llama2:13b-chat-q4_K_M	87727269f62c	7.9 GB	9 days ago 	
  llama2:7b             	78e26419b446	3.8 GB	2 weeks ago	
  mistral:latest        	61e88e884507	4.1 GB	2 weeks ago	
  openchat:latest       	537a4e03b649	4.1 GB	2 weeks ago
```

### Installation and Configuration

```bash
1、export WORKSPACE_DIR="/data/workplace"
2、docker run \
    --add-host host.docker.internal=host-gateway \
    -e LLM_API_KEY="ollama" \
    -e LLM_BASE_URL="http://host.docker.internal:11434" \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR \
    -v $WORKSPACE_DIR:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    ghcr.io/opendevin/opendevin:main
```

### Model and Agent

model：ollama/llama2
agent：CodeActAgent

### Reproduction Steps

1、export WORKSPACE_DIR="/data/workplace"
2、docker run \
    --add-host host.docker.internal=host-gateway \
    -e LLM_API_KEY="ollama" \
    -e LLM_BASE_URL="http://host.docker.internal:11434" \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR \
    -v $WORKSPACE_DIR:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    ghcr.io/opendevin/opendevin:main
3、open the browser by http://{ip}:3000/index.html
     
     select the model to ollama/llama2
     select the agent to CodeActAgent
4、write the "hello"， the window shows that: Oops. Something went wrong: Expecting CmdRunAction or AgentEchoAction for Action

extra info：
i try to use follw command to test ollama

curl http://192.168.120.17:11434/api/generate -d '{
  "model": "llama2:7b",
  "prompt":"hello"
}'

i got available response.

### Logs, Errors, Screenshots, and Additional Context

INFO:     {ip}:65458 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO:     {ip}:65457 - "GET /api/agents HTTP/1.1" 200 OK
06:20:14 - opendevin:INFO: llm.py:25 - Initializing LLM with model: ollama/llama2
06:20:16 - opendevin:INFO: ssh_box.py:271 - Container stopped
06:20:16 - opendevin:WARNING: ssh_box.py:283 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
06:20:16 - opendevin:INFO: ssh_box.py:309 - Container started
06:20:17 - opendevin:INFO: ssh_box.py:326 - waiting for container to start: 1, container status: running
06:20:17 - opendevin:INFO: ssh_box.py:161 - Connecting to root@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 50717 root@host.docker.internal` with the password '7f506fac-6a72-4d44-bae0-7fc93997b910' and report the issue on GitHub.
Mounting workspace directory:  /data/workplace
INFO:     {ip}:65500 - "GET /index.html HTTP/1.1" 304 Not Modified
06:20:20 - opendevin:INFO: session.py:39 - WebSocket disconnected, sid: 1423f92c-78b5-4293-8ffa-14f929e76ba3
INFO:     connection closed
INFO:     ('{ip}', 65504) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIxNDIzZjkyYy03OGI1LTQyOTMtOGZmYS0xNGY5MjllNzZiYTMifQ.xhxONeNA8JqzaezRFOtXaDtWRKk3Csf37reiif8hH0M" [accepted]
INFO:     connection open
06:20:21 - opendevin:INFO: llm.py:25 - Initializing LLM with model: ollama/llama2
06:20:22 - opendevin:INFO: ssh_box.py:271 - Container stopped
06:20:22 - opendevin:WARNING: ssh_box.py:283 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
06:20:23 - opendevin:INFO: ssh_box.py:309 - Container started
06:20:24 - opendevin:INFO: ssh_box.py:326 - waiting for container to start: 1, container status: running
06:20:24 - opendevin:INFO: ssh_box.py:161 - Connecting to root@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 37288 root@host.docker.internal` with the password '84b9b73d-771f-41d8-bc37-353b7fa6064f' and report the issue on GitHub.
Starting loop_recv for sid: 1423f92c-78b5-4293-8ffa-14f929e76ba3
Mounting workspace directory:  /data/workplace
INFO:     {ip}:65500 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO:     {ip}:65499 - "GET /api/agents HTTP/1.1" 200 OK

==============
STEP 97

06:20:35 - PLAN
hello
06:20:35 - opendevin:ERROR: agent_controller.py:107 - Expecting CmdRunAction or AgentEchoAction for Action
06:20:35 - OBSERVATION
Expecting CmdRunAction or AgentEchoAction for Action

==============
STEP 98

06:20:35 - PLAN
hello
06:20:35 - opendevin:ERROR: agent_controller.py:107 - Expecting CmdRunAction or AgentEchoAction for Action
06:20:35 - OBSERVATION
Expecting CmdRunAction or AgentEchoAction for Action

==============
STEP 99

06:20:35 - PLAN
hello
06:20:35 - opendevin:ERROR: agent_controller.py:107 - Expecting CmdRunAction or AgentEchoAction for Action
06:20:35 - OBSERVATION
Expecting CmdRunAction or AgentEchoAction for Action
06:20:35 - opendevin:INFO: agent_controller.py:81 - Exited before finishing the task.

**Comment by evrenyal** [comment]
ref : https://github.com/OpenDevin/OpenDevin/issues/1208

**Comment by rbren** [comment]
@zhaoweihan2017 @evrenyal what does `ollama list` show?

Your model should be `ollama/$name`, where `$name` is an exact copy of a model in the list

**Comment by evrenyal** [comment]
```
ollama list
NAME            	ID          	SIZE  	MODIFIED   
gemma:2b        	b50d6c999e59	1.7 GB	3 days ago	
llama2:latest   	78e26419b446	3.8 GB	5 days ago	
llama3:latest   	71a106a91016	4.7 GB	3 days ago	
orca-mini:latest	2dbd9f439647	2.0 GB	5 days ago 
```

I used llama2 or llama2:latest. it didn't work that way either.

==============
STEP 0

14:15:20 - PLAN
write the "hello"

this output comes and does not continue.

**Comment by SmartManoj** [comment]
@zhaoweihan2017  add `-e LLM_MODEL=ollama/llama2:13b-chat-q4_K_M` to the docker command.

**Comment by evrenyal** [comment]
> @zhaoweihan2017 add `-e LLM_MODEL=ollama/llama2:13b-chat-q4_K_M` to the docker command.

Why did you choose this particular model?

**Comment by SmartManoj** [comment]
Just mentioned the big one.

**Comment by enyst** [comment]
You may also want to try other agents, such as the monologue agent.

**Comment by zhaoweihan2017** [comment]
@rbren  i open the browser , input the ollama/codellama:7b and select the CodeActAgent. i enter 'who are you?',  it has no respnose and only show Starting new task...

**command:**
docker run     --add-host host.docker.internal=host-gateway     -e LLM_API_KEY="ollama"     -e LLM_BASE_URL="http://host.docker.internal:11434"     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR     -v $WORKSPACE_DIR:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     ghcr.io/opendevin/opendevin:main



**the full log as follows:**

INFO:     connection open
08:31:34 - opendevin:INFO: llm.py:25 - Initializing LLM with model: ollama/codellama:7b
08:31:35 - opendevin:INFO: ssh_box.py:271 - Container stopped
08:31:35 - opendevin:WARNING: ssh_box.py:283 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
08:31:35 - opendevin:INFO: ssh_box.py:309 - Container started
08:31:36 - opendevin:INFO: ssh_box.py:326 - waiting for container to start: 1, container status: running
08:31:37 - opendevin:INFO: ssh_box.py:161 - Connecting to root@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 47254 root@host.docker.internal` with the password '9d38dc77-81c1-49dc-b471-38303a64a901' and report the issue on GitHub.
Starting loop_recv for sid: 1423f92c-78b5-4293-8ffa-14f929e76ba3
Mounting workspace directory:  /data/workspace
INFO:     {ip}:61432 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO:     {ip}:61431 - "GET /api/agents HTTP/1.1" 200 OK
08:32:39 - opendevin:INFO: llm.py:25 - Initializing LLM with model: ollama/codellama:7b
08:32:41 - opendevin:INFO: ssh_box.py:271 - Container stopped
08:32:41 - opendevin:WARNING: ssh_box.py:283 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
08:32:41 - opendevin:INFO: ssh_box.py:309 - Container started
08:32:42 - opendevin:INFO: ssh_box.py:326 - waiting for container to start: 1, container status: running
08:32:42 - opendevin:INFO: ssh_box.py:161 - Connecting to root@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 50849 root@host.docker.internal` with the password '027fb09c-b3b6-4d06-982d-29dc0f151b64' and report the issue on GitHub.


==============
STEP 0

08:32:50 - PLAN
who are you?
08:34:47 - ACTION
AgentEchoAction(content="I don't understand your input. \nIf you want to execute command, please use <execute> YOUR_COMMAND_HERE </execute>.\nIf you already completed the task, please exit the shell by generating: <execute> exit </execute>.", action='echo')
08:34:47 - OBSERVATION
I don't understand your input. 
If you want to execute command, please use <execute> YOUR_COMMAND_HERE </execute>.
If you already completed the task, please exit the shell by generating: <execute> exit </execute>.


==============
STEP 1

08:34:47 - PLAN
who are you?
08:36:15 - ACTION
CmdRunAction(command=' and', background=False, action=<ActionType.RUN: 'run'>)
08:36:15 - OBSERVATION
-bash: and: command not found


==============
STEP 2

08:36:15 - PLAN
who are you?

**Comment by zhaoweihan2017** [comment]
@enyst i set the agent to monologue , it still not work.

**Comment by zhaoweihan2017** [comment]
@ SmartManoj  i have tried add this command, but it still not works

**Comment by zhaoweihan2017** [comment]
@evrenyal  got the same problem, i do not know how to solve it

**Comment by zhaoweihan2017** [comment]
> @rbren i open the browser , input the ollama/codellama:7b and select the CodeActAgent. i enter 'who are you?', it has no respnose and only show Starting new task...
> 
> **command:** docker run --add-host host.docker.internal=host-gateway -e LLM_API_KEY="ollama" -e LLM_BASE_URL="http://host.docker.internal:11434" -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR -v $WORKSPACE_DIR:/opt/workspace_base -v /var/run/docker.sock:/var/run/docker.sock -p 3000:3000 ghcr.io/opendevin/opendevin:main
> 
> **the full log as follows:**
> 
> INFO: connection open 08:31:34 - opendevin:INFO: llm.py:25 - Initializing LLM with model: ollama/codellama:7b 08:31:35 - opendevin:INFO: ssh_box.py:271 - Container stopped 08:31:35 - opendevin:WARNING: ssh_box.py:283 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See #897 for more information. 08:31:35 - opendevin:INFO: ssh_box.py:309 - Container started 08:31:36 - opendevin:INFO: ssh_box.py:326 - waiting for container to start: 1, container status: running 08:31:37 - opendevin:INFO: ssh_box.py:161 - Connecting to [root@host.docker.internal](mailto:root@host.docker.internal) via ssh. If you encounter any issues, you can try `ssh -v -p 47254 root@host.docker.internal` with the password '9d38dc77-81c1-49dc-b471-38303a64a901' and report the issue on GitHub. Starting loop_recv for sid: 1423f92c-78b5-4293-8ffa-14f929e76ba3 Mounting workspace directory: /data/workspace INFO: {ip}:61432 - "GET /api/litellm-models HTTP/1.1" 200 OK INFO: {ip}:61431 - "GET /api/agents HTTP/1.1" 200 OK 08:32:39 - opendevin:INFO: llm.py:25 - Initializing LLM with model: ollama/codellama:7b 08:32:41 - opendevin:INFO: ssh_box.py:271 - Container stopped 08:32:41 - opendevin:WARNING: ssh_box.py:283 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See #897 for more information. 08:32:41 - opendevin:INFO: ssh_box.py:309 - Container started 08:32:42 - opendevin:INFO: ssh_box.py:326 - waiting for container to start: 1, container status: running 08:32:42 - opendevin:INFO: ssh_box.py:161 - Connecting to [root@host.docker.internal](mailto:root@host.docker.internal) via ssh. If you encounter any issues, you can try `ssh -v -p 50849 root@host.docker.internal` with the password '027fb09c-b3b6-4d06-982d-29dc0f151b64' and report the issue on GitHub.
> 
> ============== STEP 0
> 
> 08:32:50 - PLAN who are you? 08:34:47 - ACTION AgentEchoAction(content="I don't understand your input. \nIf you want to execute command, please use YOUR_COMMAND_HERE .\nIf you already completed the task, please exit the shell by generating: exit .", action='echo') 08:34:47 - OBSERVATION I don't understand your input. If you want to execute command, please use YOUR_COMMAND_HERE . If you already completed the task, please exit the shell by generating: exit .
> 
> ============== STEP 1
> 
> 08:34:47 - PLAN who are you? 08:36:15 - ACTION CmdRunAction(command=' and', background=False, action=<ActionType.RUN: 'run'>) 08:36:15 - OBSERVATION -bash: and: command not found
> 
> ============== STEP 2
> 
> 08:36:15 - PLAN who are you?

**Comment by zhaoweihan2017** [comment]
https://github.com/OpenDevin/OpenDevin/issues/1283#issuecomment-2069533437

**Comment by zhaoweihan2017** [comment]
> @zhaoweihan2017 @evrenyal what does `ollama list` show?
> 
> Your model should be `ollama/$name`, where `$name` is an exact copy of a model in the list


i open the browser , input the ollama/codellama:7b and select the CodeActAgent. i enter 'who are you?', it has no respnose and only show Starting new task...

command:
docker run --add-host host.docker.internal=host-gateway -e LLM_API_KEY="ollama" -e LLM_BASE_URL="http://host.docker.internal:11434/" -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR -v $WORKSPACE_DIR:/opt/workspace_base -v /var/run/docker.sock:/var/run/docker.sock -p 3000:3000 ghcr.io/opendevin/opendevin:main

the full log as follows:

INFO: connection open
08:31:34 - opendevin:INFO: llm.py:25 - Initializing LLM with model: ollama/codellama:7b
08:31:35 - opendevin:INFO: ssh_box.py:271 - Container stopped
08:31:35 - opendevin:WARNING: ssh_box.py:283 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
08:31:35 - opendevin:INFO: ssh_box.py:309 - Container started
08:31:36 - opendevin:INFO: ssh_box.py:326 - waiting for container to start: 1, container status: running
08:31:37 - opendevin:INFO: ssh_box.py:161 - Connecting to [root@host.docker.internal](mailto:root@host.docker.internal) via ssh. If you encounter any issues, you can try ssh -v -p 47254 root@host.docker.internal with the password '9d38dc77-81c1-49dc-b471-38303a64a901' and report the issue on GitHub.
Starting loop_recv for sid: 1423f92c-78b5-4293-8ffa-14f929e76ba3
Mounting workspace directory: /data/workspace
INFO: {ip}:61432 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO: {ip}:61431 - "GET /api/agents HTTP/1.1" 200 OK
08:32:39 - opendevin:INFO: llm.py:25 - Initializing LLM with model: ollama/codellama:7b
08:32:41 - opendevin:INFO: ssh_box.py:271 - Container stopped
08:32:41 - opendevin:WARNING: ssh_box.py:283 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
08:32:41 - opendevin:INFO: ssh_box.py:309 - Container started
08:32:42 - opendevin:INFO: ssh_box.py:326 - waiting for container to start: 1, container status: running
08:32:42 - opendevin:INFO: ssh_box.py:161 - Connecting to [root@host.docker.internal](mailto:root@host.docker.internal) via ssh. If you encounter any issues, you can try ssh -v -p 50849 root@host.docker.internal with the password '027fb09c-b3b6-4d06-982d-29dc0f151b64' and report the issue on GitHub.

==============
STEP 0

08:32:50 - PLAN
who are you?
08:34:47 - ACTION
AgentEchoAction(content="I don't understand your input. \nIf you want to execute command, please use YOUR_COMMAND_HERE .\nIf you already completed the task, please exit the shell by generating: exit .", action='echo')
08:34:47 - OBSERVATION
I don't understand your input.
If you want to execute command, please use YOUR_COMMAND_HERE .
If you already completed the task, please exit the shell by generating: exit .

==============
STEP 1

08:34:47 - PLAN
who are you?
08:36:15 - ACTION
CmdRunAction(command=' and', background=False, action=<ActionType.RUN: 'run'>)
08:36:15 - OBSERVATION
-bash: and: command not found

==============
STEP 2

08:36:15 - PLAN
who are you?

**Comment by zhaoweihan2017** [comment]
> @zhaoweihan2017 add `-e LLM_MODEL=ollama/llama2:13b-chat-q4_K_M` to the docker command.

 i have tried add this command, but it still not works

**Comment by zhaoweihan2017** [comment]
> You may also want to try other agents, such as the monologue agent.

i set the agent to monologue , it still not work.

**Comment by SmartManoj** [comment]
@zhaoweihan2017 It is working. But the model is not good. Instead of `who are you?`, give it a task.

**Comment by zhaoweihan2017** [comment]
> @zhaoweihan2017 It is working. But the model is not good. Instead of `who are you?`, give it a task like "write a python script to reverse a string".

i have tried the model: ollama/llama2:13b-chat-q4_K_M and send a new task write a python script to reverse a string"， it still not output any response.

i just want to run openDevin successfully.  can you tell me your model that run successfully?

**Comment by SmartManoj** [comment]
Check Gemini 1.5 Pro free version.

**Comment by rbren** [comment]
This sounds like an underpowered model issue, so I'm going to close.

@zhaoweihan2017 GPT-4 and Claude work best
