### ISSUE TITLE
Update for windows

### ISSUE THREAD

**Issue by MKPTechnicals** [OpenDevin/OpenDevin#1287]
Can you please update it to execute in Windows 10?

**Comment by Sparkier** [comment]
Can you describe what the problem here is? What part [of this](https://github.com/OpenDevin/OpenDevin?tab=readme-ov-file#-get-started) does not work for you?

**Comment by MKPTechnicals** [comment]
Makefile doesn't work I need to change format of if statements and pxssh is
also not working.

**Comment by Qarqor5555555** [comment]
Everything works, the interface opens, but it is not possible to connect

**Comment by Qarqor5555555** [comment]
Wsl on win10

**Comment by MKPTechnicals** [comment]
Wsl is installed. 

Do we need to run it in docker and if yes what are steps to run it on windows.

**Comment by rbren** [comment]
@MKPTechnicals please use the guide provided by Sparkier for Windows. If there's a particular step or error message where you're getting stuck, feel free to open a new issue with the template filled out

**Comment by MKPTechnicals** [comment]
Can you provide link for guide by Sparkier please.

**Comment by Sparkier** [comment]
Sure, here you go:
Guide: https://opendevin.github.io/OpenDevin/modules/usage/intro
Troubleshooting: https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting/windows
