### ISSUE TITLE
[Bug]: Docker container does not start

### ISSUE THREAD

**Issue by Sparkier** [OpenDevin/OpenDevin#1294]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/Troubleshooting.md
- [X] I have checked the existing issues.

### Describe the bug

Backend can't start the container because 
`ssh_box.py:325 - b'Missing privilege separation directory: /run/sshd\r\n'`

### Current Version

```bash
ghcr.io/opendevin/sandbox:latest
```

### Installation and Configuration

```bash
make build
make start-backend
make start-frontend
```

### Model and Agent

Does not seem to make a difference.

### Logs, Errors, Screenshots, and Additional Context

![2024-04-22 at 15 04 09](https://github.com/OpenDevin/OpenDevin/assets/5690524/46315d93-202d-41fa-b8b6-64292bdc1554)

**Comment by ValerioPace** [comment]
I have same bug on Docker SSH connection, container won't start; some workaround available?

**Comment by enyst** [comment]
I hit that too. I rebuilt the docker image locally, after adding this back:
https://github.com/OpenDevin/OpenDevin/pull/1297/files

It would be great if you could confirm this. It's weird, and it seems to be a bug that occasionally hits, like:
https://askubuntu.com/questions/1109934/ssh-server-stops-working-after-reboot-caused-by-missing-var-run-sshd/1110843#1110843

**Comment by ValerioPace** [comment]
I have done a sort of workaround 2 adding RUN mkdir /run/sshd && chmod 0755 /run/sshd and works fine.

**Comment by ValerioPace** [comment]
I rebuilded locally sandbox docker image with build.sh inside /containers directory; now ollama is not working even if server doesn't do error cycle it doen't respond well after thinking phase with codellama:7b nor llama2:chat

**Comment by enyst** [comment]
I don't see how other issues with Ollama could be related... please open another issue to figure out the problem. On this one, an updated image will be available soon, too, so you no longer need to build it locally.

**Comment by xingyaoww** [comment]
Opps.. accidentally reopened it -- this should be closed by https://github.com/OpenDevin/OpenDevin/pull/1297
