### ISSUE TITLE
python or golang?

### ISSUE THREAD

**Issue by z-zeechung** [OpenDevin/OpenDevin#13]

**Comment by xandox** [comment]
rust may be?

**Comment by taylorjdawson** [comment]
Anything but Python, maybe even multilingual??

**Comment by z-zeechung** [comment]
then the package would be horribly huge😰

**Comment by rbren** [comment]
I far prefer golang, but the ecosystem is in python.

Leveraging LangChain, LlamaIndex, MetaGPT, etc will be much easier with python. Choosing anything else would be a mistake.

**Comment by suryavirkapur** [comment]
i agree with @rbren choosing anything else would be a mistake.

**Comment by neubig** [comment]
I think we're planning on ts frontend py backend
