### ISSUE TITLE
HOW I CAN RUN THIS PROJECT 

### ISSUE THREAD

**Issue by TranPhuc9898** [OpenDevin/OpenDevin#130]
**Summary**
Sorry for the inconvenience, can I ask if you can tell me how to run this project? Thank you very much for your help.

**Motivation**

**Technical Design**

**Alternatives to Consider**

**Additional context**

**Comment by rbren** [comment]
We have a working prototype as of this evening :)

Some instructions here:
https://github.com/OpenDevin/OpenDevin/pull/129
