### ISSUE TITLE
 Dockerfile, version 0.3.1

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#1300]
## Describe your question

I have a question regarding the Docker image version used in this project. Currently, according to the Dockerfile, version 0.3.1 of the image is being used. Would it be possible and sensible to use the latest available version instead? If not, what are the reasons against updating the image to the most recent version?

## Additional context

I noticed in the Dockerfile that version 0.3.1 is explicitly specified:

```
FROM myimage:0.3.1
```

Before I simply change the version number, I wanted to ask if there are any specific reasons why the older version is still being used here. Perhaps there are compatibility issues or other risks associated with upgrading that I should be aware of.

I would greatly appreciate a brief response on whether I can adjust the version or what speaks against it. This will help me better assess the best way to proceed. Thank you very much!

**Comment by PierrunoYT** [comment]
pierruno@Pierruno:/mnt/c/Users/pierr/OpenDevin$ docker run \
    -e LLM_API_KEY \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_DIR \
    -v $WORKSPACE_DIR:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    ghcr.io/opendevin/opendevin:latest
Unable to find image 'ghcr.io/opendevin/opendevin:latest' locally
latest: Pulling from opendevin/opendevin
13808c22b207: Pull complete
6c9a484475c1: Pull complete
78bef5c7424f: Pull complete
42f0d54f5caa: Pull complete
1723cff2f16b: Pull complete                                                                                             c93cc87f79c7: Pull complete
6925a3cc7bb9: Pull complete
19605de25755: Pull complete
61295c1adf7c: Pull complete
1cdb24a77a2c: Pull complete
d76d49fc3da7: Pull complete
7bc4bbdd3c81: Pull complete
415d1a590ce4: Pull complete
Digest: sha256:c765298358d45b8a76d2ce2a53c9b9ecfe1b1bd7aada7777e5ef6f18b94d9741
Status: Downloaded newer image for ghcr.io/opendevin/opendevin:latest
unable to upgrade to tcp, received 404
pierruno@Pierruno:/mnt/c/Users/pierr/OpenDevin$

**Comment by githubuserAL2024** [comment]
From the readme file:
**
If you want to use the (unstable!) bleeding edge, you can use ghcr.io/opendevin/opendevin:main as the image.
**

**Comment by rbren** [comment]
0.3.1 is the last known stable image. main is not stable--we are constantly merging changes there. I will try and cut a new stable release soon.
