### ISSUE TITLE
[Bug]: ssh_box.py:378 - b'Missing privilege separation directory: /run/sshd\r\n' On Macos

### ISSUE THREAD

**Issue by KeithMorning** [OpenDevin/OpenDevin#1309]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/Troubleshooting.md
- [X] I have checked the existing issues.

### Describe the bug

21:00:49 - opendevin:INFO: ssh_box.py:378 - b'Missing privilege separation directory: /run/sshd\r\n'
21:00:49 - opendevin:ERROR: agent.py:157 - Error creating controller: Failed to start container
Traceback (most recent call last):
  File "/Users/keithxi/Documents/work/AI/OpenDevin/opendevin/server/agent/agent.py", line 148, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/Users/keithxi/Documents/work/AI/OpenDevin/opendevin/controller/agent_controller.py", line 53, in __init__
    self.action_manager = ActionManager(self.id, container_image)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keithxi/Documents/work/AI/OpenDevin/opendevin/controller/action_manager.py", line 37, in __init__
    self.sandbox = DockerSSHBox(
                   ^^^^^^^^^^^^^
  File "/Users/keithxi/Documents/work/AI/OpenDevin/opendevin/sandbox/docker/ssh_box.py", line 92, in __init__
    self.restart_docker_container()
  File "/Users/keithxi/Documents/work/AI/OpenDevin/opendevin/sandbox/docker/ssh_box.py", line 389, in restart_docker_container
    raise Exception('Failed to start container')
Exception: Failed to start container

When make run, the container can not run

### Current Version

```bash
0.3.1
```

### Installation and Configuration

```bash
LLM_MODEL="gpt-3.5-turbo-1106"
LLM_API_KEY=""
LLM_BASE_URL=""
LLM_EMBEDDING_MODEL=""
WORKSPACE_BASE="./workspace"
```

### Reproduction Steps

Get the lastest code , make setup-config, make build and then make run , the docker container will start failed.

**Comment by jtac** [comment]
Confirmed, same behaviour

**Comment by enyst** [comment]
I'm not sure why this is still happening... There was a bug shortly last night, but it was fixed. Either the fix isn't working, or you don't have an updated image, or the image wasn't updated. Checking. 

It might be worth to delete the image in docker (then stop docker, and restart it, just in case). Then let it re-download, although I thought that should happen anyway 🤔

**Comment by enyst** [comment]
OK, from what I can tell, it should work now: please try again to `make build`, you should see it pull the latest image.

**Comment by KeithMorning** [comment]
I pulled the new docker image and the problem has been fixed. Great!
