### ISSUE TITLE
Issue with local models

### ISSUE THREAD

**Issue by aipreneurhub** [OpenDevin/OpenDevin#1311]
## Describe your question
**I have configured local llama model:**
WORKSPACE_DIR="./workspace"
LLM_BASE_URL="http://localhost:11434"
LLM_EMBEDDING_MODEL="llama3"
LLM_MODEL="ollama/llama3"

**the ollama server runs:**
ollama run llama3
>>> Send a message (/? for help)

**this is the command:**
write a python program to print 5 even numbers

**Open Devin is installed and running from:**
Users/.../openDevin
sudo make run
Running the app...
Starting backend server...
Waiting for the backend to start...
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
Connection to localhost port 3000 [tcp/hbci] succeeded!
Backend started successfully.
Starting frontend with npm...
> opendevin-frontend@0.1.0 start
> vite --port 3001
  VITE v5.2.8  ready in 306 ms
  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
15:03:50 - opendevin:INFO: ssh_box.py:309 - Container started
15:03:51 - opendevin:INFO: ssh_box.py:326 - waiting for container to start: 1, container status: running

**this is the output:**
Oops. Something went wrong: [Errno 2] No such file or directory: '/Users/.../openDevin/task.txt'
I should probably start by running `apt install python` to get the Python package installed.
I think I should start by installing Python. After that, I can try to run a simple script.
Oops. Something went wrong: "'action['action']='install'' is not defined. Available actions: dict_keys([<ActionType.KILL: 'kill'>, <ActionType.RUN: 'run'>, <ActionType.BROWSE: 'browse'>, <ActionType.READ: 'read'>, <ActionType.WRITE: 'write'>, <ActionType.RECALL: 'recall'>, <ActionType.THINK: 'think'>, <ActionType.FINISH: 'finish'>, <ActionType.ADD_TASK: 'add_task'>, <ActionType.MODIFY_TASK: 'modify_task'>])"
I think I should install some Python libraries to help me complete my task. How can I do this?
Oops. Something went wrong: [Errno 2] No such file or directory: 'Users/.../openDevin/install.txt'
I think I should install some Python libraries to help me complete my task. How can I do this?
I think I should start by installing pip first to easily install Python libraries. How do I do that?
Oops. Something went wrong: [Errno 2] No such file or directory: 'Users/.../openDevin/install_pip.sh'
I think I should check if pip is already installed before trying to install it.
I think I should try to install pip using apt first. How do I do that?

**how to fix this?**

**Comment by rbren** [comment]
@aipreneurhub make sure you're setting both `WORKSPACE_BASE` and `WORKSPACE_MOUNT_DIR` to the directory you want to work in. It needs to be an absolute path--not a relative path with `./` or `../`

**Comment by rbren** [comment]
On second look, this looks more like an underpowered LLM.
