### ISSUE TITLE
Make maximum monologue length configurable

### ISSUE THREAD

**Issue by lowlyocean** [OpenDevin/OpenDevin#1312]
## Describe your question

Can anyone else reproduce this odd behavior when running ollama/codeqwen:7b-chat-v1.5-q4_0 ?

The first MonlogueAgent prompt has too many thoughts for it to succeeed. It just prints out something like : 
```  101011                                                                        10              ▅            ▅10```

This is the last thought that it can tolerate (and print correctly-formatted JSON response):
```
  {
    "action": "think",
    "args": {
      "thought": "Very cool. Now to accomplish my task."
    }
  },
```
Because as soon as the next one is added, it generates that nonsense output:
```
  {
    "action": "think",
    "args": {
      "thought": "I'll need a strategy. And as I make progress, I'll need to keep refining that strategy. I'll need to set goals, and break them into sub-goals."
    }
  },
```

## Additional context

Using the docker image, launched from WSL on Windows 11. Ollama version 0.1.32

**Comment by lowlyocean** [comment]
Is there already a way to expose Agent-specific parameters to the UI, or would I need to perform a build to adjust this parameter below (which I suspect may be too high for this local LLM) ?

https://github.com/OpenDevin/OpenDevin/blob/ba556ea4d85093b63d627fb62d0e8f102e3093a9/agenthub/monologue_agent/agent.py#L32

**Comment by rbren** [comment]
Definitely! We could also add this to config.py so it can be set with an env var--feel free to open a PR!

**Comment by yufansong** [comment]
Prefer to close it. Because we almost not use monologue_agent now. Not worth effort on it.
But feel free to reopen it if needed.
