### ISSUE TITLE
Backend Mock

### ISSUE THREAD

**Issue by yimothysu** [OpenDevin/OpenDevin#133]
Currently, frontend development requires running the backend. It would be great if we could mock backend responses to some degree. This allows us to test frontend features in isolation.

Originally proposed by @xcodebuild in https://github.com/OpenDevin/OpenDevin/pull/128

**Comment by DHRUV6029** [comment]
Hi, Can I work on this 
Thanks

**Comment by yufansong** [comment]
Resolved in #214, maybe can be closed.
