### ISSUE TITLE
Docker run

### ISSUE THREAD

**Issue by Qarqor5555555** [OpenDevin/OpenDevin#1368]
docker run \
--add-host=host.docker.internal:host-gateway \
    -e LLM_API_KEY="ollama" \
    -e LLM_BASE_URL="http://host.docker.internal:11434" \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    ghcr.io/opendevin/opendevin:0.3.1

How do I type commands? It always gives an error. How can I collect them in one line?

**Comment by rbren** [comment]
Please open a new "bug" issue with the template filled out--there's not enough information here for us to help
