### ISSUE TITLE
How run open devin in wsl windows10

### ISSUE THREAD

**Issue by Qarqor5555555** [OpenDevin/OpenDevin#1369]
How run open devin in wsl windows10

**Comment by rbren** [comment]
Please see https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/Windows.md

**Comment by Qarqor5555555** [comment]
I will try, thank you, and I hope this solves the problem


Please guide me on how to write the lines in an order     dicker run

**Comment by Qarqor5555555** [comment]
https://xdaforums.com/t/how-to-install-opendevin-in-windows-wsl-method.4667442/#google_vignette




I do but not connect with gpt 3.5

**Comment by Qarqor5555555** [comment]
نفس المشكلة مع ديفيكا

**Comment by Qarqor5555555** [comment]
Same problem with Devikaا
