### ISSUE TITLE
Render frontend chat as markdown

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#1378]
**What problem or use case are you trying to solve?**

When the LLM agent outputs markdown responses to the user, it is not rendered properly:

![image](https://github.com/OpenDevin/OpenDevin/assets/38853559/e3b4ca07-cd6e-4b68-85e5-9718d238a8ed)

<img width="720" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/38853559/6fb826e8-767c-4790-be7e-2f09e177a1d2">

**Describe the UX of the solution you'd like**

Render agent's response (thoughts) as markdown so it gets properly rendered.

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by amanape** [comment]
Here are some useful libraries that may be relevant to the implementation:
- https://github.com/remarkjs/react-markdown for rendering markdown
- https://github.com/react-syntax-highlighter/react-syntax-highlighter for rendering code blocks (if any)
