### ISSUE TITLE
[Feature]: Support uploading/downloading file through front-end

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#1379]
**What problem or use case are you trying to solve?**

Support uploading and downloading files through the front end. This will allow the agent to perform data analytics tasks by looking at user-uploaded content (e.g., CSV, excel, or even a zip file, etc.).

**Describe the UX of the solution you'd like**

- Support uploading the files to `workspace` by simply dragging files to the workspace in UI or adding a button for uploading.
- Support downloading file (not sure what's the best way to do it).
- Maybe support the ability to move file (but it may confuses the agent)

<img width="488" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/38853559/5e54ea34-48dd-403f-817c-2ed660539bb6">

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

Having user directly modify the mounted workspace folder on their disk - this is probably not a good user experience as the user need to switch back-and-forth.

**Additional context**

---

Progress:

- [X] Upload single file: resolved by https://github.com/OpenDevin/OpenDevin/pull/1394
- [X] Upload multiple files: https://github.com/OpenDevin/OpenDevin/pull/1718
- [ ] Download files

**Comment by amanape** [comment]
For the technical implementation, it may be worth exploring the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#browser_compatibility),  [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader), and [drag event listeners](https://www.w3schools.com/jsref/event_ondrag.asp) as a starting point. It may be as straightforward as extending the backend endpoints to accept filename and content to update workspace.

It is also worth noting that the implementation may also slightly depend on the target platform, which is currently self-hosted. It will require additional considerations if OpenDevin were, for example, accessible online via URL.

**Comment by xingyaoww** [comment]
Currently, our `Sandbox` abstraction has a `copy_to` method, which we could leverage to implement this uploading feature.

We may need to support copying from [inside the container] to the [host] to be able to download from workspace.

If OpenDevin were hosted via URL, as long as the sandbox supports this `copy_to` method, the whole upload/downloading thing should work out-of-box?

**Comment by amanape** [comment]
> We may need to support copying from [inside the container] to the [host] to be able to download from workspace.

I was actually referring to extending [files.py](https://github.com/OpenDevin/OpenDevin/blob/main/opendevin/files.py) based on a quick trace from how the current frontend file explorer. But I'm not all too familiar with the backend implementation to know how the agent will be aware of this change, so I may be lacking.

> If OpenDevin were hosted via URL, as long as the sandbox supports this copy_to method, the whole upload/downloading thing should work out-of-box?

I meant the actual APIs that would be utilized on the frontend. If I remember correctly, it requires less permissions/effort to copy/paste/drag to an Electron application compared to a Safari browser. But that was a while back.

**Comment by amanape** [comment]
I am confused on the requirements of the download feature. What exactly do we want the user to download and what format should the expect it in? If the workspace is already local and on the users filesystem, what scenarios would the user want to "download"?

CC: @xingyaoww @neubig

**Comment by xingyaoww** [comment]
I am actually imagining something like the VSCode front-end, where the user could just right-click, select one file, and then download. Or the user could select an entire folder, and download it as a zip.

But I guess if it is easier to implement this directly by plugging in a web vscode interface - we could just go through that route for more fine-grained download support and just support downloading the *entire* workspace as a zip on our existing frontend. WDYT?

**Comment by amanape** [comment]
> I am actually imagining something like the VSCode front-end, where the user could just right-click, select one file, and then download. Or the user could select an entire folder, and download it as a zip.

Yes, we can make a custom right-click context menu to contain the download action, it is a good idea. 
I am just still a little lost on the use case of downloading. Are the workspaces created temporary? I haven't gone beyond the default set workspace during development, and any changes made within the UI are immediately reflected in my local filesystem.

> But I guess if it is easier to implement this directly by plugging in a web vscode interface - we could just go through that route for more fine-grained download support and just support downloading the entire workspace as a zip on our existing frontend. WDYT?

Personally I am not familiar with any web vscode interface, and don't think one exists (directly). So I am not exactly sure how you're imagining this setup.

**Comment by xingyaoww** [comment]
For VSCode web, i'm refering to something like this: https://github.com/coder/code-server

**Comment by xingyaoww** [comment]
> I am just still a little lost on the use case of downloading. Are the workspaces created temporary? I haven't gone beyond the default set workspace during development, and any changes made within the UI are immediately reflected in my local filesystem.

@amanape sorry i missed this one in my previous reply! In certain cases, download is probably smth good to have: e.g., when you are doing data analytics, and the agent plots a figure and saves it as `.png` - you can go to the mount directory to find the file, or you could simply download it from the UI if it is more convenient. This is probably matters more if we figured out how to spin up a hosted version (where the mounted folder is actually in a different place)

**Comment by amanape** [comment]
@xingyaoww Yes I see now, that makes much more sense.

On the topic of VSCode Web, it seems like it is just VSCode, on the web. I'm not sure if we can easily extend it to support features such as have OpenDevin write to console, or to download files. Have you or someone else you know used it to a similar extent before? I can't seem to find any documentation to indicate we can do so

**Comment by mamoodi** [comment]
@xingyaoww did you want to keep this issue open? The uploading part is already implemented and there is some discussion whether downloading adds a great deal of value currently.
Perhaps if a hosted version was added, you could open an issue for downloading files then?

**Comment by xingyaoww** [comment]
@mamoodi make sense! Let's close this one for the time being!
