### ISSUE TITLE
Implement Web Browser using Playwright

### ISSUE THREAD

**Issue by yimothysu** [OpenDevin/OpenDevin#138]
Currently, OpenDevin's web browser isn't functional. We would like to add web browsing functionality so that OpenDevin can view documentation and other relevant information not stored in its parametric memory.

Playwright should be added to the backend to scrape web pages and send the following payload to the frontend on each page change:
```json
{
  "url": "...",
  "screenshot": "..."
}
```

`url` is the current URL OpenDevin is viewing.
`screenshot` is a base64-encoded screenshot of the page OpenDevin is viewing.

This allows the user to see what OpenDevin is viewing from the UI.

**Comment by boyuanzheng010** [comment]
We have implemented web browsing functionality with PlayWright in the [SeeAct codebase](https://github.com/OSU-NLP-Group/SeeAct). This codebase enable running web agents on live websites, including: 
- Open a browser and go to the target websites
- Get HTML/CSS, screenshot image from the webpage
- Execute agent actions on webpage

**Comment by yimothysu** [comment]
@boyuanzheng010 That would be fantastic!

**Comment by yimothysu** [comment]
We need to add playwright to Pipenv.

**Comment by rbren** [comment]
Pretty sure this is good now
