### ISSUE TITLE
[Evaluation] Integrate BrowserGym for agent web browsing evaluation

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#1384]
**What problem or use case are you trying to solve?**

As SWE-Bench is going to be added soon, I think it'd be good to move our evaluation codebase forward to include [BrowserGym](https://github.com/ServiceNow/BrowserGym) for everything web browser! 

They already support:
- [MiniWob++](https://miniwob.farama.org/)
- [WebArena](https://webarena.dev/)
- [WorkArena](https://github.com/ServiceNow/WorkArena)

With more work going to be added to that benchmark soon!

cc @neubig @frankxu2004

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

- At least we need to figure out a way to connect OpenDevin's agent interface with `BrowserGym`'s [agent implementation](https://github.com/ServiceNow/BrowserGym/tree/main/demo_agent) as suggested by @frankxu2004

**Describe alternatives you've considered**

**Additional context**

**Comment by xingyaoww** [comment]
Re-open since the evaluation is not added yet.

**Comment by neubig** [comment]
We have a separate issue for evaluation #1471 , so maybe it can be closed?

**Comment by xingyaoww** [comment]
ohhh good point!
