### ISSUE TITLE
SSHBox should be able to run with custom images

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#1387]
**What problem or use case are you trying to solve?**
We provide a default sandbox container image with lots of software pre-installed. But we also want users to be able to bring their own sandbox. This is important for users working in languages/tools that aren't pre-installed on the sandbox

SSHBox assumes that `sshd` is available in the sandbox, which often isn't true for default language images like `node` and `go`. 

**Do you have thoughts on the technical implementation?**
We should probably make `ssh` a "plugin" that can be installed at runtime. I have a draft going for this

**Comment by xingyaoww** [comment]
Another route could be user provide an image, we have a `Dockerfile` or smth that adds OpenDevin dependencies on top of that images and built it for the user locally.
Though we might need different package manager like `yum` or `apt` for different Linux distribution.

**Comment by xingyaoww** [comment]
Side note: it'd also be super great if, say, the user can just provide an SSH login and credentials, and OpenDevin can SSH into that machine and have everything set up automatically, though I think it will be a longer goal. 
But I can't wait to let OpenDevin debug my GPU jobs.

**Comment by mamoodi** [comment]
@xingyaoww has this been addressed with the sanbox-agnostic PR as well as the document that allows custom images?
https://docs.all-hands.dev/modules/usage/custom_sandbox_guide

**Comment by xingyaoww** [comment]
@mamoodi Yes! Let's close this PR!
