### ISSUE TITLE
Implement Planner UI

### ISSUE THREAD

**Issue by yimothysu** [OpenDevin/OpenDevin#139]
Currently, the OpenDevin planner is not functional. We would like to add this functionality so the user can view what OpenDevin has planned.

This should be implemented as a Markdown file of steps which is sent to the frontend.

**Comment by rbren** [comment]
WIP here: https://github.com/OpenDevin/OpenDevin/pull/267

**Comment by rbren** [comment]
Backend is merged! Use the PlannerAgent to see plan events

**Comment by yimothysu** [comment]
@rbren currently, each controller controls a single agent (one-to-one relationship). do we want to support multiple agents per controller (one-to-many)?

this way we can have coding and planning within the same session (e.g., `LangchainsAgent` can code while `PlannerAgent` can plan)

**Comment by rbren** [comment]
Yeah I've been thinking more about multi-agent. But I'm thinking maybe it's in the form of a "meta-agent", which follows the current agent contract, but uses other agents under the hood

**Comment by yimothysu** [comment]
I like that idea better. Similar to PyTorch nn.Module where a top level nn.Module contains child nn.Modules.

**Comment by Sparkier** [comment]
I could probably take a stab at the UI for this. However, I'm not sure I understand how the planner agent works and how I could see plan events/update the UI on completion. Could somebody give me a pointer for that?

**Comment by rbren** [comment]
Hmm--good question @Sparkier 

There should be events for `add_task` and `modify_task` coming through the websocket--lmk if not.

We probably want a new API endpoint like `GET /plan` to retrieve the full plan when one of those events happens

**Comment by Sparkier** [comment]
To clarify, I should be getting these as messages from the socket? I tried logging all messages that come in [here](https://github.com/OpenDevin/OpenDevin/blob/e0c7492609bf8ebdbd7270c9e9261bf2944f3bc6/frontend/src/services/socket.ts#L55-L57) but these are the only ones:
![2024-04-12 at 15 30 30](https://github.com/OpenDevin/OpenDevin/assets/5690524/7835efb4-8d8d-465a-8295-dedb0005a9f9)

**Comment by rbren** [comment]
Ah @Sparkier are you using the PlannerAgent? I don't see that getting passed into `initialize`. PlannerAgent is the only one that implements those actions

**Comment by rbren** [comment]
Sorry @Sparkier I missed your comment!

If you look in the network tab, you'll see an `initialize` event getting sent to the backend, which has a bunch of settings in it. (Most of them are not used by the backend and should probably get removed.) The `AGENT` field controls which agent is being initialized.

I'm realizing now though that I can't see your first `initialize` call, so you may very well be using the PlannerAgent

**Comment by Sparkier** [comment]
Ahh got it, and I was not! Thank you for the pointer. Will continue work tomorrow.

**Comment by Umpire2018** [comment]
> I could probably take a stab at the UI for this. However, I'm not sure I understand how the planner agent works and how I could see plan events/update the UI on completion. Could somebody give me a pointer for that?

@Sparkier Hi, there, i can collaborate with you. Do you need the logs when running `PlannerAgent` via backend?

**Comment by Sparkier** [comment]
Hi @Umpire2018 , happy to collaborate! Not suer I understand this, though:

> Do you need the logs when running PlannerAgent via backend?
