### ISSUE TITLE
Better rendering of front-end chat: resolve overflow issue and add syntax highlighting

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#1399]
**What problem or use case are you trying to solve?**

Markdown is NOT rendered properly while the animation of generation is happening.

![image](https://github.com/OpenDevin/OpenDevin/assets/38853559/8129f09e-5552-42ea-a218-3b34640b7d23)

When generation is completed, the code block is properly displayed:

<img width="619" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/38853559/dd8d87bd-ed52-4843-8e92-1aa5fd9c38bf">

**Describe the UX of the solution you'd like**

But:

- The chat bubble somehow overflowed. Is there a way that we make the code block horizontally scrollable rather than make the entire chat window have a horizontal scroll bar (like in the screenshot)?
- It would be nice if we could add automatic syntax highlights to those code blocks.

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by amanape** [comment]
All the issues addressed here have been solved with the #1402 ad #1488 PRs. Should have closed
