### ISSUE TITLE
微软的模型API是不支持吗?

### ISSUE THREAD

**Issue by he-aook** [OpenDevin/OpenDevin#1418]
## Describe your question
配置文件按照官方提示文档配置了, 怎么配置都是连接不上

我这边配置好连接地址后, 查看微软的地址资源都是有预留的, 但是怎么启动对话,都是卡这不动了;
<img width="1088" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/48249754/18b9fbed-0d94-422c-8061-21311743e3db">

**Comment by ayanjiushishuai** [comment]
是Azure OpenAI吗？
看下这个文档：https://github.com/OpenDevin/OpenDevin/blob/main/docs/guides/AzureLLMs.md

**Comment by li-boxuan** [comment]
Could you please provide your configurations?

**Comment by he-aook** [comment]
@li-boxuan https://github.com/OpenDevin/OpenDevin/issues/1418#issuecomment-2081336077
<img width="835" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/48249754/ae3daf9a-5c56-49d4-b7f8-ae5ad2434770">
<img width="2059" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/48249754/6102517f-f5d4-4763-843f-21357549c195">

**Comment by li-boxuan** [comment]
@enyst Do you have any idea on this one? IIRC you attempted to test Azure OpenAI model.

**Comment by enyst** [comment]
> LLM_MODEL=azure/gpt4-test-ncus-0125

I think the model name needs to be the name of the deployment defined in the Azure account corresponding to the chat model, e.g. to GPT-4.

This is probably the right name, but it seems that it's not sent as such:
> opendevin:INFO: llm.py:51 - Initializing LLM with model: azure/gpt-4

I would suggest to enter azure/gpt4-test-ncus-0125 in the UI settings, the deployment of the chat model as it is defined in the Azure account, even if it's not in the predefined list of models in the UI. I believe the UI allows saving a custom name.

**Comment by he-aook** [comment]
@enyst 嗯嗯。https://github.com/OpenDevin/OpenDevin/issues/1418#issuecomment-2081403109

**Comment by he-aook** [comment]
@li-boxuan  这也并没有实际解决问题呢, 就关闭了

**Comment by li-boxuan** [comment]
@he-aook From your response I thought @enyst 's advice solved your problem. If that's not the case, feel free to reopen the issue, but please comment in English.

**Comment by he-aook** [comment]
@li-boxuan 

My English is very poor, I don't even know how to say it

**Comment by li-boxuan** [comment]
Be confident man. Your English level is certainly enough to communicate. The problem is most people here don't read Chinese :(

In the worst case, you could use a translator.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
