### ISSUE TITLE
[Dev mode] frontend/dist directory not found

### ISSUE THREAD

**Issue by Tetranode0** [OpenDevin/OpenDevin#1419]
Hey everyone, I'm very new to programming.

Currently in VsCode setting up the 'frontend/dist' directory using Uvicorn. However, I keep getting an error stating that the directory DNE, despite attempts to correctly build the frontend and ensure the directory is present.

Why wouldn't Uvicorn recognise the frontend/dist directory? 

I hope this question wasn't too elementary, lmao.

**Comment by rbren** [comment]
@Tetranode0 try running `cd frontend && npm run build`

**Comment by rbren** [comment]
I believe we should be skipping the attempt to serve from `frontend/dist` when in dev mode, or that we should `mkdir -p` it during `make build`

**Comment by iFurySt** [comment]
yes, it makes sense for dev. I also manually created the dir before🌚
