### ISSUE TITLE
Add unit tests for sandboxes

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#1431]
**What problem or use case are you trying to solve?**

I found `DockerSSHBox` does not work well with multi-line commands, we should add unit tests to cover these cases.

**Describe the UX of the solution you'd like**

`tests/unit/test_sandbox.py`

**Do you have thoughts on the technical implementation?**

Adding tests is pretty straight forward, but we should better handle how to starts each unit test with the correct config (i.e., correct UID, correct workspace to mount to, etc).

**Describe alternatives you've considered**

**Additional context**

**Comment by rbren** [comment]
We have unit tests now! Thanks Xingyao!
