### ISSUE TITLE
[Feature]: Teach OpenDevin agents their name and email address

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#1439]
**What problem or use case are you trying to solve?**

We recently added the ability to push to github: #1415
 
However, when doing so, our agents don't know their name and email address, so we should probably prompt them with a name and email address to use for PRs.

**Do you have thoughts on the technical implementation?**

This could be achieved by adding name and email to the [config](https://github.com/OpenDevin/OpenDevin/blob/0d224de369ccd0b80a7fd739ef62fd0f54eafee4/opendevin/schema/config.py#L4) and [defaults](https://github.com/OpenDevin/OpenDevin/blob/0d224de369ccd0b80a7fd739ef62fd0f54eafee4/opendevin/config.py#L21)
, with defaults like `OpenDevin` and some email address we create.

This could then be referenced in the prompts provided to the agents, starting with [MonologueAgent](https://github.com/OpenDevin/OpenDevin/blob/main/agenthub/monologue_agent/utils/prompts.py).

**Comment by ADTmux** [comment]
Hey, I would like to work on this!

**Comment by neubig** [comment]
Fixed by https://github.com/OpenDevin/OpenDevin/pull/1842

**Comment by neubig** [comment]
Hmm, it seems like this is still not fixed...

**Comment by xingyaoww** [comment]
@neubig weird... Did the agent actually sets the git config by itself though?

**Comment by neubig** [comment]
Yes, because the git config is not set, the agent does it by itself

**Comment by xingyaoww** [comment]
@neubig I actually wonder what's the `sandbox` version you are using? I just tried with `ghcr.io/opendevin/sandbox:main` and it seems to work well for me: https://github.com/OpenDevin/OpenDevin/pull/1928

**Comment by mamoodi** [comment]
@neubig Any chance you can try this with main and report back?

**Comment by neubig** [comment]
Recently I haven't noticed any issues with this, so I think it might be fixed?
