### ISSUE TITLE
[Issue] README installation guide does not work

### ISSUE THREAD

**Issue by m1nuzz** [OpenDevin/OpenDevin#1444]
## Describe your question
For some reason, in the Readme, the hyperlinks circled in the screenshot are not clickable. In other words, if you try to click on any of them, nothing happens.

## Additional context

![image](https://github.com/OpenDevin/OpenDevin/assets/109736024/1b249507-d305-46f3-8c3b-61648e3d4ce9)

**Comment by rbren** [comment]
Good catch! Feel free to open a PR that removes those links!

**Comment by Umpire2018** [comment]
Since we have updated project structure in order to implemente docs website, suggest to close this issue as completed. @rbren

**Comment by neubig** [comment]
Yep, thanks @Umpire2018 , this should be fixed!
