### ISSUE TITLE
Client websocket disconnected

### ISSUE THREAD

**Issue by ha-zhcool** [OpenDevin/OpenDevin#145]
**Describe the bug**
The web socket is disconnected after few steps and with the error:
Error sending data to client 
Client websocket disconnected (<CloseCode.ABNORMAL_CLOSURE: 1006>, None)
Error sending data to client 
INFO:     connection closed
**Steps to Reproduce**
1. Start the backend and frontend
2. Ask Opendevin to create something
3. After few steps, some commands, the error appears

**Expected behavior**
Opendevin should continue working on the next step
**Actual behavior**
Opendevin stops and a new session should be started
**Additional context**

**Comment by rbren** [comment]
Several fixes went in this morning--should be fixed now. If you're still seeing issues, feel free to open another bug!
