### ISSUE TITLE
[Bug]: make start-backend does not clear up sandbox containers when exit with C-C

### ISSUE THREAD

**Issue by frankxu2004** [OpenDevin/OpenDevin#1462]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When starting the backend with `make start-backend`, and exit the server with `C-C`, the docker sandbox container would still be running.

### Current Version

```bash
current main branch, no docker
```

### Installation and Configuration

```bash
make start-backend
```

### Reproduction Steps

0. Install dependencies
1. Run `make start-backend`
2. Run `make start-frontend`
3. Exit backend by keyboard `c-c`
4. `docker ps`, opendevin-sandbox is still up and running

**Comment by rbren** [comment]
@frankxu2004 I believe we already use `atexit` to try and clean up--not much we can do for e.g. a `kill -9`. Not sure if this is a case we can handle...

**Comment by frankxu2004** [comment]
I agree.. Really I think not that big of an issue. At least it's not creating multiple containers!
