### ISSUE TITLE
[Browsing]: Make a richer set of web browsing actions

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#1469]
**What problem or use case are you trying to solve?**

Currently OpenDevin can perform browsing on the web, but not a wider variety of web tasks. It would be good if it could do more things, such as scrolling through pages, potentially clicking on things, etc.

**Do you have thoughts on the technical implementation?**

Fortunately, we are in the process of incorporating [BrowserGym](https://github.com/OpenDevin/OpenDevin/pull/1452), which should make this relatively easy. To fix this issue we can:

- [ ] Reference the implementation of the [BrowseURLAction](https://github.com/OpenDevin/OpenDevin/blob/4e9181f326d320a705c201e5f50a3b5b16ac58a5/opendevin/action/browse.py#L29-L55).
- [ ] Reference the [set of browsing actions](https://github.com/ServiceNow/BrowserGym/blob/69a4ebc42ab41ee4c0c22e0fb8dfe09e046f3062/core/src/browsergym/core/action/functions.py#L444) provided by BrowserGym.
- [ ] Implement the set of browsing actions in BrowserGym in a similar way to BrowseURLAction

**Comment by mikanfactory** [comment]
Hi, may I work on this task?

**Comment by neubig** [comment]
Hi, we'd love to have help in general, but for this particular task @frankxu2004 is probably going to work on it so we have it covered. We'll plan on getting this implemented in the next week or two I think. If there are other issues that interest you we'd love to have your help though!

**Comment by mikanfactory** [comment]
Understood. I'll look for other issues!

**Comment by frankxu2004** [comment]
Now arbitrary actions are supported through BrowseInteractiveAction via #1807
