### ISSUE TITLE
[Browsing]: Evaluate browsing agents using WebArena

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#1471]
**What problem or use case are you trying to solve?**

Once we have implemented a browser agent (#1470), we will want to perform evaluation to make sure that it works.

**Do you have thoughts on the technical implementation?**

To do so, we can use an existing benchmark like [WebArena](https://webarena.dev/), which is implemented through [BrowserGym](https://github.com/ServiceNow/BrowserGym). 

We are incorporating BrowserGym (#1452 #1469 #1470), but once that is done, we can also implement evaluation and perform evaluation of our agents. This could either be done:
* by adding OpenDevin support to the BrowserGym evaluation platform
* in a separate repo
* in this repo
(roughly in order of my personal preference)

**Describe alternatives you've considered**

**Additional context**
Blocked by #1452 #1469 #1470

**Comment by frankxu2004** [comment]
Now that this issue can be implemented, I wonder if the order of your personal preference has changed since then? Do we put the evaluation procedure in this repo?

**Comment by neubig** [comment]
I don't have a strong preference, so maybe we should follow the convention of SWE-Bench?

**Comment by neubig** [comment]
Done by @frankxu2004 , thanks!
