### ISSUE TITLE
ERROR:root:<class 'ImportError'>: cannot import name 'spawn' from 'pexpect'

### ISSUE THREAD

**Issue by zGamerZz** [OpenDevin/OpenDevin#1475]
Hey,
i´m new in this area and want to install OpenDevin. But when I run `uvicorn opendevin.server.listen:app --port 3000` this mass of Errors are following: https://pastes.dev/VUGRkjNDYw

Thanks in Advance!

**Comment by rbren** [comment]
See this troubleshooting guide: https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting#unable-to-connect-to-ssh-box
