### ISSUE TITLE
[Bug]: Old documentation files are not removed

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#1481]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

If I move `foo.py` to `bar.py`, the documentation for foo continues to exist in ./docs/modules/python/...

### Current Version

```bash
main, `5f2d6f58f20a3f7db8e41d77bb86d1871381e367`
```

### Installation and Configuration

```bash
`make build`
```

### Model and Agent

N/A

### Reproduction Steps

1. move a python file
2. rebuild the docs
3. old docs file is still here

**Comment by Sparkier** [comment]
Good catch and a somewhat tricky one... Working on it.
