### ISSUE TITLE
Micro-agent: Support task rejection

### ISSUE THREAD

**Issue by li-boxuan** [OpenDevin/OpenDevin#1482]
Micro-agents, as a whole, don’t work well end-to-end yet. For example, I can barely make ManagerAgent, the one that does the task distribution, to complete the simple task used by the integration test:

```bash
poetry run python ./opendevin/main.py -i 10 -t "Write a shell script 'hello.sh' that prints 'hello'." -c "ManagerAgent"
```

To achieve that I think we need to do more prompt engineering, and potentially introduce more actions. I propose that we add an escalation action, because I find micro-agents often get stuck when they are assigned a task that they are not capable of.

For example, when the `CoderAgent` is assigned a task that is not concrete enough, it should `escalate` and the `ManagerAgent` should create a task for `StudyRepoForTaskAgent` first to study what files to modify, what the repo structure is, etc.

**Comment by rbren** [comment]
This is a great idea! I'm changing it to `rejection` because I think letting a smaller agent call a bigger one would lead to weird loops 😄

**Comment by li-boxuan** [comment]
Yeah when I said "escalation", I was thinking of something more like "rejection" ;)
