### ISSUE TITLE
Add i18n support for official website

### ISSUE THREAD

**Issue by li-boxuan** [OpenDevin/OpenDevin#1483]
**What problem or use case are you trying to solve?**

https://github.com/OpenDevin/OpenDevin/pull/1372 refactored the docs and created a [website](https://opendevin.github.io/OpenDevin/) for hosting docs, which is great! But that PR also removes [README-zh](https://github.com/OpenDevin/OpenDevin/blob/46bd83678a09c9f20ab53b30b7f2278932ace11b/docs/README-zh.md) file, a Chinese translation of official doc. Instead of getting the chinese translation of README back, I think we probably should leverage the chance and introduce i18n support for the official website.

**Describe the UX of the solution you'd like**

Add i18n support for the official website and/or doc. I guess when basic support is added, we can use OpenDevin to dogfood and finish the translations.

**Comment by Umpire2018** [comment]
Please assign it to me. Working on it right now.

![image](https://github.com/OpenDevin/OpenDevin/assets/138990495/113f9b32-d8c4-4d34-8e72-e4b0d8f8ed6e)
