### ISSUE TITLE
frontend: Add [continue] and [finish] button for user to click when agent is awaiting user input

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#1487]
**What problem or use case are you trying to solve?**

Now that https://github.com/OpenDevin/OpenDevin/pull/1290 is merged that supports awaiting user input, the agent may ask the user for confirmation (e.g., i propose we do X, Y, Z, do you agree?). It is a bit hassle for user to manually type in "continue" and send it to the agent.

**Describe the UX of the solution you'd like**

Add two buttons when the agent is awaiting user input:
- **continue**: sends a message "continue" to the agent
- **finish**: end the current task and starts a new one.

It will look smth like this:
![image](https://github.com/OpenDevin/OpenDevin/assets/38853559/ee61d01c-00f3-4f38-8e44-a613cdd229c4)

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

You can start work on this by using `CodeActAgent`, asking it "Can you print hello world first, then plot a figure of equation (y=x, x=0,1,2,3,4) using matplotlib?".

Demo video:

https://github.com/OpenDevin/OpenDevin/assets/38853559/745733b3-788f-4d44-b0b0-3454fbe4f1fe

**Comment by iFurySt** [comment]
<img width="783" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/16201837/bbcc1d25-3fba-496f-83b7-0fb576a52754">

is the reset equal to finish? if so, we only need to adjust the behavior to continue the current task.

**Comment by amanape** [comment]
Resolved #1508
