### ISSUE TITLE
[Bug]: The Agent stuck when error occurred in loop.

### ISSUE THREAD

**Issue by iFurySt** [OpenDevin/OpenDevin#1492]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

<img width="1611" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/16201837/a67d2f50-7a2c-4e9f-b5a1-1d0d120edc08">

<img width="1605" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/16201837/20fe87b6-6f22-4f2a-b0ab-c97994d6979f">

### Current Version

```bash
c50319138e0eef3645276bf13a50afce4980f9d8
```

### Installation and Configuration

```bash
the default setting with gpt-3.5-turbo


# Your OpenAI API key, or any other LLM API key
export LLM_API_KEY="sk-..."
# The directory you want OpenDevin to modify. MUST be an absolute path!
export WORKSPACE_BASE=$(pwd)/workspace
```
```


### Model and Agent

_No response_

### Reproduction Steps

1. start a new task
2. let the backend throw error in the loop

### Logs, Errors, Screenshots, and Additional Context

_No response_

**Comment by xingyaoww** [comment]
It looks like the error is related to LLM API? Which agent you are using?

What do you think is the expected outcome for this: The agent should just output error message once?

**Comment by iFurySt** [comment]
the problem is the backend service need to be restarted, otherwise it can't recover or start any task.

**Comment by rbren** [comment]
I've definitely noticed similar issues. We need to refactor session management for sure

**Comment by amanape** [comment]
Attempting to pause/restart the agent also results in a "Current task state not recognized."
