### ISSUE TITLE
Add server tests

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#151]
We should add a test that checks that the server runs OK. It should:
* Start the server
  * Use the `fake` model
* Create a connection with websocat
* Send a task via websocat (can we pipe to stdin?)

**Comment by rbren** [comment]
Closing in favor of https://github.com/OpenDevin/OpenDevin/issues/341

**Comment by SuibhneOFoighil** [comment]
Tried to run the regression tests via`python evaluation/regression/run_tests.py` but running into this error ...
```
(OpenDevin) (base) suibhne@Suibhnes-MBP OpenDevin % python evaluation/regression/run_tests.py 
Traceback (most recent call last):
  File "/Users/suibhne/OpenDevin/evaluation/regression/run_tests.py", line 4, in <module>
    from opendevin import config
ModuleNotFoundError: No module named 'opendevin
```
Anyone else running into this?

**Comment by rbren** [comment]
@SuibhneOFoighil try setting 
```
PYTHONPATH=`pwd`
```
