### ISSUE TITLE
Micro-agent: typo checker

### ISSUE THREAD

**Issue by li-boxuan** [OpenDevin/OpenDevin#1514]
**What problem or use case are you trying to solve?**

Micro-agents are small agents that specialize in one field. You don't have to write code to define a new micro-agent! Take a look at existing micro-agents: https://github.com/OpenDevin/OpenDevin/tree/main/agenthub/micro

We could add a new micro-agent that scans file(s) with the given path, (or maybe the current workspace?) and **just fix the typos** in-place. Motivation: typos are everywhere. Most project owners welcome PRs that fix typos, but few of them are happy to see their doc and/or docstring gets completely rewritten & polished by LLMs.

**Do you have thoughts on the technical implementation?**

We should think about how we want to prompt the LLM to fix the typos. A naive approach is to let LLM review each document and return new document with typos fixed. This might waste a lot of output tokens. An alternative is to instruct LLM to return (typo, fix) pairs, and then use `sed` or `awk` to fix them in-place. This might need some experiments. Both approaches could cause false positives.

**Comment by xingyaoww** [comment]
How do you feel about making the micro agent some sort of prompt plugins? e.g., something like OpenAI GPTs where user can customize their experience by providing domain-specific prompts / chat with the model to provide context of their need.

I'm thinking, for example, maybe **each micro-agent can just re-use the implementation of an existing agent, and what it does is simply swaps out the in-context example for that agent** (e.g., [CodeAct's in-context example](https://github.com/OpenDevin/OpenDevin/blob/main/agenthub/codeact_agent/prompt.py#L48-L220)). Generally, these in-context examples/demonstrations are essential in guiding agents to have specific capability (e.g., if you show agent how to correct typo with the correct tools, they will generally perform better on those tasks).

We can do a selector on the frontend for user to search & choose the example prompts.

**Comment by li-boxuan** [comment]
> How do you feel about making the micro agent some sort of prompt plugins? e.g., something like OpenAI GPTs where user can customize their experience by providing domain-specific prompts / chat with the model to provide context of their need.
> 
> I'm thinking, for example, maybe **each micro-agent can just re-use the implementation of an existing agent, and what it does simply swap out the in-context example for that agent** (e.g., [CodeAct's in-context example](https://github.com/OpenDevin/OpenDevin/blob/main/agenthub/codeact_agent/prompt.py#L48-L220)). Generally, these in-context examples/demonstrations are essential in guiding LLMs to have the specific capability (e.g., if you show the agent how to correct typo with the correct tools, they will generally perform better on those tasks).
> 
> We can do a selector on the front end for a user to search & choose the example prompts. This way, you get the stability & generality and re-use most implementation of the base agent, while be able to have customized performance.

As discussed offline, this is a great idea but off-topic here.

**Comment by xingyaoww** [comment]
The idea is tracked here: https://github.com/OpenDevin/OpenDevin/issues/1529
