### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by codevladdo** [OpenDevin/OpenDevin#1524]
## Describe your question

Hi - can someone point me to how i can install and run Open Devin? cant seem to find the docs. Thanks!

**Comment by PHRINGAS** [comment]
Here you'll find plenty of texts to engage with.
https://github.com/OpenDevin/OpenDevin/blob/main/agenthub/README.md

**Comment by SmartManoj** [comment]
https://opendevin.github.io/OpenDevin/modules/usage/intro

**Comment by iFurySt** [comment]
I think it's been solved. Going to close this one. If you have other questions, you can create a new issue :)
