### ISSUE TITLE
Discord link broken

### ISSUE THREAD

**Issue by jeffscottward** [OpenDevin/OpenDevin#1525]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Discord link broken

### Current Version

```bash
Discord link broken
```

### Installation and Configuration

```bash
Discord link broken
```

**Comment by SmartManoj** [comment]
Works fine
https://discord.gg/ESHStjSjD4

**Comment by neubig** [comment]
This was fixed by https://github.com/OpenDevin/OpenDevin/pull/1539
