### ISSUE TITLE
Micro-agent: git bisect helper

### ISSUE THREAD

**Issue by li-boxuan** [OpenDevin/OpenDevin#1540]
**What problem or use case are you trying to solve?**

Micro-agents are small agents that specialize in one field. You don't have to write code to define a new micro-agent! Take a look at existing micro-agents: https://github.com/OpenDevin/OpenDevin/tree/main/agenthub/micro

We could add a new micro agent that utilizes `git bisect` to find the first problematic commit automatically.

**Do you have thoughts on the technical implementation?**

The agent likely needs the following inputs:
1) How to judge if a commit works (e.g. a command to run a test)
2) A known good commit hash
3) A known bad commit hash (optional, default to be HEAD)

This could either used by user directly, or by other agents to do debugging with version control.

**Describe alternatives you've considered**

**Additional context**

**Comment by arnabbiswas1** [comment]
Can I pick it up?

**Comment by arnabbiswas1** [comment]
Can I pick it up?

**Comment by li-boxuan** [comment]
@arnabbiswas1 sure, go ahead!

**Comment by li-boxuan** [comment]
@arnabbiswas1 are you still interested in this?

**Comment by arnabbiswas1** [comment]
> @arnabbiswas1 are you still interested in this?

Sorry. I have not been able to make any progress. Someone else might pick it up if interested.
