### ISSUE TITLE
Use OpenDevin to fix MathAgent

### ISSUE THREAD

**Issue by li-boxuan** [OpenDevin/OpenDevin#1544]
There are a few typos and factual mistakes in `math_agent/agent.yaml` and `math_agent/prompt.md`. How many can you find? I see at least four:

1. agent.yaml L16: `output` -> `outputs`
2. 2099-01-01 is Thursday, not Saturday
3. integral of sin(x^2) evaluated from -1 to 1 is 0.620537, not 0.603848
4. prompt.md L2: `follwoing` -> `following`

One can fix them manually, but it would be cool to use OpenDevin to find those problems and fix them by itself. Don't feed this issue to OpenDevin - that would be cheating XD.

https://github.com/OpenDevin/OpenDevin/blob/319b9ac0f341b4433fd2c8ab78340813d4e85bff/agenthub/micro/math_agent/agent.yaml#L1-L25

https://github.com/OpenDevin/OpenDevin/blob/319b9ac0f341b4433fd2c8ab78340813d4e85bff/agenthub/micro/math_agent/prompt.md?plain=1#L1-L23

**Comment by tobitege** [comment]
Microsoft's wizardlm-2-8x22b **fails**! 😢 

![grafik](https://github.com/OpenDevin/OpenDevin/assets/10787084/540a0917-a778-4e28-a847-2fa5100c605a)

**Comment by tobitege** [comment]
just random finds:
https://github.com/rakutentech/MathSensei
https://github.com/microsoft/autogen
https://github.com/microsoft/FLAML
https://microsoft.github.io/FLAML/blog/2023/06/28/MathChat/

**Comment by li-boxuan** [comment]
@tobitege very interesting findings! Have you tried gpt-4o?

**Comment by tobitege** [comment]
I *think* I did just before WizardLM 2, but didn't make screenies then, but it also failed iirc.
