### ISSUE TITLE
docker.errors.DockerException: Error while fetching server API version: (5, 'CreateFile', 'Access is denied.')

### ISSUE THREAD

**Issue by ack72tdp** [OpenDevin/OpenDevin#155]
**Describe the bug**

**Steps to Reproduce**
1. windows 11 .. compile and run as per the steps .. in python virtual environement..
2.
3.

**Expected behavior**

**Actual behavior**

**Additional context**

**Comment by ack72tdp** [comment]
INFO:     Started server process [30216]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     127.0.0.1:55691 - "GET / HTTP/1.1" 404 Not Found
INFO:     ('127.0.0.1', 63548) - "WebSocket /ws" [accepted]
INFO:     connection open
Task exception was never retrieved
future: <Task finished name='create controller' coro=<Session.create_controller() done, defined at C:\opendevin\server\session.py:76> exception=DockerException("Error while fetching server API version: (5, 'CreateFile', 'Access is denied.')")>

**Comment by rbren** [comment]
Do you have Docker running on your machine? What does `docker ps` show?

**Comment by rbren** [comment]
See also: https://github.com/OpenDevin/OpenDevin/issues/102

**Comment by ack72tdp** [comment]
docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

docker images
REPOSITORY                  TAG                                        IMAGE ID       CREATED         SIZE
crazymax/linguist           7.20.0                                     dc5f9ae3be6a   22 months ago   72.2MB
docker/desktop-git-helper   5a4fca126aadcd3f6cc3a011aa991de982ae7000   efe2d67c403b   2 years ago     44.2M

**Comment by MitchellCash** [comment]
From what I can tell on my own machine the application is attempting to fetch `opendevin/sandbox:latest` from Docker Hub, but there is no image with the `latest` tag. As of this comment the only tag on Docker Hub is `v0.1`.

I got around this temporarily by fetching `v0.1` and tagging it locally with `latest`.

```sh
docker tag opendevin/sandbox:v0.1 opendevin/sandbox:latest
```

The more verbose error that lead me here:

```sh
INFO:     Started server process [17740]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 64606) - "WebSocket /ws" [accepted]
INFO:     connection open
Failed to start container: 404 Client Error for http+docker://localnpipe/v1.44/images/create?tag=latest&fromImage=opendevin%2Fsandbox: Not Found ("manifest for opendevin/sandbox:latest not found: manifest unknown: manifest unknown")
Task exception was never retrieved
future: <Task finished name='create controller' coro=<Session.create_controller() done, defined at D:\github.com\OpenDevin\opendevin\server\session.py:114> exception=NotFound(HTTPError('404 Client Error: Not Found for url: http+docker://localnpipe/v1.44/images/create?tag=latest&fromImage=opendevin%2Fsandbox'))>
Traceback (most recent call last):
  File "C:\Users\JohnSmith\AppData\Local\Programs\Python\Python312\Lib\site-packages\docker\api\client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "C:\Users\JohnSmith\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localnpipe/v1.44/containers/create?name=sandbox-default
```

**Comment by rbren** [comment]
Ahh that must be it! I'll push a fix

**Comment by rbren** [comment]
https://github.com/OpenDevin/OpenDevin/pull/164

**Comment by rbren** [comment]
Closing this--lmk if the fix didn't take

**Comment by morganmcg1** [comment]
I hit this issue too, it'd be helpful to mention in the readme that you need Docker running. I know its in the requirements list, but it'd be nice to be explicit about having it running :)
