### ISSUE TITLE
[Refactor]: Better screenshot rremoval

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#1553]
**Summary**

We have screenshot removal in several different places in the codebase, and we should probably consolidate the code into a single place.
More discussion: https://github.com/OpenDevin/OpenDevin/pull/1550

**Comment by frankxu2004** [comment]
What do you think about adding this https://github.com/OpenDevin/OpenDevin/blob/6013faeec5bbee370a5aaf554c9324330a2fbe95/opendevin/events/observation/browse.py#L27

**Comment by enyst** [comment]
Something like that should work just fine. Afaik, that controls the serialized form that gets sent to the llm for actions/observations.
