### ISSUE TITLE
Is there a way to use standard openai API keys instead of **Azure OpenAI**?

### ISSUE THREAD

**Issue by 4cecoder** [OpenDevin/OpenDevin#1554]
## Describe your question

I am currently exploring the use of OpenDevin on GitHub and have a question regarding the API key configuration. I noticed that the documentation and setup instructions primarily reference the use of Azure OpenAI for API key management.

Is there a way to configure OpenDevin to use standard OpenAI API keys instead of Azure OpenAI? I am looking for a straightforward method to integrate OpenDevin with the OpenAI API without the need for Azure services.

Any guidance or documentation on this matter would be greatly appreciated.

Thank you in advance for your assistance.

## Additional context

I'm on windows BTW

**Comment by enyst** [comment]
Absolutely, you don't need Azure. Just use OpenAI, and you don't need the more complicated setup documented about Azure. (It's more documented because it's tricky tbh:)

Please do make sure that once you start on the web interface, you enter the model in Settings there.

**Comment by rbren** [comment]
@4cecoder make sure your model is set to e.g. `gpt-4-turbo`, not `azure/gpt-4-turbo`. I've made that mistake before 😄
