### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/opt/workspace_base/.tmp'

### ISSUE THREAD

**Issue by zGamerZz** [OpenDevin/OpenDevin#1560]
Hey,
when I run OpenDevin and send a task this Error (terminal) is following:

```
Traceback (most recent call last):
  File "/app/opendevin/controller/agent_controller.py", line 127, in _run
    finished = await self.step(i)
               ^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 309, in step
    observation = await self.action_manager.run_action(action, self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/action_manager.py", line 51, in run_action
    observation = await action.run(agent_controller)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/events/action/commands.py", line 69, in run
    pathlib.Path(os.path.dirname(tmp_filepath)).mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/opt/workspace_base/.tmp'
```

How can I give the permission?

Thanks in Advance!

**Comment by rbren** [comment]
@zGamerZz how are you running? Which version are you on?

**Comment by norio** [comment]
I also got the same error message when using CodeActAgent.
I was using the latest 0.5 version.

**Comment by jtac** [comment]
I've been trying to set this up under wsl2 as well and looks like the docker setup doesnt create a directory named /opt/workspace_base in the setup.

I ran docker exec to create the directory and make it writeable and got that error solved:

docker exec <docker id> mkdir -p /opt/workspace_base
docker exec <docker id> chmod 777 /opt/workspace_base  # just as a precaution

**Comment by jtac** [comment]
I managed to solve this and get it running properly by editing 
containers/app/Dockerfile and moving line 42 ( RUN mkdir -p $WORKSPACE_BASE ) to line 56, ( after USER opendevin , on the next line after it. )

After this I can locally do a 'make setup-config', correct the options in config.toml that was generated and then 'make run' and the container compiles and runs properly.

**Comment by rbren** [comment]
@jtac good find! Want to open up a PR that makes the change?

**Comment by mamoodi** [comment]
Closing this due to merged PR. Please reopen issue if this did not resolve the issue.
