### ISSUE TITLE
Settings Modal: Add a "Reset to Defaults" button

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#1568]
**What problem or use case are you trying to solve?**
Some users might randomly click around and mess up their settings. We should have an easy way to get back to the original state.

**Describe the UX of the solution you'd like**
A button in the settings modal that says "Reset to Defaults"

**Do you have thoughts on the technical implementation?**
Should be pretty easy

**Comment by D0odi** [comment]
Hi, i have created a PR for that feature
