### ISSUE TITLE
[Bug]: Issue with UID 1000

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#1582]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When I run the command inside the readme I get the error below.

### Current Version

```bash
I'm using 0.5.0
```

### Installation and Configuration

```bash
export WORKSPACE_BASE=$(pwd)/workspace
pierruno@Pierruno:/mnt/c/Users/pierr/OpenDevin$ docker run \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal=host-gateway \
    ghcr.io/opendevin/opendevin:0.5
```

### Reproduction Steps

 export WORKSPACE_BASE=$(pwd)/workspace
pierruno@Pierruno:/mnt/c/Users/pierr/OpenDevin$ docker run \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal=host-gateway \
    ghcr.io/opendevin/opendevin:0.5

### Logs, Errors, Screenshots, and Additional Context

docker run \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal=host-gateway \
    ghcr.io/opendevin/opendevin:0.5
0.5: Pulling from opendevin/opendevin
b0a0cf830b12: Pull complete
72914424168c: Pull complete
80818bc858ed: Pull complete
805c2b19c211: Pull complete
7a89e8daeeae: Pull complete
5978226c46e8: Pull complete
fc009ffa9782: Pull complete
a6057d2f3c5b: Pull complete
3da7e09483c3: Pull complete
50f377d5dfac: Pull complete
bb550dd7b8e7: Pull complete
412b5821d6b9: Pull complete
48f54f0bd3f5: Pull complete
a464f58547bc: Pull complete
15e7cc3d72b8: Pull complete
a08a37884c32: Pull complete
f8e25b03915b: Pull complete
ebdb6aa597b0: Pull complete
965a5b367a2a: Pull complete                                                                                             0252b3da18b3: Pull complete
54bdae1ceca3: Pull complete
Digest: sha256:7f17489e68873cdfe06b90d7cab902bf58fcd246a8f298c7b751ac191a3e8bc3
Status: Downloaded newer image for ghcr.io/opendevin/opendevin:0.5
useradd: UID 1000 is not unique
usermod: user 'enduser' does not exist
Docker socket group id: 0
usermod: user 'enduser' does not exist
su: user enduser does not exist or the user entry does not contain all the required fields
pierruno@Pierruno:/mnt/c/Users/pierr/OpenDevin$ ^C
pierruno@Pierruno:/mnt/c/Users/pierr/OpenDevin$

**Comment by kroni66** [comment]
in entrypoint.sh is missing useradd -m enduser

**Comment by 4cecoder** [comment]
> in entrypoint.sh is missing useradd -m enduser

So how do you fix the problem?

**Comment by kroni66** [comment]
user add is for opendevin not forn enduser in dockerfile for app it must be edited

**Comment by rbren** [comment]
Ahh I see the issue--your local `uid` is 1000, which is taken by opendevin. Working on a fix

**Comment by LeonardoGentile** [comment]
A similar problem for me (M1)
Running on main

```
docker run \
    --add-host host.docker.internal=host-gateway \
    -e LLM_API_KEY="ollama" \
    -e LLM_BASE_URL="http://host.docker.internal:11434" \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    ghcr.io/opendevin/opendevin:main
```
tells `SANDBOX_USER_ID is not set`

**Comment by PierrunoYT** [comment]
Thx
