### ISSUE TITLE
Option to always continue CodeAct

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#1586]
**What problem or use case are you trying to solve?**
CodeAct keeps interrupting me for permission to continue. I want it to just chug along.

**Describe the UX of the solution you'd like**
Either a button in the UI to pin "continue", or something I can put in the prompt. TBH it probably just shouldn't ask for input as often as it does

**Comment by xingyaoww** [comment]
Maybe we can get this merged: https://github.com/OpenDevin/OpenDevin/pull/1508

And then add a checkbox saying something like "[ ] always continue"?

**Comment by rbren** [comment]
makes sense to me!

**Comment by SmartManoj** [comment]
> CodeAct keeps interrupting me

Silently.

**Comment by SmartManoj** [comment]
Closing in favor of https://github.com/OpenDevin/OpenDevin/issues/1798
