### ISSUE TITLE
[Feature]: Add Copy Button to Each Message in Chat Interface

### ISSUE THREAD

**Issue by isavita** [OpenDevin/OpenDevin#1590]
**What problem or use case are you trying to solve?**
Users need a quick and easy way to copy text from messages in the chat interface to use elsewhere. This feature will enhance user productivity and improve the overall user experience by facilitating easier sharing and documentation of information exchanged in chat.

**Describe the UX of the solution you'd like**
I propose adding a **"Copy"** button at the **top** or **bottom** of each message within the chat interface. This button should be clearly visible and accessible, ideally represented by a clipboard icon.

**Do you have thoughts on the technical implementation?**
The implementation can involve adding an event listener to each copy button that triggers a copy-to-clipboard function when clicked.

**Describe alternatives you've considered**
I don't know about alternatives

**Additional context**
This feature is aimed at enhancing user interaction efficiency within the chat application.
<img width="1355" alt="copy_button" src="https://github.com/OpenDevin/OpenDevin/assets/5805397/4a0e40ed-d81f-4807-842c-d2e385e786ee">

**Comment by rbren** [comment]
@isavita what is the use case here?

With ChatGPT, it makes sense that you'd want to copy stuff out of the messages--that's where e.g. the generated code is. But with OpenDevin, the important stuff generally gets written to files.

I think a copy button would likely just add clutter to the UI without adding much value, but I'm happy to discuss further

**Comment by isavita** [comment]
@rbren I suspected it to be a design decision, but I was testing some functionalities with a less capable local model, which struggled with certain tasks. I needed to manually assist by saving files, using code provided by the agent. Even with more capable models like Claude Opus or GPT-4, you might still need to intervene and help, whether by running code or testing sub-parts of the program. This is more apparent with local models as they are not as capable with complex tasks; GPT-4 also has its limitations. In such cases, having a copy and paste button would be useful.

**Comment by PierrunoYT** [comment]
I'm trying out if FumeDev can fix it.

**Comment by tobitege** [comment]
I'd be happy to see this, so that the "copy" icon only shows when hovering over a message (not visible permanently).
Use case: I often want to copy just my own prompts so I can start a new task 😀

**Comment by isavita** [comment]
@tobitege I will reopen it. I thought it was only me, but if and other find it useful might be good idea to keep the issue

**Comment by tobitege** [comment]
It's a feature I see in pretty much every chat UI... POE, Perplexity, Cursor...
