### ISSUE TITLE
Error with ollama by following localllm guide

### ISSUE THREAD

**Issue by suoko** [OpenDevin/OpenDevin#1591]
sudo docker run --rm   --add-host host.docker.internal=host-gateway   -e LLM_API_KEY="ollama"   -e LLM_BASE_URL="http://host.docker.internal:11434"   -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE   -v $WORKSPACE_BASE:/opt/workspace_base   -v /var/run/docker.sock:/var/run/docker.sock   -p 3000:3000   ghcr.io/opendevin/opendevin:main

I got these errors on ubuntu 24.04

usermod: no changes
Docker socket group id: 137
usermod: group '137' does not exist
INFO:   Started server process [12]
INFO:   Waiting for application startup.
INFO:   Application startup complete.
INFO:   Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:   172.17.0.1:57958 - "GET /index.html HTTP/1.1" 304 Not Modified
INFO:   172.17.0.1:57958 - "GET /index.html HTTP/1.1" 304 Not Modified
INFO:   ('172.17.0.1', 57974) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJhYzBlNzg4Ni03MjdmLTQ0MDMtYmFkMS0yZmIzMGNmNjNmYTYifQ.Qfl-TBQuRrTL4ydeAIBZQVxiWliITBhLB3YVqpuSw4I" [accepted]
INFO:   connection open
10:14:43 - opendevin:INFO: agent.py:156 - Creating agent CodeActAgent using LLM ollama/llama3:latest
10:14:43 - opendevin:INFO: llm.py:67 - Initializing LLM with model: ollama/llama3:latest
10:14:43 - opendevin:INFO: ssh_box.py:67 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
10:14:43 - opendevin:ERROR: ssh_box.py:74 - Error creating controller. Please check Docker is running and visit `https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting` for more debugging information.
10:14:43 - opendevin:ERROR: agent.py:167 - Error creating controller: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
Traceback (most recent call last):
 File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
  response = self._make_request(
        ^^^^^^^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 496, in _make_request
  conn.request(
 File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 400, in request
  self.endheaders()
 File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
  self._send_output(message_body, encode_chunked=encode_chunked)
 File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
  self.send(msg)
 File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
  self.connect()
 File "/app/.venv/lib/python3.12/site-packages/docker/transport/unixconn.py", line 27, in connect
  sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
  resp = conn.urlopen(
      ^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 847, in urlopen
  retries = retries.increment(
       ^^^^^^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 470, in increment
  raise reraise(type(error), error, _stacktrace)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
  raise value.with_traceback(tb)
 File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
  response = self._make_request(
        ^^^^^^^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 496, in _make_request
  conn.request(
 File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 400, in request
  self.endheaders()
 File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
  self._send_output(message_body, encode_chunked=encode_chunked)
 File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
  self.send(msg)
 File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
  self.connect()
 File "/app/.venv/lib/python3.12/site-packages/docker/transport/unixconn.py", line 27, in connect
  sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 213, in _retrieve_server_version
  return self.version(api_version=False)["ApiVersion"]
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/docker/api/daemon.py", line 181, in version
  return self._result(self._get(url), json=True)
            ^^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/docker/utils/decorators.py", line 44, in inner
  return f(self, *args, **kwargs)
      ^^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 236, in _get
  return self.get(url, **self._set_request_timeout(kwargs))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
  return self.request("GET", url, **kwargs)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
  resp = self.send(prep, **send_kwargs)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
  r = adapter.send(request, **kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 501, in send
  raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "/app/opendevin/server/agent/agent.py", line 159, in create_controller
  self.controller = AgentController(
           ^^^^^^^^^^^^^^^^
 File "/app/opendevin/controller/agent_controller.py", line 75, in __init__
  self.action_manager = ActionManager(self.id)
             ^^^^^^^^^^^^^^^^^^^^^^
 File "/app/opendevin/controller/action_manager.py", line 39, in __init__
  self.sandbox = DockerSSHBox(
          ^^^^^^^^^^^^^
 File "/app/opendevin/runtime/docker/ssh_box.py", line 78, in __init__
  raise ex
 File "/app/opendevin/runtime/docker/ssh_box.py", line 72, in __init__
  self.docker_client = docker.from_env()
             ^^^^^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/docker/client.py", line 94, in from_env
  return cls(
      ^^^^
 File "/app/.venv/lib/python3.12/site-packages/docker/client.py", line 45, in __init__
  self.api = APIClient(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 197, in __init__
  self._version = self._retrieve_server_version()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 220, in _retrieve_server_version
  raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
Starting loop_recv for sid: ac0e7886-727f-4403-bad1-2fb30cf63fa6
INFO:   172.17.0.1:57966 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO:   172.17.0.1:57958 - "GET /api/refresh-files HTTP/1.1" 200 OK
INFO:   172.17.0.1:57978 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:   172.17.0.1:57966 - "GET /api/agents HTTP/1.1" 200 OK
INFO:   172.17.0.1:57966 - "DELETE /api/messages HTTP/1.1" 200 OK

Above the errors I get. It's not a docker issue apparently

**Comment by isavita** [comment]
@suoko you might need to add `-e SANDBOX_USER_ID=$(id -u)` as well. From the newest README.md [here](https://github.com/OpenDevin/OpenDevin?tab=readme-ov-file#-quick-start)

**Comment by playlogo** [comment]
I got the same error and i narrowed it down to my user not being allowed to read & write to the docker socket `/var/run/docker.sock`
Running `sudo chmod 777 /var/run/docker.sock` is a temporary workaround, but keep in mind this makes the docker socket available to every user (!) thus giving everybody root access via docker. 
Also checkout this other issue #321 with a better solution (that didn't work for me).

**Comment by suoko** [comment]
> I got the same error and i narrowed it down to my user not being allowed to read & write to the docker socket `/var/run/docker.sock` Running `sudo chmod 777 /var/run/docker.sock` is a temporary workaround, but keep in mind this makes the docker socket available to every user (!) thus giving everybody root access via docker. Also checkout this other issue #321 with a better solution (that didn't work for me).

that worked, thanks, but now I'm here:

sudo docker run --rm     --add-host host.docker.internal=host-gateway     -e LLM_API_KEY="ollama"     -e LLM_BASE_URL="http://host.docker.internal:11434"     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE     -v $WORKSPACE_BASE:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     ghcr.io/opendevin/opendevin:main
[sudo] password for gabriele: 
usermod: no changes
Docker socket group id: 137
usermod: group '137' does not exist
INFO:     Started server process [12]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     ('172.17.0.1', 49166) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJhYzBlNzg4Ni03MjdmLTQ0MDMtYmFkMS0yZmIzMGNmNjNmYTYifQ.Qfl-TBQuRrTL4ydeAIBZQVxiWliITBhLB3YVqpuSw4I" [accepted]
INFO:     connection open
Starting loop_recv for sid: ac0e7886-727f-4403-bad1-2fb30cf63fa6
INFO:     172.17.0.1:36300 - "GET /api/refresh-files HTTP/1.1" 200 OK
18:07:28 - opendevin:INFO: agent.py:156 - Creating agent CodeActAgent using LLM ollama/llama2:latest
18:07:28 - opendevin:INFO: llm.py:67 - Initializing LLM with model: ollama/llama2:latest
18:07:28 - opendevin:INFO: ssh_box.py:67 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
18:07:28 - opendevin:INFO: ssh_box.py:370 - Container stopped
18:07:28 - opendevin:WARNING: ssh_box.py:382 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
18:07:28 - opendevin:INFO: ssh_box.py:391 - Mounting workspace directory: /home/gabriele/dev/workspace
18:07:28 - opendevin:INFO: ssh_box.py:412 - Container started
18:07:29 - opendevin:INFO: ssh_box.py:428 - waiting for container to start: 1, container status: running
18:07:30 - opendevin:INFO: ssh_box.py:191 - Connecting to opendevin@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 43533 opendevin@host.docker.internal` with the password '04330188-360f-4d19-804d-e5d179ddb362' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 43533 opendevin@localhost` with the password '04330188-360f-4d19-804d-e5d179ddb362 on the host machine (where you started the container).
18:08:11 - opendevin:ERROR: agent.py:167 - Error creating controller: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 159, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 75, in __init__
    self.action_manager = ActionManager(self.id)
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/action_manager.py", line 39, in __init__
    self.sandbox = DockerSSHBox(
                   ^^^^^^^^^^^^^
  File "/app/opendevin/runtime/docker/ssh_box.py", line 100, in __init__
    self.start_ssh_session()
  File "/app/opendevin/runtime/docker/ssh_box.py", line 196, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=self._ssh_port)
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 470, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
INFO:     172.17.0.1:36300 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO:     172.17.0.1:36310 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     172.17.0.1:59094 - "GET /api/agents HTTP/1.1" 200 OK
INFO:     172.17.0.1:43012 - "DELETE /api/messages HTTP/1.1" 200 OK
INFO:     172.17.0.1:43012 - "GET /index.html HTTP/1.1" 304 Not Modified
18:08:53 - opendevin:INFO: session.py:40 - WebSocket disconnected, sid: ac0e7886-727f-4403-bad1-2fb30cf63fa6
INFO:     connection closed
INFO:     ('172.17.0.1', 43030) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJhYzBlNzg4Ni03MjdmLTQ0MDMtYmFkMS0yZmIzMGNmNjNmYTYifQ.Qfl-TBQuRrTL4ydeAIBZQVxiWliITBhLB3YVqpuSw4I" [accepted]
INFO:     connection open
Starting loop_recv for sid: ac0e7886-727f-4403-bad1-2fb30cf63fa6
INFO:     172.17.0.1:43012 - "GET /api/refresh-files HTTP/1.1" 200 OK
18:08:53 - opendevin:INFO: agent.py:156 - Creating agent CodeActAgent using LLM ollama/llama2:latest
18:08:53 - opendevin:INFO: llm.py:67 - Initializing LLM with model: ollama/llama2:latest
18:08:53 - opendevin:INFO: ssh_box.py:67 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
18:08:53 - opendevin:INFO: ssh_box.py:370 - Container stopped
18:08:53 - opendevin:WARNING: ssh_box.py:382 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
18:08:53 - opendevin:INFO: ssh_box.py:391 - Mounting workspace directory: /home/gabriele/dev/workspace
18:08:53 - opendevin:INFO: ssh_box.py:412 - Container started
18:08:54 - opendevin:INFO: ssh_box.py:428 - waiting for container to start: 1, container status: running
18:08:55 - opendevin:INFO: ssh_box.py:191 - Connecting to opendevin@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 58411 opendevin@host.docker.internal` with the password '0c165874-da5a-4a15-884d-5a898fd2971b' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 58411 opendevin@localhost` with the password '0c165874-da5a-4a15-884d-5a898fd2971b on the host machine (where you started the container).
18:09:36 - opendevin:ERROR: agent.py:167 - Error creating controller: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 159, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 75, in __init__
    self.action_manager = ActionManager(self.id)
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/action_manager.py", line 39, in __init__
    self.sandbox = DockerSSHBox(
                   ^^^^^^^^^^^^^
  File "/app/opendevin/runtime/docker/ssh_box.py", line 100, in __init__
    self.start_ssh_session()
  File "/app/opendevin/runtime/docker/ssh_box.py", line 196, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=self._ssh_port)
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 470, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
INFO:     172.17.0.1:43012 - "GET /api/litellm-models HTTP/1.1" 200 OK
INFO:     172.17.0.1:43018 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     172.17.0.1:43032 - "GET /favicon-32x32.png HTTP/1.1" 304 Not Modified
INFO:     172.17.0.1:52832 - "GET /api/agents HTTP/1.1" 200 OK
INFO:     172.17.0.1:42746 - "DELETE /api/messages HTTP/1.1" 200 OK
18:10:01 - opendevin:INFO: agent.py:156 - Creating agent CodeActAgent using LLM ollama/llama3:latest
18:10:01 - opendevin:INFO: llm.py:67 - Initializing LLM with model: ollama/llama3:latest
18:10:01 - opendevin:INFO: ssh_box.py:67 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
18:10:01 - opendevin:INFO: ssh_box.py:370 - Container stopped
18:10:01 - opendevin:WARNING: ssh_box.py:382 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
18:10:01 - opendevin:INFO: ssh_box.py:391 - Mounting workspace directory: /home/gabriele/dev/workspace
18:10:01 - opendevin:INFO: ssh_box.py:412 - Container started
18:10:02 - opendevin:INFO: ssh_box.py:428 - waiting for container to start: 1, container status: running
18:10:03 - opendevin:INFO: ssh_box.py:191 - Connecting to opendevin@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 41631 opendevin@host.docker.internal` with the password '6a53da55-0baa-4cb6-a438-c8dd4e47d91c' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 41631 opendevin@localhost` with the password '6a53da55-0baa-4cb6-a438-c8dd4e47d91c on the host machine (where you started the container).
18:10:44 - opendevin:ERROR: agent.py:167 - Error creating controller: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 159, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 75, in __init__
    self.action_manager = ActionManager(self.id)
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/action_manager.py", line 39, in __init__
    self.sandbox = DockerSSHBox(
                   ^^^^^^^^^^^^^
  File "/app/opendevin/runtime/docker/ssh_box.py", line 100, in __init__
    self.start_ssh_session()
  File "/app/opendevin/runtime/docker/ssh_box.py", line 196, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=self._ssh_port)
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 470, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').

**Comment by imkebe** [comment]
Same issue. However adding SANDBOX_USER_ID hasn't fixed the issue. 

```Docker socket group id: 991
usermod: group '991' does not exist```

However `/etc/group` contains entry with `docker:x:991`

**Comment by imkebe** [comment]
I think it might be related #1582. Mine is also `uid 1000`.

**Comment by rbren** [comment]
Hey all--main issue is you need to be able to [run docker without sudo](https://www.baeldung.com/linux/docker-run-without-sudo)

See: https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting#unable-to-connect-to-docker

**Comment by imkebe** [comment]
@rbren My user is in docker group that allows docker running without sudo. That worked fine in 0.4. However - see my first comment - it reports that the group does not extists while it is.

**Comment by suoko** [comment]
I can run it without sude but I got this strange error, and bard suggests the wrong shell is used.
Is it possible that the macos shell is required ? Just guessing


19:09:52 - opendevin:ERROR: agent.py:167 - **Error creating controller: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').**
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 159, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 75, in __init__
    self.action_manager = ActionManager(self.id)
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/action_manager.py", line 39, in __init__
    self.sandbox = DockerSSHBox(
                   ^^^^^^^^^^^^^
  File "/app/opendevin/runtime/docker/ssh_box.py", line 100, in __init__
    self.start_ssh_session()
  File "/app/opendevin/runtime/docker/ssh_box.py", line 196, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=self._ssh_port)
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 470, in login
    raise ExceptionPxssh('could not set shell prompt '
pexpect.pxssh.ExceptionPxssh: could not set shell prompt (received: b"unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\nprompt restore;\r\nPS1='[PEXPECT]%(!.#.$) '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
INFO:     172.17.0.1:60934 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     172.17.0.1:60924 - "GET /api/agents HTTP/1.1" 200 OK
INFO:     ('172.17.0.1', 59236) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIwY2EzZWJlOS1kZTU4LTQzNGYtYjQwZi0yMDE0YTNiMDdmMzQifQ.L3wVK1fR6twq0kSkEi9Syb2Jvk5rxhsFMaR2haul_DA" [accepted]
19:09:52 - opendevin:INFO: session.py:40 - WebSocket disconnected, sid: 0ca3ebe9-de58-434f-b40f-2014a3b07f34
INFO:     connection closed
INFO:     connection open
19:09:52 - opendevin:INFO: session.py:40 - WebSocket disconnected, sid: 0ca3ebe9-de58-434f-b40f-2014a3b07f34
INFO:     connection closed

**Comment by imkebe** [comment]
@suoko look at #1594

**Comment by mannaandpoem** [comment]
> @rbren My user is in docker group that allows docker running without sudo. That worked fine in 0.4. However - see my first comment - it reports that the group does not extists
@rbren 
I also encounter this situation.
![image](https://github.com/OpenDevin/OpenDevin/assets/52203545/95fe22ce-2a37-42da-963f-b363cb0db366)

**Comment by mannaandpoem** [comment]
> @rbren My user is in docker group that allows docker running without sudo. That worked fine in 0.4. However - see my first comment - it reports that the group does not extists

I can run it normally after upgrading docker to 26.0.0

**Comment by imkebe** [comment]
Right now i again experiencing that in #1624 . My docker is 26.1.1 via official docker repo.
@mannaandpoem have you experienced the issue also ? Was there anything other than docker upgrade done?

**Comment by rbren** [comment]
@suoko your issue is a strange one I haven't seen before. Can you open a new issue if you're still seeing it on 0.5.3?
