### ISSUE TITLE
[Bug]: Unable to upgrade to tcp, received 404

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#1593]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Unable to upgrade to tcp, received 404

### Current Version

```bash
I use 0.5.0
```

### Installation and Configuration

```bash
export WORKSPACE_BASE=$(pwd)/workspace;

 docker run \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal=host-gateway \
    ghcr.io/opendevin/opendevin:0.5
0.5: Pulling from opendevin/opendevin
```

### Reproduction Steps

Pull the lastest commits from the repo.
Set the workspace.
Run the Docker command abovce.

### Logs, Errors, Screenshots, and Additional Context

Digest: sha256:7f17489e68873cdfe06b90d7cab902bf58fcd246a8f298c7b751ac191a3e8bc3
Status: Downloaded newer image for ghcr.io/opendevin/opendevin:0.5
unable to upgrade to tcp, received 404
pierruno@Pierruno:/mnt/c/Users/pierr/OpenDevin$

**Comment by rbren** [comment]
@PierrunoYT this seems like an issue with your docker daemon, not OpenDevin. You might want to try a restart
