### ISSUE TITLE
Simplify Message actions/observations

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#1595]
## Summary
Currently we have five separate representations of messages/text in the system:
* AgentTalkAction
* UserMessageObservation
* AgentMessageObservation
* MessageAction
* AgentEchoAction
* AgentThinkAction

Each of these serves a slightly different purpose in a different context. I'd like to simplify as much as possible.

### First: I think we should treat the user as just another agent.

We could hypothetically treat everything as being from the agent's perspective, so agent messages would be actions, and user messages would be observations. IMO that will probably lead us down the wrong path. Instead, we should make _both_ user and agent messages an Action.

Furthermore, they can be the same Action (MessageAction). I've added a `source` field to the EventStream, but it's not quite plumbed into agent history yet. For now, we could put `source` directly inside the `MessageAction` 

### Second: Information vs Interrupts

Sometimes the agent just wants to say "hey I'm gonna do a thing"--other times it needs to interrupt the user to ask for more info. IMO this could easily be handled by a field like `wait` on the `MessageAction`

### Third: Get rid of message observations
We should push everything into MessageAction, and get rid of UserMessageObservation and AgentMessageObservation.

This breaks AgentEchoAction, which is being used by CodeAct, though I'm not sure how. Hopefully @xingyaoww  can provide guidance here.

### Fourth: Think vs Message
We also have AgentThinkAction, which represents the agent's self-talk more than contact with the user. We currently just dump AgentThinkActions into the chat log, so the user can't really tell the difference.

Do we need AgentThinkAction? I'm torn on this one.

### Conclusion
We should simplify this list:
* AgentTalkAction
* UserMessageObservation
* AgentMessageObservation
* MessageAction
* AgentEchoAction
* AgentThinkAction

To just have `MessageAction`, with properties `source` and `wait`. We may want to consider keeping `AgentThinkAction` as well.

**Comment by neubig** [comment]
Overall I basically agree with this, I like the simplicity!

**Comment by xingyaoww** [comment]
> This breaks AgentEchoAction, which is being used by CodeAct, though I'm not sure how. Hopefully @xingyaoww can provide guidance here.

I think `AgentEchoAction` is no longer used by CodeAct, so if other agents are not using it, it is probably save to remove it.

> We could hypothetically treat everything as being from the agent's perspective, so agent messages would be actions, and user messages would be observations. IMO that will probably lead us down the wrong path. Instead, we should make both user and agent messages an Action.

Yeah I also kinda agree on this: We can basically define "observation" as "other agent's action" in this terminology. And/or even support more complex "partially observable" environment by selectively control what is visible to the agent
