### ISSUE TITLE
Build on top of MetaGPT

### ISSUE THREAD

**Issue by djaym7** [OpenDevin/OpenDevin#16]
To save significant effort, we should consider building on top of metaGPT: 

https://github.com/geekan/MetaGPT/tree/main

**Comment by geekan** [comment]
Hello, I am the author of MetaGPT, and I will participate in this work, especially the performance optimization of SWE-bench. Yesterday, I wrote a technical route for this dataset, covering the technical points of their technical report today, and also covering the technical points that they did not report.

![image](https://github.com/OpenDevin/OpenDevin/assets/2707039/d6a57312-0d87-4409-9790-d559127f9c08)

The truth is, it's not difficult to get there, but it does take some work.
Anyone who wants to participate in the performance optimization part is more than welcome.

**Comment by z-zeechung** [comment]
@geekan i'm currently working on llm apis, what interface i should prepare?

**Comment by mach-12** [comment]
@geekan Would be definitely up for that. Where is this conversation from, and how can I contribute?

**Comment by geekan** [comment]
@z-zeechung @mach-12 If you are interested in the current work, you are very welcome to join. We hope to surpass davin's SWE-bench score in the coming weeks. At present, we have a team starting to tackle the problem.

Anyone wants to join can send some basic information to my email, including: name, background, relevant experience, part you want to contribute, and time commitment (in the next 2 weeks). We will review it. For members who successfully join, we will open detailed ideas and documents related to this issue.

As for llm configuration and standardized interaction, you may refer to [example](https://github.com/geekan/MetaGPT/blob/main/examples/llm_hello_world.py) and [related config](https://github.com/geekan/MetaGPT/blob/main/config/config2.yaml)

If anyone is interested, you can find me at alexanderwu@deepwisdom.ai

**Comment by JustinLin610** [comment]
I'll close this as we are marching fast with community efforts. Reopen this for discussion of metagpt for this project.
