### ISSUE TITLE
[Bug]: Documentation typo, docker run command syntax fix

### ISSUE THREAD

**Issue by kviksna** [OpenDevin/OpenDevin#1603]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

In both info pages:
https://github.com/opendevin/OpenDevin/pkgs/container/sandbox
https://opendevin.github.io/OpenDevin/

docker run command syntax typo for "--add-host" parameter.

### Current Version

```bash
docker run \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal=host-gateway \
    ghcr.io/opendevin/opendevin:0.5
```

### Installation and Configuration

```bash
Fixed version:
docker run \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host=host.docker.internal:host-gateway \
    ghcr.io/opendevin/opendevin:0.5
```

**Comment by kviksna** [comment]
Does other docker version has different syntax? Fixed version works for me on Docker version 24.0.5.

**Comment by iFurySt** [comment]
in my machine, both work. 🤔

**Comment by iFurySt** [comment]
hmm, it seems the `--add-host a=b` doesn't work in 24.x.x

**Comment by rbren** [comment]
Thanks all! I think Graham had hit this too
