### ISSUE TITLE
[Bug]: Multiline/multiple commands look a bit awkward in the UI

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#1607]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When CodeAct runs multiple commands, like
```
pwd
ls -lah
```
or runs  a multiline command like
```
echo "Name,Age,Location
Alice,30,New York
Bob,25,Los Angeles
Charlie,35,Chicago" > sample.csv
```

The output looks a little funky (screenshot). The multi-command is printed with the second command looking like it's output. The multiline single command shows $PS2 characters repeating the command in the output.

Here's an example:
```
$ echo "Name,Age,Location
Alice,30,New York
Bob,25,Los Angeles
Charlie,35,Chicago" > sample.csv
> Alice,30,New York
> Bob,25,Los Angeles
> Charlie,35,Chicago" > sample.csv

$ echo 'awk -F"," '\''NR > 1 {print $2}'\'' sample.csv' > extract_field.sh
chmod +x extract_field.sh
```

<img width="1246" alt="Screenshot 2024-05-06 at 4 36 23 PM" src="https://github.com/OpenDevin/OpenDevin/assets/7611973/ae6ddc12-0c95-4c87-9bca-a366e8a04d15">

### Current Version

```bash
0.5.2
```

### Installation and Configuration

```bash
Typical
```

### Model and Agent

CodeAct, GPT4

**Comment by rbren** [comment]
CC @xingyaoww 

https://github.com/OpenDevin/OpenDevin/pull/1474 might help a bit with this. It at least introduces logic to split commands.

I've been thinking about a change that would allow agents to return a list of actions, instead of one action at a time. That would let us parse the multi-commands into separate RUN actions

**Comment by xingyaoww** [comment]
I think this is already resolved by https://github.com/OpenDevin/OpenDevin/pull/1474
