### ISSUE TITLE
Add version system for each agent

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#1611]
**What problem or use case are you trying to solve?**

We should have a versioning system for each agent to keep track of the changes in prompt, design, etc to make sure our evaluation can be reproducible.

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by yufansong** [comment]
do you want the specific version number or only use the commit hash number?

**Comment by iFurySt** [comment]
I’ve also noticed this issue recently

**Comment by Umpire2018** [comment]
> do you want the specific version number or only use the commit hash number?

I recommend to use the specific version number like `0.1.0` .

**Comment by li-boxuan** [comment]
I like the idea but it's gonna be hard to maintain because any change to the framework may require a version bump for all agents.

**Comment by li-boxuan** [comment]
If we just want to be able to reproduce experiments, commit hash should be enough and no need for a dedicated version system?

**Comment by yufansong** [comment]
> I like the idea but it's gonna be hard to maintain because any change to the framework may require a version bump for all agents.

I agree, I prefer set a seperate version for prompt or only use git commit hash id.

**Comment by xingyaoww** [comment]
> set a seperate version for prompt

I think that's primarily what we meant by adding a version system for agent - we only consider anything that changes the agent's prompt / implementation. The reason why we want to do that would be for reproducibility of evaluation score i guess.

**Comment by neubig** [comment]
Note that CodeAct agent already has a version number: https://github.com/OpenDevin/OpenDevin/blob/0fdbe1ee9340f4c7cdec15885e05e1dfd2070ba4/agenthub/codeact_agent/codeact_agent.py#L90

We could add versions to the other agents by doing something similar for all of the agents in the `agenthub/` directory.
