### ISSUE TITLE
[Bug]: Localhost:3000 is not working

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#1621]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I run the docker command with 0.5.2 and I visited localhost:3000 in Firefox via the Terminal after it showed the link but it says it can't build a connection

### Current Version

```bash
0.5.2
```

### Installation and Configuration

```bash
export WORKSPACE_BASE=$(pwd)/workspace;
pierruno@Pierruno:/mnt/c/Users/pierr/OpenDevin$ docker run \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal=host-gateway \
    ghcr.io/opendevin/opendevin:0.5.2
0.5.2: Pulling from opendevin/opendevin
```

### Reproduction Steps

Run the Commands above.
Wait until it downloaded and extracted.
Click on the localhost Url when it shows up in the terminal 

### Logs, Errors, Screenshots, and Additional Context

![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/3058ebad-812e-47c8-a8e8-61407c7966ac)
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/8bdd500d-b235-4f94-b914-ba4447d3b907)

**Comment by rbren** [comment]
Looks like you clicked the 0.0.0.0, which is not expected to work

**Comment by PierrunoYT** [comment]
> Looks like you clicked the 0.0.0.0, which is not expected to work

Yeah exactly.
