### ISSUE TITLE
[Bug]: Workspace fails to update and show the created files in it

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#1622]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I tried to make a Tetris game so I prompted OpenDevin to do so. It worked pretty good and better than the last versions but when i try to find the tetris.py I could not find it in the Workspace. I asked OpenDevin where the file is and it says it's there but the Workspace is not showing this files. Instead it's showing old files which I like to remove. I also clicked refresh. It also tried to give a task itself without any prompts.

### Current Version

```bash
O.5.2
```

### Installation and Configuration

```bash
I run the two command inside the quick start with the 0.5.2 then user German as language. CodeAct as the Agent an the model gpt-4-turbo-2024-04-09
```

### Model and Agent

Model: gpt-4-turbo-2024-04-09
Agent: CodeActAgent

### Reproduction Steps

Follow the steps above

### Logs, Errors, Screenshots, and Additional Context

![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/7e654253-6467-4102-9879-d4079992a89a)
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/e998e839-4ba4-41ed-a9a7-c7eae7115bff)
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/614a2728-66d3-4ba3-98e8-c16fe3eb79fe)
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/5f9ebe07-6838-4e67-9262-e92663d3ca87)

**Comment by rbren** [comment]
@PierrunoYT are you setting `SANDBOX_TYPE=exec` by chance?

**Comment by PierrunoYT** [comment]
> @PierrunoYT are you setting `SANDBOX_TYPE=exec` by chance?

Actually no. Should I?

**Comment by PierrunoYT** [comment]
Do you have any solution @rbren

**Comment by PierrunoYT** [comment]
@rbren Any updates on this?

**Comment by mamoodi** [comment]
@PierrunoYT Is this still an issue with the latest 0.6? I ran into this issue once but it was because I was looking at the wrong workspace. Remember that every time you open the terminal, you need to set the workspace. And the default README instructions set it to "(pwd)/workspace".
Please try the latest and if it's still an issue, please reopen.
