### ISSUE TITLE
Create Changelog for the Versions

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#1623]
**What problem or use case are you trying to solve?**
People in the Discord asking for the changes in the new versions but I could not provide them any.

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**
Create a new file with the changes inside and put it in the Docs.

**Describe alternatives you've considered**

**Additional context**

**Comment by neubig** [comment]
This can be fixed by adding the `--generate-notes` option on the command line or using the "generate notes" functionality in the web interface next time we cut a release.

**Comment by neubig** [comment]
This is fixed by using the github release functionality for recent releases: https://github.com/OpenDevin/OpenDevin/releases/tag/0.6.2
