### ISSUE TITLE
[Bug]: Setup error

### ISSUE THREAD

**Issue by zlip123** [OpenDevin/OpenDevin#1632]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I ran the docker container and entered my gpt4 (yes i pay) API key but it said i don't have access to the model? i made a new project key and got the same error. i tried gpt4 turbo and got the same error. lmk if you know what I'm missing.
<img width="1128" alt="i2" src="https://github.com/OpenDevin/OpenDevin/assets/68125655/21ba2a0e-71a4-4ea9-a9c9-5ac59a3267ce">
![i](https://github.com/OpenDevin/OpenDevin/assets/68125655/8f5633f6-e51f-471d-9fd1-0381d3d1c095)

### Current Version

```bash
ghcr.io/opendevin/opendevin:0.5
```

### Installation and Configuration

```bash
none extra
```

### Model and Agent

gpt-4

### Reproduction Steps

1. Cloned
2. Made workspace folder
3. Set workspace_base
4. Copy pasted docker run from the readme
5. Waited
6. Selected gpt-4 in pop menu and entered my new project key i made from openAI official website
7. It failed :(

### Logs, Errors, Screenshots, and Additional Context

<img width="1128" alt="i2" src="https://github.com/OpenDevin/OpenDevin/assets/68125655/d5960cb0-7cdb-4f41-9155-7d3b36753ff2">

**Comment by zlip123** [comment]
I tried again today and it still does not work.

**Comment by iFurySt** [comment]
how do you run it?

**Comment by zlip123** [comment]
I cloned the repo --> cd into it --> set workspace_base (export WORKSPACE_BASE=$(pwd)/workspace;) --> docker run command from the readme --> enter api key --> it doesnt work with new api keys (yes i pay for gpt4)

**Comment by SmartManoj** [comment]
Run this to check whether LLM is working properly.
```python
import tomllib as toml
from litellm import completion
from datetime import datetime
file_path=r'config.toml'
config = toml.load(open(file_path,'rb'))

messages = [{ "content": "If there are 10 books in a room and I read 2, how many books are still in the room?","role": "user"}]
dt = datetime.now()
response = completion(model=config['LLM_MODEL'], 
                        api_key=config['LLM_API_KEY'],
                        base_url=config.get('LLM_BASE_URL'),
                      messages=messages)

content = response.choices[0].message.content
print(content)

if '8' in content:
    print('--> Correct answer! 🎉')
    print('There are still 10 books in the room; reading them does not reduce the count. Consider exploring more accurate models for better results.')

dt2 = datetime.now()
print('Used model:',config['LLM_MODEL'])
print(f"Time taken: {(dt2-dt).total_seconds():.1f}s")
```

**Comment by enyst** [comment]
@zlip123 Does it work with gpt-3.5-turbo?

**Comment by zlip123** [comment]
@SmartManoj Do I make this file in the tests folder and download the dependencies and run through terminal?

**Comment by SmartManoj** [comment]
You can run anywhere.

Run this to check whether LLM is working properly.
```python
from litellm import completion
from datetime import datetime
config = {
    'LLM_MODEL': 'gpt-4-turbo-2024-04-09',
    'LLM_API_KEY': 'your-api-key',
    'LLM_BASE_URL': ''
}

messages = [{ "content": "If there are 10 books in a room and I read 2, how many books are still in the room?","role": "user"}]
dt = datetime.now()
response = completion(model=config['LLM_MODEL'], 
                        api_key=config['LLM_API_KEY'],
                        base_url=config.get('LLM_BASE_URL'),
                      messages=messages)

content = response.choices[0].message.content
print(content)

if '8' in content:
    print('--> Correct answer! 🎉')
    print('There are still 10 books in the room; reading them does not reduce the count. Consider exploring more accurate models for better results.')

dt2 = datetime.now()
print('Used model:',config['LLM_MODEL'])
print(f"Time taken: {(dt2-dt).total_seconds():.1f}s")
```

**Comment by neubig** [comment]
Yes, @zlip123 , you can run it through the terminal. This will help test whether it's a problem with your API key or something else.
