### ISSUE TITLE
Use pydantic to enforce type checks for Action

### ISSUE THREAD

**Issue by li-boxuan** [OpenDevin/OpenDevin#1634]
**What problem or use case are you trying to solve?**

Actions are decorated by`@dataclass` from `dataclasses` package. This, together with mypy defined in the pre-commit hooks, does static type checks, but still doesn't enforce type checks during runtime. This means a wrong json generated by LLM might be deserialized into an `Action` object without type errors.

Proof: `test_action_serialization.py` has two bugs:
- `test_modify_task_action_serialization_deserialization` uses `int` type for `id` while it should be `str`.
-  `test_cmd_kill_action_serialization_deserialization` uses `str` type for `id` while it should be `int`.

These bugs are not captured by pytest, because we don't enforce type checks during runtime.

**Describe the UX of the solution you'd like**

Use pydantic's BaseModel to replace `@dataclass` annotations for Action classes.

**Do you have thoughts on the technical implementation?**

~~This seems straightforward to fix, but it would be cool if someone could use OpenDevin to fix it!~~

**Comment by li-boxuan** [comment]
This issue is both a "feature request" and a "bug". The "bug" is not in the real code, but in the unit test itself.

**Comment by Umpire2018** [comment]
Hi, there! Please assign it to me and i will give it a shot. :)

**Comment by enyst** [comment]
Isn't it possible to use validation, including pydantic validators, on dataclasses? Perhaps we don't need to go the whole way to inherit BaseModel to achieve more type enforcement. e.g. [https://docs.pydantic.dev/latest/concepts/dataclasses/](https://docs.pydantic.dev/latest/concepts/dataclasses/)

It would keep it simple, and TBH feels more suited to the style of the codebase.

**Comment by li-boxuan** [comment]
I tried that but then gave up due to some reason I cannot remember ;)

If it works then it’s great!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Umpire2018** [comment]
I discovered something interesting. It seems like Pydantic has a [data conversion mechanism](https://docs.pydantic.dev/1.10/usage/models/#data-conversion) that converts strings, like `1`, to integers. What do you all think? Should we enable [strict type checking](https://docs.pydantic.dev/1.10/usage/types/#strict-types) or use a `str` type for `id`?

```python
from pydantic.dataclasses import dataclass

@dataclass
class Model(BaseModel):
    a: int
    b: float
    c: str


print(Model(a=3.1415, b=' 2.72 ', c=123).dict())
#> {'a': 3, 'b': 2.72, 'c': '123'}


from pydantic import StrictInt

class StrictIntModel(BaseModel):
    strict_int: StrictInt

try:
    StrictIntModel(strict_int=3.14159)
except ValidationError as e:
    print(e)
    """
    1 validation error for StrictIntModel
    strict_int
      value is not a valid integer (type=type_error.integer)
    """

```

**Comment by enyst** [comment]
I think we are forgiving about actions, or we are trying to, because the majority of them come from the LLM. Currently, if the LLM is sending something that isn't quite right, but we can figure out how to fix it, then we fix it. We try to do that with JSON 'fixes' for example, which we apply on the raw response.

It seems to me that sending '42' for the kill command instead of 42, or the other way around, is one of those we can try to fix and continue normally. Same for things like 'background': false, if it ever happens to be 'background': 'false'.

```json
{
  "action": "message",
  "args": {
    "content": "I should start by researching existing solutions to the twelve queens problem in Python.",
    "wait_for_response": false
  }
}
```

On the other hand, somewhere in my archived logs, there's this:
```
{
  "action": "kill",
  "args": {
    "id": "kill pid"
  }
}
```
😆 
(I think I asked it to send itself a kill)
This action did fail, as expected, we can't imagine what pid it wanted. It failed in the ssh_box with SandboxInvalidBackgroundCommandError, and that error was sent to the LLM. (Apparently the LLM was... err, happy about it, because next time it sent a Finish action. 😅 Good for you, GPT.)

With validation, it would fail sooner. That... seems the right behavior, doesn't it?

**Comment by Umpire2018** [comment]
> It seems to me that sending '42' for the kill command instead of 42, or the other way around, is one of those we can try to fix and continue normally. Same for things like 'background': false, if it ever happens to be 'background': 'false'.

First thing that come out of my mind is what if we add args type in prompt? like
* `kill` - kills a background command
  * `id: int` - the ID of the background command to kill

**Comment by li-boxuan** [comment]
FWIW I just removed `good first issue` label as this is getting more complicated than I initially thought ;)

> First thing that come out of my mind is what if we add args type in prompt?

That will help a bit, but still LLMs can make mistakes. I don't think adding it necessary if we have a way (and if we need a way anyways) to fix it.

It adding a prompt doesn't make the workflow marginally better, then we should double think before doing it.
