### ISSUE TITLE
How to reproduce the results on SWE-Bench

### ISSUE THREAD

**Issue by mannaandpoem** [OpenDevin/OpenDevin#1636]
## How to repreduce this result on SWE-Bench: https://xwang.dev/blog/2024/opendevin-codeact-1.0-swebench/

I'm using the main branch, selecting CodeActAgent as the agent and gpt-4-1106-preview as the base model. Given a link to an issue, it can be fixed to a certain extent, but it does not actually modify the local file, and it does not execute the git commit and git push commands.

**Comment by neubig** [comment]
Did you take a look at these pages?
* https://github.com/OpenDevin/OpenDevin/tree/bl-xw/swe-bench/evaluation/swe_bench
* https://github.com/OpenDevin/OD-SWE-bench/tree/eval

**Comment by mannaandpoem** [comment]
Thank you! The first link show that 404 - page not found. But I see evaluation update.

**Comment by li-boxuan** [comment]
@mannaandpoem check out https://github.com/OpenDevin/OpenDevin/tree/main/evaluation/swe_bench
