### ISSUE TITLE
[Bug]: Poetry stuck when installl

### ISSUE THREAD

**Issue by kroni66** [OpenDevin/OpenDevin#1640]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Poetry installing stuck and not continue.
for fix i recommend command before poetry install:
@poetry config keyring.enabled false

### Current Version

```bash
ghcr.io/opendevin/opendevin:0.5
```

### Installation and Configuration

```bash
@poetry config keyring.enabled false
```

**Comment by Umpire2018** [comment]
Can you attach more logs? I can't re-produce your error.

**Comment by iFurySt** [comment]
https://github.com/pypa/pip/issues/7883
https://github.com/python-poetry/poetry/issues/1526

some people encountered this problem. but i am not sure to disable keyring is a good solution. 🤔

**Comment by rbren** [comment]
Seems like this is a poetry issue more than an opendevin issue, so I'm going to close this one
