### ISSUE TITLE
[Bug]: "Reset to defaults" button text is empty

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#1647]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

<img width="480" alt="Screenshot 2024-05-08 at 9 49 12 AM" src="https://github.com/OpenDevin/OpenDevin/assets/7611973/242896c7-bffb-48f5-99b6-2e8c17021c66">

### Current Version

```bash
❯ git log -n1
commit c2868985e4512d147adfaaab02166c67ab6edbac (HEAD -> main, origin/main, origin/HEAD)
Author: AJ (@techfren) <aj47@users.noreply.github.com>
Date:   Wed May 8 22:20:31 2024 +1000

    add sandbox_user_id to run command which is neccesary (#1641)

```
```


### Installation and Configuration

```bash
Running in dev mode
```

### Model and Agent

any

### Reproduction Steps

For me, just open the settings modal

**Comment by rbren** [comment]
CC @D0odi @amanape

**Comment by amanape** [comment]
@rbren New translations have been added to our i18n provider for the button. On the development environment, run `npm run make-i18n` to generate the new translations.

Does the issue persist when running the public Docker command?

**Comment by rbren** [comment]
Ahh you're exactly right! Thanks
