### ISSUE TITLE
Make terminal interactive

### ISSUE THREAD

**Issue by gabboo90** [OpenDevin/OpenDevin#1655]
why is the terminal read only?
first i thought its a bug but than i saw its also on a screenshot from github page. is this normal?
https://github.com/OpenDevin/OpenDevin/raw/main/docs/static/img/screenshot.png
Image

**Comment by rbren** [comment]
Yes--the terminal isn't yet interactive. It's something we could add though!

**Comment by ztxtz** [comment]
Making it interactive would be helpful to help it recover from installation issues. Sometimes, the agent asks the user to install something due to recurrent timeout errors.

**Comment by mamoodi** [comment]
Terminal is now interactive. Closing
