### ISSUE TITLE
Windows 11: Connection closed Error sending data to client 

### ISSUE THREAD

**Issue by sonicino2** [OpenDevin/OpenDevin#166]
Hello, Windows 11 user. While OpenDev is running I get this this error as OpenDev makes my app.:

runnable=False)    
 ---
ACTION NOT EXECUTABLE
OBSERVATION

==============
Error sending data to client
Error sending data to client Cannot call "send" once a close message has been sent.
INFO:     connection closed
Error sending data to client
Error sending data to client
Client websocket disconnected (<CloseCode.ABNORMAL_CLOSURE: 1006>, None)
Error sending data to client
Error sending data to client

Any help would be appreciated.

**Comment by rbren** [comment]
Guessing you're hitting the same thing as this windows user: https://github.com/OpenDevin/OpenDevin/issues/169

Can you try this branch: `rb/fix-uid`?

**Comment by sonicino2** [comment]
I'm so sorry, how do I run that command (rb/fix-uid)?

**Comment by sonicino2** [comment]
Thanks man, looks like that worked!

**Comment by sonicino2** [comment]
If you want to see my log history, I wouldn't mind showing as the project was just a test.

**Comment by rbren** [comment]
Logs would be very helpful!

**Comment by sonicino2** [comment]
I was trying to recreate the game pac-man in python, here are my most recent logs. The problem also might stem from a resetting of the operation in total, as the project went outside of it's working directory while producing code. 
[LogHist1.txt](https://github.com/OpenDevin/OpenDevin/files/14763244/LogHist1.txt)

**Comment by rbren** [comment]
Super helpful, thanks! Two main errors I see

The LLM repeatedly tries to use key `contents` instead of `content`. Can probably have more robust parsing for that case.
```
        AGENT ERROR:
        FileWriteAction.__init__() got an unexpected keyword argument 'content'
Traceback (most recent call last):
  File "C:\Users\sonic\Downloads\OpenDevin\opendevin\controller\__init__.py", line 85, in step
    action = self.agent.step(state)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sonic\Downloads\OpenDevin\agenthub\langchains_agent\__init__.py", line 174, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sonic\Downloads\OpenDevin\agenthub\langchains_agent\utils\prompts.py", line 168, in parse_action_response
    action = ACTION_TYPE_TO_CLASS[action_dict["action"]](**action_dict["args"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FileWriteAction.__init__() got an unexpected keyword argument 'content'

        OBSERVATION:
        FileWriteAction.__init__() got an unexpected keyword argument 'content'
```

And a more serious error:
```
        AGENT ERROR:
        'AgentSummarizeAction' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\sonic\Downloads\OpenDevin\opendevin\controller\__init__.py", line 85, in step
    action = self.agent.step(state)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sonic\Downloads\OpenDevin\agenthub\langchains_agent\__init__.py", line 166, in step
    prompt = prompts.get_request_action_prompt(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sonic\Downloads\OpenDevin\agenthub\langchains_agent\utils\prompts.py", line 141, in get_request_action_prompt
    if latest_thought["action"] == 'think':
       ~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'AgentSummarizeAction' object is not subscriptable

        OBSERVATION:
        'AgentSummarizeAction' object is not subscriptable
```

I'll get in a fix for this

I'm not sure why the process exited. Looks like the client connection was closed--did you start this session from the browser?

**Comment by sonicino2** [comment]
Yes, after running npm run start -- --port 3001.

**Comment by rbren** [comment]
OK--all merged. I think the frontend bug might be this issue: https://github.com/OpenDevin/OpenDevin/issues/235

Going to close this one for now. If you're still not able to run OpenDevin, go ahead and open a new issue!

**Comment by benjaminjamesau** [comment]
Hi I am seeing a similar error as well

Error sending data to client Cannot call "send" once a close message has been sent.
