### ISSUE TITLE
[Bug]: cannot call recv while another coroutine is already waiting for the next message

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#1671]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Not sure what's the bug

### Current Version

```bash
0.5.2
```

### Installation and Configuration

```bash
The same as in the readme
```

### Model and Agent

CodeAct
gpt-4-turbo-2024-04-09

### Reproduction Steps

Not sure

### Logs, Errors, Screenshots, and Additional Context

19:06:51 - opendevin:INFO: agent_controller.py:201 - Setting agent state from AgentState.RUNNING to AgentState.AWAITING_USER_INPUT
INFO:     connection closed
19:06:51 - opendevin:ERROR: session.py:45 - Error in loop_recv: cannot call recv while another coroutine is already waiting for the next message
Traceback (most recent call last):
  File "/app/opendevin/server/session/session.py", line 30, in loop_recv
    data = await self.websocket.receive_json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/starlette/websockets.py", line 157, in receive_json
    message = await self.receive()
              ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/starlette/websockets.py", line 49, in receive
    message = await self._receive()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 379, in asgi_receive
    data = await self.recv()
           ^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 533, in recv
    raise RuntimeError(
RuntimeError: cannot call recv while another coroutine is already waiting for the next message
Starting loop_recv for sid: 5f07d3f7-44f1-491d-85a3-3573961e2d18
INFO:     172.17.0.1:53110 - "GET /api/messages/total HTTP/1.1" 200 OK
INFO:     172.17.0.1:56722 - "GET /api/messages HTTP/1.1" 200 OK

**Comment by rbren** [comment]
@PierrunoYT there's probably another error above this one--that's usually what triggers this for me.

Feel free to open a new issue if you're able to repro a second time and capture all the logs
