### ISSUE TITLE
[Bug]: CodeActAgent can't browse the web

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#1672]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I asked it to browse the web for a task and it told me it can't

### Current Version

```bash
0.5.2
```

### Installation and Configuration

```bash
The same as in the readme
```

### Model and Agent

CodeActAgent
gpt-4-turbo-2024-04-09

### Reproduction Steps

Asking to Browse the web for a task and give a link to browse it.

### Logs, Errors, Screenshots, and Additional Context

![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/72c90a6c-94aa-4dab-9e53-db2b0b8b74a2)
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/13212094-be03-4dd9-b54a-1255928c3af5)

**Comment by rbren** [comment]
Going to close this in favor of https://github.com/OpenDevin/OpenDevin/issues/1674
