### ISSUE TITLE
[Proposal]: Remove upper-case imports from typing

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#1673]
**Summary**

Currently we are using the old syntax of 
```python
from typing import List

my_list: List[str] = []
```

But we support Python 3.11, which can just use the following
```python
my_list: list[str] = []
```

We can remove imports from typing, and use this lower-case syntax instead.

**Comment by ammarladhani** [comment]
Hey! Just removed all 'List' imports from typing and used the lower case 'list' in its place. Please let me know if it all looks good or if I can do anything to fix it.
