### ISSUE TITLE
[Bug]: CONNECTION ERROR

### ISSUE THREAD

**Issue by BISHOPLOL9** [OpenDevin/OpenDevin#1689]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

index-BNujsEV6.js:318 
 Mixed Content: The page at 'https://vigilant-sniffle-699pq6q9xvr4cx6p6-3000.app.github.dev/index.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://vigilant-sniffle-699pq6q9xvr4cx6p6-3000.app.github.dev/ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJhZmJjODQ5Mi05MjI3LTQyNWQtYTZhYy05ZDYyYjNmZGU1MmYifQ.fr-nCoBjw5kPhF6KFUGHY1PUfKpFoKjrybgiyrYAoEg'. This request has been blocked; this endpoint must be available over WSS.

### Current Version

```bash
index-BNujsEV6.js:318 
 Mixed Content: The page at 'https://vigilant-sniffle-699pq6q9xvr4cx6p6-3000.app.github.dev/index.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://vigilant-sniffle-699pq6q9xvr4cx6p6-3000.app.github.dev/ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJhZmJjODQ5Mi05MjI3LTQyNWQtYTZhYy05ZDYyYjNmZGU1MmYifQ.fr-nCoBjw5kPhF6KFUGHY1PUfKpFoKjrybgiyrYAoEg'. This request has been blocked; this endpoint must be available over WSS.
```

### Installation and Configuration

```bash
index-BNujsEV6.js:318 
 Mixed Content: The page at 'https://vigilant-sniffle-699pq6q9xvr4cx6p6-3000.app.github.dev/index.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://vigilant-sniffle-699pq6q9xvr4cx6p6-3000.app.github.dev/ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJhZmJjODQ5Mi05MjI3LTQyNWQtYTZhYy05ZDYyYjNmZGU1MmYifQ.fr-nCoBjw5kPhF6KFUGHY1PUfKpFoKjrybgiyrYAoEg'. This request has been blocked; this endpoint must be available over WSS.
```

### Model and Agent

index-BNujsEV6.js:318 
 Mixed Content: The page at 'https://vigilant-sniffle-699pq6q9xvr4cx6p6-3000.app.github.dev/index.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://vigilant-sniffle-699pq6q9xvr4cx6p6-3000.app.github.dev/ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJhZmJjODQ5Mi05MjI3LTQyNWQtYTZhYy05ZDYyYjNmZGU1MmYifQ.fr-nCoBjw5kPhF6KFUGHY1PUfKpFoKjrybgiyrYAoEg'. This request has been blocked; this endpoint must be available over WSS.

### Reproduction Steps

index-BNujsEV6.js:318 
 Mixed Content: The page at 'https://vigilant-sniffle-699pq6q9xvr4cx6p6-3000.app.github.dev/index.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://vigilant-sniffle-699pq6q9xvr4cx6p6-3000.app.github.dev/ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJhZmJjODQ5Mi05MjI3LTQyNWQtYTZhYy05ZDYyYjNmZGU1MmYifQ.fr-nCoBjw5kPhF6KFUGHY1PUfKpFoKjrybgiyrYAoEg'. This request has been blocked; this endpoint must be available over WSS.

### Logs, Errors, Screenshots, and Additional Context

index-BNujsEV6.js:318 
 Mixed Content: The page at 'https://vigilant-sniffle-699pq6q9xvr4cx6p6-3000.app.github.dev/index.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://vigilant-sniffle-699pq6q9xvr4cx6p6-3000.app.github.dev/ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJhZmJjODQ5Mi05MjI3LTQyNWQtYTZhYy05ZDYyYjNmZGU1MmYifQ.fr-nCoBjw5kPhF6KFUGHY1PUfKpFoKjrybgiyrYAoEg'. This request has been blocked; this endpoint must be available over WSS.

**Comment by yufansong** [comment]
can you tell us how to reproduce this problem?
