### ISSUE TITLE
[Bug]: litellm.exceptions.APIConnectionError: LLM Provider NOT provided.

### ISSUE THREAD

**Issue by cope** [OpenDevin/OpenDevin#1694]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

litellm.exceptions.APIConnectionError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=codellama:7b-code-q8_0

### Current Version

```bash
ghcr.io/opendevin/opendevin:0.5.2
```

### Installation and Configuration

```bash
See reproduction steps, below.
```

### Model and Agent

- Model: codellama:7b-code-q8_0
- Agent: CodeActAgent

### Reproduction Steps

Started Ollama with:
```
docker run -d --restart unless-stopped \
-v "D:/db/ollama:/root/.ollama" \
-p 11434:11434 \
--name ollama \
ollama/ollama
```
Then inside ollama ran `ollama pull codellama:7b-code-q8_0`.

Started OpenDevin with:
```
docker run -d --restart unless-stopped \
-p 3000:3000 \
-e SANDBOX_USER_ID=1003 \
-e LLM_API_KEY="ollama" \
-e LLM_BASE_URL="http://host.docker.internal:11434" \
-e WORKSPACE_MOUNT_PATH=D:/db/opendevin \
-v D:/db/opendevin:/opt/workspace_base \
-v /var/run/docker.sock:/var/run/docker.sock \
--add-host host.docker.internal:host-gateway \
--name devin \
ghcr.io/opendevin/opendevin:0.5.2
```

### Logs, Errors, Screenshots, and Additional Context

![image](https://github.com/OpenDevin/OpenDevin/assets/112515/9d77ca49-5ce4-4002-9ee6-7347a10e75f4)

**Comment by enyst** [comment]
This error happens quite a bit because of the model name. It needs to be like, 'ollama/name here' or the full name that you see in `ollama serve`. Can you please try to verify that?

**Comment by cope** [comment]
checking

**Comment by cope** [comment]
I tried with _ollama/codellama:7b-code-q8_0_ and now it seems to be thinking...
![image](https://github.com/OpenDevin/OpenDevin/assets/112515/82b1fc8a-952d-4290-aff8-9853c16504d1)

I will try a different prompt, maybe this is confusing for it.

**Comment by cope** [comment]
OK, the PC fan speed indicated I should put my table in the upright position....... I presume

**Comment by cope** [comment]
OK, we might have liftoff
![image](https://github.com/OpenDevin/OpenDevin/assets/112515/97bcad7c-a95f-4667-b32b-abcb87484a2f)

**Comment by cope** [comment]
Maybe not, if it is waiting for my input but did not ask me anything :(
![image](https://github.com/OpenDevin/OpenDevin/assets/112515/a7aa9bbb-93a2-4b51-b161-ec9cd4b0345f)

**Comment by cope** [comment]
darn, it keeps `Setting agent state from AgentState.RUNNING to AgentState.AWAITING_USER_INPUT` and yet the prompt is just empty
![image](https://github.com/OpenDevin/OpenDevin/assets/112515/8e38bb90-59dd-435e-a18f-d8d052cdb005)

**Comment by yufansong** [comment]
> 172.17.0.1:51302 - "GET /api/select-file?file= HTTP/1.1" 500 Internal Server Error

Do you have more log about this internal server error?

**Comment by enyst** [comment]
For Windows, you may also want to see this: https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting/windows

**Comment by rbren** [comment]
The empty responses are likely due to the underpowered LLM :/

**Comment by rbren** [comment]
@cope seems like the original issue has been solved here. Feel free to open a new issue for the empty responses or the 500 error
