### ISSUE TITLE
[Bug]: CodeActAgent do nothing only write instructions.

### ISSUE THREAD

**Issue by kroni66** [OpenDevin/OpenDevin#1714]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

CodeActAgent only write instruction for me but not work autonomously.

### Current Version

```bash
main
```

### Installation and Configuration

```bash
Installed by make build, make run
```

**Comment by SmartManoj** [comment]
Could you add the logs?

**Comment by rbren** [comment]
@kroni66 we'll need to know what model you're using here

**Comment by rbren** [comment]
I'd recommend trying GPT-4 or Claude. They seem to work best.

Smaller models often get stuck in loops unfortunately. Hopefully LLM tech continues to improve!

**Comment by SmartManoj** [comment]
@pivettamarcos Could you provide logs?

**Comment by rbren** [comment]
codellama:7b is probably too small a model for tasks like these. I'd suggest using a 70b model, or better, GPT-4 or Claude

**Comment by adamwawrzynski** [comment]
I've encountered the same problem using the latest docker image (tags `0.7.1` and `0.7.0`) with local Ollama with `codellama` and `phi3` models. I haven't tested yet with `OpenAI` models but I will try in the future. The model generates plans and responses as normal chat does - it does not interact with the terminal, files, or browser to accomplish its tasks.

In attachment there is a zip archive with OBS recorded terminal and UI.
[2024-07-11 19-5.zip](https://github.com/user-attachments/files/16181722/2024-07-11.19-5.zip)

**Comment by SmartManoj** [comment]
LLM_MODEL - `llama3-8b-8192`

Version: 1d4f422638fb2ac6a3f698168db88abb50056f10

![image](https://github.com/user-attachments/assets/ac0e138e-6ce3-4301-b8f8-99f9eda3b572)

[Trajectory](https://od-feedback.vercel.app/show?feedback_id=93d5815b49f73a732f71f77a992a4d82a20fd11cc5f97895638be7558fdde3f8)
