### ISSUE TITLE
[Bug]: Not running in Docker Desktop with Git Bash

### ISSUE THREAD

**Issue by melvincv** [OpenDevin/OpenDevin#1715]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

OpenDevin container does not start in Docker Desktop using Git Bash for the run commands.

### Current Version

```bash
0.5
```

### Installation and Configuration

```bash
#!/bin/bash
#The directory you want OpenDevin to modify. MUST be an absolute path!
export WORKSPACE_BASE=$(pwd)/workspace;
echo $WORKSPACE_BASE

docker run --name opendevin \
    --restart unless-stopped \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    ghcr.io/opendevin/opendevin:0.5
```

### Reproduction Steps

1. Make a shell script called run.sh and make it executable
2. Execute it
3. Observe the error

### Logs, Errors, Screenshots, and Additional Context

$ ./run.sh
/d/docker/opendevin/workspace
docker: Error response from daemon: mkdir C:\Program Files\Git\var: Access is denied.
See 'docker run --help'.

**Comment by SmartManoj** [comment]
use wsl
