### ISSUE TITLE
Create a GitHub release for every tag

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#1717]
**What problem or use case are you trying to solve?**
Create a GitHub release for every tag"

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**
Use the Github in-build function

**Describe alternatives you've considered**

**Additional context**

**Comment by neubig** [comment]
See discussion on #1768, but we already [have a release for every tag](https://github.com/OpenDevin/OpenDevin/tags), the release notes are just not very complete right now. We will fix the incomplete release notes in #1623
