### ISSUE TITLE
[Bug]: cannot statx '/var/run/docker.sock': No such file or directory

### ISSUE THREAD

**Issue by 450220020** [OpenDevin/OpenDevin#1732]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

$ docker run     --pull=always     -e SANDBOX_USER_ID=$(id -u)     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE     -v $WORKSPACE_BASE:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     --add-host host.docker.internal:host-gateway     ghcr.io/opendevin/opendevin:0.5
0.5: Pulling from opendevin/opendevin

### Current Version

```bash
Digest: sha256:f871f88ce3a5e8ef5fc40ecb0f8ef8c2fe6886f4c9b4bb3544d71c2b7c40ff03
Status: Image is up to date for ghcr.io/opendevin/opendevin:0.5
Starting OpenDevin...
Setting up enduser with id 197609
useradd warning: enduser's uid 197609 outside of the UID_MIN 499 and UID_MAX 60000 range.
stat: cannot statx '/var/run/docker.sock': No such file or directory
```

### Installation and Configuration

```bash
default
```

### Logs, Errors, Screenshots, and Additional Context

Digest: sha256:f871f88ce3a5e8ef5fc40ecb0f8ef8c2fe6886f4c9b4bb3544d71c2b7c40ff03
Status: Image is up to date for ghcr.io/opendevin/opendevin:0.5
Starting OpenDevin...
Setting up enduser with id 197609
useradd warning: enduser's uid 197609 outside of the UID_MIN 499 and UID_MAX 60000 range.
stat: cannot statx '/var/run/docker.sock': No such file or directory

**Comment by yufansong** [comment]
I guess this problem may related to your own docker rather than opendevin. Does you docker launch correctly?

**Comment by 450220020** [comment]
> 我想这个问题可能与您自己的 docker 而不是 opendevin 有关。你 docker 是否正确启动？

Booted correctly, but in a windows environment

**Comment by rbren** [comment]
Our recommendation is to run in WSL

**Comment by mamoodi** [comment]
Closing as running on Windows without WSL is not supported.
