### ISSUE TITLE
Improve documentation on refractored config

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#1734]
**What problem or use case are you trying to solve?**

Improve documentation for `config` updated in https://github.com/OpenDevin/OpenDevin/pull/1552

**Describe the UX of the solution you'd like**

Update the documentation sites with different config & example `config.toml` for people to directly copy?

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by enyst** [comment]
Great point, I'll do that.

There is `make setup-config` which creates a working file, it has just a few variables though, just enough to start the app with a regular model.

The .env vars continue to work, they're the same vars.

**Comment by enyst** [comment]
This should be fixed, by https://github.com/OpenDevin/OpenDevin/pull/1929 and the examples in tutorials/readme for evaluation. Please feel free to reopen if not.
