### ISSUE TITLE
Support expanding frontend window in all directions

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#1745]
**What problem or use case are you trying to solve?**

Context: https://opendevin.slack.com/archives/C06QT0AGY4W/p1715546877469529?thread_ts=1715007881.546429&cid=C06QT0AGY4W

**Describe the UX of the solution you'd like**

Allow each window to dragged to all directions:

![image](https://github.com/OpenDevin/OpenDevin/assets/38853559/aafb8a08-62c5-4f44-89b7-eeeb2fcb6732)

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by mamoodi** [comment]
Currently the "Chat" box can be expanded. However, the "Terminal" and the box containing the browser, workspace cannot be expanded.

**Comment by xingyaoww** [comment]
Fixed by #3330.
