### ISSUE TITLE
[Frontend] Improve Window Manipulation Flexibility

### ISSUE THREAD

**Issue by isavita** [OpenDevin/OpenDevin#1746]
### Issue Description
The current window management in our development environment lacks flexibility in movement and resizing, limiting how developers can arrange their workspace.

### Suggested Enhancement
Enhance the window manipulation capabilities to:
- Allow horizontal dragging (left and right) for windows positioned in the center of the screen.
- Enable windows on the sides of the screen to expand fully to the adjacent edge or contract to a minimized state.

### Expected Benefits
- **Improved Workspace Efficiency:** Developers can adjust their workspace layout quickly, tailoring it to their specific tasks and preferences.
- **Enhanced User Experience:** Easier window management will make the environment more intuitive and responsive to developer needs.

### Implementation Considerations
- Ensure that these new features do not conflict with existing window functions like resizing and minimizing.
- Include options to save window positions and states to maintain setups across sessions.

**Comment by enyst** [comment]
Hah, this was posted in about the same time with: https://github.com/OpenDevin/OpenDevin/issues/1745 😅 

Closing this one, but lets continue there.

**Comment by isavita** [comment]
@enyst this was for Devin, but I ended up using the other one.
