### ISSUE TITLE
Unknown Observation Type Causes Premature Exit

### ISSUE THREAD

**Issue by jwoongkim11** [OpenDevin/OpenDevin#175]
**Describe the bug**
While running the code, I encountered an error that stops execution with the message:

Error in loop Unknown observation type: 
Exited before finishing

**Steps to Reproduce**
1. Set up and run the server with uvicorn opendevin.server.listen:app --port 3000.
2. Perform actions leading to STEP 2 where the error occurs.

**Additional context**

Terminal log
:

(venv) jay@Jayui-MacBookPro OpenDevin % uvicorn opendevin.server.listen:app --port 3000

INFO: Started server process [6538]
INFO: Waiting for application startup.
INFO: Application startup complete.
INFO: Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO: ('127.0.0.1', 61060) - "WebSocket /ws" [accepted]
INFO: connection open

============== STEP 0

ACTION: CmdRunAction(command='ls', background=False)

OBSERVATION: OpenDevin settings.md

============== STEP 1

ACTION: AgentThinkAction(thought="The 'ls' command output shows there's an 'OpenDevin' directory and a 'settings.md' file. I should explore the 'OpenDevin' directory next.", runnable=False)

OBSERVATION:

============== STEP 2 Error in loop Unknown observation type: Exited before finishing

**Comment by rbren** [comment]
This is fixed in #184
