### ISSUE TITLE
Support for other programming languages and paradigms. 

### ISSUE THREAD

**Issue by vedtam** [OpenDevin/OpenDevin#1754]
**Summary**
I'm a full stack developer while my language of choice is JavaScript (+TypeScript). It would be great to have OpenDevin as an assistant while working on apps that are meant to be run in the browser or node.

**Motivation**
Right now, CodeAct seems to be configured for Python - prompts, examples and tooling, but it could equally be useful for building front-end apps especially having access to the built in browser which could be a perfect fit for this scenario.

**Technical Design**
Both the browser and node could be a great choice for an interactive interpreter when executing JavaScript specific code in order to steer the model towards the desired solution.

I could eventually start looking into this, in case there's no one else already working on it.

**Comment by imkebe** [comment]
I think this is dictated by fact that most action LLM's are trained with python excellence. Most known OpenAI GPT uses python as a language of choice to execute analysis etc. Python has jupiter support, it's all in one interactive sandbox. Running node has many difficulties. Also python is type safe... and JS !? Sorry but it's a mess. TS might be a better choice.

**Comment by vedtam** [comment]
Sorry for the poor wording. I've been actually having Typescript in mind whenever referring to JavaScript. I prefer to keep a distinction between JavaScript as a programming language and Typescript - a strictly syntactical superset, that compiles to actual JavaScript.

**Comment by rbren** [comment]
Deduping this with https://github.com/OpenDevin/OpenDevin/issues/424
