### ISSUE TITLE
[Bug]: integration tests from `regenerate.sh` stall on request for input from CodeAct

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#1762]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Currently when we regenerate tests using
```bash
bash ./tests/integration/regenerate.sh
```

The regeneration script stalls, asking for user input.

This can be solved by just pressing "enter" a couple times, but it is annoying because the script takes a long time to execute, and you need to pay attention to it and press "enter" at the right places. It'd be good if we didn't have to do that.

@li-boxuan if you could take a look that'd be great, but anyone is welcome to look.

### Current Version

```bash
commit f28acea76fbbe66ceae94d715c59a2bc016c5587 (HEAD -> rb/message-for-task, origin/rb/message-for-task)
Author: Graham Neubig <neubig@gmail.com>
Date:   Mon May 13 13:48:09 2024 -0400

    Updated tests
```

### Installation and Configuration

```bash
standard
```

**Comment by li-boxuan** [comment]
I could take a look tonight. It was working - but maybe broken by recent commits on main.

**Comment by li-boxuan** [comment]
Oh yeah I thought this was already solved. Let me double check it tonight

**Comment by li-boxuan** [comment]
I just pulled latest main, deleted all artifacts for CodeAct tests and regenerated. Everything works fine! Looks like this is already solved, likely by @rbren 's changes.
