### ISSUE TITLE
[Refactor]: Re-enable PlannerAgent tests

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#1763]
This commit disabled PlannerAgent integration tests because they were failing for unknown reasons...
https://github.com/OpenDevin/OpenDevin/pull/1688/commits/d2b0b779f3d5f8a3977a1e4ec49f6e378d76ee57

We should figure out the reason and re-enable them.

**Comment by rbren** [comment]
Done in the PR above!
