### ISSUE TITLE
How can I eddit /etc/resolv.conf

### ISSUE THREAD

**Issue by hjalnko** [OpenDevin/OpenDevin#1766]
## How can eddit "/etc/resolv.conf"
 with our nameserver during the docker build, as the 
terminal is read-only so we can not use 
sudo vim /etc/resolv.conf

or How can I use our --dns= when using docker run command

**Comment by hjalnko** [comment]
when we try to install packages sudo we get a connection error as we will need to add this file /etc/resolv.conf

**Comment by rbren** [comment]
@hjalnko you might want to consider building your own sandbox image. You should probably base it off our sandbox image for now. You can set the image with `SANDBOX_CONTAINER_IMAGE=ghcr.io/yourorg/sandbox`
