### ISSUE TITLE
LM Studio Integration via OpenAI API V1 using base URL

### ISSUE THREAD

**Issue by ClaudiuHNS** [OpenDevin/OpenDevin#177]
Using opensource local LLM's available in LM Studio.

Using URL from LM Studio in OpenDevin for OpenAI-like integration:
`OPENAI_API_BASE_URL = "http://localhost:1234/v1" # LM Studio local API endpoint`

This solution proposed on crewAI may help: https://github.com/joaomdmoura/crewAI/issues/154#issuecomment-1919150315

**Comment by rbren** [comment]
See this issue for the solution: https://github.com/OpenDevin/OpenDevin/issues/111
