### ISSUE TITLE
[Bug]: Can't install nodejs

### ISSUE THREAD

**Issue by xplorer990** [OpenDevin/OpenDevin#1774]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

despite node and npm being installed opendevin says npm is not installed and when it tries to install it nothing happens

### Current Version

```bash
opendevin:0.5 WSL2 Ubuntu 22.04
```

### Installation and Configuration

```bash
enli@LY5:~/4/OpenDevin$ export WORKSPACE_BASE=$(pwd)/workspace;
enli@LY5:~/4/OpenDevin$ docker run \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal=host-gateway \
    ghcr.io/opendevin/opendevin:0.5
```

### Model and Agent

Model: gpt-4-turbo-2024-04-09
Agent: CodeActAgent

### Logs, Errors, Screenshots, and Additional Context

![image](https://github.com/OpenDevin/OpenDevin/assets/76548373/19229546-10d7-44cc-b93b-0269527c23b6)
![image](https://github.com/OpenDevin/OpenDevin/assets/76548373/3bb3af1d-ed03-4067-a6e9-bd998f8715d4)
![image](https://github.com/OpenDevin/OpenDevin/assets/76548373/988a1646-ecc5-48bf-a1b6-310c4a7a856f)

**Comment by xplorer990** [comment]
![image](https://github.com/OpenDevin/OpenDevin/assets/76548373/c3c3d283-aa9b-48bf-a6aa-fe27d30453e4)
With the latest version and agent: codeagent and gtp-4o model i get this.

**Comment by rbren** [comment]
See https://github.com/OpenDevin/OpenDevin/issues/1476 for the malformed paths issue (though that filename should be fine?)

**Comment by SmartManoj** [comment]
Node and npm need to be installed in the sandbox too. What is the task?

In step 1, it is being installed.

**Comment by Genuifx** [comment]
@SmartManoj Currently i am running OpenDevin from source, after `make build`,  my sandbox install but can not find nodejs.

[ghcr.io/opendevin/sandbox:main](app://dd/dashboard/images/local/sha256:0298538cc3ca06839afbd31c215f6071a70b9ab2d831aeeb9971730137ab5014?tag=main&name=ghcr.io%2Fopendevin%2Fsandbox)

**Comment by SmartManoj** [comment]
nodejs is not installed by default in the sandbox.

**Comment by Genuifx** [comment]
@SmartManoj Yes, I use Conda to install the deps. It looks like the sandbox is pulled from the remote server not built by local.

**Comment by SmartManoj** [comment]
> Step 1 completed?

in the task flow

**Comment by SmartManoj** [comment]
> Node and npm need to be installed in the sandbox too.

@Genuifx

**Comment by mamoodi** [comment]
@xplorer990 does the original issue still happen with the newer builds?

**Comment by mamoodi** [comment]
Going to close this. It seems that there may be a misunderstanding. Even though you have them installed on your current system, they still need to be installed in your sandbox too. For installing them in your sandbox, try the latest 0.6.2 tag and open a new issue or re-open with more details please.

**Comment by tobitege** [comment]
Correction: "main", not "0.6.2"
