### ISSUE TITLE
On Windows can't get the first response

### ISSUE THREAD

**Issue by borick** [OpenDevin/OpenDevin#178]
**Describe the bug**
doesn't work to respond on windows after initializing
**Steps to Reproduce**
1. run the backend
2. run the frontend
3. send a message

**Expected behavior**
- it works
**Actual behavior**
- errors out with:
PS C:\Users\boris\thirdparty\OpenDevin> uvicorn opendevin.server.listen:app --port 3000
INFO:     Started server process [45628]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 49661) - "WebSocket /ws" [accepted]
INFO:     connection open
STEP 0
ACTION CmdRunAction(command='ls', background=False)
---
OBSERVATION CONTRIBUTING.md
LICENSE
OpenDevinLogo.jpg
README.md
agenthub
dev_config
evaluation
frontend
opendevin
requirements.txt
workspace

CONTRIBUTING.md
LICENSE
OpenDevinLogo.jpg
README.md
agenthub
dev_config
evaluation
frontend
opendevin
requirements.txt
workspace

==============
STEP 1
ACTION AgentThinkAction(thought='Before starting to build the roguelike, I should check if the README.md file contains any relevant information about the existing project structure or any specific instructions.', runnable=False)
---
ACTION NOT EXECUTABLE
OBSERVATION

==============
STEP 2
ACTION FileReadAction(path='README.md', base_path='')
FileReadAction(path='README.md', base_path='.')
---```
Error in loop 'charmap' codec can't decode byte 0x90 in position 1928: character maps to <undefined>
**Additional context**

**Comment by rbren** [comment]
Hi @borick--looks like we've got a unicode issue. I'll take a look

**Comment by rbren** [comment]
Can you try running from branch `rb/utf8`?

**Comment by borick** [comment]
> Can you try running from branch `rb/utf8`?

INFO:     Started server process [39688]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 49843) - "WebSocket /ws" [accepted]
INFO:     connection open


==============
STEP 0

        ACTION:
        CmdRunAction(command='ls', background=False)

        OBSERVATION:
        CONTRIBUTING.md
        LICENSE
        OpenDevinLogo.jpg
        README.md
        agenthub
        dev_config
        evaluation
        frontend
        opendevin
        requirements.txt
        workspace



==============
STEP 1

        ACTION:
        AgentThinkAction(thought='To start building a 2D roguelike game in Python, I first need to check if Python is installed and confirm its version. This will help me determine if I can proceed with development or if I need to install or upgrade Python.', runnable=False)

        OBSERVATION:



==============
STEP 2
Error in loop Unknown observation type:
Exited before finishing

![image](https://github.com/OpenDevin/OpenDevin/assets/10510235/3fbb08d8-4e9f-494d-b4e1-2740c31c9be5)

**Comment by rbren** [comment]
OK great! I _just_ merged a fix for that second issue, will merge the utf8 fix now

**Comment by borick** [comment]
great it got a bit further now !!! raising another one momentarily, thank you!!!
