### ISSUE TITLE
[Feature]: Display a loading indicator in the chat interface when waiting for a response from OpenDevin

### ISSUE THREAD

**Issue by amanape** [OpenDevin/OpenDevin#1787]
**What problem or use case are you trying to solve?**
There is no indication that a response is being generated in the chat UI. The only indication is the agent status at the footer.

**Describe the UX of the solution you'd like**
Something like an animated 3 dots in the style of the existing chat bubble.

**Do you have thoughts on the technical implementation?**
Display 3 dots in the existing message component when agent is generating a response.

**Describe alternatives you've considered**
A banner embedded in the chat ui itself, not as a chat message.

**Additional context**
There are downsides to artificial streaming, and removing it can improve other small aspects (more about this discussion in #1488)
 
#1761 introduced an auto-scroll feature that can only be easily achieved by removing the effect (it is difficult to make it scroll as the height of the message changes).

I saw it as a good opportunity to take the step to move after confirmation from @neubig (in #1761) and @yimothysu (in #1488)

**Comment by natalyjazzviolin** [comment]
There's a mention of the three dot animation design in Figma in this comment here:
https://github.com/OpenDevin/OpenDevin/pull/1488#discussion_r1589580932

Would it be possible to share a screengrab of that animation?

**Comment by Shimada666** [comment]
Does it look like this? After receiving the data, the three dots will be replaced with real information.
![e83726b34e281e94aef4dccdd1b0dd10](https://github.com/OpenDevin/OpenDevin/assets/33391300/81590e45-db81-4c83-8bec-e6043bb0e885)

 Alternatively, a simpler way is to replace the send key with three dots.

**Comment by amanape** [comment]
@natalyjazzviolin I do not have any reference video or design that I can find to show you unfortunately. But something basic as what @Shimada666 sent would be more than enough for now.

**Comment by auleki** [comment]
This sounds like a fun way to start contributing on OpenDevin, can I take up this issue @amanape?

**Comment by mamoodi** [comment]
@auleki were you still interesting in looking at this issue?
