### ISSUE TITLE
Add tests for ServerRuntime and Backend Server

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#1797]
Add more testing for [runtime](https://github.com/OpenDevin/OpenDevin/tree/main/opendevin/runtime) and [server](https://github.com/OpenDevin/OpenDevin/tree/main/opendevin/server) to improve the code converage.

**Comment by mamoodi** [comment]
@xingyaoww More code coverage is always great. However, this is a little too vague so I will be closing this issue. Feel free to reopen if you feel strongly about it and add some more specific instructions to make it actionable.
