### ISSUE TITLE
Support fully autonomous mode for agent

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#1798]
**What problem or use case are you trying to solve?**

Discussion starts here: https://github.com/OpenDevin/OpenDevin/pull/1755#discussion_r1599346211

> This isn't for testing purpose - I believe it's for SWE-Bench evaluation, see [here](https://github.com/OpenDevin/OpenDevin/pull/1468/files#diff-cf5322e360ed33c3dc16023bfd443e6a7edab81c2f4a9e0dfd2f681a2fd59165R32-R37).
Looking at that giant PR, it looks like we could make this prompt as a built-in one?
> 'Please continue working on the task on whatever approach you think is suitable.\n'
        'If you think you have modified the code in a way that fixes the issue, please run the following command: <execute_bash> exit </execute_bash>.\n'
        'IMPORTANT: YOU SHOULD NEVER ASK FOR HUMAN HELP OR USE THE INTERNET TO SOLVE THIS TASK.\n'

> The agent could have a `full-autonomous` mode so that it doesn't ask for user inputs, and instead, it uses the above prompt. @xingyaoww what do you think? I could help on that if you need a hand.

_Originally posted by @li-boxuan in https://github.com/OpenDevin/OpenDevin/pull/1755#discussion_r1599346211_
            
**Describe the UX of the solution you'd like**

Maybe add a checkbox in the front-end that allows the (frontend? backend?) system to automatically provide the prompt ("Please continue working on the task on whatever approach you think is suitable...") whenever the model asks for human inputs.

The user may want it to run autonomously for a while, then uncheck the box; they expect the model will go back to the mode that requests human input.

When autonomous mode finishes, it may or may not solve the user's task (but will emit the `AgentFinish` action). We need to consider how to handle this - should we allow users to follow up given the same context?

cc @li-boxuan 
**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by gabrielblins** [comment]
There's any update about this feature? @SmartManoj

**Comment by SmartManoj** [comment]
Could you test that PR #2435?

**Comment by gabrielblins** [comment]
> Could you test that PR #2435?

I'll try! @SmartManoj thank you for your reply
