### ISSUE TITLE
[Bug]: Installed packages need to be reinstalled after each run

### ISSUE THREAD

**Issue by steventangbc** [OpenDevin/OpenDevin#1811]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Whether resuming an existing session or starting a new one, there is no memory cache of previously installed packages. They need to be reinstalled every time. 

### Current Version

```bash
Docker Desktop 4.30.0 (149282)
```

### Installation and Configuration

```bash
"install pandas, numpy, matplotlib, and seaborn"
```

### Model and Agent

Model: gpt-4o
Agent: CodeActAgent

### Reproduction Steps

1. Prompt LLM to install Python libraries
2. Import libraries to use
3. Refresh page
4. Choose either option - resume session or start new session
5. Try importing libraries again

**Comment by jiangleo** [comment]
I attempted to reproduce the issue but could not. Both resuming a session and starting a new session did not require reinstallation of the packages.

Environment Details:

Docker Desktop version: 4.28.0
OpenDevin version: main

new session:
<img width="894" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/15134896/55e5af31-510c-4815-8d97-a48b7e2cb056">

resume session:
<img width="854" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/15134896/a4954803-7835-4fce-975b-9eee530fcdef">

**Comment by mamoodi** [comment]
@steventangbc tested this on MacOS with the latest OpenDevin (0.6) and seems to be fine. Can you retry and reopen this issue if you run into it again please?
