### ISSUE TITLE
Differences Between CodeAct and OpenDevin

### ISSUE THREAD

**Issue by ramsey-coding** [OpenDevin/OpenDevin#1813]
I've come across the CodeAct repository [here](https://github.com/xingyaoww/code-act), and I'm curious about how it compares to OpenDevin. 

Can someone explain the main differences between these two projects? Specifically, I'm interested in understanding their key features, use cases, and any unique aspects that set them apart.

Thank you!

**Comment by PierrunoYT** [comment]
CodeAct is the Agent inside OpenDevin.

**Comment by ramsey-coding** [comment]
Inside https://github.com/OpenDevin/OpenDevin/tree/main/agenthub, I see many different agents. 

I am confused. What's the purpose of having so many different agents? 

Is OpenDevin the same as CodeAct?

**Comment by rbren** [comment]
CodeAct is currently our default agent. It was created by Xingyao, who is a core contributor here.

Our goal is to provide a platform where different people can contribute different agents. Agent technology is evolving rapidly, so we expect a lot of experimentation here over the next 6-12 months. Our goal is to provide a good default experience for users, but allow academics and engineers to experiment with new agents and architectures.
