### ISSUE TITLE
Design Document for OpenDevin

### ISSUE THREAD

**Issue by ramsey-coding** [OpenDevin/OpenDevin#1815]
I am interested in contributing to OpenDevin and want to understand the project better, particularly how to debug and navigate its systems.

Do you have a design document or any detailed documentation explaining how this agent system works? Specifically, I would like to know more about:

- How the agent plans and executes commands
 The architecture and flow of the system
- Any debugging tips or best practices

Your guidance would be greatly appreciated.

**Comment by mzydmer** [comment]
Maybe the docs files in project can help you
![image](https://github.com/OpenDevin/OpenDevin/assets/55788719/869e7c70-250f-4b3a-9d87-a399cd26ef74)

**Comment by rbren** [comment]
We have a rough architecture diagram here, but it probably needs updating: https://opendevin.github.io/OpenDevin/modules/usage/architecture

**Comment by mamoodi** [comment]
@ramsey-coding does this newly added overview answer your question?
https://github.com/OpenDevin/OpenDevin/blob/main/opendevin/README.md
