### ISSUE TITLE
During startup, enable text field, but disable submit

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#182]
**Describe the bug**
While waiting for OpenDevin to start, I want to start typing my prompt, so it's ready when OpenDevin is.

**Steps to Reproduce**
1. Start the app
2. Try to type your prompt while it initializes
3.

**Expected behavior**
Can type, but can't hit enter or click submit button

**Actual behavior**
Can't type

**Additional context**

**Comment by 0xSaurabhx** [comment]
Solution:
Modify ChatInterface.tsx:

`<div className="input-container">
  <button className="attach-button" type="button" aria-label="file">
    {/* ... */}
  </button>
  <input
    type="text"
    value={inputMessage}
    onChange={(e) => setInputMessage(e.target.value)}
    placeholder="Send a message (won't interrupt the Assistant)"
    onKeyDown={(e) => {
      if (e.key === "Enter") {
        handleSendMessage();
      }
    }}
  />
  <button type="button" onClick={handleSendMessage} disabled={!initialized}>
    <span className="button-text">Send</span>
  </button>
</div>`

**Comment by Sommer2me** [comment]
In JavaScript, you can disable a button by modifying its disabled property. You can set its disabled property to true to disable it, or false to enable it.
On the submit button, you can apply the attribute Ms-code-submit-form, leaving the value blank.
In Power Apps, you can create a new Enable/Require/Mask Field condition, set DO to Disable Submit, and configure your condition rules.
In GitHub, you can remove the disabled attribute from the text box and add it to the button.
In Power Apps, you can replace the 'gallery' and 'text input' references to point to the name of the controls on your side.

**Comment by yufansong** [comment]
Do you mean type here when agent initialization? It seems I can type it while initializing which already same with `Expected behavior`
 

<img width="709" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/33971064/f332e01d-dafe-47f6-ad0d-8621316093c5">

**Comment by rbren** [comment]
huh maybe this got fixed? I'll close
