### ISSUE TITLE
hi guys I don't know much about docker. Where does the SANDBOX USER ID come from?

### ISSUE THREAD

**Issue by ruanjianlun** [OpenDevin/OpenDevin#1822]
docker run \
    -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u)

**Comment by iFurySt** [comment]
> -e SANDBOX_USER_ID=$(id -u)

`id -u` the id  from you host user id.

**Comment by isweir** [comment]
> > -e SANDBOX_USER_ID=$(id -u)
> 
> `id -u` the id from you host user id.



> > -e SANDBOX_USER_ID=$(id -u)
> 
> `id -u` the id from you host user id.



> > -e SANDBOX_USER_ID=$(id -u)
> 
> `id -u` the id from you host user id.

the whole commend doesn't make any sense for me neither, i'm new to docker too, never use it before.

**Comment by tholum** [comment]
SANDBOX_USER_ID is the user ID of the user that owns your workspace folder ( generally your user ), seeing in your sandbox is running in a docker image, if your ID didn't match then the files it created wouldn't be owned by you and the files you put in wouldn't be owned by it

**Comment by rbren** [comment]
tholum has the correct answer here--it's to make sure file permissions stay nice.
