### ISSUE TITLE
Lingering browser processes

### ISSUE THREAD

**Issue by mzydmer** [OpenDevin/OpenDevin#1823]
## Describe your question

I run the main，options is --port 3000 --workers 1

when I opened a web server ，python process adding two ...
![image](https://github.com/OpenDevin/OpenDevin/assets/55788719/6433728f-bff7-410b-9a9b-241d41862374)

when I closed the web server, web socked was closed. But Two additional process were exists!

## Additional context
Each time a websocket connection is established, fastApi should add a thread to maintain the connection.

**I want to know why the new python process were created and how to optimize this**

**Comment by SmartManoj** [comment]
Could you share the arguments of the processes too?

**Comment by iFurySt** [comment]
![image](https://github.com/OpenDevin/OpenDevin/assets/16201837/ef205f7d-1c4e-4e43-ab58-9d823b90523c)

i think three processes are normal :)

if you find any situation will cause the process number increase, please let us know.

**Comment by mzydmer** [comment]
> ![image](https://private-user-images.githubusercontent.com/16201837/331478340-ef205f7d-1c4e-4e43-ab58-9d823b90523c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzQzMzgsIm5iZiI6MTcxNTkzNDAzOCwicGF0aCI6Ii8xNjIwMTgzNy8zMzE0NzgzNDAtZWYyMDVmN2QtMWM0ZS00ZTQzLWFiNTgtOWQ4MjNiOTA1MjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA4MjAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YmU1MjFlMDA4NTU3ZGNlNjZjMzEwNjc3NjJlNGE5Njk2NmZjN2UwYmIxYmZiYTQzYjkxOGQ5NTQ3ZTFkOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JAZwPa61lRL4IA_ArE0BJ_y37colgV-NJgkf3pfSsyM)
> 
> i think three processes are normal :)
> 
> if you find any situation will cause the process number increase, please let us know.



> Could you share the arguments of the processes too?

It will

> ![image](https://private-user-images.githubusercontent.com/16201837/331478340-ef205f7d-1c4e-4e43-ab58-9d823b90523c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MzQzMzgsIm5iZiI6MTcxNTkzNDAzOCwicGF0aCI6Ii8xNjIwMTgzNy8zMzE0NzgzNDAtZWYyMDVmN2QtMWM0ZS00ZTQzLWFiNTgtOWQ4MjNiOTA1MjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA4MjAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YmU1MjFlMDA4NTU3ZGNlNjZjMzEwNjc3NjJlNGE5Njk2NmZjN2UwYmIxYmZiYTQzYjkxOGQ5NTQ3ZTFkOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JAZwPa61lRL4IA_ArE0BJ_y37colgV-NJgkf3pfSsyM)
> 
> i think three processes are normal :)
> 
> if you find any situation will cause the process number increase, please let us know.

It will increase if I open more browsers.

**Comment by rbren** [comment]
Yes--each browser spawns its own process. Sounds like maybe we're not cleaning them up?

**Comment by mamoodi** [comment]
@mzydmer is this still an issue?
