### ISSUE TITLE
[Bug]: Planner is not visible and browser is disabled

### ISSUE THREAD

**Issue by somuamit** [OpenDevin/OpenDevin#1824]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I have run the following command to run the opendevin, which was given in github opendevin, but the Planner is not visible and if ask to create any user interface it is not opened on opendevin browser and also it is also disabled
![opendevin-issue](https://github.com/OpenDevin/OpenDevin/assets/12642147/9e78af3e-150a-4b1c-9f7d-dc20e7faac13)

#The directory you want OpenDevin to modify. MUST be an absolute path!
export WORKSPACE_BASE=$(pwd)/workspace;

docker run \
    -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    ghcr.io/opendevin/opendevin:0.5

### Current Version

```bash
ghcr.io/opendevin/opendevin:0.5
```

### Installation and Configuration

```bash
#The directory you want OpenDevin to modify. MUST be an absolute path!
export WORKSPACE_BASE=$(pwd)/workspace;

docker run \
    -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    ghcr.io/opendevin/opendevin:0.5
```

### Model and Agent

Model: groq/llama3-8b-8192

### Reproduction Steps

1. Take Ubuntu box in EC2
2. Install docker on EC2
3. Execute the following command which is given in opendevin github:
#The directory you want OpenDevin to modify. MUST be an absolute path!
export WORKSPACE_BASE=$(pwd)/workspace;

docker run \
    -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    ghcr.io/opendevin/opendevin:0.5

### Logs, Errors, Screenshots, and Additional Context

![opendevin-issue](https://github.com/OpenDevin/OpenDevin/assets/12642147/faeb6e5a-5c93-49cd-8bad-fd99980ab463)

**Comment by PierrunoYT** [comment]
Instead of using 0.5 use the main tag

**Comment by somuamit** [comment]
Many thanks for the prompt reply, PierrunoYT. 
Have executed the following docker command:
docker run  -it  --pull=always  -e SANDBOX_USER_ID=$(id -u)  -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE  -v $WORKSPACE_BASE:/opt/workspace_base  -v /var/run/docker.sock:/var/run/docker.sock  -p 3000:3000  --add-host host.docker.internal:host-gateway  ghcr.io/opendevin/opendevin:main

But problem remain the same. Still I am not able to see the Planner tab and also when tried to click workspace_base , it is giving error. Any suggestion will be appreciated

![opendevin-issue-1](https://github.com/OpenDevin/OpenDevin/assets/12642147/7ae7feee-ce32-4f51-87b6-1dead8b03e8b)
![opendevin-issue-2](https://github.com/OpenDevin/OpenDevin/assets/12642147/2b616ab9-e6e6-46a9-a729-698d9273a5fa)

**Comment by PierrunoYT** [comment]
> Many thanks for the prompt reply, PierrunoYT. Have executed the following docker command: docker run -it --pull=always -e SANDBOX_USER_ID=$(id -u) -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE -v $WORKSPACE_BASE:/opt/workspace_base -v /var/run/docker.sock:/var/run/docker.sock -p 3000:3000 --add-host host.docker.internal:host-gateway ghcr.io/opendevin/opendevin:main
> 
> But problem remain the same. Still I am not able to see the Planner tab and also when tried to click workspace_base , it is giving error. Any suggestion will be appreciated
> 
> ![opendevin-issue-1](https://private-user-images.githubusercontent.com/12642147/331167710-7ae7feee-ce32-4f51-87b6-1dead8b03e8b.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTU5NjgsIm5iZiI6MTcxNTg1NTY2OCwicGF0aCI6Ii8xMjY0MjE0Ny8zMzExNjc3MTAtN2FlN2ZlZWUtY2UzMi00ZjUxLTg3YjYtMWRlYWQ4YjAzZThiLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEwMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Y2Q2MTYwMWYxOTg1Y2ViNDAzZjg4NzZlODQzZjZiMjlkYjE4NzA2ZjA1MjU4MzY2OWY3YzY1NTgzMmE4MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hZwbC2jG_sX_415iXJl7hTPerpWlwv8EGWtIyNVueZg) ![opendevin-issue-2](https://private-user-images.githubusercontent.com/12642147/331167738-2b616ab9-e6e6-46a9-a729-698d9273a5fa.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTU5NjgsIm5iZiI6MTcxNTg1NTY2OCwicGF0aCI6Ii8xMjY0MjE0Ny8zMzExNjc3MzgtMmI2MTZhYjktZTZlNi00NmE5LWE3MjktNjk4ZDkyNzNhNWZhLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEwMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMGZkMTYxNzAwNDEyNzU2M2I0NTgxNjVmNWEzMjM5Y2QzYzBjNjQ2M2M0MjkxMDNjY2I4NTViMmNkMTVkNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M1yuqX_0NnOcXZRb5qwgUe26SclFbQGZ6NTaQIPWvLQ)

Not sure why.

**Comment by Shimada666** [comment]
https://github.com/OpenDevin/OpenDevin/blob/0fdbe1ee9340f4c7cdec15885e05e1dfd2070ba4/frontend/src/components/Workspace.tsx#L23-L31

The Planner Tab will only be displayed when using the PlannerAgent.
@xingyaoww Is the current PlannerAgent available?

**Comment by SmartManoj** [comment]
#1173

**Comment by neubig** [comment]
I think the UI is probably OK, but PlannerAgent is not very carefully maintained so we may want to look into that.
