### ISSUE TITLE
Not able to find requirements.txt

### ISSUE THREAD

**Issue by somuamit** [OpenDevin/OpenDevin#1826]
I was trying to setup opendevin on Windows/Ubuntu, followed the below steps, I was stuck in step 8 as I was not able to locate requirements.txt file. If needs to be created, please suggest me step by step and also mention if the steps are different for Ubuntu and Windows box

1. git clone https://github.com/OpenDevin/OpenDevin.git
2. cd OpenDevin
3. conda create -n od python=3.10
4. conda activate od
5. docker ps
(optional) install docker if not already installed
6. docker pull ghcr.io/opendevin/sandbox
7. export OPENAI_API_KEY={your key}
8. python -m pip install -r requirements.txt 
9.uvicorn opendevin.server.listen:app --port 3000

**Comment by enyst** [comment]
It sounds like you may be trying an old setup process, or is there some other reason why you try this way?

There is a different setup process documented in the README, can you please take a look at that: https://github.com/OpenDevin/OpenDevin/blob/main/README.md
Please note python 3.11 is needed.

**Comment by SmartManoj** [comment]
You can install using `python -m pip install -e .`
pip will use the `pyproject.toml` file

**Comment by isweir** [comment]
i done the same thing by following tutorials from youtube, both windows and linux version of youtube tutorials and both of them don't work. the github clone is very different than when he done it, the current readme file doesn't make any sense for beginner. here is what i done to get pass this error.

conda create -n od python=3.10, this commend doesn't work on current opendevin repository, requires atleast python 3.11, although tried to reinstall python 3.13, both pip -v and python -v still show 3.10.14 on my end, so i tried  conda create -n od python=3.11 and conda activate od commend again before i use python -m pip install -e .

on docker pull ghcr.io/opendevin/sandbox, this one doesn't work, what I did is docker pull ghcr.io/opendevin/sandbox:v0.2, this will download 2 items, one of which is around 160mb, i tried docker pull ghcr.io/opendevin/opendevin:0.5 too, however this commend downloaded bunch of docker images one of them is around 3gb, i didn't bother to, it's too large, i didn't know which one is correct, or both of them is wrong? can anyone tell me?

once I gone through the pyproject.toml, i try to follow the makefile, however when i try to use bash, i got the following error:

bash
<3>WSL (2719) ERROR: CreateProcessEntryCommon:505: execvpe /bin/bash failed 2
<3>WSL (2719) ERROR: CreateProcessEntryCommon:508: Create process not expected to return

I used this wsl -l and i get this

Windows Subsystem for Linux Distributions:
docker-desktop (Default)
docker-desktop-data

i try to use make commend and it gave me this:

make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ make
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    
finally, I have also seen the opendevin folder, there is a readMe.md file, this is what i get:

docker build -f opendevin/sandbox/docker/Dockerfile -t opendevin/sandbox:v0.1 .
[+] Building 0.0s (0/0)  docker:default
2024/05/16 18:34:12 http2: server: error reading preface from client //./pipe/docker_engine: file has already been close[+] Building 0.0s (0/0)                                                                                  docker:default
ERROR: resolve : CreateFile opendevin\sandbox: The system cannot find the file specified.

View build details: docker-desktop://dashboard/build/default/default/ml8tdbxxq3mmzf7twxspqhbqg

python3 opendevin/sandbox/docker/sandbox.py -d workspace
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

current python version i have is Python 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

pip -V

pip 24.0 from C:\Users\Wei Lin\.virtualenvs\OpenDevin-ueIkocbd\Lib\site-packages\pip (python 3.11)

**Comment by isweir** [comment]
i switch the python3 commend to python and i get this python opendevin/sandbox/docker/sandbox.py -d workspace
C:\Users\Wei Lin\miniconda3\envs\od\python.exe: can't open file 'C:\\Users\\Wei Lin\\DevinEngineer\\OpenDevin\\OpenDevin\\opendevin\\sandbox\\docker\\sandbox.py': [Errno 2] No such file or directory

**Comment by SmartManoj** [comment]
You can enter the WSL shell by using the 'wsl` command
https://github.com/OpenDevin/OpenDevin/blob/main/Development.md

**Comment by rbren** [comment]
This seems like a combination of not using WSL, and using old setup instructions.

I'm going to close this issue, but feel free to ask around in Discord or Slack (see the #troubleshooting channel) for more help w/ installation, or continue to chat on this ticket
