### ISSUE TITLE
[Bug]: /opendevin/plugins/jupyter/setup.sh: line 37: ss: command not found

### ISSUE THREAD

**Issue by unclemusclez** [OpenDevin/OpenDevin#1857]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

ss is part of iproute2
i believe ipoute2 is not available for docker images by default

ie, https://github.com/netdata/netdata/issues/9861
and, https://stackoverflow.com/questions/51834978/ip-command-is-missing-from-ubuntu-docker-image

ssh opendevin@localhost:
```
$ sudo apt install iproute2 -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package iproute2
```

### Current Version

```bash
0.5.3 Main
```

### Installation and Configuration

```bash
git clone
make run
```

### Logs, Errors, Screenshots, and Additional Context

```
22:37:48 - opendevin:INFO: mixin.py:47 - JupyterKernelGateway started with PID: 100
22:37:48 - opendevin:INFO: mixin.py:47 - /opendevin/plugins/jupyter/setup.sh: line 37: ss: command not found
22:37:48 - opendevin:INFO: mixin.py:47 - Execution server started with PID: 106
22:37:49 - opendevin:INFO: mixin.py:47 - Waiting for Jupyter kernel gateway to be available...
22:37:49 - opendevin:INFO: mixin.py:47 - Jupyter kernel ready.
```

**Comment by xingyaoww** [comment]
Can you check the `sandbox` image from main and try again? It should be resolved by https://github.com/OpenDevin/OpenDevin/pull/1859 now :)

You can set `sandbox_container_image = "ghcr.io/opendevin/sandbox:main"` into your `config.toml`.
