### ISSUE TITLE
How to run OpenDevin with AWS Bedrock?

### ISSUE THREAD

**Issue by ramsey-coding** [OpenDevin/OpenDevin#1866]
Can't figure out how can we OpenDevin with AWS Bedrock account?

**Comment by neubig** [comment]
Basically follow the instructions here and preface the model name with bedrock/ : https://litellm.vercel.app/docs/providers/bedrock
If that doesn’t work please tell us and we’ll help debug!

**Comment by rbren** [comment]
☝️ hopefully those instructions help. The #troubleshooting channel in slack is a good place to ask around too

**Comment by hasejuny** [comment]
@rbren 
I also don't know how to use OpenDevin with Claude Sonnet on my AWS Bedrock account.
Is there a document somewhere that describes the procedure as there is no mention of AWS in the installation guide?
https://docs.all-hands.dev/modules/usage/installation

**Comment by rbren** [comment]
Looks like we don't have bedrock docs, but you can check the litellm docs (same env vars should work) https://litellm.vercel.app/docs/providers/bedrock
