### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jinjunzh** [OpenDevin/OpenDevin#1868]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

This is the first launch after build the latest repo, but it looks  failed to run action. The terminal indicates that save command not find. why this happen?

[opendevin_2024-05-18.log](https://github.com/OpenDevin/OpenDevin/files/15359105/opendevin_2024-05-18.log)
![image](https://github.com/OpenDevin/OpenDevin/assets/19898583/273482ed-f4fb-4afa-82d5-49be4359f31d)

### Current Version

```bash
0.5.3
```

### Installation and Configuration

```bash
make build
make run
```

### Model and Agent

- Model: codellama:7b
- Agent: CodeReact

**Comment by SmartManoj** [comment]
save and close are not swe commands.
