### ISSUE TITLE
Every time I run Devin in a container one of the first actions it take is to install Nodejs is it possible to choose another setup configuration?

### ISSUE THREAD

**Issue by 4tal** [OpenDevin/OpenDevin#1875]
## Describe your question

Whenever I run Devin in a container, one of the first actions is installing Nodejs. Can I choose another setup configuration?

## Additional context

Like using different docker images.

**Comment by iFurySt** [comment]
what's your meaning? can you provide more context for your question?

**Comment by 4tal** [comment]
When I give Devin instructions to add tests for a local typescript project, it will install NodeJS.
I wanted to know if there's a way to use Devin without the need to install NodeJS but it will already have it pre-configured.

**Comment by rbren** [comment]
See https://github.com/OpenDevin/OpenDevin/issues/1387 and https://github.com/OpenDevin/OpenDevin/issues/424

Deduping this with the issues above
