### ISSUE TITLE
[Bug]: CodeAct repeatedly edits the wrong file

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#1890]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I'm asking CodeAct to repeatedly switch between editing two related files. Often File A is open, then CodeAct sends an `edit` command intended for File B. This usually happens when I issue a new instruction.

It'd be neat to show/emphasize the currently open file in CodeAct's prompt.

Side note: maybe we should just stop making `open` a thing, and put filenames directly into the commands? The agent has to look back over previous commands to determine current state, instead of just having a deterministic instruction it can write.

### Current Version

```bash
Main, as of `0ecba83e53c6f2abfb0fdbaf134842a0298234f6`
```

### Installation and Configuration

```bash
docker run
```

### Model and Agent

gpt-4-turbo, CodeAct

### Reproduction Steps

repeatedly prompt codeact to edit different files

### Logs, Errors, Screenshots, and Additional Context

<img width="448" alt="Screenshot 2024-05-18 at 3 40 18 PM" src="https://github.com/OpenDevin/OpenDevin/assets/7611973/5a2778c8-bf81-4a4a-a729-2c81cc95e318">

**Comment by li-boxuan** [comment]
> Side note: maybe we should just stop making open a thing, and put filenames directly into the commands?

I also had the same wonder when I saw SWE agent commands. Apparently LLM often forgets that it needs to open a file before edits it.

**Comment by edwardbrazier** [comment]
I vote for including the file name as the first parameter supplied by the AI to the edit command, as suggested above by rbren.

(This mix-up happened a bunch of times on the very first day that I used OpenDevin.)

**Comment by tobitege** [comment]
I'd take this up since I'm already on the agenskills with append_file and get to the edit_file changes for this PR afterwards.

cc @rbren @xingyaoww

**Comment by li-boxuan** [comment]
I encountered something funny with this symptom recently. The agent was trying to edit a javascript file but it forgot to open it. Since the last file it opened was an HTML file, the agent simply wrote javascript code to HTML file. When it browsed the webpage, it saw those javascript code printed out - and it thought that meant the code had been working!

**Comment by tobitege** [comment]
Proposal: right now `open_file` serves more as a `list_file` (like `cat`) and shouldn't be required prior to `edit_file`?

**Comment by li-boxuan** [comment]
> right now open_file serves more as a list_file (like cat) and shouldn't be required prior to edit_file?

+1

**Comment by xingyaoww** [comment]
@tobitege i've been thinking about the same thing too -- feel free to starts a PR and add "filepath" to the edit command!

**Comment by tobitege** [comment]
> @tobitege i've been thinking about the same thing too -- feel free to starts a PR and add "filepath" to the edit command!

Already done, waiting for review: https://github.com/OpenDevin/OpenDevin/pull/2346
