### ISSUE TITLE
[Bug]: If running a command that never returns, it gets stuck

### ISSUE THREAD

**Issue by tholum** [OpenDevin/OpenDevin#1895]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

If durring running a taak it ends up running something that never returns ( like npm run storybook, it freezes and never returns

### Current Version

```bash
ghcr.io/opendevin/opendevin:0.5
```

### Installation and Configuration

```bash
export WORKSPACE_BASE=$(pwd)/workspace
LLM_API_KEY=<REDACTED>

docker run \
    -it \
    --pull=always \
    -e LLM_API_KEY \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -e LLM_MODEL=gpt-4o-2024-05-13 \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 8002:3000 \
    --add-host host.docker.internal:host-gateway \
    ghcr.io/opendevin/opendevin:0.5

Running on ubuntu 22:04
```

### Model and Agent

Model : GPT-4o
Agent: CodeActAgent

### Reproduction Steps

1) Give it a task to write a React component and test it with storybook

The prompt I gave it
In the project emsp-frontend 

Split DevicePreview.tsx create a CoreDevicePreview that passes a QueueTicket into it, and then change DevicePreview to use CoreDevicePreview

Once that split is done, create a story in storybook for CoreDevicePreview

on a project that had storybook's installed

### Logs, Errors, Screenshots, and Additional Context

<img width="853" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/2395584/35d73b19-f023-4c7a-992b-bb079b73ef7b">
It has been stuck on this task for 4 hours

**Comment by SmartManoj** [comment]
Could you provide the log?

**Comment by tholum** [comment]
I will work on getting the log, I did write a prompt that I am 90% sure will reproduce it ( I am verifying now and it is looking like it hangs the same )

https://github.com/tholum/OpenDevinBugs/blob/main/01_hangs_on_storybook/PROMPT.md

**Comment by SmartManoj** [comment]
timeout works on that command too.

https://github.com/OpenDevin/OpenDevin/pull/2034#issuecomment-2131087130
