### ISSUE TITLE
Enable wiki and/or discussions, or create issue templates

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#19]
There's a lot of chatter in the Issues. Opening up discussions or the wiki might help cut down on it.

Alternatively, issue templates (ideas, feedback, bugs) would at least help triage. I'm happy to take a stab at this.

(And thanks for getting this rolling @huybery! Very excited for the project, looking forward to contributing some code. If there's any way I can help with logistics just let me know.)

**Comment by neubig** [comment]
Discussions are a good idea, I think they've been enabled. It would be good to add issue templates. Please feel free to send a PR with a suggestion!
