### ISSUE TITLE
Better in-line code styling for messages

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#1907]
**What problem or use case are you trying to solve?**
We're currently rendering `inline code` in a way that isn't super distinguishable from other text

**Describe the UX of the solution you'd like**
Something closer to what `github does`
<img width="415" alt="Screenshot 2024-05-19 at 6 55 09 PM" src="https://github.com/OpenDevin/OpenDevin/assets/7611973/3a85d21c-e117-47e6-a361-394bce891e5e">

**Do you have thoughts on the technical implementation?**
CSS

**Comment by amanape** [comment]
Resolved by #1909
