### ISSUE TITLE
Conceal API key when serializing config

### ISSUE THREAD

**Issue by li-boxuan** [OpenDevin/OpenDevin#1936]
We log LLM configs:

https://github.com/OpenDevin/OpenDevin/blob/7ca560471bd262f22513f3863995d0a8e6121c07/opendevin/core/main.py#L69-L71

which contains `api_key` that can be easily overlooked when transmitting/sharing logs.

Logs should never contain sensitive data, and we should conceal `api_key` when we serialize configs.

Example: https://github.com/OpenDevin/OpenDevin/pull/1891#issuecomment-2121971670 I uploaded my OpenDevin logs before I noticed it leaked my API key.

**Comment by li-boxuan** [comment]
Thanks @enyst for pushing a hot fix. Reopening this issue for a long-term fix.

**Comment by enyst** [comment]
We can always log from somewhere else without realizing it will include sensitive information, so the solution should be to mask it in the logger, and anything else we can think of.

**Comment by Shimada666** [comment]
Do we just need to rewrite the __str__ method of LLMConfig and replace it with `******` when the key is `api-key`?

**Comment by Shimada666** [comment]
I found a simpler and more universal method by adding a log filter for data desensitization.
@enyst @li-boxuan 
#1940
