### ISSUE TITLE
Incorporate BrowsingAgent's prompts to CodeAct to enable richer interactions with the browser.

### ISSUE THREAD

**Issue by frankxu2004** [OpenDevin/OpenDevin#1945]
**What problem or use case are you trying to solve?**
Add functionality to CodeAct agent

**Describe the UX of the solution you'd like**
Can browse internet.

**Do you have thoughts on the technical implementation?**
Re-use some prompts inside the BrowsingAgent, into the CodeAct agent's prompts. CodeAct now already supports <execute_browse> so it should be relatively straight forward.

**Describe alternatives you've considered**

**Additional context**

#1856

**Comment by li-boxuan** [comment]
I prefer we do it via delegation. CodeAct agent should be able to delegate the task to BrowsingAgent.

**Comment by frankxu2004** [comment]
Good point, then we may not worry about it for the current milestone
