### ISSUE TITLE
Document various config parameters in https://github.com/OpenDevin/OpenDevin/blob/1fe290adf9140de639c58475023dcd57bd5bae20/opendevin/core/schema/config.py#L31

### ISSUE THREAD

**Issue by josephykwang** [OpenDevin/OpenDevin#1957]
## Describe your question

There is no document on config parameters. 

## Additional context

Encountered exception like 
```
AgentFinishAction.__init__() got an unexpected keyword argument 'reason'
```

wondering if it is due to memory or bad response from llm. Want to change config parameters so see we can avoid exceptions.

**Comment by enyst** [comment]
Please take a look here: https://opendevin.github.io/OpenDevin/modules/python/opendevin/core/config
