### ISSUE TITLE
[Bug]: make states poetry is not installed

### ISSUE THREAD

**Issue by josephykwang** [OpenDevin/OpenDevin#1978]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

```
curl -sSL https://install.python-poetry.org | python3.11 - 
Retrieving Poetry metadata

The latest version (1.8.3) is already installed.
(venv) jwang@jwang-JMLWV6CL9W OpenDevin % make
Building project...
Checking dependencies...
Checking system...
macOS detected.
Checking Python installation...
Python 3.11.8 is already installed.
Checking npm installation...
npm 10.5.0 is already installed.
Checking Node.js installation...
Node.js 21.7.1 is already installed.
Checking Docker installation...
Docker version 26.0.0, build 2ae903e is already installed.
make[2]: poetry: Command not found
Checking Poetry installation...
Poetry is not installed. You can install poetry by running the following command, then adding Poetry to your PATH:
 curl -sSL https://install.python-poetry.org | python3.11 -
More detail here: https://python-poetry.org/docs/#installing-with-the-official-installer
make[2]: *** [check-poetry] Error 1
make[1]: *** [check-dependencies] Error 2
make: *** [build] Error 2
```

### Current Version

```bash
git branch
* (HEAD detached at 0.5.3)
  main
```

### Installation and Configuration

```bash
run
```

### Model and Agent

NA

### Reproduction Steps

1. run make

### Logs, Errors, Screenshots, and Additional Context

```(venv) jwang@jwang-JMLWV6CL9W OpenDevin % curl -sSL https://install.python-poetry.org | python3.11 - 
Retrieving Poetry metadata

The latest version (1.8.3) is already installed.
(venv) jwang@jwang-JMLWV6CL9W OpenDevin % make
Building project...
Checking dependencies...
Checking system...
macOS detected.
Checking Python installation...
Python 3.11.8 is already installed.
Checking npm installation...
npm 10.5.0 is already installed.
Checking Node.js installation...
Node.js 21.7.1 is already installed.
Checking Docker installation...
Docker version 26.0.0, build 2ae903e is already installed.
make[2]: poetry: Command not found
Checking Poetry installation...
Poetry is not installed. You can install poetry by running the following command, then adding Poetry to your PATH:
 curl -sSL https://install.python-poetry.org | python3.11 -
More detail here: https://python-poetry.org/docs/#installing-with-the-official-installer
make[2]: *** [check-poetry] Error 1
make[1]: *** [check-dependencies] Error 2```

**Comment by SmartManoj** [comment]
> You can install poetry by running the following command, then adding Poetry to your PATH:
>  curl -sSL https://install.python-poetry.org | python3.11 -

**Comment by josephykwang** [comment]
Did that . However when running make , it states it is not installed. See the logSent from my iPhoneOn May 22, 2024, at 9:20 PM, மனோஜ்குமார் பழனிச்சாமி ***@***.***> wrote:﻿

You can install poetry by running the following command, then adding Poetry to your PATH:
curl -sSL https://install.python-poetry.org | python3.11 -

**Comment by SmartManoj** [comment]
reopen the shell

**Comment by josephykwang** [comment]
What do you mean? Please see the log I copied to the bug issue Sent from my iPhoneOn May 22, 2024, at 10:10 PM, மனோஜ்குமார் பழனிச்சாமி ***@***.***> wrote:﻿
reopen the shell

**Comment by SmartManoj** [comment]
You can install Poetry by running the following command:

```bash
curl -sSL install.python-poetry.org | python3.11 -
```

After running the command, you'll need to reload your shell configuration to ensure that the changes take effect. You can do this by running:

```bash
source ~/.bashrc
```

Reopening the terminal achieves the same result.

If you still encounter issues, please share the log for further assistance.

With warmest regards,

மனோஜ்குமார் பழனிச்சாமி

**Comment by josephykwang** [comment]
open a new terminal and then run the following```
***@***.*** workspace % cd OpenDevin

***@***.*** OpenDevin % bash




The default interactive shell is now zsh.

To update your account to use zsh, please run `chsh -s /bin/zsh`.

For more details, please visit https://support.apple.com/kb/HT208050.

bash-3.2$ source venv/bin/activate

(venv) bash-3.2$  curl -sSL https://install.python-poetry.org | python3.11 -

Retrieving Poetry metadata




The latest version (1.8.3) is already installed.

(venv) bash-3.2$ make

Building project...

Checking dependencies...

Checking system...

macOS detected.

Checking Python installation...

Python 3.11.8 is already installed.

Checking npm installation...

npm 10.5.0 is already installed.

Checking Node.js installation...

Node.js 21.7.1 is already installed.

Checking Docker installation...

Docker version 26.0.0, build 2ae903e is already installed.

make[2]: poetry: Command not found

Checking Poetry installation...

Poetry is not installed. You can install poetry by running the following command, then adding Poetry to your PATH:

 curl -sSL https://install.python-poetry.org | python3.11 -

More detail here: https://python-poetry.org/docs/#installing-with-the-official-installer

make[2]: *** [check-poetry] Error 1

make[1]: *** [check-dependencies] Error 2

make: *** [build] Error 2
```
    On Thursday, May 23, 2024 at 06:36:15 AM PDT, மனோஜ்குமார் பழனிச்சாமி ***@***.***> wrote:  
 
 


You can install Poetry by running the following command:
curl -sSL install.python-poetry.org | python3.11 -
After running the command, you'll need to reload your shell configuration to ensure that the changes take effect. You can do this by running:
source ~/.bashrc
Reopening the terminal achieves the same result.

If you still encounter issues, please share the log for further assistance.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by SmartManoj** [comment]
without venv?

**Comment by josephykwang** [comment]
```
% bash




The default interactive shell is now zsh.

To update your account to use zsh, please run `chsh -s /bin/zsh`.

For more details, please visit https://support.apple.com/kb/HT208050.

bash-3.2$ make

Building project...

Checking dependencies...

Checking system...

macOS detected.

Checking Python installation...

Python 3.11.8 is already installed.

Checking npm installation...

npm 10.5.0 is already installed.

Checking Node.js installation...

Node.js 21.7.1 is already installed.

Checking Docker installation...

Docker version 26.0.0, build 2ae903e is already installed.

make[2]: poetry: Command not found

Checking Poetry installation...

Poetry is not installed. You can install poetry by running the following command, then adding Poetry to your PATH:

 curl -sSL https://install.python-poetry.org | python3.11 -

More detail here: https://python-poetry.org/docs/#installing-with-the-official-installer

make[2]: *** [check-poetry] Error 1

make[1]: *** [check-dependencies] Error 2

make: *** [build] Error 2

bash-3.2$ curl -sSL https://install.python-poetry.org | python3.11 -

Retrieving Poetry metadata



The latest version (1.8.3) is already installed.
```    On Thursday, May 23, 2024 at 09:16:05 AM PDT, மனோஜ்குமார் பழனிச்சாமி ***@***.***> wrote:  
 
 


without venv?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by SmartManoj** [comment]
Why are you running this command `source venv/bin/activate`?

**Comment by josephykwang** [comment]
To activate virtual environment . Note with or without virtual environment, it doesn’t work Sent from my iPhoneOn May 23, 2024, at 6:43 PM, மனோஜ்குமார் பழனிச்சாமி ***@***.***> wrote:﻿
Why are you running this command source venv/bin/activate?

**Comment by SmartManoj** [comment]
virtual environment is not needed as poetry will do that itself.
Could you just run `poetry` after it is installed?

**Comment by josephykwang** [comment]
```
***@***.*** OpenDevin % curl -sSL https://install.python-poetry.org | python3.11 -

Retrieving Poetry metadata




The latest version (1.8.3) is already installed.

***@***.*** OpenDevin % echo $SHELL

/bin/zsh

***@***.*** OpenDevin % poetry

zsh: command not found: poetry

***@***.*** OpenDevin % bash




The default interactive shell is now zsh.

To update your account to use zsh, please run `chsh -s /bin/zsh`.

For more details, please visit https://support.apple.com/kb/HT208050.

bash-3.2$ poetry
bash: poetry: command not found```
    On Thursday, May 23, 2024 at 07:52:28 PM PDT, மனோஜ்குமார் பழனிச்சாமி ***@***.***> wrote:  
 
 


virtual environment is not needed as poetry will do that itself.
Could you just run poetry after it is installed?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by SmartManoj** [comment]
https://stackoverflow.com/a/73656539/5033247

**Comment by mamoodi** [comment]
I'm going to close this one. Please try the newest version. If it still has issues, please open a new issue or re-open this with more info.
