### ISSUE TITLE
Does the browser work?

### ISSUE THREAD

**Issue by shaggy2626** [OpenDevin/OpenDevin#1988]
How do you use the browser? I'm unable to edit the url or get the agent to open a browser especially when it runs a flask app

![image](https://github.com/OpenDevin/OpenDevin/assets/120447538/35e95c29-ae8e-465a-b485-c4f1d8733c77)

**Comment by xingyaoww** [comment]
Which agent are you using? If you are using `CodeActAgent` (and `gpt-4o` as the LLM) from `main`, you can actually tell the agent to browse the URL of `OpenDevin` and it should work.

Unfortunately, the browser is currently edit-only for the agent (e.g., if humans edit it, it may confuse the agent) - but this may change as we improve the agents.

**Comment by rishi8011** [comment]
can we edit url so that we can guide agent to look for specific information from that url ??

**Comment by cwints** [comment]
When I ask the agent to browse for a URL it responds with "I don't have the capability to interact with a web browser directly". I am using the CodeActAgent and gpt-4o

**Comment by rishi8011** [comment]
same issue with me

**Comment by rishi8011** [comment]
@xingyaoww check this github project how it integrates browser in it maybe it help us to improve opendevin 

https://github.com/entropy-research/Devon

**Comment by waldy6** [comment]
Worked for me running from the latest build.

**Comment by assertion** [comment]
Not every agent has the ability to open browser, if it doesn't work, pls tell us what's the agent you're using.

**Comment by mamoodi** [comment]
As mentioned, not every agent has browser capability. However, if you choose CodeActAgent and type something like:
"Go to the OpenDevin github page and tell me how many stars the github repo currently has"
you can see the browser in action. Currently you cannot edit the browser url.
