### ISSUE TITLE
Constant "bash: line 1: execute_cli: command not found" Jupyter

### ISSUE THREAD

**Issue by shaggy2626** [OpenDevin/OpenDevin#1989]
Is this normal behavior for every jupyter cell to display  "bash: line 1: execute_cli: command not found"

![image](https://github.com/OpenDevin/OpenDevin/assets/120447538/f292ddac-d06c-4e02-9360-09348928004e)

**Comment by assertion** [comment]
@shaggy2626 which runtime you use? try SSHBox instead of ExecBox when running CodeActAgent?

**Comment by mamoodi** [comment]
Can you try this with the 0.6.2 tag of OpenDevin. Just tried reproducing and was not able to. Closing. Please re-open with more details as requested if you are still running into issues.
