### ISSUE TITLE
[Bug]: UI not loading due to in-memory session management

### ISSUE THREAD

**Issue by johnnyaug** [OpenDevin/OpenDevin#1997]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I'm wondering about the new session management, particularly the fact that it's persisted in-memory.
When I'm using multiple backend workers, the UI can't load the file explorer, because the request to `list-files` gets to a worker which is not familiar with my session. 

<img width="623" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/3149885/4020f3ca-21a3-48cc-808a-831527adc3eb">

If I repeat the `list-files` request, it works occasionally when it's lucky enough to go through the worker where the session is persisted.

### Current Version

```bash
0eccf316
```

### Installation and Configuration

```bash
LLM_MODEL="gpt-3.5-turbo-0125"
LLM_API_KEY="<redacted>"
WORKSPACE_BASE="/Users/yoni/OpenDevin/workspace"
WORKSPACE_MOUNT_PATH="/Users/yoni/OpenDevin/workspace"
SANDBOX_TYPE="ssh"
JWT_SECRET="<redacted>"
```

### Reproduction Steps

1. Start the server with 8 workers.
   ```
   uvicorn.run('listen:app', host='0.0.0.0', port=3000, workers=8)
   ```
3. Open the UI and wait for the engine to load.

**Comment by assertion** [comment]
I don't think we support running backend with several workers now, due to `_sessions` in `SessionManager` is stored in memory and this problem should not related to the new session management code. 

Just want to confirm the reason you run backend with multi-workers @johnnyaug ? Single worker may stuck in some situations?

**Comment by CmetankaJDD** [comment]
> I don't think we support running backend with several workers now, due to `_sessions` in `SessionManager` is stored in memory and this problem should not related to the new session management code.
> 
> Just want to confirm the reason you run backend with multi-workers @johnnyaug ? Single worker may stuck in some situations?
I don't have a workspace even in a single run https://github.com/OpenDevin/OpenDevin/issues/2000

**Comment by johnnyaug** [comment]
@assertion actually no good reason to do so. At some point in time the websocket got stuck when I used one worker, but this has been resolved since.

**Comment by CmetankaJDD** [comment]
I re-downloaded the files, and the error went away. I'm sorry.

**Comment by amanape** [comment]
Closing since its been resolved
