### ISSUE TITLE
[Bug]: Agent reinitializes when the API key changes

### ISSUE THREAD

**Issue by amanape** [OpenDevin/OpenDevin#2019]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Going to settings and changing nothing but the API key causes the agent to reinitialize

### Current Version

```bash
latest/main
```

### Installation and Configuration

```bash
make build && make run
```

### Model and Agent

Any model/agent

### Reproduction Steps

1. Wait for first time initializing after starting OpenDevin
2. Go to settings
3. Update API key input

**Comment by assertion** [comment]
Settings changing will trigger reinitializing of the whole session, I think this is a feature and designed to be so? @amanape

**Comment by amanape** [comment]
@assertion Yes, but I remember an older issue that has set it to only reinitialise when relevant, and did not do so when the API key changed.

Is it an expected behaviour to reinitialise when the key changes?

**Comment by rbren** [comment]
Generally I think it's safer to re-init whenever there's a settings change. Otherwise you end up with a mixed session which is hard for us to debug.

Do you think switching API keys mid-session is a common flow we should anticipate? Is that something users need to do for some reason?

**Comment by amanape** [comment]
Good point!

**Comment by tobitege** [comment]
> Generally I think it's safer to re-init whenever there's a settings change. Otherwise you end up with a mixed session which is hard for us to debug.
> 
> Do you think switching API keys mid-session is a common flow we should anticipate? Is that something users need to do for some reason?

IF it were possible to switch models in between, it could be very helpful (idk if it is currently, waiting for v1 before diving in) when I'd see a model mess up code and try to switch to a different model instead.
Sidenote: too often I see gpt-4o mentioned, which in my experience is not soo good with coding; I'd rather recommend to also consider trying the bench with Microsoft's WizardLM2 70B (64K context) model, which has been more helpful quite often.
