### ISSUE TITLE
[Bug]: Failed to initialize plugin jupyter with exit code 126 and output <opendevin.runtime.docker.ssh_box.SSHExecCancellableStream object at 0x7fce9b088500> in WSL

### ISSUE THREAD

**Issue by mannaandpoem** [OpenDevin/OpenDevin#2027]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Getting Started works fine, but when running the python script `poetry run python evaluation/swe_bench/swe_env_box.py` to evaluate the swe_bench, the following error occurs：

mixin.py:39 - Initializing plugin [jupyter] by executing [/opendevin/plugins/jupyter/setup.sh] in the sandbox.
ERROR:root:  File "/home/manna/OpenDevin/evaluation/swe_bench/swe_env_box.py", line 141, in <module>
    sandbox.init_plugins([JupyterRequirement(), SWEAgentCommandsRequirement()])
  File "/home/manna/OpenDevin/opendevin/runtime/plugins/mixin.py", line 50, in init_plugins
    raise RuntimeError(

ERROR:root:<class 'RuntimeError'>: Failed to initialize plugin jupyter with exit code 126 and output <opendevin.runtime.docker.ssh_box.SSHExecCancellableStream object at 0x7fce9b088500>

### Current Version

```bash
Python 3.12.1
Poetry (version 1.8.3)
WSL: Ubuntu 22.04.3 LTS
Docker version 26.0.0, build 2ae903e
ghcr.io/opendevin/eval-swe-bench:full-v1.1
ghcr.io/opendevin/opendevin:0.5
ghcr.io/opendevin/sandbox:main
```

### Installation and Configuration

```bash
[core]
max_iterations = 100
cache_dir = "/tmp/cache"
sandbox_container_image = "ghcr.io/opendevin/sandbox:latest"
sandbox_type = "ssh"
ssh_hostname = "localhost"
sandbox_timeout = 120

# SWEBench eval specific
use_host_network = false
run_as_devin = false
enable_auto_lint = true

# TODO: Change these to the model you want to evaluate
[eval_gpt4_1106_preview]
model = "gpt-4-1106-preview"
api_key = "XXX"
temperature = 0.0

[eval_some_openai_compatible_model]
model = "openai/MODEL_NAME"
base_url = "https://OPENAI_COMPATIBLE_URL/v1"
api_key = "XXX"
temperature = 0.0
```

### Model and Agent

None

### Reproduction Steps

1. Download all docker images.
2. Run `curl -sSL https://install.python-poetry.org | python3 -` to Install poetry tool.
3. Run `poetry install` to install dependencies.
4. Run `poetry run python evaluation/swe_bench/swe_env_box.py`

### Logs, Errors, Screenshots, and Additional Context

(base) manna@LAPTOP-QPIELSGC:~/OpenDevin$ poetry run python evaluation/swe_bench/swe_env_box.py
12:23:12 - opendevin:INFO: ssh_box.py:208 - SSHBox is running as root user with USER_ID=1000 in the sandbox
12:23:12 - opendevin:INFO: ssh_box.py:642 - Container stopped
12:23:12 - opendevin:WARNING: ssh_box.py:654 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
12:23:12 - opendevin:INFO: ssh_box.py:627 - Mounting workspace directory: None
12:23:12 - opendevin:INFO: ssh_box.py:663 - Mounting volumes: {'/tmp/cache': {'bind': '/root/.cache', 'mode': 'rw'}}
12:23:12 - opendevin:INFO: ssh_box.py:627 - Mounting workspace directory: None
12:23:12 - opendevin:INFO: ssh_box.py:674 - Container started
12:23:13 - opendevin:INFO: ssh_box.py:690 - waiting for container to start: 1, container status: running
12:23:13 - opendevin:INFO: ssh_box.py:377 - Connecting to root@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 60997 root@localhost` with the password 'f884f02d-9907-48ed-b8ea-a5f79dd3c556' and report the issue on GitHub. If you started OpenDevin with `docker run`, you should try `ssh -v -p 60997 root@localhost` with the password 'f884f02d-9907-48ed-b8ea-a5f79dd3c556 on the host machine (where you started the container).
12:23:16 - opendevin:INFO: swe_env_box.py:45 - Sourcing swe_entry.sh to set up environment variables
12:24:09 - opendevin:INFO: swe_env_box.py:48 - exit code: 0
12:24:09 - opendevin:INFO: swe_env_box.py:49 - CONDA_ENV_NAME: astropy__astropy__4.3
Warning: 'conda-forge' already in 'channels' list, moving to the bottom
2024-05-24 04:23:18,711 - testbed_context_manager - INFO - [Testbed] Using conda path /swe_util/miniforge3
2024-05-24 04:23:18,711 - testbed_context_manager - INFO - [Testbed] Using working directory /workspace for testbed
2024-05-24 04:23:18,712 - testbed_context_manager - INFO - [Testbed] Repo astropy/astropy: 1 versions
2024-05-24 04:23:18,712 - testbed_context_manager - INFO - [Testbed]    Version 4.3: 1 instances
2024-05-24 04:23:18,712 - testbed_context_manager - INFO - [Testbed] Using conda path /swe_util/miniforge3
2024-05-24 04:23:18,712 - testbed_context_manager - INFO - [Testbed] Using conda executable: /swe_util/miniforge3/bin/mamba
2024-05-24 04:23:18,992 - testbed_context_manager - INFO - [Testbed] Setting up testbed for astropy__astropy__4.3
2024-05-24 04:23:18,992 - testbed_context_manager - INFO - [Testbed] Repo for astropy__astropy version 4.3 exists: /workspace/astropy__astropy__4.3; skipping
2024-05-24 04:23:18,992 - testbed_context_manager - INFO - [Testbed-DEBUG]repo_path: /workspace/astropy__astropy__4.3
2024-05-24 04:23:18,992 - testbed_context_manager - INFO - [Testbed] Environment astropy__astropy__4.3 already exists; skipping
2024-05-24 04:23:19,420 - taskenv_context_manager - INFO - [astropy__astropy__4.3] [astropy__astropy-12907] Reset task environment to d16bfe05a744909de4b27f5875fe0d4ed41ce607
2024-05-24 04:23:19,421 - taskenv_context_manager - INFO - [astropy__astropy__4.3] [astropy__astropy-12907] Running pre-install setup command: . /
swe_util/miniforge3/etc/profile.d/conda.sh && conda activate astropy__astropy__4.3 && echo 'activate successful' && sed -i 's/"setuptools"/"setuptools<69.0.0"/' pyproject.toml
2024-05-24 04:23:19,471 - taskenv_context_manager - INFO - [astropy__astropy__4.3] [astropy__astropy-12907] Installing with command: . /swe_util/miniforge3/etc/profile.d/conda.sh && conda activate astropy__astropy__4.3 && echo 'activate successful' && pip install -e .[test]
2024-05-24 04:24:09,492 - taskenv_context_manager - INFO - [astropy__astropy__4.3] [astropy__astropy-12907] Installation successful
Repo Path: /workspace/astropy__astropy__4.3
Test Command: pytest --no-header -rA --tb=no -p no:cacheprovider astropy/modeling/tests/test_separable.py
12:24:09 - opendevin:INFO: swe_env_box.py:51 - Sourced swe_entry.sh successfully
12:24:09 - opendevin:INFO: swe_env_box.py:88 - SSH box started for instance astropy__astropy-12907.
12:24:10 - opendevin:INFO: mixin.py:31 - Copied files from [/home/manna/OpenDevin/opendevin/runtime/plugins/jupyter] to [/opendevin/plugins/jupyter] inside sandbox.
12:24:10 - opendevin:INFO: mixin.py:39 - Initializing plugin [jupyter] by executing [/opendevin/plugins/jupyter/setup.sh] in the sandbox.
ERROR:root:  File "/home/manna/OpenDevin/evaluation/swe_bench/swe_env_box.py", line 141, in <module>
    sandbox.init_plugins([JupyterRequirement(), SWEAgentCommandsRequirement()])
  File "/home/manna/OpenDevin/opendevin/runtime/plugins/mixin.py", line 50, in init_plugins
    raise RuntimeError(

ERROR:root:<class 'RuntimeError'>: Failed to initialize plugin jupyter with exit code 126 and output <opendevin.runtime.docker.ssh_box.SSHExecCancellableStream object at 0x7fce9b088500>

**Comment by xingyaoww** [comment]
> Run `poetry install` to install dependencies.

Can you try to use `make build` to install dependencies and see if it resolves the issue? More details about installation process can be found in https://github.com/OpenDevin/OpenDevin/blob/main/Development.md

**Comment by karcheng** [comment]
I git clone, followed https://github.com/OpenDevin/OpenDevin/blob/main/Development.md and performed  poetry run pytest ./tests/unit/test_sandbox.py.

FAILED tests/unit/test_sandbox.py::test_sandbox_jupyter_plugin - RuntimeError: Failed to initialize plugin jupyter with exit code 126 and output <opendevin.runtime.docker.ssh_box.S...

**Comment by mannaandpoem** [comment]
I followed this guild https://github.com/OpenDevin/OpenDevin/blob/main/Development.md and run `make build` successfully. However,  running `tests/unit/test_sandbox.py::test_sandbox_jupyter_plugin` and  `evaluation/swe_bench/swe_env_box.py` fails: Failed to initialize plugin jupyter with exit code 126 .

<img width="1218" alt="4420dd28b9bd0cd6cb9c9d8278fdd18" src="https://github.com/OpenDevin/OpenDevin/assets/52203545/673b8cd9-85b6-4f72-9f64-643a70211ee3">

<img width="1120" alt="7e1520c41fddae58b00c2c356f871af" src="https://github.com/OpenDevin/OpenDevin/assets/52203545/a5fc9663-13cd-4054-9501-7f5d8f7dbc25">

**Comment by karcheng** [comment]
Sorry my bad. Nothing wrong with development.md.  I've encountered various issues.  1. sandbox will not start when opendevin running in WSL but docker works in windows.  2. opendevin can't connect to local llm.  It been resolved.

**Comment by mannaandpoem** [comment]
> Failed to initialize plugin jupyter with exit code 126

How to solve this problem: Failed to initialize plugin jupyter with exit code 126

**Comment by karcheng** [comment]
sorry @mannaandpoem , just read you post again and noticed that you did start opendevin in WSL. Make you have 
.wslconfig file located at C:\Users\%username%\.wslconfig

```
[wsl2]
networkingMode=mirrored
localhostForwarding=true
```
see:
https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting/windows

**Comment by mannaandpoem** [comment]
> sorry @mannaandpoem , just read you post again and noticed that you did start opendevin in WSL. Make you have .wslconfig file located at C:\Users%username%.wslconfig
> 
> ```
> [wsl2]
> networkingMode=mirrored
> localhostForwarding=true
> ```
> 
> see: https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting/windows

OK, think you for your help!
