### ISSUE TITLE
Replace the usage of `defaultProps` for React components with JavaScript default parameters.

### ISSUE THREAD

**Issue by amanape** [OpenDevin/OpenDevin#2029]
Since React 18.3.0, a console warning displays for any usage of `.defaultProps`. It is now [deprecated](https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#deprecate-defaultprops-on-function-components).

Warning:
```sh
Warning: <COMPONENT>: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```

As the in the README link shared above, we should make these changes:

BEFORE:
```tsx
interface ComponentProps = {
  optionalProp?: false;
}

const Component: React.FC<ComponentProps> = ({ optionalProp }) => /* ... */;

Component.defaultProps = {
  optionalProp = false;
};
```

AFTER:
```tsx
interface ComponentProps = {
  optionalProp?: false;
}

const Component: React.FC<ComponentProps> = ({ optionalProp = false }) => /* ... */;
```

Additionally, we have to disable the `react/require-default-props` rule from ESLint since it encourages the use of this now deprecated method (we should probably update it to the latest major release)

**Comment by prithvi2226** [comment]
Hi! I like this issue and would love to work on it, as a side question, are there any other ESLint rules we should consider updating in light of this change? Thanks!

**Comment by amanape** [comment]
@prithvi2226 The current version requires us to create or update the rule to ignore any of these usages as ESLint warns us if we don't use `defaultProps`. The current version we have though is outdated, and there has been a major release since, so I imagine the more later version of ESLint removes this warning altogether. If so, it would be preferred to have it updated rather than ignored.

**Comment by prithvi2226** [comment]
Hi! Thanks for sharing this, I would like to share with you what I am thinking of doing. Under the SWE_agent prompts, I would like to change the `DEFAULT_COMMANDS_DICT` and the `COMMAND_USAGE` by adding the examples of the previous `defaultProps` and telling it to use the new `defaultProps`. Can you share your insights on this? Also, I am still figuring out how would I update the ESLint rules using the prompts. Thanks, any insights would be appreciated!

**Comment by amanape** [comment]
@prithvi2226 I'm not sure I understand. This issue has to do with React components and the way they safely handle optional props. This was done by setting the default values for the `defaultProps` object of a component. For example: https://github.com/OpenDevin/OpenDevin/blob/3d29ec04182841f94c88b1bbc2fed84e2ca0317a/frontend/src/components/modals/base-modal/BaseModal.tsx#L63-L68

This is not the preferred version and since React 18.3.0 there are console warnings to let developers know it is deprecated in preference for regular JS default parameters.

We have to remove all usages of `defaultProps` and use JS default parameters instead. It is not dependent on any implementation or commands for the actual agent on the backend.

**Comment by prithvi2226** [comment]
Thank you very much for the clarification. So for the example given, after removing the` defaultProps` it should look something like 
`const BaseModal = ({ isDismissable = true, subtitle = undefined, actions = [], children = null }) => {
// component implementation
};
` 
also, this change is specific to the frontend React components and does not involve the implementation or commands for the agent on the backend?

**Comment by prithvi2226** [comment]
I have created a pull request and would greatly appreciate any insights or feedback on the quality of my work. Please let me know if there is anything else needed. Thank you for your time and consideration!
