### ISSUE TITLE
Support Local models with LocalAI

### ISSUE THREAD

**Issue by mudler** [OpenDevin/OpenDevin#203]
First of all - thank you, I think projects like this should exist - so I'm happy to see the community to step up.

**What problem or use case are you trying to solve?**

I'd like to use OpenDevin, but I want to use it 100% Local, for instance with LocalAI  ( https://github.com/mudler/LocalAI ) which is an OpenAI free alternative

**Describe alternatives you've considered**

**Additional context**

I'm the author of LocalAI, I can likely help in anything you need from the backend to make this working properly.

**Comment by rbren** [comment]
We're using LiteLLM--any chance of adding LocalAI as a provider?

https://docs.litellm.ai/docs/providers

**Comment by rbren** [comment]
From what I'm reading this will work seamlessly 🎉 

https://docs.litellm.ai/docs/providers/custom_openai_proxy

LMK if you think otherwise

**Comment by mudler** [comment]
oh nice! that's cool! maybe we can close this already, or maybe want to keep it open until we have an e2e working example?

**Comment by rbren** [comment]
I think we can close--but if you get a chance to try it let me know if you find any issues!
