### ISSUE TITLE
file:///home/ubuntu/OpenDevin/frontend/node_modules/vite/bin/vite.js:7     await import('source-map-support').then((r) => r.default.install())     ^^^^^  SyntaxError: Unexpected reserved wordB

### ISSUE THREAD

**Issue by ack72tdp** [OpenDevin/OpenDevin#204]
**Describe the bug**
on npm run start -- --port 3001

node --version
v12.22.9

npm --version
8.5.1

npm --version
8.5.1

Ubuntu 22.04

file:///home/ubuntu/OpenDevin/frontend/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^
SyntaxError: Unexpected reserved wordB

**Steps to Reproduce**
1.
2.
3.

**Expected behavior**

**Actual behavior**

**Additional context**

**Comment by rbren** [comment]
Looks like we need node 14+ for top-level await

https://www.stefanjudis.com/today-i-learned/top-level-await-is-available-in-node-js-modules/

Will document

**Comment by rbren** [comment]
https://github.com/OpenDevin/OpenDevin/pull/206
