### ISSUE TITLE
[Bug]: Instructions missing in Development.md for running without Docker.

### ISSUE THREAD

**Issue by larryhardin** [OpenDevin/OpenDevin#2047]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

At https://opendevin.github.io/OpenDevin/modules/usage/intro,  near the end, you will find this text: "See Development.md for instructions on running OpenDevin without Docker."
I checked the file and could not find this information.
The reason running without Docker is important to me is that I also run VMWare Player for work. During the installation of Docker, a message is displayed about how Docker modifies virtualization settings. 
Proceeding with the installation completely destroyed my VM performance and I spent hours trying to correct it. In the end, I had to uninstall docker. 
I have seen another closed ticket about this topic and it seems odd that it was a closed ticket because the person who closed the ticket didn't like the idea of running without docker, but you also put text indicating there is a way.

### Current OpenDevin version

```bash
Latest as of 5/24, which I think is 0.5
```

### Installation and Configuration

```bash
I followed instructions.
```

### Operating System

Windows 10 running WSL

### Logs, Errors, Screenshots, and Additional Context

![openDevin_Dockerless](https://github.com/OpenDevin/OpenDevin/assets/108157696/616d0275-f918-41e6-a2da-898f40ce0c08)

**Comment by SmartManoj** [comment]
https://github.com/OpenDevin/OpenDevin/blob/main/Development.md

**Comment by SmartManoj** [comment]
> I have seen another closed ticket

Could you point out that?
