### ISSUE TITLE
[Bug]: CodeAct Agent unable to execute command and write code when using ollama/llama3

### ISSUE THREAD

**Issue by arjun-mavonic** [OpenDevin/OpenDevin#2048]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

The tool is unable to actually perform the task eg, running commands and writing code when using a local model using ollama.

I've got ollama server running and have the llama3 8b pulled locally. I was successfully able to run OpenDevin while using llama3 through ollama.

But unlike when I tried with OpenAI GPT-4o which could actually perform commands like npm init -y etc, model through ollama is unable to perform actual task and write the code. All it does is suggest everything.

Probably an issue with function calling or planning I am not sure. I've attached below screenshots, if it helps.

### Current OpenDevin version

```bash
ghcr.io/opendevin/opendevin:0.5
```

### Installation and Configuration

```bash
export WORKSPACE_BASE=$(pwd)/workspace

docker run \
    -it \
    --pull=always \
    --add-host host.docker.internal:host-gateway \
    -e SANDBOX_USER_ID=$(id -u) \
    -e LLM_API_KEY="ollama" \
    -e LLM_BASE_URL="http://host.docker.internal:11434" \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    ghcr.io/opendevin/opendevin:0.5
```

### Model and Agent

- Model: ollama/llama3
- Agent: CodeActAgent

### Operating System

Mac OS

### Reproduction Steps

1. Install Ollama (ollama version is 0.1.38)
2. Run `ollama pull llama3`
3. Run `ollama serve` if already not running
4. Run OpenDevin tag 0.5
```
export WORKSPACE_BASE=$(pwd)/workspace

docker run \
    -it \
    --pull=always \
    --add-host host.docker.internal:host-gateway \
    -e SANDBOX_USER_ID=$(id -u) \
    -e LLM_API_KEY="ollama" \
    -e LLM_BASE_URL="http://host.docker.internal:11434" \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    ghcr.io/opendevin/opendevin:0.5
```
5. Open the GUI and input the `ollama/llama3` as model, `CodeActAgent` as the agent and `ollama` as the Api Key.
6. Ask OpenDevin to write a node js application for a user management service in node js and express js using mysql2

### Logs, Errors, Screenshots, and Additional Context

<img width="1470" alt="ollama-serve" src="https://github.com/OpenDevin/OpenDevin/assets/25246034/6300d48e-30ad-49b1-a105-68b23b7b00f5">
<img width="1470" alt="open-devin" src="https://github.com/OpenDevin/OpenDevin/assets/25246034/ef24e71f-f158-48e6-b879-d79dd433c66c">
<img width="1470" alt="runniing-local-model" src="https://github.com/OpenDevin/OpenDevin/assets/25246034/241d7d9c-c171-4fc1-a13c-61796d41030a">
<img width="1470" alt="ui-application-settings" src="https://github.com/OpenDevin/OpenDevin/assets/25246034/bcd79d60-f16e-4024-8fe5-f231106483ac">
<img width="1470" alt="open-devin-plan" src="https://github.com/OpenDevin/OpenDevin/assets/25246034/692a1ecb-9751-483c-9139-5cb0eb05cba4">
<img width="1470" alt="open-devin-web-ui-result" src="https://github.com/OpenDevin/OpenDevin/assets/25246034/f51f8d04-f916-4b2e-8488-6e010b0e0b4f">

**Comment by li-boxuan** [comment]
Unfortunately llama3 8b is too weak for CodeActAgent (and likely any other agent) to work properly... For now please use GPT-4 or any other LLM that is near as powerful as it.

Stay tuned, the community might fine-tune a small model in the future.

**Comment by SmartManoj** [comment]
https://github.com/OpenDevin/OpenDevin/issues/1981#issuecomment-2130783340

**Comment by mamoodi** [comment]
@arjun-mavonic going to close this based on li-boxuan's comment. Feel free to reopen if you feel otherwise.

**Comment by arjun-mavonic** [comment]
Thank you. Yes it does work with GPT 4o. But the cost is very high. I'll look into more powerful open source model which I can run on a bigger GPU and also fine tune it.

**Comment by SmartManoj** [comment]
> [#1981 (comment)](https://github.com/OpenDevin/OpenDevin/issues/1981#issuecomment-2130783340)

Did you modify the prompt?
