### ISSUE TITLE
Respect `timeout` in docker sandbox

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#207]
**Describe the bug**
Sometimes the agent tries to run commands like `npm run start` in the foreground. This just stalls out and everything hangs.

**Steps to Reproduce**
1. `python opendevin/sandbox/sandbox.py` to start a sandbox
2. run `while true; do echo "." && sleep 1; done` in the prompt

**Expected behavior**
It quits after 120s (should we pick a different timeout? `npm install` can take a while...)

**Actual behavior**
It hangs

**Comment by yufansong** [comment]
Solved in #316, can be closed.
