### ISSUE TITLE
budget 

### ISSUE THREAD

**Issue by rishi8011** [OpenDevin/OpenDevin#2073]
@li-boxuan @isavita 
 how can i set budget in opendevin ??

can anyone guide me ? i am running devin in docker 

there is no info in docs that help or guide us how we can set budget for task @mroch

**Comment by li-boxuan** [comment]
If you are using latest main, and let's assume your budget for ANY SINGLE TASK is 10 USD.

You could add 

```
max_budget_per_task=10
```

to the `[core]` section of `config.toml`.

**Comment by li-boxuan** [comment]
<img width="595" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/25746010/08038a13-6c53-4e8a-9d17-588ae6652911">

**Comment by rishi8011** [comment]
@li-boxuan 

i running this is in docker , so i can set the budget there ??

**Comment by li-boxuan** [comment]
@rishi8011 

`-e MAX_BUDGET_PER_TASK=10`

**Comment by rishi8011** [comment]
@li-boxuan 

heyy should i paste here ?? am i right 

![Screenshot 2024-05-27 043849](https://github.com/OpenDevin/OpenDevin/assets/156211215/ed2ea05f-9bbd-41a3-896b-a3d35e71c2c9)

**Comment by li-boxuan** [comment]
@rishi8011 You said you used Docker. How did you run it?

**Comment by rishi8011** [comment]
i just paste this code block that is provided in docs 

docker run \
    -it \
    --pull=always \
    -e LLM_API_KEY \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    ghcr.io/opendevin/opendevin:0.5
    
    
   and it run's i didn't use gitclone method i just simple paste this in vs code WSL: ubuntu remotely in conda env

**Comment by li-boxuan** [comment]
Change it to

```
docker run
-it
--pull=always
-e LLM_API_KEY
-e SANDBOX_USER_ID=$(id -u)
-e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE
-e MAX_BUDGET_PER_TASK=10
-v $WORKSPACE_BASE:/opt/workspace_base
-v /var/run/docker.sock:/var/run/docker.sock
-p 3000:3000
--add-host host.docker.internal:host-gateway
ghcr.io/opendevin/opendevin:0.5
```

**Comment by rishi8011** [comment]
@li-boxuan 

that's great it work thanks for help and guidance 

just a little request can share me some expert tips to be great developer just like you

**Comment by li-boxuan** [comment]
Glad it solve the issue. We should definitely improve the doc but we are moving fast so sometimes user doc is a bit outdated.
