### ISSUE TITLE
[Feature] Support CentOS

### ISSUE THREAD

**Issue by mannaandpoem** [OpenDevin/OpenDevin#2084]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When executing `make build`, an error occurred that the installation could not be successful.
![1716806330998](https://github.com/OpenDevin/OpenDevin/assets/52203545/0950de56-eed8-443b-b69b-247bdb031f4e)

### Current OpenDevin version

```bash
ghcr.io/opendevin/sandbox:latest
```

### Installation and Configuration

```bash
# Download and install Mamba (a faster version of conda)
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
bash Miniforge3-$(uname)-$(uname -m).sh

# Install Python 3.11, nodejs, and poetry
mamba install python=3.11
mamba install conda-forge::nodejs
mamba install conda-forge::poetry

# Build and Setup The Environment
make build
```

### Operating System

CentOS Linux 7

### Logs, Errors, Screenshots, and Additional Context

(nlp) [root@swebench OpenDevin]# make build

Building project...
Checking dependencies...
Checking system...
Linux detected.
Checking Python installation...
Python 3.11.9 is already installed.
Checking npm installation...
npm 10.5.0 is already installed.
Checking Node.js installation...
Node.js 20.12.2 is already installed.
Checking Docker installation...
Docker version 26.1.3, build b72abbb is already installed.
Checking Poetry installation...
Poetry (version 1.8.3) is already installed.
Dependencies checked successfully.
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:4bd05c581692e26a448bbc6771a21bb27002cb0e6bcf5034d0db91bb8704d0f0
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest
Docker image pulled successfully.
Installing Python dependencies...
Using virtualenv: /root/.cache/pypoetry/virtualenvs/opendevin-j196sbkk-py3.11
Installing dependencies from lock file

Package operations: 80 installs, 0 updates, 0 removals

  - Installing onnxruntime (1.17.3): Failed

  RuntimeError

  Unable to find installation candidates for onnxruntime (1.17.3)

  at ~/anaconda3/envs/nlp/lib/python3.11/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│ 
       71│             links.append(link)
       72│ 
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│ 
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│ 

Cannot install onnxruntime.

make[1]: *** [install-python-dependencies] 错误 1
make: *** [build] 错误 2

**Comment by SmartManoj** [comment]
Could you check `pip install onnxruntime`?

https://github.com/microsoft/onnxruntime/issues/1001

**Comment by mannaandpoem** [comment]
> Could you check `pip install onnxruntime`?
> 
> [microsoft/onnxruntime#1001](https://github.com/microsoft/onnxruntime/issues/1001)
In CentOS, it is possible to install onnxruntime, with the version being 1.16.3; however, it is not possible to install the version required by OpenDevin, which is 1.17.3.

# log
$ pip install onnxruntime==1.17.3
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.17.3 (from versions: 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.17.3

**Comment by SmartManoj** [comment]
Did you get any error with `v1.16.3`?

**Comment by mannaandpoem** [comment]
poetry install 1.17.3 defaultly.  Can I change the dependency in poetry.lock to 1.16.1?

**Comment by SmartManoj** [comment]
s

**Comment by mannaandpoem** [comment]
poetry install 1.17.3 defaultly. Can I change the dependency in poetry.lock to 1.16.3?

**Comment by SmartManoj** [comment]
s

**Comment by SmartManoj** [comment]
https://github.com/microsoft/playwright/issues/9199
