### ISSUE TITLE
Make `sandbox_image` configurable via the `initialize` event

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#210]
**What problem or use case are you trying to solve?**
Allow the user to specify which image to use in the sandbox, e.g. so it has all the right software installed

**Describe the UX of the solution you'd like**
See https://github.com/OpenDevin/OpenDevin/issues/208

**Do you have thoughts on the technical implementation?**
Would need to pull it out of the request here: https://github.com/OpenDevin/OpenDevin/blob/02a0367757b665171e9dff28fe434713382f2b92/opendevin/server/session.py#L116

and then plumb it through to the sandbox

**Comment by 0xSaurabhx** [comment]
[made changes ](https://github.com/OpenDevin/OpenDevin/tree/b3ea6a81f6654af59115e5b33573c4224a9b935e)

**Comment by rbren** [comment]
Looks like that link is broken--do you have a PR?

**Comment by 0xSaurabhx** [comment]
> Looks like that link is broken--do you have a PR?

#211
