### ISSUE TITLE
[Bug]: opendevin:WARNING: llm.py:137 - Could not get model info for ollama/*:*

### ISSUE THREAD

**Issue by unclemusclez** [OpenDevin/OpenDevin#2118]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

`llm.py` is unable to find llm information for Local Ollama models.
Ollama models will use a `:` to indicated which quantization is being used of a specific model.
As I understand it, llm.py should be able to parse the LLM type from the config.

Perhaps something to the effect of the following in `config.toml`:
```
[llm]
model="ollama/command-r:35b-v0.1-q3_K_L"
model_info="ollama/command-r"
api_key="ollama"
```

I believe being able to specify/parse the `ollama/command-r` from `ollama/command-r:35b-v0.1-q3_K_L` in the web interface, or be able to enter it in the `config.toml` is needed. It could also be useful for custom `model`'s that are essentially using `model_info`'s of the `model` they are based off of. 

### Current OpenDevin version

origin main 
`make start-backend`

### Installation and Configuration

```bash
[core]
workspace_base='/home/opendevin/workspace'
workspace_mount_path_in_sandbox='/home/opendevin/workspace'
workspace_mount_path='/home/opendevin/workspace'

[llm]
model="ollama/command-r:35b-v0.1-q3_K_L"
model_info="ollama/command-r"
api_key="ollama"
base_url="http://localhost:11434"
embedding_model="local"
```

### Model and Agent

CodeAct Agent 
Command-R
![5eho3d2](https://github.com/OpenDevin/OpenDevin/assets/8789242/f62fa436-bf32-47c3-97c5-a912d39e4f80)

### Logs, Errors, Screenshots, and Additional Context

```15:27:18 - opendevin:INFO: browser_env.py:35 - Starting browser env...
15:27:20 - opendevin:INFO: browser_env.py:51 - Browser env started.
15:27:20 - opendevin:INFO: agent.py:96 - Creating agent CodeActAgent using LLM ollama/command-r:35b-v0.1-q3_K_L
15:27:20 - opendevin:INFO: llm.py:120 - Initializing LLM with model: ollama/command-r:35b-v0.1-q3_K_L
15:27:20 - opendevin:WARNING: llm.py:137 - Could not get model info for ollama/command-r:35b-v0.1-q3_K_L
```

**Comment by SmartManoj** [comment]
Fixed.

https://github.com/OpenDevin/OpenDevin/assets/7231077/9e57a50a-de4d-4ee8-9d06-9c68ad98a77d
