### ISSUE TITLE
Add support to AzureOpenAI

### ISSUE THREAD

**Issue by ack72tdp** [OpenDevin/OpenDevin#213]
**What problem or use case are you trying to solve?**
Add support to AzureOpenAI 

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by rbren** [comment]
Please see: https://github.com/opendevin/opendevin?tab=readme-ov-file#picking-a-model

Here's the LiteLLM docs for https://docs.litellm.ai/docs/providers/azure

Let me know if that doesn't work

**Comment by ack72tdp** [comment]
I have custom API_BASE which points to AZURE_API_BASE .. Can we publish all the LLM variables exposed .. such as LLM_MODEL, LLM_API_KEY.

**Comment by rbren** [comment]
It's just `LLM_MODEL` and `LLM_API_KEY` that are custom to OpenDevin--the rest is managed by LiteLLM.

Would a link here help? https://litellm.vercel.app/docs/set_keys#environment-variables
