### ISSUE TITLE
[Bug]: Password must be set for persistent sandbox

### ISSUE THREAD

**Issue by unclemusclez** [OpenDevin/OpenDevin#2134]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

 trying to run as normal and i am receiving the following error:
```
  File "/home/opendevin/opendevin/runtime/docker/ssh_box.py", line 231, in __init__
    raise Exception('Password must be set for persistent sandbox')
```

### Current OpenDevin version

```bash
main
make start-backend
```

### Installation and Configuration

```bash
git pull origin main
```

### Reproduction Steps

`make start-backend`

### Logs, Errors, Screenshots, and Additional Context

```
11:44:33 - opendevin:ERROR: session.py:69 - Error creating controller: Password must be set for persistent sandbox
Traceback (most recent call last):
  File "/home/opendevin/opendevin/server/session/session.py", line 67, in _initialize_agent
    await self.agent_session.start(data)
  File "/home/opendevin/opendevin/server/session/agent.py", line 46, in start
    await self._create_runtime()
  File "/home/opendevin/opendevin/server/session/agent.py", line 65, in _create_runtime
    self.runtime = ServerRuntime(self.event_stream, self.sid)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opendevin/opendevin/runtime/server/runtime.py", line 35, in __init__
    super().__init__(event_stream, sid, sandbox)
  File "/home/opendevin/opendevin/runtime/runtime.py", line 71, in __init__
    self.sandbox = create_sandbox(sid, config.sandbox_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opendevin/opendevin/runtime/runtime.py", line 45, in create_sandbox
    return DockerSSHBox(sid=sid)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/opendevin/opendevin/runtime/docker/ssh_box.py", line 231, in __init__
    raise Exception('Password must be set for persistent sandbox')
Exception: Password must be set for persistent sandbox
^CINFO:     Shutting down
```

**Comment by SmartManoj** [comment]
Yes.

**Comment by gagangayari** [comment]
I am following [Development.md](https://github.com/OpenDevin/OpenDevin/blob/main/Development.md) . But I am also facing this similar issue

<img width="1269" alt="Screenshot 2024-05-31 at 8 53 28 PM" src="https://github.com/OpenDevin/OpenDevin/assets/55296443/37c9e84d-1729-4d8b-a45e-2d8d90205df9">

**Comment by SmartManoj** [comment]
Did you run `make setup-config`?

**Comment by unclemusclez** [comment]
we can close this.. and if necessary i can help with this issue for people in the future. im in the discord.

i think a lot of these configuration issues come from people not understanding how this application works. /Workspace is generated by the application. That directory should not exist prior.

I think people are trying to build this application linking it to their per-existing workspace on their host machine. whereas, you should really ssh into your opendevin workspace and work from there with terminal, vscode, etc.

you guys are awesome! thanks for all of the help.
