### ISSUE TITLE
Submit SWE-bench results to the official leaderboard?

### ISSUE THREAD

**Issue by 0xdevalias** [OpenDevin/OpenDevin#2136]
## Describe your question

Curious if there are plans to submit the SWE-bench results to the official leaderboard; and/or if there is a reason why they haven't been yet.

## Additional context

- https://github.com/swe-bench/experiments#leaderboard-participation
  - > Leaderboard Participation
    > If you are interested in submitting your model to the [SWE-bench Leaderboard](https://www.swebench.com/), please do the following...
- https://x.com/xingyaow_/status/1787862432888545665
  - OpenDevin CodeAct 1.0 - achieves a 21% unassisted resolve rate on SWE-Bench Lite
- https://x.com/gneubig/status/1791498953709752405
  - OpenDevin CodeAct 1.3 agent with browsing and github support. With GPT-4o, 25% accuracy on SWE-Bench Lite
- https://x.com/_devalias/status/1795994610746998934
  - My tweet asking about submitting the results
- https://github.com/swe-bench/experiments/pull/7
  - `aider` recently added their results

Tangentially related:

- https://github.com/OpenDevin/OpenDevin/issues/2072
- https://github.com/OpenDevin/OpenDevin/issues/1693
- https://github.com/OpenDevin/OpenDevin/issues/1289

**Comment by li-boxuan** [comment]
The recent experiments had some problems - they used the hint column from the benchmark, which the original SWE-Agent team claimed they didn't use. Removal of that column as part of prompt dropped the benchmark score, but the community is still running benchmarks. Stay tuned.

**Comment by mamoodi** [comment]
@0xdevalias if that answered your question, please consider closing the issue :)

**Comment by 0xdevalias** [comment]
> please consider closing the issue

@mamoodi I mean.. technically it does answer it, but there is also no current resolution to it, so I would tend to leave an issue open until it's been resolved; which in this case, would be when the results are fixed up/re-run and submitted.

If you have differing opinions as repo maintainers, close it if you need to.

**Comment by neubig** [comment]
Hey @0xdevalias , also for additional context, we're working on a paper with a deadline next Wednesday, we'll probably submit to the leaderboard after that!

**Comment by 0xdevalias** [comment]
@neubig Awesome, appreciate the update! :)

**Comment by neubig** [comment]
THis is finished thanks to @li-boxuan

**Comment by 0xdevalias** [comment]
> THis is finished thanks to @li-boxuan

Submission PR for continuity:

- https://github.com/swe-bench/experiments/pull/44
