### ISSUE TITLE
Fix annoying "typing" effect for LLM output

### ISSUE THREAD

**Issue by renxida** [OpenDevin/OpenDevin#2156]
**What problem or use case are you trying to solve?**
Multiple messages would sonetimes show up in the chat interface, each showing a chat output. All the chat outputs would play the typing animation, making it hard to read and very annoying to watch & wait for.

**Describe the UX of the solution you'd like**
1. If multiple messages pop into the chatbox at once, only the final message should show the "typing" animation.
2. The user should be able to turn off ALL typing animations by e.g. modifying a config file or adding a param to the url.

**Comment by amanape** [comment]
Which version of OpenDevin are you currently running? The latest version (future release) removes the typing effect altogether.

**Comment by renxida** [comment]
just built latest and tried it. It's gone! Thanks @amanape
