### ISSUE TITLE
Can't use `apt-get install` in sandbox

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#216]
**Describe the bug**
Often OpenDevin needs to install software in order to perform its task, e.g. `nodejs` and `npm`

By default, we run as user `devin`, which is not a sudoer and can't use apt-get.

Workaround: `export RUN_AS_DEVIN=false`

**Steps to Reproduce**
1. run `python opendevin/sandbox/sandbox.py`
2. enter `apt-get install nodejs` or `sudo apt-get install nodejs`

**Expected behavior**
nodejs installs (maybe with sudo?)

**Actual behavior**
Fails

**Additional context**

**Comment by mickstar** [comment]
The docker image doesn't have sudo so we could add that, but then we would also need to remove the password requirement for the devin user. Better off just running as root from the get go which is what RUN_AS_DEVIN=false does.

**Comment by rbren** [comment]
https://github.com/OpenDevin/OpenDevin/pull/390
