### ISSUE TITLE
[Bug]:  ./workspace /bin/bash: -c: line 8: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by unclemusclez** [OpenDevin/OpenDevin#2166]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

trying to generate a fresh config file

```
opendevin@NSA:~$ make setup-config
Setting up config.toml...
make[1]: Entering directory '/home/opendevin'
Enter your workspace directory [default: ./workspace]: ./workspace
/bin/bash: -c: line 8: syntax error: unexpected end of file
make[1]: *** [Makefile:225: setup-config-prompts] Error 2
make[1]: Leaving directory '/home/opendevin'
make: *** [Makefile:218: setup-config] Error 2
```

### Current OpenDevin version

```bash
origin main
```

### Installation and Configuration

```bash
make start-backend
```

**Comment by SmartManoj** [comment]
Thanks for the report. 🥰
