### ISSUE TITLE
`source ~/.bashrc` times out when running as root

### ISSUE THREAD

**Issue by SmartManoj** [OpenDevin/OpenDevin#2178]
Regarding `source .bashrc` timing out, I'm guessing that there is some command in the root `source .bashrc` file that times out so if we could figure out which command it is on when it hangs I think that would put us in the right direction.

_Originally posted by @neubig in https://github.com/OpenDevin/OpenDevin/pull/1651#pullrequestreview-2050806807_
            
---

Need to examine it's content.

**Comment by mamoodi** [comment]
@SmartManoj was this issue resolved with the PRs that merged against it? Or is there anything remaining?

**Comment by SmartManoj** [comment]
If the `source ~/.bashrc` command is used, the problem may be raised. #2172

**Comment by neubig** [comment]
Hey, @x66ccff , could you elaborate a little bit more? It might be good for you to create a new issue that describes how you're running OpenHands (e.g. through the official docker command, or through the dev workflow of `make run; make build`), etc. That will help us debug your specific case. Thanks!
