### ISSUE TITLE
browser can not open the web generated by codeact agent,but the curl respone is correct.

### ISSUE THREAD

**Issue by b0pro** [OpenDevin/OpenDevin#2188]
## Describe your question
i use gpt-4o as llm backedn,and i ask the codeact agent write a simple web(print the current date),the curl respone is correct,but when the browser open the route,it always show the error page,how can i fix it.

root@11b63dcc078d:/workspace# curl http://127.0.0.1:5000
<h1>Current Date and Time: 2024-06-01 18:27:44</h1>root@11b63dcc078d:/workspace#

**BrowseInteractiveAction**
THOUGHT: 好的，让我们使用浏览器打开该网址。
BROWSER_ACTIONS: goto("http://0.0.0.0:5000")
18:35:39 - OBSERVATION
**BrowserOutputObservation**
URL: chrome-error://chromewebdata/
Status code: 200
Error: True
Open pages: ['chrome-error://chromewebdata/']
Active page index: 0
Last browser action: goto("http://0.0.0.0:5000")
Last browser action error: Error: net::ERR_CONNECTION_REFUSED at http://0.0.0.0:5000/
=========================== logs ===========================
navigating to "http://0.0.0.0:5000/", waiting until "load"
============================================================
Focused element bid: 2
CONTENT:

![image](https://github.com/OpenDevin/OpenDevin/assets/13183524/c1b4de7e-9f4e-4382-9c58-997e47276026)

**Comment by li-boxuan** [comment]
Can you prompt the agent to try `localhost`, when it asks for user input?

**Comment by b0pro** [comment]
> Can you prompt the agent to try `localhost`, when it asks for user input?

thanks your reply.i ask the agent to open http://0.0.0.0:5000 or http://127.0.0.1:5000，the same error return.but i can ask the other url like (bing.com),the browser can open the web. it seems like something about docker net config make the local server can not visited?

**Comment by li-boxuan** [comment]
That's very weird. One thing you could try:

1. Follow whatever the agent has done (same code and command), but do it outside the sandbox. E.g. write the app and launch the app by yourself.
2. Prompt the agent to visit the web page.

This could help us isolate if it's a docker/sandbox issue.

**Comment by b0pro** [comment]
> That's very weird. One thing you could try:
> 
> 1. Follow whatever the agent has done (same code and command), but do it outside the sandbox. E.g. write the app and launch the app by yourself.
> 2. Prompt the agent to visit the web page.
> 
> This could help us isolate if it's a docker/sandbox issue.

thanks for your help,i try it later

**Comment by b0pro** [comment]
> That's very weird. One thing you could try:
> 
> 1. Follow whatever the agent has done (same code and command), but do it outside the sandbox. E.g. write the app and launch the app by yourself.
> 2. Prompt the agent to visit the web page.
> 
> This could help us isolate if it's a docker/sandbox issue.

i find the problem is that the browser is running on the main container(so the browser can not visit the sandbox container url).so when i start a server at the main container like http://127.0.0.1:5000,the chrome browser open the url correct.but the agent is auto generate the code and  run the flask at the sandbox  containers,so the chrome return error。now my question is how can i config the port map on the sandbox container or other solutions?thx. 
i just run the main container use the cmd:
docker run -it --add-host host.docker.internal:host-gateway     -e SANDBOX_USER_ID=$(id -u)     -e SSH_PASSWORD="xxxx" -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE     -v $WORKSPACE_BASE:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     ghcr.io/opendevin/opendevin:main

**Comment by neubig** [comment]
@b0pro : sorry about the late reply on this!

Can you try setting `USE_HOST_NETWORK=true` in your `config.toml` file? This should fix the problem temporarily.

**Comment by mamoodi** [comment]
@b0pro did you try the above suggestion to see if it works?
