### ISSUE TITLE
[langchains] tries to use the wrong `python` command

### ISSUE THREAD

**Issue by skadaba1** [OpenDevin/OpenDevin#219]
**Describe the bug**
OpenDevin cannot run python code because the environment variable for its sandbox does not seem to be set
**Steps to Reproduce**
1. Fahrenheit_to_celsius example given in ReadMe
2.
3.

**Expected behavior**

**Actual behavior**

**Additional context**
        ACTION:
        CmdRunAction(command='python fahrenheit_to_celsius.py', background=False)

        OBSERVATION:
        bash: line 1: python: command not found

ACTION:
        CmdRunAction(command='apt update && apt install python3 -y', background=False)

        OBSERVATION:

        WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

        Reading package lists...
        E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)

**Comment by skadaba1** [comment]
Noticed that it was executing functions with python and pip whereas it should be using python3 and pip3. How do I change default commands it uses?

**Comment by rbren** [comment]
Hmm--this isn't a simple issue. The LLM is responsible for deciding what commands to run and what to try. But we could potentially provide it with a list of installed software as part of the prompt

Related issue: https://github.com/OpenDevin/OpenDevin/issues/216

**Comment by VJlaxmi** [comment]
Hi @rbren, can I please take up this task?

**Comment by rbren** [comment]
I don't think there's any easy solution here--I'm going to close it for now. We have a separate issue tracking the ability to install python

**Comment by hqnicolas** [comment]
if I just change the container on sandbox.py?
quay.io/jupyter/scipy-notebook

**Comment by rbren** [comment]
yes you can set the sandbox container image in your config.toml
