### ISSUE TITLE
Add file picker to choose the working directory

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#221]
**What problem or use case are you trying to solve?**
Allow the user to pick which directory they want to work in

**Describe the UX of the solution you'd like**
A filepicker above the chat window. See also: https://github.com/OpenDevin/OpenDevin/issues/208

**Do you have thoughts on the technical implementation?**
Should probably use the system filepicker UI. Will need to be able to select a directory

When the directory is chosen, an `initialize` action can  be sent to the backend to reinitialize the agent

**Comment by Yashwanth-Chandrakumar** [comment]
Hi @rbren just added the feature right now at PR #289

**Comment by yimothysu** [comment]
The current implementation actually doesn't get the directory path, just the directory name.

It seems that selecting a directory path is only possible via https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker, which is not supported in Firefox, Safari, or mobile browsers.

More info: https://stackoverflow.com/questions/2809688/directory-chooser-in-html-page

@rbren should we use this to add support for Chromium browsers only?

**Comment by Yashwanth-Chandrakumar** [comment]
Let me try me best to obtain the directory path, if not possible i will let you know. 

There are other options like uploading the directory into the model, like website deploying but i think they may cause some performance issue.

**Comment by WorldICTown** [comment]
I thoroughly enjoyed reading this.Learned a lot. The writing style is PROFESSIONAL, and the content is both interesting and valuable. Looking forward to more! By the way,if you have any ICs' need, find all your chip needs at https://www.worldictown.com/ – your one-stop destination for a diverse range of chips and solutions.You can contact us on Worldictown

**Comment by rbren** [comment]
Oh interesting, yeah this does seem like a hard problem!

Should we revert the existing PR, so people don't get confused?

**Comment by yimothysu** [comment]
Sure

**Comment by yimothysu** [comment]
I opened a new PR that correctly changes the directory. This uses a text input instead of file picker. It's not as nice, but it works.
