### ISSUE TITLE
[Feature]: Aider-inspired EditBlock functionality

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#2222]
**What problem or use case are you trying to solve?**

Aider has implemented functionality to improve editing, which could be helpful for our work as well.

**Do you have thoughts on the technical implementation?**

The code for Aider `EditBlockCoder` is [here](https://github.com/paul-gauthier/aider/blob/4753db0b0f6b597410fda1288d484f367819fed5/aider/coders/editblock_coder.py#L11)

Within OpenDevin, we could either:
1. Create a separate agent called EditBlockAgent that specifically aims at performing edits based on a description
2. Try to align the interface/prompt of our existing agents with Aider, possibly by adding an `aider_edit_file()` skill to the agentskills framework: https://github.com/OpenDevin/OpenDevin/blob/c9c5d71e5c6fe153dfdb4a1db943501fcd1d60e4/opendevin/runtime/plugins/agent_skills/agentskills.py#L247

We may also want to consider running [benchmarking](https://aider.chat/docs/leaderboards/) that is similar to aider as well.

**Additional context**

* #120 as a super-issue

**Comment by edwardbrazier** [comment]
Hey @neubig, I have a suggestion on this:
Aider sometimes malfunctions because it includes too little context in its diffs.
It sometimes edits the wrong passage within the right file.
I suggest directing the AI to always include a bit of extra context either side.

**Comment by neubig** [comment]
Thanks @edwardbrazier ! As far as I know, no-one is working on this at the moment so if you want to take a look it'd be welcome.

**Comment by edwardbrazier** [comment]
@neubig, I am interested but will focus on #2363 first.

**Comment by xingyaoww** [comment]
I'm currently implement a variant of this since i spotted too many issues with `edit_file` now - can share a PR when it is close to ready!
