### ISSUE TITLE
[Bug]: Remove Textarea bottom shadow when at bottom of messages

### ISSUE THREAD

**Issue by tobitege** [OpenDevin/OpenDevin#2236]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

There is a shadow effect at the bottom of the messages list, which is quite distracting/annoying when it is still visible at the bottom of the list. Just visually I'm then triggered to scroll down further! 🙄 Habits!
![grafik](https://github.com/OpenDevin/OpenDevin/assets/10787084/f593531e-b1fa-4966-968c-b199f3111883)

It's a tiny thing, but I can't unsee it each and every time. 😬 

### Current OpenDevin version

```bash
main
```

### Installation and Configuration

```bash
WSL
```

**Comment by tobitege** [comment]
Ok, I found what is responsible, I think, in frontend/src/components/chat/ChatInterface.tsx:
```ts
        {/* Fade between messages and input */}
        <div
          className={twMerge(
            "absolute bottom-0 left-0 right-0",
            curAgentState === AgentState.AWAITING_USER_INPUT ? "h-10" : "h-4",
            "bg-gradient-to-b from-transparent to-neutral-800",
          )}
        />
```

**Comment by SmartManoj** [comment]
Did you change and confirm?
