### ISSUE TITLE
Q: Add workspace hint (absolute path) to "make setup"?

### ISSUE THREAD

**Issue by tobitege** [OpenDevin/OpenDevin#2246]
## Should there be a better hint for workspace folder?

Running `make setup` calls setup-config-prompts within Makefile and prompts the user for the workspace directory.

Unless I'm mixing this up here, wouldn't it be helpful to echo beforehand, that it should be an absolute path, since the suggested value is a relative path?

**Comment by enyst** [comment]
It would absolutely be useful!

**Comment by tobitege** [comment]
Fixed by #2289
