### ISSUE TITLE
View descriptions and examples of the different agents types?

### ISSUE THREAD

**Issue by 4tal** [OpenDevin/OpenDevin#2251]
## Describe your question

I didn't find any relevant explanations for these.
What about adding "?" for additional explanations or links for references?

## Additional context

<img width="359" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/6404507/af7f6e1d-3fb1-4d45-b78a-246565fd03ef">

**Comment by tobitege** [comment]
The only info I can find is this, but a good question/request!

https://github.com/OpenDevin/OpenDevin/blob/main/agenthub/README.md

**Comment by mamoodi** [comment]
There isn't any explanation for all of these agents right now. It's been asked a few times and brought to the attention of maintainers. More are being added and some are being deprecated in favor of others. I'm guessing this dropdown will be changed a little in the future on how it works and probably will add descriptions.
