### ISSUE TITLE
Feature Request: Devcontainer configuration to Contribute

### ISSUE THREAD

**Issue by IA-Programming** [OpenDevin/OpenDevin#2264]
**What problem or use case are you trying to solve?**
In order to pass directly to the code and don't be stall in the installation and setting of the environment

**Do you have thoughts on the technical implementation?**
  Would it be very helpful to be able to make a devcontainer setup setting json file to get started easily like with the deployment command jus one bash docker command

**Describe alternatives you've considered**
If it's not a devcontainer setup file may could it be using make files

**Additional context**
I'm currently reviewing the backend code in order to add some features but just to get started setting up the workflow environment on my windows and vscode environment it seems a little overwhelming, just to get started

**Comment by mamoodi** [comment]
Hi if I'm understanding this, you can setup the development with: https://github.com/OpenDevin/OpenDevin/blob/main/Development.md

With Windows you have to setup WSL.
