### ISSUE TITLE
run Devin via cli

### ISSUE THREAD

**Issue by josephykwang** [OpenDevin/OpenDevin#2265]
## Describe your question

in the previous release, one can invoke Devin 

```
PYTHONPATH=`pwd` python opendevin/main.py -i 500 -f ${taskfile}
```

don't see doc mentioning how to run Devin via cli for 0.6.1.

**Comment by enyst** [comment]
You can still do that, just `main.py` is now in `opendevin.core`. If you wish, you can use -c for the agent of your choice. Also you can use -l parameter to load a pre-configured llm, e.g. add in config.toml separately from the rest:

```
[claude]
model="claude-3-opus-20240229"
api_key="sk-something"

[gpt-35]
model="gpt-3.5-turbo"
api_key="sk-something-else"
...
```
and use it like python opendevin/core/main.py -i 500 -f ${taskfile} -l claude

I'm not sure what happened to its doc, but we should document it. Probably this is a good place https://github.com/OpenDevin/OpenDevin/blob/main/Development.md

**Comment by josephykwang** [comment]
What r available agents? Any doc when a particular agent should be used?Sent from my iPhoneOn Jun 5, 2024, at 4:40 PM, Engel Nyst ***@***.***> wrote:﻿
You can still do that, just main.py is now in opendevin.core. If you wish, you can use -c for the agent of your choice. Also you can use -l parameter to load a pre-configured llm, e.g. add in config.toml separately from the rest:
[claude]
model="claude-3-opus-20240229"
api_key="sk-something"

[gpt-35]
model="gpt-3.5-turbo"
api_key="sk-something-else"
...

and use it like python opendevin/core/main.py -i 500 -f ${taskfile} -l claude
I'm not sure what happened to its doc, but we should document it. Probably this is a good place https://github.com/OpenDevin/OpenDevin/blob/main/Development.md

**Comment by enyst** [comment]
The agents are here:
https://github.com/OpenDevin/OpenDevin/tree/main/agenthub

There is a README on the folder, though I don't think it answers your question, it's more geared for agent research and development, which is their purpose.

The best suggestion I can give is actually to use CodeAct unless you have a reason to use another. CodeAct, SWE-CodeAct and Monologue are generic agents, with the other two older and not as good. Others are in development, micro-agents or delegates are experimental and might be used by other agents as necessary (by CodeAct perhaps, in the future). Browsing agent is fine, but as the name says, it's specialized and its main use will probably be via another, for browsing tasks.

**Comment by yufansong** [comment]
We recommand to use poetry to run the opendevin. Using cli run it may cause lots of dependency and environment problem.
