### ISSUE TITLE
App does not initialize on Mac OS

### ISSUE THREAD

**Issue by AndyPelaez** [OpenDevin/OpenDevin#2266]
### Describe your question
I used the command provided by the documentation to run the openDevin container, but the website does not initialize. I have checked all Mac OS requirements, and it keeps not initializing.

### A clear and concise description of what you want to know
I need to test it on my local using GPT-4. How can I resolve this initialization issue?

#### Console Output
<img width="1542" alt="Screenshot 2024-06-04 at 6 43 40 PM" src="https://github.com/OpenDevin/OpenDevin/assets/86849083/118a02f9-99e2-4646-9811-32688ad6863f">

#### Client Initializing message
<img width="1542" alt="Screenshot 2024-06-04 at 6 44 00 PM" src="https://github.com/OpenDevin/OpenDevin/assets/86849083/24b72505-36e1-4161-bf3e-489a04b29371">

### Steps to reproduce
1. Followed the documentation steps to run the openDevin container.
2. Checked all prerequisites for Mac OS.
3. Ran the provided command.
```sh

OPENDEVIN_WORKSPACE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
        -e LLM_API_KEY="my-openai-key" \
    -e PERSIST_SANDBOX="true" \
    -e SSH_PASSWORD="make something up here" \
-e HF_HOME=/opt/workspace_base/.cache/huggingface/hub \
    -e WORKSPACE_MOUNT_PATH=$OPENDEVIN_WORKSPACE \
    -v $OPENDEVIN_WORKSPACE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.6
```

### What I have tried so far
- Rechecked the Mac OS requirements.
- Verified the steps in the documentation.
- Searched for similar issues in the repository.

Any help to get this running would be greatly appreciated. Thank you!

**Comment by tarangkr12** [comment]
Can you try to configure with Gemini once if it's working or not. You can refer below template where you have to insert your gemini api key and gemini model name.

OPENDEVIN_WORKSPACE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e PERSIST_SANDBOX="true" \
    -e SSH_PASSWORD="make something up here" \
    -e GEMINI_API_KEY="<your-gemini-api-key>" \
    -e LLM_MODEL="gemini/gemini-pro" \
    -e WORKSPACE_MOUNT_PATH=$OPENDEVIN_WORKSPACE \
    -v $OPENDEVIN_WORKSPACE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.6

**Comment by SmartManoj** [comment]
Any errors in the browser console?

**Comment by mamoodi** [comment]
@AndyPelaez have you tried the last 0.6.2 tag and checking if it works with the new command on README?
