### ISSUE TITLE
Adding copy button next to code responses, similar to other AI chat services

### ISSUE THREAD

**Issue by 4tal** [OpenDevin/OpenDevin#2292]
**What problem or use case are you trying to solve?**
no need to manually select the code

**Describe the UX of the solution you'd like**
faster copy / paste to other platform

**Comment by enyst** [comment]
You may want to see this previous discussion: https://github.com/OpenDevin/OpenDevin/issues/1590

**Comment by enyst** [comment]
I will close this in favor of the linked issue, please feel free to continue the discussion there.
