### ISSUE TITLE
allow to specify llm config like max output token limit and temperature via main.py cli

### ISSUE THREAD

**Issue by josephykwang** [OpenDevin/OpenDevin#2303]
each 3P vendor has different model parameters. their corresponding default value is model specific.

we want to be able to pass temperature and max temperature via cli so that we can write an optimizer to pick the best set of parameters

**Comment by enyst** [comment]
You can set llm parameters, including `temperature` and `max_output_tokens`, in config.toml. Something like this works:
```
...
[gpt-name-it-as-you-like]
model="GPT-4o"
api_key=...
temperature=0
max_output_tokens=4096
...
[claude]
model="Claude-opus..."
api_key=...
temperature=0
max_output_tokens=2048
...
```
The section names here are user-defined. Then when running main.py, use the respective section name with -l or --llm-config, e.g. `main.py --llm-config=claude ...`

Note that all attributes of LLMConfig class from opendevin.core.config.py can be set in custom llm configs this way, but the agents are able to override them. Currently most agents don't override anything as far as I know, except CodeAct and CodeActSWE on temperature: they always call the API with `temperature=0`.

**Comment by josephykwang** [comment]
your suggestion means extra step of creating a config file
    On Wednesday, June 19, 2024 at 04:42:25 PM PDT, Engel Nyst ***@***.***> wrote:  
 
 


You can set llm parameters, including temperature and max_output_tokens, in config.toml. Something like this works:
...
[gpt-name-it-as-you-like]
model="GPT-4o"
api_key=...
temperature=0
max_output_tokens=4096
...
[claude]
model="Claude-opus..."
api_key=...
temperature=0
max_output_tokens=2048
...

The section names here are user-defined. Then when running main.py, use the respective section name with -l or --llm-config, e.g. main.py --llm-config=claude ...

Note that all attributes of LLMConfig class from opendevin.core.config.py can be set in custom llm configs this way, but the agents are able to override them. Currently most agents don't override anything as far as I know, except CodeAct and CodeActSWE on temperature: they always call the API with temperature=0.

**Comment by tobitege** [comment]
> each 3P vendor has different model parameters. their corresponding default value is model specific.
> 
> we want to be able to pass temperature and max temperature via cli so that we can write an optimizer to pick the best set of parameters

I think the litellm documentation for Docker can help your requirements with some examples how to pass environment variables with the docker command line into the sandbox via the "-e" option:
https://litellm.vercel.app/docs/proxy/deploy
https://litellm.vercel.app/docs/proxy/cli

**Comment by enyst** [comment]
Alternatively, you can use the env vars version of the config.toml variables. The env vars are uppercase, and if they're part of LLM config, then they have the prefix LLM_. So LLM_TEMPERATURE, LLM_MAX_OUTPUT_TOKENS, etc.

**Comment by mamoodi** [comment]
Looks like this can be closed as you can pass in these configs already, correct @enyst?

**Comment by enyst** [comment]
Yes, I think we can pass these already, either in env or config file. @josephykwang please feel free to re-open if it still doesn't address your intended use.
