### ISSUE TITLE
[Bug]: can't edit typescript files with template literals

### ISSUE THREAD

**Issue by tholum** [OpenDevin/OpenDevin#2314]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

If writting typescript that has template literals ( the strings with backtick's ) it is never able to write them

### Current OpenDevin version

```bash
ghcr.io/opendevin/opendevin:0.6
ghcr.io/opendevin/opendevin:0.5

Also ( 2 weeks ago ) tried it on ghcr.io/opendevin/opendevin:main
```

### Installation and Configuration

```bash
Just the standard setup from getting started

OPENDEVIN_WORKSPACE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e PERSIST_SANDBOX="true" \
    -e SSH_PASSWORD="<a password>" \
    -e WORKSPACE_MOUNT_PATH=$OPENDEVIN_WORKSPACE \
    -v $OPENDEVIN_WORKSPACE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.6
```

### Model and Agent

- Model : gpt-4o
- CodeActAgent

### Operating System

Linux

### Reproduction Steps

with this prompt

Clone the repository https://github.com/tholum/OpenDevinBugs.git then go to the folder 02_cant_edit_typeliterals folder

install npm lts using nvm

Edit test.js change MY_VARIABLE to "Hello World 2" and change the output to be "for another test" at the end of the console.log

### Logs, Errors, Screenshots, and Additional Context

It loops attempting to fix it unitl I stop it ( I gave it at least 50 loops of attempting to fix it )

![image](https://github.com/OpenDevin/OpenDevin/assets/2395584/386da7bd-1921-4961-804c-3ea09fe0cdeb)

**Comment by tobitege** [comment]
Hello
yes, I noticed it too. I'm in the process of tracking the cause down and already did some extra tests to eliminate some code suspects in this PR #2307

**Comment by tobitege** [comment]
This is fixed now with https://github.com/OpenDevin/OpenDevin/pull/2321

Feel free to close the issue or provide more feedback in case the issue reappears.

**Comment by tholum** [comment]
Thanks @tobitege I just tested it on main and it works :)
