### ISSUE TITLE
API key error when using Claude

### ISSUE THREAD

**Issue by JimJim12** [OpenDevin/OpenDevin#233]
When following instructions on using litellm, I get an error saying openai api key incorrect:
Retrying llama_index.embeddings.openai.base.get_embeddings in 3.1550330153450243 seconds as it raised AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: . You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}.

Instructions I'm following:
To change the model, set the `LLM_MODEL` and `LLM_API_KEY` environment variables.

For example, to run Claude:
```bash
export LLM_API_KEY="your-api-key"
export LLM_MODEL="claude-3-opus-20240229"
```

Is it that all that needs to be done to use another model like claude through litellm?

**Comment by rbren** [comment]
Deduping with https://github.com/OpenDevin/OpenDevin/issues/228

@JimJim12 there's a branch with a fix if you're able to try it out
