### ISSUE TITLE
[Bug]: "Publish Docker Image" CI workflow is failing

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#2330]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Currently docker build seems to be consistently failing, one example here: https://github.com/OpenDevin/OpenDevin/actions/runs/9394171049/job/25973749341?pr=2081

### Current OpenDevin version

```bash
main
```

### Installation and Configuration

```bash
n/a
```

**Comment by SmartManoj** [comment]
![image](https://github.com/OpenDevin/OpenDevin/assets/7231077/4d81b84e-cd98-418f-b03d-dabbb01aff20)

**Comment by enyst** [comment]
Looks like we're not the only ones: https://github.com/pydantic/pydantic/pull/9610
