### ISSUE TITLE
Agent Config

### ISSUE THREAD

**Issue by enyst** [OpenDevin/OpenDevin#2337]
**What problem or use case are you trying to solve?**
We need some way to configure the agent more in detail and easier than we do today.
For example [on slack](https://opendevin.slack.com/archives/C06U8UTKSAD/p1717779430449069?thread_ts=1717778692.412489&channel=C06U8UTKSAD&message_ts=1717779430.449069)
Also: https://github.com/OpenDevin/OpenDevin/pull/1996#pullrequestreview-2104227581
- config to prefer command line for working on github (presumably enabling/disabling some part of the prompt)
- eval_mode

**Describe the UX of the solution you'd like**
An AgentConfig modeled after LLMConfig, as described in this comment: https://github.com/OpenDevin/OpenDevin/pull/1552#issuecomment-2093998935
In practice, it would be like:
```
[agent]
name=CodeActAgent
memory_enabled=true
prefer_browsing_on_github=false
prefer_browsing=true
max_history=20
summarize_delegates=true

[browse]
name=BrowsingAgent
memory_enabled=false
prefer_browsing_on_github=true

[mono]
name=MonologueAgent
memory_enabled=true
prefer_browsing_on_github=true
max_history=50
```

In this setup, the generic `agent` config is the default, the others have user-defined names: preconfigured agents for various experiments. When starting main.py, we can include it on the command line, like `main.py -l 'gpt-4o' --agentconfig 'browse'`. This will override any attribute from the generic 'agent' (or default in config.py) with attributes in 'browse'.

**Do you have thoughts on the technical implementation?**
Similar to LLMConfig.

**Alternatives**
I'm not sure if the memory-related vars as exemplified above are more of "an agent thing" or a general "memory thing", e.g. max_history, summarize_delegates. I suppose an alternative is to split `memory` from `llm` for memory configs. Does it make sense to make those per agent, will they really differ per agent?

**Additional context**
What other things do we want to test for an agent setup or per agent?

**Comment by mamoodi** [comment]
@enyst with the recent changes @li-boxuan did, does it address this issue?

**Comment by enyst** [comment]
I think it's solved, thanks.
