### ISSUE TITLE
Automatic reconnection after websocket disconnects

### ISSUE THREAD

**Issue by universea** [OpenDevin/OpenDevin#235]
**What problem or use case are you trying to solve?**

Client websocket always disconnected

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

Maybe autodetect the connection status and reconnect the server

**Describe alternatives you've considered**

**Additional context**

Error sending data to client 
Error sending data to client 
Client websocket disconnected (<CloseCode.ABNORMAL_CLOSURE: 1006>, None)
INFO:     connection closed

<img width="433" alt="1711513841377" src="https://github.com/OpenDevin/OpenDevin/assets/13444641/13031484-465a-40e0-bb73-fe79b88514e3">

**Comment by Toasterme** [comment]
Got the same error, WSL2 under Windows 11

**Comment by lowlyocean** [comment]
"Error sending data to client" shows up for me after a few Steps. I see more steps being performed once this happens, but from then on, the UI no longer updates. 

Environment is WSL2, Windows 11, using Ollama model

**Comment by rbren** [comment]
Fixed now!
