### ISSUE TITLE
[Agent]: Incorporate agent based on moatless tools

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#2353]
**What problem or use case are you trying to solve?**

[Moatless tools](https://github.com/aorwall/moatless-tools) gets 23% pass rate on swe-bench at a very low cost with gpt-4, it'd be great to get it into OpenDevin's agent hub: https://github.com/aorwall/moatless-tools

**Additional context**

* [SWE-Bench results](https://github.com/swe-bench/experiments/pull/17)

**Comment by ryanhoangt** [comment]
Hi @neubig, I'm interested in this one, can give it a shot!

**Comment by 0xdevalias** [comment]
Seems there's a refined set of results in a new PR too:

- https://github.com/swe-bench/experiments/pull/17
- https://github.com/swe-bench/experiments/pull/24

Seemingly improves from 70 -> 74 solved issues; which would bring it up from 23.33% to 24.67% on SWE-bench lite.
