### ISSUE TITLE
how can i browse any website for information with opendevin 

### ISSUE THREAD

**Issue by rishi8011** [OpenDevin/OpenDevin#2354]
@li-boxuan @mroch @jeremi 

 i have tried to browse the webpages of documentation but it didn't it just get stuck in a loop 
 
 can anyone guide me how to do it ??

**Comment by enyst** [comment]
Can you please explain a bit what agent were you using, and what the agent did exactly? Or better, do you have some logs?

**Comment by rishi8011** [comment]
i am using groq with browsing agent . i have also tried gpt-4o but it is not able browse the documentation of framework or any other info like i have tried with crewai framework docs but i didn't gather info instead it shows unexcepted error occur

i just restart the terminal so all logs ae gone now .

**Comment by mamoodi** [comment]
Going to close this issue as will not do as it does not have enough information.
If you run into this issue again, please make sure you click the "thumbs down" button as neubig has mentioned and feel free to open a new issue with more logs and information.
