### ISSUE TITLE
[Bug]: "OpenDevin SWE-Bench Output Visualizer" failed when `Select all`

### ISSUE THREAD

**Issue by Felix-Zhenghao** [OpenDevin/OpenDevin#2358]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

1. Just go to this [link](https://huggingface.co/spaces/OpenDevin/evaluation)
2. Go to the 'SWE-Bench-Visualizer'
3. Choose `Select all` and the 'Aggregated stats' part can't show.

The error:
```
AttributeError: 'float' object has no attribute 'get'
Traceback:
File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
File "/home/user/app/pages/1_🔎_SWEBench_Visualizer.py", line 66, in <module>
    stats_df = agg_stats(df)
File "/home/user/app/utils/swe_bench.py", line 114, in agg_stats
    cost = metrics.get('accumulated_cost', None)
```

Only when you choose like this, you can get aggregated stats:
![image](https://github.com/OpenDevin/OpenDevin/assets/131735752/53b283f4-683a-4d93-b47c-739fac071cf4)

### Current OpenDevin version

```bash
0.6.2
```

### Installation and Configuration

```bash
The problem exists in the data visualizer of SWE Benchmark.
```

### Reproduction Steps

1. Just go to this [link](https://huggingface.co/spaces/OpenDevin/evaluation)
2. Go to the 'SWE-Bench-Visualizer'
3. Choose `Select all` and the 'Aggregated stats' part can't show.

**Comment by SmartManoj** [comment]
Where did you get that error?

**Comment by SmartManoj** [comment]
Error in huggingface?
![image](https://github.com/OpenDevin/OpenDevin/assets/7231077/8e3f0959-f8a3-40ea-a9b1-468ab4541325)

**Comment by Felix-Zhenghao** [comment]
Yes. BTW the code for visualization is hosted by us or huggingface?

**Comment by tobitege** [comment]
> Yes. BTW the code for visualization is hosted by us or huggingface?

gpt4o to the rescue lol
`Here's how they work together:

    Source Code on GitHub: When you deploy a Hugging Face Space, you typically link it to a GitHub repository. This repository contains the source code for your project, including the model files, scripts, and any other necessary files.
    Deployment on Hugging Face: Hugging Face Spaces then takes your source code from GitHub and builds a running environment for your project. This means the actual running code and model are hosted on Hugging Face's servers.
    Access and Collaboration: You can still access and edit the source code in your GitHub repository. Any changes you make will be reflected in the Hugging Face Space when you redeploy it.`

So if your link goes to HF spaces, it is a deployment on their server.
But the issue on first look appears to be an OpenDevin issue as "metrics" seems to be None.

**Comment by SmartManoj** [comment]
> "metrics" seems to be None.

No, it is a `float` but it should be a dictionary.
