### ISSUE TITLE
[Feature]: Create a default `config.template.toml` to help people quickly on-board

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#2361]
**Describe the UX of the solution you'd like**

Create a default template of `config.toml` with all the common config configurations with explanations to help people onboard quickly. They just need to rename `config.template.toml` to `config.toml` and customize it to their needs.

It should ideally contain examples of:
- different sandbox configurations
- sandbox env var settings
- local LLM / examples of using different LLM providers

EDIT: suggest by @SmartManoj , we should use `config.toml.template` instead

**Comment by SmartManoj** [comment]
When renaming a configuration file template in Visual Studio Code, using the naming convention `config.toml.template` allows for a straightforward renaming process.
When you initiate the rename action (through command palette -> rename or F2 in explorer), only the `config.toml` portion of the filename is selected by default. This makes it easy to remove the `.template` suffix by using `Right -> Shift + End -> Delete`
This method leverages the default selection behavior in Visual Studio Code, making the renaming quick and efficient.

**Comment by Shimada666** [comment]
If the template needs to contain all the example, I am a little worried that there are too many configuration items...
I am not against creating template file, but I personally prefer to use interactive tools to generate config files, just like what we are doing now. An ideal situation is that we can completely allow users to use interactive tools to configure everything.

**Comment by xingyaoww** [comment]
Resolved by https://github.com/OpenDevin/OpenDevin/pull/2736
