### ISSUE TITLE
Feat: Agentskills - enhancement suggestions for  command descriptions from LLM itself

### ISSUE THREAD

**Issue by tobitege** [OpenDevin/OpenDevin#2378]
### What problem or use case are you trying to solve?

As title says, I kindly asked ChatGPT4o:
"_Any recommendations on the commands descriptions that would make it easier for YOU to instantly know what they do? we want to improve the interactions with you._"

The answers themselves indicate that with little tweaks we could prevent misconceptions on side of the LLM's.

### Answer:

_Thank you for considering improvements to the command descriptions! Here are some suggestions to make the descriptions even clearer and more intuitive for me:_

1. **create_file**
   - **Current Description:** Creates and opens a new file with the given name.
   - **Suggested Description:** Creates and opens a new file with the specified name. Useful for starting new projects or adding new files.

2. **edit_file**
   - **Current Description:** Edit a file. It replaces lines `start` through `end` (inclusive) with the given text `content` in the open file.
   - **Suggested Description:** Replaces lines `start` through `end` (inclusive) with the specified `content` in the open file. Ideal for modifying existing code or text.

3. **open_file**
   - **Current Description:** Opens the file at the given path in the editor. If line_number is provided, the window will be moved to include that line.
   - **Suggested Description:** Opens the specified file in the editor. Optionally, move to a specific line number for quick access.

4. **goto_line**
   - **Current Description:** Moves the window to show the specified line number.
   - **Suggested Description:** Jumps to the specified line number in the open file. Useful for quick navigation.

5. **scroll_down**
   - **Current Description:** Moves the window down by 100 lines.
   - **Suggested Description:** Scrolls down by 100 lines in the open file. Useful for viewing more content without editing.

6. **scroll_up**
   - **Current Description:** Moves the window up by 100 lines.
   - **Suggested Description:** Scrolls up by 100 lines in the open file. Useful for reviewing previous content without editing.

7. **search_dir**
   - **Current Description:** Searches for search_term in all files in dir. If dir is not provided, searches in the current directory.
   - **Suggested Description:** Searches for the specified term in all files within the given directory. Defaults to the current directory if none is provided.

8. **search_file**
   - **Current Description:** Searches for search_term in file. If file is not provided, searches in the current open file.
   - **Suggested Description:** Searches for the specified term in the given file. Defaults to the current open file if none is provided.

9. **find_file**
   - **Current Description:** Finds all files with the given name in the specified directory.
   - **Suggested Description:** Locates all files with the specified name within the given directory. Useful for quickly finding specific files.

10. **parse_pdf**
    - **Current Description:** Parses the content of a PDF file and prints it.
    - **Suggested Description:** Extracts and prints the content of the specified PDF file. Useful for reading and analyzing PDF documents.

11. **parse_docx**
    - **Current Description:** Parses the content of a DOCX file and prints it.
    - **Suggested Description:** Extracts and prints the content of the specified DOCX file. Useful for reading and analyzing Word documents.

12. **parse_latex**
    - **Current Description:** Parses the content of a LaTex file and prints it.
    - **Suggested Description:** Extracts and prints the content of the specified LaTeX file. Useful for reading and analyzing LaTeX documents.

13. **parse_pptx**
    - **Current Description:** Parses the content of a pptx file and prints it.
    - **Suggested Description:** Extracts and prints the content of the specified PowerPoint file. Useful for reading and analyzing presentations.

_These suggestions aim to make the purpose and utility of each command immediately clear, enhancing the interaction experience._

**Comment by enyst** [comment]
I don't know if it's so, but Claude-3-opus agrees. 😅 

> _In your workplace, there is a file named agentskill_descriptions. Read it. It contains your own agent skills descriptions! For each skill, analyze and tell me which description is better for you, which helps you be good._

> ...
> scroll_down / scroll_up
The Large Descriptions are better by specifying these are for viewing content without editing.
> ...
> The Large Descriptions are consistently better by specifying the file types and explaining these are useful for reading and analyzing the content of those document formats.
In summary, the Large Descriptions tend to provide more context and explain the purpose/value of each skill more clearly. This additional information helps me better understand when and how to apply the skills to assist users effectively. The Small Descriptions are more concise but the Large ones are more informative.

(I bet it'd say the same for many other purposes, though, simply because it contains extra info 🤷)

**Comment by tobitege** [comment]
I just need to find the time and a stable agentskills to do this.

**Comment by enyst** [comment]
FWIW, it seems possible to me that these don't help precisely because the LLM happily offers them. It's an autocomplete machine, after all, it gives us what has high probability to follow after the short descriptions, so to speak, in which case these "suggestions" would be how it interprets anyway. Just a thought! 🤷‍♂️

**Comment by tobitege** [comment]
From my own experience, the default prompt needs more pointed suggestions for the LLM, especially with regard to file editing.
I'll close this one.
