### ISSUE TITLE
add agent pair to directory_class_pairs variable in run.sh  key is the directory name in /agenthub and value is the class name 

### ISSUE THREAD

**Issue by Dadas123456** [OpenDevin/OpenDevin#238]
**What problem or use case are you trying to solve?**

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by rbren** [comment]
@Dadas123456 can you fill out the template? I'm not sure what this refers to
