### ISSUE TITLE
[Bug]: run with poetry in CodeAct1.3 branch documents

### ISSUE THREAD

**Issue by lwaekfjlk** [OpenDevin/OpenDevin#2396]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

https://github.com/OpenDevin/OpenDevin/tree/codeact_1.3_swebench/evaluation/swe_bench In this document, we actually need to run `poetry run python evaluation/swe_bench/swe_env_box.py`, right? Is this a bug in this branch or I understand something run.

### Current OpenDevin version

```bash
ghcr.io/opendevin/eval-swe-bench:full-v1.0
```

### Installation and Configuration

```bash
/
```

**Comment by SmartManoj** [comment]
Yes.

**Comment by lwaekfjlk** [comment]
gotcha
