### ISSUE TITLE
Memgpt and OpenDevin Collaboration 

### ISSUE THREAD

**Issue by SupercaliG** [OpenDevin/OpenDevin#2417]
I feel that a Memgpt and OpenDevin collab would be awesome. If we could have features from both programs in one that would be awesome. Is there a way to embed documents for the agents to refer to yet? Kind of how AnythingLLM works? I assume this is some kind of "post tuning" superpower.

**Comment by neubig** [comment]
Woops, it looks like this is a duplicate with #530 I'll close this but we can continue the discussion there.

**Comment by 0xdevalias** [comment]
Now moved to:

- https://github.com/OpenDevin/OpenDevin/issues/2487
