### ISSUE TITLE
[Enhancement]: Store the user's name and email in local storage after submitting feedback

### ISSUE THREAD

**Issue by amanape** [OpenDevin/OpenDevin#2420]
**What problem or use case are you trying to solve?**
The user always has to enter their name and email every time they wish to submit feedback.

**Describe the UX of the solution you'd like**
Store the relevant information in local storage

**Do you have thoughts on the technical implementation?**
Store the relevant information in local storage

**Describe alternatives you've considered**

**Additional context**

**Comment by tobitege** [comment]
I'd wait for this till we actually have user accounts. Right now OpenDevin could be run on e.g. shared PC's and I'd rather have the user enter their email again and not find someone else's email pre-filled.

**Comment by amanape** [comment]
@tobitege Actually, I was now thinking of storing the email in local storage so we can set value so the user does not have to re-enter it when they open the feedback modal. That way, the user will still see the privacy statement, they just don't have to set their email every time.

What do you think?

**Comment by tobitege** [comment]
I understand the intent and I have no objections to it - if OpenDevin had distinct user accounts.
So it is more whether we care if OpenDevin is accessed by different users and it remembers potentially an email address of someone else?

**Comment by tobitege** [comment]
Just as one possible scenario: a parent lets their kid use OpenDevin and might not supervise every step.
There is no way for the parent to a) disable any feedback and b) prevent the use of their email if its alread pre-filled.
Above might actually raise another issue or two by itself, but that's my thinking about it.

**Comment by amanape** [comment]
Setting up an auth provider is way too much work (verify email, set password, change password, GDPR delete account, request info, etc...) for little value right now.

> Just as one possible scenario: a parent lets their kid use OpenDevin and might not supervise every step.
There is no way for the parent to a) disable any feedback and b) prevent the use of their email if its alread pre-filled.
Above might actually raise another issue or two by itself, but that's my thinking about it.

Actually, now that I think of it, I'm not sure if requiring the user to share their email is entirely necessary. Maybe we can do without it for now and send it anonymized until we see a more solid requirements for it (e.g., responding to the user that shared the feedback for some reason)

**Comment by mamoodi** [comment]
@amanape is this issue now "Allow user to send feedback while optionally providing email"?

**Comment by amanape** [comment]
This issue is actually completed. I didn't realize it was already implemented
