### ISSUE TITLE
[Bug]: Unable to use cohere command LLM

### ISSUE THREAD

**Issue by SupercaliG** [OpenDevin/OpenDevin#2421]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

14:59:15 - opendevin:ERROR: llm.py:173 - BedrockException - bedrock does not support parameters: {'top_p': 0.5, 'stop': ['</execute_ipython>', '</execute_bash>', '</execute_browse>']}, for model=cohere.command-r-plus-v1:0. To drop these, set `litellm.drop_params=True` or for proxy:

`litellm_settings:
 drop_params: true`
. Attempt #3 | You can customize these settings in the configuration.

### Current OpenDevin version

```bash
Running in Docker with the latest OpenDevin version.
```

### Installation and Configuration

```bash
I tried this setup:
docker run -it `
    --pull=always `
    -e SANDBOX_USER_ID=1000 `
    -e LLM_RETRY_MIN_WAIT=20 `
    -e LLM_NUM_RETRIES=15 `
    -e PERSIST_SANDBOX="true" `
    -e SSH_PASSWORD="password" `
    -e WORKSPACE_MOUNT_PATH=$env:OPENDEVIN_WORKSPACE `
    -e LLM_API_KEY="ollama" `
    -e LLM_BASE_URL="http://host.docker.internal:11434" `
    -e LITELLM_DROP_PARAMS=true `
    -e LITELLM_VERBOSE=true `
    -v $env:OPENDEVIN_WORKSPACE:/opt/workspace_base `
    -v /var/run/docker.sock:/var/run/docker.sock `
    -p 3000:3000 `
    --add-host host.docker.internal:host-gateway `
    --name opendevin-app-$(Get-Date -Format "yyyyMMddHHmmss") `
    ghcr.io/opendevin/opendevin:0.6
```

### Model and Agent

Cohere Command R Plus

### Operating System

Windows 11 with WSL

**Comment by SupercaliG** [comment]
Correction this is the docker command, the above uses ollama for local use:
docker run -it `
    --pull=always `
    -e SANDBOX_USER_ID=1000 `
    -e PERSIST_SANDBOX="true" `
    -e SSH_PASSWORD="password" `
    -e WORKSPACE_MOUNT_PATH=$env:OPENDEVIN_WORKSPACE `
    -v $env:OPENDEVIN_WORKSPACE:/opt/workspace_base `
    -v /var/run/docker.sock:/var/run/docker.sock `
    -p 3000:3000 `
    --add-host host.docker.internal:host-gateway `
    --name opendevin-app-$(Get-Date -Format "yyyyMMddHHmmss") `
    ghcr.io/opendevin/opendevin:0.6

**Comment by SmartManoj** [comment]
Could you run this?
https://litellm.vercel.app/docs/providers/bedrock#set-temperature-top-p-etc

**Comment by SmartManoj** [comment]
https://github.com/OpenDevin/OpenDevin/blob/90ec0095dfe72e30114e093f2dc27c6bc75e8140/opendevin/llm/llm.py
```py
import litellm
litellm.drop_params=True
```
Add these 2 lines in here and check

**Comment by SupercaliG** [comment]
> https://github.com/OpenDevin/OpenDevin/blob/90ec0095dfe72e30114e093f2dc27c6bc75e8140/opendevin/llm/llm.py
> 
> ```python
> import litellm
> litellm.drop_params=True
> ```
> 
> Add these 2 lines in here and check

How would I do this with the docker setup?

**Comment by SmartManoj** [comment]
Could you pass `-e LITELLM_DROP_PARAMS="true"`?

https://github.com/BerriAI/litellm/blob/3a35a58859a145a4a568548316a1930340e7440a/litellm/__init__.py#L76
