### ISSUE TITLE
Github codespace

### ISSUE THREAD

**Issue by rezzie-rich** [OpenDevin/OpenDevin#2428]
Along with the next release, can we please get a 'github codespace' version like the swe-agent? It would be awesome if opendevin could be used from mobile.

**Comment by SmartManoj** [comment]
You can create one manually at https://github.com/codespaces/new

![image](https://github.com/OpenDevin/OpenDevin/assets/7231077/2967b041-d9ad-42e0-8ac7-75264d9b9528)

**Comment by rezzie-rich** [comment]
awsome, thank you

**Comment by SmartManoj** [comment]
https://github.com/OpenDevin/OpenDevin/pull/2975

**Comment by SmartManoj** [comment]
You can use this tab.
![image](https://github.com/user-attachments/assets/aaaa7e25-72b0-458c-8385-28d6c37b7463)


CC: @neubig
