### ISSUE TITLE
My local ollama models do not show in the dropdown. 

### ISSUE THREAD

**Issue by SmartManoj** [OpenDevin/OpenDevin#2432]
My local ollama models do not show in the dropdown. According to ollama logs opendevin does not even query the ollama server:

```
#!/bin/bash

OPENDEVIN_WORKSPACE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e PERSIST_SANDBOX="true" \
    -e SSH_PASSWORD="make something up here" \
    -e WORKSPACE_MOUNT_PATH=$OPENDEVIN_WORKSPACE \
    -e TRANSFORMERS_CACHE=/opt/hf_cache \
    -e HF_HOME=/opt/hf_cache \
    -e LLM_API_KEY="ollama" \
    -e LLM_MODEL"ollama/codestral:22b-test" \
    -e LLM_BASE_URL="http://host.docker.internal:11434" \
    -v $OPENDEVIN_WORKSPACE:/opt/workspace_base \
    -v hf_cache:/opt/hf_cache \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:main
```

_Originally posted by @bendavis78 in https://github.com/OpenDevin/OpenDevin/issues/1981#issuecomment-2167101266_

**Comment by Umpire2018** [comment]
From [here](https://opendevin.github.io/OpenDevin/modules/usage/llms/localLLMs#select-your-model)

>In the OpenDevin UI, click on the Settings wheel in the bottom-left corner. Then in the Model input, enter ollama/codellama:7b, or the name of the model you pulled earlier. If it doesn’t show up in a dropdown, that’s fine, just type it in. Click Save when you’re done.

I don't think this issue need to be worried about. Currently, we rely on `litellm` to acquire full list of models, it may be slow to include all the models in the market.

```python
@app.get('/api/options/models')
async def get_litellm_models():
    """
    Get all models supported by LiteLLM.

    To get the models:
    ```sh
    curl http://localhost:3000/api/litellm-models
    ```
    """
    litellm_model_list = litellm.model_list + list(litellm.model_cost.keys())
    litellm_model_list_without_bedrock = bedrock.remove_error_modelId(
        litellm_model_list
    )
    bedrock_model_list = bedrock.list_foundation_models()
    model_list = litellm_model_list_without_bedrock + bedrock_model_list

    return list(sorted(set(model_list)))
```
