### ISSUE TITLE
Document command line usage

### ISSUE THREAD

**Issue by josephykwang** [OpenDevin/OpenDevin#245]
**What problem or use case are you trying to solve?**
for swe integration, we need cli integration

**Describe the UX of the solution you'd like**
command line

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by rbren** [comment]
You can run OpenDevin on the command line like this:
```
python opendevin/main.py -d ./workspace/ -i 100 -t "Write a tic tac toe command line app"
```

**Comment by josephykwang** [comment]
OpenDevin % python opendevin/main.py -d ./workspace/ -i 100 -t "Write a tic tac toe command line app"




Traceback (most recent call last):

  File "/Users/jwang/Documents/workspace/OpenDevin/opendevin/main.py", line 6, in <module>

    import agenthub # noqa F401 (we import this to get the agents registered)

    ^^^^^^^^^^^^^^^

ModuleNotFoundError: No module named 'agenthub'


    On Wednesday, March 27, 2024 at 06:45:04 AM PDT, Robert Brennan ***@***.***> wrote:  
 
 


You can run OpenDevin on the command line like this:
python opendevin/main.py -d ./workspace/ -i 100 -t "Write a tic tac toe command line app"

**Comment by rbren** [comment]
I never understand why and when this is necessary, but
```
export PYTHONPATH=`pwd`
```
should fix this problem
