### ISSUE TITLE
[Bug]: Huggingface evaluation benchmark for SWE-Bench Visualizer shows 'AttributeError'

### ISSUE THREAD

**Issue by pyrytakala** [OpenDevin/OpenDevin#2467]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Visiting https://huggingface.co/spaces/OpenDevin/evaluation yields currently for SWE-Bench visualizer
`AttributeError: 'NoneType' object has no attribute 'keys'`.

It works fine for the MINT-Benchmark. 

The spaces are referenced at https://github.com/OpenDevin/OpenDevin/blob/main/evaluation/README.md so I would expect both to visualize correctly.

### Current OpenDevin version

```bash
not relevant
```

### Installation and Configuration

```bash
not relevant
```

**Comment by mamoodi** [comment]
@xingyaoww mind taking a quick peek at this when you're able please?

**Comment by xingyaoww** [comment]
Can you provide a screenshot if it still doesn't work for you? I remember this was an issue a few weeks ago, but we should have already fixed it. Feel free to re-open if this still does not work for you!
