### ISSUE TITLE
[Bug]: OpenDevin reports unexpected error when credit balance is finished

### ISSUE THREAD

**Issue by PaoloC68** [OpenDevin/OpenDevin#2494]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Error messages from openai don't get relayed 

### Current OpenDevin version

```bash
0.6
```

### Installation and Configuration

```bash
docker run -it     --pull=always     -e SANDBOX_USER_ID=$(id -u)     -e PERSIST_SANDBOX="true"     -e SSH_PASSWORD="password"     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE -e MAX_CHARS=50000000    -v $WORKSPACE_BASE:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     --add-host host.docker.internal:host-gateway     --name opendevin-app-$(date +%Y%m%d%H%M%S)     ghcr.io/opendevin/opendevin:0.6
```

### Model and Agent

Openai:Gpt4o

### Operating System

Windows

### Reproduction Steps

There was an unexpected error while running the agent, I finished my credit balance, but I was able to see that only in the dockers logs, I think you should relay this error messages to the user in a clearer way

### Logs, Errors, Screenshots, and Additional Context

sorry, didn't capture the log, yet the error of exausted credit was there

**Comment by enyst** [comment]
Thank you for the report! This issue isn’t yet addressed, but it’s tracked in https://github.com/OpenDevin/OpenDevin/issues/1451.

I’m going to close this as duplicate, but please take a look at that issue and let us know what you think!
