### ISSUE TITLE
Create RepoPilot Agent

### ISSUE THREAD

**Issue by huyphan168** [OpenDevin/OpenDevin#25]
It seems that Devin is based on multi-agent system, we at FSoft AI Center, proposed [RepoPilot](https://github.com/FSoft-AI4Code/RepoPilot) few months ago for repo-level code understanding. Adding some components like web browsing, test execution might be valuable on top of RepoPilot.

**Comment by ryanmoriarty-lee** [comment]
it looks good, is it like bloop ai?

**Comment by rbren** [comment]
Hey @huyphan168, thanks for the suggestion! We're creating a library of agents in the `/agenthub` directory--feel free to contribute something based on RepoPilot!

**Comment by huybery** [comment]
@huyphan168 Good idea and feel free to discuss this with us at slack! I'll close the issue and keep it simple, you can reopen it later.
