### ISSUE TITLE
[Bug]: Agent encountered an error.

### ISSUE THREAD

**Issue by graemefan** [OpenDevin/OpenDevin#2511]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

hi, just installed OpenDevin following instructions. On my first prompt once the agent was initialised, the message 'Agent encountered an error' was immediately returned in the message bar at the bottom of the interface. 

I have tried this several times and the same error message is returned. 

<img width="284" alt="Screenshot 2024-06-19 at 11 38 13 AM" src="https://github.com/OpenDevin/OpenDevin/assets/160987571/8ffa71b3-7114-4632-9dbe-1060d7de7aa0">

 

### Current OpenDevin version

```bash
ghcr.io/opendevin/opendevin:0.6.2
```

### Installation and Configuration

```bash
I've simply completed the steps outlined per the readme.md file.
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e PERSIST_SANDBOX="true" \
    -e SSH_PASSWORD="make something up here" \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.6.2
```

### Model and Agent

gpt-3.5-turbo-instruct
gpt-4

CodeActAgent

### Operating System

Mac OS, Apple M2 Pro, 16 GB, Sonoma 14.5

### Reproduction Steps

"Hi"

### Logs, Errors, Screenshots, and Additional Context

I have checked log file in logs directory and it is an empty file.

**Comment by graemefan** [comment]
apologies, I should have added this screenshot too.
<img width="483" alt="Screenshot 2024-06-19 at 11 46 08 AM" src="https://github.com/OpenDevin/OpenDevin/assets/160987571/7f46ce1c-c710-4639-bd73-bb3de258edf7">

**Comment by SmartManoj** [comment]
Could you provide the logs too?

**Comment by graemefan** [comment]
My sincere apologies! I did not think to look there. Here is the most recent snippet (which states invalid OpenAI key, but I know it is valid as I am using it elsewhere):

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/opendevin/controller/agent_controller.py", line 130, in _start_step_loop
    await self._step()
  File "/app/opendevin/controller/agent_controller.py", line 290, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agenthub/codeact_agent/codeact_agent.py", line 228, in step
    response = self.llm.do_completion(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 217, in do_completion
    resp = self._completion(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 330, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 467, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 390, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 470, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 197, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 3415, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 3306, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2447, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 9989, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 8658, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: AuthenticationError: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: UXWRgUlq************************************CX6V. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

Attached are the log files in OpenDevin/logs:
[opendevin_2024-06-19.log](https://github.com/user-attachments/files/15894794/opendevin_2024-06-19.log)

**Comment by SmartManoj** [comment]
Could you run this to check whether the API is working properly?

```python
from litellm import completion
from datetime import datetime
import os

if os.path.exists('config.toml'):
    from toml import load
    config = load('config.toml')
else:
    config = {
        'LLM_MODEL': 'gpt-4-turbo-2024-04-09',
        'LLM_API_KEY': 'your-api-key',
        'LLM_BASE_URL': None
    }

messages = [{ "content": "If there are 10 books in a room and I read 2, how many books are still in the room?","role": "user"}]
dt = datetime.now()
response = completion(model=config['LLM_MODEL'], 
                        api_key=config['LLM_API_KEY'],
                        base_url=config['LLM_BASE_URL'],
                      messages=messages)

content = response.choices[0].message.content
print(content)

if '8' in content:
    print('--> Correct answer! 🎉')
    print('There are still 10 books in the room; reading them does not reduce the count. Consider exploring more accurate models for better results.')

dt2 = datetime.now()
print('Used model:',config['LLM_MODEL'])
print(f"Time taken: {(dt2-dt).total_seconds():.1f}s")
```

**Comment by graemefan** [comment]
Hi! Where would you like me to run that?

**Comment by SmartManoj** [comment]
Anywhere.

**Comment by graemefan** [comment]
Here is the output:
---------------------------------------------------------------------------
AuthenticationError                       Traceback (most recent call last)
File [/opt/anaconda3/lib/python3.11/site-packages/litellm/llms/openai.py:799](http://localhost:8888/opt/anaconda3/lib/python3.11/site-packages/litellm/llms/openai.py#line=798), in OpenAIChatCompletion.completion(self, model_response, timeout, optional_params, model, messages, print_verbose, api_key, api_base, acompletion, logging_obj, litellm_params, logger_fn, headers, custom_prompt_dict, client, organization, custom_llm_provider)
    798             else:
--> 799                 raise e
    800 except OpenAIError as e:

File [/opt/anaconda3/lib/python3.11/site-packages/litellm/llms/openai.py:758](http://localhost:8888/opt/anaconda3/lib/python3.11/site-packages/litellm/llms/openai.py#line=757), in OpenAIChatCompletion.completion(self, model_response, timeout, optional_params, model, messages, print_verbose, api_key, api_base, acompletion, logging_obj, litellm_params, logger_fn, headers, custom_prompt_dict, client, organization, custom_llm_provider)
    747 logging_obj.pre_call(
    748     input=messages,
    749     api_key=openai_client.api_key,
   (...)
    755     },
    756 )
--> 758 response = openai_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
    759 stringified_response = response.model_dump()

File [/opt/anaconda3/lib/python3.11/site-packages/openai/_utils/_utils.py:277](http://localhost:8888/opt/anaconda3/lib/python3.11/site-packages/openai/_utils/_utils.py#line=276), in required_args.<locals>.inner.<locals>.wrapper(*args, **kwargs)
    276     raise TypeError(msg)
--> 277 return func(*args, **kwargs)

File [/opt/anaconda3/lib/python3.11/site-packages/openai/resources/chat/completions.py:590](http://localhost:8888/opt/anaconda3/lib/python3.11/site-packages/openai/resources/chat/completions.py#line=589), in Completions.create(self, messages, model, frequency_penalty, function_call, functions, logit_bias, logprobs, max_tokens, n, presence_penalty, response_format, seed, stop, stream, stream_options, temperature, tool_choice, tools, top_logprobs, top_p, user, extra_headers, extra_query, extra_body, timeout)
    558 @required_args(["messages", "model"], ["messages", "model", "stream"])
    559 def create(
    560     self,
   (...)
    588     timeout: float | httpx.Timeout | None | NotGiven = NOT_GIVEN,
    589 ) -> ChatCompletion | Stream[ChatCompletionChunk]:
--> 590     return self._post(
    591         "[/chat/completions](http://localhost:8888/chat/completions)",
    592         body=maybe_transform(
    593             {
    594                 "messages": messages,
    595                 "model": model,
    596                 "frequency_penalty": frequency_penalty,
    597                 "function_call": function_call,
    598                 "functions": functions,
    599                 "logit_bias": logit_bias,
    600                 "logprobs": logprobs,
    601                 "max_tokens": max_tokens,
    602                 "n": n,
    603                 "presence_penalty": presence_penalty,
    604                 "response_format": response_format,
    605                 "seed": seed,
    606                 "stop": stop,
    607                 "stream": stream,
    608                 "stream_options": stream_options,
    609                 "temperature": temperature,
    610                 "tool_choice": tool_choice,
    611                 "tools": tools,
    612                 "top_logprobs": top_logprobs,
    613                 "top_p": top_p,
    614                 "user": user,
    615             },
    616             completion_create_params.CompletionCreateParams,
    617         ),
    618         options=make_request_options(
    619             extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
    620         ),
    621         cast_to=ChatCompletion,
    622         stream=stream or False,
    623         stream_cls=Stream[ChatCompletionChunk],
    624     )

File [/opt/anaconda3/lib/python3.11/site-packages/openai/_base_client.py:1240](http://localhost:8888/opt/anaconda3/lib/python3.11/site-packages/openai/_base_client.py#line=1239), in SyncAPIClient.post(self, path, cast_to, body, options, files, stream, stream_cls)
   1237 opts = FinalRequestOptions.construct(
   1238     method="post", url=path, json_data=body, files=to_httpx_files(files), **options
   1239 )
-> 1240 return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))

File [/opt/anaconda3/lib/python3.11/site-packages/openai/_base_client.py:921](http://localhost:8888/opt/anaconda3/lib/python3.11/site-packages/openai/_base_client.py#line=920), in SyncAPIClient.request(self, cast_to, options, remaining_retries, stream, stream_cls)
    912 def request(
    913     self,
    914     cast_to: Type[ResponseT],
   (...)
    919     stream_cls: type[_StreamT] | None = None,
    920 ) -> ResponseT | _StreamT:
--> 921     return self._request(
    922         cast_to=cast_to,
    923         options=options,
    924         stream=stream,
    925         stream_cls=stream_cls,
    926         remaining_retries=remaining_retries,
    927     )

File [/opt/anaconda3/lib/python3.11/site-packages/openai/_base_client.py:1020](http://localhost:8888/opt/anaconda3/lib/python3.11/site-packages/openai/_base_client.py#line=1019), in SyncAPIClient._request(self, cast_to, options, remaining_retries, stream, stream_cls)
   1019     log.debug("Re-raising status error")
-> 1020     raise self._make_status_error_from_response(err.response) from None
   1022 return self._process_response(
   1023     cast_to=cast_to,
   1024     options=options,
   (...)
   1027     stream_cls=stream_cls,
   1028 )

AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: UXWRgUlq************************************CX6V. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

OpenAIError                               Traceback (most recent call last)
File /opt/anaconda3/lib/python3.11/site-packages/litellm/main.py:1157, in completion(model, messages, timeout, temperature, top_p, n, stream, stream_options, stop, max_tokens, presence_penalty, frequency_penalty, logit_bias, user, response_format, seed, tools, tool_choice, logprobs, top_logprobs, deployment_id, extra_headers, functions, function_call, base_url, api_version, api_key, model_list, **kwargs)
   1151     logging.post_call(
   1152         input=messages,
   1153         api_key=api_key,
   1154         original_response=str(e),
   1155         additional_args={"headers": headers},
   1156     )
-> 1157     raise e
   1159 if optional_params.get("stream", False):
   1160     ## LOGGING

File [/opt/anaconda3/lib/python3.11/site-packages/litellm/main.py:1130](http://localhost:8888/opt/anaconda3/lib/python3.11/site-packages/litellm/main.py#line=1129), in completion(model, messages, timeout, temperature, top_p, n, stream, stream_options, stop, max_tokens, presence_penalty, frequency_penalty, logit_bias, user, response_format, seed, tools, tool_choice, logprobs, top_logprobs, deployment_id, extra_headers, functions, function_call, base_url, api_version, api_key, model_list, **kwargs)
   1129 try:
-> 1130     response = openai_chat_completions.completion(
   1131         model=model,
   1132         messages=messages,
   1133         headers=headers,
   1134         model_response=model_response,
   1135         print_verbose=print_verbose,
   1136         api_key=api_key,
   1137         api_base=api_base,
   1138         acompletion=acompletion,
   1139         logging_obj=logging,
   1140         optional_params=optional_params,
   1141         litellm_params=litellm_params,
   1142         logger_fn=logger_fn,
   1143         timeout=timeout,  # type: ignore
   1144         custom_prompt_dict=custom_prompt_dict,
   1145         client=client,  # pass AsyncOpenAI, OpenAI client
   1146         organization=organization,
   1147         custom_llm_provider=custom_llm_provider,
   1148     )
   1149 except Exception as e:
   1150     ## LOGGING - log the original exception returned

File [/opt/anaconda3/lib/python3.11/site-packages/litellm/llms/openai.py:805](http://localhost:8888/opt/anaconda3/lib/python3.11/site-packages/litellm/llms/openai.py#line=804), in OpenAIChatCompletion.completion(self, model_response, timeout, optional_params, model, messages, print_verbose, api_key, api_base, acompletion, logging_obj, litellm_params, logger_fn, headers, custom_prompt_dict, client, organization, custom_llm_provider)
    804 if hasattr(e, "status_code"):
--> 805     raise OpenAIError(status_code=e.status_code, message=str(e))
    806 else:

OpenAIError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: UXWRgUlq************************************CX6V. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

AuthenticationError                       Traceback (most recent call last)
Cell In[2], line 17
     15 messages = [{ "content": "If there are 10 books in a room and I read 2, how many books are still in the room?","role": "user"}]
     16 dt = datetime.now()
---> 17 response = completion(model=config['LLM_MODEL'], 
     18                         api_key=config['LLM_API_KEY'],
     19                         base_url=config['LLM_BASE_URL'],
     20                       messages=messages)
     22 content = response.choices[0].message.content
     23 print(content)

File /opt/anaconda3/lib/python3.11/site-packages/litellm/utils.py:953, in client.<locals>.wrapper(*args, **kwargs)
    949         if (
    950             liteDebuggerClient and liteDebuggerClient.dashboard_url != None
    951         ):  # make it easy to get to the debugger logs if you've initialized it
    952             e.message += f"\n Check the log in your dashboard - {liteDebuggerClient.dashboard_url}"
--> 953 raise e

File [/opt/anaconda3/lib/python3.11/site-packages/litellm/utils.py:848](http://localhost:8888/opt/anaconda3/lib/python3.11/site-packages/litellm/utils.py#line=847), in client.<locals>.wrapper(*args, **kwargs)
    846         print_verbose(f"Error while checking max token limit: {str(e)}")
    847 # MODEL CALL
--> 848 result = original_function(*args, **kwargs)
    849 end_time = datetime.datetime.now()
    850 if "stream" in kwargs and kwargs["stream"] == True:

File [/opt/anaconda3/lib/python3.11/site-packages/litellm/main.py:2576](http://localhost:8888/opt/anaconda3/lib/python3.11/site-packages/litellm/main.py#line=2575), in completion(model, messages, timeout, temperature, top_p, n, stream, stream_options, stop, max_tokens, presence_penalty, frequency_penalty, logit_bias, user, response_format, seed, tools, tool_choice, logprobs, top_logprobs, deployment_id, extra_headers, functions, function_call, base_url, api_version, api_key, model_list, **kwargs)
   2573     return response
   2574 except Exception as e:
   2575     ## Map to OpenAI Exception
-> 2576     raise exception_type(
   2577         model=model,
   2578         custom_llm_provider=custom_llm_provider,
   2579         original_exception=e,
   2580         completion_kwargs=args,
   2581         extra_kwargs=kwargs,
   2582     )

File [/opt/anaconda3/lib/python3.11/site-packages/litellm/utils.py:7157](http://localhost:8888/opt/anaconda3/lib/python3.11/site-packages/litellm/utils.py#line=7156), in exception_type(model, original_exception, custom_llm_provider, completion_kwargs, extra_kwargs)
   7155 # don't let an error with mapping interrupt the user from receiving an error from the llm api calls
   7156 if exception_mapping_worked:
-> 7157     raise e
   7158 else:
   7159     raise APIConnectionError(
   7160         message="{}\n{}".format(original_exception, traceback.format_exc()),
   7161         llm_provider="",
   (...)
   7166         ),
   7167     )

File [/opt/anaconda3/lib/python3.11/site-packages/litellm/utils.py:5715](http://localhost:8888/opt/anaconda3/lib/python3.11/site-packages/litellm/utils.py#line=5714), in exception_type(model, original_exception, custom_llm_provider, completion_kwargs, extra_kwargs)
   5713 elif original_exception.status_code == 401:
   5714     exception_mapping_worked = True
-> 5715     raise AuthenticationError(
   5716         message=f"AuthenticationError: {exception_provider} - {message}",
   5717         llm_provider=custom_llm_provider,
   5718         model=model,
   5719         response=original_exception.response,
   5720         litellm_debug_info=extra_information,
   5721     )
   5722 elif original_exception.status_code == 404:
   5723     exception_mapping_worked = True

AuthenticationError: litellm.AuthenticationError: AuthenticationError: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: UXWRgUlq************************************CX6V. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

**Comment by SmartManoj** [comment]
> Incorrect API key provided:

Could you double check?

**Comment by tobitege** [comment]
> Error code: 401 - {'error': {'message': 'Incorrect API key provided: UXWRgUlq**_**_**_*********************CX6V.

That is not a valid API key, they start with "`sk-`".

**Comment by graemefan** [comment]
Thank you! Well spotted! I had accidentally truncated the api key when copying it from my environment file. I am very sorry to have 'wasted' your time. It is a simple fix and is currently returning some outputs. I will now try and become familiar with the interface. Thank you once again.

**Comment by tobitege** [comment]
Glad you got it running then, this happens. 😃 
Closing this for now.

**Comment by zhangshu0** [comment]
> 任何地方。

I prompted after running:

Traceback (most recent call last):
  File "/Users/zhangshuo147/PycharmProjects/OpenDevin/venv/lib/python3.9/site-packages/litellm/main.py", line 805, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
  File "/Users/zhangshuo147/PycharmProjects/OpenDevin/venv/lib/python3.9/site-packages/litellm/utils.py", line 4386, in get_llm_provider
    raise e
  File "/Users/zhangshuo147/PycharmProjects/OpenDevin/venv/lib/python3.9/site-packages/litellm/utils.py", line 4363, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=chatrhino/Chatrhino-14B
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangshuo147/PycharmProjects/OpenDevin/tests/test_connect.py", line 19, in <module>
    response = completion(model=config['LLM_MODEL'],
  File "/Users/zhangshuo147/PycharmProjects/OpenDevin/venv/lib/python3.9/site-packages/litellm/utils.py", line 1001, in wrapper
    raise e
  File "/Users/zhangshuo147/PycharmProjects/OpenDevin/venv/lib/python3.9/site-packages/litellm/utils.py", line 881, in wrapper
    result = original_function(*args, **kwargs)
  File "/Users/zhangshuo147/PycharmProjects/OpenDevin/venv/lib/python3.9/site-packages/litellm/main.py", line 2582, in completion
    raise exception_type(
  File "/Users/zhangshuo147/PycharmProjects/OpenDevin/venv/lib/python3.9/site-packages/litellm/utils.py", line 7644, in exception_type
    raise e
  File "/Users/zhangshuo147/PycharmProjects/OpenDevin/venv/lib/python3.9/site-packages/litellm/utils.py", line 7608, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=chatrhino/Chatrhino-14B
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
Traceback (most recent call last):
  File "/Users/zhangshuo147/PycharmProjects/OpenDevin/venv/lib/python3.9/site-packages/litellm/main.py", line 805, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
  File "/Users/zhangshuo147/PycharmProjects/OpenDevin/venv/lib/python3.9/site-packages/litellm/utils.py", line 4386, in get_llm_provider
    raise e
  File "/Users/zhangshuo147/PycharmProjects/OpenDevin/venv/lib/python3.9/site-packages/litellm/utils.py", line 4363, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=chatrhino/Chatrhino-14B
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

**Comment by zhangshu0** [comment]
> chatrhino/Chatrhino-14B

I have configured the connection of chatrino/chatrino-14B and apikey in config.toml. It is my private domain model and not in Ollama, but it is not in the default list of litellm. How should I connect it to opendevin
