### ISSUE TITLE
[Bug]: Its not working on Ollama

### ISSUE THREAD

**Issue by Woodenfather** [OpenDevin/OpenDevin#2517]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

It is not working with ollama on my setup. 

### Current OpenDevin version

```bash
0.6.2
```

### Installation and Configuration

```bash
woodenfather@GamingPC:~$ WORKSPACE_BASE="/mnt/c/Users/Abshe/OneDrive/Desktop/open-devin"
woodenfather@GamingPC:~$ docker run \
    -it \
    --pull=always \
    --add-host host.docker.internal:host-gateway \
    -e SANDBOX_USER_ID=$(id -u) \
    -e LLM_API_KEY="ollama" \
    -e LLM_BASE_URL="http://host.docker.internal:11434" \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 8000:3000 \
    ghcr.io/opendevin/opendevin:0.6.2
```

### Model and Agent

codellama:7b

CodeActAgent

### Operating System

windows 11 pro

### Reproduction Steps

use the docks on OpenDevin

### Logs, Errors, Screenshots, and Additional Context

woodenfather@GamingPC:~$ WORKSPACE_BASE="/mnt/c/Users/Abshe/OneDrive/Desktop/open-devin"
woodenfather@GamingPC:~$ docker run \
    -it \
    --pull=always \
    --add-host host.docker.internal:host-gateway \
    -e SANDBOX_USER_ID=$(id -u) \
    -e LLM_API_KEY="ollama" \
    -e LLM_BASE_URL="http://host.docker.internal:11434" \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 8000:3000 \
    ghcr.io/opendevin/opendevin:0.6.2
0.6.2: Pulling from opendevin/opendevin
Digest: sha256:cb0a82bbc1f595fdfd146e3a0c1f1d86434200fc1db31f25013832d1dd32d427
Status: Image is up to date for ghcr.io/opendevin/opendevin:0.6.2
Starting OpenDevin...
Setting up enduser with id 1000
Docker socket group id: 1001
Creating group with id 1001
Running as enduser
/app/.venv/lib/python3.12/site-packages/llama_index_client/types/metadata_filter.py:20: SyntaxWarning: invalid escape sequence '\*'
  """
There was a problem when trying to write in your cache folder (/home/enduser/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
INFO:     Started server process [42]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     ('172.17.0.1', 33892) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJjMWFlMTZmMy1hZWFhLTQ1MWUtOTM4Yi1lMWRlYzA1NzcwYTcifQ.xFDE2CSqP3drYuzE9ms3MUBPdn4yuZ-htcoNuBZld10&latest_event_id=4" [accepted]
10:37:52 - opendevin:ERROR: auth.py:29 - Invalid token
INFO:     connection open
INFO:     connection closed
INFO:     ('172.17.0.1', 39546) - "WebSocket /ws" [accepted]
INFO:     connection open
10:37:56 - opendevin:INFO: agent.py:64 - Using server runtime
10:37:56 - opendevin:INFO: ssh_box.py:206 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
10:37:56 - opendevin:INFO: ssh_box.py:248 - Detected initial session.
10:37:56 - opendevin:INFO: ssh_box.py:250 - Creating new Docker container
10:37:56 - opendevin:WARNING: ssh_box.py:700 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
10:37:56 - opendevin:INFO: ssh_box.py:674 - Mounting workspace directory: /mnt/c/Users/Abshe/OneDrive/Desktop/open-devin
10:37:56 - opendevin:INFO: ssh_box.py:709 - Mounting volumes: {'/mnt/c/Users/Abshe/OneDrive/Desktop/open-devin': {'bind': '/workspace', 'mode': 'rw'}, '/tmp/cache': {'bind': '/home/opendevin/.cache', 'mode': 'rw'}}
10:37:56 - opendevin:INFO: ssh_box.py:674 - Mounting workspace directory: /mnt/c/Users/Abshe/OneDrive/Desktop/open-devin
10:39:51 - opendevin:INFO: ssh_box.py:720 - Container started
10:39:52 - opendevin:INFO: ssh_box.py:736 - waiting for container to start: 1, container status: running
10:39:52 - opendevin:INFO: ssh_box.py:395 - Connecting to SSH session...
10:39:52 - opendevin:INFO: ssh_box.py:397 - You can debug the SSH connection by running: `ssh -v -p 46967 opendevin@host.docker.internal` using the password '2ff7b3a2-bdb1-4b8d-9517-5bde71c6931b'
10:39:53 - opendevin:INFO: ssh_box.py:401 - Connected to SSH session
10:39:54 - opendevin:INFO: agent.py:96 - Creating agent CodeActAgent using LLM gpt-4o
10:39:54 - opendevin:INFO: llm.py:120 - Initializing LLM with model: gpt-4o
10:39:54 - opendevin:INFO: mixin.py:32 - Initializing plugins in the sandbox
10:39:54 - opendevin:INFO: mixin.py:42 - Copied files from [/app/opendevin/runtime/plugins/agent_skills] to [/opendevin/plugins/agent_skills] inside sandbox.
10:39:54 - opendevin:INFO: mixin.py:50 - Initializing plugin [agent_skills] by executing [/opendevin/plugins/agent_skills/setup.sh] in the sandbox.
10:40:20 - opendevin:INFO: mixin.py:67 - Plugin agent_skills initialized successfully
10:40:20 - opendevin:INFO: mixin.py:42 - Copied files from [/app/opendevin/runtime/plugins/jupyter] to [/opendevin/plugins/jupyter] inside sandbox.
10:40:20 - opendevin:INFO: mixin.py:50 - Initializing plugin [jupyter] by executing [/opendevin/plugins/jupyter/setup.sh] in the sandbox.
10:40:50 - opendevin:INFO: mixin.py:67 - Plugin jupyter initialized successfully
10:40:50 - opendevin:INFO: mixin.py:83 - Sourced ~/.bashrc successfully
10:40:50 - opendevin:INFO: browser_env.py:43 - Starting browser env...
10:40:50 - opendevin:ERROR: state.py:64 - Failed to restore state from session: sessions/cc3b4898-6b4d-44e5-a16f-13258de2da0c/agent_state.pkl
Error restoring state sessions/cc3b4898-6b4d-44e5-a16f-13258de2da0c/agent_state.pkl
10:40:50 - opendevin:INFO: agent_controller.py:183 - [Agent Controller cc3b4898-6b4d-44e5-a16f-13258de2da0c] Setting agent(CodeActAgent) state from AgentState.LOADING to AgentState.INIT
10:40:50 - opendevin:INFO: agent_controller.py:127 - [Agent Controller cc3b4898-6b4d-44e5-a16f-13258de2da0c] Starting step loop...
INFO:     ('172.17.0.1', 44706) - "WebSocket /ws" [accepted]
INFO:     connection open
INFO:     ('172.17.0.1', 44180) - "WebSocket /ws" [accepted]
INFO:     connection open
10:40:50 - opendevin:INFO: agent_controller.py:183 - [Agent Controller cc3b4898-6b4d-44e5-a16f-13258de2da0c] Setting agent(CodeActAgent) state from AgentState.INIT to AgentState.STOPPED
10:40:57 - opendevin:ERROR: browser_env.py:117 - Browser process did not terminate, forcefully terminating...
Exception in thread Thread-1 (init_browser):
10:40:57 - opendevin:INFO: session.py:54 - WebSocket disconnected, sid: cc3b4898-6b4d-44e5-a16f-13258de2da0c
Traceback (most recent call last):
INFO:     connection closed
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
10:40:57 - opendevin:INFO: agent_controller.py:132 - AgentController task was cancelled
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
10:40:57 - opendevin:INFO: agent.py:64 - Using server runtime
10:40:57 - opendevin:INFO: ssh_box.py:206 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
    self._target(*self._args, **self._kwargs)
  File "/app/opendevin/runtime/browser/browser_env.py", line 45, in init_browser
    if not self.check_alive():
           ^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/browser/browser_env.py", line 104, in check_alive
    response_id, _ = self.agent_side.recv()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 248, in recv
    self._check_closed()
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 137, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
10:40:57 - opendevin:INFO: ssh_box.py:248 - Detected initial session.
10:40:57 - opendevin:INFO: ssh_box.py:250 - Creating new Docker container
10:40:57 - opendevin:WARNING: ssh_box.py:700 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
10:40:57 - opendevin:INFO: ssh_box.py:674 - Mounting workspace directory: /mnt/c/Users/Abshe/OneDrive/Desktop/open-devin
10:40:57 - opendevin:INFO: ssh_box.py:709 - Mounting volumes: {'/mnt/c/Users/Abshe/OneDrive/Desktop/open-devin': {'bind': '/workspace', 'mode': 'rw'}, '/tmp/cache': {'bind': '/home/opendevin/.cache', 'mode': 'rw'}}
10:40:57 - opendevin:INFO: ssh_box.py:674 - Mounting workspace directory: /mnt/c/Users/Abshe/OneDrive/Desktop/open-devin
10:40:57 - opendevin:INFO: ssh_box.py:720 - Container started
10:40:58 - opendevin:INFO: ssh_box.py:736 - waiting for container to start: 1, container status: running
10:40:58 - opendevin:INFO: ssh_box.py:395 - Connecting to SSH session...
10:40:58 - opendevin:INFO: ssh_box.py:397 - You can debug the SSH connection by running: `ssh -v -p 33039 opendevin@host.docker.internal` using the password '9f4ce349-b125-4cb2-8d91-a6f49182843f'
10:40:59 - opendevin:INFO: ssh_box.py:401 - Connected to SSH session
10:41:00 - opendevin:INFO: agent.py:96 - Creating agent CodeActAgent using LLM ollama/codellama:7b
10:41:00 - opendevin:INFO: llm.py:120 - Initializing LLM with model: ollama/codellama:7b
10:41:00 - opendevin:INFO: mixin.py:32 - Initializing plugins in the sandbox
10:41:00 - opendevin:INFO: mixin.py:42 - Copied files from [/app/opendevin/runtime/plugins/agent_skills] to [/opendevin/plugins/agent_skills] inside sandbox.
10:41:00 - opendevin:INFO: mixin.py:50 - Initializing plugin [agent_skills] by executing [/opendevin/plugins/agent_skills/setup.sh] in the sandbox.
10:41:25 - opendevin:INFO: mixin.py:67 - Plugin agent_skills initialized successfully
10:41:25 - opendevin:INFO: mixin.py:42 - Copied files from [/app/opendevin/runtime/plugins/jupyter] to [/opendevin/plugins/jupyter] inside sandbox.
10:41:25 - opendevin:INFO: mixin.py:50 - Initializing plugin [jupyter] by executing [/opendevin/plugins/jupyter/setup.sh] in the sandbox.
10:41:56 - opendevin:INFO: mixin.py:67 - Plugin jupyter initialized successfully
10:41:56 - opendevin:INFO: mixin.py:83 - Sourced ~/.bashrc successfully
10:41:56 - opendevin:INFO: browser_env.py:43 - Starting browser env...
10:41:56 - opendevin:ERROR: state.py:64 - Failed to restore state from session: sessions/679c2d24-6768-4cb5-853e-596492e87c1a/agent_state.pkl
Error restoring state sessions/679c2d24-6768-4cb5-853e-596492e87c1a/agent_state.pkl
10:41:56 - opendevin:INFO: agent_controller.py:183 - [Agent Controller 679c2d24-6768-4cb5-853e-596492e87c1a] Setting agent(CodeActAgent) state from AgentState.LOADING to AgentState.INIT
10:41:56 - opendevin:INFO: agent_controller.py:127 - [Agent Controller 679c2d24-6768-4cb5-853e-596492e87c1a] Starting step loop...
10:41:56 - opendevin:INFO: agent_controller.py:183 - [Agent Controller 679c2d24-6768-4cb5-853e-596492e87c1a] Setting agent(CodeActAgent) state from AgentState.INIT to stopped
INFO:     172.17.0.1:60420 - "GET / HTTP/1.1" 304 Not Modified
INFO:     172.17.0.1:60420 - "GET /api/list-files?path=/ HTTP/1.1" 200 OK
10:41:56 - opendevin:INFO: session.py:54 - WebSocket disconnected, sid: 6de9a981-5261-4770-8531-053275dc3ff7
INFO:     connection closed
10:41:56 - opendevin:INFO: agent_controller.py:183 - [Agent Controller 679c2d24-6768-4cb5-853e-596492e87c1a] Setting agent(CodeActAgent) state from stopped to AgentState.STOPPED
10:42:02 - opendevin:ERROR: browser_env.py:117 - Browser process did not terminate, forcefully terminating...
10:42:02 - opendevin:INFO: session.py:54 - WebSocket disconnected, sid: 679c2d24-6768-4cb5-853e-596492e87c1a
Exception in thread Thread-2 (init_browser):
Traceback (most recent call last):
10:42:02 - opendevin:INFO: agent_controller.py:132 - AgentController task was cancelled
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
INFO:     connection closed
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
INFO:     ('172.17.0.1', 34070) - "WebSocket /ws" [accepted]
    self._target(*self._args, **self._kwargs)
INFO:     connection open
  File "/app/opendevin/runtime/browser/browser_env.py", line 45, in init_browser
INFO:     172.17.0.1:34058 - "GET /api/options/models HTTP/1.1" 200 OK
    if not self.check_alive():
           ^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/browser/browser_env.py", line 104, in check_alive
    response_id, _ = self.agent_side.recv()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 248, in recv
    self._check_closed()
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 137, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
10:42:02 - opendevin:INFO: agent.py:64 - Using server runtime
10:42:02 - opendevin:INFO: ssh_box.py:206 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
10:42:02 - opendevin:INFO: ssh_box.py:248 - Detected initial session.
10:42:02 - opendevin:INFO: ssh_box.py:250 - Creating new Docker container
10:42:02 - opendevin:WARNING: ssh_box.py:700 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
10:42:02 - opendevin:INFO: ssh_box.py:674 - Mounting workspace directory: /mnt/c/Users/Abshe/OneDrive/Desktop/open-devin
10:42:02 - opendevin:INFO: ssh_box.py:709 - Mounting volumes: {'/mnt/c/Users/Abshe/OneDrive/Desktop/open-devin': {'bind': '/workspace', 'mode': 'rw'}, '/tmp/cache': {'bind': '/home/opendevin/.cache', 'mode': 'rw'}}
10:42:02 - opendevin:INFO: ssh_box.py:674 - Mounting workspace directory: /mnt/c/Users/Abshe/OneDrive/Desktop/open-devin
10:42:02 - opendevin:INFO: ssh_box.py:720 - Container started
10:42:03 - opendevin:INFO: ssh_box.py:736 - waiting for container to start: 1, container status: running
10:42:04 - opendevin:INFO: ssh_box.py:395 - Connecting to SSH session...
10:42:04 - opendevin:INFO: ssh_box.py:397 - You can debug the SSH connection by running: `ssh -v -p 39363 opendevin@host.docker.internal` using the password 'fbff3a11-764f-43b7-9a69-bc5c556b716f'
10:42:05 - opendevin:INFO: ssh_box.py:401 - Connected to SSH session
10:42:05 - opendevin:INFO: agent.py:96 - Creating agent CodeActAgent using LLM ollama/codellama:7b
10:42:05 - opendevin:INFO: llm.py:120 - Initializing LLM with model: ollama/codellama:7b
10:42:05 - opendevin:INFO: mixin.py:32 - Initializing plugins in the sandbox
10:42:06 - opendevin:INFO: mixin.py:42 - Copied files from [/app/opendevin/runtime/plugins/agent_skills] to [/opendevin/plugins/agent_skills] inside sandbox.
10:42:06 - opendevin:INFO: mixin.py:50 - Initializing plugin [agent_skills] by executing [/opendevin/plugins/agent_skills/setup.sh] in the sandbox.
10:42:30 - opendevin:INFO: mixin.py:67 - Plugin agent_skills initialized successfully
10:42:30 - opendevin:INFO: mixin.py:42 - Copied files from [/app/opendevin/runtime/plugins/jupyter] to [/opendevin/plugins/jupyter] inside sandbox.
10:42:30 - opendevin:INFO: mixin.py:50 - Initializing plugin [jupyter] by executing [/opendevin/plugins/jupyter/setup.sh] in the sandbox.
10:43:01 - opendevin:INFO: mixin.py:67 - Plugin jupyter initialized successfully
10:43:01 - opendevin:INFO: mixin.py:83 - Sourced ~/.bashrc successfully
10:43:01 - opendevin:INFO: browser_env.py:43 - Starting browser env...
10:43:01 - opendevin:ERROR: state.py:64 - Failed to restore state from session: sessions/f64f3c61-73c9-44f2-a6ce-4f2bc3a507a0/agent_state.pkl
Error restoring state sessions/f64f3c61-73c9-44f2-a6ce-4f2bc3a507a0/agent_state.pkl
10:43:01 - opendevin:INFO: agent_controller.py:183 - [Agent Controller f64f3c61-73c9-44f2-a6ce-4f2bc3a507a0] Setting agent(CodeActAgent) state from AgentState.LOADING to AgentState.INIT
10:43:01 - opendevin:INFO: agent_controller.py:127 - [Agent Controller f64f3c61-73c9-44f2-a6ce-4f2bc3a507a0] Starting step loop...
INFO:     172.17.0.1:34058 - "GET /api/options/agents HTTP/1.1" 200 OK
INFO:     172.17.0.1:34058 - "GET /api/list-files?path=/ HTTP/1.1" 200 OK
INFO:     172.17.0.1:34058 - "GET /api/list-files?path=/transformers_cache/ HTTP/1.1" 200 OK
10:43:07 - opendevin:INFO: browser_env.py:58 - Browser env started.
10:43:58 - OBSERVATION
**MessageAction** (source=EventSource.USER)
CONTENT: hello, can you make me a hangman game in python code
10:43:58 - opendevin:INFO: agent_controller.py:183 - [Agent Controller f64f3c61-73c9-44f2-a6ce-4f2bc3a507a0] Setting agent(CodeActAgent) state from AgentState.INIT to AgentState.RUNNING
INFO:     172.17.0.1:40700 - "GET /api/list-files?path=/ HTTP/1.1" 200 OK
INFO:     172.17.0.1:35202 - "GET /api/list-files?path=/transformers_cache/ HTTP/1.1" 200 OK

==============
CodeActAgent LEVEL 0 STEP 0

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Provider List: https://docs.litellm.ai/docs/providers

10:43:58 - opendevin:ERROR: llm.py:173 - {"error":"model 'codellama:7b' not found, try pulling it first"}. Attempt #1 | You can customize these settings in the configuration.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Provider List: https://docs.litellm.ai/docs/providers

10:43:59 - opendevin:ERROR: llm.py:173 - {"error":"model 'codellama:7b' not found, try pulling it first"}. Attempt #2 | You can customize these settings in the configuration.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Provider List: https://docs.litellm.ai/docs/providers

10:44:01 - opendevin:ERROR: llm.py:173 - {"error":"model 'codellama:7b' not found, try pulling it first"}. Attempt #3 | You can customize these settings in the configuration.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Provider List: https://docs.litellm.ai/docs/providers

10:44:01 - opendevin:ERROR: llm.py:173 - {"error":"model 'codellama:7b' not found, try pulling it first"}. Attempt #4 | You can customize these settings in the configuration.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Provider List: https://docs.litellm.ai/docs/providers

10:44:03 - opendevin:ERROR: llm.py:173 - {"error":"model 'codellama:7b' not found, try pulling it first"}. Attempt #5 | You can customize these settings in the configuration.
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2224, in completion
    generator = ollama.get_ollama_response(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/ollama.py", line 241, in get_ollama_response
    raise OllamaError(status_code=response.status_code, message=response.text)
litellm.llms.ollama.OllamaError: {"error":"model 'codellama:7b' not found, try pulling it first"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/opendevin/controller/agent_controller.py", line 130, in _start_step_loop
    await self._step()
  File "/app/opendevin/controller/agent_controller.py", line 290, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agenthub/codeact_agent/codeact_agent.py", line 228, in step
    response = self.llm.do_completion(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 217, in do_completion
    resp = self._completion(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 330, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 467, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 410, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 183, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 470, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 197, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 3415, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 3306, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2447, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 9989, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 9957, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: {"error":"model 'codellama:7b' not found, try pulling it first"}
10:44:03 - opendevin:ERROR: agent_controller.py:136 - Error while running the agent: {"error":"model 'codellama:7b' not found, try pulling it first"}
10:44:03 - opendevin:ERROR: agent_controller.py:137 - Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2224, in completion
    generator = ollama.get_ollama_response(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/ollama.py", line 241, in get_ollama_response
    raise OllamaError(status_code=response.status_code, message=response.text)
litellm.llms.ollama.OllamaError: {"error":"model 'codellama:7b' not found, try pulling it first"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/opendevin/controller/agent_controller.py", line 130, in _start_step_loop
    await self._step()
  File "/app/opendevin/controller/agent_controller.py", line 290, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agenthub/codeact_agent/codeact_agent.py", line 228, in step
    response = self.llm.do_completion(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 217, in do_completion
    resp = self._completion(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 330, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 467, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 410, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 183, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 470, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 197, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 3415, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 3306, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2447, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 9989, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 9957, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: {"error":"model 'codellama:7b' not found, try pulling it first"}

10:44:03 - opendevin:INFO: agent_controller.py:183 - [Agent Controller f64f3c61-73c9-44f2-a6ce-4f2bc3a507a0] Setting agent(CodeActAgent) state from AgentState.RUNNING to AgentState.ERROR
INFO:     172.17.0.1:35214 - "GET /api/list-files?path=/ HTTP/1.1" 200 OK
INFO:     172.17.0.1:35216 - "GET /api/list-files?path=/transformers_cache/ HTTP/1.1" 200 OK

**Comment by tobitege** [comment]
As the error says: you actually have to first download the LLM model with Ollama itself.

**Comment by tobitege** [comment]
Please reopen if need be.
