### ISSUE TITLE
feat: a FileChangeHandler service (for e.g. agentskills)

### ISSUE THREAD

**Issue by tobitege** [OpenDevin/OpenDevin#2527]
**What problem or use case are you trying to solve?**

In order to let OpenDevin know that files have changed intermittently without its knowledge,
I'd like to implement a FileChangeHandler service.

When OpenDevin then acts to edit/append files, the agentskills could query that observer
and give a warning about the file already being changed to the LLM and cancel the operation.

Idea introduced in this issue: https://github.com/OpenDevin/OpenDevin/issues/2443

**Do you have thoughts on the technical implementation?**

The changes to the agentskills are comparably easy, but I'm looking for collaboration on below drafts, that I had gpt4o craft as I don't feel comfortable enough around Linux.

* The Makefile part could either be rewritten to become part of the agentskill's `setup.sh` or the main Makefile?
* How to fully integrate the rest or make it somehow optional from the beginning as `sudo` seems required?

----

A bash-style shell script to set up the `FileChangeHandler` as a systemd service, and a Makefile that calls this script.

### Shell Script (`setup_file_change_handler.sh`):

```bash
#!/bin/bash

# Define variables
SCRIPT_PATH="/usr/local/bin/file_change_handler.py"
SERVICE_PATH="/etc/systemd/system/file_change_handler.service"
DIRECTORY_TO_WATCH="/path/to/directory"

# Create the Python script
cat <<EOL > $SCRIPT_PATH
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
import time

class FileChangeHandler(FileSystemEventHandler):
    def on_modified(self, event):
        print(f'File {event.src_path} has been modified')

    def on_created(self, event):
        print(f'File {event.src_path} has been created')

    def on_deleted(self, event):
        print(f'File {event.src_path} has been deleted')

if __name__ == "__main__":
    path = "$DIRECTORY_TO_WATCH"
    event_handler = FileChangeHandler()
    observer = Observer()
    observer.schedule(event_handler, path, recursive=True)
    observer.start()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
EOL

# Make the script executable
chmod +x $SCRIPT_PATH

# Create the systemd service unit file
cat <<EOL > $SERVICE_PATH
[Unit]
Description=File Change Handler Service
After=network.target

[Service]
ExecStart=/usr/bin/python3 $SCRIPT_PATH
Restart=always
User=nobody
Group=nogroup

[Install]
WantedBy=multi-user.target
EOL

# Reload systemd, start the service, and enable it to start on boot
systemctl daemon-reload
systemctl start file_change_handler.service
systemctl enable file_change_handler.service

echo "FileChangeHandler service setup complete."
```

### Makefile:

```makefile
.PHONY: setup

setup:
    sudo bash setup_file_change_handler.sh
```

### Instructions:

1. **Save the Shell Script**:
   Save the shell script as `setup_file_change_handler.sh`.

2. **Make the Shell Script Executable**:
   ```sh
   chmod +x setup_file_change_handler.sh
   ```

3. **Create the Makefile**:
   Save the Makefile content in a file named `Makefile`.

4. **Run the Setup**:
   Execute the setup by running:
   ```sh
   make setup
   ```

### Explanation:
- **Shell Script**: This script creates the Python file change handler script, makes it executable, creates the systemd service unit file, and starts/enables the service.
- **Makefile**: The `setup` target in the Makefile calls the shell script with `sudo` to ensure it has the necessary permissions to create files in system directories and manage services.

By running `make setup`, the entire process of setting up the `FileChangeHandler` as a systemd service will be automated.

----

**Comment by tobitege** [comment]
cc @rbren @neubig @li-boxuan 

Is this something to further look into? Happy to hear thoughts!

**Comment by li-boxuan** [comment]
My first impression:

1. FileChangeHandler sounds interesting.
2. Only a subset of customers need it - IIRC different people/developers have mentioned in different places/issues that we need to have an option for users to choose optional skills. This could be one of them.
3. As long as this is optional, and people could choose whether to enable it, I don't see any harm to introduce this service/feature.

**Comment by enyst** [comment]
You may want to see also https://github.com/OpenDevin/OpenDevin/issues/1934
