### ISSUE TITLE
Commmand line cannot find module 'agenthub'

### ISSUE THREAD

**Issue by jojeyh** [OpenDevin/OpenDevin#255]
**Describe the bug**
The command line program in `opendevin/main.py` cannot locate `agenthub` module.  This currently works with the server because running FastAPI from root folder can access `agenthub` but this doesn't work when running `opendevin/main.py`.  Not sure how you want to fix it, moving `main.py` to root folder? or moving `agenthub` down into `opendevin` ?

**Steps to Reproduce**
```
PYTHONPATH=`env` python opendevin/main.py -d ./workspace/ -i 100 -t "Write a bash script that prints hello world"
```

**Expected behavior**
Runs programs and solves task

**Actual behavior**
Fails on ModuleNotFoundError

**Additional context**
Traceback (most recent call last):
  File "/home/anon/OpenDevin/opendevin/main.py", line 6, in <module>
    import agenthub # noqa F401 (we import this to get the agents registered)
ModuleNotFoundError: No module named 'agenthub'

**Comment by rbren** [comment]
It should be `PYTHONPATH`, not `PYTHON_PATH`

**Comment by jojeyh** [comment]
Sorry I typed it in wrong but ran with `PYTHONPATH` and still generates error

**Comment by rbren** [comment]
You've still got it wrong 😅 
```
PYTHONPATH=`pwd`
```
not
```
PYTHONPATH=`env`
```

**Comment by rbren** [comment]
I'm going to add this to the README

**Comment by jojeyh** [comment]
🤦 yea that was it haha. thx.  I'm getting more internal server errors from docker but I'll check them out later as I have to go somewhere now.

**Comment by jojeyh** [comment]
I see now why it's used, but it's a little irksome.  Is it worth refactoring `agenthub` into `opendevin`.  I think this would eliminate the need for the env var, but maybe break a bunch of stuff?

**Comment by rbren** [comment]
I tried doing that, but it still made me use PYTHONPATH...definitely up for a PR if you want to try it

**Comment by Ido108** [comment]
in windows use-

`$Env:PYTHONPATH = (Get-Location).Path;`

instead of 

`PYTHONPATH=`pwd``

**Comment by suoko** [comment]
I have this error  `No module named 'opendevin.logging'`

```
PYTHONPATH=`pwd` python opendevin/main.py -d ./workspace/ -i 100 -t "Write a bash script that prints hello world"
Traceback (most recent call last):
  File "/opt/dev/OpenDevin.new/opendevin/main.py", line 6, in <module>
    import agenthub  # noqa F401 (we import this to get the agents registered)
    ^^^^^^^^^^^^^^^
  File "/home/gabriele.vidali@digitalvirgo.com/dev/OpenDevin.new/agenthub/__init__.py", line 5, in <module>
    from . import monologue_agent # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabriele.vidali@digitalvirgo.com/dev/OpenDevin.new/agenthub/monologue_agent/__init__.py", line 1, in <module>
    from opendevin.agent import Agent
  File "/home/gabriele.vidali@digitalvirgo.com/dev/OpenDevin.new/opendevin/agent.py", line 7, in <module>
    from opendevin.llm.llm import LLM
  File "/home/gabriele.vidali@digitalvirgo.com/dev/OpenDevin.new/opendevin/llm/llm.py", line 6, in <module>
    from opendevin.logging import llm_prompt_logger, llm_response_logger
ModuleNotFoundError: No module named 'opendevin.logging'

```

**Comment by rbren** [comment]
@suoko this is fixed in main
