### ISSUE TITLE
[Bug]:  Integration of OpenDevin Script with Nginx Proxy Manager

### ISSUE THREAD

**Issue by tosin2013** [OpenDevin/OpenDevin#2553]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Description

I am attempting to integrate the script from [OpenDevin](https://raw.githubusercontent.com/tosin2013/OpenDevin/main/scripts/opendevin.sh) with Nginx Proxy Manager to forward both the frontend and backend of the Devin application. I am currently facing issues with forwarding the backend API over HTTPS.

### Current Configuration

I have modified the `frontend/.env` file as follows:

```bash
cat frontend/.env
VITE_BACKEND_HOST="backend.opendevin-testing.example.com"
VITE_USE_TLS="true"
VITE_INSECURE_SKIP_VERIFY="false"
VITE_FRONTEND_PORT="3001"
```

### Goal

The goal is to use this setup with the [code-server-instance](https://github.com/tosin2013/code-server-instance) project so that it can sit behind an Nginx proxy and a code-server, allowing users to interact with the Devin frontend and modify the code in the code-server.

### Steps to Reproduce

1. Clone the OpenDevin repository.
2. Modify the `frontend/.env` file with the above configurations.
3. Rebuild the Nginx Proxy Manager instance.
4. Attempt to access the backend API over HTTPS.

### Expected Behavior

The backend API should be accessible over HTTPS, and the frontend should correctly point to the backend.

### Actual Behavior

The requests still show the frontend endpoint, and the backend API is not accessible over HTTPS.

### Additional Context

- **OpenDevin Version:** main branch 
- **Model and Agent:** Not applicable.
- **Operating System:** Ubuntu.

### Logs and Errors

No specific logs or errors provided as the issue is related to configuration and integration.

### References

- [OpenDevin Script](https://raw.githubusercontent.com/tosin2013/OpenDevin/main/scripts/opendevin.sh)
- [code-server-instance](https://github.com/tosin2013/code-server-instance)

### Checklist

- [x] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting.
- [x] I have checked the existing issues for similar bugs.

Thank you for your assistance.

### Current OpenDevin version

```bash
main branch
```

### Installation and Configuration

```bash
Configure [nginx proxy manger](https://github.com/tosin2013/code-server-instance) 
Freshly installed Ubuntu 22.10 
git clone https://github.com/tosin2013/OpenDevin.git
cd OpenDevin
./scripts/opendevin.sh -r -i -b
```

### Model and Agent

NA

### Operating System

Ubuntu 22.10 

### Reproduction Steps

1. Deploy nginx proxy manager 
2. Configure front end with nginx proxy manager 
3. Configure backend with nginx proxy manager.
4. attempt to access frontend using nginx proxy manager

### Logs, Errors, Screenshots, and Additional Context

n/a

**Comment by neubig** [comment]
Thanks for the detailed report @tosin2013 ! We'll try to take a look at this, but since it's somewhat of an unusual setting it might be somewhat lower priority for the core developers. We'd definitely appreciate a PR from the community though!

**Comment by Shimada666** [comment]
I am also using Nginx Proxy Manager. I can take a look at this when I have some time.
