### ISSUE TITLE
Support Basic Auth for Ollama Calls or being able to add Headers to all Ollama Calls.

### ISSUE THREAD

**Issue by cesarandreslopez** [OpenDevin/OpenDevin#2559]
**What problem or use case are you trying to solve?**

In our case, our Olama server is protected under basic authorization in a GPU server. We want to be able to call it and have it pass the authentication. 

**Describe the UX of the solution you'd like**

An Environment parameter somewhere I could ask OpenDevin to attach something like this:

```
      "requestOptions": {
        "headers": {"Authorization": "Basic XXXXXXXXXXXXXXX"}
      }
```

**Do you have thoughts on the technical implementation?**

No.

**Describe alternatives you've considered**

Opening up our Ollama server, but it will be insecure.

**Comment by neubig** [comment]
Hey @cesarandreslopez , have you tried setting `LLM_API_KEY`? If that doesn't work, what error do you get?

**Comment by cesarandreslopez** [comment]
@neubig, so the issue was that I had an Nginx Basic Auth in front of my Ollama services. The issue was much simpler than I expected to resolve. I just updated Ollama connection string to include the following the username and password as part of the connection string to the remote ollama.

Thank you!
