### ISSUE TITLE
[Feature]: Make eval-num-workers configurable in evaluation scripts

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#2567]
**What problem or use case are you trying to solve?**

In the scripts `evaluation/*/scripts/run_infer.sh`, the `eval-num-workers` setting is (1) hard-coded, and (2) inconsistent across evaluation benchmarks: https://github.com/search?q=repo%3AOpenDevin%2FOpenDevin%20eval-num-workers&type=code

Being hard-coded is a problem because different people may want to set this to different numbers (to avoid being rate-limited, or to not run too many processes on weaker machines).

**Describe the UX of the solution you'd like**

Add a `NUM_WORKERS` variable to the bash script's input variables that sets the number of workers.

**Comment by PierrunoYT** [comment]
To address the issue of the `eval-num-workers` setting being hard-coded and inconsistent across evaluation benchmarks, you can add a `NUM_WORKERS` variable to the bash script's input variables. This will allow users to set the number of workers according to their needs.

Here is how you can modify the `run_infer.sh` scripts to include the `NUM_WORKERS` variable:

1. **Add `NUM_WORKERS` as an input variable.**
2. **Set a default value for `NUM_WORKERS` if it is not provided.**
3. **Update the command to use the `NUM_WORKERS` variable.**

Below is an example of how you can modify one of the scripts (`evaluation/toolqa/scripts/run_infer.sh`). You can apply similar changes to the other scripts.

### Modified `evaluation/toolqa/scripts/run_infer.sh`

```bash
#!/bin/bash
set -eo pipefail

source "evaluation/utils/version_control.sh"

MODEL_CONFIG=$1
COMMIT_HASH=$2
AGENT=$3
EVAL_LIMIT=$4
DATASET=$5
HARDNESS=$6
WOLFRAM_APPID=$7
NUM_WORKERS=${8:-1}  # Add NUM_WORKERS variable with default value 1

checkout_eval_branch

if [ -z "$AGENT" ]; then
  echo "Agent not specified, use default CodeActAgent"
  AGENT="CodeActAgent"
fi

if [ -z "$DATASET" ]; then
  DATASET="flight"
  echo "Dataset not specified, use default $DATASET"
fi

if [ -z "$HARDNESS" ]; then
  HARDNESS="easy"
  echo "Hardness not specified, use default $HARDNESS"
fi

if [ -z "$WOLFRAM_APPID" ]; then
  WOLFRAM_APPID="YOUR_WOLFRAMALPHA_APPID"
  echo "WOLFRAM_APPID not specified"
fi

get_agent_version

echo "AGENT: $AGENT"
echo "AGENT_VERSION: $AGENT_VERSION"
echo "MODEL_CONFIG: $MODEL_CONFIG"
echo "DATASET: $DATASET"
echo "HARDNESS: $HARDNESS"
echo "WOLFRAM_APPID: $WOLFRAM_APPID"
echo "NUM_WORKERS: $NUM_WORKERS"  # Print NUM_WORKERS

COMMAND="poetry run python evaluation/toolqa/run_infer.py \
  --agent-cls $AGENT \
  --llm-config $MODEL_CONFIG \
  --max-iterations 30 \
  --dataset $DATASET \
  --hardness $HARDNESS \
  --wolfram_alpha_appid $WOLFRAM_APPID \
  --data-split validation \
  --max-chars 10000000 \
  --eval-num-workers $NUM_WORKERS \  # Use NUM_WORKERS variable
  --eval-note ${AGENT_VERSION}_${LEVELS}"

if [ -n "$EVAL_LIMIT" ]; then
  echo "EVAL_LIMIT: $EVAL_LIMIT"
  COMMAND="$COMMAND --eval-n-limit $EVAL_LIMIT"
fi

# Run the command
eval $COMMAND
```

### Apply Similar Changes to Other Scripts

You can apply similar changes to the other `run_infer.sh` scripts in the `evaluation` directory. Here is a summary of the changes:

1. Add `NUM_WORKERS=${8:-1}` to the list of input variables.
2. Print the `NUM_WORKERS` variable for debugging purposes.
3. Update the `COMMAND` to use the `--eval-num-workers $NUM_WORKERS` option.

By making these changes, users will be able to specify the number of workers when running the scripts, providing greater flexibility and consistency across different evaluation benchmarks.
