### ISSUE TITLE
support statistical number in the report.json

### ISSUE THREAD

**Issue by lwaekfjlk** [OpenDevin/OpenDevin#2577]
**What problem or use case are you trying to solve?**
instead of listing all the instance_ids, an additional information should be added is their number. So that we don't need to count.
**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by neubig** [comment]
I think this is already implemented in the summary statistics? https://github.com/OpenDevin/OpenDevin/tree/main/evaluation/swe_bench#view-result-summary

**Comment by mamoodi** [comment]
@lwaekfjlk does the result summary do what you want?
