### ISSUE TITLE
[Bug]: ERROR: session.py:69 - Error creating controller: Persistent sandbox is currently designed for opendevin user only. Please set run_as_devin=True in your config.toml

### ISSUE THREAD

**Issue by dearbulut** [OpenDevin/OpenDevin#2579]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

opendevin:ERROR: session.py:69 - Error creating controller: Persistent sandbox is currently designed for opendevin user only. Please set run_as_devin=True in your config.toml

### Current OpenDevin version

```bash
ghcr.io/opendevin/opendevin:0.3.1
```

### Installation and Configuration

```bash
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e PERSIST_SANDBOX="true" \
    -e SSH_PASSWORD="make something up here" \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.6.2
```

**Comment by mamoodi** [comment]
@dearbulut out of curiosity, does it work if you set PERSIST_SANDBOX=false
?

**Comment by mamoodi** [comment]
Try the command on the README currently and see if the issue happens (it does not have persist_sandbox). Please open a new issue if you run into issues.
