### ISSUE TITLE
[Feature] Support vision inputs for LLM with vision capabilities

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#2590]
**What problem or use case are you trying to solve?**

Context: https://opendevin.slack.com/archives/C06P5NCGSFP/p1719073107473339

It will be very helpful for the agent to actually "see," especially if you ask the agent to develop a web page / frontend UI / game.

**Describe the UX of the solution you'd like**

- [ ] **Backend**: We should use litellm to enable vision model support (https://litellm.vercel.app/docs/completion/vision#checking-if-a-model-supports-vision) in the OpenAI API format where image can be represented as `base64` to pass into chat completion call. The chat `Event` (text-only now) needs to be modified to support passing images as "base64" to the backend: maybe each chat event can be an interleaved list of `[text, image_in_base64, text, ...]`.

- [ ] **Frontend**: the user can upload images to the *chat* by (1) pasting, (2) clicking to upload, and/or (3) referring to files inside the workspace (e.g., @/workspace/screenshot.png -- this maybe too complicated and can leave to future). And once the image is added, we should show the thumbnail of the added images. The chat `Event` need to be modified to support passing images as "base64" to the backend.
<img width="759" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/38853559/a8131a76-9968-486a-8b57-ee2b3f699a41">

**Do you have thoughts on the technical implementation?**

LiteLLM already have vision model supports: 
https://litellm.vercel.app/docs/completion/vision#checking-if-a-model-supports-vision

We should throw out an error if user choose to use a model without vision support, yet uploaded an image.

**Describe alternatives you've considered**

**Additional context**

**Comment by PierrunoYT** [comment]
Yeah this would be sick

**Comment by xingyaoww** [comment]
Resolved by #2848.
