### ISSUE TITLE
Static OPENAI API KEY assigned.

### ISSUE THREAD

**Issue by doc1024** [OpenDevin/OpenDevin#2607]
I have the issue that there seems to be a static OPENAI API KEY used, the key referenced is not mine: 
{'error': {'message': 'Incorrect API key provided: sk-proj-********************************************ygNW

I have also following issue, but now I have this static key assigned issue.
https://discord.com/channels/1222935860639563850/1226175438833844285/threads/1254603317120729219

              Made some progress, I didn't have ```llamma-index-embeddings-huggingface``` installed.

Now I've arrived at the frontend page, but when given a prompt I receive this error:

EDIT: This was after I input a response on the frontend page. This error below was being repeated as a response from the bot in the chat.

```
Oops. Something went wrong: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided:
hf_wZdQE*************************FdyQ. You can find your API key at https://platform.openai.com/account/api-keys.',
'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
```

I have ```LLM_MODEL```, ```LLM_API_KEY```, and ```LLM_EMBEDDING_MODEL``` all set. I also have set and unset ```OPENAI_API_KEY``` and it appears to make no difference. Perhaps a logical error with handling huggingface litellm models?

Also, I was reading [memory.py](https://github.com/OpenDevin/OpenDevin/blob/adc317de4c006683c2c5bb4e8823b03208d1dfa1/agenthub/langchains_agent/utils/memory.py) and it seems like on line ```25``` that its referencing a static HuggingFace model rather than taking in ```LLM_MODEL```. Maybe a design feature, but thought it was worth mentioning.

_Originally posted by @Solonce in https://github.com/OpenDevin/OpenDevin/issues/228#issuecomment-2022658511_

**Comment by enyst** [comment]
Hey @doc1024, please use the bottom down Settings wheel in the frontend to set the model and key. Save and it should work. You don't need the vars for model and key, use the frontend settings window.

The post you reposted is from 3 months ago, a lot has changed since then. Have you used opendevin before? Do you share the computer with someone else?

**Comment by mamoodi** [comment]
@doc1024 are you still running into this issue after setting the API key through the settings UI?

**Comment by doc1024** [comment]
I stopped using the latest code, it usually breaks. I'm not sharing the computer. Do you plan to release a stable version?

**Comment by doc1024** [comment]
Yes the issue persised at the build I did at that time. I need to build with latest to check if it is still in issue. In the moment I try to use 0.62. But it has an issue with certificate handling in my environment. I opened an issue for that too.

**Comment by tobitege** [comment]
There is no static API key coming from OpenDevin: it is either an environment variable (maybe even set in .bashrc), or in the config.toml file. Go to your OpenAI account page and generate a new key and enter that in the UI and click Save.

**Comment by doc1024** [comment]
Issue solved with the latest build today.
