### ISSUE TITLE
How to Install Open Devin Locally

### ISSUE THREAD

**Issue by SM-Kumail-Rizvi** [OpenDevin/OpenDevin#2611]
Hi everyone @jeremi @neubig  @mroch @penberg  @ohhmm  @JensRoland 

I am trying to install OpenDevin locally on my system. While I have found some instructions on how to do this, I am encountering difficulties and would appreciate a detailed, step-by-step guide to ensure I set it up correctly. My goal is to clone OpenDevin, modify its prompts, and integrate it into my development workflow without having to pull the entire package each time.

**Describe the UX of the solution you'd like**

I would like a clear, comprehensive guide that covers the following aspects:
1. Prerequisites and system requirements for running OpenDevin locally.
2. Step-by-step instructions for installing all necessary tools and dependencies (e.g., Docker, Node.js, npm, Rust, Conda, etc.).
3. Detailed commands for cloning the OpenDevin repository and setting up the development environment.
4. Instructions for modifying the cloned version of OpenDevin, including how to integrate custom prompts and other changes.
5. Guidance on running OpenDevin in a Docker container using the local clone instead of pulling from the GitHub Container Registry each time.

**Do you have thoughts on the technical implementation?**

Here are some initial thoughts on the technical implementation:
- Docker Configuration: I need to configure Docker to use a locally cloned version of OpenDevin. This might involve modifying the Dockerfile or using volume mounts to point to the local codebase.
- Environment Setup: Detailed commands and configuration settings for setting up the environment in WSL (Windows Subsystem for Linux) or a native Linux environment.
- Dependency Management: Information on managing dependencies using Conda, npm, and other package managers.

**Describe alternatives you've considered**

I have considered the following alternatives:
- Following the existing installation guides available online, but they are either incomplete or do not address the specific need to use a local clone.
- Using a virtual machine to set up a completely isolated environment, but this approach seems overly complex and resource-intensive for my needs.
- Attempting to modify the Docker commands to point to a local directory, but I am unsure of the correct configuration.

**Additional context**

- System Details: I am using a Windows system with WSL2 enabled. Docker is installed and running correctly.
- Development Tools: I have experience with using Git, Docker, and basic command-line operations, but I am not deeply familiar with modifying Dockerfiles or complex environment setups.
- Goal: My ultimate goal is to be able to make custom modifications to OpenDevin and run it locally in a way that is efficient and repeatable.

Any assistance or detailed guidance on how to achieve this setup would be greatly appreciated. Thank you!

**Comment by cntyt** [comment]
我一直在关注这个项目，因为技术原因，一直没有运行成功，我也希望项目主能出一些能让小白新手一步步能运行起来，谢谢！

**Comment by li-boxuan** [comment]
> Google translate to English for the above: "I have been paying attention to this project, but due to technical reasons, it has not been successfully run. I also hope that the project owner can come up with something that can help novices start running it step by step. Thank you!"

Tbh the original version (chinese post) reads more like machine translation XD

**Comment by tobitege** [comment]
> After this, you should be able to visit the opendevin website. You might encounter some docker issues, but you can follow the documentation to resolve them.

hmm... instead of 4, 5 and 6: why not just "`make build`" and "`make run`"?
Are there issues with that we need to look into or is it just faster? 🤔

**Comment by Shimada666** [comment]
@tobitege 
It might be because of my personal habit. I contribute to both the frontend and backend of opendevin. So, I prefer to start the frontend and backend separately.

**Comment by mamoodi** [comment]
@SM-Kumail-Rizvi the official ways to setup OpenDevin are:
* Docker command: https://github.com/OpenDevin/OpenDevin?tab=readme-ov-file#-getting-started
* Development workflow: https://github.com/OpenDevin/OpenDevin/blob/main/Development.md

Does that answer your question?

If you require a very specific setup, you can join the slack group and ask there to see if any developers can help you. However, the official documentation should work for setting up OpenDevin locally.
