### ISSUE TITLE
[Bug]: e2e test with dummy agent: wrong action state outcome

### ISSUE THREAD

**Issue by tobitege** [OpenDevin/OpenDevin#2618]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Action "*Run e2e test with dummy agent / test (pull_request)*" running in CI returns success, even though the _actual_ test inside fails with a curious error.

For reference, link to test result log from a PR that itself isn't involved in the test:
https://github.com/OpenDevin/OpenDevin/actions/runs/9644933344/job/26598091132?pr=2552#step:5:32
```py
12:05:46 - opendevin:INFO: agent_controller.py:135 - [Agent Controller default] Starting step loop...

==============
DummyAgent LEVEL 0 STEP 0

12:05:46 - ACTION
AddTaskAction(parent='0.0', goal='run ls', subtasks=[], thought='', action='add_task')
12:05:46 - opendevin:ERROR: agent_controller.py:143 - Error while running the agent: Task does not exist:0.0
12:05:46 - opendevin:ERROR: agent_controller.py:144 - Traceback (most recent call last):
  File "/home/runner/work/OpenDevin/OpenDevin/opendevin/controller/agent_controller.py", line 138, in _start_step_loop
    await self._step()
  File "/home/runner/work/OpenDevin/OpenDevin/opendevin/controller/agent_controller.py", line 324, in _step
    await self.event_stream.add_event(action, EventSource.AGENT)
  File "/home/runner/work/OpenDevin/OpenDevin/opendevin/events/stream.py", line 112, in add_event
    await callback(event)
  File "/home/runner/work/OpenDevin/OpenDevin/opendevin/controller/agent_controller.py", line 168, in on_event
    self.state.root_task.add_subtask(event.parent, event.goal, event.subtasks)
  File "/home/runner/work/OpenDevin/OpenDevin/opendevin/controller/state/task.py", line 204, in add_subtask
    parent = self.get_task_by_id(parent_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/OpenDevin/OpenDevin/opendevin/controller/state/task.py", line 183, in get_task_by_id
    raise LLMMalformedActionError('Task does not exist:' + id)
opendevin.core.exceptions.LLMMalformedActionError: Task does not exist:0.0
12:05:46 - opendevin:INFO: agent_controller.py:193 - [Agent Controller default] Setting agent(DummyAgent) state from AgentState.RUNNING to AgentState.ERROR
12:05:47 - opendevin:INFO: agent_controller.py:193 - [Agent Controller default] Setting agent(DummyAgent) state from AgentState.ERROR to AgentState.STOPPED
```
- the agent's ERROR state is reset to STOPPED thus no fail?
- the session id is not provided as call to main.py, thus defaulting to "default"?
- DummyAgent itself not using correct sid itself?

### Current OpenDevin version

```bash
0.6.2
```

### Installation and Configuration

```bash
CI
```

### Model and Agent

see CI

**Comment by tobitege** [comment]
Hello @rbren if you have a minute, I think this issue needs some assistance of yours, thanks! 👋

**Comment by SmartManoj** [comment]
[In the latest action,](https://github.com/OpenDevin/OpenDevin/actions/runs/9825518342/job/27125775860) step 1 error is ignored.

![image](https://github.com/OpenDevin/OpenDevin/assets/7231077/a18bf79e-3839-4d7c-9927-d63781824025)

**Comment by SmartManoj** [comment]
Could you reopen it as the test in #2834 was not failed as expected?
