### ISSUE TITLE
Windows 11: Client websocket disconnected again

### ISSUE THREAD

**Issue by sonicino2** [OpenDevin/OpenDevin#262]
**Describe the bug**
I keep getting: 
```
Error sending data to client Cannot call "send" once a close message has been sent.
Error sending data to client
Client websocket disconnected (<CloseCode.ABNORMAL_CLOSURE: 1006>, None)
Error sending data to client
```
After so many steps have been completed

**Steps to Reproduce**
1. Run npm run start -- --port 3001
2. Set a task 
3. Error after so many steps have been produced

**Expected behavior**
Build the project
**Actual behavior**
(<CloseCode.ABNORMAL_CLOSURE: 1006>, None)

**Additional context**
Used Claude 3 as my LLM. On a Windows 11 machine. Followed the steps in the root dir `readme.md`. Was trying to create a pac-man game

[error3.txt](https://github.com/OpenDevin/OpenDevin/files/14779614/error3.txt)

**Comment by rbren** [comment]
Tracking this one here: https://github.com/OpenDevin/OpenDevin/issues/235
