### ISSUE TITLE
[Bug]: httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate

### ISSUE THREAD

**Issue by doc1024** [OpenDevin/OpenDevin#2620]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Main and 0.62 produce the same error 

httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)
httpcore.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006) 

### Current OpenDevin version

```bash
main and 0.6.2
```

### Installation and Configuration

```bash
export LLM_MODEL="gpt4o"
export LLM_EMBEDDING_MODEL="openai"
export LLM_EMBEDDING_MODEL_BASE_URL=""
export LLM_API_KEY="sk-proj-......."

export OPENAI_API_KEY="sk-proj-......"
export WORKSPACE_MOUNT="/opt/OpenDevin"
export WORKSPACE_BASE=$WORKSPACE_MOUNT"/workspace"
export TRANSFORMERS_CACHE=$WORKSPACE_MOUNT"/cache"

#hhtp certificate error: https://stackoverflow.com/questions/76578915/ssl-certificate-verify-failed-certificate-verify-failed-self-signed-certifica
export SSL_CERT_FILE=$WORKSPACE_MOUNT"/ca-root.pem"
export REQUESTS_CA_BUNDLE=$WORKSPACE_MOUNT"/ca-root.pem"

using micromamba
/opendevin: make
make setup-config
make run

OR

docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.6.2
```

### Model and Agent

- Model: gpt4o
- Agent: CodeAgent

### Operating System

Mac Latest

### Logs, Errors, Screenshots, and Additional Context

[error (1).pdf](https://github.com/user-attachments/files/15961954/error.1.pdf)
<img width="1414" alt="Screenshot 2024-06-25 at 00 34 48" src="https://github.com/OpenDevin/OpenDevin/assets/111521088/16444850-9fa9-4fed-9551-f82149d3b5c3">
<img width="430" alt="Screenshot 2024-06-25 at 00 35 04" src="https://github.com/OpenDevin/OpenDevin/assets/111521088/cc5b36a4-91bc-43ae-a8b1-8624e4df2a2c">

---
## I just triggered a "make build" of 0.6.2. The build produces now a new issue:

`
Building project...
Checking dependencies...
Checking system...
macOS detected.
Checking Python installation...
Python 3.11.9 is already installed.
Checking npm installation...
npm 10.5.0 is already installed.
Checking Node.js installation...
Node.js 20.12.2 is already installed.
Checking Docker installation...
Docker version 26.0.0, build 2ae903e is already installed.
Checking Poetry installation...
Poetry (version 1.8.3) is already installed.
Dependencies checked successfully.
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:4bd05c581692e26a448bbc6771a21bb27002cb0e6bcf5034d0db91bb8704d0f0
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/opendevin/sandbox
Docker image pulled successfully.
Installing Python dependencies...
Using virtualenv: /Users/sstraube/Library/Caches/pypoetry/virtualenvs/opendevin-l0sScIZF-py3.11
Installing chroma-hnswlib...
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/chroma-hnswlib/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/chroma-hnswlib/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/chroma-hnswlib/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/chroma-hnswlib/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/chroma-hnswlib/
Could not fetch URL https://pypi.org/simple/chroma-hnswlib/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/chroma-hnswlib/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))) - skipping
ERROR: Could not find a version that satisfies the requirement chroma-hnswlib (from versions: none)
ERROR: No matching distribution found for chroma-hnswlib
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))) - skipping
make[1]: *** [install-python-dependencies] Error 1
make: *** [build] Error 2
`

**Comment by SmartManoj** [comment]
Is there any firewall enabled in your network?
Could you run this code?
```py
import requests
from requests.exceptions import SSLError
url = "https://example.com/"
try:
    # Make a request with SSL verification enabled
    response = requests.get(url)
    print("Request succeeded. Response code:", response.status_code)
except SSLError as e:
    print("SSL error:", e)
try:
    # Make a request with SSL verification disabled
    response = requests.get(url, verify=False)
    print("Request succeeded (without SSL verification). Response code:", response.status_code)
except requests.exceptions.RequestException as e:
    print("Request failed:", e)
```

**Comment by doc1024** [comment]
@SmartManoj  this is the Output:
----------------
InsecureRequestWarning: Unverified HTTPS request is being made to host 'google.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
....python/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.google.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Request succeeded (without SSL verification). Response code: 200

**Comment by doc1024** [comment]
Is there an option to disable the ssl check, so I can run opendevin?
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

P.S.Yes I have a firewall, why whould the Firewall make the https request insecure?

**Comment by doc1024** [comment]
@SmartManoj any idea how to solve this issue?

**Comment by doc1024** [comment]
The cause of the issue is probably that my endpoint security or firewall sitting in between is opening up the ssl transaction to check the data inside (DPI). The firewall replaced the certificate with a self-signed and added through MDM into my cert-store on my laptop. When I start opendevin the ssl urllib3 has seen a self-signed cert and produces an exception, because the trust-chain is broken. Which is correct.

error: httpcore.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)

How could this issue been resolved, any SSL_UNTRUSTED=True flag available?

**Comment by SmartManoj** [comment]
Relevant SO Post [Disable ssl verification on a third party module using HTTPX](https://stackoverflow.com/a/75726782)
