### ISSUE TITLE
Some way to manage the sandbox environment (e.g. to change python version?)

### ISSUE THREAD

**Issue by ldorigo** [OpenDevin/OpenDevin#2656]
**What problem or use case are you trying to solve?**

My project uses python 3.11. I wanted to try and make changes, run tests etc. with OpenDevin  but it fails because its python version is 3.10 (it even tried, and failed, to install 3.11 on its own)

**Describe the UX of the solution you'd like**

Problem is that it's set at the docker container level, so I'm not sure how this can be done elegantly without requiring users to clone the repo locally and do lots of manual work...?

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by tobitege** [comment]
Hmm... I thought 3.11 was the default Python version we install, not 3.10. 🤔

**Comment by ldorigo** [comment]
![image](https://github.com/OpenDevin/OpenDevin/assets/8631181/48c42701-589b-45ee-a131-f32bc2ac3f2f)

**Comment by tobitege** [comment]
@SmartManoj you have an idea here?

**Comment by SmartManoj** [comment]
Ubuntu 22.04 comes with Python 3.10
https://github.com/OpenDevin/OpenDevin/blob/9919d8e448bfa1bac7c50545f1c7a821f5537795/containers/sandbox/Dockerfile#L1

**Comment by SmartManoj** [comment]
> (it even tried, and failed, to install 3.11 on its own)

Sorry, I read it as "I even tried". In the main version, you can use the Terminal in the UI.

**Comment by ldorigo** [comment]
Maybe a good flexible solution to this would be to allow editing the dockerfile for the inner container in settings? To e.g. set up a permanent environment; otherwise the sandbox (and so e.g. any installed packages, python upgrades,...) gets reset every time - even with access to the terminal, you'd have to re-do the setup every time you launch

**Comment by SmartManoj** [comment]
You can specify custom sandboxes using the `sandbox_container_image` config and persist the changes in the sandbox using the `persist_sandbox` config.

**Comment by mamoodi** [comment]
@ldorigo can you try this procedure and see if it is what you require?
https://docs.all-hands.dev/modules/usage/custom_sandbox_guide

**Comment by Shimada666** [comment]
If you need to use Python 3.11, maybe you can tell llm to use Miniconda to create a Python 3.11 environment, then install your project's dependencies, and start your project using this environment?

Mixing your project's Python environment with the one used by OpenDevin might not be a good idea. But I don't have a best practice right now either. 

@xingyaoww 
Can you give a better suggestion?

**Comment by xingyaoww** [comment]
Actually, I think this issue can be best resolved following @mamoodi's advice by changing `sandbox_container_image` into an image that contains Python 3.11, following https://docs.all-hands.dev/modules/usage/custom_sandbox_guide.

**Comment by Shimada666** [comment]
You can install Python 3.11 based on the Ubuntu image, then build a new image. After that, you can set it as the sandbox container image, then the sandbox image will have Python 3.11 runtime.

**Comment by mamoodi** [comment]
@ldorigo did you try the suggestions above and check if this is what you require?

**Comment by ldorigo** [comment]
Sorry I didn't answer further, didn't have time to play with it more. The only issue with this solution is that it requires cloning the repo locally, can't just run it from docker like the readme shows.

**Comment by mamoodi** [comment]
@x66ccff this is the new page: https://docs.all-hands.dev/modules/usage/how-to/custom-sandbox-guide
