### ISSUE TITLE
[Bug]: Sometimes fails to open in google chrome

### ISSUE THREAD

**Issue by sohail535** [OpenDevin/OpenDevin#2659]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

## Describe the bug
After following instructions on how to run opendevin, I am able to use it fine. But often times iam not able to open it in google chrome, but works in firefox.
I am using openai for the llm, my system does not have any GPU.

### Current OpenDevin version

```bash
ghcr.io/opendevin/opendevin:0.6.2
```

### Installation and Configuration

```bash
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.6.2
```

### Operating System

linux

### Reproduction Steps

Start the docker container as in the instructions
Open localhost:3000 in google chrome

### Logs, Errors, Screenshots, and Additional Context

![image](https://github.com/OpenDevin/OpenDevin/assets/8740782/b5e70d32-cb52-45c1-8ccb-f3833b6c684c)

**Comment by Siddharth-Latthe-07** [comment]
@sohail535 
have you check these steps:-
1.  Browser Cache: 
Sometimes, Chrome might have cached an old version of the page or some resources. Try clearing the cache or opening the page in an incognito window.
2. Port Conflict: 
See to it  that there is no other service is using port 3000.
if there kill it by:-
```
sudo lsof -i :3000
sudo kill -9 <PID>
```
3. Inspect the logs of your Docker container for any errors that might indicate why Chrome is having trouble loading the page.
`docker logs <container_id>` and check the docker health by `docker ps`

chekc if these work, and let me know the details for further issue , if it persist
Thanks

**Comment by mamoodi** [comment]
I've run into this multiple times and clearing the cache always seems to fix it. @sohail535
