### ISSUE TITLE
Automate regression test checking

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#269]
**What problem or use case are you trying to solve?**
We can run the regression tests with `./evaluation/regression/run.sh`. But it's hard to tell how each agent does, and if it accomplishes the task.

**Describe the UX of the solution you'd like**
I'd like to see a score of how many tests it accomplished successfully

**Do you have thoughts on the technical implementation?**
We should add a `test.sh` to each test case, and expect it to exit `0`.

Each agent should then get a score of how many tests it passed.

**Describe alternatives you've considered**

**Additional context**

**Comment by dorbanianas** [comment]
@rbren is this what you mean exactly?

https://github.com/OpenDevin/OpenDevin/pull/287

If so I can try to improve the regression testing framework to make it much easier to execute and to build new tests

**Comment by rbren** [comment]
This looks awesome!

Some of the `test.sh` scripts might be hard to write generically--e.g. how do you test that there's a working TODO list application? We might have to get a little creative with those

**Comment by rbren** [comment]
whoops didn't mean to close

**Comment by dorbanianas** [comment]
what I'm doing now is trying to switch to python. maybe having a class where the tests should inherit from it would be beneficial, we need to architect the tests structure

**Comment by rbren** [comment]
Nice, yeah, agree it'd be better to have something that isn't just a bash script
