### ISSUE TITLE
Make ghcr.io docker image public

### ISSUE THREAD

**Issue by yufansong** [OpenDevin/OpenDevin#270]
**Describe the bug**
Proposed in #263. Currently we switch to use `ghcr.io` to maintain the docker image. But it seems private. 

**Steps to Reproduce**
```shell
docker pull ghcr.io/opendevin/sandbox:v0.1
```

**Expected behavior**
Pull image successfully.

**Actual behavior**
```
Error response from daemon: denied
```

**Additional context**

**Comment by xmaayy** [comment]
@yufansong You dont have permission for the docker daemon, this is not an issue with the repo
```bash
docker pull ghcr.io/opendevin/sandbox:v0.1
v0.1: Pulling from opendevin/sandbox
bccd10f490ab: Pull complete
7ec1b7f950f8: Pull complete
Digest: sha256:8b5dc51a8c725588c0abc024f9fc0f1e9d32341caa2342fe2cb99e7a2e4d30a3
Status: Downloaded newer image for ghcr.io/opendevin/sandbox:v0.1
ghcr.io/opendevin/sandbox:v0.1
```

You need to give yourself permission then log back in
``` bash
sudo usermod -aG docker $USER
```

**Comment by yufansong** [comment]
The problem solved in slark several hours ago after I proposed this issue. The image repo is public now, so that maybe the reason why you can work. 
Currently this problem should be solved.
