### ISSUE TITLE
[Bug]: ERROR: session.py:69 - Error creating controller: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by tansautn** [OpenDevin/OpenDevin#2702]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I think the error would be: pass a string into int().
The error in WSL terminal:
```
08:28:51 - opendevin:INFO: mixin.py:50 - Initializing plugin [jupyter] by executing [/opendevin/plugins/jupyter/setup.sh] in the sandbox.
08:31:59 - opendevin:ERROR: session.py:69 - Error creating controller: invalid literal for int() with base 10: 'Successfully installed MarkupSafe-2.1.5 argon2-cffi-23.1.0 argon2-cffi-bindings-21.2.0 arrow-1.3.0 asttokens-2.4.1 async-lru-2.0.4 attrs-23.2.0 babel-2.15.0 beautifulsoup4-4.12.3 bleach-6.1.0 cffi-1.
Traceback (most recent call last):
  File "/app/opendevin/server/session/session.py", line 67, in _initialize_agent
    await self.agent_session.start(data)
  File "/app/opendevin/server/session/agent.py", line 47, in start
    await self._create_controller(start_event)
  File "/app/opendevin/server/session/agent.py", line 104, in _create_controller
    self.runtime.init_sandbox_plugins(agent.sandbox_plugins)
  File "/app/opendevin/runtime/runtime.py", line 91, in init_sandbox_plugins
    self.sandbox.init_plugins(plugins)
  File "/app/opendevin/runtime/plugins/mixin.py", line 61, in init_plugins
    _exit_code = output.exit_code()
                 ^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/docker/ssh_box.py", line 48, in exit_code
    return int(_exit_code)
           ^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Successfully installed MarkupSafe-2.1.5 argon2-cffi-23.1.0 argon2-cffi-bindings-21.2.0 arrow-1.3.0 asttokens-2.4.1 async-lru-2.0.4 attrs-23.2.0 babel-2.15.0 beautifulsoup4-4.12.3 bleach-6.1.0 cffi-1.
```
### Current OpenDevin version

```bash
`0.6.2` as of command given on documents
```

### Installation and Configuration

```bash
WORKSPACE_BASE=/home/zuko/git/testopendevin
	 docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-test \
    ghcr.io/opendevin/opendevin:0.6.2
```

### Model and Agent

Model : claude3-sonnet-20240229
Agent : CodeActSWEAgent 

### Operating System

Windows 10 build 19045.
WSL 2 - Debian distro

### Reproduction Steps

Just run inside WSL as normal user (zuko - the default user created with distro installation)

### Logs, Errors, Screenshots, and Additional Context

[term-log.log](https://github.com/user-attachments/files/16043854/term-log.log)
WSL console log.

**Comment by tobitege** [comment]
Please use "main" instead of 0.6.2 at the end of the command.

**Comment by tansautn** [comment]
using the main version number, i got same issue. So i've push tiny fix. Hope that can help & merge

**Comment by tobitege** [comment]
@SmartManoj regression bug since https://github.com/OpenDevin/OpenDevin/pull/2642 ?

**Comment by tobitege** [comment]
@tansautn can you elaborate the steps where you added these exactly?
MarkupSafe-2.1.5 argon2-cffi-23.1.0 argon2-cffi-bindings-21.2.0 arrow-1.3.0 asttokens-2.4.1 async-lru-2.0.4 attrs-23.2.0 babel-2.15.0 beautifulsoup4-4.12.3 bleach-6.1.0 cffi-1
