### ISSUE TITLE
Handle further user input in FINISHED state

### ISSUE THREAD

**Issue by li-boxuan** [OpenDevin/OpenDevin#2710]
**What problem or use case are you trying to solve?**

Not every agent can handle further user inputs once they are "finished".

For example, for BrowsingAgent, when a task is finished, the chat panel is still active and allows inputs, even though it won't do anything:

<img width="324" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/25746010/bc380f28-40c8-4089-8ee7-c81d112ae3db">

<img width="1045" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/25746010/98fd7fa3-21b2-4f26-a7bf-c837b2076b3a">

Note: to reproduce this, you need to use BrowsingAgent. I am pretty sure DelegatorAgent has the same problem. Not sure about others...

**Describe the UX of the solution you'd like**

Two options:
1. Disable the chat textbox when **BrowsingAgent** has finished the task.
2. Better, make BrowsingAgent able to handle further tasks.

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by tobitege** [comment]
Can you elaborate what exactly you'd like to disable? The user's textarea for input?

**Comment by li-boxuan** [comment]
> Can you elaborate what exactly you'd like to disable? The user's textarea for input?

Yep

**Comment by tobitege** [comment]
> > Can you elaborate what exactly you'd like to disable? The user's textarea for input?
> 
> Yep

Ok, so if a task is "finished", why shouldn't the user be able to continue the chat session?

**Comment by li-boxuan** [comment]
> Ok, so if a task is "finished", why shouldn't the user be able to continue the chat session?

I thought simply disabling textarea is a simple and quick fix - likely one-liner.

Allowing the user to be able to continue the chat session sounds like a plan - we need backend changes though. We may also need to keep in mind that it could have other implications. For example, even though the user's intention is to start a new task, they might very likely continue using the same chat session and hit out-of-budget or max_iterations error pretty soon.

**Comment by tobitege** [comment]
I'm a bit confused right now what the disabling is trying to fix?
It is the "normal" user UI operation that I give smaller or bigger tasks.
Sometimes the LLM marks them as finished, but that doesn't mean that I as a user am finished.
Any other web UI has continouus chat, I don't see why we would suddenly limit it to an arbitrary "one task" use? 🤔

**Comment by li-boxuan** [comment]
> Sometimes the LLM marks them as finished, but that doesn't mean that I as a user am finished.

Did you try continue the chat even if LLM marks them as finished? Per my testing (see the screenshots in the first post) it won't do anything.

**Comment by li-boxuan** [comment]
I did more testing and realized it might just be an issue with certain agents: BrowsingAgent, DelegatorAgent, and probably more.

**Comment by tobitege** [comment]
I haven't had an issue with CodeActAgent stopping on me with being finished.
If your screenshot is coming from delegation (browser agent?), and it gets stuck on finish, sure, that needs backend fixes.
But till then disabling user input is not the right way.

**Comment by li-boxuan** [comment]
> Note: to reproduce this, you need to use an agent other than CodeAct*Agent which never finishes (before https://github.com/OpenDevin/OpenDevin/pull/2673 is merged).

CodeActAgent never "stops" so you won't have an issue 😉

**Comment by tobitege** [comment]
So glad about that! 🤣 

Kidding aside, should we just re-check that all agents can react appropriately send and/or parse the "finish" tag and act accordingly?

**Comment by li-boxuan** [comment]
> should we just re-check that all agents

Totally. I rewrote the description and removed "good first issue" label. This is harder than just disabling textarea. Even if we want to do it (because some agents are hard to take further input or by design they cannot), we shall do it only for certain agents.

**Comment by enyst** [comment]
> 1. For example, even though the user's intention is to start a new task, they might very likely continue using the same chat session and hit out-of-budget or max_iterations error pretty soon.

I wonder how much good do these limits for interactive sessions. For non-interactive sessions, sure.
