### ISSUE TITLE
[Bug]: The long filename will stretch the workspace panel

### ISSUE THREAD

**Issue by iFurySt** [OpenDevin/OpenDevin#2714]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

The issue manifests as follows:
<img width="1513" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/16201837/3468e1cc-352a-4483-a883-d6a37a11157e">

We can limit the maximum display length, or allow the panel to freely adjust its width and scroll along the x and y axes.

### Current OpenDevin version

```bash
0.7.0
```

### Installation and Configuration

```bash
Default configuration.
```

**Comment by iFurySt** [comment]
IMO, it will be good if we can adjust it like this:

https://github.com/OpenDevin/OpenDevin/assets/16201837/abd6815f-5dfe-4a97-8e55-088b2b2d5f95

But the VSCode just does an ellipsis like you said:

https://github.com/OpenDevin/OpenDevin/assets/16201837/2e3f915d-cb0d-43e1-91ef-e935044553e2

WDYT?

**Comment by iFurySt** [comment]
yep, just like you, I prefer scrolling.

**Comment by richardokonicha** [comment]
https://github.com/OpenDevin/OpenDevin/assets/48168290/9f2ef0b0-8975-48a0-b29b-88ae230d5258

something like this ?

**Comment by richardokonicha** [comment]
https://github.com/OpenDevin/OpenDevin/pull/2731
here I created a pull request for this fix. 

sidenote:
I was just exploring https://ui.shadcn.com/docs/components/resizable I think we could have a good use for these resizable components across. thoughts**

**Comment by mamoodi** [comment]
@iFurySt closing as scrolling seems implemented. Tested on main.
