### ISSUE TITLE
Add latest tag for docker image

### ISSUE THREAD

**Issue by yufansong** [OpenDevin/OpenDevin#272]
**What problem or use case are you trying to solve?**
Proposed [here](https://github.com/OpenDevin/OpenDevin/pull/263#issuecomment-2023918115). Better to add `latest` tag for image. Then user do not need to pull image at specific version. We also do not need to always change the tags in [code](https://github.com/OpenDevin/OpenDevin/blob/a9102382f6a56765eea34fdac0f04ca0f2305651/opendevin/sandbox/sandbox.py#L17).

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**
Need the pipeline builder to set it.

**Describe alternatives you've considered**

**Additional context**

**Comment by iFurySt** [comment]
![image](https://github.com/OpenDevin/OpenDevin/assets/16201837/f96415c0-ba9c-443a-ba23-b03f35e44070)

Actually, the workflow/ghcr.yaml will auto-generate the latest tag. So we only need to change the usage to let code pull the latest image. I'll change it later.
