### ISSUE TITLE
[Bug]: README says to use localhost but that causes 401 and 404 errors.

### ISSUE THREAD

**Issue by medined** [OpenDevin/OpenDevin#2727]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

After starting the docker container, I visited http://localhost:3000/ as the README says but that generated 401 and 404 errors.

### Current OpenDevin version

```bash
ghcr.io/opendevin/opendevin:0.7
```

### Installation and Configuration

```bash
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.7
```
```


### Model and Agent

The UI does not load because of the 401 and 404 errors.

### Operating System

Ubuntu

### Reproduction Steps

1. Run docker container.
```
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.7
```
2. Visit http://localhost:3000/


### Logs, Errors, Screenshots, and Additional Context

```
Running as enduser
/app/.venv/lib/python3.12/site-packages/llama_index_client/types/metadata_filter.py:20: SyntaxWarning: invalid escape sequence '\*'
  """
08:09:21 - opendevin:INFO: listen.py:100 - File upload config: max_size=0MB, restrict_types=False, allowed_extensions=['.*']
INFO:     Started server process [42]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
INFO:     172.17.0.1:46040 - "GET /api/v1/ HTTP/1.1" 401 Unauthorized
INFO:     172.17.0.1:46040 - "GET /_app/immutable/nodes/10.d09b2165.js HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:46040 - "GET /_app/version.json HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:46040 - "GET /_app/version.json HTTP/1.1" 404 Not Found
```

**Comment by tobitege** [comment]
Is this with Ubuntu as WSL? Can you try just CTRL+Click the link in your terminal "_**Uvicorn running on ...**_" to open the browser with it?

**Comment by medined** [comment]
Yes, the link in the terminal uses 0.0.0.0 as the hostname and it works.

**Comment by tobitege** [comment]
> Yes, the link in the terminal uses 0.0.0.0 as the hostname and it works.

Does that link still produce the errors like in your log above?

**Comment by medined** [comment]
Apologies. I don't mean to be dense. Yes, when 0.0.0.0 is used as the hostname, there are no 401 and 403 errors. I should have mentioned that but I did not see a "suggested resolution" section in the bug ticket.

**Comment by tobitege** [comment]
No worries, glad this way it works for you! 😃 
I'll close this issue for now, but feel free to reopen this one or create a new one shall an issue arise.

**Comment by tobitege** [comment]
Hey @Shimada666 could you provide a little insight why the localhost wouldn't work? 
Or is that covered in our troubleshooting page already?
You have way more expertise in that Docker area.

**Comment by Shimada666** [comment]
@tobitege 
Sorry, I don't really understand either. I didn't even see what was changed to make it work. 
> Running as enduser
/app/.venv/lib/python3.12/site-packages/llama_index_client/types/metadata_filter.py:20: SyntaxWarning: invalid escape sequence '*'
"""
08:09:21 - opendevin:INFO: listen.py:100 - File upload config: max_size=0MB, restrict_types=False, allowed_extensions=['.*']
INFO: Started server process [42]
INFO: Waiting for application startup.
INFO: Application startup complete.
INFO: Uvicorn running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
INFO: 172.17.0.1:46040 - "GET /api/v1/ HTTP/1.1" 401 Unauthorized
INFO: 172.17.0.1:46040 - "GET /_app/immutable/nodes/10.d09b2165.js HTTP/1.1" 404 Not Found
INFO: 172.17.0.1:46040 - "GET /_app/version.json HTTP/1.1" 404 Not Found
INFO: 172.17.0.1:46040 - "GET /_app/version.json HTTP/1.1" 404 Not Found

From the logs, using 0.0.0.0 got 401 and 404 errors. But why does say it worked? 🤔

**Comment by medined** [comment]
The original Getting Starting section used localhost instead of 0.0.0.0 in the URL in the STDOUT message. Clicking on the URL in the README caused the 401 and 404 errors because the web server is not configured to respond to external requests. I think (but have not verified this) that when starting uvicorn, you can use the "--host 0.0.0.0" parameter to tell the server to listen on all available network interfaces, making it accessible from any IP address that can reach the machine.

**Comment by medined** [comment]
I was using Brave on Ubuntu.

**Comment by SmartManoj** [comment]
Could you check if `localhost` works now?

**Comment by medined** [comment]
How could those paths not be related to OpenDevin when those messages were generated by univorn *inside* the OpenDevin docker container? 

I feel there is some communications gap between us. Are you familiar with the --host parameter for univorn? I feel that I can't explain the issue any better.

If nobody else is reporting a problem, I'm okay with declaring "user error" and closing the ticket.

**Comment by SmartManoj** [comment]
> Did you run any other project in that port?

If so, the following will happen.

> How could those paths not be related to OpenDevin when those messages were generated by univorn inside the OpenDevin docker container?

**Comment by SmartManoj** [comment]
> INFO: 172.17.0.1:46040 - "GET /api/v1/ HTTP/1.1" 401 Unauthorized

The 401 entry  is due to that it checks for all `/api/` paths
https://github.com/OpenDevin/OpenDevin/blob/ad1e44585b220dabf112631d8c528565ad51b73f/opendevin/server/listen.py#L156-L166

The remaining paths are not there.

**Comment by medined** [comment]
I don't see any reason to keep this issue open. Has it been resolved? I think the issue has been adequately discussed and others do not consider my observation valid. That's OK. Keep up the great work.

**Comment by SmartManoj** [comment]
> Could you check if `localhost` works now?

If so, you can close it.

**Comment by medined** [comment]
Localhost is now working.
