### ISSUE TITLE
Mention OPENAI_API_KEY in "Getting Started" Section of README.

### ISSUE THREAD

**Issue by medined** [OpenDevin/OpenDevin#2729]
**What problem or use case are you trying to solve?**

When starting the container, no responses were possible because the OPENAI_API_KEY was not supplied by the docker run command.

**Describe the UX of the solution you'd like**

Update the README to indicate that the default is to use OpenAI API and how it should be configured.

**Do you have thoughts on the technical implementation?**

Add a sub-section something like:

The default is to use the Openai API. To use this default, set an environment variable:

export OPENAI_API_KEY=sk-XXXXX

Then add this following to the docker run command:

-e OPENAI_API_KEY=$OPENAI_API_KEY \

**Describe alternatives you've considered**

**Additional context**

**Comment by tobitege** [comment]
For reference: https://docs.all-hands.dev/modules/usage/llms

**Comment by tobitege** [comment]
You do not have to use that environment variable. Once you have the UI open in the browser, you can configure your settings with click on the bottom-right cogtooth button (model, llm url, llm api key)

**Comment by medined** [comment]
### Below is a suggestion for rewording the Getting Started section of the README file.

The easiest way to run OpenDevin is inside a Docker container by following these steps. Adjust as needed for your particular needs.
- Create an environment variable to tell the container where on the host machine to store files. As the container runs, the files in this workspace may be modified or deleted.
```
export WORKSPACE_BASE=$(pwd)/workspace
```
- If you'd like, you can create an environment variable to tell the container the API key for OpenAI. Another approach is to click the gear at the bottom right of the web page after the container is running. Without using one of these options, OpenDevin will encounter errors as it attempts to respond to user prompts.
```
export OPENAI_API_KEY=sk-XXXXX
```
- Run the docker container. This particular command runs the container in interactive mode. This means you'll see STDOUT mesages scroll by as the container initializes and runs. When you see a  line that contains "Uvicorn running" then the container is ready. Stop the container by using ctrl-c. This will stop and remove the container. As of 2024-07-01, make sure to specify the "0.7" version because the "latest" tag is an older version. Optionally add "-e OPENAI_API_KEY=$OPENAI_API_KEY \" if you want to pass the OpenAI API key to the container.
```shell
docker run -it \
    --rm \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin \
    ghcr.io/opendevin/opendevin:0.7
```
- Visit [http://0.0.0.0:3000](http://0.0.0.0:3000/) to see OpenDevin in action. OpenDevin will only have access to the  workspace folder on the host machine. The rest of your system will not be affected as it runs in a secure docker sandbox.
- Until you learn more, leave the CodeActAgent Agent selected in the configuration settings.
If you are ready to run OpenDevin all the time (in the background), use the following version of the docker command:
```
docker run -d \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e OPENAI_API_KEY=$OPENAI_API_KEY \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name OpenDevin \
    --restart unless-stopped \
    ghcr.io/opendevin/opendevin:0.7
```
As needed, you can see the STDOUT of the container using this command. Press ctrl-c when you want to stop viewing the logs.
```
docker logs -f OpenDevin
```

Just to get you started, here are a sequence of instructors to create a simple python script and unit tests.
 - Create a module for some basic functionality.
```
create a python module that serves as a number generator. As needed, i will pass start and end numbers. Then I want to iterate over the range of the two numbers.
```
- Create and run unit tests.
```
now create a comprehensive suite of unit tests that can be run using pytest.
```
- Run pylint to perform static code analysis and fix any issues found.
```
lastly, run pylint and fix any issues that it finds.
```

**Comment by mamoodi** [comment]
@medined curious did the settings UI not pop open the first time you ran OpenDevin?
When you run OpenDevin for the first time it brings up the settings UI because that's the easiest way to get up and running.

**Comment by mamoodi** [comment]
Ah I understand! OpenDevin doesn't only work with OpenAI though so I'm wondering if having a note under the command that says something along the lines of:
"For OpenDevin to work, you will require a LLM API key which is set in the settings UI that pops up open opening OpenDevin."

would help with this issue?

(Not exactly those words but some mention of it may help?)

**Comment by medined** [comment]
Yes. Thank you. That cuts to the heart of the matter. I'm a big fan of
explicit step-by-step instructions but realize that maintaining that level
of documentation is hard.

**Comment by mamoodi** [comment]
For sure. I understand. We will address this soon. Thanks for bringing it up.

**Comment by mamoodi** [comment]
Updated README with instructions that you must select Model and put in an API key
