### ISSUE TITLE
Couple of steps results Error sending data to client

### ISSUE THREAD

**Issue by skadaba1** [OpenDevin/OpenDevin#273]
**Describe the bug**
After a couple of reasoning steps the web-socket unexpectedly closes? Saw this error posted previously and a fix was merged however my repo is up to date, still getting this error. 

**Steps to Reproduce**
1.
2.
3.

**Expected behavior**

**Actual behavior**

**Additional context**

Error sending data to client 
Error sending data to client 
Error sending data to client 
Client websocket disconnected (<CloseCode.ABNORMAL_CLOSURE: 1006>, None)
INFO:     connection closed

**Comment by rbren** [comment]
Deduping with https://github.com/OpenDevin/OpenDevin/issues/235
