### ISSUE TITLE
[Bug]: Release "latest" tag when pushing image to DockerHub

### ISSUE THREAD

**Issue by medined** [OpenDevin/OpenDevin#2730]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When I pull the opendevin image without using a label, it downloads an image that is two **months** old. However, there is a 0.7 image that is only two **days** old. Please keep the "latest" tag current with the newest version.

```
ghcr.io/opendevin/opendevin                     0.7                       0d240a96195f   2 days ago      7.09GB
ghcr.io/opendevin/opendevin                     latest                    ce6e72faf570   2 months ago    6.83GB
```

I feel this is important so that documentation (such as the Getting Started section of the README) does not need to change from version to version.

### Current OpenDevin version

```bash
N/A
```

### Installation and Configuration

```bash
N/A
```

**Comment by richardokonicha** [comment]
```- name: Capture tags
  id: capture-tags
  run: |
    tags=$(cat tags.txt)
    echo "tags=$tags"
    echo "tags=$tags" >> $GITHUB_OUTPUT
```
https://github.com/OpenDevin/OpenDevin/blob/main/.github/workflows/ghcr.yml


tags.txt might not include the "latest" tag

**Comment by medined** [comment]
Where is the tags.txt file located? I don't see it in the gitgub project.

**Comment by iFurySt** [comment]
Currently, the default tag is `main`

**Comment by richardokonicha** [comment]
we'd probably need to also have it shipped with `ghcr.io/opendevin/opendevin:latest` to keep the 'latest' referenced to the most recent build. 

to put simply
```
tags: |
  ghcr.io/opendevin/opendevin:${{ current version }}
  ghcr.io/opendevin/opendevin:main
  ghcr.io/opendevin/opendevin:latest
```

**Comment by richardokonicha** [comment]
> Where is the tags.txt file located? I don't see it in the gitgub project.

@medined its created during docker image build, you can see a reference to the file creation here where it happens. 
https://github.com/richardokonicha/OpenDevin/blob/main/containers/build.sh

**Comment by richardokonicha** [comment]
though the solution seems straightforward here, we need to add the latest tag, we can do so like `tags+=("latest")`

however, we should decide when to apply 'latest' on all builds or only when building a release version e.g (0.7.0)
```

if [[ -n $GITHUB_REF_NAME ]]; then
  # check if ref name is a version number
  if [[ $GITHUB_REF_NAME =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    major_version=$(echo "$GITHUB_REF_NAME" | cut -d. -f1)
    minor_version=$(echo "$GITHUB_REF_NAME" | cut -d. -f1,2)
    tags+=("$major_version" "$minor_version")
    
    tags+=("latest")  # This will add latest only when we build for stable version numbers
    
  fi
  sanitized=$(echo "$GITHUB_REF_NAME" | sed 's/[^a-zA-Z0-9.-]\+/-/g')
  OPEN_DEVIN_BUILD_VERSION=$sanitized
  tag=$(echo "$sanitized" | tr '[:upper:]' '[:lower:]') # lower case is required in tagging
  tags+=("$tag")
  
  tags+=("latest")  # This will add latest every time we build a new container.  
   
fi
```
Your thoughts on this? 
@medined @iFurySt @neubig @xingyaoww

**Comment by tobitege** [comment]
> Your thoughts on this? @medined @iFurySt @neubig @xingyaoww

It's important that @li-boxuan is taking the lead on this on our side as that closely relates to the workflows in place.

**Comment by tobitege** [comment]
> As a clueless user, I'd expect the "latest" to be related to the current release. Using the "latest" tag states my implicit trust in your development process. I trust that enough new features have been added, bugs have been fixed, and that the risk to my own project has been minimized.

However, on the main page we do state to use 0.7 as the container name, not latest, and we might not even change that should latest make a return.
Latest can also be similar to "nightly" in other software areas, thus not necessarily bug free, but cutting edge. 😏

**Comment by richardokonicha** [comment]
I couldn't agree more @medined there is an implicit trust in the 'latest'. 

What this means is that we would want to add the 'latest' only when we build for stable releases with semantic version numbers e.g (0.7.0)

```
if [[ $GITHUB_REF_NAME =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    major_version=$(echo "$GITHUB_REF_NAME" | cut -d. -f1)
    minor_version=$(echo "$GITHUB_REF_NAME" | cut -d. -f1,2)
    tags+=("$major_version" "$minor_version")
    
    tags+=("latest")  # This will add latest only when we build for stable version numbers
    
  fi
```

Thanks @tobitege for the mention, there is indeed an advantage to making latest to be sort of nightly, 

I'll hold until @li-boxuan to gives the final on this.

**Comment by richardokonicha** [comment]
> Currently, the default tag is `main`

@tobitege this true 
though what occurs to me is that when a novice user tries to pull, they would most likely do this simply like so 
`docker pull ghcr.io/opendevin/opendevin` and this pulls 'latest' at the moment as the default tag. 

<img width="971" alt="Screenshot 2024-07-03 at 2 25 29 PM" src="https://github.com/OpenDevin/OpenDevin/assets/48168290/ac6acb54-7a99-463f-91d1-e01eb63f5a46">

**Comment by tobitege** [comment]
See? that's why I'm not the lead in that area 🤣  I think we defaultet to latest just a couple of days ago, iirc.

**Comment by tobitege** [comment]
I think the confusion is the opposite for users (incl. myself), from what I read.. latest release vs latest build is so ambivalent.

**Comment by iFurySt** [comment]
> > however, we should decide when to apply 'latest' on all builds or only when building a release version e.g (0.7.0)
> 
> 
> 
> I'm definitely leaning more towards tagging "latest" when we build a release version (0.7.0) and keeping the `main` tag as the "nightly" version - so it reduces the confusion from the user's end?

I agree with that too.

**Comment by xingyaoww** [comment]
@iFurySt Any idea how we can implement it? I'm not super familiar with the workflow stuff otherwise i can help too..

**Comment by tobitege** [comment]
Re: "latest", I'll follow you guys with that.
We just need to add some clear hints on the frontpage, what's what, and what options exist at all, I guess.
Latest -> latest release; 0.7 -> specific release and "main" for current, something along those lines?
About how to go about it: I'd like to have @li-boxuan involved here as he did a lot of work in that area already, wdyt?

**Comment by richardokonicha** [comment]
> @iFurySt Any idea how we can implement it? I'm not super familiar with the workflow stuff otherwise i can help too..

I can create a PR for this one once @li-boxuan gives the final on this.

**Comment by medined** [comment]
Can you suggest wording other than "main for current"? Perhaps main is the
development version and corresponds to the main branch in GitHub?

Suggested Wording. I don't like the word bugs but can't think of an
alternative at the moment.

The "main" docker image should only be used by someone willing to put up
with occasional bugs. It's not designed for someone who "just wants it to
work".

**Comment by tobitege** [comment]
Oh, I was shothanding the wording, I wasn't suggesting to use that verbatim. 😬 
With main we indeed mean the "main branch", which is the cutting-edge, but also the version that gets the bug fixes in "first", if need be.

**Comment by li-boxuan** [comment]
@richardokonicha Your proposal sounds perfect to me. When we tag release versions we should add latest tag, and seems you have already figured out how to do it!

**Comment by iFurySt** [comment]
> @iFurySt Any idea how we can implement it? I'm not super familiar with the workflow stuff otherwise i can help too..

We can trigger building the image with the latest tag when a new release is detected in the workflow. This way, we can keep the main branch as-is for a nightly version.

@richardokonicha Do you want to give it a try and submit a PR?

**Comment by richardokonicha** [comment]
sure thing

**Comment by enyst** [comment]
I think this has been solved so I'll close it, thank you @richardokonicha !
