### ISSUE TITLE
[Documentation]: Custom docker image instructions should note that you can use a pre-existing docker image

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#2734]
**What problem or use case are you trying to solve?**

In our custom sandbox guide: https://github.com/OpenDevin/OpenDevin/blob/41ddba84bd0d62f8a4bc48d08addde4b4269a687/docs/modules/usage/custom_sandbox_guide.md?plain=1

We state that you can create a custom sandbox by creating your own docker image, then specifying it. But actually it's also easy to use an existing docker image from the docker hub, e.g. the following code if you want a sandbox with node installed:

```python
sandbox = DockerSSHBox(
   container_image="node:21"
)
```

It'd be nice to make it clear that creating your own custom image is optional.

**Comment by richardokonicha** [comment]
ready for review.

**Comment by enyst** [comment]
This has been fixed by the linked PR, so I'll close it. Please re-open if that's not the case.
