### ISSUE TITLE
How OpenDevin Docks with Private Domain Models

### ISSUE THREAD

**Issue by zhangshu0** [OpenDevin/OpenDevin#2757]
我在使用“make setup”来配置config.toml后配置了一个我私域的模型，尽管他不在litellm默认支持的里面，但是会提示我：“litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=“abc” 请问我应该如何接入litellm默认列表中没有的模型

**Comment by tobitege** [comment]
please be so kind to use Google translate for English 😃

**Comment by tobitege** [comment]
Maybe this helps?
https://docs.all-hands.dev/modules/usage/llms/localLLMs

**Comment by zhangshu0** [comment]
> Maybe this helps? https://docs.all-hands.dev/modules/usage/llms/localLLMs

My model is not in Ollama, it is a private domain deployment model

**Comment by tobitege** [comment]
Right. But did you specify an API URL for your custom model then?

**Comment by zhangshu0** [comment]
> 是的。但是，您是否为自定义模型指定了 API URL？

this is my config.toml :  [core]
workspace_base="./workspace"
persist_sandbox=false

[llm]
model="chatrhino/Chatrhino-14B"
base_url="http://gpt-proxy.com/gateway/common"
embedding_model="text-embedding-ada-002-2"

**Comment by zhangshu0** [comment]
> > 是的。但是，请指定自定义模型指定的 API URL？
> 
> 这是我的 config.toml ： [core] workspace_base="./workspace" persist_sandbox=false
> 
> [llm] 模型="chatrhino/Chatrhino-14B" base_url=" http://gpt-proxy.com/gateway/common " embedding_model="text-embedding-ada-002-2"
Apikey did not reply to you

**Comment by tobitege** [comment]
I think this better asked in the litellm repository or searched in their docs:
https://github.com/BerriAI/litellm
https://litellm.vercel.app/docs/

**Comment by zhangshu0** [comment]
> I think this is better asked in the litellm repository or searched in their docs: https://github.com/BerriAI/litellm https://litellm.vercel.app/docs/

I would like to ask if OpenDevin supports docking with private domain models. If so, should specific operating steps be provided, such as how to configure config.toml or what configuration files need to be provided for litellm?

**Comment by zhangshu0** [comment]
> > 我认为最好在 litellm 存储库中询问或在他们的文档中搜索：[https://github.com/BerriAI/litellm ](https://github.com/BerriAI/litellm) https://litellm.vercel.app/docs/
> 
> 请问OpenDevin是否支持与私有领域模型对接，如果支持的话是否能提供具体的操作步骤，比如如何配置config.toml或者litellm需要提供哪些配置文件？

How can I integrate into OpenDevin even if I can configure my private domain model after reading the document from Litellm? I couldn't find the complete answer to this scene online either

**Comment by tobitege** [comment]
It is unclear still which parameters are needed by litellm. If you have it working outside OpenDevin and could provide us the flags you pass on to litellm, then I hope to be of more help to you.

**Comment by zhangshu0** [comment]
> 目前还不清楚 litellm 需要哪些参数。如果您在 OpenDevin 之外使用它，并且可以向我们提供您传递给 litellm 的标志，那么我希望对您有所帮助。

Is there a plan for OpenDevin to support users to connect with private domain models in the later stage? If so, what is the approximate time

**Comment by tobitege** [comment]
I'll try to look into this issue, but it'll take a little bit, please give me a couple of days.
You should be able to pass litellm-specific values with the "-e" parameter into the sandbox if you start OpenDevin via the docker command, but I don't know the exact value litellm is expecting for your case.

**Comment by zhangshu0** [comment]
> 我会尝试调查这个问题，但这需要一点时间，请给我几天时间。 如果您通过 docker 命令启动 OpenDevin，您应该能够使用“-e”参数将特定于 litellm 的值传递到沙盒中，但我不知道 litellm 在您的案例中期望的确切值。

docker run -it \
--pull=always \
-e SANDBOX_USER_ID=$(id -u) \
-e PERSIST_SANDBOX="true" \
-e SSH_PASSWORD="abc" \
-e LLM_BASE_URL="[http://gpt-proxy.com/gateway/](http://gpt-proxy.jd.com/gateway/common/chat/completions)common” \
-e LLM_MODEL="chatrhino/Chatrhino-14B" \
-e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
-v $WORKSPACE_BASE=/opt/workspace_base \
-v /var/run/docker.sock:/var/run/docker.sock \
-p 3000:3000 \
--add-host host.docker.internal:host-gateway \
--name opendevin-app-$(date +%Y%m%d%H%M%S) \
ghcr.io/opendevin/opendevin:0.6

**Comment by zhangshu0** [comment]
> 我会尝试调查这个问题，但这需要一点时间，请给我几天时间。 如果您通过docker命令启动OpenDevin，您能够使用“-e”参数将特定于litellm的值传递到沙盒中，但我不知道litellm在您的案例中期望的判决值。

docker run -it \
--pull=always \
-e SANDBOX_USER_ID=$(id -u) \
-e PERSIST_SANDBOX="true" \
-e SSH_PASSWORD="abc" \
-e LLM_BASE_URL="http://gpt-proxy.com/gateway/common"  \
-e LLM_MODEL="chatrhino/Chatrhino-14B" \
-e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
-v $WORKSPACE_BASE=/opt/workspace_base \
-v /var/run/docker.sock:/var/run/docker.sock \
-p 3000:3000 \
--add-host host.docker.internal:host-gateway \
--name opendevin-app-$(date +%Y%m%d%H%M%S) \
ghcr.io/opendevin/opendevin:0.6

**Comment by zhangshu0** [comment]
> > 我会尝试调查这个问题，但这需要一点时间，请给我几天时间。 如果您通过docker命令启动OpenDevin，您能够使用“-e”参数将特定于litellm的值传递到沙盒中，但我不知道litellm在您的案例中期望的判决值。
> 
> docker run -it --pull=always -e SANDBOX_USER_ID=$(id -u) -e PERSIST_SANDBOX="true" -e SSH_PASSWORD="abc" -e LLM_BASE_URL="http://gpt-proxy.com/gateway/common" -e LLM_MODEL="chatrhino/Chatrhino-14B" -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE -v $WORKSPACE_BASE=/opt/workspace_base -v /var/run/docker.sock:/var/run/docker.sock -p 3000:3000 --add-host host.docker.internal:host-gateway --name opendevin-app-$(date +%Y%m%d%H%M%S) ghcr.io/opendevin/opendevin:0.6

error message: During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/opendevin/controller/agent_controller.py", line 135, in _start_step_loop
    await self._step()
  File "/app/opendevin/controller/agent_controller.py", line 343, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agenthub/codeact_agent/codeact_agent.py", line 207, in step
    response = self.llm.completion(
               ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 209, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1001, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 881, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2582, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 7644, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 7608, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=Chatrhino-14B
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 805, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
                                                            ^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4386, in get_llm_provider
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4363, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=Chatrhino-14B
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

**Comment by tobitege** [comment]
As far as I can tell from the documentation, you could try to add the below parameters to the docker command.
```
-e OPENAI_API_KEY=anything
-e CUSTOM_LLM_PROVIDER=openai
``` 

Please find "Example Usage" in the documentation by litellm for custom api server:
https://docs.litellm.ai/docs/providers/custom_openai_proxy

**Comment by zhangshu0** [comment]
> -e OPENAI_API_KEY=anything
> -e CUSTOM_LLM_PROVIDER=openai

it's still report error:  llm.py:176 - litellm.APIConnectionError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=chatrhino/Chatrhino-14B
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 805, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
                                                            ^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4386, in get_llm_provider
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4363, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=chatrhino/Chatrhino-14B
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
. Attempt #5 | You can customize these settings in the configuration.
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 805, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
                                                            ^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4386, in get_llm_provider
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4363, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=chatrhino/Chatrhino-14B
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

My startup script is：docker run -it \
--pull=always \
-e SANDBOX_USER_ID=$(id -u) \
-e PERSIST_SANDBOX="true" \
-e SSH_PASSWORD="abc" \
-e LLM_BASE_URL="http://gpt-proxy.jd.com/gateway/common"  \
-e LLM_MODEL="Chatrhino-14B" \
-e OPENAI_API_KEY="c2b530e2-100d-4c76-a9b0***" \
-e CUSTOM_LLM_PROVIDER="chatrhino" \
-e LLM_EMBEDDING_MODEL="text-embedding-ada-002-2" \
-e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
-v $WORKSPACE_BASE=/opt/workspace_base \
-v /var/run/docker.sock:/var/run/docker.sock \
-p 3000:3000 \
--add-host host.docker.internal:host-gateway \
--name opendevin-app-$(date +%Y%m%d%H%M%S) \
ghcr.io/opendevin/opendevin:main.  
![7bcb71e1-8c6e-464b-85b8-3a646eddfa4e](https://github.com/OpenDevin/OpenDevin/assets/27984294/dd2508e1-1074-499d-9af3-aa5c8b78f121)

**Comment by tobitege** [comment]
That is as much help I can provide. This is an litellm issue not OpenDevin.
You can pass the values into via "-e", but for what exactly is needed in your case, you may have to consult litellm.

**Comment by mamoodi** [comment]
@tobitege based on your last comment, can this issue be closed if it's an litellm issue?
