### ISSUE TITLE
bug: handle context window exceeded error appropriately

### ISSUE THREAD

**Issue by tobitege** [OpenDevin/OpenDevin#2823]
### Discussed in https://github.com/OpenDevin/OpenDevin/discussions/2739

<div type='discussions-op-text'>

<sup>Originally posted by **Jadow44** July  2, 2024</sup>
Good afternoon,
I am French and I use a translator and I do not have much notion of coding. If you want to help me can give you details so that I can make the corrections.
I’m on mac, I installed the docker that works properly and I put a key for GPT.
I think I correctly installed the program, but not otherwise it would work!!! -)
here is the first message when I launch the application:

0.7: Pulling from opendevin/opendevin
Digest: sha256:fa41135b3800d07b7bb7850c072914580a0107cee706f8bfe1b3691b7b7eaaad
Status: Image is up to date for ghcr.io/opendevin/opendevin:0.7
Starting OpenDevin...
Setting up enduser with id 501
Docker socket group id: 0
root:x:0:
Group with id 0 already exists
Running as enduser
/app/.venv/lib/python3.12/site-packages/llama_index_client/types/metadata_filter.py:20: SyntaxWarning: invalid escape sequence '\*'
  """
12:44:11 - opendevin:INFO: listen.py:100 - File upload config: max_size=0MB, restrict_types=False, allowed_extensions=['.*']
INFO:     Started server process [36]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)</div>

Error message in log:
File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 5811, in exception_type
raise **ContextWindowExceededError**(
litellm.exceptions.ContextWindowExceededError: litellm.BadRequestError: litellm.ContextWindowExceededError: ContextWindowExceededError: OpenAIException - Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, you requested 8277 tokens (4181 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

08:47:41 - OBSERVATION
ErrorObservation(content='There was an unexpected error while running the agent', observation='error')

**Comment by SmartManoj** [comment]
Instead, it will be solved by #2021
