### ISSUE TITLE
starts from an existing projext

### ISSUE THREAD

**Issue by clipsheep6** [OpenDevin/OpenDevin#284]
**What problem or use case are you trying to solve?**

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

currently the agent always starts from scratch, but some time we also need add feature/fix bug from previous project (e.g. just generate by opendevin)

**Comment by yimothysu** [comment]
Hi @clipsheep6, we just added a directory feature where you can specify the directory OpenDevin starts in. You can set this directory path to an existing project. Does this work for you?

**Comment by rbren** [comment]
Yup--you can also point it to an existing directory with the `WORKSPACE_DIR` env var or config.toml var
