### ISSUE TITLE
Additional install required for Gemini

### ISSUE THREAD

**Issue by jojeyh** [OpenDevin/OpenDevin#285]
**Describe the bug**
Setting environment to use Gemini Pro results in error unless an additional package is installed.  I'm opening the issue cause not sure how the maintainers want it handled.  Should we add to `requirements.txt` or add instructions to `README`  to check LiteLLM for model specific install ?

**Steps to Reproduce**
```
export LLM_MODEL=gemini/gemini-pro
export LLM_API_KEY=....GEMINI_API_KEY...
python opendevin/main.py -d ./workspace/ -i 100 -t "Write a bash script that prints hello world"
```

**Expected behavior**
Runs normally

**Actual behavior**
Requires additional pip install

**Additional context**

**Comment by iFurySt** [comment]
Hey, maybe you need to add PYTHONPATH=`pwd` before the command. just see this:
[https://github.com/OpenDevin/OpenDevin?tab=readme-ov-file#running-on-the-command-line](https://github.com/OpenDevin/OpenDevin?tab=readme-ov-file#running-on-the-command-line)

**Comment by RohitX0X** [comment]
It would be helpful if you had specify what error did you get into

**Comment by jojeyh** [comment]
Sorry if I wasn't clear above.  The PYTHONPATH was already there as I set it before, forgot to include it.  
The error generated is 

Traceback (most recent call last):
  File "/home/anon/OpenDevin/.venv/lib/python3.10/site-packages/litellm/main.py", line 1620, in completion
    model_response = gemini.completion(
  File "/home/anon/OpenDevin/.venv/lib/python3.10/site-packages/litellm/llms/gemini.py", line 123, in completion
    raise Exception(
Exception: Importing google.generativeai failed, please run 'pip install -q google-generativeai

So to use Gemini a pip install is required.  LiteLLM is used to get completions and it works automatically with some models like those from OpenAI and Anthropic but requires separate package installation for some models like Gemini.  As stated in [https://docs.litellm.ai/docs/providers/gemini](LiteLLM docs) Gemini requires installing
```
pip install google-generativeai
```
Installing fixes my problem.  I opened this issue to ask what core maintainers would like to do. I could add a PR that just adds `google-generateai` to `requirements.txt` but it's unnecessary unless using Gemini.  Quickly looking over LiteLLM site it seems Google products are the only one that requires separate pip installaiton.

**Comment by rbren** [comment]
👍 this will probably be an issue for other providers too. We have the same issue with embeddings.

Feel free to add this one to `requirements.txt`--it'll be common enough that we should support it out of the box

**Comment by jojeyh** [comment]
Ok sounds good, will close and open PR
