### ISSUE TITLE
[Bug]: azure open ai config

### ISSUE THREAD

**Issue by yanivvak** [OpenDevin/OpenDevin#2866]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Based on the documentation I ran the azure open ai config, I managed to open the ui but i got :
Agent encountered an error.

Would it be possible to give an example of azure openai configuration,
this one is not so clear : https://docs.all-hands.dev/modules/usage/llms/azureLLMs#azure-openai-configs

### Current OpenDevin version

```bash
ghcr.io/opendevin/opendevin
```

### Installation and Configuration

```bash
I ran this command in the terminal:

WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -e LLM_BASE_URL="https://xxx.openai.azure.com/" \  
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin
```

### Operating System

WSL

### Logs, Errors, Screenshots, and Additional Context

 File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 7496, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: AzureException APIConnectionError - 'NoneType' object has no attribute 'split'

**Comment by SmartManoj** [comment]
> ```shell
> -e LLM_BASE_URL="https://xxx.openai.azure.com/" \
> ```

Like this, you need to pass the remaining environment variables.

**Comment by SmartManoj** [comment]
Could you run this to check whether the API is working properly?
```python
from litellm import completion
from datetime import datetime
import os

if os.path.exists('config.toml'):
    from toml import load
    config = load('config.toml')
else:
    config = {
        'LLM_MODEL': 'gpt-4-turbo-2024-04-09',
        'LLM_API_KEY': 'your-api-key',
        'LLM_BASE_URL': None
    }

messages = [{ "content": "If there are 10 books in a room and I read 2, how many books are still in the room?","role": "user"}]
dt = datetime.now()
response = completion(model=config['LLM_MODEL'], 
                        api_key=config['LLM_API_KEY'],
                        base_url=config['LLM_BASE_URL'],
                      messages=messages)

content = response.choices[0].message.content
print(content)

if '8' in content:
    print('--> Correct answer! 🎉')
    print('There are still 10 books in the room; reading them does not reduce the count. Consider exploring more accurate models for better results.')

dt2 = datetime.now()
print('Used model:',config['LLM_MODEL'])
print(f"Time taken: {(dt2-dt).total_seconds():.1f}s")
```

**Comment by SmartManoj** [comment]
> api version can use the default

I think you need to pass that too.

https://litellm.vercel.app/docs/providers/azure

**Comment by yanivvak** [comment]
it's working , 
what is the structure of the command, is it
   -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -e LLM_BASE_URL="https://xx.openai.azure.com/" \
    -e LLM_MODEL="azure/gpt-4o" \
    -v $WORKSPACE_BASE:/opt/workspace_base \

**Comment by SmartManoj** [comment]
Yes

**Comment by yanivvak** [comment]
The notebook is working but there's a problem with the command structure i tried various options and it didn't work

**Comment by enyst** [comment]
@yanivvak can you please send with -e the two variables for api base and api version, as you did, then open the UI and choose the model in the Settings box, same for the key.

**Comment by yanivvak** [comment]
@enyst  thanks, I tried it:
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -e LLM_BASE_URL="https://xx.openai.azure.com/" \
    -e LLM_API_VERSION = "2024-02-15-preview" \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin
docker: invalid reference format.
See 'docker run --help'.

* I tried with deployment name as well and it didn't work

**Comment by SmartManoj** [comment]
Did you run in powershell?

https://stackoverflow.com/a/51379726/5033247

**Comment by yanivvak** [comment]
I ran it with wsl(inside power shell), the thing is that I manage to run the docker with the ui, but when I add azure credentials, i get this response

**Comment by SmartManoj** [comment]
Could you provide a screenshot of the error?

**Comment by yanivvak** [comment]
@SmartManoj  "you must be using Linux, Mac OS, or WSL on Windows"(documentation)
When I run this command from WSL the docker and ui is working
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin

**when i try to add azure credentials I'm getting the above error, I guess it is related to command structure because I managed to run the code snippet of litellm that you sent me

**Comment by SmartManoj** [comment]
> Could you run it in CMD?

You need to type wsl in cmd and enter this command. 

Could you provide the screenshot of the error?

**Comment by yanivvak** [comment]
Again when I run it with on wsl without api key it's working, the problem is with the structure of the command with the credentials

WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -e LLM_BASE_URL="https://x.openai.azure.com/" \
    -e LLM_API_KEY="x" \
    -e LLM_MODEL="azure/gpt-4o" \
    -e LLM_API_VERSION = "2024-02-15-preview" \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin
docker: invalid reference format.
See 'docker run --help'.
-e: command not found

**Comment by yanivvak** [comment]
BTW I used open ai key and it did work, but after a while i got a 429 error so it's quota issues, this is why I'm struggling to deploy with azure which I don't have quota issues

**Comment by yanivvak** [comment]
Great, it's working, can you please change your documentation, as this space is in the original documentation :(you can add your command as an example)
LLM_BASE_URL="<azure-api-base-url>"          # e.g. "https://openai-gpt-4-test-v-1.openai.azure.com/"
LLM_API_KEY="<azure-api-key>"
LLM_MODEL="azure/<your-gpt-deployment-name>"
LLM_API_VERSION = "<api-version>"          # e.g. "2024-02-15-preview"

**Comment by mamoodi** [comment]
@yanivvak now that the docs have been updated with this fix, are we good to close this issue?

**Comment by yanivvak** [comment]
Sure, thanks!
