### ISSUE TITLE
Toolkit in the UI

### ISSUE THREAD

**Issue by anikamurarka** [OpenDevin/OpenDevin#2896]
**I tried using the UI and except the assistant part, the other tabs werent that intuitive**

**It can have the following features:
- description of that particular tab
- next button
- previous button
- skip button **

**info button at every tab to revisit it**

**Comment by mamoodi** [comment]
Hello there! Could you please clarify a bit more on which tabs weren't intuitive?
Are you referring to Code Editor, Browser, Jupyter and terminal tabs?
And could you please clarify what you mean by next/previous/skip buttons? What would these buttons accomplish and where would they be located?
