### ISSUE TITLE
[Bug]: After building from source using Ollama's local LLM on an AMD W7900 GPU, problems occurred.

### ISSUE THREAD

**Issue by liangyong928** [OpenDevin/OpenDevin#2909]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

After running make build, I saw that Docker was being pulled (I thought building from source would avoid using Docker).
During the make build process, I noticed CUDA being installed. I am using an AMD W7900 GPU and am unsure if there is a conflict.
I am remotely accessing the PC. During the WebUI installation, remote access became unavailable. Even after remotely rebooting the PC, I couldn’t reconnect, possibly because the installation of CUDA caused the AMD W7900 GPU to stop displaying.
Is it possible not to install CUDA during the make build process? Can building from source avoid using Docker?

### Current OpenDevin version

```bash
It is probably the latest version, and the source code is downloaded using git clone https://github.com/OpenDevin/OpenDevin.git.
```

### Installation and Configuration

```bash
The content of config.toml is:
LLM_MODEL="ollama/qwen2:72b-instruct"
LLM_API_KEY="ollama"
LLM_EMBEDDING_MODEL="local"
LLM_BASE_URL="http://localhost:11434"
WORKSPACE_BASE="./workspace"

make build
```

**Comment by SmartManoj** [comment]
> Is it possible not to install CUDA during the make build process?

Could you provide a Screenshot to check at which stage it is installed?



> Can building from source avoid using Docker?

Docker is needed for the sandbox.

**Comment by mamoodi** [comment]
There is this issue that may be related: https://github.com/OpenDevin/OpenDevin/issues/794

**Comment by liangyong928** [comment]
I tried remote connection again, and it turns out it works now.
(1) Version Information:

```
(base) yong@yong-System:~/OpenDevin/logs$ git log
commit 2df1d67007b983cce24fa8fea1d6234e32186dd8 (HEAD -> main, origin/main, origin/HEAD)
Author: Engel Nyst <enyst@users.noreply.github.com>
Date:   Mon Jul 8 05:10:21 2024 +0200

    History clean up (#2849)

    * clean up add_history

    * refactor last agent message

commit c6aa50779d03e703cefc1dd754ae95f3ee0d8f1f
Author: மனோஜ்குமார் பழனிச்சாமி <smartmanoj42857@gmail.com>
Date:   Mon Jul 8 03:22:03 2024 +0530

    Update regenerate.sh (#2832)

commit ba0f57c2798ce09735761d2c9f8033c83c8455ca
Author: Ralf D. Müller <ralf.d.mueller@gmail.com>
Date:   Sun Jul 7 23:32:56 2024 +0200

    added netcat to the requirements (#2822)
```
(2) Is the sandbox necessary?
```
~/OpenDevin$ cat config.toml
[core]
workspace_base="./workspace"
persist_sandbox=false

[llm]
model="ollama/qwen2:72b-instruct"
api_key="ollama"
base_url="http://localhost:11434/"
embedding_model="local"
```
Does persist_sandbox=false mean the sandbox is not used?

(3) Checking the logs directory, it is empty. I am not sure where to find the log files.

(4) Run "make [build"]([OpenDevin.txt](https://github.com/user-attachments/files/16203073/OpenDevin.txt)) again. This time, there were no errors. The screen output is copied into the attached file OpenDevin.txt.
[OpenDevin.txt](https://github.com/user-attachments/files/16203078/OpenDevin.txt)

(5) Choosing ollama/qwen2:72b-instruct generates C code. I did not run ollama run ollama/qwen2:72b-instruct manually, I just selected ollama/qwen2:72b-instruct in the configuration, and OpenDevin was able to generate the code. Was it generated using ollama/qwen2:72b-instruct?
![截图20240714011359](https://github.com/user-attachments/assets/2e84f223-eded-4cb4-94c7-e3f227ac9438)
![截图20240714012010](https://github.com/user-attachments/assets/0bcef2e8-2d3d-4cb0-bf1b-53f75fd4236e)

**Comment by mamoodi** [comment]
The sandbox is necessary yes as that's how OpenDevin has access to the workspace.
The persist_sandbox=false is not really important right now. OpenDevin will use a sandbox container regardless of this setting.

Yes in your screenshot I see that you have set the Model `ollama/qwen2:72b-instruct` and that is what OpenDevin will use as the LLM.

**Comment by liangyong928** [comment]
Thanks.
