### ISSUE TITLE
Rename and/or properly document the two different `changeAgentState` functions

### ISSUE THREAD

**Issue by amanape** [OpenDevin/OpenDevin#2977]
There are two `changeAgentState` functions that should probably be renamed and properly documented to avoid confusion for the future.

https://github.com/OpenDevin/OpenDevin/blob/01ce1e35b5b40e57d96b15a7fc9bee4eb8f6966d/frontend/src/state/agentSlice.tsx#L10-L12

https://github.com/OpenDevin/OpenDevin/blob/01ce1e35b5b40e57d96b15a7fc9bee4eb8f6966d/frontend/src/services/agentStateService.ts#L7-L18

**Comment by DecodersLord** [comment]
@amanape I believe https://github.com/OpenDevin/OpenDevin/blob/01ce1e35b5b40e57d96b15a7fc9bee4eb8f6966d/frontend/src/services/agentStateService.ts#L7-L18 Should still be called changeAgentState as that is the action being performed under it. 

Hoever the https://github.com/OpenDevin/OpenDevin/blob/01ce1e35b5b40e57d96b15a7fc9bee4eb8f6966d/frontend/src/state/agentSlice.tsx#L10-L12 can be renamed to "setCurrentAgentState"? 

Where do I need to document it? I do not see any reference to a readme or tutorial file if any. Please assign the issue to me if you think this is a viable solution

**Comment by amanape** [comment]
Hey @DecodersLord, thanks for taking a look into this.

By "document" I really meant just add some comments or a JSDoc description for the function to describe what it's for and when to use it. Updating the name is also a big plus as it will reduce errors from mistankingly using the incorrect function (I did when extending the tests)

Feel free to submit a PR with these changes and I'll take a look at it tomorrow!

**Comment by DecodersLord** [comment]
@amanape apologies for late response. It took me sometime to figure out the build for local environment. 
Can you also advise steps to test this changes? do I test some visual changes on the front-end or just run the pytest and make sure they all pass?

**Comment by amanape** [comment]
@DecodersLord This is a minor change. The frontend and python tests all run when you submit a PR so you shouldn't worry. As for visual tests, you can test anything that works with agent state (such as sending and receiving messages)

**Comment by DecodersLord** [comment]
@amanape I made the changed in my local branch but when I try and run it locally using my WSL, I seem to run in the error as below
![image](https://github.com/user-attachments/assets/6d058644-db00-4d28-9e05-f2b8b117ddf1)

![image](https://github.com/user-attachments/assets/37a2e043-95ec-40e6-a63b-4776e7af373f)

Can you advise if I am missing a step in the setup or something in my docker config?

**Comment by amanape** [comment]
@DecodersLord I am not familiar with WSL setup (I am on a Mac) so I can't really help there. If you've made the changes though, just submit a PR and I'll check the changes there
