### ISSUE TITLE
No matching version for chromadb

### ISSUE THREAD

**Issue by gprethesh** [OpenDevin/OpenDevin#299]
ERROR: Could not find a version that satisfies the requirement pulsar-client>=3.1.0 (from chromadb->-r requirements.txt (line 18)) (from versions: 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.3, 2.7.0, 2.7.1, 2.7.2, 2.7.2.post0, 2.7.3, 2.8.0, 2.8.0.post0)
ERROR: No matching distribution found for pulsar-client>=3.1.0 (from chromadb->-r requirements.txt (line 18))

**Comment by tzenmatt** [comment]
Incompatible CPU detected for M2 mac..

Anyone else?

**Comment by rbren** [comment]
@tzenmatt that sounds like a separate issue. We have several people running on apple silicon, so it'd be good to see the logs/errors you're seeing. Can you open a separate issue?

**Comment by rbren** [comment]
@gprethesh this sounds like a python environment issue. Can you try using virtualenv or similar to isolate your environment?

**Comment by gprethesh** [comment]
> @gprethesh this sounds like a python environment issue. Can you try using virtualenv or similar to isolate your environment?

I'm running it on venv not directly into the root system.

**Comment by rbren** [comment]
Strange. There is definitely a 3.1: https://pypi.org/project/pulsar-client/#history

**Comment by rbren** [comment]
If you're able to give exact repro steps (including python and pip versions) that might help

**Comment by Zoyashah01** [comment]
Encounter "No matching version for chromadb" exclusively at Carrefour deals. Troubleshoot and resolve this issue related to incompatible versions of chromadb, ensuring smooth operation of your application. Just as Carrefour deals offer a diverse range of products and promotions, this opportunity provides essential guidance for resolving version compatibility errors effectively. Address the issue promptly to maintain the integrity and functionality of your system. Access exclusive content now at [Carrefour deals!](https://wowdeals360.com/carrefour-uae/)

**Comment by rbren** [comment]
@gprethesh can you try the latest install using Pipenv?

**Comment by rbren** [comment]
Closing this since we can't repro. But if you have any more info I'm happy to help debug
