### ISSUE TITLE
Cannot download files from workspace

### ISSUE THREAD

**Issue by Tang-Steven** [OpenDevin/OpenDevin#3006]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I prompted OpenDevin to edit some code. It was able to do so successfully. However there is no option to download any of the files to my local machine. They can only be viewed in the workspace. The best it can do is zip up the folders containing the files. But still I cannot download the zipped folder. When I click on the zipped folder, the following error message appears: `500 error while fetching /api/select-file?file=%2Ftranscribe.zip: Internal Server Error
`
### Current OpenDevin version

```bash
0.8.0
```

### Installation and Configuration

```bash
WSL Ubuntu
```

**Comment by SmartManoj** [comment]
You can find those files in your workspace directory.

**Comment by mamoodi** [comment]
Hi @Tang-Steven. All the files that OpenDevin has access to in the workspace are actually located somewhere on your system. 
If you followed the main README to setup OpenDevin you likely ran:
`WORKSPACE_BASE=$(pwd)/workspace`

This will setup the workspace to a "workspace" folder relative to where you ran the command. So if you go there on your system, you should find all your files. 

Does that make sense?

**Comment by Tang-Steven** [comment]
After a bit of searching I found the workspace directory on my Windows system at `\\wsl.localhost\Ubuntu\home\username\workspace`
Thank you for pointing me in the right direction.

**Comment by bee-san** [comment]
Sorry to necro:

> This will setup the workspace to a "workspace" folder relative to where you ran the command. So if you go there on your system, you should find all your files.

1. Is this still true? I am also looking for a way to get my data easily. The only thing I set up is a sessions folder now 🤔

**Comment by mamoodi** [comment]
@bee-san you can use this documentation to attach your filesystem: https://docs.all-hands.dev/modules/usage/runtimes#connecting-to-your-filesystem

Just make sure you have your files saved elsewhere or better yet, saved on a github repo because OpenHands will directly change them on your system.
