### ISSUE TITLE
Api related issue 

### ISSUE THREAD

**Issue by R3verseIN** [OpenDevin/OpenDevin#304]
**INFO:     Started server process [119867]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 32842) - "WebSocket /ws" [accepted]
INFO:     connection open
Please check Docker is running using `docker ps`.
Error! Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Failed to stop container: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Error creating controller.**

used in usl 

commands i used 
export WORKSPACE_DIR="~/Work/"
export LLM_BASE_URL="http://localhost:11434"
export LLM_EMBEDDING_MODEL="llama2"
export LLM_API_KEY=""

i am running ui on windows machine as i am facing issues npm related on running on linux. the ollama and server running on wsl running ubuntu.

**Comment by RohitX0X** [comment]
is your docker or docker desktop running?

**Comment by deepakJangidz** [comment]
Try to configure  Docker Desktop to listen on TCP port 2375.
Make sure that Docker is allowed through the firewall by adding an inbound rule for TCP port 2375.

**Comment by R3verseIN** [comment]
> Try to configure  Docker Desktop to listen on TCP port 2375.
> Make sure that Docker is allowed through the firewall by adding an inbound rule for TCP port 2375.

I'm not running it on docker but in wsl.

**Comment by R3verseIN** [comment]
> > Try to configure  Docker Desktop to listen on TCP port 2375.
> > Make sure that Docker is allowed through the firewall by adding an inbound rule for TCP port 2375.
> 
> I'm not running it on docker but in wsl.

IIts now fixed Thank you @deepakJangidz
