### ISSUE TITLE
[Qustion]: When will Jupyter IPython start working

### ISSUE THREAD

**Issue by charliez0** [OpenDevin/OpenDevin#3046]
I can see IPython logs in runtime but nothing in the frontend

version: latest

**Comment by tobitege** [comment]
Sorry, without any further information or logs this is not something we can answer.

**Comment by mamoodi** [comment]
Right, this is a little bit difficult to answer without more information. However, @tobitege or @xingyaoww is there a high level answer to this? Are there specific criteria that has to be met?

(I personally haven't seen this myself)

**Comment by tobitege** [comment]
Not with this issue described as it is. Could be this or that. 😁

**Comment by SmartManoj** [comment]
> I can see IPython logs in runtime but nothing in the frontend

There is a delay in that. It is being updated in the next step only.
