### ISSUE TITLE
Environment/settings file for configuration

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#305]
Update the Reame for Windows and change export to set.
Add option to set the api key and directory in a config.ini or .env

**Comment by rbren** [comment]
I think it's standard practice to target Unix, so I'd rather keep `export`. I don't really see `set` documented in other projects.

**Comment by PierrunoYT** [comment]
> I think it's standard practice to target Unix, so I'd rather keep `export`. I don't really see `set` documented in other projects.

I mean you can add seperate readme maybe?

**Comment by rbren** [comment]
Maintaining two READMEs is hard 😅 I think we should just standardize on Unix.

But, more to the point, it would be nice to have a settings file that we can pull from, instead of using env vars for everything

**Comment by Zoyashah01** [comment]
Access the environment/settings file for configuration exclusively at Wow Deals. Utilize this file to customize and fine-tune the settings of your environment, enabling seamless integration and optimal performance. Just as Wow Deals offers unparalleled discounts and promotions, this file provides essential tools for configuring your system according to your specific requirements. Enhance flexibility and efficiency in managing your environment with the settings file. Access exclusive content now at [Wow Deals!](https://wowdeals360.com/abu-dhabi/)

**Comment by yimothysu** [comment]
@rbren What do you think about having settings in a new file `config.toml`, which is added to .gitignore?

**Comment by PierrunoYT** [comment]
> Maintaining two READMEs is hard 😅 I think we should just standardize on Unix.
> 
> But, more to the point, it would be nice to have a settings file that we can pull from, instead of using env vars for everything

It would be cool if you can add a Windows Readme as most standard people would use windows. Also add step by step guide in the readme even if you don't want to add Windows.
