### ISSUE TITLE
Latest update makes right pane headers hard to see.

### ISSUE THREAD

**Issue by 1of13** [OpenDevin/OpenDevin#307]
**Describe the bug**
The color scheme used in the latest update makes the tabs and text in the right pane challenging to read.

**Steps to Reproduce**
1.Set up OpenDevin per instructions.
2.Start OpenDevin

**Expected behavior**
Same as prior version or improvement.
**Actual behavior**

**Additional context**
I'm using an M3 Mac. Following the instructions, the installation works flawlessly. I appreciate the developers' hard work!

<img width="1405" alt="SCR-20240328-iakj" src="https://github.com/OpenDevin/OpenDevin/assets/31781349/ed6923dd-994e-401b-8e94-052d6c0463fe">

**Comment by Yashwanth-Chandrakumar** [comment]
![Screenshot 2024-03-28 213433](https://github.com/OpenDevin/OpenDevin/assets/121328223/9bb2de00-b4d7-47e4-8626-3480e4149586)

Hi @1of13 For me it looks great can you explain in detail about how the bug came

**Comment by yimothysu** [comment]
Can reproduce. This happens when your OS appearance is in light mode. Will force dark mode for now.
