### ISSUE TITLE
Config should raise errors when detect keys in `config.toml` that does not match config classes

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#3074]
**What problem or use case are you trying to solve?**

We recently did some breaking changes to the `config.toml` systems, which makes some old `config.toml` file does not work as expected. However, there's no error/warning when using an old configuration file.

**Describe the UX of the solution you'd like**

Ideally, the config `opendevin/core/config.py` should raise errors when it detects `config.toml` contains configuration names not matched with the current Pydantic config classes.

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by enyst** [comment]
I think I've seen an error when attempting to load an old `llm_config` with a name without `llm`. Although it may have been because of the name on the command line. 🤔

Most other things should be compatible. What keys were silently ignored?
