### ISSUE TITLE
`git` command not found when starting frontend

### ISSUE THREAD

**Issue by Mecil9** [OpenDevin/OpenDevin#308]
**Describe the bug**
when i run "npm i",throw this error:

> opendevin-frontend@0.1.0 prepare
> cd .. && husky install frontend/.husky

fatal: not a git repository (or any of the parent directories): .git
husky - git command not found, skipping install

apple: m1 max
node:20.8.0

**Comment by ASQUAREEE** [comment]
If you want to resolve the issue, simply delete the .husky file and the node_modules directory, then run npm i again

**Comment by rbren** [comment]
Sounds like you don't have `git` installed? It should come pre-loaded on os x...

What does `git --version` show?

**Comment by Zoyashah01** [comment]
Encounter "command not found" errors when starting the frontend exclusively at Deals in UAE. Troubleshoot and resolve issues related to frontend application startup, ensuring seamless operation of your software stack. Just as Deals in UAE offers unbeatable solutions and insights, this opportunity provides essential guidance for frontend development and deployment. Address command-related issues effectively and optimize your frontend environment for enhanced performance. Access exclusive content now at [Deals in UAE!](https://wowdeals360.com/)

**Comment by somashekar17** [comment]
Check whether git is installed or not 'git --version'

Install  husky using cmd :
npm i husky --save-dev
 or 
npm i husky@latest -- save dev

**Comment by rbren** [comment]
This seems like `git` just isn't installed on your machine (though I'm still confused how you cloned it).

Going to close this one for now since it doesn't seem like an OpenDevin issue, but if you have any more info I'm happy to help you debug.

**Comment by enyst** [comment]
> This seems like `git` just isn't installed on your machine (though I'm still confused how you cloned it). 

Could use the "download zip" button from the same dialog box with git URLs, I suppose.
