### ISSUE TITLE
Add formatting and linting for typescript components

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#31]
Right now we don't have any central standard for formatting typescript, and because of this various PRs are doing things like changing the formatting, which makes it difficult to focus on the actual content of the PR.

It'd be good to:

- [ ] choose our formatting standard for typescript (maybe [ESLint+Prettier](https://blog.logrocket.com/linting-typescript-eslint-prettier/))
- [ ] add [CI](https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration) to check the linting
- [ ] add git [pre-commit hook](https://pre-commit.com/) to ensure that these are run on commit

Any comments or contributions are welcome!

**Comment by FrankenDeba** [comment]
I have added the prettier + eslint
Working for the ci/pre-commit hook

> Right now we don't have any central standard for formatting typescript, and because of this various PRs are doing things like changing the formatting, which makes it difficult to focus on the actual content of the PR.
> 
> It'd be good to:
> 
> * [ +]  choose our formatting standard for typescript (maybe [ESLint+Prettier](https://blog.logrocket.com/linting-typescript-eslint-prettier/))
> * [ ]  add [CI](https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration) to check the linting
> * [ ]  add git [pre-commit hook](https://pre-commit.com/) to ensure that these are run on commit
> 
> Any comments or contributions are welcome!
