### ISSUE TITLE
[Bug]: Opendevin can not install numpy, pytorch etc.

### ISSUE THREAD

**Issue by drzsdrtfg** [OpenDevin/OpenDevin#3119]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Example:import numpy as np
ModuleNotFoundError: No module named 'numpy'

$ pip install numpy --user
[Package installed successfully]

$ python3 transformer_llm.py
Traceback (most recent call last):
  File "/workspace/transformer_llm.py", line 3, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'

$ pip install datasets --user
[Package installed successfully]

$ python3 transformer_llm.py
Traceback (most recent call last):
  File "/workspace/transformer_llm.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

### Current OpenDevin version

```bash
newest
```

### Installation and Configuration

```bash
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin
```

### Operating System

WSL on Windows with docker

### Logs, Errors, Screenshots, and Additional Context

Ask me for more information (e.g. Screenshots etc.)

**Comment by tobitege** [comment]
![grafik](https://github.com/user-attachments/assets/34904e02-d4d2-4647-9606-4da027699490)

Tried to reproduce the issue.
So I created just a single-line test.py and told the model to run it.
Of course, first attempt failed, so the model called the `pip install datasets` and even started adding example code to it and ran it.

**Comment by drzsdrtfg** [comment]
I somehow didnt manage to reproduce it aswell.

**Comment by SmartManoj** [comment]
@tobitege Could you run `pip install datasets --user`?
