### ISSUE TITLE
Ensure workspace directory exists before starting agent

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#312]
**Describe the bug**
If you try to run OpenDevin with a workspace directory that doesn't exist, it fails hard.

**Steps to Reproduce**
1. `python opendevin/main.py -d ./foo/ -t "create a TODO list web app"`

**Expected behavior**
Create the dir

**Actual behavior**
`AssertionError: Directory ./foo/ does not exist.`

**Additional context**

We should use `os.mkdirs` to ensure the dir exists. 

This should work for both the server and the main.py script

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/3ebd2748-823c-49a3-b08e-685aa5e1a4e6)
