### ISSUE TITLE
Make UI more responsive

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#313]
**Describe the bug**
On smaller windows, the UI gets squished.

**Steps to Reproduce**
1. Shrink window width to < 1000px

**Expected behavior**
Things still look nice

**Actual behavior**
Screenshot
<img width="892" alt="Screenshot 2024-03-28 at 1 48 48 PM" src="https://github.com/OpenDevin/OpenDevin/assets/7611973/592e4bc4-624e-4c02-b79d-56fe89adc5d2">

**Additional context**

**Comment by ASQUAREEE** [comment]
https://github.com/OpenDevin/OpenDevin/pull/302/files

**Comment by ASQUAREEE** [comment]
![image](https://github.com/OpenDevin/OpenDevin/assets/99893402/0d0ae4e0-2c36-475c-8d19-c87774d3da65)
