### ISSUE TITLE
Allow the sandbox container to run seperately

### ISSUE THREAD

**Issue by JamDon2** [OpenDevin/OpenDevin#3187]
**Summary**
The sandbox container should be allowed to run outside of the OpenDevin container, and communication between them can be handled by an exposed port.

**Motivation**
This would help avoid SSH connection errors, and more advanced users could choose where they want to run their sandbox.

**Technical Design**
The sandbox hostname is passed in as an environment variable, so no access to the Docker socket is neeeded.

**Comment by neubig** [comment]
Thanks @JamDon2 ! We have now deprecated SSH-based communication so SSH socket errors should be fixed on the latest main branch. But if you're still having issues please tell us and we can look into it.
