### ISSUE TITLE
Stuck on Initializing the agent

### ISSUE THREAD

**Issue by omrode1** [OpenDevin/OpenDevin#331]
![image](https://github.com/OpenDevin/OpenDevin/assets/119610460/774ee28e-6b54-4b62-baa6-96705b7d6d47)

**Comment by nasko94** [comment]
I am having the same issue. I am on a windows 11 laptop with the latest Python version. I am doing everything step by step, but the agent wont initialize.

Please help.

**Comment by rbren** [comment]
@nasko94 are you using WSL? uvicorn doesn't seem to run on standard Windows

**Comment by rbren** [comment]
Any logs y'all can share will help us debug

**Comment by nasko94** [comment]
@rbren  No, I did used uvicorn as stated in the readme. Also, there are no problematic logs. Everything seems normal, except that the agent doesn't initialize. 

I have no idea how to use WSL and if you have no docs, I'll have to use gpt4 to guide me I guess

**Comment by rbren** [comment]
Here's instructions on installing WSL: https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by rbren** [comment]
Deduping this with https://github.com/OpenDevin/OpenDevin/issues/344#issuecomment-2027739962

**Comment by DibakarBala** [comment]
I am on version 8, still facing same issue
