### ISSUE TITLE
[Testing]: Add runtime test with sandbox_container_image?

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#3314]
**What problem or use case are you trying to solve?**

We officially [support](https://docs.all-hands.dev/modules/usage/custom_sandbox_guide) custom container images. However, it seems that we don't have any runtime tests that test whether OpenDevin works with a custom container image (at least I wasn't able to find `sandbox_container_image` used in the tests anywhere).

**Describe the UX of the solution you'd like**

It would be good to have at least one test to tell whether this important functionality is tested.

**Do you have thoughts on the technical implementation?**

This could be tested either within the existing runtime tests, or in a different set of tests.

(CC: @xingyaoww @li-boxuan @tobitege if you have any comments)

**Comment by tobitege** [comment]
There are tests involving `debian:11`:

https://github.com/OpenDevin/OpenDevin/blob/5e6fd58f56840f20fc619349428092b7ddae45fc/tests/unit/test_runtime_build.py#L129-L134

**Comment by neubig** [comment]
Cool! This is good, but it's a unit test that just test tests the dockerfile content, and doesn't test whether OpenDevin actually runs after generating the custom image.
