### ISSUE TITLE
[Bug]: Error when selecting non-text file in file selector

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#3315]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

OpenDevin has a file selector that allows you to browse the files within the workspace. This works well for text/code files, but when you select an image file it gives you the following error:

```log
09:42:41 - opendevin:ERROR: listen.py:433 - Error opening file /workspace/month_days_plot.png: ErrorObservation(content='File could not be decoded as utf-8: /workspace/month_days_plot.png.', observation='error')
INFO:     127.0.0.1:50192 - "GET /api/select-file?file=%2Fworkspace%2Fmonth_days_plot.png HTTP/1.1" 500 Internal Server Error
```

This probably requires fixes to both the backend (to serve binary files) and the frontend (to display files).

### Current OpenDevin version

```bash
commit 5e6fd58f56840f20fc619349428092b7ddae45fc
```

### Installation and Configuration

```bash
make build; make run
```

**Comment by tobitege** [comment]
I wouldn't call this a bug, but a feature request for displaying images. :)

**Comment by neubig** [comment]
Maybe, but it currently throws a "500 internal server error" so at least the display of the error should be fixed.

**Comment by mamoodi** [comment]
Agree that this one can be used for better handling. Aside from that the feature request is a duplicate of this:
https://github.com/OpenDevin/OpenDevin/issues/1491

**Comment by neubig** [comment]
Ah, I agree this is a duplicate of #1491 (which I didn't find in my search...) Closing!
