### ISSUE TITLE
[Bug]: Deepseek-coder not working

### ISSUE THREAD

**Issue by DefamationStation** [OpenDevin/OpenDevin#3339]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When I try to run a prompt of any kind through the chat it tells me that "There was an unexpected error while running the agent"

### Current OpenDevin version

```bash
latest version just installed
```

### Installation and Configuration

```bash
$ WORKSPACE_BASE=$(pwd)
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3001:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.8
0.8: Pulling from opendevin/opendevin
```

### Model and Agent

CodeActAgent with deepseek-coder

### Operating System

WSL on windows

### Reproduction Steps

Open OpenDevin web UI, choose, deepseek-coder provider, input API key, click save, wait for agent to initialize and try to send a message,

### Logs, Errors, Screenshots, and Additional Context

17:34:05 - opendevin:WARNING: llm.py:70 - Could not get model info for deepseek-coder
17:34:05 - opendevin:INFO: agent.py:79 - Using runtime: server
17:34:05 - opendevin:INFO: ssh_box.py:135 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
17:34:05 - opendevin:INFO: ssh_box.py:178 - Detected initial session.
17:34:05 - opendevin:INFO: ssh_box.py:180 - Creating new Docker container
17:34:05 - opendevin:WARNING: ssh_box.py:578 - Using port forwarding till the enable host network mode of Docker is out of experimental mode.Check the 897th issue on https://github.com/OpenDevin/OpenDevin/issues/ for more information.
17:34:05 - opendevin:INFO: ssh_box.py:586 - Mounting volumes: {'/mnt/c/Users/frenz/workspace': {'bind': '/workspace', 'mode': 'rw'}, '/tmp/cache': {'bind': '/home/opendevin/.cache', 'mode': 'rw'}}
17:34:05 - opendevin:INFO: ssh_box.py:597 - Container started
17:34:06 - opendevin:INFO: ssh_box.py:613 - waiting for container to start: 1, container status: running
17:34:07 - opendevin:INFO: ssh_box.py:342 - Connecting to SSH session...
17:34:07 - opendevin:INFO: ssh_box.py:345 - You can debug the SSH connection by running: `ssh -v -p 58123 opendevin@localhost` using the password '36cee857-cca4-45fa-8c85-f58c6297de18'
17:34:09 - opendevin:INFO: ssh_box.py:349 - Connected to SSH session
17:34:11 - opendevin:INFO: agent.py:100 - Creating agent CodeActAgent using LLM deepseek-coder
17:34:11 - opendevin:INFO: mixin.py:42 - Initializing plugins in the sandbox
17:34:11 - opendevin:INFO: mixin.py:30 - Sourced /opendevin/bash.bashrc and ~/.bashrc successfully
17:34:11 - opendevin:INFO: mixin.py:59 - Copied files from [/app/opendevin/runtime/plugins/agent_skills] to [/opendevin/plugins/agent_skills] inside sandbox.
17:34:11 - opendevin:INFO: mixin.py:67 - Initializing plugin [agent_skills] by executing [/opendevin/plugins/agent_skills/setup.sh] in the sandbox.
17:34:19 - opendevin:INFO: mixin.py:85 - Plugin agent_skills initialized successfully
17:34:19 - opendevin:INFO: mixin.py:30 - Sourced /opendevin/bash.bashrc and ~/.bashrc successfully
17:34:19 - opendevin:INFO: mixin.py:59 - Copied files from [/app/opendevin/runtime/plugins/jupyter] to [/opendevin/plugins/jupyter] inside sandbox.
17:34:19 - opendevin:INFO: mixin.py:67 - Initializing plugin [jupyter] by executing [/opendevin/plugins/jupyter/setup.sh] in the sandbox.
17:34:21 - opendevin:INFO: mixin.py:85 - Plugin jupyter initialized successfully
17:34:21 - opendevin:INFO: mixin.py:30 - Sourced /opendevin/bash.bashrc and ~/.bashrc successfully
17:34:21 - opendevin:INFO: browser_env.py:78 - Starting browser env...
17:34:21 - opendevin:ERROR: state.py:127 - Failed to restore state from session: sessions/15caebbf-f845-4224-94a7-3b2ddab250b6/agent_state.pkl
Error restoring state sessions/15caebbf-f845-4224-94a7-3b2ddab250b6/agent_state.pkl
17:34:21 - opendevin:INFO: agent_controller.py:140 - [Agent Controller 15caebbf-f845-4224-94a7-3b2ddab250b6] Starting step loop...
INFO:     172.17.0.1:39408 - "GET /api/list-files?path=%2F HTTP/1.1" 200 OK
17:34:26 - opendevin:INFO: browser_env.py:121 - Browser env started.
17:34:50 - USER_ACTION
**MessageAction** (source=EventSource.USER)
CONTENT: please navigate to https://github.com/DefamationStation/Retrochat-v2 and download the retrochat.py file only.
It's a program I run in the windows terminal where the user can communicate with different models through API's. I need a good way to handle markdown text formatting properly for every single provider in that script.
INFO:     172.17.0.1:52848 - "GET /api/list-files?path=%2F HTTP/1.1" 200 OK

==============
CodeActAgent LEVEL 0 LOCAL STEP 0 GLOBAL STEP 0

Provider List: https://docs.litellm.ai/docs/providers

Traceback (most recent call last):
  File "/app/opendevin/controller/agent_controller.py", line 143, in _start_step_loop
    await self._step()
  File "/app/opendevin/controller/agent_controller.py", line 392, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agenthub/codeact_agent/codeact_agent.py", line 194, in step
    response = self.llm.completion(
               ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 154, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1028, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 908, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2750, in completion
    raise exception_type(
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 832, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
                                                            ^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4704, in get_llm_provider
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4681, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=deepseek-coder
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
17:34:51 - opendevin:ERROR: agent_controller.py:149 - Error while running the agent: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=deepseek-coder
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
17:34:51 - opendevin:ERROR: agent_controller.py:150 - Traceback (most recent call last):
  File "/app/opendevin/controller/agent_controller.py", line 143, in _start_step_loop
    await self._step()
  File "/app/opendevin/controller/agent_controller.py", line 392, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agenthub/codeact_agent/codeact_agent.py", line 194, in step
    response = self.llm.completion(
               ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/llm/llm.py", line 154, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1028, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 908, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2750, in completion
    raise exception_type(
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 832, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
                                                            ^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4704, in get_llm_provider
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 4681, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=deepseek-coder
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers

17:34:51 - OBSERVATION
ErrorObservation(content='There was an unexpected error while running the agent', observation='error')
INFO:     172.17.0.1:52848 - "GET /api/list-files?path=%2F HTTP/1.1" 200 OK

**Comment by DefamationStation** [comment]
GPT-4o works fine it's only deepseek-coder

**Comment by DefamationStation** [comment]
deepseek-coder doesn't seem to use the deepseek platform? it's through huggingface? why and there is no indication that thats the case on the UI

**Comment by neubig** [comment]
Yes, unfortunately it's a known issue that open LLMs are not as good as the other alternatives. We're already tracking this in issue #1085 so I'll close this one and we can continue the discussion there.

**Comment by enyst** [comment]
@DefamationStation From your error log, it seems it didn't find the model at all. Try to check the name you entered in the UI, add version if necessary. How does the provider say you can access the model? It needs to have the right name, which is probably not only "deepseek-coder".
