### ISSUE TITLE
[Question]: Does the fronend support LLM streaming?

### ISSUE THREAD

**Issue by flyingdutchpig** [OpenDevin/OpenDevin#3362]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

The assistant's reply is showing up in one piece rather than streaming out in the chatting box.
I have checked the doc: https://docs.all-hands.dev/modules/usage/intro and most of the source code without seeing anywhere to set "stream=True". 
I thought this was a feature ( reply in non-stream style in frontend ) before finding this offical demo in which the words are streaming out. (https://github.com/OpenDevin/OpenDevin/assets/38853559/f592a192-e86c-4f48-ad31-d69282d5f6ac)

so, should the word streaming out in the chatting box in the frontend? or have I just missed some configuration? Thanks

### Current OpenDevin version

```bash
0.8.0
```

### Installation and Configuration

```bash
started with "make run"
```

### Model and Agent

ollama:qwen2:latest

### Operating System

centos7

**Comment by tobitege** [comment]
Streaming the LLM output is not implemented, yet.

**Comment by tobitege** [comment]
If I recall correctly, OD never had LLM streaming, so I'm not sure what videos you are refering to?

**Comment by tobitege** [comment]
And just to make sure: this repo is "OpenDevin", not "Devin" 😁

**Comment by flyingdutchpig** [comment]
> If I recall correctly, OD never had LLM streaming, so I'm not sure what videos you are refering to?

This is the [demo video](https://github.com/OpenDevin/OpenDevin/assets/38853559/f592a192-e86c-4f48-ad31-d69282d5f6ac) I mention above, I found it from the [doc page](https://docs.all-hands.dev/modules/usage/agents)

And this is [another video in youtube](https://www.youtube.com/watch?v=fPljokOHhwo) showing "streaming words"

**Comment by flyingdutchpig** [comment]
> And just to make sure: this repo is "OpenDevin", not "Devin" 😁

Oh yes, I am talking about "OpenDevin".

**Comment by tobitege** [comment]
Oh, I see now! Wow, when I first tried OD myself, that was already gone.

**Comment by flyingdutchpig** [comment]
> Oh, I see now! Wow, when I first tried OD myself, that was already gone.

What do you mean by "already gone"? They have supported text stream in frontend once but not anymore?

**Comment by enyst** [comment]
That old video wasn't streaming the LLM output, it was a hard-coded experiment: it got the whole response from the LLM, but the frontend was typing it letter by letter like streaming would look like. It wasn't very stable either. We have eventually concluded it will be better to have real streaming. ☺️

**Comment by flyingdutchpig** [comment]
Thank you both @enyst @tobitege  for answering my questions and contributions to this project. Now I got the answer and this issue will be closed.
