### ISSUE TITLE
UI is missing claude-3-opus-20240229 option

### ISSUE THREAD

**Issue by crypdick** [OpenDevin/OpenDevin#340]
**Describe the bug**
The README described how one can set the endpoint to use Claude Opus. However, when following those directions, the UI does not display Opus as an option

**Steps to Reproduce**
1. Follow README instructions to use Claude Opus
2. Launch the UI
3. Opus not available as an option.

**Expected behavior**
Opus available as an option, Opus set as default

**Actual behavior**
Opus not available as an option.

**Additional context**
![image](https://github.com/OpenDevin/OpenDevin/assets/5415776/1e2c37d4-fbe3-49ac-b4e7-69278e93fd46)

**Comment by rfleuryleveso** [comment]
Looking through the code, the value is missing in 
[frontend/src/services/settingsService.ts](https://github.com/OpenDevin/OpenDevin/blob/a6f0c066b5241f76f40fd7e14a45432b081e214f/frontend/src/services/settingsService.ts#L6)

Values availables are given here: https://docs.litellm.ai/docs/providers/anthropic
More generally, also here: https://docs.litellm.ai/docs/providers

I can make a PR

**Comment by rbren** [comment]
👍 PR would be helpful, thanks!

**Comment by PierrunoYT** [comment]
I also saw this

**Comment by ishaan-jaff** [comment]
@rfleuryleveso most projects read available models from here: https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json 

We also have helpful utils for getting supported providers, when importing / using `litellm` you will be able to see litellm providers

**Comment by rbren** [comment]
Should be fixed now: https://github.com/OpenDevin/OpenDevin/pull/370/files
