### ISSUE TITLE
Create test.py for each of the regression cases

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#341]
**What problem or use case are you trying to solve?**
We have an automated test framework now. But we need to actually add tests!

CC @dorbanianas

**Comment by dorbanianas** [comment]
Thanks @rbren

**Comment by yufansong** [comment]
Little confused about `test.py`, can you elaborate more details?

**Comment by dorbanianas** [comment]
@yufansong you can check this example described by @rbren #151 or you can check the hello-world folder in the cases folder
