### ISSUE TITLE
Unknow issue when running prompt inside the webui with WSL Ubuntu

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#343]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/17cc9a77-f162-4eac-ac63-b0cade24d6a0)

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/fc3ea72a-adfd-4ed6-b1e8-896dd23fa676)

**Comment by AbdelrahmanHassan111** [comment]
Make sure that you have set your OPENAI API Key

**Comment by PierrunoYT** [comment]
> Make sure that you have set your **OPENAI API Key**

I did but it's not working with Claude

**Comment by rbren** [comment]
it should be `LLM_API_KEY`: https://github.com/opendevin/opendevin?tab=readme-ov-file#picking-a-model

**Comment by AbdelrahmanHassan111** [comment]
> > Make sure that you have set your **OPENAI API Key**
> 
> I did but it's not working with Claude

ensure this command prompt `claude POST https://api.openai.com/v1/completions -H "Content-Type: application/json" -H "Authorization: Bearer YOUR_API_KEY" -d "{\"prompt\":\"Hello, world!\"}"
`
and **replace**  `YOUR_API_KEY` with your actual OpenAI API key.

**Comment by rbren** [comment]
This is looking like user error--we do need to rework the key/model interaction a bit though. E.g. only make models available if the user has plugged in a key, or prompt for a key when choosing a model.

I'll open a PR
