### ISSUE TITLE
Unexpected Error when running a command in the WebUI using WSL Ubuntu

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#345]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/6535ddd1-997e-46b8-ab11-3a939667dbbe)

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/2f502740-7a92-4774-bdcd-df7fb3417d8b)

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/6f7c1acc-e430-443e-8fb6-f1ae4f32129d)

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/79477ffe-38b3-4208-ab4c-9438dd84b644)

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/1bbf8e20-1ed7-4ccc-834a-4c8dc6d8229a)
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/4a0dd9e6-587d-42af-ae16-a37d86850831)

**Comment by yufansong** [comment]
@rbren can you help to merge #292 to solve this problem?
