### ISSUE TITLE
support bazel test

### ISSUE THREAD

**Issue by josephykwang** [OpenDevin/OpenDevin#350]
we are using bazel test for testing code.

**Comment by rbren** [comment]
Who is "we" here?

Any particular reason we should use bazel vs just e.g. pytest?

**Comment by josephykwang** [comment]
we use bazel build/test with conda. 
    On Friday, March 29, 2024 at 12:50:02 PM PDT, Robert Brennan ***@***.***> wrote:  
 
 


Who is "we" here?

Any particular reason we should use bazel vs just e.g. pytest?

**Comment by rbren** [comment]
Sorry, I'm still confused. OpenDevin (to my knowledge) is not using bazel or conda.

**Comment by josephykwang** [comment]
we as my company
    On Friday, March 29, 2024 at 02:19:49 PM PDT, Robert Brennan ***@***.***> wrote:  
 
 


Sorry, I'm still confused. OpenDevin (to my knowledge) is not using bazel or conda.

**Comment by rbren** [comment]
Bazel seems like probably overkill for this project, so I'm going to close this one. But if others disagree I'm happy to have a discussion, here or on Slack!
