### ISSUE TITLE
Make the UI responsive for all devices

### ISSUE THREAD

**Issue by Yashwanth-Chandrakumar** [OpenDevin/OpenDevin#351]
**Summary**
OpenDevin must be responsive for all screen sizes

**Motivation**
When the screen sizes reduce the tabs like browser, code editor do out of viewport.

**Technical Design**
Use of media query to adjust the alignment according to screen sizes.
![Screenshot 2024-03-29 225701](https://github.com/OpenDevin/OpenDevin/assets/121328223/d2b678ac-871a-4d3d-8947-bfb785f0aa8d)

**Comment by sa64r** [comment]
Raised a PR to help tackle this https://github.com/OpenDevin/OpenDevin/pull/677

**Comment by mamoodi** [comment]
I'm going to close this as will not do for now because there doesn't seem to be plans to tackle this for a while. We can open a new issue if it's something that a lot of people want.
