### ISSUE TITLE
Docker volume on windows

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#368]
pierre@Pierruno:~$ docker pull ghcr.io/opendevin/sandbox
Using default tag: latest
latest: Pulling from opendevin/sandbox
bccd10f490ab: Pull complete
cb5edcfbf460: Pull complete
Digest: sha256:fac15190a8ccf145758151dc41d329f1de0cf5de43b4737fa83d3d3773cfe993
Status: Downloaded newer image for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest
pierre@Pierruno:~$ cd /mnt/c/Users/pierr/OpenDevin
pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ pipenv shell
Launching subshell in virtual environment...
pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$  . /home/pierre/.local/share/virtualenvs/OpenDevin-kZ9rGcbW/bin/activate
(OpenDevin) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ uvicorn opendevin.server.listen:app --port 3000
INFO:     Started server process [53146]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 42980) - "WebSocket /ws" [accepted]
INFO:     connection open
Failed to start container: 500 Server Error for http+docker://localhost/v1.44/containers/create?name=sandbox-default: Internal Server Error ("invalid volume specification: '/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/af7e382c682ee4a4990e1cf9ea6fe474064e92073dd5c85b9da40e18878efc33:\Users\pierr\OpenDevinProjects:/workspace:rw'")
Error creating controller.

**Comment by rbren** [comment]
Looks like it's trying to mount windows directory `\Users\pierr\OpenDevinProjects` to `/workspace` 

There's no `C:` for some reason.

What do you get if you run
```
docker run -it -v `pwd`:/testdir alpine:latest
```

**Comment by PierrunoYT** [comment]
> Looks like it's trying to mount windows directory `\Users\pierr\OpenDevinProjects` to `/workspace` 
> 
> 
> 
> There's no `C:` for some reason.
> 
> 
> 
> What do you get if you run
> 
> ```
> 
> docker run -it -v `pwd`:/testdir alpine:latest
> 
> ```

Where do I need to run it?

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/6fc3fd03-5d90-46e1-a6fa-c0714f591e08)

**Comment by kvchitrapu** [comment]
Probably a path issue. Check if docker container comes up with this command:

```
$ docker run --name=try-opendevin  --hostname=docker-desktop --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --volume=C:/Users/pierr/OpenDevProjects:/workspace:rw --volume=/workspace ghcr.io/opendevin/sandbox:v0.1 tail -f /dev/null
```

**Comment by PierrunoYT** [comment]
> Probably a path issue. Check if docker container comes up with this command:
> 
> ```
> $ docker run --name=try-opendevin  --hostname=docker-desktop --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --volume=C:/Users/pierr/OpenDevProjects:/workspace:rw --volume=/workspace ghcr.io/opendevin/sandbox:v0.1 tail -f /dev/null
> ```

![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/b1a66737-137b-43f2-a772-07f3e5a2001d)

**Comment by rbren** [comment]
Try following the instructions here: https://stackoverflow.com/questions/35315996/how-do-i-mount-a-docker-volume-while-using-a-windows-host

**Comment by PierrunoYT** [comment]
Not sure if this is the issue

**Comment by rbren** [comment]
`invalid volume specification` is the error. It means the flag after `-v` is formatted wrong

**Comment by enyst** [comment]
Or try using /mnt/c/Users/pierr/OpenDevinProjects as that WSL path.

**Comment by arose26** [comment]
I got a similar error and fixed it by doing export WORKSPACE_BASE=$(pwd)/workspace before calling docker run
