### ISSUE TITLE
Frontend: Implement browser tab

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#37]
In the actual Devin demo there is a browser tab that allows the user to see which pages the assistant is currently looking at. But we do not have such a tab within our [current prototype frontend](https://github.com/OpenDevin/OpenDevin/tree/main/frontend).

We could add such a tab. Contributors for this welcome!

**Comment by yimothysu** [comment]
If the assistant views webpages through Selenium, it can send a screenshot every second (or every page update) to the frontend, which this tab can render.

Embedding an `<iframe />` is also possible but might have security/reliability issues (such as CORS).

**Comment by neubig** [comment]
Yeah, I think that the selenium screenshot might be the appropriate way to do things here, nice idea @yimothysu !
