### ISSUE TITLE
Create a poetry configuration for better dependencies management and project setup

### ISSUE THREAD

**Issue by dorbanianas** [OpenDevin/OpenDevin#374]
**What problem or use case are you trying to solve?**

Set up Poetry for seamless dependency management.

**Comment by neubig** [comment]
I'm not sure if we need poetry, or could just use pip? I prefer pip because it's simpler, but if poetry is really necessary then we could do it.

Either way, we should use `pyproject.toml`, as it gives us flexibility.

**Comment by rbren** [comment]
We _just_ switched to Pipenv.

I'm open to a discussion on what's the best package manager, but we should probably move it to Slack. Gonna close this one, but let's start a thread in Slack

**Comment by dorbanianas** [comment]
@rbren https://dev.to/farcellier/i-migrate-to-poetry-in-2023-am-i-right--115 this article has some arguments HHHH and I created the above PR that contains the modifications

**Comment by jojeyh** [comment]
Poetry is great in general and forward looking but I've always run into problems with torch when I try to use it for ML projects

**Comment by lowlyocean** [comment]
Anecdotally, I had an easier time getting up & running _before_ this PR. I'm running Ubuntu 22.04 via WSL and ended up needing to this even though I installed python3.11: https://github.com/python-poetry/poetry/issues/7158#issuecomment-1342197929
