### ISSUE TITLE
Sai programmare in pine script per tradinf view?

### ISSUE THREAD

**Issue by piacevoleitalia** [OpenDevin/OpenDevin#382]
**What problem or use case are you trying to solve?**

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by piacevoleitalia** [comment]
Vorrei un indicatore di r quadro pearson con il dato di R2 in percentuale e la pendenza della funzione di interpolazione calcolata in tasso composto annuo

**Comment by rbren** [comment]
Dupe
