### ISSUE TITLE
M2 mac incompatibility???

### ISSUE THREAD

**Issue by tzenmatt** [OpenDevin/OpenDevin#386]
None of it is compatible on the m2 mac... anyone have a solution?

**Comment by kvchitrapu** [comment]
@tzenmatt , Could you specify where exactly you're encountering issues during installation or runtime on the M2 Mac? It would be really helpful if you could share any logs or error messages that highlight the incompatibility problems you're facing. This way, we can offer more targeted advice or solutions.

**Comment by huybery** [comment]
Provide a case: I am M2 and have no problems.

**Comment by rbren** [comment]
Closing this. Feel free to open a new issue with more details.

**Comment by tzenmatt** [comment]
<img width="323" alt="Screenshot 2024-03-30 at 18 15 53" src="https://github.com/OpenDevin/OpenDevin/assets/122181340/2ccb09cb-8183-42e9-99c4-a8a1f56c9476">

the docker installation isn't working, yes
