### ISSUE TITLE
Improve the model picker

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#397]
**What problem or use case are you trying to solve?**
The list of models is _massive_ (screenshot)

**Describe the UX of the solution you'd like**
Some ideas on how to fix this:
* Create a searchable dropdown, with a max-height (instead of using a `<select>`)
* Sort the models alphabetically
* Only show a shortlist of the 10-20 most popular models

**Do you have thoughts on the technical implementation?**
Probably use a searchable dropdown UI component, and sort

**Describe alternatives you've considered**
<img width="1191" alt="Screenshot 2024-03-30 at 12 23 59 PM" src="https://github.com/OpenDevin/OpenDevin/assets/7611973/b316175d-849b-4ff1-b0f0-df68ee3e3c60">

**Additional context**

**Comment by maruf-rahman007** [comment]
![image](https://github.com/OpenDevin/OpenDevin/assets/109809127/5a36c08c-724c-4bf8-aee1-ee05b07ccf5b)

It seems resolved. Could we add an enhancement to the UI where the cursor automatically focuses on the input box upon entering or reloading the page? This would enhance user experience.

**Comment by rbren** [comment]
Nice! Yeah feel free to open a ticket for the autofocus
