### ISSUE TITLE
Retrieve the list of agents from the backend

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#398]
**What problem or use case are you trying to solve?**
There's a new agent available (PlannerAgent). But it's not visible in the UI

**Describe the UX of the solution you'd like**
Same UX--just a new way of populating the options in the current agent picker

**Do you have thoughts on the technical implementation?**
Make the list of agents available in the backend, then populate the dropdown using that

Similar to: https://github.com/OpenDevin/OpenDevin/pull/370

**Describe alternatives you've considered**

**Additional context**

**Comment by manalarora** [comment]
I would like to take a stab at it, I have already added functionality in the ui to fetch it from the backend server.

Can someone help guide me how to get a list of available agents in python

**Comment by manalarora** [comment]
I have raised a PR, can someone check and help furhter on how to make changes in listen.py to get a list of avialble litellm agents

**Comment by manalarora** [comment]
@rbren I am new to open source, so would appreciate a little help here. Would love to contribute to this awesome project

**Comment by rbren** [comment]
Thanks for the contribution! This is in now
