### ISSUE TITLE
Use devin to code opendevin?

### ISSUE THREAD

**Issue by pandahighfive** [OpenDevin/OpenDevin#4]
..DevinCeption!!!

**Comment by JustinLin610** [comment]
Damn you are a genius!

**Comment by electyrion** [comment]
it might actually works

**Comment by fakerybakery** [comment]
It might actually work… if they’ll let you get access ;)

**Comment by PierrunoYT** [comment]
I had the same Idea :)

**Comment by jayathuc** [comment]
Make Devin make more devins so they can improve each other?

**Comment by neubig** [comment]
We're working on making it so you can use opendevin to code opendevin!

**Comment by CakeCrusher** [comment]
Request to reopen this issue untill Devin has had an opportunity to jailbreak.

**Comment by imbdb** [comment]
> Make Devin make more devins so they can improve each other?

This feels like  "Von Neumann Probe"
