### ISSUE TITLE
Where I can get the requirements.txt

### ISSUE THREAD

**Issue by arywidos** [OpenDevin/OpenDevin#401]
**What problem or use case are you trying to solve?**
It is very difficult for me without requirements.txt because there are too many errors related to no module found, Would you revert back the requirements.txt to minimize the errors related to missing dependencies? during the installation process.

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by theguy000** [comment]
same issue here lol

**Comment by rbren** [comment]
You can run `pipenv requirements > requirements.txt` to generate a requirements.txt

We're actively discussing package management here: https://github.com/OpenDevin/OpenDevin/issues/376

I'll add the workaround to the readme
