### ISSUE TITLE
What's the difference between OpenDevin and Devika?

### ISSUE THREAD

**Issue by code2graph** [OpenDevin/OpenDevin#415]
OpenDevin and Devika seems to be two completing projects.

When would one will use OpenDevin instead of Devika?

**Comment by PierrunoYT** [comment]
OpenDevin works better that's the difference actually.

**Comment by code2graph** [comment]
Why does it work better though? They both are using same GPT models.

**Comment by jojeyh** [comment]
This should be moved to Discussions

**Comment by rbren** [comment]
We're similar projects, both chasing after Devin. IMO OpenDevin's selling points are:
* a wider community of collaborators
* a "marketplace of agents" approach, which will help long-term innovation
* a (to be determined) open governance model, as opposed to being owned by a corporate entity (stition.ai)
