### ISSUE TITLE
Document how to use specific LLMs

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#417]
**What problem or use case are you trying to solve?**
Lots of folks are struggling to get OpenDevin working with non-OpenAI models. Local ollama seems to be particularly hard

**Describe the UX of the solution you'd like**
We should have a doc that lists out 3-4 major providers, explains how to get an API key, and how to configure OpenDevin

**Do you have thoughts on the technical implementation?**
Just a Models.md that we can link to from README.md

**Comment by gaborkukucska** [comment]
+1 for ollama support and documentation.

I get `ModuleNotFoundError: No module named 'llama_index.embeddings.ollama'` when
I use `LLM_EMBEDDING_MODEL="llama2"` and `ModuleNotFoundError: No module named 'llama_index.embeddings.huggingface'` when I use `LLM_EMBEDDING_MODEL="local"`

**Comment by enyst** [comment]
> Do you have thoughts on the technical implementation?
Just a Models.md that we can link to from README.md

I see github still has the wiki feature. I don't see it on opendevin, but IIRC that's because it would need enabled for the project. What if we use that for a few / several model-specific pages? I don't remember if access can be enabled widely but it's a wiki, I'd assume so.

**Comment by DanRegalia** [comment]
Can you update the supported tags for the .env with commands to connect to open llms, openAI/OllamaWebUI/Oogabooga/ETC?

**Comment by Dampfinchen** [comment]
IMO, Ollama is a nuisance because it requires GGUFs to be converted.

I recommend using llama.cpp, koboldcpp server and Ooba instead. Those are really easy to use inference programs.

**Comment by DGdev91** [comment]
Agreed. I also made a PR for setting LLM_BASE_URL with make setup-config.
Should be enough for any OpenAI-compatible https://github.com/OpenDevin/OpenDevin/pull/616

For example, it works with Koboldcpp by setting it like this:
LLM_API_KEY="."
LLM_MODEL="gpt-4-0125-preview"
LLM_BASE_URL="http://localhost:5001/v1/"
WORKSPACE_DIR="./workspace"

**Comment by JayQuimby** [comment]
I made a markdown file for Ollama #615.

**Comment by feuler** [comment]
I use oobabooga with the openai compabile api. And currently trying OpenCodeInterpreter-DS-33B (exl2) as model first. I'm not aware which non-openai/claude model works best yet...

config.toml:
WORKSPACE_DIR="./workspace"
LLM_API_KEY="sk-111111111111111111111111111111111111111111111111"
LLM_BASE_URL="http://127.0.0.1:5000"
LLM_EMBEDDING_MODEL="local"
LLM_MODEL="oobabooga/OpenCodeInterpreter-DS-33B-4.65bpw-h6-exl2"

After starting a development i currently get these kind of errors sometimes during the process:

ERROR:
'str' object has no attribute 'copy'
Traceback (most recent call last):
  File "/opt/llm/OpenDevin/opendevin/controller/agent_controller.py", line 113, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/llm/OpenDevin/agenthub/monologue_agent/agent.py", line 166, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/llm/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 135, in parse_action_response
    return action_from_dict(action_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/llm/OpenDevin/opendevin/action/__init__.py", line 24, in action_from_dict
    action = action.copy()
             ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'copy'

###############
ERROR:
"'action' key is not found in action={}"
Traceback (most recent call last):
  File "/opt/llm/OpenDevin/opendevin/controller/agent_controller.py", line 113, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/llm/OpenDevin/agenthub/monologue_agent/agent.py", line 166, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/llm/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 135, in parse_action_response
    return action_from_dict(action_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/llm/OpenDevin/opendevin/action/__init__.py", line 26, in action_from_dict
    raise KeyError(f"'action' key is not found in {action=}")
KeyError: "'action' key is not found in action={}"

**Comment by stratte89** [comment]
> Can you update the supported tags for the .env with commands to connect to open llms, openAI/OllamaWebUI/Oogabooga/ETC?

here is a guide for oobabooga webui
https://github.com/OpenDevin/OpenDevin/commit/08a2dfb01af1aec6743f5e4c23507d63980726c0#commitcomment-140559598

**Comment by rmortes** [comment]
> I use oobabooga with the openai compatible api. And currently trying OpenCodeInterpreter-DS-33B (exl2) as model first. I'm not aware which non-openai/claude model works best yet...
> 
> config.toml: WORKSPACE_DIR="./workspace" LLM_API_KEY="sk-111111111111111111111111111111111111111111111111" LLM_BASE_URL="http://127.0.0.1:5000" LLM_EMBEDDING_MODEL="local" LLM_MODEL="oobabooga/OpenCodeInterpreter-DS-33B-4.65bpw-h6-exl2"
> 
> After starting a development i currently get these kind of errors sometimes during the process:
> 
> ERROR: 'str' object has no attribute 'copy' Traceback (most recent call last): File "/opt/llm/OpenDevin/opendevin/controller/agent_controller.py", line 113, in step action = self.agent.step(self.state) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/llm/OpenDevin/agenthub/monologue_agent/agent.py", line 166, in step action = prompts.parse_action_response(action_resp) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/llm/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 135, in parse_action_response return action_from_dict(action_dict) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/llm/OpenDevin/opendevin/action/**init**.py", line 24, in action_from_dict action = action.copy() ^^^^^^^^^^^ AttributeError: 'str' object has no attribute 'copy'
> 
> ############### ERROR: "'action' key is not found in action={}" Traceback (most recent call last): File "/opt/llm/OpenDevin/opendevin/controller/agent_controller.py", line 113, in step action = self.agent.step(self.state) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/llm/OpenDevin/agenthub/monologue_agent/agent.py", line 166, in step action = prompts.parse_action_response(action_resp) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/llm/OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 135, in parse_action_response return action_from_dict(action_dict) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/llm/OpenDevin/opendevin/action/**init**.py", line 26, in action_from_dict raise KeyError(f"'action' key is not found in {action=}") KeyError: "'action' key is not found in action={}"

Getting a similar error using the following config in MacOS
<details>
<summary>config.toml</summary>

```toml
LLM_MODEL="ollama/deepseek-coder:instruct"
LLM_API_KEY="ollama"
LLM_EMBEDDING_MODEL="local"
LLM_BASE_URL="http://localhost:11434"
WORKSPACE_DIR="./workspace"
```
</details>

```
Oops. Something went wrong: 'str' object has no attribute 'copy'
Oops. Something went wrong: "'action['action']=None' is not defined. Available actions: dict_keys(['kill', 'run', 'browse', 'read', 'write', 'recall', 'think', 'finish', 'add_task', 'modify_task'])"
```

**Comment by Rags100** [comment]
Hello Team, Few basic questions

1. Do we need run Make build and other commands in CMD or Ubuntu?
2.  How to get API Key

Please assist

**Comment by rbren** [comment]
@Rags100 this isn't really the right place for your question. Please follow the README, and search our issues for related problems (there's an existing one for uvloop--you'll need WSL to make it work).

If you continue to have trouble, feel free to file a new issue with the template filled out. Thanks!

**Comment by SNEHAL-VATS** [comment]
snehalvats@DESKTOP-11UAB1I:/mnt/e/OpenDevin-main$ sudo make build
Building project...
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest
Installing Python dependencies...
Retrieving Poetry metadata

The latest version (1.8.2) is already installed.

  Stack trace:

  11  /usr/lib/python3/dist-packages/clikit/console_application.py:123 in run
      io = io_factory(

  10  /usr/lib/python3/dist-packages/poetry/console/config/application_config.py:221 in create_io
      resolved_command = application.resolve_command(args)

   9  /usr/lib/python3/dist-packages/clikit/console_application.py:110 in resolve_command
      return self._config.command_resolver.resolve(args, self)

   8  /usr/lib/python3/dist-packages/clikit/resolver/default_resolver.py:34 in resolve
      return self.create_resolved_command(result)

   7  /usr/lib/python3/dist-packages/clikit/resolver/default_resolver.py:166 in create_resolved_command
      if not result.is_parsable():

   6  /usr/lib/python3/dist-packages/clikit/resolver/resolve_result.py:43 in is_parsable
      self._parse()

   5  /usr/lib/python3/dist-packages/clikit/resolver/resolve_result.py:49 in _parse
      self._parsed_args = self._command.parse(self._raw_args)

   4  /usr/lib/python3/dist-packages/clikit/api/command/command.py:113 in parse
      return self._config.args_parser.parse(args, self._args_format, lenient)

   3  /usr/lib/python3/dist-packages/clikit/args/default_args_parser.py:53 in parse
      self._parse(args, _fmt, lenient)

   2  /usr/lib/python3/dist-packages/clikit/args/default_args_parser.py:101 in _parse
      self._parse_long_option(token, tokens, fmt, lenient)

   1  /usr/lib/python3/dist-packages/clikit/args/default_args_parser.py:247 in _parse_long_option
      self._add_long_option(name, None, tokens, fmt, lenient)

  NoSuchOptionException

  The "--without" option does not exist.

  at /usr/lib/python3/dist-packages/clikit/args/default_args_parser.py:300 in _add_long_option
      296│     def _add_long_option(
      297│         self, name, value, tokens, fmt, lenient
      298│     ):  # type: (str, Optional[str], List[str], ArgsFormat, bool) -> None
      299│         if not fmt.has_option(name):
    → 300│             raise NoSuchOptionException(name)
      301│
      302│         option = fmt.get_option(name)
      303│
      304│         if value is False:
make: *** [Makefile:20: build] Error 1


I received this error but I let it go and just followed the steps and then reached the `make run` command. It is now just stuck at this:
snehalvats@DESKTOP-11UAB1I:/mnt/e/OpenDevin-main$ make run
Running the app...
Waiting for the backend to start...

What to do? I am running Ubuntu on Windows 11.

**Comment by DOLARIK** [comment]
Failed to resolve import "../i18n/declaration" from "src/components/Workspace.tsx". Does the file exist? 

how to resolve this? i18n doesn't have any declaration

**Comment by yashupadhyayy1** [comment]
Hey, I tried to run the openDevin in my pc's vs code 3 days ago it were working fine in making html code on there but when i asked to build a react or npm or npx it was showing error about not finding the npm in there( I guess it were at wsl or in ubantu based ). I am not totally were that from where to install all requirements in setup. is it in my local machine or or in wsl subsystem?

**Comment by grey-demon** [comment]
after i ran

```
make start-backend
```

and 

```
make start-frontend
```


i then opened my brower on localhost:3001

the console of backend displayed this? how do i fix this?
```
INFO:     connection open
INFO:     127.0.0.1:50890 - "GET /configurations HTTP/1.1" 200 OK
INFO:     127.0.0.1:50888 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     127.0.0.1:50892 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:50904 - "GET /refresh-files HTTP/1.1" 200 OK
17:42:19 - opendevin:INFO: sandbox.py:118 - Using workspace directory: /mnt/d/Data/VSCode/AI/OpenDevin/workspace
17:42:21 - opendevin:ERROR: manager.py:134 - Error creating controller.
Traceback (most recent call last):
  File "/mnt/d/Data/VSCode/AI/OpenDevin/opendevin/server/agent/manager.py", line 125, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/mnt/d/Data/VSCode/AI/OpenDevin/opendevin/controller/agent_controller.py", line 86, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/mnt/d/Data/VSCode/AI/OpenDevin/opendevin/controller/command_manager.py", line 14, in __init__
    self.shell = DockerInteractive(
                 ^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Data/VSCode/AI/OpenDevin/opendevin/sandbox/sandbox.py", line 139, in __init__
    self.start_ssh_session()
  File "/mnt/d/Data/VSCode/AI/OpenDevin/opendevin/sandbox/sandbox.py", line 167, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=2222)
  File "/root/.cache/pypoetry/virtualenvs/opendevin-efAE98hl-py3.11/lib/python3.11/site-packages/pexpect/pxssh.py", line 440, in login       
    raise ExceptionPxssh('password refused')
pexpect.pxssh.ExceptionPxssh: password refused
```

this is my config.toml
```
LLM_MODEL="ollama/llama2"
LLM_API_KEY=""
LLM_BASE_URL="http://localhost:11434"
LLM_EMBEDDING_MODEL="llama2"
WORKSPACE_DIR="./workspace"
```

**Comment by rbren** [comment]
Hey all--lots of unrelated comments in this thread. Please try to keep this about LLM Model documentation.

I'm going to delete the unrelated comments--feel free to open new issues if you're having trouble

**Comment by enyst** [comment]
Documentation for Azure: https://github.com/OpenDevin/OpenDevin/pull/1035

**Comment by larkinwc** [comment]
Added documentation for using Google's Gemini model through AI studio as well as VertexAI through GCP #1321

**Comment by rbren** [comment]
We've made a lot of progress on this one, so I'm going to close it. More docs welcome!

**Comment by Jammer77** [comment]
Looking for solution for llama.cpp  that doesn't work for me:  

LLM_MODEL=codellama
LLM_BASE_URL=http://127.0.0.1:8080/v1
LLM_API_KEY=no
LLM_EMBEDDING_MODEL=local
LLM_PROVIDER=llama-cpp
LLAMA_CPP_SERVER_HOST=127.0.0.1
LLAMA_CPP_SERVER_PORT=8080
