### ISSUE TITLE
Really long load time when UI first loads

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#418]
**Describe the bug**
We send a few API requests on first load
* websocket connect
* GET models
* GET agents

It takes a good 5-10s for any of these endpoints to respond. And it looks like we're double-requesting the GET requests.

All three should respond pretty quickly if things are working correctly.

**Steps to Reproduce**
1. open the network tab in browser console
2. load the UI
3. see pending requests

**Expected behavior**
Requests (at least the GETs) load quickly

**Actual behavior**
Sits pending for > 5s

**Additional context**

Hopefully this isn't just my machine...
<img width="501" alt="Screenshot 2024-03-30 at 7 45 24 PM" src="https://github.com/OpenDevin/OpenDevin/assets/7611973/cf9110bc-7e46-4e66-a74d-db574356e360">

**Comment by xcodebuild** [comment]
- Double-requesting the GET requests is not a bug, `useEffect` run twice in dev mode
- Maybe https://github.com/OpenDevin/OpenDevin/pull/454 can fix this if you dose not set `VITE_WS_URL` and `VITE_API_URL `

**Comment by ASQUAREEE** [comment]
In development mode only, it requests twice. Removing React.StrictMode prevents the double request. This occurs because in development mode, useEffect is mounted, unmounted, and then mounted again, triggering the API call twice
![image](https://github.com/OpenDevin/OpenDevin/assets/99893402/68c21602-6549-4ca1-8201-392fb306dc78)

**Comment by ASQUAREEE** [comment]
@rbren  If we skip waiting for the controller creation, the initialization process will be faster. What do you suggest?

**Comment by rbren** [comment]
My real concern here is how long it takes for the GET requests to succeed. Since they're population UI options, it feels kinda broken (the options in the dropdowns suddenly change ~5s after loading)

What's causing the GETs to hang? Is it waiting for initialization?

**Comment by yimothysu** [comment]
The websocket is somehow blocking. If you remove the websocket handler, the GET request is nearly instantaneous.

**Comment by yufansong** [comment]
Do some local test. Provide my personal opinion which slight different from above discussion. 
1. When launch the project at first time, it will be very quickly, finish in around 2 seconds.
2. When refresh the website, it will need 10+s to initialization. And the probelm happend in it will try to [kill the previous docker env](https://github.com/OpenDevin/OpenDevin/blob/c37124d74022fc73f32a576d88dd59db2ebfe2ac/opendevin/sandbox/sandbox.py#L210). This process will cost around 10s, which is the key point result the slow initializaiton.

**Comment by yufansong** [comment]
Add a PR to fix it #557.
