### ISSUE TITLE
Getting stuck with observation 'Error condensing thoughts: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by santonakakis** [OpenDevin/OpenDevin#420]
I have tried this with both claude-3-opus-20240229s and gpt-4--0125-preview:

changeset from 3/30/2024:
git log -1 --pretty=format:"%H"
87d56d961ffb0410b8dc423b0a2494d602778c36

**Steps to Reproduce**
1. Requested creation of a python package with four named modules, using pytest and pytest-bdd with an initial placeholder and the package dependency manager of od's choice
2. It makes it as far as installing poetry and then receive the issue.
3. I would stop backend and front end and restart with a prompt to 'resume where we left off' - it would detect and continue then fail again on the same, post poetry install.
4. I would thenk stop backend and front end swap from Claude to GPT4 with same prompt --- same outcome

**Additional context**
![image](https://github.com/OpenDevin/OpenDevin/assets/112708907/b330fc14-4c53-46ab-add0-cd925a710b6f)

![image](https://github.com/OpenDevin/OpenDevin/assets/112708907/b60ac002-7e19-4ddb-a1dc-b990ea2edf24)

**Comment by enyst** [comment]
This happens sometimes when the LLM sends the JSON enclosed in backticks. I'll look into fixing it tomorrow, if someone doesn't get to it sooner.

**Comment by ntrpnr** [comment]
Got this error both with GPT4 and Claude Opus.

**Comment by leewsimpson** [comment]
this is not sometimes for me - this happens everytime at some point.

**Comment by PBenavides** [comment]
@leewsimpson Same here. I'm not able to completely test the repo

**Comment by rbren** [comment]
Should be fixed now. Thanks for the report y'all!
