### ISSUE TITLE
Create a Makefile for  the full project to make the project setup much easier

### ISSUE THREAD

**Issue by dorbanianas** [OpenDevin/OpenDevin#429]
**What problem or use case are you trying to solve?**

This Makefile streamlines the setup and execution of the OpenDevin project. It automates tasks like installing dependencies, starting servers, picking models, and running the application, simplifying development and promoting consistency.

**Comment by rbren** [comment]
We're working on a Dockerfile here: https://github.com/OpenDevin/OpenDevin/pull/377

Will that suffice?

**Comment by dorbanianas** [comment]
I guess they have different purposes for the Makefile would be important for the dev side while Docker compose would help with the prod side

**Comment by rbren** [comment]
Makes sense to me! Let's get this one in
