### ISSUE TITLE
Docker container becomes unmanageble 

### ISSUE THREAD

**Issue by bxck75** [OpenDevin/OpenDevin#431]
**Describe the bug**
Docker container becomes unmanageble ...can't close container and also can not resatart backend because docker exits with error
only after reboot of system can it be run again
**Steps to Reproduce**
1.start backend and frontend
2. quit backend with ctrl-c because (in my case the agent tried installing torch gpu on a non gpu system and froze the backend)
3. unmanageble docker ...docker wont do anything any more  

**Expected behavior**
clean exit
**Actual behavior**
unusable docker untill reboot of system
**Additional context**

**Comment by jojeyh** [comment]
@bxck75 Can you please display the commands you used and logs?

**Comment by tonyppe** [comment]
op you are running ubuntu I guess and apparmor is blocking access to the container to kill it. check your logs.

**Comment by rbren** [comment]
This sounds like a docker issue, not an OpenDevin issue. Running a container shouldn't ever block the daemon, and we're not doing anything all that strange w/ docker.

I'm going to close this, but @bxck75 let us know if you think OpenDevin is truly at fault here.

**Comment by bxck75** [comment]
First of all i would like to compliment you guys on this great project. I went through the code and tried to see if i could find any obvious reason for the issue. But could not find any. Code lòoks ok..still. After the forced stopping of the backend my docker would not stop, restart ok run any other containers. Only after reboot i got docker working as normal again. I am indeed running ubuntu 22.04...this evening i will try again and save all possible logs and commands...Tonyppe could you shine light on what could be the issue with apparmor and how i could test to see if this is causing the issue. Thanks for the quick reply. Big fan..grtz...K00b404
