### ISSUE TITLE
im runnig llama 2 llm on local server  through Lm studio after i add custom llm url in the config.toml :

### ISSUE THREAD

**Issue by SaimNadeemdev** [OpenDevin/OpenDevin#446]
**Describe the bug**

**Steps to Reproduce**
1.
2.
3.

**Expected behavior**

**Actual behavior**

**Additional context**

**Comment by rbren** [comment]
@SaimNadeemdev we need more information here if you want help. I'm going to close this, but feel free to open a new issue, with the template fully filled out
