### ISSUE TITLE
Please help trying to help Local LLM

### ISSUE THREAD

**Issue by SaimNadeemdev** [OpenDevin/OpenDevin#447]
**Describe the bug**
im runnig llama 2 llm on local server  through Lm studio after i add custom llm url in the config.toml :
LLM_BASE_URL="http://localhost:1234/v1"
WORKSPACE_DIR="./workspace"

this error happens :

Oops. Something went wrong: Error condensing thoughts: OpenAIException - Traceback (most recent call last): File "C:\Users\Saim\.virtualenvs\OpenDevin-mBWLJISc\Lib\site-packages\litellm\llms\openai.py", line 376, in completion raise e File "C:\Users\Saim\.virtualenvs\OpenDevin-mBWLJISc\Lib\site-packages\litellm\llms\openai.py", line 312, in completion openai_client = openai( ^^^^^^^ File "C:\Users\Saim\.virtualenvs\OpenDevin-mBWLJISc\Lib\site-packages\openai\_client.py", line 98, in __init__ raise openaiError( openai.openaiError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

**Comment by rbren** [comment]
You need to set `LLM_MODEL` to something like `ollama/llama2`

see "Picking a Model" here: https://github.com/opendevin/opendevin?tab=readme-ov-file#picking-a-model
