### ISSUE TITLE
Very Very unsafe attachment to OpenAI services

### ISSUE THREAD

**Issue by Kingbadger3d** [OpenDevin/OpenDevin#448]
**Ask your software to do a task with GPT4 selected, failed but managed to wipe out $16 credit in 30 mins**

**Steps to Reproduce**
1. Install your tool
2.run your tool
3.tool doesn't work but steals all your credits money

**not to spam your gpt account, this could cost someone thousands if they haven't properly setup limits with OpenAI billing**

**Broken, doesn't do anything, But cost you a fortune**

**Additional context**

**Comment by rbren** [comment]
@Kingbadger3d sorry this happened. We do set a maximum number of iterations. We could probably do more to put in-app limits on how many requests/tokens are sent. I'll open a separate issue.

**Comment by rbren** [comment]
https://github.com/OpenDevin/OpenDevin/issues/449
