### ISSUE TITLE
Updating main.py and the other python scripts to be compatible with Windows

### ISSUE THREAD

**Issue by AbdelrahmanHassan111** [OpenDevin/OpenDevin#458]
after running open Devin by the command: 
```
set PYTHONPATH=%cd%
python opendevin\main.py -d .\workspace\ -i 100 -t "Write a bash script that prints 'hello world'"

```
we got an error that: 
```
\opendevin\opendevin\main.py", line 1, in <module>
    from opendevin.agent import Agent
ModuleNotFoundError: No module named 'opendevin'
```
as shown here in the error : 

![Screenshot 2024-03-31 151127](https://github.com/OpenDevin/OpenDevin/assets/156480367/e28d4120-4100-411a-b7d8-a7cdd73a8133)

so when we checked **main.py**  we found an error in the syntax as shown here:

![Screenshot 2024-03-31 151340](https://github.com/OpenDevin/OpenDevin/assets/156480367/bc79f36e-9e92-4d5c-8c46-e09768ca663b)

to solve this we want to modify package calling like this:

![Screenshot 2024-03-31 151527](https://github.com/OpenDevin/OpenDevin/assets/156480367/77b6aca5-aac2-41c0-81fd-467820696bb6)

and the modification should be applied on all Python files that have any package calling  like **--inti--.py** ...etc

**Comment by rbren** [comment]
I'm fine with this. I've never been sure of the best syntax for imports in python.

But I don't think this is really a Windows issue--it crops up everywhere

**Comment by AbdelrahmanHassan111** [comment]
> I'm fine with this. I've never been sure of the best syntax for imports in python.
> 
> But I don't think this is really a Windows issue--it crops up everywhere
I'm trying to install it without WSL 
TBH the installation till this step works successfully without WSL and everything is good. so, I'm working on this I'll complete it and I'll get you updated

**Comment by rbren** [comment]
I'm going to close this one--seems like a combination of different edge cases
