### ISSUE TITLE
Have OpenDevin work on OpenDevin Issues

### ISSUE THREAD

**Issue by rkeshwani** [OpenDevin/OpenDevin#459]
**What problem or use case are you trying to solve?**
This repo is getting popular and you will get overwhelmed quickly.
Have you thought about delegating some issues to OpenDevin?

There are also solutions like https://github.com/apps/dosubot to help you manage the repository.

**Comment by rbren** [comment]
See https://github.com/OpenDevin/OpenDevin/issues/198

😄 I'm excited for this one
