### ISSUE TITLE
Google Gemini 

### ISSUE THREAD

**Issue by heisentberg** [OpenDevin/OpenDevin#461]
We need to import the Google Gemini Pro API. This can help many individuals create exciting projects for free.

**Comment by rbren** [comment]
See https://github.com/OpenDevin/OpenDevin?tab=readme-ov-file#picking-a-model for Gemini support

Also https://github.com/OpenDevin/OpenDevin/issues/417

**Comment by heisentberg** [comment]
Are there any tutorials available? I've attempted several times without success.

**Comment by rbren** [comment]
#417 is our call for tutorials--if you figure it out, comment there with your setup!
