### ISSUE TITLE
src/components/ChatInterface.tsx:56:16 - error TS2786: 'TypingChat' cannot be used as a JSX component

### ISSUE THREAD

**Issue by robertZaufall** [OpenDevin/OpenDevin#467]
**Describe the bug**

**Steps to Reproduce**
1. npm run build

**Expected behavior**
can compile

**Actual behavior**
error

**Additional context**
> opendevin-frontend@0.1.0 build
> tsc && vite build

src/components/ChatInterface.tsx:56:16 - error TS2786: 'TypingChat' cannot be used as a JSX component.
  Its return type '"" | Element' is not a valid JSX element.
    Type 'string' is not assignable to type 'ReactElement<any, any>'.

56               <TypingChat msg={msg} />
                  ~~~~~~~~~~


Found 1 error in src/components/ChatInterface.tsx:56

**Comment by rbren** [comment]
Should be fixed now--lmk if we need to reopen
