### ISSUE TITLE
Add "stop/cancel" button

### ISSUE THREAD

**Issue by Kapowpenguin1** [OpenDevin/OpenDevin#470]
while using claude, it sometimes gives a "rate limit" error, and spits out a ton of these messages in the chat. maybe the user could pause the chat, or the system could timeout whenever it detects such an error?

the error, for reference:
Oops. Something went wrong: Error condensing thoughts: AnthropicException - {"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your rate limit (https://docs.anthropic.com/claude/reference/rate-limits). Please reduce the the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}

**Comment by rbren** [comment]
See also: https://github.com/OpenDevin/OpenDevin/issues/332

**Comment by rbren** [comment]
I think a good solution here is to give the user the ability to stop/cancel the current task

**Comment by marikan114** [comment]
How about defining a parameter in config.toml to throttle requests per minute?

**Comment by rbren** [comment]
Oh good point @robshox, would be nice to do 10 iterations, then have the option to continue

**Comment by rbren** [comment]
Related: https://github.com/OpenDevin/OpenDevin/issues/1049
