### ISSUE TITLE
The typewriter feature is disconcerting when responses are longer than a few lines

### ISSUE THREAD

**Issue by enyst** [OpenDevin/OpenDevin#476]
**Describe the bug**
The chat with OpenDevin the AI now displays its thoughts character-by-character, which creates a cool impression of thinking as it "types". But that impression breaks when the second line and the third line start to be filled in the same time, in parallel. I imagine that this has to work sequentially, finish a thought, then start typing the next.

**Steps to Reproduce**
1. Give our AI a task, bigger than hello world.
2. Sit back and watch its train of thought... if you can. 😅 

**Expected behavior**
Sequential display, to be able to follow its reasoning.

**Actual behavior**
Parallel display: as you read its thoughts, when one is longer than a few lines, the second starts.
In many occasions, the third starts too, and they all fill their rows.

**Comment by arywidos** [comment]
Hahahha same erorr here

Client websocket disconnected (<CloseCode.ABNORMAL_CLOSURE: 1006>, None)
Error sending data to client

**Comment by 808vita** [comment]
@enyst thanks for the detailed bug submission; I will try to make use of things you have stated.

**Comment by rbren** [comment]
Should be fixed now!
