### ISSUE TITLE
Frontend : The text editor is settings to choose a model is not necessary

### ISSUE THREAD

**Issue by Yashwanth-Chandrakumar** [OpenDevin/OpenDevin#482]
**Describe the bug**
The settings menu in Open Devin is used to select the directory and the model, even though there is a dropdown menu there is typing option available which is not necessary.

**Steps to Reproduce**
1.Run OpenDevin
2.Click on Settings
3.Click the model name

**Expected behavior**
Open Dropdown

**Actual behavior**
Text editing option appears

Please confirm whether this is the intended behaviour or  @rbren 

https://github.com/OpenDevin/OpenDevin/assets/121328223/4938ba51-12c1-404f-a051-a62096f0b095

**Comment by rbren** [comment]
@Yashwanth-Chandrakumar @jojeyh I think the idea is that the dropdown is searchable--you can type to filter the options. Is that not the case?

**Comment by yimothysu** [comment]
This is intended behavior.
