### ISSUE TITLE
Incorrect API key does not fail gracefully. 

### ISSUE THREAD

**Issue by CakeCrusher** [OpenDevin/OpenDevin#483]
**Describe the bug**
If incorrect LLM_API_KEY passed then the agent loops endlessly.
**Steps to Reproduce**
1. Pass in incorrect API key
2. Submit a chat message
3. See failure message loop

**Expected behavior**
Toast suggesting incorrect API key.
**Actual behavior**
Agent loops endlessly.
**Additional context**
![image](https://github.com/OpenDevin/OpenDevin/assets/37946988/7dfea541-88fb-41d0-b632-f6fcce22ca13)
![image](https://github.com/OpenDevin/OpenDevin/assets/37946988/f1edce4b-f291-478a-87fa-b3c7d9ce04ef)

**Comment by enyst** [comment]
Also tracked here: https://github.com/OpenDevin/OpenDevin/issues/326

**Comment by enyst** [comment]
I see your point on user error. I think you're right that it's worth tracking separately.

The worst thing that happens for the user experience, and which IMHO we need to fix first though, is similar: the infinite loop part.
