### ISSUE TITLE
Frontend : Unnecessary linebreak when text message in sent.

### ISSUE THREAD

**Issue by Yashwanth-Chandrakumar** [OpenDevin/OpenDevin#489]
**Describe the bug**
The "Enter" key is used to send a message in chat, but when the key is pressed message gets sent but a enter space is automatically entered. 

**Steps to Reproduce**
1.Run OpenDevin
2.Send a message by clicking enter
3.You would notice a bug where there is a existing line break

**Expected behavior**
Normal text bar

**Actual behavior**
Line break occurs.

https://github.com/OpenDevin/OpenDevin/assets/121328223/eaa70a81-2542-457c-8c58-554f886bb727

**Comment by ryanlohyr** [comment]
Could I take this up?

**Comment by Sparkier** [comment]
I hink this is not an issue anymore. Can be closed IMO.
