### ISSUE TITLE
Google Gemini

### ISSUE THREAD

**Issue by heisentberg** [OpenDevin/OpenDevin#490]
Are there any tutorials available? I've attempted several times without success. We need to import the Google Gemini Pro API. This can help many individuals create exciting projects for free.

**Comment by jojeyh** [comment]
You should be able to use Gemini Pro by setting `LLM_MODEL=gemini/gemini-pro` and `LLM_API_KEY=<your key>`.

**Comment by rbren** [comment]
See https://github.com/OpenDevin/OpenDevin/issues/417
