### ISSUE TITLE
404 Error but only with OpenAI

### ISSUE THREAD

**Issue by bamit99** [OpenDevin/OpenDevin#493]
Getting this error when I am using OpenAI keys. Keys are fine since I am using them in other projects and even a short test Python Script. I can get OpenDevin to work with Ollama for whatever it's worth but OpenAI keeps failing. Claude works too! Is my format of Config file correct?

![image](https://github.com/OpenDevin/OpenDevin/assets/32737966/cd05a9ea-3249-4e68-9d16-5fb68e71f12d)
![image](https://github.com/OpenDevin/OpenDevin/assets/32737966/b7094475-32ca-45d8-a0fe-5a042c0ff8e8)

**Comment by rbren** [comment]
@bamit99 what do you have LLM_MODEL set to? There is no gpt-3.5-turbo-0125 model

https://docs.litellm.ai/docs/providers/openai
