### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by clening** [OpenDevin/OpenDevin#498]
**Describe the bug**

**Steps to Reproduce**
1. Followed all install steps -- including python -m pipenv requirements > requirements.txt && python -m pip install -r requirements.txt
2. Finished backend steps and then launched new terminal to load frontend.  
3. Received following error when running npm start: 

 ~/OpenDevin/frontend
 % npm start

> opendevin-frontend@0.1.0 start
> vite

file:///home/xxxx/OpenDevin/frontend/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

Tried ignoring and loading 127.0.0.1:3000 and received {"detail":"Not Found"}

Backend logs INFO reports: 

INFO:     Started server process [10464]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     127.0.0.1:53266 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:53266 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:54462 - "GET / HTTP/1.1" 404 Not Found

**Expected behavior**
OpenDevin runs

**Actual behavior**
{"detail":"Not Found"}
INFO:     127.0.0.1:54462 - "GET / HTTP/1.1" 404 Not Found

**Additional context**

**Comment by omutist** [comment]
I run into this issue yesterday

Check npm version
`node --version`

If your version is older than 14.8.0, update Node.js
If you have nvm installed, you can upgrade using the following commands:
```
nvm install --lts
nvm use --lts
```

This helped me, but I'm not an expert here.

**Comment by rbren** [comment]
Yup this is an old node version. We explicitly require 14.8+

**Comment by clening** [comment]
Thank you so much omutist! That absolutely was the problem. Everything's working now.
