### ISSUE TITLE
Error sending data to client

### ISSUE THREAD

**Issue by jojogamerCt** [OpenDevin/OpenDevin#507]
**Describe the bug**
Basically when I give a prompt, after a few steps OpenDevin stops everything.

**Steps to Reproduce**
1. Connect both to backend and frontend
2. Give OpenDevin a task

**Expected behavior**
OpenDevin should continue developing the application and never stop

**Actual behavior**
OpenDevin actually stops after a few steps

**Additional context**
![Screenshot 2024-04-01 181105](https://github.com/OpenDevin/OpenDevin/assets/51884596/ec59c0f0-1299-4b05-8fd3-2d3a0eed7255)

**Comment by rbren** [comment]
@jojogamerCt I'm going to close this in favor of https://github.com/OpenDevin/OpenDevin/issues/235

But feel free to chime in on that issue if you can provide any more logs etc
