### ISSUE TITLE
Websocket Abnormal Closure During Think Action

### ISSUE THREAD

**Issue by GRVYDEV** [OpenDevin/OpenDevin#512]
**Describe the bug**
The agent will randomly stop during a think action with an websocket abnormal_closure

**Steps to Reproduce**
1. Normal usage

**Expected behavior**
No crash and continued thought

**Actual behavior**
Websocket closes and agent stops

**Additional context**

Logs:
```==============
STEP 29
	
	PLAN:
	
	🔵 0 We need to update the genserver in lib/sym/my_gen_server to create a retell LLM on init. Here are the API docs https://docs.retellai.com/api-references/create-retell-llm
	
Repaired JSON: {"action": "think", "args": {"thought": "With the integration of the HTTP request for creating a Retell LLM now coded into the MyGenServer's init/1 function, the next logical step is to ensure its functionality in a real-world scenario. This means conducting a test to verify that the GenServer, upon initialization, successfully makes the POST request to the Retell API, receives a response, and correctly handles that response. To accomplish this, unit tests should be written to simulate the initialization of the GenServer and mock the HTTP response from the Retell API. Additionally, manual testing might be required to observe the interaction and potential logging of any errors or successful creation messages. It's also important to consider the handling of API keys securely and how they're managed within the application's environment or config files."}}
Original JSON: {
  "action": "think",
  "args": {
    "thought": "With the integration of the HTTP request for creating a Retell LLM now coded into the MyGenServer's init/1 function, the next logical step is to ensure its functionality in a real-world scenario. This means conducting a test to verify that the GenServer, upon initialization, successfully makes the POST request to the Retell API, receives a response, and correctly handles that response. To accomplish this, unit tests should be written to simulate the initialization of the GenServer and mock the HTTP response from the Retell API. Additionally, manual testing might be required to observe the interaction and potential logging of any errors or successful creation messages. It's also important to consider the handling of API keys securely and how they're managed within the application's environment or config files."
  }
}
	
	ACTION:
	AgentThinkAction(thought="With the integration of the HTTP request for creating a Retell LLM now coded into the MyGenServer's init/1 function, the next logical step is to ensure its functionality in a real-world scenario. This means conducting a test to verify that the GenServer, upon initialization, successfully makes the POST request to the Retell API, receives a response, and correctly handles that response. To accomplish this, unit tests should be written to simulate the initialization of the GenServer and mock the HTTP response from the Retell API. Additionally, manual testing might be required to observe the interaction and potential logging of any errors or successful creation messages. It's also important to consider the handling of API keys securely and how they're managed within the application's environment or config files.", action='think')
Error sending data to client 
Client websocket disconnected (<CloseCode.ABNORMAL_CLOSURE: 1006>, None)
Error sending data to client 
```

**Comment by rbren** [comment]
Closing in favor of https://github.com/OpenDevin/OpenDevin/issues/235

Definitely need to figure this one out

**Comment by Lego4005** [comment]
Same here. Installed on my Ubuntu machine same network. Launched got it to do some basic task but anything that takes some thinking every time i get a disconnected socket as well.  

`Repaired JSON: {"action": "think", "args": {"thought": "To initiate project development, I must first create a project directory structure and initialize a Node.js project. This involves creating a directory for the project, initializing it as a Node.js project with 'npm init', and installing necessary dependencies like 'express' for server handling, 'axios' for making API requests, and potentially a library such as 'sequelize' for database management. Additionally, setting up environment variables for API keys and sensitive data is crucial for security."}}
Original JSON: {
  "action": "think",
  "args": {
    "thought": "To initiate project development, I must first create a project directory structure and initialize a Node.js project. This involves creating a directory for the project, initializing it as a Node.js project with 'npm init', and installing necessary dependencies like 'express' for server handling, 'axios' for making API requests, and potentially a library such as 'sequelize' for database management. Additionally, setting up environment variables for API keys and sensitive data is crucial for security."
  }
}

        ACTION:
        AgentThinkAction(thought="To initiate project development, I must first create a project directory structure and initialize a Node.js project. This involves creating a directory for the project, initializing it as a Node.js project with 'npm init', and installing necessary dependencies like 'express' for server handling, 'axios' for making API requests, and potentially a library such as 'sequelize' for database management. Additionally, setting up environment variables for API keys and sensitive data is crucial for security.", action='think')
Client websocket disconnected (<CloseCode.ABNORMAL_CLOSURE: 1006>, None)
INFO:     connection closed`

**Comment by BinaryBeastMaster** [comment]
I get it every time as well. This time I see its related to the token count. App doesn't crash, just stops working.

Projects\OpenDevin\OpenDevin\agenthub\langchains_agent\utils\monologue.py", line 36, in condense
    raise RuntimeError(f"Error condensing thoughts: {e}")
RuntimeError: Error condensing thoughts: OpenAIException - Error code: 400 - {'error': {'message': "This model's maximum context length is 128000 tokens. However, your messages resulted in 135795 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
Error sending data to client
Client websocket disconnected (<CloseCode.ABNORMAL_CLOSURE: 1006>, None)
INFO:     connection closed
