### ISSUE TITLE
Add Option to save or write logs to a file

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#525]
**What problem or use case are you trying to solve?**
Debug Errors

**Describe the UX of the solution you'd like**
Option to auto save logs or a button to click where you can save the logs to a file.

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by rbren** [comment]
You can add `PROMPT_DEBUG_DIR` to get full prompts and responses that were sent to or received from the LLM.

Is that what you're looking for?

**Comment by enyst** [comment]
Thanks, @PierrunoYT, yes, we need it. I'm working on this and will have a PR soon (tomorrow probably). No button, but I'll propose both some automatic logging (errors), and the rest configurable in a logging config file.

**Comment by rbren** [comment]
I believe this is fixed. @enyst feel free to reopen if I'm wrong
