### ISSUE TITLE
Agent wouldn't take any inputs

### ISSUE THREAD

**Issue by alphaabhi** [OpenDevin/OpenDevin#526]
**After completing the setup when I am accessing devin at localhost:3001, when trying to give any inputs it's not taking anything and is stuck on intializing agent**

**Steps to Reproduce**
1. Open devin at localhost:3001
2. Try to give input
3.

**Should take input and provide resopnse**

**Nothing is happening on the agent
**

**Additional context**

![devin_error](https://github.com/OpenDevin/OpenDevin/assets/39146300/695a156f-358a-431d-9d5c-bd1fda27942e)

**Comment by foragerr** [comment]
As the UI indicates, the agent initializing did not complete. Do you see anything in the logs for backend?
did you set an env var for openAI or alternate LLM authentication?

**Comment by alphaabhi** [comment]
Working fine after restarting the project
