### ISSUE TITLE
Create MemGPT agent

### ISSUE THREAD

**Issue by ajeema** [OpenDevin/OpenDevin#530]
**What problem or use case are you trying to solve?**
Increased context window for agents
**Describe the UX of the solution you'd like**
This could be an option in settings to enable and configure
**Do you have thoughts on the technical implementation?**
I can look into it for sure but wanted to float the idea by first
**Describe alternatives you've considered**

**Additional context**

**Comment by rbren** [comment]
https://github.com/cpacker/MemGPT

**Comment by zhonggegege** [comment]
I think this 's indeed an issue that cannot be ignored. Although RAG technology is not mature even at present, as a function, we try to embed it into an existing mature project and try to improve the basic implementation of our project. This is a good way.

**Comment by neubig** [comment]
Closing in favor of #2487, which is probably a more reasonable way to describe integration of MemGPT in OpenDevin than having a separate agent.
