### ISSUE TITLE
Use `python -m pip` in Makefile

### ISSUE THREAD

**Issue by odiumuniverse** [OpenDevin/OpenDevin#544]
Change in Makefile `pip install pipenv` on `pip3 install pipenv` or `brew install pipenv`

**Comment by AbhisekOmkar** [comment]
can you use conda env

**Comment by dragoalato1988** [comment]
hi, I can't start it on mac m1 pro either.

detects errors in pip dependency installations.

after a series of attempts, I managed to start it, but not in doker

**Comment by odiumuniverse** [comment]
> detects errors in pip dependency installations.
you can replace the line `pip instal ...` in the Makefile with `brew install ...` or `pip3 install ...`.

**Comment by odiumuniverse** [comment]
https://github.com/OpenDevin/OpenDevin/issues/544#issuecomment-2031146928
you can replace the line `pip instal ...` in the Makefile with `brew install ...` or `pip3 install ...`.

**Comment by rbren** [comment]
Changing the title of this one--the issue isn't M1/ARM. It's just the pip reference.

We should be able to make it more robust with `python -m pip`
