### ISSUE TITLE
Error at make build: externally-managed-environment

### ISSUE THREAD

**Issue by butisello** [OpenDevin/OpenDevin#548]
#### Describe the bug

Encounter error when running "make build". Have not proceeded past this point. followe all instructions
#### Setup and configuration
**Current version**:

```commit 79237210f27a0f8ee7cdda00f54993b2eda433a7 (HEAD -> main, origin/main, origin/HEAD)
Author: Alex Bäuerle <alex@a13x.io>
Date:   Mon Apr 1 20:21:45 2024 -0700

    build(add-files-created-for-other-dev-envs-to-gitignore): Add files such as requirements.txt, .python-version, bun.lockb, and yarn.lock so that if anybody uses these systems, they don't accidentally push the files (#519)
```

**My config.toml and environment vars** (be sure to redact API keys):
```Did not reach this stage yet.
```

**My model and agent** (you can see these settings in the UI):
* Model: Did not reach this stage yet
* Agent: same

**Commands I ran to install and run OpenDevin**:
```
   git clone https://github.com/OpenDevin/OpenDevin.git
   cd OpenDevin
   
```

**Steps to Reproduce**:
1. make build
2.
3.

**Logs, error messages, and screenshots**:

#### Additional Context
![makeBuild](https://github.com/OpenDevin/OpenDevin/assets/108600808/716afae9-7cb2-454e-80fb-25d324d86384)

Ubuntu 23.10 (on VirtualBox)
Python 3.11
NodeJS 18.13.0
Docker

**Comment by arywidos** [comment]
Starting frustrated with OpenDevin I'm working so hard to make my pipenv working on my windows env now they changed the installation method with make file helll yeah now is totally lost 100% linux env

**Comment by Kurtisone** [comment]
Same issue for me, Arch Linux Bare-Metal.

Already install before with ` python -m venv venv`

**Comment by rbren** [comment]
Some tips in here, YMMV: https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-every-time-i-use-pip-3

**Comment by dorbanianas** [comment]
This is solved by the migration to poetry! If you still encounter some issues let us know 😁
