### ISSUE TITLE
OpenDevin can't `apt install`

### ISSUE THREAD

**Issue by robshox** [OpenDevin/OpenDevin#550]
I'm getting these kinds of 127 errors

Command `sudo apt update && sudo apt install nodejs npm -y` executed with exit code 127.

ODevin Can write to the file system on my machine but anything got to do with downloading or running packages I believe in the sandbox won't work.
I think this has got to do with the fact I'm on Windows but I thought the backend had it's own Docker setup with Linux.

**Comment by rbren** [comment]
Hmm...this should be solved since we started running Devin as root.

Are there any error messages besides this?

Also--it would be helpful if you could fill out the issue template

**Comment by AmerDinar** [comment]
same issue.

**Comment by enyst** [comment]
@andrescevp @AmerDinar Are you also running on Windows like the OP?

**Comment by andrescevp** [comment]
Using it with Ubuntu

**Comment by andrewparry** [comment]
Maybe this helps? This is the error message I observe with Ubuntu.
```
ACTION:
CmdRunAction(command='sudo apt-get update && sudo apt-get install -y cppcheck', background=False, action=<ActionType.RUN: 'run'>)
13:02:00 - opendevin:ERROR: sandbox.py:227 - Command timed out, killing process...
13:04:00 - opendevin:ERROR: sandbox.py:227 - Command timed out, killing process...

OBSERVATION:
Command: "sudo apt-get update && sudo apt-get install -y cppcheck" timed out. Sending SIGINT to the process: sudo: unable to resolve host opendevin_sandbox: Temporary failure in name resolution
[sudo] password for opendevin: 
sudo: a password is required
```

**Comment by andrewparry** [comment]
Ok updated, I see the command now being run without sudo, but fall into this error, from Opendevin terminal: 
```$ apt update && apt install clang-tidy -y
Reading package lists... 0Reading package lists... 0Reading package lists... 3Reading package lists... Done
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
```

Out of interest
```
parallels@ubuntu-linux-22-04-02-desktop:~/OpenDevin$ ls -l /var/lib/apt/lists
total 183932
...
drwx------ 2 _apt root    12288 Apr  8 15:56 partial
...
```

**Comment by kroggen** [comment]
Same error for me, trying to install `sqlite3`:

```
ACTION:
CmdRunAction(command='apt update && apt install sqlite3 -y', background=False, action=<ActionType.RUN: 'run'>)

OBSERVATION:
Reading package lists... Done
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
```

**Comment by hcossio** [comment]
@andrewparry @kroggen Apparently this is a Docker problem. I'm having some success editing the docker file and adding:

`ARG SSL_KEYSTORE_PASSWORD
USER root
USER 1001`

Looks like:

`FROM ubuntu:22.04
ARG SSL_KEYSTORE_PASSWORD
USER root
# install basic packages
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    git \
    vim \
    nano \
    unzip \
    zip \
    python3 \
    python3-pip \
    python3-venv \
    python3-dev \
    build-essential \
    openssh-server \
    sudo \
    && rm -rf /var/lib/apt/lists/*
USER 1001
RUN service ssh start`

Also, adding in sandbox.py:

`USER_ID = 1001`

before commenting out:

`# if config.get_or_none('SANDBOX_USER_ID') is not None:
#     USER_ID = int(config.get_or_default('SANDBOX_USER_ID', ''))
# elif hasattr(os, 'getuid'):
#     USER_ID = os.getuid()`

**Comment by andrescevp** [comment]
working for me on Ubuntu, thanks guys!

**Comment by R-Dson** [comment]
> @andrewparry @kroggen Apparently this is a Docker problem. I'm having some success editing the docker file and adding:
> 
> ARG SSL_KEYSTORE_PASSWORD USER root USER 1001
> 
> Looks like:
> 
> FROM ubuntu:22.04 ARG SSL_KEYSTORE_PASSWORD USER root '#' install basic packages RUN apt-get update && apt-get install -y curl wget git vim nano unzip zip python3 python3-pip python3-venv python3-dev build-essential openssh-server sudo && rm -rf /var/lib/apt/lists/* USER 1001 RUN service ssh start
> 
> Also, adding in sandbox.py:
> 
> USER_ID = 1001
> 
> before commenting out:
> 
> if config.get_or_none('SANDBOX_USER_ID') is not None: USER_ID = int(config.get_or_default('SANDBOX_USER_ID', '')) elif hasattr(os, 'getuid'): USER_ID = os.getuid()

Thanks, that fixed it for me, but it was exec_box.py and not sandbox.py.

**Comment by rbren** [comment]
I believe this is fixed now that everything is running in a consistent sandbox with RUN_AS_DEVIN=false
