### ISSUE TITLE
Browser Tab does not work

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#552]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/0d9ede41-0b26-476c-8449-f4ee990ce70b)

**Comment by rbren** [comment]
Known issue--it hasn't been implemented. We are working on it here: https://github.com/OpenDevin/OpenDevin/pull/547

Existing issue: https://github.com/OpenDevin/OpenDevin/issues/138
