### ISSUE TITLE
Terminal writes multiple replies at the same time

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#554]
Sometimes the terminal threw multiple reponses at the same time.

**Comment by yufansong** [comment]
Can you provide a way to reliably reproduce this problem? Or do you remember any action will largely trigger this problem?

**Comment by PierrunoYT** [comment]
> Can you provide a way to reliably reproduce this problem? Or do you remember any action will largely trigger this problem?

Hey there. I don't know how to reproduce this issue but I'm pretty sure you will get just while chatting with the Tool.

**Comment by enyst** [comment]
It sounds like this: https://github.com/OpenDevin/OpenDevin/issues/476

**Comment by rbren** [comment]
Duplicate. @PierrunoYT please try and search for existing issues before opening a new one
