### ISSUE TITLE
Option to Delete Projects, Start a new Task and Stop the Output

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#555]
**What problem or use case are you trying to solve?**
Option to Delete Projects, Start a new Task and Stop the Output

**Describe the UX of the solution you'd like**
Buttons for it

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by rbren** [comment]
Going to close this in favor of two similar issues:
* https://github.com/OpenDevin/OpenDevin/issues/470
* https://github.com/OpenDevin/OpenDevin/issues/565
