### ISSUE TITLE
Terminal Output Bug

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#556]
I asked to delete all files and then it started to bug and I got multiple replies at the same time in the terminal

![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/6a66b4d3-9459-4503-b0b9-003b67b37522)
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/0bfbebe9-82c3-480a-935f-2f2855a3e1b8)
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/2ece6748-8cad-4a80-8e33-9579f73956c0)
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/070360f6-8e31-41db-9b64-4c67f66baff0)

**Comment by enyst** [comment]
Wow, that was a fun read! What model were you running?

`tar -czvf backup.tar.gz
rm -rf *` 🤣 

I think what you mean by multiple replies in the same time was reported here: https://github.com/OpenDevin/OpenDevin/issues/476 and a fix is in progress: https://github.com/OpenDevin/OpenDevin/pull/531

**Comment by PierrunoYT** [comment]
> Wow, that was a fun read! What model were you running?
> 
> `tar -czvf backup.tar.gz`
> 
> `rm -rf *` 🤣
> 
> If I understand correctly the report, I think multiple replies in the same time was reported here: #476 and a fix is in progress: #531

I'm running OPENAI because Claude 3 is rate limited I heard.

**Comment by enyst** [comment]
GPT-4 or GPT-3.5?

**Comment by PierrunoYT** [comment]
> GPT-4 or GPT-3.5?

GPT 4

**Comment by enyst** [comment]
Sorry, the LLM was so amazing, it worked so hard to decide to make a backup only to delete it immediately after!

On a serious note, though, perhaps we should clarify somewhere that the agent's abilities are not limited to /workspace. They cannot be too limited if we need it to install software, so it can also "delete all" software. I don't know what to recommend, I'm not sure it was clear that it can destroy more than its previous files? You may want to tell it clearly next time what files to delete. I really don't know how likely it is that it makes a mess, really, GPT-4 is pretty smart. And you can always restore the docker container from the image, anew.

**Comment by rbren** [comment]
Let's close this in favor of https://github.com/OpenDevin/OpenDevin/issues/565

Thanks for the report!
