### ISSUE TITLE
I just want to ask how this video is achieved in README.md

### ISSUE THREAD

**Issue by SmallTeddy** [OpenDevin/OpenDevin#560]

**Comment by enyst** [comment]
Do you mean you're trying the same task and it does something else?
It's possible, depending on what LLM you use, and even the same LLM doesn't always do the exact same thing.

GPT-4, for example, responds the way you see in the video.

**Comment by Sparkier** [comment]
I was confused about it as well. This is what happens if you drag it into the GitHub website directly.

**Comment by Alikberova** [comment]
From mobile I can't see the video

**Comment by Sparkier** [comment]
I can't reproduce that. I can see it on mobile.

**Comment by enyst** [comment]
I can't see it on Apple mobiles/Safari/Bravo, I can see it on Android/Chrome.
