### ISSUE TITLE
Improve frontend readme

### ISSUE THREAD

**Issue by 808vita** [OpenDevin/OpenDevin#563]
[Frontend readme](https://github.com/OpenDevin/OpenDevin/blob/main/frontend/README.md)

- Improve frontend readme file.
- provide some details about all scripts available in package.json
- (maybe?) provide some details about git pre-commit hooks  & configuration( husky and lint-staged)

**Comment by hasnainmakada-99** [comment]
May I work on this one @808vita ?

**Comment by 808vita** [comment]
@hasnainmakada-99 sure go ahead :) .

**Comment by hasnainmakada-99** [comment]
Okay then thanks for assigning it to me @808vita

**Comment by 808vita** [comment]
Please do also explore repo fully and try out the project. @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
Sure @808vita

**Comment by AbhishekJ24** [comment]
@808vita Are there any things, I can work on as of now?

**Comment by 808vita** [comment]
@AbhishekJ24 Please check issues tagged with [good first issue](https://github.com/OpenDevin/OpenDevin/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

Also since you asked here are some suggestions:
- add translation - search for commits relating i18n for context and create a pr providing translations
- auto scroll feature - still an open issue

Please try to avoid duplication of tasks and work.thanks.
