### ISSUE TITLE
Add Agent Comparable to SWE-agent

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#570]
These folks seem to be doing really well on the SWE-bench score!

https://swe-agent.com/

**Comment by xingyaoww** [comment]
I think a good few steps would be:

- [ ] **SWE-Agent requires a persistent docker execution([1](https://github.com/princeton-nlp/SWE-agent/blob/main/sweagent/environment/utils.py#L219-L253), [2](https://github.com/princeton-nlp/SWE-agent/blob/main/sweagent/environment/swe_env.py#L396-L461))**. Our todo for this would be making the docker sandbox keeps all its past states as discussed [here](https://github.com/OpenDevin/OpenDevin/issues/226#issuecomment-2021943071) - I am working on a version based on [`dockerpty`](https://github.com/d11wtq/dockerpty/blob/master/dockerpty/pty.py) but it seems to be pretty tricky to get it working (draft PR #597 - suggestions/PRs are welcomed!)

- [ ] I think the critical component of their success lies in the specific hand-crafted tools (available as commands in bash) like the `search_dir`, `open`, and `edit` tools. A very easy way for us to incorporate these would be: (1) find these tools, and implement as a bash command (this is exactly how they implement it!! - check [this example](https://github.com/princeton-nlp/SWE-agent/blob/67fee842cd984a78b1e94f7be11705c3c351f0b4/config/commands/search.sh#L13-L49)), (2) pack these tools into our sandbox docker image, (3) tweak the prompt [here](https://github.com/OpenDevin/OpenDevin/blob/main/agenthub/codeact_agent/codeact_agent.py#L20-L39) to let the agent knows these are the additional tools they can use. I think (1) and (2) are not hard to do - we probably only need to tweak [our Dockerfile](https://github.com/OpenDevin/OpenDevin/blob/main/opendevin/sandbox/Dockerfile) to achieve this.

![image](https://github.com/OpenDevin/OpenDevin/assets/38853559/c14c88fc-9f9c-4402-927f-387e913b5efa)

- [ ] Besides these tools, they have pretty [sophisticated bash command parsing and block lists](https://github.com/princeton-nlp/SWE-agent/blob/main/sweagent/agent/commands.py#L73-L246). Maybe we can get rid of it to simply our solution at the early stage by directly allowing the agent to interact with the system via bash (similar to [CodeActAgent's pipeline](https://github.com/OpenDevin/OpenDevin/blob/main/agenthub/codeact_agent/codeact_agent.py#L98) - the agent can execute whatever they want, we returns an error message (like [this](https://github.com/OpenDevin/OpenDevin/blob/main/agenthub/codeact_agent/codeact_agent.py#L41-L45)) when it touches on command on the blocklist)

Free free to suggest anything i missed!

**Comment by guneetsk99** [comment]
@rbren @xingyaoww 
Did anyone pick this??

**Comment by neubig** [comment]
Hey @guneetsk99 , not yet! Please feel free to start taking a look at the substeps and claim ones that you like.

**Comment by Sparkier** [comment]
Correction @guneetsk99, I've started with the handcrafted tools [here](https://github.com/OpenDevin/OpenDevin/pull/682).

**Comment by JayQuimby** [comment]
Made a PR for this: #846

**Comment by rbren** [comment]
SWE-agent is merged!

Unclear how it compares to the main SWE-agent--will see if we can get some folks to eval it

**Comment by neubig** [comment]
Hey @rbren, I was looking back at our roadmap, and I don't think this was ready to be closed yet, because we haven't done all of the steps that @xingyaoww mentioned. We still need to test whether our implemented version of the agent gets competitive accuracy on SWE-bench, which we can do after we finish #795

**Comment by neubig** [comment]
This is finished, great job @xingyaoww and @libowen2121 ! https://xwang.dev/blog/2024/opendevin-codeact-1.0-swebench/
