### ISSUE TITLE
Add Nix/NixOS sandbox implementation

### ISSUE THREAD

**Issue by jatinsehrwt** [OpenDevin/OpenDevin#575]
[devenv](https://devenv.sh/) is project based development environment based on nix, which can be utilized for the use case of AI agents, by giving it all the tools required to build an amazing project.

**What problem or use case are you trying to solve?**
Streamlined configuration and management of development environment, it will also help in encapsulating the runtime with the environment. 

**Describe the UX of the solution you'd like**
User should be able to select the environment with help of a configuration file or nix file. Then, a custom development environment is setup or an existing one is used .

**Do you have thoughts on the technical implementation?**
User should have devenv installed and configured for the target repository.  

**Describe alternatives you've considered**
Development with the help of managed and isolated virtual environment, like spinning a custom docker file for every new project, but it becomes tedious to reinstall/reuse docker files. 
Also, developing on docker is very subjective in nature as they are primarily used to run endlessly, which means they are not meant to store and transfer their state, to overcome this persistent storage can be used with docker but it limits the capabilities of AI agent, as it gets tightly coupled with docker images rather than the development system. 

In my humble opinion docker is very good to deploy stuff, not actively develop.

**Additional context**
Configuring packages, runtime, scripts and environment was so hard, that AI was always stuck at some random step in development figuring out ungodly ways to fix the environment.
The best part about nix ecosystem is that it is only meant for development in *nix system. So no, windows development.

**Comment by rbren** [comment]
We recently made "Sandbox" a generic interface, so we can have multiple sandbox implementations. This would be a neat one!
