### ISSUE TITLE
Add -y to apt install

### ISSUE THREAD

**Issue by wesamdev** [OpenDevin/OpenDevin#577]
**What problem or use case are you trying to solve?**
Add -y to apt install
cause it cause problems when ai try to install apt packges

**Comment by rbren** [comment]
Not much we can do here right now, but we have this related issue, which would give the AI the ability to add a `y` to stdin

https://github.com/OpenDevin/OpenDevin/issues/226

Going to close this in favor of the more interactive sandbox
