### ISSUE TITLE
Help 😓🥲

### ISSUE THREAD

**Issue by AniketRajSingh** [OpenDevin/OpenDevin#580]
FileNotFoundError: [Errno 2] No such file or directory: '/Users/aniketrajsingh/Library/Caches/llama_index/models--BAAI--bge-small-en-v1.5/snapshots/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling/config.json'
make: *** [start-backend] Error 1

Help me out with this.

**Comment by enyst** [comment]
Please see this: https://github.com/OpenDevin/OpenDevin/issues/573

**Comment by CatalinCiocea** [comment]
There is a missing folder 1_Pooling and a missing file config.json . Open the path , make the folder and download the file from here : https://huggingface.co/BAAI/bge-small-en-v1.5/tree/main/1_Pooling . If needed change the name in config.json .
