### ISSUE TITLE
ModuleNotFoundError: No module named 'agenthub'

### ISSUE THREAD

**Issue by jalendarreddym** [OpenDevin/OpenDevin#584]
Describe the bug
When attempting to build and run OpenDevin, the make command is not recognized, and there is a missing module agenthub, resulting in a ModuleNotFoundError.

Setup and configuration
Current version:

My config.toml and environment vars (be sure to redact API keys):

My model and agent (you can see these settings in the UI):

Model:
Agent:
Commands I ran to install and run OpenDevin:

Steps to Reproduce:

Clone the OpenDevin repository.
Attempt to build the project using make build.
Navigate to the opendevin directory and run python main.py.
Logs, error messages, and screenshots:

E:\docker\OpenDevin>make build
'make' is not recognized as an internal or external command,
operable program or batch file.

E:\docker\OpenDevin>cd opendevin

E:\docker\OpenDevin\opendevin>python main.py
Traceback (most recent call last):
  File "E:\docker\OpenDevin\opendevin\main.py", line 6, in <module>
    import agenthub  # noqa F401 (we import this to get the agents registered)
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'agenthub'

Additional Context
It seems that the make command is not available on your system, and the agenthub module is missing. The requirements.txt file is also not present in the project directory.

**Comment by foragerr** [comment]
If you don't have `make` installed... install make. See https://stackoverflow.com/a/32127632/745574

**Comment by JustinLin610** [comment]
try sth like `PYTHONPATH=`pwd` pipenv run python ./opendevin/main.py -d ./workspace -t "create a hello world text file"`

**Comment by enyst** [comment]
You're running on Windows, it's best to use WSL: https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by rbren** [comment]
Looks like folks above covered the options for how to proceed--run WSL, use make, set PYTHONPATH.

We'll work on improving this flow so it's a little more seamless on windows. Thanks for reaching out!

**Comment by suoko** [comment]
I first had this error:
```
"/opt/dev/OpenDevin.new/opendevin/logging.py", line 7, in <module>
    console_formatter = logging.Formatter(
```
so I remove logging.py but now I have this 
`ModuleNotFoundError: No module named 'agenthub'`

and can't find a way to solve it
If I run: 
`PYTHONPATH=pwd pipenv run python ./opendevin/main.py -d ./workspace -t "create a hello world text file"
`
I get the same error

On Ubuntu 14.04, not WSL

**Comment by rbren** [comment]
@suoko I believe this is fixed in main
