### ISSUE TITLE
Windows 11 Pro WSL2 - Error when running 'make run'

### ISSUE THREAD

**Issue by androidworkz** [OpenDevin/OpenDevin#587]
#### Describe the bug
After running 'make build' and 'make setup-config' successfully, I ran 'make run' and received this error

(base) oldsk00l@asus-4070:~/OpenDevin$ make run
Running the app...
rm: cannot remove 'logs/pipe': No such file or directory
make: *** [Makefile:34: run] Error 1

#### Setup and configuration
**Current version**:

```bash
 (HEAD -> main, origin/main, origin/HEAD)
Author: Robert Brennan <accounts@rbren.io>
Date:   Tue Apr 2 10:02:09 2024 -0400

    Update intro message (#569)
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_API_KEY="xxx"
LLM_MODEL=""
WORKSPACE_DIR="~/workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
make build
make setup-config
make run
```

**Steps to Reproduce**:
See above

**Logs, error messages, and screenshots**:

**Comment by androidworkz** [comment]
I got it to run for a moment by commenting out the @rm and @mkfifo lines in the makefile but got additional errors

**Comment by SiboVG** [comment]
Same issue for me, running on macOS 14.3.1 on an Apple Silicon M1. I got rid of the error by manually creating the logs dir in the OpenDev root dir.

**Comment by PierrunoYT** [comment]
Same here on Windows 11 Pro using WSL.

**Comment by PierrunoYT** [comment]
pierre@Pierruno:/mnt/c/Users/pierr/opendevin$ make run
Running the app...
rm: cannot remove 'logs/pipe': No such file or directory
make: *** [Makefile:34: run] Error 1
pierre@Pierruno:/mnt/c/Users/pierr/opendevin$ make run
Running the app...
rm: cannot remove 'logs/pipe': No such file or directory
make: *** [Makefile:34: run] Error 1
pierre@Pierruno:/mnt/c/Users/pierr/opendevin$

**Comment by enyst** [comment]
There's a PR to fix this: https://github.com/OpenDevin/OpenDevin/pull/579

As @SiboVG said, the easiest way to make it go away is to create a logs dir and inside it a directory named pipe. Or take a look at the PR, and remove from makefile the two lines that start with "rm ".

**Comment by enyst** [comment]
> Maybe add a check to see if the log directories exist before trying to remove them in the makefile?

Yes, that's what the PR does: https://github.com/OpenDevin/OpenDevin/pull/579

**Comment by marcin-jozwikowski** [comment]
Can confirm, @tonyw54 solution works. Did that myself as well.

```
mkdir logs -p
touch logs/pipe
```

**Comment by rbren** [comment]
This should be fixed on main
