### ISSUE TITLE
No logs folder when building OpenDevin

### ISSUE THREAD

**Issue by dproworld** [OpenDevin/OpenDevin#589]
#### Describe the bug
`make run` fails because it tries to `rm logs/pipe` when folder `logs` doesn't exist

#### Setup and configuration
**Current version**:
```bash
commit 22a9a28e46f86488d8756db3c074ee35403ba740 (HEAD -> main, origin/main, origin/HEAD)
Author: Robert Brennan <accounts@rbren.io>
Date:   Tue Apr 2 10:02:09 2024 -0400

    Update intro message (#569)
```

Default environment, config is irrelevant 

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
make build
make run
```

**Steps to Reproduce**:
mentioned above, just cloning repo, make build and make run

**Solution**:
add a logs folder

**Comment by dproworld** [comment]
And a check for the existence of file logs/pipe in makefile should also be added

**Comment by enyst** [comment]
Thank you for the report, you're right, and there's a PR to fix this https://github.com/OpenDevin/OpenDevin/pull/579

**Comment by rbren** [comment]
This should be solved now
