### ISSUE TITLE
How to enable users who cannot access openai to use opendevin with the help of a proxy

### ISSUE THREAD

**Issue by Wenqiaog** [OpenDevin/OpenDevin#590]
In some areas, it is not possible to directly access the official website of openai. I need to use a proxy to access it. I hope the author can configure the local proxy function. The common protocol is socks5h/http; for example, the default local protocol of v2**y and ss* is socks5h; and The default local protocol for cl**h is http

**Comment by rbren** [comment]
@Wenqiaog I think this is out of scope for OpenDevin, but could be something we document. If you come across a good solution let us know.

You might check out LM Studio or LocalAI.

You can also look at LiteLLM to see if they offer anything here--that's what we use under the hood.
