### ISSUE TITLE
No installation guides

### ISSUE THREAD

**Issue by ArFiction** [OpenDevin/OpenDevin#595]
The installation guides that were previously here yesterday have disappeared, when can we expect for them to return?

Thanks

**Comment by PierrunoYT** [comment]
> The installation guides that were previously here yesterday have disappeared, when can we expect for them to return?
> 
> Thanks

They are still there. They updated the guides.

**Comment by skilbjo** [comment]
running macOS, installed python3 with homebrew

```
(OpenDevin) @Johns-MacBook-Air:OpenDevin $ make build
Building project...
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/opendevin/sandbox
Installing Python dependencies...
make: pip: No such file or directory
make: *** [build] Error 1
OpenDevin $ which pip
OpenDevin $ which pip3
/opt/homebrew/bin/pip3
```

the `make build` command is:

```
build:
	...
	@echo "Installing Python dependencies..."
	@pip install pipenv
	@pipenv install -v
	...
```

even changing it to `pip3` doesn't work, nor does creating a virtual environment via `venv && source .venv/bin/activate`, you'll get an error about overriding system python

so not really turnkey, am not a python developer ...

**Comment by PierrunoYT** [comment]
> running macOS, installed python3 with homebrew
> 
> ```
> OpenDevin $ make build
> Building project...
> Pulling Docker image...
> Using default tag: latest
> latest: Pulling from opendevin/sandbox
> Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
> Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
> ghcr.io/opendevin/sandbox:latest
> 
> What's Next?
>   View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/opendevin/sandbox
> Installing Python dependencies...
> make: pip: No such file or directory
> make: *** [build] Error 1
> OpenDevin $ which pip
> OpenDevin $ which pip3
> /opt/homebrew/bin/pip3
> ```
> 
> the `make build` command is:
> 
> ```
> build:
> 	...
> 	@echo "Installing Python dependencies..."
> 	@pip install pipenv
> 	@pipenv install -v
> 	...
> ```
> 
> even changing it to `pip3` doesn't work, nor does creating a virtual environment via `venv && source .venv/bin/activate`, you'll get an error about overriding system python
> 
> so not really turnkey, am not a python developer ...

Check https://github.com/OpenDevin/OpenDevin/issues/587

**Comment by rbren** [comment]
We're working on the `pip` issues.

Pierre is right that the new workflow is to use `make`. We're still working on making this better.
