### ISSUE TITLE
`logs/pipe` not found in `make run`

### ISSUE THREAD

**Issue by jojeyh** [OpenDevin/OpenDevin#602]
#### Describe the bug
Makefile first removes `logs/pipe` in call to `make run` but does not exists and exits without running

#### Setup and configuration
**Current version**:

```bash
commit 22a9a28e46f86488d8756db3c074ee35403ba740 (HEAD -> main, upstream/main, origin/main, origin/HEAD, files-endpoints)
Author: Robert Brennan <accounts@rbren.io>
Date:   Tue Apr 2 10:02:09 2024 -0400

    Update intro message (#569)

```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_API_KEY="..."
LLM_MODEL=""
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model: default
* Agent: MonologueAgent

**Commands I ran to install and run OpenDevin**:
```
make build
make setup-config
make run
```

**Steps to Reproduce**:
1. Clone repo 
2. Run above commands

**Logs, error messages, and screenshots**:
Running the app...
rm: cannot remove 'logs/pipe': No such file or directory
make: *** [Makefile:34: run] Error 1

**Comment by androidworkz** [comment]
There are at least 2 other reports for this bug and they have added a fix

**Comment by jojeyh** [comment]
I see them, thx closing
