### ISSUE TITLE
logs/pipe Error

### ISSUE THREAD

**Issue by stratte89** [OpenDevin/OpenDevin#608]
after running make run i get this error, does anyone know how to fix, im on ubuntu?

Running the app...
rm: das Entfernen von 'logs/pipe' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
make: *** [Makefile:34: run] Fehler 1

**Comment by rbren** [comment]
A fix for this was merged 20m ago. It should be OK if you pull latest
