### ISSUE TITLE
90%PROBLEM

### ISSUE THREAD

**Issue by Claudioappassionato** [OpenDevin/OpenDevin#610]
**Alternatives to Consider**
Downloading the program, lots of people download it. but 90% can't make it work. Do you want some advice on how to succeed, considering that most users know nothing about coding? do a one-time installation for windows MSI or EXE style with everything inside. Then you will be successful

**Comment by rbren** [comment]
We're working on making installation better. But we will be targeting Unix for the time being. Docker and/or WSL is probably our best bet for Windows support.
