### ISSUE TITLE
how to run OpenDevin with Claude 2 or Claude 3?

### ISSUE THREAD

**Issue by code2graph** [OpenDevin/OpenDevin#611]
how to setup OpenDevin with Claude 2 or Claude 3?

**Comment by rbren** [comment]
@code2graph we don't have model-specific instructions, but I'm modifying things here to make it easier to set up: https://github.com/OpenDevin/OpenDevin/pull/614

**Comment by DGdev91** [comment]
set LLM_MODEL to claude-2 or claude-3, then export ANTHROPIC_API_KEY = "your_key" and run.

OpenDevin uses LiteLLM, you basically have to follow the instruction there for each model
https://docs.litellm.ai/docs/providers/anthropic

**Comment by neubig** [comment]
Should be fixed. https://github.com/OpenDevin/OpenDevin/pull/614
