### ISSUE TITLE
Document difference between different agents (and maybe expose descriptions in UI)

### ISSUE THREAD

**Issue by shaggy2626** [OpenDevin/OpenDevin#628]
I've come across multiple agent options in the configuration that I'm not entirely familiar with. Specifically, the options are MonologueAgent, CodeActAgent, and PlannerAgent. I've attached a screenshot for reference.

Could you please provide some details on the differences between these agents and the intended use cases for each? Which one do I select? 
![image](https://github.com/OpenDevin/OpenDevin/assets/120447538/5f0fd79d-dd1f-41c3-9ec5-b0f8620c8c0b)

**Comment by yimothysu** [comment]
Hi @shaggy2626, use `MonologueAgent` for now. We'll need to update the documentation for this.

**Comment by shaggy2626** [comment]
Got it, and other question I had was which temp and top p settings are used by default? Is there  a way to change it?

**Comment by yimothysu** [comment]
There's no way to change it in the UI currently. For a quick workaround, you can pass temperature and top p into the `completion` function of `agenthub/monologue_agent/agent.py` for now:

Change line 164
```py
resp = self.llm.completion(messages=messages)
```
to
```py
resp = self.llm.completion(messages=messages, temperature=..., top_p=...)
```

**Comment by shaggy2626** [comment]
> Hi @shaggy2626, use `MonologueAgent` for now. We'll need to update the documentation for this.

Should I still be using this as the default? MonologueAgent

**Comment by yimothysu** [comment]
@shaggy2626 I recommend defaulting to CodeActAgent now
