### ISSUE TITLE
Set up Python Linting/TypeChecking/CI

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#63]
Currently we don't have any linting or typechecking in CI. It'd be good to add this. My suggestions are:

* Linting: [Ruff](https://github.com/astral-sh/ruff)
* Typechecking: [MyPy](https://mypy-lang.org/)

Assuming this, we should:

* [ ] add linting
* [ ] add typechecking
* [ ] add [CI](https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration) to check the linting/typechecking
* [ ] add git [pre-commit hook](https://pre-commit.com/) to ensure that these are run on commit

**Comment by neubig** [comment]
Yeah, sounds great. We may also want to consider doing something like
`config/python` or `dev_config/python`
just to limit the number of top-level directories.

**Comment by yimothysu** [comment]
It might be simpler then to move all the Python code into a shared `backend/` directory. @rbren what do you think?

**Comment by mahithsc** [comment]
I like the second model of moving all the python code to one shared backend folder. Dow the road when we need to create the socket interface between he server and the agent this structure would be more beneficial as well.

**Comment by neubig** [comment]
I think that since we're probably going to have lots of Python backend code (as opposed to the frontend code, which can be somewhat minimal), it might be better to not restrict the Python code to go under the `backend` directory.

**Comment by yimothysu** [comment]
Closing because https://github.com/OpenDevin/OpenDevin/pull/69 is merged.
