### ISSUE TITLE
Make `make` fail with a good error message when npm or python have incompatible versions

### ISSUE THREAD

**Issue by abhawan888** [OpenDevin/OpenDevin#634]
**Summary**

Windows 11 WSL2 Ubuntu 20.04

System:~/OpenDevin$ make build
Building project...
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/opendevin/sandbox
Installing Python dependencies...
make: python: No such file or directory
make: *** [Makefile:17: build] Error 127

**Comment by yimothysu** [comment]
Is Python in your `PATH`? What is the output of `python --version`?

**Comment by abhawan888** [comment]
@dorbanianas Thanks! I have a fresh install and everything is the latest version. I'll keep an eye out for the merge. Really excited to give this a try.

**Comment by Jaitwo** [comment]
im new using ubuntu how can i use the command make to install OpenDevin? i don't quite understand what to do or how command "make" works

**Comment by dorbanianas** [comment]
@Jaitwo you can simply follow the steps in the readme and how `make` works just you define a file named `Makefile` where you give some shortcuts like build, install... Where the users of the project can run a lot of these commands using just the shortcut that you have defined, this is my definition of course to make it simple for you, Now how you can use it? just you need to go to the linux terminal and type `make build` to build the venv and install the dependencies, after that use `make setup-config` to setup your model config and finally `make run` to run the full project, you may encounter so bugs but we are working to fix them asap.

**Comment by rahulraikwar00** [comment]
Just make these changes in your Makefile. this will fix the issue

- Replaced python with python3 to specify the Python 3 executable.
- Changed pip3 to pip because it's invoked using python3 -m pip.

@python3 -m pip install pipenv
@python3 -m pipenv install -v

**Comment by Ido108** [comment]
edit "makefile" replace all "python" with "python3"

**Comment by dracoix** [comment]
> edit "makefile" replace all "python" with "python3"

make build is so far working, thank you.

**Comment by dracoix** [comment]
okay so I also had to install npm in the environment itself

**Comment by dorbanianas** [comment]
@rbren @neubig what do you think about including the installation of python3.11 and npm in the make build?

**Comment by rbren** [comment]
installing a full programming language is kind of aggressive for `make` 😅 

IMO `make` shouldn't have system-wide side-effects, as much as possible

**Comment by rbren** [comment]
Can we fail the `make` with a good error message if npm or python isn't installed or on an old version?

**Comment by xcodebuild** [comment]
Most of the compatibility work is done in the Makefile at https://github.com/OpenDevin/OpenDevin/pull/650

Regarding the node and npm version inspection, I believe it has been implemented in https://github.com/OpenDevin/OpenDevin/pull/659

**Comment by dorbanianas** [comment]
@rbren we can run the process in the background and show some good looking messages and wait for it until it finishes

**Comment by dorbanianas** [comment]
But I guess for now maybe it's not necessary because it will add more complexity and edge cases to handle that we are not supposed to think of right now

**Comment by dorbanianas** [comment]
now we handle check python and npm and docker and for the pnpm if npm is installed the pnpm get enabled also added some styling 😅, more details here #634
