### ISSUE TITLE
Cannot run docker image and send message to agent

### ISSUE THREAD

**Issue by alexsiu398** [OpenDevin/OpenDevin#639]
I ran the project on linux. When on docker desktop I ran ghcr.io/opendevin/sandbox image, it exited immediately. I ran "make run" but cannot send message to agent. Terminal returns "please check docker is running using docker ps". docker ps does not return any entry.

**Comment by rbren** [comment]
@alexsiu398 we'll need more information here--can you open a new issue and fill out the bug template?
