### ISSUE TITLE
I don't understand, does this use openai API or no? does it need cpu or what I Don't understand, please add to readme or docs

### ISSUE THREAD

**Issue by ahmedomar365** [OpenDevin/OpenDevin#642]
I don't understand, does this use openai API or no? does it need cpu or what I Don't understand, please add to readme or docs

**Comment by neubig** [comment]
Thanks for the feedback! @dorbanianas , would you be interested in helping make the README more clear wrt this?

**Comment by neubig** [comment]
OpenDevin supports multiple LLMs, but we should make this clearer in the README. I have opened an issue for this!
https://github.com/OpenDevin/OpenDevin/issues/644

**Comment by dorbanianas** [comment]
@neubig yes I can take care of this 😉
