### ISSUE TITLE
can't start docker service . 

### ISSUE THREAD

**Issue by shanghailiwei** [OpenDevin/OpenDevin#643]
(OpenDevin) (base) [root@localhost OpenDevin]# python opendevin/sandbox/sandbox.py  -d workspace
Traceback (most recent call last):
  File "/home/liwei/OpenDevin/opendevin/sandbox/sandbox.py", line 13, in <module>
    from opendevin import config
ModuleNotFoundError: No module named 'opendevin'
(OpenDevin) (base) [root@localhost OpenDevin]#

**Comment by shanghailiwei** [comment]
(OpenDevin) (base) root@LiWei-MacBook-Pro OpenDevin # python opendevin/sandbox/sandbox.py.2 -d workspace
Restarting Docker container sandbox-4510ffa2-001a-4086-9288-6f001946d73d
Stopping and removing Docker container sandbox-4510ffa2-001a-4086-9288-6f001946d73d
Failed to initialize Docker client: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Failed to stop container: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Failed to start Docker container: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

**Comment by foragerr** [comment]
Would you mind filling out the issue template?
What are you trying to do, it's not clear why you're running sandbox.py directly.

If you're trying to use OpenDevin, could you try following the instructions in README.md?

**Comment by rbren** [comment]
@shanghailiwei if the README doesn't work for you, can you file a new issue and fill out the bug template?
