### ISSUE TITLE
Add more information about how to run with different LMs to the README

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#644]
**Additional context**

OpenDevin supports mulltiple LLMs through [litellm](https://litellm.ai/), so information about supported LLMs can be found [here](https://litellm.vercel.app/docs/providers). The LLM to use is set during the `make setup-config` phase or through `config.toml`.

**What problem or use case are you trying to solve?**

Currently, it is not clear that OpenDevin supports multiple LMs in the README.

**Describe the UX of the solution you'd like**

A clear description that:
1. OpenDevin supports various LMs
2. How to set the LM you want to use

**Comment by neubig** [comment]
@dorbanianas will take a look at this!

**Comment by dorbanianas** [comment]
@neubig thanks! I'll submit the PR as soon as I finish some stuff

**Comment by dorbanianas** [comment]
@rbren what do you think about it? have you any suggestions

**Comment by neubig** [comment]
Solved by #614
