### ISSUE TITLE
Error while using Gemini

### ISSUE THREAD

**Issue by timucindusunur** [OpenDevin/OpenDevin#653]
root@DESKTOP-1TC1K9D:/home/timuc/OpenDevin# make run
Running the app...
make[1]: Entering directory '/home/timuc/OpenDevin'
Starting backend...
make[1]: Entering directory '/home/timuc/OpenDevin'
Starting frontend...

> opendevin-frontend@0.1.0 start
> vite

  VITE v5.2.7  ready in 658 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
INFO:     Started server process [12950]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     127.0.0.1:47280 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:47296 - "GET /litellm-agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:47306 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:47318 - "GET /litellm-agents HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 47328) - "WebSocket /ws" [accepted]
INFO:     connection open
Workspace directory ./workspace does not exist. Creating it...

==============
STEP 0

PLAN:
bana mali danışmanlık firması için web sitesi tasarla ve çalıştır. Detaylı ve kapsamlı bir çalışma olsun.

INFO:
HINT:
You're not currently working on any tasks. Your next action MUST be to mark a task as in_progress.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

what is the reason of this  ?

**Comment by timucindusunur** [comment]
LLM_MODEL="gemini/gemini-pro"
LLM_API_KEY="A...."
WORKSPACE_DIR="./workspace"

**Comment by jpshackelford** [comment]
I am working through this one as well. It looked to me like litellm might be using the vertex api instead of the developer api for gemini. I think the API keys may be different (https://cloud.google.com/vertex-ai/generative-ai/docs/migrate/migrate-google-ai#google-ai).

Actively trying to figure out what is going on now.

I also am wondering what the right value in LLM_MODEL is and whether it should match 1:1 with the value in the UI settings or whether there is a different convention in play.

**Comment by jpshackelford** [comment]
Here is a bit more that leads me to this conclusion. 
```
OBSERVATION:
VertexAIException - 403 Vertex AI API has not been used in project <<PROJECT ID>> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/aiplatform.googleapis.com/overview?project= <<PROJECT ID>>  then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [links {
  description: "Google developers console API activation"
  url: "https://console.developers.google.com/apis/api/aiplatform.googleapis.com/overview?project=<<PROJECT ID>> "
}
, reason: "SERVICE_DISABLED"
domain: "googleapis.com"
metadata {
  key: "service"
  value: "aiplatform.googleapis.com"
}
metadata {
  key: "consumer"
  value: "projects/<<PROJECT ID>>"
}
]
```

I was also prompted to use the google cloud client to set up credentials. This shouldn't be necessary with an API key using the developer APIs. I've coded against the before without having to do so. 

```
OpenDevin/.env/lib/python3.12/site-packages/litellm/main.py", line 1677, in completion
    model_response = vertex_ai.completion(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/boxy-01/code-archive/viewing/OpenDevin/.env/lib/python3.12/site-packages/litellm/llms/vertex_ai.py", line 676, in completion
    raise VertexAIError(status_code=500, message=str(e))
litellm.llms.vertex_ai.VertexAIError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
```

So somewhere litellm thinks we should be using vertex APIs and I am not sure why. I was just using litellm for another project yesterday in which it was correctly authenticating with an API token against the developer apis.

**Comment by jpshackelford** [comment]
I have now verified but not pinpointed the issue.

Config.toml correctly has:

```
LLM_MODEL="gemini/gemini-pro"
```

Which matches the correct value for developer the api (`gemini/gemini-pro`)in the (llmlite docs)[https://docs.litellm.ai/docs/providers/gemini]. Notice that `llmlite` also supports Vertex with the key:  `gemini-pro`

AI Studio Params
![gemini-ai-studio](https://github.com/OpenDevin/OpenDevin/assets/13136/fd8435ab-f097-4130-8a19-6cb3159c0b94)

Vertex Params
![gemini-vertex](https://github.com/OpenDevin/OpenDevin/assets/13136/382460af-825a-475c-b3de-ddf61e2b71a2)

Despite having the correct values set in the configuration file and UI cycling servers, even rebuilding, I still see the errors referring to Vertex.

**Comment by enyst** [comment]
@timucindusunur 
> Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

> what is the reason of this ?

This is only the start of an error, the next lines should say what error it is.

**Comment by enyst** [comment]
@jpshackelford Weird, and I think you're right, today/yesterday I've seen other issues in various places with some subset of LLMs via LiteLLM, but I can't find now the references.

Gemini via LiteLLM should work - and has worked - with google generativeai IIRC.

**Comment by dorbanianas** [comment]
I guess the issue was related to some dependencies currently, everything works well with Gemini without the need for vertex here's my `config.toml` file:

```
LLM_MODEL="gemini/gemini-pro"
LLM_API_KEY="<YOUR-API-KEY>"
LLM_EMBEDDING_MODEL=""
WORKSPACE_DIR="./workspace"
