### ISSUE TITLE
Bugs in build and setup

### ISSUE THREAD

**Issue by boyuanzheng010** [OpenDevin/OpenDevin#658]
#### Describe the bug

I am running `make build` to set up the environment.

#### Setup and configuration
**Current version**: d397a200bfa6f5706ab2ff615eed99bddfb46c4f

**My config.toml and environment vars** (be sure to redact API keys):
```toml
```

**Commands I ran to install and run OpenDevin**:
```
```

**Steps to Reproduce**:
1. make build

**Logs, error messages, and screenshots**:
I have the following error report:
[pipenv.exceptions.InstallError]: ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement nvidia-nvjitlink-cu12==12.4.99 (from versions: 0.0.1.dev5)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for nvidia-nvjitlink-cu12==12.4.99
ERROR: Couldn't install package: {}
 Package installation failed...
/Users/zheng.2372/anaconda3/envs/OpenDevin/lib/python3.11/subprocess.py:1127: ResourceWarning: subprocess 27957 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 encoding='utf-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=7 encoding='utf-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
make: *** [build] Error 1

While building the environment, there are also errors during install: 
Ignoring nvidia-cuda-nvrtc-cu12: markers 'platform_system == "Linux" and platform_machine == "x86_64"' don't match your environment

Ignoring nvidia-cuda-runtime-cu12: markers 'platform_system == "Linux" and platform_machine == "x86_64"' don't match your environment

Ignoring nvidia-cudnn-cu12: markers 'platform_system == "Linux" and platform_machine == "x86_64"' don't match your environment

Ignoring nvidia-cufft-cu12: markers 'platform_system == "Linux" and platform_machine == "x86_64"' don't match your environment

Ignoring nvidia-curand-cu12: markers 'platform_system == "Linux" and platform_machine == "x86_64"' don't match your environment

Ignoring nvidia-cusolver-cu12: markers 'platform_system == "Linux" and platform_machine == "x86_64"' don't match your environment

Ignoring nvidia-cusparse-cu12: markers 'platform_system == "Linux" and platform_machine == "x86_64"' don't match your environment

Ignoring nvidia-nccl-cu12: markers 'platform_system == "Linux" and platform_machine == "x86_64"' don't match your environment

Ignoring nvidia-nvtx-cu12: markers 'platform_system == "Linux" and platform_machine == "x86_64"' don't match your environment

**Comment by foragerr** [comment]
Are you on a M1 mac?

**Comment by boyuanzheng010** [comment]
@foragerr Yes, I have tested both on M1 and M2 mac.

**Comment by mahesh12393** [comment]
Hi @boyuanzheng010 , I'm still facing this issue. Have you got a solution. I'm also on M1 mac

**Comment by yufansong** [comment]
Does it still exist on the latest main? Close it now. Feel free to reopen it if it still exist on latest main.
