### ISSUE TITLE
Requirements.txt file is missing

### ISSUE THREAD

**Issue by Vijender944** [OpenDevin/OpenDevin#661]
The requirements.txt file is missing and when i try running the backend by the ovicorn command, it keep on saying that : 
ModuleNotFoundError: No module named 'opendevin'

**Comment by foragerr** [comment]
The repo does not use pip, rather it uses pipfile (soon to be converted to poetry).
This means there is a `[pipfile](https://github.com/OpenDevin/OpenDevin/blob/main/Pipfile)` rather than a `requirements.txt`.

Please follow the installation steps in Readme. 
https://github.com/OpenDevin/OpenDevin?tab=readme-ov-file#-get-started

**Comment by Dr-Mohamed-Elkholy** [comment]
I did these steps then got the requirement.txt file and the installation :

python -m pip install pipenv  # Install Pipenv if you haven't already
python -m pipenv install -v  # Install dependencies specified in Pipfile
python -m pipenv shell  # Activate the virtual environment created by Pipenv
uvicorn opendevin.server.listen:app --port 3000  # Start the backend server


Then generating the requirement.txt
python -m pip freeze > requirements.txt  # Generate requirements.txt from current environment
python -m pip install -r requirements.txt  # Install dependencies from requirements.txt

**Comment by neubig** [comment]
Yes, as @foragerr pointed out I believe if you follow the README for installation it should install the packages appropriately. I'll close this issue for now, but if you cannot get it to work, please feel free to re-open with more detail on the exact installation steps you ran and where you encountered a problem.

**Comment by Vijender944** [comment]
> The repo does not use pip, rather it uses pipfile (soon to be converted to poetry). This means there is a [`pipfile`](https://github.com/OpenDevin/OpenDevin/blob/main/Pipfile) rather than a `requirements.txt`.
> 
> Please follow the installation steps in Readme. https://github.com/OpenDevin/OpenDevin?tab=readme-ov-file#-get-started

Thanks
