### ISSUE TITLE
System running issue

### ISSUE THREAD

**Issue by TUTULEMAN** [OpenDevin/OpenDevin#663]
#### System running issue
 I have imported everything and was able to get the front end running. However, whenever I try to type something into the text bar, I would return a series of error.

#### Setup and configuration
**Current version**:

```bash 
commit 4882cb6a66e856106930f0ce5c5849cbe135e09f (HEAD -> main, origin/main, origin/HEAD)
Author: Robert Brennan <accounts@rbren.io>
Date:   Sat Mar 30 14:11:58 2024 -0400

    Update README.md (#403)
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
_PS C:\Users\max\opendevin> set OPEN_API_KEY="i_inserted_my_api_key"
PS C:\Users\max\opendevin> set LLM_BASE_URL="https://localhost:3001/"
```

**My model and agent** (you can see these settings in the UI):
* Model: "gpt-3.5-turbo"
* Agent: OpenAI

**Steps to Reproduce**:
```gitclone -> cd opendevin -> export OPENAIKEY + WORKSPACE_DIR -> m pip install -r requirements.txt -> uvicorn.opendevin.server..listen:app -- port 3000-> cd frontend ->npm install -> npm start --port 3001
```
**Commands I ran to install and run OpenDevin**
**Back End
_PS C:\Users\max\opendevin> set OPEN_API_KEY="i_inserted_my_api_key"
PS C:\Users\max\opendevin> set LLM_BASE_URL="https://localhost:3001/"
PS C:\Users\max\opendevin> set LLM_MODEL="gpt-4-32k-0613"
PS C:\Users\max\opendevin> python -m pipenv install -v
Installing dependencies from Pipfile.lock (5563c0)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
PS C:\Users\max\opendevin> python -m pipenv shell
Launching subshell in virtual environment...
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\max\OpenDevin> uvicorn opendevin.server.listen:app --port 3000
INFO: Started server process [28312]
INFO: Waiting for application startup.
INFO: Application startup complete.
INFO: Uvicorn running on http://127.0.0.1:3000/ (Press CTRL+C to quit)_

Front End
_Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\max> cd opendevin
PS C:\Users\max\opendevin> cd frontend
PS C:\Users\max\opendevin\frontend> npm install

opendevin-frontend@0.1.0 prepare
cd .. && husky install frontend/.husky

husky - Git hooks installed

up to date, audited 826 packages in 3s

209 packages are looking for funding
run npm fund for details

found 0 vulnerabilities
PS C:\Users\max\opendevin\frontend> npm start

opendevin-frontend@0.1.0 start
vite

Port 3001 is in use, trying another one...
Port 3002 is in use, trying another one...

VITE v5.1.6 ready in 1330 ms

➜ Local: http://localhost:3003/
➜ Network: use --host to expose
➜ press h + enter to show help_
Results

_During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\max\OpenDevin\opendevin\controller\agent_controller.py", line 88, in step
action = self.agent.step(self.state)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\max\OpenDevin\agenthub\langchains_agent\langchains_agent.py", line 124, in step
self._add_event(prev_action.to_dict())
File "C:\Users\max\OpenDevin\agenthub\langchains_agent\langchains_agent.py", line 74, in _add_event
self.monologue.condense(self.llm)
File "C:\Users\max\OpenDevin\agenthub\langchains_agent\utils\monologue.py", line 35, in condense
raise RuntimeError(f"Error condensing thoughts: {e}")
RuntimeError: Error condensing thoughts: OpenAIException - Traceback (most recent call last):
File "C:\Users\max.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\llms\openai.py", line 376, in completion
raise e
File "C:\Users\max.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\llms\openai.py", line 312, in completion
openai_client = openai(
^^^^^^^
File "C:\Users\max.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\openai_client.py", line 98, in init
raise openaiError(
openai.openaiError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable**:

**Comment by stratte89** [comment]
hey try to use this format

LLM_API_KEY="OpenAI API KEs"
LLM_MODEL="openai model name"
WORKSPACE_DIR="./workspace"

**Comment by neubig** [comment]
I believe that if you set `config.toml` to the format suggested by @stratte89 that should fix your issue, so I'll close this. But please re-open the issue with more details about the error you're getting if that does not work!

**Comment by TUTULEMAN** [comment]
Hi, I've done it but its still not working on my end. This showed up in the backend instead:
`Error! Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
Failed to stop container: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
Error creating controller.`

**Comment by TUTULEMAN** [comment]
okok
