### ISSUE TITLE
System running issue. Potential dir problem.

### ISSUE THREAD

**Issue by TUTULEMAN** [OpenDevin/OpenDevin#670]
#### System running issue
this is a continued thread from a previous problem on workspace_dir. I tried changing the format according to *stratte89* (LLM_API_KEY="OpenAI API Key"
LLM_MODEL="openai model name"
WORKSPACE_DIR="./workspace") but it still returned an error.

#### Setup and configuration
**Current version**:

```bash 
commit 4882cb6a66e856106930f0ce5c5849cbe135e09f (HEAD -> main, origin/main, origin/HEAD)
Author: Robert Brennan <accounts@rbren.io>
Date:   Sat Mar 30 14:11:58 2024 -0400

    Update README.md (#403)
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_API_KEY="myopen ai api key"
LLM_MODEL="gpt-3.5-turbo"
WORKSPACE_DIR="./workspace"="https://localhost:3001/"
```

**My model and agent** (you can see these settings in the UI):
* Model: "gpt-3.5-turbo"
* Agent: OpenAI

**Commands I ran to install and run OpenDevin**
**Back End
_PS C:\Users\max\opendevin> set LLM_API_KEY="i_inserted_my_api_key"
PS C:\Users\max\opendevin> set WORKSPACE_DIR="https://localhost:3001/"
PS C:\Users\max\opendevin> set LLM_MODEL="gpt-3.5-turbo"
PS C:\Users\max\opendevin> python -m pipenv install -v
Installing dependencies from Pipfile.lock (5563c0)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
PS C:\Users\max\opendevin> python -m pipenv shell
Launching subshell in virtual environment...
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\max\OpenDevin> uvicorn opendevin.server.listen:app --port 3000
INFO: Started server process [28312]
INFO: Waiting for application startup.
INFO: Application startup complete.
INFO: Uvicorn running on http://127.0.0.1:3000/ (Press CTRL+C to quit)_
Error! Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.') Failed to stop container: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.') Error creating controller.

**Comment by foragerr** [comment]
Previous issue for context: https://github.com/OpenDevin/OpenDevin/issues/663

**Comment by foragerr** [comment]
Do you have docker running? see also: https://github.com/OpenDevin/OpenDevin/issues/155

**Comment by enyst** [comment]
@TUTULEMAN thank you for the details. If docker isn't running on your machine, you need to start it.

Also, the commit from  March 30th means your repo is outdated by now, there've been some fixes meanwhile.

**Comment by TUTULEMAN** [comment]
@enyst how can I get the system back to date? Also, thank you @foragerr I should have turned it on.

**Comment by enyst** [comment]
In the project directory, git pull.
Then run as the readme says: make build.

**Comment by TUTULEMAN** [comment]
what if I had run it and this is what it said:
make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ make build
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by rbren** [comment]
@TUTULEMAN you need to run on WSL, not on Windows itself. Please see the README for more info

**Comment by TUTULEMAN** [comment]
i did

**Comment by enyst** [comment]
If you don't have make on the system, you can install it. What Linux distribution have you chosen in WSL? Please run the project there, in that distribution. 

Your initial post shows c:\ paths, which shouldn't happen in the Linux subsystem. I think it will be something like /mnt/c/other/directories

**Comment by rbren** [comment]
Looks like this is a windows issue from the logs. Make sure you're running in WSL, and if you're still having trouble feel free to open an new issue
