### ISSUE TITLE
I can't start OpenDevin: ERROR: Failed connection to server. Please ensure the server is reachable at ws://localhost:3002/ws.

### ISSUE THREAD

**Issue by Hanz-Zoe** [OpenDevin/OpenDevin#671]
The bug I am experiencing happens after I install everything I need to run OpenDevin, when I run the program I get this error on the browser ERROR: Failed connection to server. Please ensure the server is reachable at ws://localhost:3002/ws. and I can't use it I don't understand WHY it happens I tried building the program from scratch, I don't know if I have to change de localhost port or if I'm just being stupid and my port is closed.

#### Setup and configuration
**Current version**:
commit 310cd7017d669c5414f29fcb79fc2b8e6e51c552 (HEAD -> main)
Author: Robert Brennan <accounts@rbren.io>
Date:   Wed Apr 3 10:22:08 2024 -0400

    Add link to LiteLLM to make-setup (#614)
    
    * Update Makefile
    
    * fix tab
    
    * add note to readme
```bash
```

**My config.toml and environment vars** (be sure to redact API keys):
LLM_MODEL="gpt-4-0125-preview"
LLM_API_KEY=[Redacted]
WORKSPACE_DIR="./workspace"

SHELL=/bin/bash
SESSION_MANAGER=local/vinicius-sl:@/tmp/.ICE-unix/2905,unix/vinicius-sl:/tmp/.ICE-unix/2905
QT_ACCESSIBILITY=1
COLORTERM=truecolor
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
SSH_AGENT_LAUNCHER=gnome-keyring
NVM_INC=/home/vinicius/.nvm/versions/node/v20.12.0/include/node
XDG_MENU_PREFIX=gnome-
TERM_PROGRAM_VERSION=1.87.2
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
CONDA_EXE=/home/vinicius/anaconda3/bin/conda
_CE_M=
LANGUAGE=pt_BR:pt:en
GNOME_SHELL_SESSION_MODE=ubuntu
SSH_AUTH_SOCK=/run/user/1001/keyring/ssh
OPENAI_API_KEY=[Redacted]
XMODIFIERS=@im=ibus
DESKTOP_SESSION=ubuntu
GTK_MODULES=gail:atk-bridge
PWD=/home/vinicius/OpenDevin
XDG_SESSION_DESKTOP=ubuntu
LOGNAME=vinicius
XDG_SESSION_TYPE=wayland
CONDA_PREFIX=/home/vinicius/anaconda3/envs/od
SYSTEMD_EXEC_PID=2935
XAUTHORITY=/run/user/1001/.mutter-Xwaylandauth.YBIJL2
VSCODE_GIT_ASKPASS_NODE=/usr/share/code/code
IM_CONFIG_CHECK_ENV=1
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
HOME=/home/vinicius
USERNAME=vinicius
IM_CONFIG_PHASE=1
LANG=pt_BR.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_CURRENT_DESKTOP=Unity
WAYLAND_DISPLAY=wayland-0
CONDA_PROMPT_MODIFIER=(od) 
GIT_ASKPASS=/usr/share/code/resources/app/extensions/git/dist/askpass.sh
INVOCATION_ID=012a4705b6e04dc7942d788e28a73184
MANAGERPID=2722
CHROME_DESKTOP=code-url-handler.desktop
GJS_DEBUG_OUTPUT=stderr
NVM_DIR=/home/vinicius/.nvm
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
GNOME_SETUP_DISPLAY=:1
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
TERM=xterm-256color
_CE_CONDA=
LESSOPEN=| /usr/bin/lesspipe %s
USER=vinicius
VSCODE_GIT_IPC_HANDLE=/run/user/1001/vscode-git-ab5462a0d9.sock
CONDA_SHLVL=2
DISPLAY=:0
SHLVL=1
NVM_CD_FLAGS=
QT_IM_MODULE=ibus
CONDA_PYTHON_EXE=/home/vinicius/anaconda3/bin/python
XDG_RUNTIME_DIR=/run/user/1001
CONDA_DEFAULT_ENV=od
VSCODE_GIT_ASKPASS_MAIN=/usr/share/code/resources/app/extensions/git/dist/askpass-main.js
JOURNAL_STREAM=8:18088
XDG_DATA_DIRS=/usr/share/ubuntu:/home/vinicius/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
GDK_BACKEND=x11
PATH=/home/vinicius/.nvm/versions/node/v20.12.0/bin:/home/vinicius/anaconda3/envs/od/bin:/home/vinicius/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
GDMSESSION=ubuntu
ORIGINAL_XDG_CURRENT_DESKTOP=ubuntu:GNOME
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
NVM_BIN=/home/vinicius/.nvm/versions/node/v20.12.0/bin
CONDA_PREFIX_1=/home/vinicius/anaconda3
GIO_LAUNCHED_DESKTOP_FILE_PID=14877
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/code.desktop
TERM_PROGRAM=vscode
_=/usr/bin/printenv
```toml
```

**My model and agent** (you can see these settings in the UI):
* Model: none
* Agent: none

**Commands I ran to install and run OpenDevin**:
I followed the instructions on the github page
```

**Steps to Reproduce**:
1. follow the instructions on github page. 
2. generate an openai api key 
3.

**Logs, error messages, and screenshots**:

#### Additional Context
I feel stupid because I feel this is a simple flix lmao

**Comment by qwaszaq** [comment]
> The bug I am experiencing happens after I install everything I need to run OpenDevin, when I run the program I get this error on the browser ERROR: Failed connection to server. Please ensure the server is reachable at ws://localhost:3002/ws. and I can't use it I don't understand WHY it happens I tried building the program from scratch, I don't know if I have to change de localhost port or if I'm just being stupid and my port is closed.

> ```

same case....

**Comment by v4175mx** [comment]
Yup, same here.

**Comment by Hanz-Zoe** [comment]
Did you have any luck trying to solve it ?

**Comment by harshithahasii** [comment]
Same issue...

**Comment by spayyavula** [comment]
I am also having the same issue.

ERROR: Failed connection to server. Please ensure the server is reachable at ws://localhost:3001/ws.

**Comment by rbren** [comment]
@Hanz-Zoe any idea where port `3002` came from? We listen on 3000 and 3001 last I checked...

**Comment by xcodebuild** [comment]
Do you have the log information from the terminal after running `make run`? The information from the browser is very limited @Hanz-Zoe Han

> @Hanz-Zoe any idea where port `3002` came from? We listen on 3000 and 3001 last I checked...

`3002` is probably because the `3001` port is already occupied. `vite` will automatically search for available ports, but theoretically this does not affect usability.

**Comment by spayyavula** [comment]
The Logs are as follows -

6:57:38 PM [vite] http proxy error: /litellm-models
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
6:57:38 PM [vite] http proxy error: /default-model

**Comment by spayyavula** [comment]
Where do I look for the backend logs?

Regards
Sreekanth

**Comment by xcodebuild** [comment]
> Where do I look for the backend logs? Regards Sreekanth

`make run` **should** output backend logs, or you can `make start:frontend` and `make start:backend` separately

**Comment by spayyavula** [comment]
Logs
====

Warning: Python 3.11 was not found on your system...
Neither 'pyenv' nor 'asdf' could be found to install Python.
You can specify specific versions of Python with:
$ pipenv --python path/to/python
make[1]: *** [Makefile:26: start-backend] Error 1
make[1]: Leaving directory '/home/spayyavula/opendevin'

============================================

I have python 3.12 => Could that be an issue?

Regards
Sreekanth

**Comment by Hanz-Zoe** [comment]
@rbren  
> opendevin-frontend@0.1.0 start
> vite

Port 3001 is in use, trying another one...

  VITE v5.2.7  ready in 506 ms

  ➜  Local:   http://localhost:3002/
  ➜  Network: use --host to expose
--host

Here's what it shows in my terminal

**Comment by Hanz-Zoe** [comment]
@rbren I think it's my docker image that is using that port

**Comment by Hanz-Zoe** [comment]
in fact it seems I can't run the opendevin docker container, I don't understand why, not yet at least

**Comment by Hanz-Zoe** [comment]
od) vinicius@vinicius-sl:~/OpenDevin$ docker run ghcr.io/opendevin/sandbox
(od) vinicius@vinicius-sl:~/OpenDevin$ docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS         PORTS                  NAMES
d595323d4311   nginx:stable-alpine3.17-slim   "/docker-entrypoint.…"   8 minutes ago   Up 8 minutes   0.0.0.0:8080->80/tcp   nginx
(od) vinicius@vinicius-sl:~/OpenDevin$

**Comment by spayyavula** [comment]
I got it to work on Python 3.11. I had to pip install a lot of dependencies
manually though..

Regards
Sreekanth

**Comment by rbren** [comment]
We just updated the install process using poetry--hopefully a little better now

**Comment by rbren** [comment]
Closing in favor of https://github.com/OpenDevin/OpenDevin/issues/954

**Comment by spayyavula** [comment]
Thanks Robert. This time it was installed like a charm. Let me know if the
code it generates can be written to file in a specified folder.

Regards

**Comment by rbren** [comment]
@spayyavula yes you can set WORKSPACE_DIR (on the command line or in the UI settings) to decide which dir to work with. It's not the best workflow but we're working on it
