### ISSUE TITLE
OpenDevin does not run with Rancher on a Mac

### ISSUE THREAD

**Issue by olafgeibig** [OpenDevin/OpenDevin#673]
Known issue with Rancher on Mac. Please add to README.md

If you are running Rancher Desktop you need this line:

```sudo ln -s ~$USER/.rd/docker.sock /var/run/docker.sock```

https://github.com/rancher-sandbox/rancher-desktop/issues/2534

**Comment by rbren** [comment]
Probably a little too much of an edge case for the README, but we're working on various cookbooks for various scenarios. This seems like a good one to add

**Comment by jandubois** [comment]
I don't know how OpenDevin connects to the docker daemon, but modern client libraries normally support the concept of [docker contexts](https://docs.docker.com/engine/context/working-with-contexts/).

Rancher Desktop creates a `rancher-desktop` context and also makes it the current context if no context exists yet:

```
$ docker context show
rancher-desktop
```

If it is set to a different context, you can switch with `docker context use rancher-desktop`. Alternatively you can also set the `DOCKER_CONTEXT=rancher-desktop` environment variable. Or set `DOCKER_HOST="$HOME/.rd/docker.sock"`.

But if OpenDevin doesn't have support for the regular docker context/host mechanisms, then creating the symlink may be the only option. But it should be a last resort, as it makes permanent changes to the system.

PS: You can also configure Rancher Desktop to allow [Administrative Access](https://docs.rancherdesktop.io/ui/preferences/application/general), which will allow it to create the socket in the default location. Personally I would not recommend it, as you will have to enter your password to re-enable `sudo` access every time you start the app after you reboot your machine.

**Comment by rbren** [comment]
Hopefully the new docker installation method fixes this. If not, lmk and I'll reopen
