### ISSUE TITLE
Remove torch dependency if possible

### ISSUE THREAD

**Issue by JoonHong-Kim** [OpenDevin/OpenDevin#690]
**Summary**
There are too many unnecessary packages in this repository.
Why pytorch is there?
![image](https://github.com/OpenDevin/OpenDevin/assets/30318926/59d1d12b-8e58-4bae-acfe-f7fad2a79943)

**Additional context**

**Comment by rbren** [comment]
It's a good question on torch. Seems like a transitive dependency. Maybe from llamaindex?

**Comment by yufansong** [comment]
> There are too many unnecessary packages in this repository.

Agree, after introduce the pipenv, to much unnecessary dependency introcuded.

**Comment by foragerr** [comment]
@dorbanianas You moved torch to a separate dependency group?
This issue can be closed?

**Comment by dorbanianas** [comment]
Yeah thanks for the mention 👌

**Comment by dorbanianas** [comment]
This issue is solved by including torch to a new dependency group named `evaluation` in the pyproject.toml file
