### ISSUE TITLE
ONNX version discrepancy with recommended python version

### ISSUE THREAD

**Issue by vafaei-ar** [OpenDevin/OpenDevin#694]
#### Describe the bug

I have python 3.11.8 on mac and I am getting an error in make build.
 
#### Setup and configuration
**Current version**:

```bash
python --version
Python 3.11.8
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
```

**My model and agent** (you can see these settings in the UI):
* Model: OpenAI
* Agent:

**Commands I ran to install and run OpenDevin**:
```
make build
```

**Steps to Reproduce**:
1.make build
2.
3.

**Logs, error messages, and screenshots**:
 Preparing Installation of "zipp==3.18.1; python_version >= '3.8' --hash=sha256:206f5a15f2af3dbaee80769fb7dc6f249695e940acca08dfb2a4769fe61e538b 
--hash=sha256:2884ed22e7d8961de1c9a05142eb69a247f120291bc0206a00a7642f09b5b715"
$ /Users/decodelab1/.local/share/virtualenvs/OpenDevin-Gtn4eF7s/bin/python /Users/decodelab1/miniconda3/envs/od/lib/python3.11/site-packages/pipenv/patched/pip/__pip-runner__.py install -i 
https://pypi.org/simple --no-input --upgrade --no-deps -r /var/folders/6z/1g2wt2fs0zv2p18mty31b0h00000gn/T/pipenv-0r3d7hk0-requirements/pipenv-k90yjq8k-reqs.txt
Using source directory: '/Users/decodelab1/.local/share/virtualenvs/OpenDevin-Gtn4eF7s/src'
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 
Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.17.1 (from versions: 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.17.1
[pipenv.exceptions.InstallError]: ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement onnxruntime==1.17.1 (from versions: 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for onnxruntime==1.17.1
ERROR: Couldn't install package: {}

**Comment by dorbanianas** [comment]
can anyone reproduce this issue? @vafaei-ar you still face the issue?

**Comment by vafaei-ar** [comment]
Thanks, I tried again by updating the repo with the latest updates and the problem is resolved. One important thing to keep in mind might be one should let make to install python.
