### ISSUE TITLE
Gets error that Node.js version is wrong when its exactly 18.17.1

### ISSUE THREAD

**Issue by emilie2906** [OpenDevin/OpenDevin#698]
I was in the process of setting up the project using the make build command. During this process, I encountered the following error:
"The current Node.js version is 18.17.1, but Corepack is unsupported. Required version: ^18.17.1."
It appears that the detect-node-version.js file is configured to only accept versions of Node.js that are strictly greater than 18.17.1. The issue was resolved when I modified the logic to: if (compareVersions(currentVersion, targetVersion) >= 0).

**Comment by 94mashiro** [comment]
thanks for reporting this bug, I will fix it ASAP.

**Comment by heartsiddharth1** [comment]
Hi This is not fixed please find the latest screenshot  from my system
![Screenshot from 2024-04-04 19-28-28](https://github.com/OpenDevin/OpenDevin/assets/100776531/348ba013-5f99-4ac1-a9fe-3044965a1701)

**Comment by 94mashiro** [comment]
> Hi This is not fixed please find the latest screenshot from my system ![Screenshot from 2024-04-04 19-28-28](https://private-user-images.githubusercontent.com/100776531/319617841-348ba013-5f99-4ac1-a9fe-3044965a1701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNDE5MjYsIm5iZiI6MTcxMjI0MTYyNiwicGF0aCI6Ii8xMDA3NzY1MzEvMzE5NjE3ODQxLTM0OGJhMDEzLTVmOTktNGFjMS1hOWZlLTMwNDQ5NjVhMTcwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxNDQwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDkwNzZlNTYwY2U5YTQ5NzZkMGE3Yjk1NTczYTNlODg5MTA5ZmNmMTZiMWVhMWYyNzA5MzlhN2U4NDkwY2EwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ekrr8BtrvSIQIMxa3qIKsl6szwRNoIekgW66-mgnwKU)

Your node.js version is 12.22.9, should upgrade to at least 18.17.1。
Here is install tutorial via package manager.
https://nodejs.org/en/download/package-manager

**Comment by heartsiddharth1** [comment]
![Screenshot from 2024-04-05 21-41-04](https://github.com/OpenDevin/OpenDevin/assets/100776531/c41e2fed-adac-41e9-8bb9-02f8450d5366)
still same issue even after i installed the latest node

**Comment by enyst** [comment]
This console shows Node.js is still 12.22.9, you may need to check that.

Also, please pull the opendevin repository again to update (git pull, make build), we have changed from pipenv to poetry. See the readme

**Comment by heartsiddharth1** [comment]
thanks will get now and see
