### ISSUE TITLE
Doomsday is coming Gotta do fast

### ISSUE THREAD

**Issue by urmaliyadivyanshu31** [OpenDevin/OpenDevin#7]
What is there fo beginners to contribute

**Comment by pandahighfive** [comment]
> What is there fo beginners to contribute

Your body, to be used as a battery, by our upcoming AI overlords.... all hail The Devins..!!

**Comment by z-zeechung** [comment]
let's make some infrastructures like llm api, knowledge base, browser, shell env and so on. it harms nothing, at least

**Comment by JustinLin610** [comment]
We are going to design a contribution guideline then. Now people are just rushing
