### ISSUE TITLE
`python3` command compatibility

### ISSUE THREAD

**Issue by raygyli** [OpenDevin/OpenDevin#708]
#### Describe the bug

The Makefile fails to run on systems that use `python3` instead of `python` for using Python due to command incompatibility.

#### Setup and configuration

* System: Windows 11 WSL (Ubuntu 22.04.3)

**Current version**:
```bash
commit 08a2dfb01af1aec6743f5e4c23507d63980726c0 (HEAD -> main, origin/main, origin/HEAD)
Author: Jack Quimby <76570167+JayQuimby@users.noreply.github.com>
Date:   Tue Apr 2 23:20:25 2024 -0400

    Guide for Ollama local LLM (#615)
    
    * doc: Guide for using local LLM with Ollama
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
Default
```

**Commands I ran to install and run OpenDevin**:
```
make setup-config
make run

# or

make start-backend
# and
make start-frontend
```

**Steps to Reproduce**:
1. Use system where the command for Python is `python3` (or set alias)
2. Run OpenDevin with `make run` or `make start-backend` and `make start-frontend`

**Logs, error messages, and screenshots**:
```
make[1]: python: No such file or directory
make[1]: *** [Makefile:25: start-backend] Error 127
```

#### Additional Context
To fix this, we can conditionally check whether the Python command is `python` or `python3` etc.

**Comment by aanwark** [comment]
I am facing same issue on Macbook Pro 2019 with MacOS Solana.

**Comment by Jordan-88** [comment]
I went through the make file and changed all the calls that called python to python3

example.

@python -m pip install pipenv
@python -m pipenv install -v

go through all that and change to:

@python3 -m pip install pipenv
@python3 -m pipenv install -v

and anything else that calls python like that.

**Comment by 94mashiro** [comment]
```
brew install python@3.11
ln -s -f $(which python3.11) /usr/local/bin/python
```
This is effective for me.

**Comment by Jordan-88** [comment]
I actually submitted a pull request for this that should fix this. fingers crossed.

**Comment by foragerr** [comment]
Also, see: https://github.com/OpenDevin/OpenDevin/pull/650

**Comment by amralassal** [comment]
Also, change `python` to `python3` at:
```
start-backend:
	@echo "Starting backend..."
	@python3 -m pipenv run uvicorn opendevin.server.listen:app --port $(BACKEND_PORT)
```

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/9c275b0c-3be5-4820-9cbb-7799645b8ede)
Same issue

**Comment by aanwark** [comment]
> ```
> brew install python@3.11
> ln -s -f $(which python3.11) /usr/local/bin/python
> ```
> 
> This is effective for me.

This worked for me. Thanks

**Comment by dorbanianas** [comment]
You can pull now the new main it's working! if there's any issues let me know
