### ISSUE TITLE
Swe-bench evaluation not working

### ISSUE THREAD

**Issue by SinaRanjkeshzade** [OpenDevin/OpenDevin#709]
Hi, 
https://github.com/OpenDevin/SWE-bench/commit/2228232f7afee7da040cc16056e156b4180e4c3f has changed the files path in evaluation swe-bench and the evaluation process is not working. The harness folder which is the main folder for evaluation has been moved to swebench folder.

**Comment by JustinLin610** [comment]
Actually there are a lot of problems in the evaluation pipeline that need fix. Temporarily we are still updating the whole evaluation. Stay tuned

**Comment by yufansong** [comment]
Let's wait us works more on swe-bench. Close the problen now.
