### ISSUE TITLE
Tune rate-limit backoff

### ISSUE THREAD

**Issue by shing100** [OpenDevin/OpenDevin#710]
**What problem or use case are you trying to solve?**
Due to the AnthropicException error, which indicates that the request limit has been reached, it is necessary to increase the interval between requests. This will prevent system overload and provide a stable service.

**Describe the UX of the solution you'd like**
From a user experience (UX) perspective, the most important aspect is to send requests at an appropriate interval. Sending requests too frequently will cause errors, while sending requests at too long an interval will result in longer response times. Therefore, finding the right balance is crucial. Additionally, informing users about the current status and estimated wait time would also contribute to a good UX.

**Do you have thoughts on the technical implementation?**
From a technical implementation standpoint, a mechanism to monitor and manage request limits is required. For example, tracking the number of requests and the time they were made, and stopping requests for a certain period of time once the limit is reached. Additionally, implementing an algorithm to dynamically adjust the request interval could be more efficient.

**Additional context**
An additional consideration is the error handling mechanism. When a request limit error occurs, appropriate exception handling and retry logic should be implemented. Additionally, through logging and monitoring systems, the system's status should be continuously monitored, and issues should be promptly detected.

**Comment by rbren** [comment]
We did a first pass at rate-limit handling here: https://github.com/OpenDevin/OpenDevin/pull/501/files

Sounds like we need to fix it up a bit

**Comment by shing100** [comment]
@enyst Thanks you so much!!!
