### ISSUE TITLE
Internal Error: EACCES: permission denied, symlink '.

### ISSUE THREAD

**Issue by taozhiyuai** [OpenDevin/OpenDevin#713]
#### Setup and configuration
**Current version**:

```bash
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
```

**Steps to Reproduce**:
1.i install all pre request package
2.run. make build
3. Internal Error: EACCES: permission denied, symlink '.

<img width="1589" alt="截屏2024-04-04 22 47 04" src="https://github.com/OpenDevin/OpenDevin/assets/146583103/3a657e10-319a-47b9-a13e-214f6f328aae">

**Logs, error messages, and screenshots**:

**Comment by yufansong** [comment]
Maybe try `sudo make build` if `sudo` is safe for you.

**Comment by taozhiyuai** [comment]
> Maybe try `sudo make build` if `sudo` is safe for you.

thanks but, error with this instruction.

`
(opendevin) taozhiyu@TAOZHIYUs-MBP OpenDevin % sudo make build
Password:
Building project...
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest
Installing Python dependencies...
WARNING: The directory '/Users/taozhiyu/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/
Requirement already satisfied: pipenv in /Users/taozhiyu/miniconda3/envs/opendevin/lib/python3.11/site-packages (2023.12.1)
Requirement already satisfied: certifi in /Users/taozhiyu/miniconda3/envs/opendevin/lib/python3.11/site-packages (from pipenv) (2024.2.2)
Requirement already satisfied: setuptools>=67 in /Users/taozhiyu/miniconda3/envs/opendevin/lib/python3.11/site-packages (from pipenv) (69.2.0)
Requirement already satisfied: virtualenv>=20.24.2 in /Users/taozhiyu/miniconda3/envs/opendevin/lib/python3.11/site-packages (from pipenv) (20.25.1)
Requirement already satisfied: distlib<1,>=0.3.7 in /Users/taozhiyu/miniconda3/envs/opendevin/lib/python3.11/site-packages (from virtualenv>=20.24.2->pipenv) (0.3.8)
Requirement already satisfied: filelock<4,>=3.12.2 in /Users/taozhiyu/miniconda3/envs/opendevin/lib/python3.11/site-packages (from virtualenv>=20.24.2->pipenv) (3.13.3)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /Users/taozhiyu/miniconda3/envs/opendevin/lib/python3.11/site-packages (from virtualenv>=20.24.2->pipenv) (4.2.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Installing dependencies from Pipfile.lock (370c43)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Setting up frontend environment...
Detect Node.js version...
Current Node.js version is 21.7.1, corepack is supported.
Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-8.15.6.tgz.

Do you want to continue? [Y/n] Y
Lockfile is up to date, resolution step is skipped
Packages: +902
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading registry.npmmirror.com/monaco-editor/0.47.0: 17.39 MB/17.39 MB, done
Downloading registry.npmmirror.com/typescript/5.4.3: 5.82 MB/5.82 MB, done
Progress: resolved 902, reused 0, downloaded 902, added 902, done
node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild: Running postinstall script, done in 220ms

dependencies:
+ @monaco-editor/react 4.6.0
+ @nextui-org/react 2.2.10
+ @react-types/shared 3.22.1
+ @reduxjs/toolkit 2.2.3
+ @testing-library/jest-dom 5.17.0
+ @testing-library/react 13.4.0
+ @testing-library/user-event 13.5.0
+ @types/node 18.19.29
+ @types/react 18.2.74
+ @types/react-dom 18.2.23
+ @types/react-syntax-highlighter 15.5.11
+ @typescript-eslint/eslint-plugin 7.5.0
+ @vitejs/plugin-react 4.2.1
+ @xterm/xterm 5.4.0
+ eslint-config-airbnb-typescript 18.0.0
+ framer-motion 11.0.24
+ react 18.2.0
+ react-dom 18.2.0
+ react-redux 9.1.0
+ react-syntax-highlighter 15.5.0
+ typescript 5.4.3
+ vite 5.2.8
+ vite-tsconfig-paths 4.3.2
+ web-vitals 2.1.4
+ xterm-addon-fit 0.8.0

devDependencies:
+ @types/jest 29.5.12
+ @typescript-eslint/parser 7.5.0
+ autoprefixer 10.4.19
+ eslint 8.57.0
+ eslint-config-airbnb 19.0.4
+ eslint-config-prettier 9.1.0
+ eslint-plugin-import 2.29.1
+ eslint-plugin-jsx-a11y 6.8.0
+ eslint-plugin-prettier 5.1.3
+ eslint-plugin-react 7.34.1
+ eslint-plugin-react-hooks 4.6.0
+ husky 8.0.3
+ jest 29.7.0
+ jest-environment-jsdom 29.7.0
+ lint-staged 15.2.2
+ postcss 8.4.38
+ prettier 3.2.5
+ tailwindcss 3.4.3
+ ts-jest 29.1.2

> opendevin-frontend@0.1.0 prepare /Users/taozhiyu/Downloads/OpenDevin/frontend
> cd .. && husky install frontend/.husky

fatal: not a git repository (or any of the parent directories): .git
husky - git command not found, skipping install

Done in 10.7s
`

**Comment by yufansong** [comment]
> fatal: not a git repository (or any of the parent directories): .git
husky - git command not found, skipping install

Those two lines look strange. Seems like a git or husky problem.

**Comment by yufansong** [comment]
When I try `sudo make run` locally, I will get:
```

> opendevin-frontend@0.1.0 prepare /Users/yufansong/code/OpenDevin/frontend
> cd .. && husky install frontend/.husky

husky - Git hooks installed
Done in 1.6s
```
