### ISSUE TITLE
Support multiple simultaneous sessions

### ISSUE THREAD

**Issue by Yashwanth-Chandrakumar** [OpenDevin/OpenDevin#717]
**What problem or use case are you trying to solve?**
Similar to ChatGPT, users can create a new chat with new work directory but can work on different chats without any issue.

**Describe the UX of the solution you'd like**
A new chat button to create a new chat.

**Comment by yufansong** [comment]
I think our sandbox logic also need some change [here](https://github.com/OpenDevin/OpenDevin/blob/baa981cda761907ae53419921e1aa5d8048d18d9/opendevin/controller/command_manager.py#L9) to support this change.
