### ISSUE TITLE
Oops. Something went wrong: 'str' object has no attribute 'copy'

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#718]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/870d1ba0-691f-4841-93f2-c15c71160a00)

**Comment by yufansong** [comment]
Can you provide more information in the log file? Do you find any more useful clues?

**Comment by PierrunoYT** [comment]
> Can you provide more information in the log file? Do you find any more useful clues?

Hey there. I dont have any log files inside the logs folder in OpenDevin

**Comment by yufansong** [comment]
Or do you find any logs in terminal output where you run `make run`?

**Comment by PierrunoYT** [comment]
> Or do you find any logs in terminal output where you run `make run`?

No I closed it already but I run the backend and frontend seperately.

**Comment by yufansong** [comment]
> I run the backend and frontend seperately

That is OK. If you meet this problem again and have any useful logs, please put it here. I will also pay attention whether other user also meet this problem.

**Comment by PierrunoYT** [comment]
> > I run the backend and frontend seperately
> 
> That is OK. If you meet this problem again and have any useful logs, please put it here. I will also pay attention whether other user also meet this problem.

Okay but right now I have a new problem.

**Comment by SaeedSalem** [comment]
I am facing the same problem, and I am getting the following error:

```
'str' object has no attribute 'copy'
Traceback (most recent call last):
  File "OpenDevin/opendevin/controller/agent_controller.py", line 113, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "OpenDevin/agenthub/monologue_agent/agent.py", line 166, in step
    action = prompts.parse_action_response(action_resp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "OpenDevin/agenthub/monologue_agent/utils/prompts.py", line 135, in parse_action_response
    return action_from_dict(action_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "OpenDevin/opendevin/action/__init__.py", line 24, in action_from_dict
    action = action.copy()
             ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'copy'
```

**Comment by stratte89** [comment]
Choose different llm's, i tried like 30 already on my i5 11400, 32gb ram, rtx3080 and many model gave me that error as well, i guess their just too weak to power devin. have't found the "right" one yet but im experementing with TheBloke_Mistral-7B-Instruct-v0.2-code-ft-AWQ and TheBloke_Mistral-7B-Instruct-v0.2-code-ft-AWQ although TheBloke_Mistral-7B-Instruct-v0.2-code-ft-AWQ is making a lot of reasonable thinking it stops writing updates in the devinchat and just updates it'S messages in the terminal without actually programming. But I just went home so I'm gonna try with the latest version. Also I recommend to use oobabooga webui since it's the only one which got me a good output.  here is a guide for oobabooga https://github.com/OpenDevin/OpenDevin/commit/08a2dfb01af1aec6743f5e4c23507d63980726c0#commitcomment-140559598

**Comment by stratte89** [comment]
> claude works try that one out

what model are you using? can you provide a huggingface link? also what are your specs? just to compare

**Comment by PierrunoYT** [comment]
> claude works try that one out

I'm using Claude and I got this error.

**Comment by PierrunoYT** [comment]
> > ![grafik](https://private-user-images.githubusercontent.com/95778421/319923881-7b7b8ec8-ec96-4216-b915-81a605c835c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMDczMzEsIm5iZiI6MTcxMjMwNzAzMSwicGF0aCI6Ii85NTc3ODQyMS8zMTk5MjM4ODEtN2I3YjhlYzgtZWM5Ni00MjE2LWI5MTUtODFhNjA1YzgzNWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA4NTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3N2JhYzI0NTFjYzlhNGUwNmQ3NjkzY2Q1MmM4MjI3N2IzMzQ4N2ZiM2E4MzI0MGQ5OWE2YTU2MDE3MGM3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9oXZxPObQ6I1qcrbfHQbrSewXJ22z2l2NiuqNVpbnKM) ![Screenshot 2024-04-05 104352](https://private-user-images.githubusercontent.com/95778421/319924291-f0466431-fd3d-4e3f-af1e-8bbab27125ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMDczMzEsIm5iZiI6MTcxMjMwNzAzMSwicGF0aCI6Ii85NTc3ODQyMS8zMTk5MjQyOTEtZjA0NjY0MzEtZmQzZC00ZTNmLWFmMWUtOGJiYWIyNzEyNWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA4NTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViY2RmMmU2MmRjZGZlZGQzZDE4MDI4ZjcxZjgyYjcxZTc1NzJjYmEyNGI5Y2RlYzJlN2Q2MzRhOWNhZWVhNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iSOdh83_YHXMstP5vQW_6XoQppzQ5fK-w5sKFJtF48A)
> 
> [#718 (comment)](https://github.com/OpenDevin/OpenDevin/issues/718#issuecomment-2038342654)
> 
> make sure that the model has a high context lenght like 25000+, make sure you have enough vram/ram depending on what architecture ur using (gguf, awq). What claude model are you using and what ai software are you using? like ollama, lm-studio, oobabooga etc

I'm using Claude 3

**Comment by stratte89** [comment]
> > > ![grafik](https://private-user-images.githubusercontent.com/95778421/319923881-7b7b8ec8-ec96-4216-b915-81a605c835c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMDczMzEsIm5iZiI6MTcxMjMwNzAzMSwicGF0aCI6Ii85NTc3ODQyMS8zMTk5MjM4ODEtN2I3YjhlYzgtZWM5Ni00MjE2LWI5MTUtODFhNjA1YzgzNWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA4NTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3N2JhYzI0NTFjYzlhNGUwNmQ3NjkzY2Q1MmM4MjI3N2IzMzQ4N2ZiM2E4MzI0MGQ5OWE2YTU2MDE3MGM3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9oXZxPObQ6I1qcrbfHQbrSewXJ22z2l2NiuqNVpbnKM) ![Screenshot 2024-04-05 104352](https://private-user-images.githubusercontent.com/95778421/319924291-f0466431-fd3d-4e3f-af1e-8bbab27125ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMDczMzEsIm5iZiI6MTcxMjMwNzAzMSwicGF0aCI6Ii85NTc3ODQyMS8zMTk5MjQyOTEtZjA0NjY0MzEtZmQzZC00ZTNmLWFmMWUtOGJiYWIyNzEyNWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA4NTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViY2RmMmU2MmRjZGZlZGQzZDE4MDI4ZjcxZjgyYjcxZTc1NzJjYmEyNGI5Y2RlYzJlN2Q2MzRhOWNhZWVhNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iSOdh83_YHXMstP5vQW_6XoQppzQ5fK-w5sKFJtF48A)
> > 
> > 
> > [#718 (comment)](https://github.com/OpenDevin/OpenDevin/issues/718#issuecomment-2038342654)
> > make sure that the model has a high context lenght like 25000+, make sure you have enough vram/ram depending on what architecture ur using (gguf, awq). What claude model are you using and what ai software are you using? like ollama, lm-studio, oobabooga etc
> 
> I'm using Claude 3

ah i see, sorry i haven't used claude 3. hope someone else can help

**Comment by SmartManoj** [comment]
![image](https://github.com/OpenDevin/OpenDevin/assets/7231077/a78bded3-6d27-40b8-94e4-a9120d469b9a)

https://github.com/continuedev/continue/issues/919#issuecomment-1975224068
