### ISSUE TITLE
ERROR: Failed connection to server. Please ensure the server is reachable at ws://localhost:3001/ws.

### ISSUE THREAD

**Issue by jorsky** [OpenDevin/OpenDevin#720]
#### Describe the bug

 [vite] http proxy error: /default-model
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
#### Setup and configuration
**Current version**:

Author: mashiro <github@te.sb>
Date:   Thu Apr 4 21:44:07 2024 +0800

    fix: block input send event while ime composition (#701)
    
    * fix: trigger send event while ime composition & separate input element & disable input event while initializing
    
    * fix: eslint react plugin setting
    
    ---------
    
    Co-authored-by: Jim Su <jimsu@protonmail.com>
```bash
```

**My config.toml and environment vars** (be sure to redact API keys):

LLM_MODEL="claude-3-haiku-20240307"
LLM_API_KEY="redacted"
WORKSPACE_DIR="./workspace"

```toml
```

**My model and agent** (you can see these settings in the UI):
* Model:not showing
* Agent:not showing

**Commands I ran to install and run OpenDevin**:

git clone 

make build

make run 

make setup-config 
```
```

**Steps to Reproduce**:
1.make run 
2.get error
3.

**Logs, error messages, and screenshots**:
ERROR: Failed connection to server. Please ensure the server is reachable at ws://localhost:3001/ws.

socket.ts:12 WebSocket connection to 'ws://localhost:3001/ws' failed: 
:3001/api/default-model:1 
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:3001/api/litellm-models:1 
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:3001/api/litellm-agents:1 
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:3001/api/default-model:1 
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:3001/api/litellm-models:1 
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:3001/api/litellm-agents:1 
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
localhost/:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at getInitialModel (settingsService.ts:11:14)
    at async setInitialModel (SettingModal.tsx:59:28)
localhost/:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at fetchModels (settingsService.ts:16:19)
localhost/:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at fetchAgents (settingsService.ts:21:19)
localhost/:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at getInitialModel (settingsService.ts:11:14)
    at async setInitialModel (SettingModal.tsx:59:28)
localhost/:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at fetchModels (settingsService.ts:16:19)
localhost/:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
<img width="762" alt="Screenshot 2024-04-04 at 9 53 19 AM" src="https://github.com/OpenDevin/OpenDevin/assets/33999365/1a0c24cd-5a12-4190-be42-9af4725fed23">

**Comment by ataki** [comment]
I got this too. Rebooting the server solved the issue. There are also prev tickets that talk about this: https://github.com/OpenDevin/OpenDevin/issues/671

**Comment by jorsky** [comment]
> I got this too. Rebooting the server solved the issue. There are also prev tickets that talk about this: #671
> 
> Caveat: I didn't use `claude` in my mode, but this error seems to be front-end related.

How did you restart the server?

**Comment by jorsky** [comment]
Work fire wall was blocking 3001 request

**Comment by chandrabhraman** [comment]
Hi all, I am facing the same issue in the terminal
`Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)`
while my browser (tried both firefox and chrome) gives the following error:
`ERROR: WebSocket connection is not ready.` and temporarily this:
`ERROR: Failed to get token: TypeError: NetworkError when attempting to fetch resource..`

Restarting didn't seem to help.
