### ISSUE TITLE
backend fails to start

### ISSUE THREAD

**Issue by blackron83** [OpenDevin/OpenDevin#728]
#### Describe the bug
Backend fails to start with the following error:
Error! Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

#### Setup and configuration
**Current version**:
commit baa981cda761907ae53419921e1aa5d8048d18d9 (HEAD -> main, origin/main, origin/HEAD)
Author: mashiro <github@te.sb>
Date:   Thu Apr 4 21:44:07 2024 +0800

    fix: block input send event while ime composition (#701)
    
    * fix: trigger send event while ime composition & separate input element & disable input event while initializing
    
    * fix: eslint react plugin setting
    
    ---------
    
    Co-authored-by: Jim Su <jimsu@protonmail.com>

**My config.toml and environment vars** (be sure to redact API keys):
LLM_MODEL="gpt-3.5-turbo"
LLM_API_KEY=<MY-API-KEY>
WORKSPACE_DIR="./workspace"

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
make build
make run

**Steps to Reproduce**:
make run

**Logs, error messages, and screenshots**:

make start-backend
Starting backend...
INFO:     Started server process [87829]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 49868) - "WebSocket /ws" [accepted]
INFO:     connection open
INFO:     127.0.0.1:49869 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:49870 - "GET /litellm-agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:49871 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:49872 - "GET /litellm-agents HTTP/1.1" 200 OK
Please check Docker is running using `docker ps`.
Error! Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Failed to stop container: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Error creating controller.

**Comment by yufansong** [comment]
Thanks for the reply. If problem get solved. Please close it.

**Comment by blackron83** [comment]
thanks @williamliawdesign.
Issue solved

**Comment by DOLARIK** [comment]
The following did not solve my issue, and the make run command remains stuck at "waiting for the backend to start"

<img width="572" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/22707418/c8c7a7f6-eb8f-46a5-833a-46e5722fbef9">


> I ran into the same issue, check Docker Socket Permissions (Especially for MacOS): This seems to be a common culprit on MacOS. Follow these steps:
> 
> 1. Open Docker Desktop settings.
> 2. Go to "Settings" > "Advanced".
> 3. Check the box for "Allow the default Docker socket to be used (requires password)".
> 4. Restart Docker Desktop.

**Comment by enyst** [comment]
@DOLARIK try to start separately, ```make start-backend``` and then in another terminal, ```make start-frontend```.

If it's still a problem, please open a new issue and fill in the information, so we can figure out what's wrong.
