### ISSUE TITLE
Localhost takes long to load

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#729]
I think last time it was faster in loading the website on localhost. Right now it takes like at leat 15 seconds to load.

**Comment by PierrunoYT** [comment]
> after running which command?

while starting front and backend.

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/008895d5-3fd0-49c3-b38d-c01b3fc364f5)

**Comment by rbren** [comment]
Closing due to lack of information
