### ISSUE TITLE
Don't send initialize event for settings where it's not necessary

### ISSUE THREAD

**Issue by yimothysu** [OpenDevin/OpenDevin#732]
We currently send an `initialize` event regardless of which setting was changed. However, some settings are frontend-only (such as i18n). We should avoid sending the `initialize` event if frontend-only settings are changed since it wastes time to restart docker, etc.

**Comment by foragerr** [comment]
What would this change look like, is there more than dropping `language` from this line? https://github.com/94mashiro/OpenDevin/blob/4e5133fb9af4862d745e852616727ec049449022/frontend/src/components/SettingModal.tsx#L84

**Comment by yimothysu** [comment]
That would still send the `initialize` event, but without `language` in the payload.

**Comment by foragerr** [comment]
Ah, makes sense, thanks.

**Comment by foragerr** [comment]
Review https://github.com/OpenDevin/OpenDevin/pull/736 please.
