### ISSUE TITLE
The "--without" option does not exist.

### ISSUE THREAD

**Issue by stratte89** [OpenDevin/OpenDevin#740]
seems that the make build part got a little buggy, just tried to install the recent version.

  NoSuchOptionException

  The "--without" option does not exist.

  at /usr/lib/python3/dist-packages/clikit/args/default_args_parser.py:300 in _add_long_option
      296│     def _add_long_option(
      297│         self, name, value, tokens, fmt, lenient
      298│     ):  # type: (str, Optional[str], List[str], ArgsFormat, bool) -> None
      299│         if not fmt.has_option(name):
    → 300│             raise NoSuchOptionException(name)
      301│ 
      302│         option = fmt.get_option(name)
      303│ 
      304│         if value is False:
make: *** [Makefile:20: build] Fehler 1

And when starting the backend
(base) stratte@stratte-MS-7D08:~/Schreibtisch/AI/OpenDevin4$ make start-backend
Starting backend...

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  

  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│ 
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│ 
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
make: *** [Makefile:37: start-backend] Fehler 1

**Comment by dorbanianas** [comment]
which machine are you using?

**Comment by stratte89** [comment]
> which machine are you using?
I am using Ubuntu 22.04.4 LTS

**Comment by foragerr** [comment]
What's your `poetry --version`

**Comment by stratte89** [comment]
> poetry --version

shouldn't the makefile make sure to install the correct version? My Version is Poetry version 1.1.12

**Comment by foragerr** [comment]
+1 It should, and I thought it did.
Try upgrading poetry please. latest is 1.8.2

**Comment by stratte89** [comment]
> poetry --version

thanks, it solved the issue, but i ran into another error now

An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
Check the log at /home/stratte/.cache/pre-commit/pre-commit.log
make: *** [Makefile:23: build] Fehler 1

my git version 2.34.1

**Comment by foragerr** [comment]
I'm not sure about this one. What does `git status` return?
I'm guessing this comes from this line https://github.com/OpenDevin/OpenDevin/blob/main/Makefile#L23
perhaps comment/remove that one line temporarily to work around the issue.

**Comment by stratte89** [comment]
> git status

it prints that there is no git-repository in the filepath. i just donwnloaded the .zip file of opendevin. I will try removing that line thnx :)

(base) stratte@stratte-MS-7D08:~/Schreibtisch/AI/OpenDevin3$ git status
fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git

**Comment by foragerr** [comment]
Yeah, there multiple things that assume you did a `git clone`, at least husky fails more gracefully.
ideally the `pre-commit install` line does too..

**Comment by stratte89** [comment]
> Yeah, there multiple things that assume you did a `git clone`, at least husky fails more gracefully. ideally the `pre-commit install` line does too..

alright its running, but there are no step updates in the the server terminal anymore, can i somehow activate them? like in the config.toml?

**Comment by dorbanianas** [comment]
what do you mean exactly?

**Comment by foragerr** [comment]
They're seeing the effect of this: https://github.com/OpenDevin/OpenDevin/pull/378#discussion_r1552135801

The logs now don't print to console, instead they go into a fine in ./logs .. I think.

**Comment by stratte89** [comment]
> what do you mean exactly?

![Bildschirmfoto vom 2024-04-05 02-45-49](https://github.com/OpenDevin/OpenDevin/assets/101955267/5f28c4f3-1235-4dbd-bfb7-e55763847bbf)

well before i could see the steps in the opendevin server terminal. Because some model tend to stop replying in the frontend but still outputting on the terminal, without outputting any files in the workspace tho. you can see that on the pic. So it was good to check if there was a a problem to change the model, not waiting for output and thinking its just working

**Comment by stratte89** [comment]
> They're seeing the effect of this: [#378 (comment)](https://github.com/OpenDevin/OpenDevin/pull/378#discussion_r1552135801)
> 
> The logs now don't print to console, instead they go into a file in ./logs .. I think.

oh sad. i'd love to print it again or having like another tab next to the browser with the live logs so you can check whats actually going on

**Comment by dorbanianas** [comment]
> oh sad. i'd love to print it again or having like another tab next to the browser with the live logs so you can check whats actually going on


you can create a new issue about that 👌
