### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by yucc-leon** [OpenDevin/OpenDevin#75]
I have some experience finetuning LLMs and synthetic data and would like to know more about how to contribute; already submitted the form but have not received the invitation from the Slack channel. 
Just want to know, is there any plan for the (outer) community? For example, if I clone this repo, add some code, and make a PR, is that OK to try?

**Comment by huybery** [comment]
If you fill out the form but don't receive an invitation, you may not have filled out the information completely. Let me know your email, thanks!

**Comment by yucc-leon** [comment]
Thanks for the replying. I received the invitation from Junyang right after raising this issue. Looking forward to the following discussions and planning!
