### ISSUE TITLE
BedrockException - AWS region not set

### ISSUE THREAD

**Issue by cocobeach** [OpenDevin/OpenDevin#755]
#### Describe the bug

Error when giving prompt top the AI for the first time:
 
Error condensing thoughts: BedrockException - AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file

#### Setup and configuration
**Current version**:

[dcaf51b](https://github.com/OpenDevin/OpenDevin/commit/dcaf51bc9e09ae02c5719aea7f9232d7c6dd2c9e)

**My config.toml and environment vars** (be sure to redact API keys):
```LLM_API_KEY="0"
WORKSPACE_DIR="./workspace"
LLM_BASE_URL="http://0.0.0.0:4000/"
LLM_MODEL="ollama/mixtral"
LLM_EMBEDDING_MODEL="ollama/mixtral"
ANTHROPIC_API_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```

**My model and agent** (you can see these settings in the UI):
* Model: mistral.mixtral-8x7b-instruct-v0:1
* Agent:MonologueAgent

**Commands I ran to install and run OpenDevin**:
make start-frontend
Starting frontend...

litellm --model ollama/mixtral

uvicorn opendevin.server.listen:app --port 3000

**Steps to Reproduce**:
1. Start Open Devin
2. input a prompt:

![Screenshot from 2024-04-05 08-46-14](https://github.com/OpenDevin/OpenDevin/assets/128893/6a8213a9-150f-4e07-8eac-e4a323abf4a8)

**Logs, error messages, and screenshots**:

#### Additional Context

/OpenDevin/agenthub/monologue_agent/utils/monologue.py", line 36, in condense
    raise RuntimeError(f"Error condensing thoughts: {e}")
RuntimeError: Error condensing thoughts: BedrockException - AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file

OBSERVATION:
Error condensing thoughts: BedrockException - AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file
Exited before finishing

**Comment by cocobeach** [comment]
Point being I don;t want amazon, I didn't setup amazon, why is it giving me this exception?

thanks for the great job btw

**Comment by cocobeach** [comment]
![Screenshot from 2024-04-05 09-05-45](https://github.com/OpenDevin/OpenDevin/assets/128893/8702080a-7bb3-41f5-ab83-7b044bfdabc1)
Same with claude

**Comment by risingsunomi** [comment]
What is the output of your logs located at OpenDevin/logs? I don't see anything in the code to ask this so I wonder if something else. Also, I see you ran the make start-frontend but did you also run make start-backend?

**Comment by yufansong** [comment]
We have no use `aws` in backend. I guess the problem may result from `ollama/mixtral `. Not sure if anyone have experience on `ollama/mixtral` can reply.

**Comment by Joseph-L-O** [comment]
Trying different models and get the same result, none of ollama models installed on my machine is working. All returns the message: "Oops. Something went wrong: BedrockException - AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file".

**Comment by liontariai** [comment]
I had the same issue, this solved it for me: https://github.com/OpenDevin/OpenDevin/issues/619#issuecomment-2041526238

**Comment by rbren** [comment]
This should be solved as of https://github.com/OpenDevin/OpenDevin/pull/863

If not let us know!
