### ISSUE TITLE
"make run" fails due to missing poetry dependency

### ISSUE THREAD

**Issue by akhilvc10** [OpenDevin/OpenDevin#759]
**Describe the bug**

The command `make run` fails due to a missing poetry dependency. The error message "make: poetry: No such file or directory" indicates that the `poetry` command is not available.

**Steps to Reproduce**

1. Run the command `make build`.
2. Observe the error message "make: poetry: No such file or directory" in the terminal.

**Logs, error messages, and screenshots**

<img width="585" alt="Screenshot 2024-04-05 at 1 08 15 PM" src="https://github.com/OpenDevin/OpenDevin/assets/23031065/bb52efe5-bccf-40dd-9270-ad46af330925">

**Additional Context**

* System information: macOS Ventura 13.4
* Python version: Python 3.11.7

**Additional Notes**

* It is recommended to verify the official OpenDevin documentation for the most up-to-date installation instructions to ensure `poetry` is properly installed.

**Comment by foragerr** [comment]
Your error indicates poetry _is_ installed, but you're not able to run it - I wonder if you need to add it's location to your $PATH.

could you please try `export PATH="$HOME/.local/bin:$PATH` and then `make build` ?

**Comment by guibovo** [comment]
> Your error indicates poetry _is_ installed, but you're not able to run it - I wonder if you need to add it's location to your $PATH.
> 
> could you please try `export PATH="$HOME/.local/bin:$PATH` and then `make build` ?

Thanks a lot, it solved fo me!
