### ISSUE TITLE
[Evaluation TODO] Move regression tests to `evaluation/`

### ISSUE THREAD

**Issue by xingyaoww** [OpenDevin/OpenDevin#76]
@rbren developed some regression tests [here](https://github.com/OpenDevin/OpenDevin/tree/main/agenthub/langchains_agent/regression). It would be pretty helpful if we could standardize it to a "test suites" to test any given `Agent` instance (abstraction: [here](https://github.com/OpenDevin/OpenDevin/blob/main/opendevin/agent.py)).

**Comment by zch-cc** [comment]
this is done as the pr is merged

**Comment by xingyaoww** [comment]
Solved by #86.
