### ISSUE TITLE
set-config

### ISSUE THREAD

**Issue by sravan792** [OpenDevin/OpenDevin#761]
#### Describe the bug

When running the make setup-config and after entering the LLM Model name, LLM API KEY, LLM Embedding Model, Workspace, iam getting at an error

process_begin: CreateProcess(NULL, mv config.toml.tmp config.toml, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:64: setup-config] Error 2

**Screenshot**:
(![erro](https://github.com/OpenDevin/OpenDevin/assets/142962217/5f4df255-b091-4a3c-93c8-8749c30fb358))

**Comment by yufansong** [comment]
Guess more like you local env problem. https://stackoverflow.com/questions/33674973/makefile-error-make-e-2-the-system-cannot-find-the-file-specified

**Comment by yufansong** [comment]
BTW, if you use windows, it seems like opendevin only can work on WSL on windows. I am not a windows user, so I am not familiar with this parts. But you may check some other issues. Many user discuss the error they have meet on windows.

**Comment by rbren** [comment]
@sravan792 if you're using WSL and still hitting this problem, feel free to open a new issue with the template filled out
