### ISSUE TITLE
Failing at make build on Windows

### ISSUE THREAD

**Issue by Xerizaf** [OpenDevin/OpenDevin#763]
#### Describe the bug

I'm trying to run make build in order to install the project but I'm encountering an error
#### Setup and configuration
Windows 10 with WSL, Python 3.11.8, Node.js 20.12.1, Docker Desktop 4.28.0.
**Current version**:

```bash
commit dcaf51bc9e09ae02c5719aea7f9232d7c6dd2c9e (HEAD -> main, origin/main, origin/HEAD)
Author: iFurySt <ifuryst@gmail.com>
Date:   Fri Apr 5 11:21:17 2024 +0800

    fix: add the community-maintained model list (#654)
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_API_KEY="<YOUR OPENAI API KEY>"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
make build
```

**Steps to Reproduce**:
1. Building the project
2. Installing dependencies
3. Setting up OpenDevin

**Logs, error messages, and screenshots**:

"Building project..."
"Pulling Docker image..."
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest

What's Next?
  1. Sign in to your Docker account → docker login
  2. View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/opendevin/sandbox
"Installing Python dependencies..."
curl: (23) Failure writing output to destination
make: *** [Makefile:19: build] Error 9009

#### Additional Context

I also tried to install poetry with pipx but it seems to fail on curl command

**Comment by PierrunoYT** [comment]
> #### Describe the bug
> 
> I'm trying to run make build in order to install the project but I'm encountering an error
> #### Setup and configuration
> 
> Windows 10 with WSL, Python 3.11.8, Node.js 20.12.1, Docker Desktop 4.28.0. **Current version**:
> 
> ```shell
> commit dcaf51bc9e09ae02c5719aea7f9232d7c6dd2c9e (HEAD -> main, origin/main, origin/HEAD)
> Author: iFurySt <ifuryst@gmail.com>
> Date:   Fri Apr 5 11:21:17 2024 +0800
> 
>     fix: add the community-maintained model list (#654)
> ```
> 
> **My config.toml and environment vars** (be sure to redact API keys):
> 
> ```toml
> LLM_API_KEY="<YOUR OPENAI API KEY>"
> WORKSPACE_DIR="./workspace"
> ```
> 
> **My model and agent** (you can see these settings in the UI):
> 
>     * Model:
> 
>     * Agent:
> 
> 
> **Commands I ran to install and run OpenDevin**:
> 
> ```
> make build
> ```
> 
> **Steps to Reproduce**:
> 
>     1. Building the project
> 
>     2. Installing dependencies
> 
>     3. Setting up OpenDevin
> 
> 
> **Logs, error messages, and screenshots**:
> 
> "Building project..." "Pulling Docker image..." Using default tag: latest latest: Pulling from opendevin/sandbox Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575 Status: Image is up to date for ghcr.io/opendevin/sandbox:latest ghcr.io/opendevin/sandbox:latest
> 
> What's Next?
> 
>     1. Sign in to your Docker account → docker login
> 
>     2. View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/opendevin/sandbox
>        "Installing Python dependencies..."
>        curl: (23) Failure writing output to destination
>        make: *** [Makefile:19: build] Error 9009
> 
> 
> #### Additional Context
> 
> I also tried to install poetry with pipx but it seems to fail on curl command

I don't think you posted the error.

**Comment by Xerizaf** [comment]
I think I have perimissions but sudo isn't available on Windows. Tried also to run it as admin but can't build it..

**Comment by PierrunoYT** [comment]
> I think I have perimissions but sudo isn't available on Windows. Tried also to run it as admin but can't build it..

Did you followed the readme https://github.com/OpenDevin/OpenDevin/blob/main/README.md

**Comment by Xerizaf** [comment]
I managed to get make run to work but now: Installing the current project: opendevin (0.1.0)
"Activating Poetry shell..."
"Installing pre-commit hooks..."
pre-commit installed at .git\hooks\pre-commit
"Setting up frontend environment..."
"Detect Node.js version..."
Current Node.js version is 20.12.1, corepack is supported.
-f non atteso.
make: *** [Makefile:27: build] Error255
@foragerr

**Comment by yufansong** [comment]
Seems you open a new issue here #771. Close this one.
