### ISSUE TITLE
Enhance LLM Usage by Separating Local vs. API-based Implementations and Reducing Installed Package Dependencies

### ISSUE THREAD

**Issue by touhidurrr** [OpenDevin/OpenDevin#766]
When I tried to do `make run` after a clean clone on a clean WSL Debian image, it tried to install 10GB+ Nvidia packages that made my system run out of disk space and segfault on build time. I am not sure why it needs Nvidia packages when my system does not have any external GPU to begin with (I use AMD APU) and its not like I was trying to run a model offline with OpenDevin (or if you are supposed to do that to begin with). So, this is outrageous.

**Current version**:
forgot as I cleaned up the mess. But it was using poetry so probably after #378 or 5ec0e5b7ec8088a47dae534ce04e25a8eb51f919.

**My config.toml and environment vars**:
```toml
LLM_MODEL="gpt-4-0125-preview"
LLM_API_KEY="<MY OPENAI API KEY>"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model: gpt-4-0125-preview
* Agent: not sure as build failed

**Commands I ran to install and run OpenDevin**:
```
git clone https://github.com/OpenDevin/OpenDevin.git
cd OpenDevin
make build
```

**Steps to Reproduce**:
See above section

**Comment by touhidurrr** [comment]
> Can you post the logs produced by make build please.

Basically it segfaulted showing disk errors trying to install various nvdia prefixed packages with poetry. I needed to delete the WSL Debian image to clean up my disk space afterwards. My PC was misbehaving so I proceeded with a restart quickly. Did not take any screenshots.

I don't want to face these problems again trying to build OpenDevin, so sorry for not being able to provide logs.

**Comment by dorbanianas** [comment]
I'll submit a PR soon about this issue I guess `poetry install --without evaluation` doesn't have an effect.

**Comment by dorbanianas** [comment]
I guess it's a dependency from llama-index you can get more info from [here ](https://medium.com/llamaindex-blog/running-mixtral-8x7-locally-with-llamaindex-e6cebeabe0ab#:~:text=By%20passing%20embed_model%3D%22local%22,you%20needed%20torch%20and%20transformers%20.) because we are using `OllamaEmbedding` so basically using a local modal would need torch and gpus

cc: @rbren

**Comment by dorbanianas** [comment]
so I will modify the title and tag and make it as feature to think about a better logic to separate the usage of local models than the APIs

**Comment by dorbanianas** [comment]
I think I would close that and create a new one with description and put this as reference.
