### ISSUE TITLE
frontend ui is not working as backend working

### ISSUE THREAD

**Issue by MokshithAnnagiri** [OpenDevin/OpenDevin#768]
for in this case backend logs 

==============
STEP 0

PLAN:
create a python calculator with ui

ACTION:
AgentThinkAction(thought="I need to start by creating a new python file for my calculator. I'll call it calculator.py.", action='think')

==============
STEP 1

PLAN:
create a python calculator with ui

ACTION:
AgentThinkAction(thought="I need to start by creating a new python file for my calculator. I'll call it calculator.py.", action='think')

==============
STEP 2

PLAN:
create a python calculator with ui

ACTION:
AgentThinkAction(thought="I need to start by creating a new python file for my calculator. I'll call it calculator.py. To do this, I can use the `write` action, set `path` to 'calculator.py', and set `content` to a shebang line and my initial code.", action='think')

==============
STEP 3

PLAN:
create a python calculator with ui

ACTION:
AgentThinkAction(thought="I need to start by creating a new python file for my calculator. I'll call it calculator.py. To do this, I can use the `write` action, set `path` to 'calculator.py', and set `content` to a shebang line and my initial code.", action='think')

==============
STEP 4

PLAN:
create a python calculator with ui

ACTION:
AgentThinkAction(thought='I have started by creating a new python file for my calculator named calculator.py. Now I need to write the basic structure of a command-line calculator in it.', action='think')

==============
STEP 5

PLAN:
create a python calculator with ui

ACTION:
AgentThinkAction(thought='Now that I have created the basic structure of the command-line calculator in calculator.py, I need to implement the functionality for the four basic arithmetic operations: addition, subtraction, multiplication, and division.', action='think')

==============
STEP 6

PLAN:
create a python calculator with ui

ACTION:
AgentThinkAction(thought="Now that I have created the basic structure of the command-line calculator in calculator.py, I need to implement the functionality for the four basic arithmetic operations: addition, subtraction, multiplication, and division. I will use an if-elif-else statement to check the user's input and perform the appropriate operation.", action='think')

in frontend is 

![Screenshot (3)](https://github.com/OpenDevin/OpenDevin/assets/85815678/b47bcd0e-74d1-4110-9674-2ad3aacd4feb)

here ui is just stop reacting with backend 

**use groq api** 

optional
for saving data use database . that can help to check previous data also save 

OS  -- ubuntu
browser -- chrome

**Comment by 808vita** [comment]
Thanks for the deatiled backend logs. Good catch , it is a hidden frontend bug!.

To be precise it happens here 
```
if (
      currentQueueMarker !== null &&
      currentQueueMarker !== 0 &&
      currentTypingMessage !== newMessage
    ) {
```
From the looks of it the UI would stop priting when AI sends two consequtive same messages - if the ai output is the following array of texts [a , b , c , d , e , f , f , g ,h] - the ui will stop at f .

I wrote this 😂 fast to fix another bug. Will make use of your bug report to implement this better, thanks again.
