### ISSUE TITLE
Black Screen When Ran in Codespace

### ISSUE THREAD

**Issue by GetGud** [OpenDevin/OpenDevin#770]
#### Describe the bug
I get a black screen when I try to run this in codespaces. 

#### Setup and configuration
**Current version**: Current
commit dcaf51bc9e09ae02c5719aea7f9232d7c6dd2c9e (HEAD -> main, origin/main, origin/HEAD)
Author: iFurySt <ifuryst@gmail.com>
Date:   Fri Apr 5 11:21:17 2024 +0800

    fix: add the community-maintained model list (#654)

**My config.toml and environment vars** (be sure to redact API keys):
```Basically default
```

**My model and agent** (you can see these settings in the UI):
* Model :Claude
* Agent: Default

**Commands I ran to install and run OpenDevin**:
``` Make Run
```

**Steps to Reproduce**:
1.Run in Codespaces.
2.Follow the instructions and install any dependances that are missing.
3.Look at the black screen of doom.

**Logs, error messages, and screenshots**:

**Comment by foragerr** [comment]
Does codespace allow you to start docker containers?
If not, I'd say it's not compatible with OpenDevin.

**Comment by GetGud** [comment]
Nevermind. It's working now.
