### ISSUE TITLE
-f non atteso. make: *** [Makefile:27: build] Error 255

### ISSUE THREAD

**Issue by Xerizaf** [OpenDevin/OpenDevin#771]
#### Describe the bug

I'm trying to building the project but when running make build an error occurred
#### Setup and configuration
Windows 10 with WSL, Python 3.11.8, Node.js 21.7.2, Docker Desktop 4.28.0

**Current version**:

```bash
commit dcaf51bc9e09ae02c5719aea7f9232d7c6dd2c9e (HEAD -> main, origin/main, origin/HEAD)
Author: iFurySt <ifuryst@gmail.com>
Date:   Fri Apr 5 11:21:17 2024 +0800

    fix: add the community-maintained model list (#654)
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_API_KEY="<YOUR OPENAI API KEY>"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
make build
```

**Steps to Reproduce**:
1. Installing dependencies
2. Building the project
3. Running it

**Logs, error messages, and screenshots**:

"Building project..."
"Pulling Docker image..."
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest

What's Next?
  1. Sign in to your Docker account → docker login
  2. View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/opendevin/sandbox
"Installing Python dependencies..."
Retrieving Poetry metadata

The latest version (1.8.2) is already installed.
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: opendevin (0.1.0)
"Activating Poetry shell..."
"Installing pre-commit hooks..."
pre-commit installed at .git\hooks\pre-commit
"Setting up frontend environment..."
"Detect Node.js version..."
Current Node.js version is 21.7.2, corepack is supported.
-f non atteso.
make: *** [Makefile:27: build] Error 255

#### Additional Context

I tried a lot of things to solve this. Please help me!

**Comment by foragerr** [comment]
I'm guessing `-f` not being an option comes from this line: https://github.com/OpenDevin/OpenDevin/blob/main/Makefile#L27

What shell do you use?

As a workaround, I would remove lines [27-30](https://github.com/OpenDevin/OpenDevin/blob/main/Makefile#L27-L30) and try again.

**Comment by Xerizaf** [comment]
I use cmd

**Comment by foragerr** [comment]
windows? You may need to use WSL.

**Comment by Xerizaf** [comment]
Yes I'm on Windows. Will try then and let you know! Thank you very much!

**Comment by Xerizaf** [comment]
I'm encountering this error now: xerizaf@DESKTOP-8EIPA77:/mnt/c/Users/Maradei/Desktop/OpenDevin/OpenDevin$ make build
Building project...
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
bccd10f490ab: Pull complete
5fbe14d869db: Pull complete
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Downloaded newer image for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest

What's Next?
  1. Sign in to your Docker account → docker login
  2. View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/opendevin/sandbox
Installing Python dependencies...
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/xerizaf/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.8.2): Done

Poetry (1.8.2) is installed now. Great!

To get started you need Poetry's bin directory (/home/xerizaf/.local/bin) in your `PATH`
environment variable.

Add `export PATH="/home/xerizaf/.local/bin:$PATH"` to your shell configuration file.

Alternatively, you can call Poetry explicitly with `/home/xerizaf/.local/bin/poetry`.

You can test that everything is set up by executing:

`poetry --version`

make: poetry: No such file or directory
make: *** [Makefile:20: build] Error 127

**Comment by yufansong** [comment]
> To get started you need Poetry's bin directory (/home/xerizaf/.local/bin) in your PATH
> environment variable.
> 
> Add export PATH="/home/xerizaf/.local/bin:$PATH" to your shell configuration file.
> 
> Alternatively, you can call Poetry explicitly with /home/xerizaf/.local/bin/poetry.
> 
> You can test that everything is set up by executing:
> 
> poetry --version
> 
> make: poetry: No such file or directory
> make: *** [Makefile:20: build] Error 127

You need to follow the instruction to set the poetry environment path. Or you cmd cannot find the `poetry`.

**Comment by PierrunoYT** [comment]
> Yes I'm on Windows. Will try then and let you know! Thank you very much!

You need to use WSL

**Comment by yufansong** [comment]
And maybe can checke this [comments](https://github.com/OpenDevin/OpenDevin/issues/759#issuecomment-2039618274)

**Comment by Xerizaf** [comment]
Thank you very much @yufansong. I'm installing the dependencies right now! I managed to get it working!

**Comment by yufansong** [comment]
Good, enjoy our work. Close it now.
