### ISSUE TITLE
Error Encountered - Preventing Functionality 

### ISSUE THREAD

**Issue by JakcinManoj** [OpenDevin/OpenDevin#772]
#### Describe the bug

Upon using OpenDevin, I encountered an error preventing certain functionalities from working properly.

#### Setup and configuration
**Current version**:

```bash
commit dcaf51bc9e09ae02c5719aea7f9232d7c6dd2c9e (HEAD -> main, origin/main, origin/HEAD)
Author: iFurySt <ifuryst@gmail.com>
Date:   Fri Apr 5 11:21:17 2024 +0800

    fix: add the community-maintained model list (#654)
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="gpt-3.5-turbo-1106"
LLM_API_KEY=""
LLM_EMBEDDING_MODEL="text-embedding-ada-002"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model: gpt-3.5-turbo-1106
* Agent: MonologueAgent

**Commands I ran to install and run OpenDevin**:
```
make build
make setup-config
make start-backend
make start-frontend
```

**Steps to Reproduce**:
1. I am using the API from the free version of Chatgpt i.e., chatgpt 3.5
2. I am running the codebase from WSL.
3. The UI and Backend runs well only the functionality causes the error 

**Logs, error messages, and screenshots**:
![image](https://github.com/OpenDevin/OpenDevin/assets/93825223/bde866d6-d997-4cb2-9c9e-5c2a1bc14dd5)
![image](https://github.com/OpenDevin/OpenDevin/assets/93825223/19044a66-3486-47b1-a644-44c5ed46bbca)
![image](https://github.com/OpenDevin/OpenDevin/assets/93825223/328a5a19-e899-4121-aafa-9e1b74b9b941)
![image](https://github.com/OpenDevin/OpenDevin/assets/93825223/d6bb8a87-b853-4129-9d78-af0187724e9d)
![image](https://github.com/OpenDevin/OpenDevin/assets/93825223/31408707-9688-43eb-be88-51fbd6dbd5f1)

#### Additional Context

I know that this error is also a part of the limit setting from the provider.
Does this tool not support the free tier of chatgpt?
Am I using the wrong model and EMBEDDING_MODEL names ?

### I have also tried it with gemini free version as well and face this issue 

**Prerequsite**
```
pip install -U google-generativeai
```

```
pip install -q google-generativeai
```
This didn't do the trick for me so I used the above 

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="gemini/gemini-pro-vision"
LLM_API_KEY=""
LLM_EMBEDDING_MODEL="text-embedding-ada-002"
WORKSPACE_DIR="./workspace"
```

**Screenshots***:
 
![image](https://github.com/OpenDevin/OpenDevin/assets/93825223/517712ef-13ef-42e3-a344-042215733e34)
![image](https://github.com/OpenDevin/OpenDevin/assets/93825223/59c78cdc-6857-47a3-a426-f815d6a65455)
![image](https://github.com/OpenDevin/OpenDevin/assets/93825223/896c5408-4cd2-4f26-b8ea-0bad86a22beb)

**Comment by foragerr** [comment]
insufficient_quota sounds like an OpenAI issue with your account. Other people report seeing that issue intermittently and resolving after some time. https://community.openai.com/t/i-keep-getting-an-error-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details-even-though-my-account-has-sufficient-credits/537053

**Comment by JakcinManoj** [comment]
> For gemini, I would try `gemini/gemini-pro` rather than the vision one.

It still shows the same error 
![image](https://github.com/OpenDevin/OpenDevin/assets/93825223/040f94ed-deea-4606-bc2a-ae294b4383bd)

**Comment by JakcinManoj** [comment]
> insufficient_quota sounds like an OpenAI issue with your account. Other people report seeing that issue intermittently and resolving after some time. https://community.openai.com/t/i-keep-getting-an-error-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details-even-though-my-account-has-sufficient-credits/537053

Yeah, It seems so 
But In my case 
![image](https://github.com/OpenDevin/OpenDevin/assets/93825223/0b30f963-2424-4fc8-a233-b5c0fe0ad703)
This error keeps on running and finally shows this error pops out at the last. I think this is because of the continuous request from the LLM. Do you have any idea where to add this line to see the eloboration of the error?  

![image](https://github.com/OpenDevin/OpenDevin/assets/93825223/a165350b-2d4a-4520-8672-807218db937e)

**Comment by yufansong** [comment]
> insufficient_quota sounds like an OpenAI issue with your account.

Agree with this. So currently close it. If you find any new problem related to opendevin, feel free to provide more details and reopen it.
