### ISSUE TITLE
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Xxcoincoin** [OpenDevin/OpenDevin#779]
### Discussed in https://github.com/OpenDevin/OpenDevin/discussions/778

<div type='discussions-op-text'>

<sup>Originally posted by **Xxcoincoin** April  5, 2024</sup>
Hello everyone, I installed OpenDevin on WSL2. I followed the tutorial in LOCAL_LLM_GUIDE.md

So launching in a cuda environment (od)
-make build
-modification of the configuration file
-make run: starts, but error
-make start-backend: not working

I have those errors : 

` ab@DESKTOP-6C3GB46:~/OpenDevin$ make run
Running the app...
/bin/sh: 1: [: unexpected operator
make[1]: Entering directory '/home/ab/OpenDevin'
Starting backend...
make[1]: Entering directory '/home/ab/OpenDevin'
Starting frontend...
[...]
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory`
[...]
8:28:57 PM [vite] ws proxy error:
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
8:28:57 PM [vite] http proxy error: /litellm-models
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
8:28:57 PM [vite] http proxy error: /default-model
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
8:28:57 PM [vite] http proxy error: /litellm-agents
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
8:28:57 PM [vite] http proxy error: /litellm-models
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
8:28:57 PM [vite] http proxy error: /default-model
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
8:28:57 PM [vite] http proxy error: /litellm-agents
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
`

For the libcudnn error i have installed inside my conda env pip install torch => did not work / same error
Installed cuDNN with the nvidia installer (https://developer.nvidia.com/cudnn-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_network) => same error...

I have no clue on what's going on, do you have some ideas ?

Thanks a lot guys !
</div>

**Comment by yufansong** [comment]
It should be your environment problem. Search a little about error 
```
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory
```
Maybe you can try [this](https://stackoverflow.com/questions/69779667/could-not-load-dynamic-library-libcudnn-so-8-in-ubuntu) or [this](https://github.com/NVIDIA/TensorRT/issues/1747)

**Comment by risingsunomi** [comment]
What version of Python are you using? I ran into something like this when I accidentally used Python 3.10

**Comment by rbren** [comment]
I'm going to dedupe this with https://github.com/OpenDevin/OpenDevin/issues/726 since they seem related
