### ISSUE TITLE
Make command results in `Access is denied error` 

### ISSUE THREAD

**Issue by BennyDanielT** [OpenDevin/OpenDevin#781]
Installing the current project: opendevin (0.1.0)                                          
[WinError 5] Access is denied: '%USERPROFILE%\\OpenDevin\\.venv\\Lib\\site-packages\\opendevin-0.1.0.dist-info'

**Comment by yufansong** [comment]
It seems like a permission error in your local env, rather than a bug. Close it now. Feel free to open it when you meet any new unexpect error.
