### ISSUE TITLE
make  build not working

### ISSUE THREAD

**Issue by Soundmovin46** [OpenDevin/OpenDevin#783]
so im trying to install this on a windows machine .i have swl and the make build is not working for me can you give the  install instruction and how to fix the make build work

**Comment by BennyDanielT** [comment]
What error(s) are you facing?
I am facing the following issue: 

```
Installing the current project: opendevin (0.1.0)
[WinError 5] Access is denied: '%USERPROFILE%\\OpenDevin\\.venv\\Lib\\site-packages\\opendevin-0.1.0.dist-info'
make: *** [Makefile:20: build] Error 1
```

**Comment by Soundmovin46** [comment]
> Oops, @BennyDanielT problem is a permission error. What is your problem @Soundmovin46 , any details?
 i think that i need poetry install
 but its saying make build not fuond

**Comment by yufansong** [comment]
Any more details? Maybe paste the log. Before continue, maybe check this problem #759.

**Comment by Soundmovin46** [comment]
devin_env) PS C:\Users\zombi\Downloads\GPT\OpenDevin> make build
make : The term 'make' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a     
path was included, verify that the path is correct and try again.
At line:1 char:1
+ make build
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFo  
   undException
    + FullyQualifiedErrorId : CommandNotFoundException

(devin_env) PS C:\Users\zombi\Downloads\GPT\OpenDevin>

**Comment by Ratul007** [comment]
Install Chocolatey and then install make from cmd after just enjoy many problems u have to solve 😜 this is first step

**Comment by Soundmovin46** [comment]
thank you ill try to install chocolatey and see how that gose

**Comment by foragerr** [comment]
If your paths start with `C:\` you're not in WSL.
OpenDevin only works on WSL.

**Comment by Soundmovin46** [comment]
thank you ill give a try

**Comment by BennyDanielT** [comment]
This might seem weird, but none of the Linux commands work in WSL for me.

```
DANNY:~# sudo apt-get install make
-sh: sudo: not found
```

**Comment by Soundmovin46** [comment]
(devin_env) soundmoving465@bryantmorrismin:/mnt/c/Users/zombi/downloads/gpt/OPENDEVIN$ make start-frontend
Starting frontend...
/bin/sh: 1: pnpm: not found
make: *** [Makefile:42: start-frontend] Error 127
(devin_env) soundmoving465@bryantmorrismin:/mnt/c/Users/zombi/downloads/gpt/OPENDEVIN$ make run
Running the app...
Waiting for the backend to start...
/bin/sh: 1: pnpm: not found
make: *** [Makefile:52: run] Error 127
(devin_env) soundmoving465@bryantmorrismin:/mnt/c/Users/zombi/downloads/gpt/OPENDEVIN$ got a new error pmpn not found

**Comment by Ratul007** [comment]
Contact with me 😭🤣

**Comment by foragerr** [comment]
Install `pnpm`.
It might be something like `curl -fsSL https://get.pnpm.io/install.sh | sh -`

**Comment by Soundmovin46** [comment]
> Contact with me 😭🤣

hey how it going

**Comment by Soundmovin46** [comment]
i got a new error Starting backend...
/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`. nd it sayhe api is wrong for lm-studio this is my crunnet set up LLM_MODEL="TheBloke/CodeLlama-13B-Instruct-GGUF/codellama-13b-instruct.Q8_0.gguf"
LLM_API_KEY="lm-studio"
LLM_EMBEDDING_MODEL="local"
WORKSPACE_DIR="./workspace"

**Comment by Soundmovin46** [comment]
Oops. Something went wrong: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: lm-studio. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

**Comment by Soundmovin46** [comment]
make start-backend
Starting backend...
/mnt/c/Users/zombi/Downloads/GPT/OpenDevin/devin_env_311/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.

**Comment by rbren** [comment]
This seems to be a mega-thread with many different issues conflated. If anyone is still having problems, open a new issue, and fill out the template.

Thanks all!

**Comment by Soundmovin46** [comment]
> This seems to be a mega-thread with many different issues conflated. If anyone is still having problems, open a new issue, and fill out the template.
> 
> Thanks all!

im just have problems
 with the last one

**Comment by werruww** [comment]
PS C:\Users\m\Desktop\a\OpenDevin> make
process_begin: CreateProcess(NULL, tput -Txterm setaf 2, ...) failed.
Makefile:23: pipe: No such file or directory
process_begin: CreateProcess(NULL, tput -Txterm sgr0, ...) failed.
Makefile:23: pipe: No such file or directory
process_begin: CreateProcess(NULL, tput -Txterm setaf 2, ...) failed.
Makefile:30: pipe: No such file or directory
process_begin: CreateProcess(NULL, tput -Txterm sgr0, ...) failed.
Makefile:30: pipe: No such file or directory
Building project...
process_begin: CreateProcess(NULL, tput -Txterm setaf 3, ...) failed.
Makefile:33: pipe: No such file or directory
process_begin: CreateProcess(NULL, tput -Txterm sgr0, ...) failed.
Makefile:33: pipe: No such file or directory
process_begin: CreateProcess(NULL, tput -Txterm setaf 2, ...) failed.
Makefile:40: pipe: No such file or directory
process_begin: CreateProcess(NULL, tput -Txterm sgr0, ...) failed.
Makefile:40: pipe: No such file or directory
Checking dependencies...
process_begin: CreateProcess(NULL, tput -Txterm setaf 3, ...) failed.
Makefile:43: pipe: No such file or directory
process_begin: CreateProcess(NULL, tput -Txterm sgr0, ...) failed.
Makefile:43: pipe: No such file or directory
process_begin: CreateProcess(NULL, tput -Txterm setaf 6, ...) failed.
Makefile:44: pipe: Bad file descriptor
process_begin: CreateProcess(NULL, tput -Txterm sgr0, ...) failed.
Makefile:44: pipe: Bad file descriptor
process_begin: CreateProcess(NULL, tput -Txterm setaf 6, ...) failed.
Makefile:44: pipe: Bad file descriptor
process_begin: CreateProcess(NULL, tput -Txterm sgr0, ...) failed.
Makefile:44: pipe: Bad file descriptor
process_begin: CreateProcess(NULL, tput -Txterm setaf 6, ...) failed.
Makefile:44: pipe: Bad file descriptor
process_begin: CreateProcess(NULL, tput -Txterm sgr0, ...) failed.
Makefile:44: pipe: Bad file descriptor
process_begin: CreateProcess(NULL, tput -Txterm setaf 1, ...) failed.
Makefile:44: pipe: Bad file descriptor
process_begin: CreateProcess(NULL, tput -Txterm sgr0, ...) failed.
Makefile:44: pipe: Bad file descriptor
Checking system...
Unsupported system detected. Please use macOS, Linux, or Windows Subsystem for Linux (WSL).
make[2]: *** [Makefile:44: check-system] Error 1
make[1]: *** [Makefile:34: check-dependencies] Error 2
make: *** [Makefile:24: build] Error 2
PS C:\Users\m\Desktop\a\OpenDevin>

**Comment by werruww** [comment]
win10
