### ISSUE TITLE
[meta] Create a discord channel

### ISSUE THREAD

**Issue by xplorer990** [OpenDevin/OpenDevin#787]
Create a discord channel, it would make communication easier. If possible let there be connection to Github for the issues that can be synchronised.

**Comment by jwtly10** [comment]
I would also suggest this. Issues are being spammed with make build issues - would be good to have a single place of all potential issues (often just poetry missing from path)

**Comment by universea** [comment]
> Create a discord channel, it would make communication easier. If possible let there be connection to Github for the issues that can be synchronised.

Currently, there is a Slack. What are the differences between Slack and Discord?

**Comment by risingsunomi** [comment]
There is a sister discord to the slack but also has other agent projects 

https://discord.gg/canwebeatdevin

**Comment by risingsunomi** [comment]
> > Create a discord channel, it would make communication easier. If possible let there be connection to Github for the issues that can be synchronised.
> 
> 
> 
> Currently, there is a Slack. What are the differences between Slack and Discord?

Not much of a difference except preference.

**Comment by jwtly10** [comment]
> > Create a discord channel, it would make communication easier. If possible let there be connection to Github for the issues that can be synchronised.
> 
> Currently, there is a Slack. What are the differences between Slack and Discord?

I just think its a case of the acceptance system. So people aren't applying and instead just creating an issue (with problems that potential fixes are found in other issues)

**Comment by rbren** [comment]
Hey folks--we're actively working on setting up a discussion space to help keep issues clear. Stay tuned!

**Comment by PierrunoYT** [comment]
Already asked for it

**Comment by neubig** [comment]
We created a discord for now: https://discord.gg/85CunwWggG

The devs might check slack more frequently, but do feel free to discuss issues there if you want.

**Comment by rbren** [comment]
Done! It's in the readme now
