### ISSUE TITLE
stucked step 0 lm studio

### ISSUE THREAD

**Issue by flavioTocca** [OpenDevin/OpenDevin#790]
i'm stucked in step 0 with lm studio he sends the first step to LM studio but it remains stuck there it does not return the response to devin and the LM studio logs
![agent](https://github.com/OpenDevin/OpenDevin/assets/64084046/2f3b3acf-7329-4a86-8d1e-f950ddf3b0bc)

![lmscreen](https://github.com/OpenDevin/OpenDevin/assets/64084046/a0bbbd13-7968-444c-9e39-1d0b8a6c9da5)
[lmstudio-server-log.txt](https://github.com/OpenDevin/OpenDevin/files/14877448/lmstudio-server-log.txt)

_Originally posted by @flavioTocca in https://github.com/OpenDevin/OpenDevin/discussions/672#discussioncomment-9014801_

**Comment by rbren** [comment]
@flavioTocca please open a new issue and fill out the template
