### ISSUE TITLE
Poetry unable to install pymupdfb on M1

### ISSUE THREAD

**Issue by spuder** [OpenDevin/OpenDevin#791]
#### Describe the bug

Doing `make build` on an OSX machine with M1/M2/M3 processor causes a failure because `pymupdfb (1.24.1)` is not available

#### Setup and configuration
**Current version**:

```bash
2855959c767feaea2b5e90dc76f93e996606d0e9
```

This was noticed by several other users in PR https://github.com/OpenDevin/OpenDevin/pull/378
- https://github.com/OpenDevin/OpenDevin/pull/378#issuecomment-2033478758

## Related

- https://github.com/pymupdf/PyMuPDF/issues/2613

One user [suggests the solution is to install MuPDF](https://github.com/pymupdf/PyMuPDF/discussions/1486#discussioncomment-1861977) to indirectly cause wheels to be installed

> There are no wheels for M1 platforms (and there will not be any time soon). So you must install from sources - which means you must install MuPDF first, then PyMuPDF.

I've tried that with no luck.

**Comment by spuder** [comment]
As mentioned [here](https://github.com/OpenDevin/OpenDevin/pull/378#issuecomment-2034843314)

## Workaround

```bash
poetry run pip install pymupdfb
poetry install --without evaluation
```

(poetry run might not be required), in which case the following might be more appropriate


```bash
pip install pymupdfb
poetry install --without evaluation
```

**Comment by rbren** [comment]
Should be fixed with the new docker installation method
