### ISSUE TITLE
frontend `npm run build` found errors

### ISSUE THREAD

**Issue by foragerr** [OpenDevin/OpenDevin#805]
```
cd frontend && npm run build
```

```
npm run build

> opendevin-frontend@0.1.0 build
> tsc && vite build

src/App.test.tsx:5:1 - error TS2593: Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha` and then add 'jest' or 'mocha' to the types field in your tsconfig.

5 test("renders learn react link", () => {
  ~~~~

src/App.test.tsx:8:3 - error TS2304: Cannot find name 'expect'.

8   expect(linkElement).toBeInTheDocument();
    ~~~~~~

src/components/CodeEditor.tsx:2:29 - error TS2307: Cannot find module 'monaco-editor' or its corresponding type declarations.

2 import type { editor } from "monaco-editor";
                              ~~~~~~~~~~~~~~~


Found 3 errors in 2 files.

Errors  Files
     2  src/App.test.tsx:5
     1  src/components/CodeEditor.tsx:2
```

**Comment by dorbanianas** [comment]
didn't you use make build?

**Comment by foragerr** [comment]
Sorry, I just realized I messed up my node_modules. 
cleaned up re-ran, lot fewer errors, but not 0

**Comment by dorbanianas** [comment]
For now the frontend is still under-dev so it's not that stable

**Comment by foragerr** [comment]
For giggles, I ran OpenDevin on this issue. It didn't fix it, but it came up with

> ACTION:
AgentThinkAction(thought="The errors can be grouped into two categories: missing type definitions and missing dependencies. For the 'Cannot find name' errors related to testing, installing @types/jest should suffice, since the default create-react-app setup uses Jest for testing. The 'Cannot find module' error for 'monaco-editor' suggests the actual dependency is missing or not installed correctly. The plan involves installing necessary types for Jest and the monaco-editor package. However, since the environment doesn't have Node.js or any package manager installed, further steps cannot be directly executed. The first step is amending the package.json to include the missing types and dependencies before thinking of a strategy to guide the user or another entity to properly install or update the required tools and dependencies.", action='think')

see full run here: https://github.com/foragerr/OpenDevin/actions/runs/8578500805/job/23512418111

@rbren dogfooding in action! ^^

**Comment by foragerr** [comment]
@dorbanianas would you mind reviewing https://github.com/OpenDevin/OpenDevin/pull/810 please.

**Comment by dorbanianas** [comment]
@foragerr I will take a look at that tomorrow morning it's now 5AM and I need to sleep 🥲 sorry abt that 🙏 but it would be the first thing that I will do 👌

**Comment by dorbanianas** [comment]
@neubig thanks 👌
