### ISSUE TITLE
api problem with lm -studios 

### ISSUE THREAD

**Issue by Soundmovin46** [OpenDevin/OpenDevin#806]
Retrying llama_index.embeddings.openai.base.get_embeddings in 0.3343583846742836 seconds as it raised AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: lm-studio. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}.
Retrying llama_index.embeddings.openai.base.get_embeddings in 0.8035137344338514 seconds as it raised AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: lm-studio. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}.
Retrying llama_index.embeddings.openai.base.get_embeddings in 1.8771487024421867 seconds as it raised AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: lm-studio. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}.
Retrying llama_index.embeddings.openai.base.get_embeddings in 6.788596299732432 seconds as it raised AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: lm-studio. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}.
Oops. Something went wrong: Error code: 401 - {'error': {'message': 'Incorrect API key provided: lm-studio. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

**Comment by friendlyFriend4000** [comment]
Trying to run opendevin for the first itme, I am running into same issue.

**Comment by rbren** [comment]
Hey all--lots of folks seem to have trouble with LM Studio. See this thread: https://github.com/OpenDevin/OpenDevin/issues/419

We'll work on getting some docs for LM Studio
