### ISSUE TITLE
MAKE A BETTER README.MD! NEEDS TO BE USERFRIENDLY AND ATTRACTIVE!

### ISSUE THREAD

**Issue by keithorange** [OpenDevin/OpenDevin#808]
OPEN DEVIN IS 2X BIGGER THAN DEVIKA! DO NOT LOSE THE RACE! OPEN DEVIN WILL WIN THE #1 OPEN SOURCE CODER! DESTROY OPEN AI! DESTROY DEVIN! DESTROY DEVIKA! OPEN DEVIN WILL SUCCEED!!!!!!!!!!!!!

**Comment by neubig** [comment]
If you have any concrete suggestions for making a better README please either send a PR or post an issue or [discussion](https://github.com/OpenDevin/OpenDevin/discussions)! This issue is not concrete enough to fix, so I'll close it for now.
