### ISSUE TITLE
Please Provide  docker compose file for this project for easy selfhosting

### ISSUE THREAD

**Issue by HakaishinShwet** [OpenDevin/OpenDevin#809]
Please build generalized images for this project component which can be used in docker compose to easily setup open devin. In just one single docker compose file and .env file we should have everything which we can change easily and run container as per our requirement.

**Comment by thelege2nd** [comment]
Where is the docker image even? The readme file got updated yesterday and deleted the instructions..

**Comment by neubig** [comment]
This is a great suggestion, but is also a duplicate with https://github.com/OpenDevin/OpenDevin/issues/110

I'd love to see this functionality implemented!
