### ISSUE TITLE
stucked step 0 lm studio

### ISSUE THREAD

**Issue by flavioTocca** [OpenDevin/OpenDevin#812]
i'm stucked in step 0 with lm studio he sends the first step to LM studio but it remains stuck there it does not return the response to devin and the LM studio logs.
i use wsl and windows 11

config file is:
LLM_MODEL="openai/MaziyarPanahi/dolphin-2.6-mistral-7b-GGUF/dolphin-2.6-mistral-7b.Q8_0.gguf"
LLM_API_KEY="lm-studio"
WORKSPACE_DIR="./workspace"
LLM_BASE_URL="http://localhost:1234/v1"
LLM_EMBEDDING_MODEL="local"
LLM_COOLDOWN_TIME = 1

![agent](https://github.com/OpenDevin/OpenDevin/assets/64084046/dfbdd33d-faef-479c-952f-ff2e8fcda269)
![lmscreen](https://github.com/OpenDevin/OpenDevin/assets/64084046/dae61d55-6daf-4078-a28f-352f9773683b)
[lmstudio-server-log.txt](https://github.com/OpenDevin/OpenDevin/files/14892853/lmstudio-server-log.txt)

**Comment by rbren** [comment]
Lots of folks seem to have a hard time running with LM Studio. We'll try and get some docs up for it.

See https://github.com/OpenDevin/OpenDevin/issues/419 for now
