### ISSUE TITLE
Localhost takes really long to load after starting front and backend using make run

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#816]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/a4884922-3b83-4721-80b0-c2ff470f19d5)

**Comment by PierrunoYT** [comment]
I clicked on it but it took at least 20 sec to load the web ui

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/5293a5e9-8db4-4da6-95d8-b3ef3bae56e1)
![grafik](https://github.com/OpenDevin/OpenDevin/assets/95778421/7ce1cca2-f111-4a1e-a45f-a778aeb4a25b)

**Comment by rbren** [comment]
@PierrunoYT please fill out the template when opening bugs. We need to know which version you're on at least.
