### ISSUE TITLE
Error installing pnpm on mac

### ISSUE THREAD

**Issue by neubig** [OpenDevin/OpenDevin#819]
#### Describe the bug

When i run `make build` on mac I get the following error:

```bash
Checking pnpm installation...
pnpm is not installed. Installing corepack to enable pnpm...
npm ERR! code EEXIST
npm ERR! path /opt/homebrew/bin/yarn
npm ERR! EEXIST: file already exists
npm ERR! File exists: /opt/homebrew/bin/yarn
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in: /Users/gneubig/.npm/_logs/2024-04-06T11_41_44_231Z-debug-0.log
/bin/sh: corepack: command not found
```

#### Setup and configuration
**Current version**:

```bash
commit 228889c50cf301bfbda9aacfe4e18ea6a3ff108d (HEAD -> main, origin/main, origin/HEAD)
Author: RaGe <foragerr@users.noreply.github.com>
Date:   Sat Apr 6 07:04:10 2024 -0400

    fix frontend dependencies (#810)
    
    fixes #805
```

**Commands I ran to install and run OpenDevin**:
```bash
make build
```

**Logs, error messages, and screenshots**:

Here is the full log cited in the error message above.
[2024-04-06T11_41_44_231Z-debug-0.log](https://github.com/OpenDevin/OpenDevin/files/14893401/2024-04-06T11_41_44_231Z-debug-0.log)

#### Additional Context

OS is Mac OS Sonoma 14.1.2 (23B92)

[Maybe we don't need pnpm](https://github.com/OpenDevin/OpenDevin/discussions/820)

**Comment by lehcode** [comment]
Are you trying to install PNPM with Yarn?
