### ISSUE TITLE
/bin/bash: line 1: google-chrome: command not found

### ISSUE THREAD

**Issue by timucindusunur** [OpenDevin/OpenDevin#822]
google-chrome https://www.google.com/search?q=Finansal+dan%C4%B1%C5%9Fmanl%C4%B1k+firmalar%C4%B1
/bin/bash: line 1: google-chrome: command not found

$ google-chrome https://www.duckduckgo.com/?q=Finansal+dan%C4%B1%C5%9Fmanl%C4%B1k+firmalar%C4%B1
/bin/bash: line 1: google-chrome: command not found

$ whois apple.com
/bin/bash: line 1: whois: command not found

Open devin worked, but it gives google-chrome: command not found error in the terminal.

What is the reason? I manually installed Google-chrome in Ubuntu, but it still didn't work. ??

**Comment by timucindusunur** [comment]
$ google-chrome https://www.google.com/search?q=Finansal+dan%C4%B1%C5%9Fmanl%C4%B1k+firmalar%C4%B1
/bin/bash: line 1: google-chrome: command not found


$ google-chrome https://www.duckduckgo.com/?q=Finansal+dan%C4%B1%C5%9Fmanl%C4%B1k+firmalar%C4%B1
/bin/bash: line 1: google-chrome: command not found


$ whois apple.com
/bin/bash: line 1: whois: command not found


$ firefox https://www.linkedin.com/search/results/people/?keywords=Financial%20advisor
/bin/bash: line 1: firefox: command not found


$ firefox https://www.linkedin.com/search/results/people/?keywords=Financial%20advisor
/bin/bash: line 1: firefox: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


$ export PATH=$PATH:/path/to/playwright


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found   


Cannot perform any installation!!!! Also, the ./workspace file is not automatically installed in the opendevin file anymore!!!

**Comment by LiuJiewenTT** [comment]
Did you install google chrome really?

**Comment by timucindusunur** [comment]
Yes, I installed it, google-chrome-stable_current_amd64.deb is installed in Ubuntu, I installed it manually but it is not there.

**Comment by timucindusunur** [comment]
1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


$ export PATH=$PATH:/path/to/playwright


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ playwright install
/bin/bash: line 1: playwright: command not found


$ sudo apt-get update && sudo apt-get upgrade
/bin/bash: line 1: sudo: command not found


$ apt install sudo

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package sudo


$ apt install sudo

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package sudo


$ apt install sudo

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package sudo


$ sudo apt-get update && sudo apt-get install sudo
/bin/bash: line 1: sudo: command not found


$ sudo apt-get update && sudo apt-get install sudo
/bin/bash: line 1: sudo: command not found


$ sudo apt-get update && sudo apt-get install sudo
/bin/bash: line 1: sudo: command not found


$ sudo apt-get update
/bin/bash: line 1: sudo: command not found


$ sudo apt-get update && sudo apt-get install sudo
/bin/bash: line 1: sudo: command not found


$ sudo apt-get update && sudo apt-get install sudo
/bin/bash: line 1: sudo: command not found


I knowingly leave the command still running to report all errors

**Comment by timucindusunur** [comment]
Also, it cannot execute any commands, not just Google browser.!!!

**Comment by timucindusunur** [comment]
![Ekran görüntüsü 2024-04-06 151151](https://github.com/OpenDevin/OpenDevin/assets/40573794/89ea9f7c-0656-4607-839f-bd32d2974582)

**Comment by timucindusunur** [comment]
![Ekran görüntüsü 2024-04-06 152206](https://github.com/OpenDevin/OpenDevin/assets/40573794/1ef48dea-f3cc-4498-830f-33462d446bd7)

**Comment by rbren** [comment]
@timucindusunur please open a new issue and fill out the template
