### ISSUE TITLE
awk issue in WSL

### ISSUE THREAD

**Issue by Jazbrooks5** [OpenDevin/OpenDevin#824]
New to programming so i tried to install and make opendevin work but i run into that issue, i don't know how to resolve it
"C:\OpenDevin\OpenDevin>make build
awk: cmd. line:1: '{print
awk: cmd. line:1: ^ invalid char ''' in expression
write /dev/stdout: The pipe is being closed.
"\033[0;32mBuilding project...\033[0m"
"\033[0;33mChecking Python installation...\033[0m"
-v était inattendu.
make: *** [Makefile:24: build] Error 255"
Can someone help me ? i am on windows 10, python 3.12

**Comment by rbren** [comment]
@dorbanianas seems like this `awk` line was introduced in https://github.com/OpenDevin/OpenDevin/commit/66cd9f9bd98e00d3677e5bc74a327895b18f58e3

**Comment by dorbanianas** [comment]
I'll try to remove it because it was used just to select the python version from the stdout

**Comment by dorbanianas** [comment]
@Jazbrooks5 solved now, pull the latest changes and enjoy 😁!!
