### ISSUE TITLE
Missing declaration.ts in OpenDevin\frontend\src\i18n

### ISSUE THREAD

**Issue by dwells3** [OpenDevin/OpenDevin#827]
Terminal output showed errors declaration was missing from OpenDevin\frontend\src\i18n. I reverse engineered it and this is what I have in the file to fix the error. Filename: declaration.ts

export enum I18nKey {
    WORKSPACE_TITLE = 'WORKSPACE$TITLE',
    WORKSPACE_TERMINAL_TAB_LABEL = 'WORKSPACE$TERMINAL_TAB_LABEL',
    WORKSPACE_PLANNER_TAB_LABEL = 'WORKSPACE$PLANNER_TAB_LABEL',
    WORKSPACE_CODE_EDITOR_TAB_LABEL = 'WORKSPACE$CODE_EDITOR_TAB_LABEL',
    WORKSPACE_BROWSER_TAB_LABEL = 'WORKSPACE$BROWSER_TAB_LABEL',
    CONFIGURATION_OPENDEVIN_WORKSPACE_DIRECTORY_INPUT_LABEL = 'CONFIGURATION$OPENDEVIN_WORKSPACE_DIRECTORY_INPUT_LABEL',
    CONFIGURATION_OPENDEVIN_WORKSPACE_DIRECTORY_INPUT_PLACEHOLDER = 'CONFIGURATION$OPENDEVIN_WORKSPACE_DIRECTORY_INPUT_PLACEHOLDER',
    CONFIGURATION_MODAL_TITLE = 'CONFIGURATION$MODAL_TITLE',
    CONFIGURATION_MODEL_SELECT_LABEL = 'CONFIGURATION$MODEL_SELECT_LABEL',
    CONFIGURATION_MODEL_SELECT_PLACEHOLDER = 'CONFIGURATION$MODEL_SELECT_PLACEHOLDER',
    CONFIGURATION_AGENT_SELECT_LABEL = 'CONFIGURATION$AGENT_SELECT_LABEL',
    CONFIGURATION_AGENT_SELECT_PLACEHOLDER = 'CONFIGURATION$AGENT_SELECT_PLACEHOLDER',
    CONFIGURATION_LANGUAGE_SELECT_LABEL = 'CONFIGURATION$LANGUAGE_SELECT_LABEL',
    CONFIGURATION_MODAL_CLOSE_BUTTON_LABEL = 'CONFIGURATION$MODAL_CLOSE_BUTTON_LABEL',
    CONFIGURATION_MODAL_SAVE_BUTTON_LABEL = 'CONFIGURATION$MODAL_SAVE_BUTTON_LABEL',
    CHAT_INTERFACE_INITIALZING_AGENT_LOADING_MESSAGE = 'CHAT_INTERFACE$INITIALZING_AGENT_LOADING_MESSAGE',
    CHAT_INTERFACE_INPUT_PLACEHOLDER = 'CHAT_INTERFACE$INPUT_PLACEHOLDER',
    CHAT_INTERFACE_INPUT_SEND_MESSAGE_BUTTON_CONTENT = 'CHAT_INTERFACE$INPUT_SEND_MESSAGE_BUTTON_CONTENT',
}

**Comment by enyst** [comment]
Please try @808vita 's suggestion, or ```make build``` and ```make run```, it should work. Closing this, but let us know if you still need assistance.
