### ISSUE TITLE
The working file cannot be created with the specified name.It creates the most

### ISSUE THREAD

**Issue by timucindusunur** [OpenDevin/OpenDevin#829]
![Ekran görüntüsü 2024-04-06 193649](https://github.com/OpenDevin/OpenDevin/assets/40573794/096b8bde-3c59-4d33-8983-00d18ef2f2f9)

The working file cannot be created with the specified name.It creates the most

**Comment by rbren** [comment]
@timucindusunur we'll need more info. Please open a new issue and fill out the template.
