### ISSUE TITLE
An error occurs when running `make build`, indicating that npm is unable to correctly install the frontend dependencies.

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#836]
## Bug Description
An error occurs when running `make build`, indicating that npm is unable to correctly install the frontend dependencies.

## Setup and Configuration
**Current Version**:

```bash
commit c0dfc851b9e9de352ad4adcb4752ef14c4ba9be2 (HEAD -> main, origin/main, origin/HEAD)
Author: AbhisekOmkar <67184718+AbhisekOmkar@users.noreply.github.com>
Date:   Sun Apr 7 00:00:58 2024 +0530

     Add Discord and Slack Community Link to README (#835)

    This pull request enhances the README.md file by adding a Discord community link to the OpenDevin project. The addition includes a Discord logo with a hyperlink to the project's Discord server invite, ensuring easy access for users interested in joining the community. This update maintains consistency with existing style elements, such as badges for other community platforms like Slack. By incorporating the Discord link, this pull request aims to promote community engagement and improve user accessibility within the project.
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="gpt-4-0125-preview"
LLM_API_KEY="XYZ"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
make build
```

## Steps to Reproduce
1. Clone the repository
2. Change into the project directory
3. Run `make build`

## Logs, Error Messages, and Screenshots
```
(base) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ make build
Building project...
Checking Python installation...
Python 3 is already installed. Version: 3.12.1
Checking npm installation...
npm is already installed. Version: 10.5.1
Checking Docker installation...
Docker is already installed. Version: 26.0.0,
Installing Python dependencies...
Poetry is already installed.
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest
The currently activated Python version 3.10.12 is not supported by the project (^3.11).
Trying to find and use a compatible version.
Using python3 (3.12.1)
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: opendevin (0.1.0)
Activating Poetry shell...
Setting up frontend environment...
Detect Node.js version...
Current Node.js version is 18.17.1, corepack is supported.
Installing frontend dependencies with npm...
npm ERR! Cannot read properties of null (reading 'edgesOut')

npm ERR! A complete log of this run can be found in: /home/pierre/.npm/_logs/2024-04-06T19_41_17_476Z-debug-0.log
make: *** [Makefile:38: build] Error 1
```

## Additional Context
- The issue occurs when installing the frontend dependencies with npm.
- The error message indicates that npm is trying to access a property of a null object (`Cannot read properties of null (reading 'edgesOut')`).
- A complete log of this run can be found at `/home/pierre/.npm/_logs/2024-04-06T19_41_17_476Z-debug-0.log`.
- Python 3.12.1, npm 10.5.1, and Docker 26.0.0 are installed.
- The currently activated Python version 3.10.12 is not supported by the project, so Python 3.12.1 is being used instead.

**Comment by enyst** [comment]
Try this:
``` npm i -D styled-components@latest
npm install
make start-backend
make start-frontend```

**Comment by PierrunoYT** [comment]
> Try this:
> 
> ```
> npm i -D styled-components@latest
> npm install
> make start-backend
> make start-frontend```
> ```

I did this as clean install and it's gone. The was some node.js warnings but idk

Here is the English translation:

Alright! Here are all the updated steps to set up OpenDevin in Ubuntu WSL with Python 3.12.1, Docker, and the requirements:

## Prerequisites

1. Make sure that WSL2 is installed on your Windows system. Open PowerShell as an Administrator and run the following command:

```
wsl --install
```

2. Install Docker Desktop for Windows and enable the WSL2 integration in the Docker settings.

## Set up Ubuntu in WSL

1. Open Ubuntu in WSL.

2. Update the package lists and install updates:

```
sudo apt update
sudo apt upgrade
```

3. Install the required packages:

```
sudo apt install git make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl
```

## Install Python 3.12.1

1. Add the Deadsnakes PPA:

```
sudo add-apt-repository ppa:deadsnakes/ppa
```

2. Update the package lists:

```
sudo apt update
```

3. Install Python 3.12.1:

```
sudo apt install python3.12
```

4. Verify the Python version:

```
python3.12 --version
```

5. Install pip for Python 3.12.1:

```
sudo apt install python3.12-distutils
curl https://bootstrap.pypa.io/get-pip.py | python3.12
```

6. Verify the pip version for Python 3.12.1:

```
python3.12 -m pip --version
```

## Install NodeJS and Poetry

1. Install NodeJS 18.17.1 or higher:

```
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt install nodejs
```

2. Install Poetry 1.8 or higher:

```
curl -sSL https://install.python-poetry.org | python3.12 -
```

3. Add the Poetry path to your shell configuration (e.g., ~/.bashrc):

```
export PATH="$HOME/.local/bin:$PATH"
```

4. Reload the shell configuration:

```
source ~/.bashrc
```

## Set up Docker

1. Install Docker:

```
sudo apt install docker.io
```

2. Add your user to the Docker group:

```
sudo usermod -aG docker $USER
```

3. Log out and log back in for the changes to take effect.

## Clone and set up OpenDevin

1. Navigate to the desired directory, e.g.:

```
cd /mnt/c/Users/pierr
```

2. Clone the OpenDevin repository:

```
git clone https://github.com/OpenDevin/OpenDevin.git
```

3. Navigate to the cloned directory:

```
cd OpenDevin
```

4. Build the project and set up the environment:

```
make build
```

5. Configure the desired language model:

```
make setup-config
```

Enter the API key and model name when prompted.

## Start OpenDevin

1. Start OpenDevin:

```
make run
```

This will start both the backend and frontend servers.

2. For help on available commands and targets, use:

```
make help
```

With these updated steps, you should be able to successfully set up and start OpenDevin in Ubuntu WSL with Python 3.12.1, Docker, and all the requirements. Enjoy developing and exploring with OpenDevin!

**Comment by PierrunoYT** [comment]
Some commands did not work right at the start so I need to fix them with the help of AI

**Comment by enyst** [comment]
Good it worked! I'll close this issue then, I'll leave https://github.com/OpenDevin/OpenDevin/issues/834 for a bit to see if the solutions there are helping.
