### ISSUE TITLE
can I download package from my own mirror?

### ISSUE THREAD

**Issue by taozhiyuai** [OpenDevin/OpenDevin#844]
<img width="1026" alt="截屏2024-04-07 14 35 06" src="https://github.com/OpenDevin/OpenDevin/assets/146583103/ed6815c2-0d2b-46b7-a3b5-00eee5cef022">

too many error and too slow.

**Comment by rbren** [comment]
@taozhiyuai I'm not sure what the request is here. It does indeed take a long time to install dependencies. We're working on a Dockerfile.

Feel free to add more info for what you're looking for, but I'm going to close this one as wontfix for now
