### ISSUE TITLE
error when I start opendevin

### ISSUE THREAD

**Issue by taozhiyuai** [OpenDevin/OpenDevin#848]
model in setting is not the one I set.

<img width="1840" alt="截屏2024-04-07 14 55 50" src="https://github.com/OpenDevin/OpenDevin/assets/146583103/58ac3b46-cabd-4c5d-99ec-567dc71a2f35">
<img width="1840" alt="截屏2024-04-07 14 56 21" src="https://github.com/OpenDevin/OpenDevin/assets/146583103/24b78f23-d1fa-4840-b526-a9f930e1a2d6">
<img width="773" alt="截屏2024-04-07 14 56 41" src="https://github.com/OpenDevin/OpenDevin/assets/146583103/45c8b68c-1d5d-40bb-9247-fcf8f9bbcad9">

**Comment by rbren** [comment]
This should be fixed now. If not, feel free to open a new issue with the template filled out
