### ISSUE TITLE
Edit readme to show what the different Agents does

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#853]
**What problem or use case are you trying to solve?**
Edit readme to show what the different Agents does

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**
Edit readme to show what the different Agents does

**Comment by rbren** [comment]
See https://github.com/OpenDevin/OpenDevin/blob/main/docs/documentation/Agents.md

**Comment by rbren** [comment]
Also: https://github.com/OpenDevin/OpenDevin/issues/628
