### ISSUE TITLE
[feature] Edit files directly via frontend

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#855]
**What problem or use case are you trying to solve?**
Option to edit codebase and upload files

**Describe the UX of the solution you'd like**
A Button where you can upload files. A option to load a folder or file to edit it.

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by rbren** [comment]
We're actively working on the file UI--this should be available soon

**Comment by enyst** [comment]
This feature request seems to have two components:
- upload files, which is also the topic of https://github.com/OpenDevin/OpenDevin/issues/1379
- edit files, which I assume means through the code editor interface, and implies saving them via the UI.

I'll rename it for the second so we can keep track of it here. Is this understanding accurate?

**Comment by PierrunoYT** [comment]
Yeah I think this was it.

**Comment by tobitege** [comment]
Fixed with #2646
