### ISSUE TITLE
Option to create and stop new task and make new folder.

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#856]
**What problem or use case are you trying to solve?**
Option to create and stop new task and make new folder.

**Describe the UX of the solution you'd like**
A Button to create a new task and a new folder. A Button to stop the current task.
**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by rbren** [comment]
Deduping with https://github.com/OpenDevin/OpenDevin/issues/470

We also have some plans for multi-project support--stay tuned!
