### ISSUE TITLE
Allow entering text while the agent starts up

### ISSUE THREAD

**Issue by nullnuller** [OpenDevin/OpenDevin#859]
#### Describe the bug

The config file is set (tried different ones, both local and api) but the front-end chat window keeps showing 
```Initializing agent (may take up to 10 seconds)...``` and the textbox to send the message is not responsive (e.g., editable) and text cannot be entered. 
#### Setup and configuration
**Current version**:

```bash
commit e9121b78fed0b5ef36718ca0bf59588c0b094b86 (HEAD -> main, origin/main, origin/HEAD)
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="groq/mixtral-8x7b-32768"
LLM_API_KEY="API_KEY"
LLM_EMBEDDING_MODEL=""
WORKSPACE_DIR="./workspace"

```

**My model and agent** (you can see these settings in the UI):
* Model:mixtral-8x7b-32768
* Agent:groq

**Commands I ran to install and run OpenDevin**:
```
git pull 
make build
make run

```

**Steps to Reproduce**:
1. Open the browser pointing to http://localhost:3001/
2. Try to enter and instruction into the textbox
3.

**Logs, error messages, and screenshots**:

#### Additional Context

![image](https://github.com/OpenDevin/OpenDevin/assets/32858321/1f8ab3d6-6165-4285-8850-0374198430c9)

**Comment by rbren** [comment]
This seems like a regression of https://github.com/OpenDevin/OpenDevin/issues/182
