### ISSUE TITLE
ERROR: Could not open requirements file

### ISSUE THREAD

**Issue by QueRicoChulo** [OpenDevin/OpenDevin#862]
i dont know much about this whole process please accept my appology . all the steps were smooth till this 

PS C:\Users\owner\Desktop\OpenDevin\opendevin> C:\Python312\python -m pip install -r requirements.txt 
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
PS C:\Users\owner\Desktop\OpenDevin\opendevin> 

please bare with me...., can someone please telll me if the file is missing or how to fix this

**Comment by PierrunoYT** [comment]
This is not what is written the Readme. You need to check it again.

**Comment by foragerr** [comment]
This repo uses poetry to manage python requirements/dependencies. You do not need a requirements.txt if you follow the setup instructions in README.md.

However if for some reason you really want requirements.txt, you can generate it with:

```
poetry export --without-hashes --format=requirements.txt > requirements.txt
```
(this obviously assumes you have poetry installed. [See](https://python-poetry.org/docs/#installation).)

**Comment by enyst** [comment]
It can be a bit confusing, because we have multiple README files in subfolders and some talk about pip / requirements.txt.
@QueRicoChulo you normally only need the instructions on the main repo: [README](https://github.com/OpenDevin/OpenDevin)

**Comment by rbren** [comment]
Fixed by https://github.com/OpenDevin/OpenDevin/pull/871
