### ISSUE TITLE
ERROR: Failed to get token: Error: Get token failed..

### ISSUE THREAD

**Issue by dhammavipassi** [OpenDevin/OpenDevin#865]
I think I add the right api, but it doesn't work.

**Comment by foragerr** [comment]
There's no enough detail here to help. Please fill out the bug report template.
https://github.com/OpenDevin/OpenDevin/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by dhammavipassi** [comment]
I fixed the issue, it was caused by a backend port conflict

**Comment by foragerr** [comment]
That's great, please feel free to close this issue.

**Comment by dhammavipassi** [comment]
Fix it
