### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by MohamedAtta-AI** [OpenDevin/OpenDevin#877]
#### Describe the bug
I get this error when I type the command `make build`
![image](https://github.com/OpenDevin/OpenDevin/assets/135552142/e19f7644-dbc4-4ed3-b415-d5e668e7e335)

**Comment by SmartManoj** [comment]
OS?

**Comment by MohamedAtta-AI** [comment]
Windows 11, python 3.11.6

**Comment by SmartManoj** [comment]
Where did you run this?

**Comment by MohamedAtta-AI** [comment]
locally inside the OpenDevin directory
![image](https://github.com/OpenDevin/OpenDevin/assets/135552142/b2246a83-a86e-4c94-8725-8810289c06d1)

**Comment by SmartManoj** [comment]
In WSL terminal?

**Comment by MohamedAtta-AI** [comment]
No, this is VS Code powershell

**Comment by SmartManoj** [comment]
https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by MohamedAtta-AI** [comment]
Okay, I just installed WSL and cloned the repo there. Now, there is this new error here:
```
Building project...
Checking dependencies...
Checking Python installation...
Python 3.11.0 is already installed.
Checking npm installation...
npm 9.8.1 is already installed.
Checking Docker installation...
Docker version 24.0.6, build ed223bc is already installed.
Checking Poetry installation...
Poetry version 1.1.12 is already installed.
Dependencies checked successfully.
Pulling Docker image...
Using default tag: latest
latest: Pulling from opendevin/sandbox
Digest: sha256:486e3da1d7c8ec54a2e3269071eed9b91bc75b82ca5d1ac1760d33883c39e575
Status: Image is up to date for ghcr.io/opendevin/sandbox:latest
ghcr.io/opendevin/sandbox:latest

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/opendevin/sandbox
Docker image pulled successfully.
Installing Python dependencies...

  Stack trace:

  11  /usr/lib/python3/dist-packages/clikit/console_application.py:123 in run
      io = io_factory(

  10  /usr/lib/python3/dist-packages/poetry/console/config/application_config.py:221 in create_io
      resolved_command = application.resolve_command(args)

   9  /usr/lib/python3/dist-packages/clikit/console_application.py:110 in resolve_command
      return self._config.command_resolver.resolve(args, self)

   8  /usr/lib/python3/dist-packages/clikit/resolver/default_resolver.py:34 in resolve
      return self.create_resolved_command(result)

   7  /usr/lib/python3/dist-packages/clikit/resolver/default_resolver.py:166 in create_resolved_command
      if not result.is_parsable():

   6  /usr/lib/python3/dist-packages/clikit/resolver/resolve_result.py:43 in is_parsable
      self._parse()

   5  /usr/lib/python3/dist-packages/clikit/resolver/resolve_result.py:49 in _parse
      self._parsed_args = self._command.parse(self._raw_args)

   4  /usr/lib/python3/dist-packages/clikit/api/command/command.py:113 in parse
      return self._config.args_parser.parse(args, self._args_format, lenient)

   3  /usr/lib/python3/dist-packages/clikit/args/default_args_parser.py:53 in parse
      self._parse(args, _fmt, lenient)

   2  /usr/lib/python3/dist-packages/clikit/args/default_args_parser.py:101 in _parse
      self._parse_long_option(token, tokens, fmt, lenient)

   1  /usr/lib/python3/dist-packages/clikit/args/default_args_parser.py:247 in _parse_long_option
      self._add_long_option(name, None, tokens, fmt, lenient)

  NoSuchOptionException

  The "--without" option does not exist.

  at /usr/lib/python3/dist-packages/clikit/args/default_args_parser.py:300 in _add_long_option
      296│     def _add_long_option(
      297│         self, name, value, tokens, fmt, lenient
      298│     ):  # type: (str, Optional[str], List[str], ArgsFormat, bool) -> None
      299│         if not fmt.has_option(name):
    → 300│             raise NoSuchOptionException(name)
      301│
      302│         option = fmt.get_option(name)
      303│
      304│         if value is False:
make[1]: *** [Makefile:84: install-python-dependencies] Error 1
make: *** [Makefile:25: build] Error 2
```

**Comment by SmartManoj** [comment]
Just run `poetry install --without evaluation`

**Comment by SmartManoj** [comment]
poetry version?
`poetry -V`

**Comment by dorbanianas** [comment]
@MohamedAtta-AI  you are using Poetry version 1.1.12  so try to upgrade your poetry version to version 1.8>=

**Comment by a18792721831** [comment]
@SmartManoj hello, i have this :
<img width="1217" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/45473764/bb62b5bd-2733-4d39-b3d2-12a4244c05f3">
linux ,centos.
i change makefile `@echo "$(BLUE)Usage: make [target]$(RESET)"` to `@echo -e "$(BLUE)Usage: make [target]$(RESET)"`, color is work.
<img width="1216" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/45473764/f7a6923c-1c2f-4371-9c8b-6f896f37571c">
windows is work? no idea.

**Comment by SmartManoj** [comment]
> upgrade your poetry version to version 1.8>=

run this to update poetry
`curl -sSL https://install.python-poetry.org | python3 -`

**Comment by a18792721831** [comment]
> > upgrade your poetry version to version 1.8>=
> 
> @a18792721831 run this to update poetry `curl -sSL https://install.python-poetry.org | python3 -`

<img width="1246" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/45473764/cd8b8f32-d86e-4197-88d1-2cb9971a2f78">
no working

**Comment by dorbanianas** [comment]
Can you pls try these steps and send me the full terminal output:

- pull the latest changes
- and run `make build`

**Comment by a18792721831** [comment]
> Can you pls try these steps and send me the full terminal output:
> 
> * pull the latest changes
> * and run `make build`

`make build` can work, but color :
<img width="850" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/45473764/91c45e30-db99-439d-a132-69b9c1bbb30e">

**Comment by dorbanianas** [comment]
so what's the issue now?

**Comment by a18792721831** [comment]
> so what's the issue now?

new issue , i create now .

**Comment by a18792721831** [comment]
> > so what's the issue now?
> 
> new issue , i create now .

https://github.com/OpenDevin/OpenDevin/issues/893
