### ISSUE TITLE
ERROR: WebSocket connection is not ready

### ISSUE THREAD

**Issue by Sponge-Star** [OpenDevin/OpenDevin#882]
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
INFO:     Started server process [7397]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
Backend started successfully.
Starting frontend with npm...

> opendevin-frontend@0.1.0 start
> vite --port 3001

  VITE v5.2.8  ready in 4152 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
INFO:     ('127.0.0.1', 60770) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiI2ZGQxMjEzYy02YjYwLTQwZGItOTUzNC0wYjEwMjQzZDU5MGEifQ.vJ6B8rbr7kQRlbvfV6JyJCfQd43_oC76z5wxMtUWh-o" [accepted]
Starting loop_recv for sid: 6dd1213c-6b60-40db-9534-0b10243d590a, False
INFO:     connection open
INFO:     127.0.0.1:60938 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     127.0.0.1:60962 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:60954 - "GET /configurations HTTP/1.1" 200 OK
INFO:     127.0.0.1:60970 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 60984) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiI2ZGQxMjEzYy02YjYwLTQwZGItOTUzNC0wYjEwMjQzZDU5MGEifQ.vJ6B8rbr7kQRlbvfV6JyJCfQd43_oC76z5wxMtUWh-o" [accepted]
Starting loop_recv for sid: 6dd1213c-6b60-40db-9534-0b10243d590a, False
INFO:     connection open
INFO:     ('127.0.0.1', 60986) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiI2ZGQxMjEzYy02YjYwLTQwZGItOTUzNC0wYjEwMjQzZDU5MGEifQ.vJ6B8rbr7kQRlbvfV6JyJCfQd43_oC76z5wxMtUWh-o" [accepted]
Starting loop_recv for sid: 6dd1213c-6b60-40db-9534-0b10243d590a, False
INFO:     connection open
INFO:     127.0.0.1:60792 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:60798 - "GET /litellm-agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:60804 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:60816 - "GET /litellm-agents HTTP/1.1" 200 OK
11:52:08 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: 6dd1213c-6b60-40db-9534-0b10243d590a
INFO:     connection closed
INFO:     127.0.0.1:60822 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     127.0.0.1:60838 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:60834 - "GET /configurations HTTP/1.1" 200 OK
INFO:     127.0.0.1:60852 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 60864) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiI2ZGQxMjEzYy02YjYwLTQwZGItOTUzNC0wYjEwMjQzZDU5MGEifQ.vJ6B8rbr7kQRlbvfV6JyJCfQd43_oC76z5wxMtUWh-o" [accepted]
Starting loop_recv for sid: 6dd1213c-6b60-40db-9534-0b10243d590a, False
INFO:     connection open
INFO:     ('127.0.0.1', 60866) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiI2ZGQxMjEzYy02YjYwLTQwZGItOTUzNC0wYjEwMjQzZDU5MGEifQ.vJ6B8rbr7kQRlbvfV6JyJCfQd43_oC76z5wxMtUWh-o" [accepted]
Starting loop_recv for sid: 6dd1213c-6b60-40db-9534-0b10243d590a, False
INFO:     connection open
11:52:10 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: 6dd1213c-6b60-40db-9534-0b10243d590a
INFO:     connection closed
11:52:10 - opendevin:INFO: session.py:38 - WebSocket disconnected, sid: 6dd1213c-6b60-40db-9534-0b10243d590a
INFO:     connection closed

Can open the webpage but continually shows ERROR: WebSocket connection is not ready
![屏幕截图 2024-04-08 115441](https://github.com/OpenDevin/OpenDevin/assets/102195313/53f44603-1a01-4d71-97c1-8c2676220595)

**Comment by SmartManoj** [comment]
browser?
