### ISSUE TITLE
check that the installed OpenDevin pre-requisites are valid

### ISSUE THREAD

**Issue by dorbanianas** [OpenDevin/OpenDevin#886]
**What problem or use case are you trying to solve?**
Ensuring that all installed prerequisites are valid before proceeding with a particular action or process.

- Linked issue: #877

**Comment by Beichen-Ma** [comment]
I would like to try with this. Can you assign this to me? @dorbanianas

**Comment by dorbanianas** [comment]
@Beichen-Ma done!
