### ISSUE TITLE
with Color Escape Sequences in Terminal Output

### ISSUE THREAD

**Issue by a18792721831** [OpenDevin/OpenDevin#893]
#### Describe the bug

1. `git pull` 
2. `make help`

outout:
```
\033[0;34mUsage: make [target]\033[0m
Targets:
  \033[0;32mbuild\033[0m               - Build project, including environment setup and dependencies.
  \033[0;32msetup-config\033[0m        - Setup the configuration for OpenDevin by providing LLM API key,
                        LLM Model name, and workspace directory.
  \033[0;32mstart-backend\033[0m       - Start the backend server for the OpenDevin project.
  \033[0;32mstart-frontend\033[0m      - Start the frontend server for the OpenDevin project.
  \033[0;32mrun\033[0m                 - Run the OpenDevin application, starting both backend and frontend servers.
                        Backend Log file will be stored in the 'logs' directory.
  \033[0;32mhelp\033[0m                - Display this help message, providing information on available targets.
```
#### Setup and configuration
**Current version**:

```bash
cc6626ff0da9f3c146e88c179f1e1432b9d60550
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
```

**Steps to Reproduce**:
1.
4.
5.

**Logs, error messages, and screenshots**:
<img width="1210" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/45473764/b163c7e6-066f-4ad8-b29c-269cad28eaf5">

#### Additional Context
1. i try `curl -sSL https://install.python-poetry.org | python3 -` , not work.
2. replace `@echo "$(BLUE)Usage: make [target]$(RESET)"`to `@echo -e "$(BLUE)Usage: make [target]$(RESET)"`,worked.
  maybe `@echo` with ` -e` ?

**Comment by dorbanianas** [comment]
so basically the issue is with the makefile output?

**Comment by a18792721831** [comment]
> so basically the issue is with the makefile output?

right.

**Comment by dorbanianas** [comment]
sure I'll check that

**Comment by foragerr** [comment]
I suppose not all shells support color output, I wonder if you'll need a --no-color flag @dorbanianas

**Comment by maxyz** [comment]
It seems to me that the echo calls need to be replaced by echo -e, so it processes the escape chars. I wonder if there is a difference in the "layer" that's processing the escape chars for you.
