### ISSUE TITLE
NoSuchOptionException

### ISSUE THREAD

**Issue by SpringBootReactTypescriptTailwindMaster** [OpenDevin/OpenDevin#896]
Hi, i try to make build the project but it doesnt work, my poetry version is 1.8.2 and i dont think i missed something 
![Capture](https://github.com/OpenDevin/OpenDevin/assets/154255969/a37411f6-9e9f-430b-9797-d20e496acc77)

**Comment by rbren** [comment]
This thread suggests you need to restart your WSL terminal: https://github.com/orgs/python-poetry/discussions/8686

If the problem persists, feel free to open a new issue with the template filled out.
