### ISSUE TITLE
make run error

### ISSUE THREAD

**Issue by timucindusunur** [OpenDevin/OpenDevin#898]
(OpenDevin) timuc@DESKTOP-1TC1K9D:~/OpenDevin$ make run
Running the app...
Starting backend server...
Waiting for the backend to start...
/home/timuc/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/timuc/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/timuc/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_group_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/timuc/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/timuc/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
INFO:     Started server process [73716]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
Backend started successfully.
Starting frontend with npm...

> opendevin-frontend@0.1.0 start
> vite --port 3001

  VITE v5.2.8  ready in 621 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
INFO:     127.0.0.1:51594 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     127.0.0.1:51624 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:51610 - "GET /configurations HTTP/1.1" 200 OK
INFO:     127.0.0.1:51628 - "GET /refresh-files HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 51632) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIzYmQ1M2VjMC0xNmI4LTQzN2EtYWYzZC0zZGRkMDI1OGRlOWEifQ.lDBqVOFNUIhJ6EBTFkNA3ZTUXHtsJG_8BZTVhHf9Vpk" [accepted]
Starting loop_recv for sid: 3bd53ec0-16b8-437a-af3d-3ddd0258de9a, False
INFO:     connection open
14:12:39 - opendevin:INFO: sandbox.py:118 - Using workspace directory: /home/timuc/OpenDevin/work
14:12:42 - opendevin:ERROR: manager.py:134 - Error creating controller.
Traceback (most recent call last):
  File "/home/timuc/OpenDevin/opendevin/server/agent/manager.py", line 125, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/timuc/OpenDevin/opendevin/controller/agent_controller.py", line 86, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/timuc/OpenDevin/opendevin/controller/command_manager.py", line 14, in __init__
    self.shell = DockerInteractive(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/timuc/OpenDevin/opendevin/sandbox/sandbox.py", line 139, in __init__
    self.start_ssh_session()
  File "/home/timuc/OpenDevin/opendevin/sandbox/sandbox.py", line 167, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=2222)
  File "/home/timuc/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.11/site-packages/pexpect/pxssh.py", line 440, in login
    raise ExceptionPxssh('password refused')
pexpect.pxssh.ExceptionPxssh: password refused
INFO:     127.0.0.1:44376 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:44382 - "GET /litellm-agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:44388 - "GET /litellm-models HTTP/1.1" 200 OK
INFO:     127.0.0.1:44396 - "GET /litellm-agents HTTP/1.1" 200 OK
14:13:01 - opendevin:INFO: sandbox.py:118 - Using workspace directory: /home/timuc/OpenDevin/work
14:13:05 - opendevin:ERROR: manager.py:134 - Error creating controller.
Traceback (most recent call last):
  File "/home/timuc/OpenDevin/opendevin/server/agent/manager.py", line 125, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/home/timuc/OpenDevin/opendevin/controller/agent_controller.py", line 86, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/home/timuc/OpenDevin/opendevin/controller/command_manager.py", line 14, in __init__
    self.shell = DockerInteractive(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/timuc/OpenDevin/opendevin/sandbox/sandbox.py", line 139, in __init__
    self.start_ssh_session()
  File "/home/timuc/OpenDevin/opendevin/sandbox/sandbox.py", line 167, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=2222)
  File "/home/timuc/.local/share/virtualenvs/OpenDevin-vZQ1SGmD/lib/python3.11/site-packages/pexpect/pxssh.py", line 440, in login
    raise ExceptionPxssh('password refused')
pexpect.pxssh.ExceptionPxssh: password refused

there is a problem

**Comment by enyst** [comment]
What operating system are you running?

It looks like a Linux, but it would be good to confirm.

Also please tell what git commit you're running on. It can help to git pull, to make sure it's the latest hotfix.

**Comment by hongdongyue2012** [comment]
Same for me. It looks like **self._ssh_password** is a random uuid
```
   
       self._ssh_password = str(uuid.uuid4())
        .....
        .....
    def start_ssh_session(self):
        # start ssh session at the background
        self.ssh = pxssh.pxssh()
        hostname = 'localhost'
        username = 'opendevin'
        self.ssh.login(hostname, username, self._ssh_password, port=2222)

        # Fix: https://github.com/pexpect/pexpect/issues/669
        self.ssh.sendline("bind 'set enable-bracketed-paste off'")
        self.ssh.prompt()
        # cd to workspace
        self.ssh.sendline('cd /workspace')
        self.ssh.prompt()
```

**Comment by timucindusunur** [comment]
![Ekran görüntüsü 2024-04-08 155814](https://github.com/OpenDevin/OpenDevin/assets/40573794/2034f309-6651-48a7-bb49-8333ca68604d)

operating system linux ubuntu

**Comment by JustinLin610** [comment]
this is a similar issue to the previous one. try the latest code with this pr https://github.com/OpenDevin/OpenDevin/pull/891 . and remember to restart the docker container.

**Comment by timucindusunur** [comment]
Which one?

**Comment by timucindusunur** [comment]
![Ekran görüntüsü 2024-04-08 175103](https://github.com/OpenDevin/OpenDevin/assets/40573794/e1a7f680-002c-40e7-9792-7842c63b5b59)

**Comment by dorbanianas** [comment]
@timucindusunur Fixed by : #941 you can now pull the latest changes!

**Comment by DXLgpt** [comment]
I having the same issue, with #941 
WSL2+ubuntu 

05:51:11 - opendevin:ERROR: manager.py:134 - Error creating controller.
Traceback (most recent call last):
  File "/mnt/f/1Coding/OpenDevin/opendevin/server/agent/manager.py", line 125, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/mnt/f/1Coding/OpenDevin/opendevin/controller/agent_controller.py", line 86, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/mnt/f/1Coding/OpenDevin/opendevin/controller/command_manager.py", line 14, in __init__
    self.shell = DockerInteractive(
                 ^^^^^^^^^^^^^^^^^^
  File "/mnt/f/1Coding/OpenDevin/opendevin/sandbox/sandbox.py", line 139, in __init__
    self.start_ssh_session()
  File "/mnt/f/1Coding/OpenDevin/opendevin/sandbox/sandbox.py", line 213, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=2222)
  File "/home/dxliu/.cache/pypoetry/virtualenvs/opendevin-8axCXPJN-py3.11/lib/python3.11/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host

**Comment by dorbanianas** [comment]
try to remove the docker container and rebuild `make build`
