### ISSUE TITLE
We'd like to support this project

### ISSUE THREAD

**Issue by forrestchang** [OpenDevin/OpenDevin#9]
We are a startup focused on developing innovative tools. Currently, we are in the process of creating an AI-powered search engine specifically designed for developers, accessible at https://devv.ai/.

We are interested in sponsoring this project and are open to including the token usage of models from OpenAI, Anthropic, Gemini, or others. Additionally, we can offer our search index infrastructure to significantly enhance the development of OpenDevin.

Please feel free to reach out to me at jiayuan@devv.ai to discuss further details.

**Comment by JustinLin610** [comment]
Feel free to fill in the form in the readme and join in our slack! Many thanks for your kindness!

**Comment by JustinLin610** [comment]
I'll just close this and we can turn our discussion to the slack channel
