### ISSUE TITLE
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host

### ISSUE THREAD

**Issue by Haywardchan** [OpenDevin/OpenDevin#902]
#### Describe the bug
After running 'make run' in the console and changing configType.RUN_AS_DEVIN to be true, the connection fails and Devin agents cannot be initialized
#### Setup and configuration
**Current version**:
```bash
commit 6e566dd21dc4f93475fd5b8e601d301226a12f2f (HEAD -> main, origin/main, origin/HEAD)
Author: Yufan Song <33971064+yufansong@users.noreply.github.com>
Date:   Mon Apr 8 02:23:25 2024 -0700

    fix: change default RUN_AS_DEVIN to true and change some network setting (#895)

    * fix use devin

    * fix port problem
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="gpt-3.5-turbo-1106"
LLM_API_KEY="<Redacted>"
LLM_EMBEDDING_MODEL=""
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model: NA
* Agent: NA
* Yet to load as it is stuck in the initializing agent stage

**Commands I ran to install and run OpenDevin**:
```
> Installing Python 3.11, and other requirements using windows WSL2
make build
make run
```

**Steps to Reproduce**:
1. make build
2. make run

**Logs, error messages, and screenshots**:

#### Additional Context

File "/mnt/../opendevin/server/agent/manager.py", line 125, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/mnt/../opendevin/controller/agent_controller.py", line 86, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/mnt/../OpenDevin/opendevin/controller/command_manager.py", line 14, in __init__
    self.shell = DockerInteractive(
                 ^^^^^^^^^^^^^^^^^^
  File "/mnt/../OpenDevin/opendevin/sandbox/sandbox.py", line 139, in __init__
    self.start_ssh_session()
  File "/mnt/../opendevin/sandbox/sandbox.py", line 167, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=2222)
  File "/home/user/.cache/pypoetry/virtualenvs/opendevin-RHnpmKt7-py3.11/lib/python3.11/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host

**Comment by JustinLin610** [comment]
you need to restart your container for that.

btw the very recent pr https://github.com/OpenDevin/OpenDevin/pull/891 solved this problem also.

**Comment by Haywardchan** [comment]
I have restarted the docker container using the docker restart <container> command, but it still does not work on my side. Do we have to change network_mode='host' or any other network settings?

**Comment by denggeng** [comment]
I have the same issue。Mac M1.
I find that the SSH server did not start successfully, because the port 2222 have no server listened.

**Comment by rbren** [comment]
Closing in favor of https://github.com/OpenDevin/OpenDevin/issues/889

**Comment by hungson175** [comment]
> Closing in favor of #889

Hi, @rbren - I have followed your link to #889 - but I don't see any solution - only a link this this problem #902 . Have I missed something ? I have the same problem on Ubuntu 22.04 machines (I tried both PCs at work & and at home)
The log is similar:

`10:05:46 - opendevin:INFO: ssh_box.py:309 - Container started
10:05:47 - opendevin:INFO: ssh_box.py:326 - waiting for container to start: 1, container status: running
10:05:47 - opendevin:INFO: ssh_box.py:161 - Connecting to root@host.docker.internal via ssh. If you encounter any issues, you can try `ssh -v -p 38873 root@host.docker.internal` with the password '558203f6-353e-45d1-88d4-521a788e9db1' and report the issue on GitHub.
10:05:47 - opendevin:ERROR: agent.py:123 - Error creating controller: Could not establish connection to host
Traceback (most recent call last):
  File "/app/opendevin/server/agent/agent.py", line 114, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/agent_controller.py", line 47, in __init__
    self.action_manager = ActionManager(self.id, container_image)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/controller/action_manager.py", line 36, in __init__
    self.shell = DockerSSHBox(
                 ^^^^^^^^^^^^^
  File "/app/opendevin/sandbox/ssh_box.py", line 90, in __init__
    self.start_ssh_session()
  File "/app/opendevin/sandbox/ssh_box.py", line 164, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password,
  File "/app/.venv/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host`

Tks for supporting

**Comment by enyst** [comment]
@hungson175 Please try adding to config.toml: SANDBOX_TYPE=exec

**Comment by rbren** [comment]
Sorry, new canonical issue is here: https://github.com/OpenDevin/OpenDevin/issues/1156

**Comment by h2oicsaba** [comment]
same error on Ubuntu 22.04 but before this error i also added 
127.0.0.1       host.docker.internal
in the hosts file because the docker desktop install only ads 
127.0.0.1   kubernetes.docker.internal 
to this file
