### ISSUE TITLE
make run causes error: `nc: not found`

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#905]
#### Describe the bug

When running `make run` (on a recent Ubuntu) , I get `nc not round`

Solution is `sudo apt install netcat`. But it'd be nice if we don't rely on `nc`, or maybe warn the user and tell them to install it.

#### Setup and configuration
**Current version**:

```bash
❯ git log -n1
commit 6f795f5e9c64e42b5577c2270cbf10d8dee593d9 (HEAD -> main)
Author: Akki <akhilvc10@gmail.com>
Date:   Mon Apr 8 18:32:45 2024 +0400

```

**Commands I ran to install and run OpenDevin**:
```
make build
make setup-config
make run
```

**Steps to Reproduce**:
1. Do the above on the `ubuntu:latest` docker image, with the right node and python installed
2.
3.

**Logs, error messages, and screenshots**:

```
❯ make run
Running the app...
Starting backend server...
Waiting for the backend to start...
/bin/sh: 1: nc: not found
/bin/sh: 1: nc: not found
/bin/sh: 1: nc: not found
/bin/sh: 1: nc: not found
/bin/sh: 1: nc: not found
/bin/sh: 1: nc: not found
/bin/sh: 1: nc: not found
/bin/sh: 1: nc: not found
/bin/sh: 1: nc: not found
/bin/sh: 1: nc: not found
...
```

**Comment by userandpass** [comment]
sudo yum install nc
