### ISSUE TITLE
`make run` acts successful when the server fails to bind to the port

### ISSUE THREAD

**Issue by rbren** [OpenDevin/OpenDevin#907]
#### Describe the bug

If port 3000 is taken, `make run` seems to complete successfully, rather than exiting and telling the user what went wrong

Also notice that vite falls back to 3002 instead of 3001, which I believe breaks everything.

#### Setup and configuration
**Current version**:

```bash
❯ git log -n1
commit 6f795f5e9c64e42b5577c2270cbf10d8dee593d9 (HEAD -> main)
Author: Akki <akhilvc10@gmail.com>
Date:   Mon Apr 8 18:32:45 2024 +0400
```

**Commands I ran to install and run OpenDevin**:
```
make build
make setup-config
make run
```

**Steps to Reproduce**:
1. Start the backend on port 3000, or run some other app on 3000
2. run `make run`
3.

**Logs, error messages, and screenshots**:

```bash
❯ make run
Running the app...
Starting backend server...
Waiting for the backend to start...
Backend started successfully.
Starting frontend with npm...

> opendevin-frontend@0.1.0 start
> vite --port 3001

Port 3001 is in use, trying another one...

  VITE v5.2.8  ready in 508 ms

  ➜  Local:   http://localhost:3002/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
/home/rbren/.local/share/virtualenvs/opendevin-0fQgowZe/lib/python3.12/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/rbren/.local/share/virtualenvs/opendevin-0fQgowZe/lib/python3.12/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/rbren/.local/share/virtualenvs/opendevin-0fQgowZe/lib/python3.12/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_group_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/rbren/.local/share/virtualenvs/opendevin-0fQgowZe/lib/python3.12/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/rbren/.local/share/virtualenvs/opendevin-0fQgowZe/lib/python3.12/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
INFO:     Started server process [1280354]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('127.0.0.1', 3000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.


^Cmake: *** [Makefile:128: run] Interrupt

```

**Comment by Pengymd** [comment]
I don't know if it can help .  But when i do Make build
At the end i get :

Installing the current project: opendevin (0.1.0)
Python dependencies installed successfully.
Setting up frontend environment...
Detect Node.js version...
/bin/sh: 1: node: not found
make[1]: *** [Makefile:94: install-frontend-dependencies] Error 127
make: *** [Makefile:26: build] Error 2

After if i Make run,


Running the app...
Starting backend server...
Waiting for the backend to start...
Backend started successfully.
Starting frontend with npm...

> opendevin-frontend@0.1.0 start
> vite --port 3001

'vite' is not recognized as an internal or external command,
operable program or batch file.
make: *** [Makefile:128: run] Error 1
unixjas@DESKTOP-FPD4J66:/mnt/c/Opendevin/OpenDevin$ /home/unixjas/.cache/pypoetry/virtualenvs/opendevin-wWEJnBUH-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/unixjas/.cache/pypoetry/virtualenvs/opendevin-wWEJnBUH-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/unixjas/.cache/pypoetry/virtualenvs/opendevin-wWEJnBUH-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_group_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/unixjas/.cache/pypoetry/virtualenvs/opendevin-wWEJnBUH-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/unixjas/.cache/pypoetry/virtualenvs/opendevin-wWEJnBUH-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
INFO:     Started server process [15254]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('127.0.0.1', 3000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.

**Comment by Pengymd** [comment]
On reddit i followed instruction to installed node 
Installing Node.js 20.12.1 with nvm
Install cURL:

sudo apt-get install curl


Download and run the nvm installation script:

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash


Close and reopen your terminal.

Verify the nvm installation:

command -v nvm


Install Node.js 20.12.1:

nvm install 20.12.1


Set Node.js 20.12.1 as the default version:

nvm alias default 20.12.1


Verify the Node.js and npm versions:

node -v
npm -v

Make build doesnt do the error anymore :
Detect Node.js version...
/bin/sh: 1: node: not found
make[1]: *** [Makefile:94: install-frontend-dependencies] Error 127
make: *** [Makefile:26: build] Error 2

And when i make run,
It does the same error 
ERROR: [Errno 98] error while attempting to bind on address ('127.0.0.1', 3000): address already in use
And on the web page its does the failed connection endlessly.

If it doesnt help, forget about my comment!

**Comment by rbren** [comment]
Not really much of an issue now that we have docker

**Comment by SmartManoj** [comment]
Command to kill those processes.
```bash
sudo kill -9 $(sudo lsof -t -i:3000)
sudo kill -9 $(sudo lsof -t -i:3001)
```
