### ISSUE TITLE
Code Editor height too large

### ISSUE THREAD

**Issue by iFurySt** [OpenDevin/OpenDevin#914]
<img width="1766" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/16201837/d7f32971-0ae8-476c-b354-c44af4ba4647">

i have no idea what to fix for now. does anyone have time to take a look?

**Comment by Sparkier** [comment]
Can you describe how to replicate this? I don't seem to have the same issue.

**Comment by iFurySt** [comment]
when the chat window has enough messages to trigger the scroll

**Comment by iFurySt** [comment]
<img width="1579" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/16201837/917b006a-1900-4f1b-9cec-75a7defa527a">

@Sparkier it seems doesn't be fixed. 😅
