### ISSUE TITLE
ERROR: Failed to get token: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON.

### ISSUE THREAD

**Issue by AlexLisong** [OpenDevin/OpenDevin#915]
Started the front end after make run, and I got this pop up error message:
ERROR: Failed to get token: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON.
[
![Screenshot from 2024-04-08 09-11-35](https://github.com/OpenDevin/OpenDevin/assets/5325037/e83b0158-2581-431f-9cb3-fb952e85b1fd)
](url)

**Comment by rbren** [comment]
Seems like your backend server isn't listening. I'd check the logs from `make run` for errors--probably there's something else listening on port 3000 and responding with HTML

Going to close this, but if that doesn't solve your problem, feel free to open a new issue with the template filled out
