### ISSUE TITLE
An error occurs when trying to establish an SSH connection to the sandbox environment while running make run, preventing the creation of the AgentController.

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#916]
## Bug Description
An error occurs when trying to establish an SSH connection to the sandbox environment while running `make run`, preventing the creation of the AgentController.

## Setup and Configuration
**Current Version**:

```bash
01c4c4bee4b5d8dc227e3432f585229a7c9d7126 (HEAD -> main, origin/main, origin/HEAD)
Author: ITNerdAZ <158104716+ITNerdAZ@users.noreply.github.com>
Date:   Mon Apr 8 14:56:02 2024 +0000

    Add installation warning to readme (#883)

    * Update README

    * Update README.md

    ---------

    Co-authored-by: Robert Brennan <accounts@rbren.io>
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="gpt-4-0125-preview"
LLM_API_KEY="XYZ"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model:
* Agent:

**Commands I ran to install and run OpenDevin**:
```
make run
```

## Steps to Reproduce
1. Clone the repository
2. Change into the project directory
3. Run `make run`

## Logs, Error Messages, and Screenshots
```
18:19:42 - opendevin:INFO: sandbox.py:210 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 2222 opendevin@localhost` with the password '9e5c46b1-856b-42f1-ac09-3240398b8d40' and report the issue on GitHub.
18:19:43 - opendevin:ERROR: manager.py:134 - Error creating controller.
Traceback (most recent call last):
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/server/agent/manager.py", line 125, in create_controller
    self.controller = AgentController(
                      ^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/controller/agent_controller.py", line 86, in __init__
    self.command_manager = CommandManager(
                           ^^^^^^^^^^^^^^^
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/controller/command_manager.py", line 14, in __init__
    self.shell = DockerInteractive(
                 ^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/sandbox/sandbox.py", line 139, in __init__
    self.start_ssh_session()
  File "/mnt/c/Users/pierr/OpenDevin/opendevin/sandbox/sandbox.py", line 213, in start_ssh_session
    self.ssh.login(hostname, username, self._ssh_password, port=2222)
  File "/home/pierre/.cache/pypoetry/virtualenvs/opendevin-lPNnzAY--py3.12/lib/python3.12/site-packages/pexpect/pxssh.py", line 424, in login
    raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
```

## Additional Context
- The error occurs when running `make run`, which attempts to establish an SSH connection to `opendevin@localhost` on port 2222.
- The password for the SSH connection is provided in the log message: `9e5c46b1-856b-42f1-ac09-3240398b8d40`.
- The error is raised by the `pexpect.pxssh` library, indicating that it could not establish a connection to the host.
- The error propagates through the `DockerInteractive`, `CommandManager`, and `AgentController` classes, ultimately preventing the creation of the controller.
- The issue seems to be related to the SSH connection setup and configuration within the OpenDevin sandbox environment when running the application using `make run`.

**Comment by rbren** [comment]
Deduping in favor of https://github.com/OpenDevin/OpenDevin/issues/911
