### ISSUE TITLE
make run stuck on dependecies

### ISSUE THREAD

**Issue by nowheel** [OpenDevin/OpenDevin#919]
installation stuck on dependencies. debian server.

**Logs:**
```
Package operations: 210 installs, 1 update, 0 removals

  - Installing certifi (2024.2.2): Pending...
  - Installing h11 (0.14.0): Pending...
  - Installing idna (3.6): Pending...
  - Installing sniffio (1.3.1): Pending...
  - Installing typing-extensions (4.11.0): Pending...
```

**Comment by enyst** [comment]
I'm not sure why it'd do that. 😔 
Did you clone and run make build, or something else?

**Comment by enyst** [comment]
Same as here: https://github.com/OpenDevin/OpenDevin/issues/935

That was solved by updating poetry.

**Comment by enyst** [comment]
I'll close this issue, but if you still experience problems please open a new one.

**Comment by dorbanianas** [comment]
@zingshowba try `poetry env remove python3.11` and after `make build`

**Comment by dorbanianas** [comment]
@zingshowba Enjoy!!
