### ISSUE TITLE
Agent selector dropdown does not work

### ISSUE THREAD

**Issue by JayQuimby** [OpenDevin/OpenDevin#929]
#### Describe the bug

I am trying to use an agent other than the monologue agent but no matter what I select it always uses monologue agent
#### Setup and configuration
WSL2 Ubuntu

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="ollama/codellama"
LLM_API_KEY="ollama"
LLM_EMBEDDING_MODEL="llama2"
LLM_BASE_URL="http://localhost:11434"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model: llama2
* Agent: all of them

**Commands I ran to install and run OpenDevin**:
```
make build
make run
```

**Steps to Reproduce**:
1. open frontend in browser
2. switch agents
3. the switcher will work and say that it has switched but when I make an error intentionally I can see it is the monologue agent being prompted no matter what I switch it to.

**Logs, error messages, and screenshots**:
![image](https://github.com/OpenDevin/OpenDevin/assets/76570167/5276ca30-88bc-4bb9-9672-bdf8a36ded21)
![image](https://github.com/OpenDevin/OpenDevin/assets/76570167/775b7679-6118-4919-908a-a3858458be03)

As you can see, I am using the codeactagent according to the FE, but the call is made to monologue agent on the BE

I have tried restarting the BE with the FE still running and the settings set to codeactagent, but even on restart it still uses monologue agent. I think it got hard coded somewhere, just not sure where.

EDIT:
Setting the Agent using config.toml works, but the frontend still does not work.

**Comment by yimothysu** [comment]
@JayQuimby I can't reproduce. Can you add a debugging print statement `print(agent_cls)` after the line `agent_cls = self.get_arg_or_default(args, ConfigType.AGENT)` in `manager.py`?

On my machine, it displays the correct agent when I switch between Monologue and CodeAct.

**Comment by JayQuimby** [comment]
@yimothysu Seems to be working now for me too! Not sure what happened...
