### ISSUE TITLE
make build on ubuntu 22.04

### ISSUE THREAD

**Issue by fournicknet** [OpenDevin/OpenDevin#930]
#### Describe the bug
When I run 'make build' I get the following output

Building project...
Checking dependencies...
Checking Python installation...
Python 3.10.12 is already installed.
Checking npm installation...
npm 10.5.0 is already installed.
Checking Docker installation...
Docker version 26.0.0, build 2ae903e is already installed.
Checking Poetry installation...
Poetry (version 1.8.2) is already installed.
Dependencies checked successfully.
Pulling Docker image...
Using default tag: latest
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/images/create?fromImage=ghcr.io%2Fopendevin%2Fsandbox&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
make[1]: *** [Makefile:78: pull-docker-image] Error 1
make: *** [Makefile:24: build] Error 2

I havn't been able to progress to creating the config file
**My config.toml and environment vars** (be sure to redact API keys):
```toml
```

**Steps to Reproduce**:
1. install ubuntu 22.04
2. install the packages from the OpenDevin Page that are required
3. download the git for OpenDevin...

**Comment by nullnuller** [comment]
Same here.
![image](https://github.com/OpenDevin/OpenDevin/assets/32858321/16d2c78f-456e-40ed-8ba8-7bbfd7b7354e)

**Comment by RipleyMaoyu** [comment]
Try running the backend and frontend seperately. Worked for me to some degree. Run backend first, then frontend

**Comment by nullnuller** [comment]
> Try running the backend and frontend seperately. Worked for me to some degree. Run backend first, then frontend

It's happening for ```make build``` so cannot run.

**Comment by nullnuller** [comment]
> > Try running the backend and frontend seperately. Worked for me to some degree. Run backend first, then frontend
> 
> `` It's happening for ```make build``` so cannot run. ``

I have been able to resolve this by deleting the previous docker image and make build

**Comment by fournicknet** [comment]
I was able to resolve the issue by adding the docker to sudo group and running docker without sudo. https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue   closing issue
