### ISSUE TITLE
Getting started instructions unclear

### ISSUE THREAD

**Issue by MightEnlightenYou** [OpenDevin/OpenDevin#937]
The installation instructions are unclear for regular users who might not be familiar with all the concepts and tools/procedures for getting started.

You can reproduce the issue by simply doing a clean install of OpenDevin and following the instructions **exactly** as they are in the Readme and you'll see that doing a "make build" doesn't do anything if you don't know to git clone first and that you should cd to the repo in CLI and make build there and so on.

The fix is to write installation instructions that take the install through **every step** for a clean install. One per OS is advisable.

**Comment by cntyt** [comment]
Please improve the relevant help documentation, which is important for beginners.

**Comment by foragerr** [comment]
If you're using OpenAI, you could give this a try: https://github.com/OpenDevin/OpenDevin/issues/110#issuecomment-2043631744

**Comment by rbren** [comment]
This should be much easier once we have docker set up. Closing in favor of https://github.com/OpenDevin/OpenDevin/issues/110
