### ISSUE TITLE
Exceeded quota error when running the app

### ISSUE THREAD

**Issue by AndyPelaez** [OpenDevin/OpenDevin#945]
#### Describe the bug
I already configured the app as the README reads. I used gpt-3.5-turbo and openai. I also added an api key obtained from https://platform.openai.com/api-keys, but an error is received:

```
Oops. Something went wrong: OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
```

#### Setup and configuration
**Current version**:

```bash
main branch
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="gpt-3.5-turbo-1106"
LLM_API_KEY="xxxxxx"
LLM_EMBEDDING_MODEL="openai"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model: gpt-3.5-turbo-1106
* Agent:  MonologueAgent

**Commands I ran to install and run OpenDevin**:
```
make build
make setup-config
make run
```

**Steps to Reproduce**:
1.Install a normally 
2. Run the app

**Logs, error messages, and screenshots**:

**Comment by dorbanianas** [comment]
I guess you should pay your openai api

**Comment by divyakr-06** [comment]
Hi @dorbanianas, wondering can't we use free account to try this out (since Model: gpt-3.5-turbo-1106 comes for free)?

**Comment by nickjuntilla** [comment]
I pay. It still doesn't work.

**Comment by enyst** [comment]
@nickjuntilla Please open a new issue if you haven't yet, and tell us details about what happens, so we can figure it out.

**Comment by tobitege** [comment]
As of January 2024:
https://platform.openai.com/docs/guides/rate-limits
