### ISSUE TITLE
This error still persists

### ISSUE THREAD

**Issue by timucindusunur** [OpenDevin/OpenDevin#950]
/home/timuc/.cache/pypoetry/virtualenvs/opendevin-nbEpGqxf-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/timuc/.cache/pypoetry/virtualenvs/opendevin-nbEpGqxf-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/timuc/.cache/pypoetry/virtualenvs/opendevin-nbEpGqxf-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_group_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/timuc/.cache/pypoetry/virtualenvs/opendevin-nbEpGqxf-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/timuc/.cache/pypoetry/virtualenvs/opendevin-nbEpGqxf-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(

**Comment by enyst** [comment]
This is a warning, not an error, so things work otherwise. It looks worrying though, you're right, but it will disappear when liteLLM is updated, and we include the update in the project.

I'll close this issue, but please note that it's tracked and it will vanish soon.
