### ISSUE TITLE
update of #919, stuck on dependencies

### ISSUE THREAD

**Issue by nowheel** [OpenDevin/OpenDevin#953]
Read the original ticket here: #919 

updated Poetry.

```
/Scaricati/OpenDevin$ uname -v
#1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01)
/Scaricati/OpenDevin$ poetry --version
Poetry (version 1.8.2)


/.........................................../


Package operations: 210 installs, 1 update, 0 removals

  - Installing certifi (2024.2.2): Pending...
  - Installing h11 (0.14.0): Pending...
  - Installing idna (3.6): Pending...
  - Installing sniffio (1.3.1): Pending...
  - Installing typing-extensions (4.11.0): Pending...
```

this night i format the server, repeat all step and tomorrow i write if successful or  not.

Sorry for my eng, i don't study it, i learn it from various computer guide.

**Comment by rbren** [comment]
@nowheel I'm not really sure what the issue is here. Can you explain more?

Did running `poetry --version` cause those `Installing` commands? Or is there a command missing?

**Comment by nowheel** [comment]
After reinstall Debian Os, no problem to build. thank you. but i don't know want i wrong. it's same step of last installation, and the last installation are cleaner same this.
