### ISSUE TITLE
You close the topics before the problems are solved??

### ISSUE THREAD

**Issue by timucindusunur** [OpenDevin/OpenDevin#955]
.

**Comment by foragerr** [comment]
Because the issues you raise do not have enough detail to actually help. Including this one.
Please use the [bug report template](https://github.com/OpenDevin/OpenDevin/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) when raising the issue, so someone can actually help.

**Comment by rbren** [comment]
@timucindusunur we get a lot of issues, and it's hard to stay on top of them. If users don't provide enough information for us to debug, we can't help.

As foragerr points out, if you fill out the template we will do our best to help.

Please remember that we're a team of volunteers, working for free.
