### ISSUE TITLE
Create LangGraph Agent

### ISSUE THREAD

**Issue by moresearch** [OpenDevin/OpenDevin#96]
**What problem or use case are you trying to solve?**
OpenDevin requires an Agent implementation and LangGraph seems to be a good candidate.
 
**Describe the UX of the solution you'd like**
N\A

**Do you have thoughts on the technical implementation?**
- https://arxiv.org/pdf/2310.04406.pdf
- https://github.com/langchain-ai/langgraph/blob/main/examples/lats/lats.ipynb

**Describe alternatives you've considered**
LATS paper seems to be SOTA considering other alternatives. 

**Additional context**

**Comment by xingyaoww** [comment]
Looks great!! If interested, feel free to send PR to implement this under the [agenthub](https://github.com/OpenDevin/OpenDevin/tree/main/agenthub) :)

**Comment by neubig** [comment]
Since nobody has expressed interest in doing this, and I don't think it's super-high-priority at the moment I'll close this issue, but we always accept contributions of new agents!
