### ISSUE TITLE
Add to readme: do not use root

### ISSUE THREAD

**Issue by kroggen** [OpenDevin/OpenDevin#961]
Add to somewhere on the readme that installation as `root` is not supported

**Comment by yufansong** [comment]
What do you mean `installation as root is not supported `? You mean agent cannot run as root in sandbox or you cannot install opendevin as root? Can you elaborate more details?

**Comment by rbren** [comment]
Going to close this one--not entirely clear what the issue is, and hopefully `docker run` makes it easier

**Comment by kroggen** [comment]
It is not possible to run OpenDevin as root.

Check #969 and #887
