### ISSUE TITLE
Cache locally BAAI/bge-small-en-v1.5 json

### ISSUE THREAD

**Issue by enyst** [OpenDevin/OpenDevin#964]
**Summary**
Cache locally that file. It's normally downloaded from Hugging Face, but we have multiple reports of the download being flaky or impossible.
Fixes issues like https://github.com/OpenDevin/OpenDevin/issues/939

**Motivation**
There are scenarios where users cannot download from HF, like corporate environments or other IP blocks.
I believe it's used for embeddings and missing it currently breaks opendevin.

**Technical Design**
- save it locally, in the cache folder
- fallback to it
- I don't know much about it, so for the rest some investigation needed. 😅 

**Alternatives to Consider**
- a mirror?
- a different default accessible differently, like github?
They might have the same issue.

**Comment by rbren** [comment]
I believe this is now solved by running `download.py` during the docker build
