### ISSUE TITLE
when i use Azure OpenAI to run open devin, i run into this error

### ISSUE THREAD

**Issue by LeoYoungChina** [OpenDevin/OpenDevin#968]
the error is :
![1](https://github.com/OpenDevin/OpenDevin/assets/15046431/474a3d04-7819-4e65-91c5-e00025e1c43b)
 
the config.toml file is :

![2](https://github.com/OpenDevin/OpenDevin/assets/15046431/c8ddf287-24e8-4866-866e-e6385bb3dd7e)

my azure open ai studio's settings :
![3](https://github.com/OpenDevin/OpenDevin/assets/15046431/60e66188-8423-4a0a-b960-a5792ab06f50)

**Comment by enyst** [comment]
Ah, I see the problem. Please make a .env file in the project directory, and add it there. Same for LLM_API_VERSION.

**Comment by rbren** [comment]
Should be fixed by https://github.com/OpenDevin/OpenDevin/pull/1005

Let us know if not!
