### ISSUE TITLE
Afer "make run"，it seems alright till runing into the  error "Bus error Makefile:120: recipe for target 'run' failed make: *** [run] Error 135 "

### ISSUE THREAD

**Issue by LeoYoungChina** [OpenDevin/OpenDevin#972]
building is ok ,then i hit make run :
![image](https://github.com/OpenDevin/OpenDevin/assets/15046431/655ab123-3b4b-4d98-a371-24bd04cad284)

**Comment by aichiyudemiaomiao** [comment]
hi，How did you deal with “ ERROR:root:<class 'OSError'>: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like BAAI/bge-small-en-v1.5 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.”

**Comment by enyst** [comment]
@LeoYoungChina What if you try, in two different terminals: in one, ```make start-backend``` and the other ```make start-frontend```.

**Comment by LeoYoungChina** [comment]
> hi，How did you deal with “ ERROR:root:<class 'OSError'>: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like BAAI/bge-small-en-v1.5 is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at '[https://huggingface.co/docs/transformers/installation#offline-mode'.”](https://huggingface.co/docs/transformers/installation#offline-mode'.%E2%80%9D)

i dont deal with it , so i trun to get a azure openai studio key

**Comment by LeoYoungChina** [comment]
> @LeoYoungChina What if you try, in two different terminals: in one, `make start-backend` and the other `make start-frontend`.

so i tried with two terminals, still facing the same error:
![image](https://github.com/OpenDevin/OpenDevin/assets/15046431/219af11c-bc66-4c15-8f05-39210136b90c)

then i sudo make run , getting the npm is not found ,but i surely can print the version of npm out below. so confusing :
![image](https://github.com/OpenDevin/OpenDevin/assets/15046431/945bb59e-eaf1-4fa8-b54f-753919a877b0)

**Comment by LeoYoungChina** [comment]
i am running it up guys 
![1](https://github.com/OpenDevin/OpenDevin/assets/15046431/e5fe3488-f22f-477d-9f99-d86356be74db)

**Comment by LeoYoungChina** [comment]
> i am running it up guys ![1](https://private-user-images.githubusercontent.com/15046431/321826278-e5fe3488-f22f-477d-9f99-d86356be74db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODUyMDUsIm5iZiI6MTcxMjg4NDkwNSwicGF0aCI6Ii8xNTA0NjQzMS8zMjE4MjYyNzgtZTVmZTM0ODgtZjIyZi00NzdkLTlmOTktZDg2MzU2YmU3NGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAxMjE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMzJkOTk0MzRmMzQxZTljYzA0YmNkNzQyNWU1NWRkZmM0Mjk2M2U5MDZjZjczZDcyN2YxZjc3MmZiNWUzOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y2uFoaa1T_-bGu4O5bsmLujiEpDaBSoVvkC1hA63Osg)

but it looks like i got something wrong with it , trying to fix it up~

it requires root as login user rather other accounts

**Comment by rbren** [comment]
Looks like this issue is solved at least. @LeoYoungChina can you say more about how you got it running?

And can you open a new issue with more details for the "it requires root as login user" problem?
