### ISSUE TITLE
litellm error

### ISSUE THREAD

**Issue by MrPowerX95** [OpenDevin/OpenDevin#973]
when i run this cmd - uvicorn opendevin.server.listen:app --port 3000

show error modulenotfounderror: litellm

then i install litellm then again i run 
uvicorn opendevin.server.listen:app --port 3000
show same error

**Comment by wenxiaoyu** [comment]
me to

**Comment by a775189488** [comment]
why not use `make build&make run` to start?

**Comment by enyst** [comment]
Yes, please use the make commands as listed in the README.

**Comment by neubig** [comment]
Yes, could you please use the `make` commands as in the readme? I'll close this for now, but if you still encounter errors after using `make` then please feel free to open a new issue!
