### ISSUE TITLE
Unterminated string literal

### ISSUE THREAD

**Issue by wenxiaoyu** [OpenDevin/OpenDevin#975]
Error: Build failed with 1 error:
node_modules/@xterm/xterm/lib/xterm.js.map:1:600558: ERROR: Unterminated string literal
    at failureErrorWithLog (/Users/wenxiaoyu/workspace/xiaopeng/code/OpenDevin/frontend/node_modules/esbuild/lib/main.js:1651:15)
    at /Users/wenxiaoyu/workspace/xiaopeng/code/OpenDevin/frontend/node_modules/esbuild/lib/main.js:1059:25
    at /Users/wenxiaoyu/workspace/xiaopeng/code/OpenDevin/frontend/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v18.17.1
make: *** [run] Error 1

**Comment by enyst** [comment]
Can you try: cd to ./frontend folder, ```npm install``` ?

**Comment by rbren** [comment]
`cd frontend && rm -rf node_modules && npm install` might help too

**Comment by rbren** [comment]
This should be fixed with docker
