### ISSUE TITLE
Git fetch and Git Pull does not work

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#980]
(base) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ git fetch
fatal: unable to access 'https://github.com/OpenDevin/OpenDevin.git/': Failed to connect to github.com port 443 after 132973 ms: Connection timed out
(base) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$ git pull
fatal: unable to access 'https://github.com/OpenDevin/OpenDevin.git/': Failed to connect to github.com port 443 after 131599 ms: Connection timed out
(base) pierre@Pierruno:/mnt/c/Users/pierr/OpenDevin$

Bug Template did not fit this issue

**Comment by foragerr** [comment]
Is this the agent trying to connect to GitHub? 
or you trying to fetch/pull on your local box?

If it's the later, you seem to have some sort of network connectivity issues, it's unclear to me how that's related to OpenDevin.

**Comment by foragerr** [comment]
> related to Github

Exactly. Which is not something OpenDevin folks can help with. Try GitHub support perhaps.

**Comment by PierrunoYT** [comment]
Fixed after restarting PC
