### ISSUE TITLE
Create Bug Form in YAML

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#981]
**What problem or use case are you trying to solve?**
It would be cool if there is a Bug Template with Boxes where you can just fill out the issue like copy paste it in the fields.

**Describe the UX of the solution you'd like**
Create Bug Template in YAML

**Do you have thoughts on the technical implementation?**
Follow this https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Describe alternatives you've considered**

**Additional context**

**Comment by foragerr** [comment]
Yes, please.

@rbren is there a process to request higher access to the repo?
Access to close issues, or Access to make chances of the type asked in this thread?

**Comment by rbren** [comment]
@foragerr what is your name in Slack?

**Comment by rbren** [comment]
@PierrunoYT we've got templates--that's what you used to make this issue 😄 

But we could use the form functionality to make it even simpler

**Comment by foragerr** [comment]
I'm not in slack yet :(
I filled the slack form something like 2 weeks ago now.

I'm foragerr@gmail.com if that helps.

**Comment by PierrunoYT** [comment]
> @PierrunoYT we've got templates--that's what you used to make this issue 😄
> 
> But we could use the form functionality to make it even simpler

Yeah but I mean you can configure it so there are field boxes where you can copy paste. I needed to ask AI how to fill the Template.

**Comment by rbren** [comment]
@PierrunoYT you might be able to use OpenAI/OpenDevin to convert the existing issue template (in the .github folder) into an issue form

**Comment by enyst** [comment]
Fixed by https://github.com/OpenDevin/OpenDevin/pull/1243
