### ISSUE TITLE
Could not establish connection to host

### ISSUE THREAD

**Issue by DXLgpt** [OpenDevin/OpenDevin#982]
#### Describe the bug

can not connect the agent
![F2C0{VPKT%`Q)FHLCLU{%F4](https://github.com/OpenDevin/OpenDevin/assets/155650456/667b2beb-1cb7-49c3-8b6c-4158b0649ee1)
![1WG%7@Z1R9JH5C51~3~Y7FJ](https://github.com/OpenDevin/OpenDevin/assets/155650456/76c20523-6ba2-4fa0-a024-31bb27b9ac5e)

#### Setup and configuration
**Current version**:#941

WSL2+ubuntu

####DOCKER:
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
bce3d286af8a ghcr.io/opendevin/sandbox "/usr/sbin/sshd -D -…" 2 minutes ago Up 2 minutes sandbox-a802f37d-0483-4d24-ab6d

####**Commands I ran to install and run OpenDevin**:
1.make build
2.make setup-config
3.make run

####**Steps to Reproduce**:
1.make build by #941 
2.make setup-config(GPT3.5+openai+workspace)
3.make run
4.o+enter

####**Logs, error messages, and screenshots**:

05:51:11 - opendevin:ERROR: manager.py:134 - Error creating controller.
Traceback (most recent call last):
File "/mnt/f/1Coding/OpenDevin/opendevin/server/agent/manager.py", line 125, in create_controller
self.controller = AgentController(
^^^^^^^^^^^^^^^^
File "/mnt/f/1Coding/OpenDevin/opendevin/controller/agent_controller.py", line 86, in init
self.command_manager = CommandManager(
^^^^^^^^^^^^^^^
File "/mnt/f/1Coding/OpenDevin/opendevin/controller/command_manager.py", line 14, in init
self.shell = DockerInteractive(
^^^^^^^^^^^^^^^^^^
File "/mnt/f/1Coding/OpenDevin/opendevin/sandbox/sandbox.py", line 139, in init
self.start_ssh_session()
File "/mnt/f/1Coding/OpenDevin/opendevin/sandbox/sandbox.py", line 213, in start_ssh_session
self.ssh.login(hostname, username, self._ssh_password, port=2222)
File "/home/dxliu/.cache/pypoetry/virtualenvs/opendevin-8axCXPJN-py3.11/lib/python3.11/site-packages/pexpect/pxssh.py", line 424, in login
raise ExceptionPxssh('Could not establish connection to host')
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host

**Comment by DXLgpt** [comment]
> Does the console show you a password you can try to connect with, directly, just to see if it works? It should be a message saying to connect with ssh -v -p opendevin@localhost, I think.控制台是否会向您显示一个密码，您可以尝试直接连接，只是为了看看它是否有效？我想，这应该是一条消息，说要与 ssh -v -p opendevin@localhost 连接。



> Does the console show you a password you can try to connect with, directly, just to see if it works? It should be a message saying to connect with ssh -v -p opendevin@localhost, I think.

there isn't any password show me...

**Comment by rbren** [comment]
Should be fixed by https://github.com/OpenDevin/OpenDevin/pull/983, if you add `SANDBOX_TYPE=exec` to your config.toml

**Comment by rbren** [comment]
#983 is merged now--try adding `SANDBOX_TYPE=exec` to your config.toml

**Comment by DXLgpt** [comment]
> OK, even without password, if you try `ssh -v -p 2222 opendevin@localhost` what happens? Paste it here for some random password.

(opendevin-py3.11) dxl@WIN-EJOAN8:/mnt/f/1Coding/OpenDevin$ ssh -v -p 2222 opendevin@localhost
OpenSSH_8.9p1 Ubuntu-3ubuntu0.4, OpenSSL 3.0.2 15 Mar 2022
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to localhost [127.0.0.1] port 2222.
debug1: connect to address 127.0.0.1 port 2222: Connection refused
ssh: connect to host localhost port 2222: Connection refused

**Comment by DXLgpt** [comment]
> #983 is merged now--try adding `SANDBOX_TYPE=exec` to your config.toml

it's working, but find out another issue.
thank you

**Comment by DXLgpt** [comment]
https://github.com/OpenDevin/OpenDevin/pull/983 is merged now--try adding SANDBOX_TYPE=exec to your config.toml

This is working.

**Comment by katmai** [comment]
seems something else got broken. with the latest commit:

```
atlas@chia01:~$ make run
Running OpenDevin via CLI...
/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_list" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_group_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/toml/decoder.py", line 737, in load_line
    raise ValueError("Invalid date or number")
ValueError: Invalid date or number

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/atlas/OpenDevin/opendevin/main.py", line 6, in <module>
    import agenthub  # noqa F401 (we import this to get the agents registered)
    ^^^^^^^^^^^^^^^
  File "/home/atlas/OpenDevin/agenthub/__init__.py", line 5, in <module>
    from . import monologue_agent # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atlas/OpenDevin/agenthub/monologue_agent/__init__.py", line 1, in <module>
    from opendevin.agent import Agent
  File "/home/atlas/OpenDevin/opendevin/agent.py", line 7, in <module>
    from opendevin.llm.llm import LLM
  File "/home/atlas/OpenDevin/opendevin/llm/llm.py", line 5, in <module>
    from opendevin import config
  File "/home/atlas/OpenDevin/opendevin/config.py", line 35, in <module>
    tomlConfig = toml.loads(config_str)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Invalid date or number (line 6 column 1 char 157)
make: *** [Makefile:26: run] Error 1
```

can't test this fix above.

**Comment by katmai** [comment]
SANDBOX_TYPE="exec"

don't forget the quotes

**Comment by katmai** [comment]
> #983 is merged now--try adding `SANDBOX_TYPE=exec` to your config.toml

however with this implementation i notice that the line that output the ssh connect string and the password is now missing.

**Comment by enyst** [comment]
> > #983 is merged now--try adding `SANDBOX_TYPE=exec` to your config.toml
> 
> however with this implementation i notice that the line that output the ssh connect string and the password is now missing.

You're right, and it's because it doesn't try to ssh anymore, if you choose "exec". I mean, we have two options now: you can choose "exec" or "ssh". So if you choose exec, then it's the old style sandbox, which isn't connected via ssh.

**Comment by Anujh23** [comment]
Oops. Something went wrong: Error code: 400 - {'error': {'code': 'OperationNotSupported', 'message': 'The embeddings operation does not work with the specified model, gpt-35-turbo. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.'}}

**Comment by enyst** [comment]
@Anujh23 can you please check the deployment name as documented here: https://github.com/OpenDevin/OpenDevin/blob/main/docs/documentation/AZURE_LLM_GUIDE.md#2-embeddings

It sounds like you're using a "deployment" defined in Azure for gpt-35, but this parameter needs an embeddings deployment.
