### ISSUE TITLE
Enable --host exposure to bind port to network so can be reacheable from outside

### ISSUE THREAD

**Issue by alanreynosov** [OpenDevin/OpenDevin#989]
**What problem or use case are you trying to solve?**
To enable exposure of service to be callable from outside running machine

**Describe the UX of the solution you'd like**
Add additional flag for `make run` command 

**Do you have thoughts on the technical implementation?**
Currently I've added this flag for npm server to Makefile

https://github.com/OpenDevin/OpenDevin/blob/main/Makefile#L131

**Describe alternatives you've considered**
To add --host flat to npm run start

![imagen](https://github.com/OpenDevin/OpenDevin/assets/672235/5cc0a638-1659-4bcd-8220-8eb74a962b7c)

**Additional context**
Result

![imagen](https://github.com/OpenDevin/OpenDevin/assets/672235/c50c63c4-c459-40d5-b189-a06444e9ebb2)
![imagen](https://github.com/OpenDevin/OpenDevin/assets/672235/82cac833-b8a8-40c1-9644-abd1813480a1)

**Comment by rbren** [comment]
I hit this too. Hopefully it goes away when we get Docker as our main deploy method, but let's leave it open for now

**Comment by rbren** [comment]
Should be fixed with the new docker installation method!
