### ISSUE TITLE
Trying to run a local ollama with llama2

### ISSUE THREAD

**Issue by suoko** [OpenDevin/OpenDevin#990]
Both "make start-backend" and "make start-frontend" are apparently working fine, ollama is running in the same server and is reachable from external (I added 'Environment="OLLAMA_HOST=0.0.0.0"' to ollama service), however I receive no reply from devin
How can I debut it ?

![image](https://github.com/OpenDevin/OpenDevin/assets/3659980/1e60ac7f-42f9-4a0c-a842-4db66bfaa6d3)

This is the config.toml

```
LLM_MODEL="ollama/llama2"
LLM_API_KEY="11111111111111111111"
LLM_EMBEDDING_MODEL="llama2"
LLM_BASE_URL="http://localhost:11434"
WORKSPACE_DIR="./workspace"
```

Backend shows:
```
INFO:     127.0.0.1:40684 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:40672 - "GET /configurations HTTP/1.1" 200 OK
INFO:     127.0.0.1:36836 - "GET /messages/total HTTP/1.1" 200 OK
INFO:     127.0.0.1:36844 - "GET /configurations HTTP/1.1" 200 OK
17:22:29 - opendevin:INFO: sandbox.py:119 - Using workspace directory: /opt/dev/OpenDevin.new/workspace
17:22:30 - opendevin:INFO: sandbox.py:210 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 2222 opendevin@localhost` with the password '7d1d1cef-7b38-4071-9b51-97b853a62904' and report the issue on GitHub.
17:22:31 - opendevin:INFO: sandbox.py:119 - Using workspace directory: /opt/dev/OpenDevin.new/workspace
17:22:31 - opendevin:INFO: sandbox.py:210 - Connecting to opendevin@localhost via ssh. If you encounter any issues, you can try `ssh -v -p 2222 opendevin@localhost` with the password '9b9651d1-a8f9-42d5-a934-77f4bf8686c7' and report the issue on GitHub.


==============
STEP 0

PLAN:
hi
```
Frontend shows:
```
> opendevin-frontend@0.1.0 start
> vite


  VITE v5.2.8  ready in 316 ms

  ➜  Local:   http://localhost:3001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
```

**Comment by rbren** [comment]
@suoko have you checked out these docs? https://github.com/OpenDevin/OpenDevin/blob/main/docs/documentation/LOCAL_LLM_GUIDE.md

**Comment by suoko** [comment]
@rbren  thanks
I should have solved using this

LLM_API_KEY="ollama"
LLM_MODEL="ollama/llama2:latest"
LLM_EMBEDDING_MODEL="local"
LLM_BASE_URL="http://localhost:11434"
WORKSPACE_DIR="./workspace"

**Comment by neubig** [comment]
Looks like this is solved, but please re-open if not!

**Comment by suoko** [comment]
> @suoko have you checked out these docs? https://github.com/OpenDevin/OpenDevin/blob/main/docs/documentation/LOCAL_LLM_GUIDE.md

do you know by chance why I miss code editor and planner tabs ?

**Comment by rbren** [comment]
The planner tab is not implemented currently, but the editor should be there!
