### ISSUE TITLE
What is the exact system that you ran this on? I'm getting a bunch of version issues with mac or ubuntu. 

### ISSUE THREAD

**Issue by BradleyBoldt** [OpenDevin/OpenDevin#991]
Just trying to test this out but cant get it on mac due to docker socket issues and running into sqlite3 issues with python on ubuntu

**Comment by enyst** [comment]
Please see the README on docker socket, section Requirements: https://github.com/OpenDevin/OpenDevin?tab=readme-ov-file#1-requirements

The dev machines include at least Mac and Ubuntu. How have you installed the project and what are the versions of the requirements?

**Comment by BradleyBoldt** [comment]
I got it working using conda environment in Ubuntu 22. combination of these directions and the make commands. Very cool so far! https://www.fahdmirza.com/2024/03/how-to-install-opendevin-locally.html

**Comment by enyst** [comment]
Good to hear! I'll close this issue, but if you experience problems you need help with, feel free to open another and fill in the template.
