### ISSUE TITLE
After running `make build` and `make run` commands for the OpenDevin application, an infinite loop occurs due to permission issues while installing npm and Node.js dependencies.

### ISSUE THREAD

**Issue by PierrunoYT** [OpenDevin/OpenDevin#992]
## Bug Description
After running `make build` and `make run` commands for the OpenDevin application, an infinite loop occurs due to permission issues while installing npm and Node.js dependencies.

## Setup and Configuration
**Current Version**:

```bash
commit b2de79ae0863ed49c67c8121fb1d40249d00c06d (HEAD -> main, origin/main, origin/HEAD)
Author: Leo <ifuryst@gmail.com>
Date:   Thu Apr 11 00:10:58 2024 +0800

    Feat add toast (#951)

    * feat: add agent status bar.

    * fix: ws will reconnect after failed in first time.

    * update: delete useless codes.

    * feat: add toast
```

**My config.toml and environment vars** (be sure to redact API keys):
```toml
LLM_MODEL="gpt-4-0125-preview"
LLM_API_KEY="XYZ"
WORKSPACE_DIR="./workspace"
```

**My model and agent** (you can see these settings in the UI):
* Model: 
* Agent:

**Commands I ran to install and run OpenDevin**:
```
make build
make run
```

## Steps to Reproduce
1. Run `make build` to build the OpenDevin application
2. Run `make run` to start the application

## Additional Context
- The issue occurred after running `make build` and `make run` commands for the OpenDevin application.
- An infinite loop was encountered due to permission issues while installing npm and Node.js dependencies.
- The latest commit from April 11, 2024, at 00:10:58 is being used.
- The commit includes features such as adding an agent status bar, fixing WebSocket reconnection issues, deleting useless code, and adding a toast feature.
- The screenshot of the issue is no longer available.
- More information is needed to identify the exact nature of the permission issues and troubleshoot the problem effectively.

**Comment by rbren** [comment]
Closing in favor of https://github.com/OpenDevin/OpenDevin/issues/326

Please search for existing issues before creating new ones 😄

**Comment by rbren** [comment]
Actually--where is the infinite loop? Is it when you're running a task?

**Comment by PierrunoYT** [comment]
> Actually--where is the infinite loop? Is it when you're running a task?

It just talk that it can't create it and and says it need to tell me how to run it manually and it spins around. I think after sometimes it stopped but there was no readme how to run it manually neither the problem was fixed. I thought I have taken a screenshot but I could not find it.

**Comment by rbren** [comment]
OK yeah sounds indeed like #326
